### ISSUE TITLE
deprecation warning provoked by import imp

### ISSUE THREAD

**Issue by cknoll** [davidhalter/jedi#1001]
This is the version which is installed (using pip from a conda env)

     In [3]: jedi.__version__
     Out[3]: '0.11.0'

I get the following deprecation warning:

    21:30 $ python
    Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
    [GCC 7.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import warnings
    >>> warnings.simplefilter('error')
    >>> import jedi
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/ck/miniconda3/lib/python3.6/site-packages/jedi/__init__.py", line 41, in <module>
        from jedi.api import Script, Interpreter, set_debug_function, \
    File "/home/ck/miniconda3/lib/python3.6/site-packages/jedi/api/__init__.py", line 19, in <module>
        from jedi.parser_utils import get_executable_nodes, get_statement_of_position
    File "/home/ck/miniconda3/lib/python3.6/site-packages/jedi/parser_utils.py", line 4, in <module>
        from jedi._compatibility import literal_eval, is_py3
    File "/home/ck/miniconda3/lib/python3.6/site-packages/jedi/_compatibility.py", line 6, in <module>
        import imp
    File "/home/ck/miniconda3/lib/python3.6/imp.py", line 33, in <module>
        DeprecationWarning, stacklevel=2)
    DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

I think that is not intended and should be easy to fix

**Comment by davidhalter** [comment]
Should I just catch the warning and ignore it? I don't deal with warnings very often. What's your advice?

We still use imp for Python 2 compatibility and `imp.get_suffixes`.

**Comment by cknoll** [comment]
I think the cleanest way would be to distinguish between python3 and python2 at this place.

    if sys.version_info.major >= 3:
        import importlib
        # ....
    else:
        import imp
        # ...


Actively ignoring deprecation warnings is imho not a good idea because things will probably break in the future.

**Comment by davidhalter** [comment]
Well, it's not a problem if they break and you have tests ;-) Seriously, it's never that black and white. Of course there will be an import error in Python 4.0 or so, but the CI will notice that.

However since this probably annoys some people I changed it for the better.
