### ISSUE TITLE
Does Jedi have import hints?

### ISSUE THREAD

**Issue by assumptionsoup** [davidhalter/jedi#1007]
I'm using [this qt shim](https://github.com/mottosso/Qt.py) like so:
```
from qt import QtCore, QtGui, QtWidgets
```
But Jedi can't auto-complete this import.  It can auto-complete with this import:
```
from PySide2 import QtCore, QtGui, QtWidgets
```
Is there any way I hint to Jedi, "Please use PySide2, even though it looks like I'm using something else?"  Something like...
```
from qt import QtCore, QtGui, QtWidgets
# jedi_import: from PySide2 import QtCore, QtGui, QtWidgets
```
I looked through the docs, but I wasn't seeing anything jump out.

**Comment by davidhalter** [comment]
Sorry Jedi doesn't have something like that and I'm also not planning to add that. If anything we would probably want to improve completions for a specific library (because this is not something that gets asked for at all).
