### ISSUE TITLE
Keywords not being completed in some cases on 0.11.0 or above

### ISSUE THREAD

**Issue by red8012** [davidhalter/jedi#1009]
On 0.10.0, `jedi.Script('def a():\n    pa').completions()` gives `[<Completion: pass>]` as expected.
However, on 0.11.0 or newer, it gives no completion `[]`.

**Comment by davidhalter** [comment]
Works on master again. No idea when it was fixed, but it's been like a thousand commits (ok I counted, 423), since then.

Thanks for the report. Let me know if something breaks again!
