### ISSUE TITLE
Can not complete lib-dynload module

### ISSUE THREAD

**Issue by bstaint** [davidhalter/jedi#1013]
Windows msys2 Python3 env,  such as cmath,binascii module can not complete.
call jedi#enable_debugging output:

> speed: init 0.0
> speed: init 0.0
> speed: completions start 0.0
>  dbg: eval_element <Name: cmath@3,0>@(3, 0)
>   dbg: finder.filter_name "'cmath'" in (<ModuleContext: 1@1-4>): [<TreeNameDefinition: cmath@(1, 7)>]@(3, 0)
>   speed: import (<Name: cmath@1,7>,) 1.1350648403167725
>   dbg: search_module 'cmath' in 'E:\\Downloads\\1.py'
>   warning: Module 'cmath-cpython-36m' not importable in path 'D:\\Develop\\msys32\\mingw32\\lib\\python3.6\\lib-dynload\\cmath-cpython-36m.dll'.
>   dbg: finder._names_to_types: [<TreeNameDefinition: cmath@(1, 7)>] -> ContextSet()
> dbg: trailer completion contexts: ContextSet()
> speed: completions end 1.1690666675567627

I think jedi\jedi\evaluate\compiled\__init__.py, line 455 dotted_path should not contain `-cpython-36m`

**Comment by davidhalter** [comment]
Are you sure that these modules actually are importable and can you tell me what paths they exist under?

I have never seen something like this before and `-cpython-36m` is one of the allowed suffixes for your Python version.

For me it would be:
```
>>> imp.get_suffixes()
[('.cpython-35m-x86_64-linux-gnu.so', 'rb', 3), ('.abi3.so', 'rb', 3), ('.so', 'rb', 3), ('.py', 'r', 1), ('.pyc', 'rb', 2)]
```

**Comment by bstaint** [comment]
I used msys2 with python:
```
[/e/Downloads]$ python3
Python 3.6.4 (default, Dec 21 2017, 10:44:07)  [GCC 7.2.0 32 bit] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cmath; print(cmath.__file__)
D:/Develop/msys32/mingw32/lib/python3.6/lib-dynload\cmath-cpython-36m.dll
>>> import imp
>>> imp.get_suffixes()
[('-cpython-36m.dll', 'rb', 3), ('-abi3.dll', 'rb', 3), ('.cp36.pyd', 'rb', 3), ('.pyd', 'rb', 3), ('.py', 'r', 1), ('.pyw', 'r', 1), ('.pyc', 'rb', 2)]
>>>
```

**Comment by davidhalter** [comment]
Ohhh, now I understand your issue. It should actually not contain `-cpython-36m`. Sorry. I should learn how to read.

I guess I understand... Not sure how this really happens. But thank you for the report.

**Comment by davidhalter** [comment]
I think I fixed this, because the import logic for builtin modules is not so complicated anymore. Please test and let me know if it works. I cannot reproduce this case on my machines.

**Comment by bstaint** [comment]
It works, thx.
