### ISSUE TITLE
Support completion for NewType "instances"

### ISSUE THREAD

**Issue by mwchase** [davidhalter/jedi#1015]
The `typing` module has a lightweight "NewType" function. From a PEP 484 perspective, the result of
```
MyType = NewType('MyType', int)
```
is a subclass of int, that has a constructor like
```
MyType(5) # typechecks as MyType, is an int at runtime
```
I believe the text editors I've checked have recent versions of Jedi, and they seem to be operating on the runtime behavior of "NewTypes":
```
MyType(5). # has int methods in completion dropdown

def test_func(int_arg: int, nt_arg: MyType):
    int_arg. # int methods in dropdown
    nt_arg. # no int methods in dropdown
```
I'd like variables annotated with a NewType value to have completion behavior as if they were just the underlying type (which is stored in the "type"'s `__supertype__` attribute, if that's relevant/helpful).

I would have put together a pull request, but I don't understand jedi's code well enough.

**Comment by davidhalter** [comment]
If anybody wants to help with this, most of the details are hidden in evaluate/pep0484.py and evaluate/jedi_typing.py.

The latter is statically analyzed by jedi to generate types. A very simple implementation would be something like

```
def NewType(string, type_):
    return type_
```

However that would just work with int/str and a few others and is not generally the right way to do this. If you actually want to do this the right way you have to play with contexts.

**Comment by mwchase** [comment]
I'm messing around with this, and I'm trying to get a sense of what's consistent with Jedi's existing behavior, and how I want to do things.

Looking at some of the tests, it looks like typing information "wins" over even trivial analysis, so we'd want something like
```
ANewType('ANewType', int)
y = ANewType(ANYTHING AT ALL)
#? ANewType()
y
#? ["to_bytes"]
y.t
```
And that the NewTypeContext would forward much of the documentation, as well as instance resolution, to the underlying ClassContext, while possibly including the name in it, somewhere.

Is that the right way of thinking about and approaching this?

**Comment by davidhalter** [comment]
I'm pretty sure you're right. Generally speaking we want a new `MyType` Context that gives you 

I have just reread some parts of PEP 484 that are related to what you want to achieve. It looks like your approach sounds good.

> And that the NewTypeContext would forward much of the documentation, as well as instance resolution, to the underlying ClassContext, while possibly including the name in it, somewhere.

That sounds pretty good. You could even think about adding something like `__getattr__` or `__getattribute__` on the context and redirect some calls. I'm not sure if I have to create something like a proxy object anyway in the future.

Just to clarify, my example above was pretty bad. I guess playing with contexts would result in something much nicer.

**Comment by mwchase** [comment]
I started working on this, and then mostly didn't. Would it make sense for me to start over on the typeshed branch?

**Comment by davidhalter** [comment]
Yes. The typeshed branch changed almost everything:

 110 files changed, 5317 insertions(+), 2830 deletions(-)

**Comment by mwchase** [comment]
I haven't made much progress since I started back up, because I don't really understand the code yet. Here's what I have so far, in case I've managed to be wrong about the stuff I think I'm right about:

The `jedi.evaluate.gradual.typing` module handles special-casing behavior for the functions and types in the `typing` stdlib module. Therefore, changes to support NewType should be made there.

The broad strokes of the changes are: there need to be new contexts for the output of the NewType function, and *I think* the NewType function itself. This latter context is instantiated by `TypingModuleName._remap` when the name is "NewType".

It's at this point that I get too uncertain to continue speculating about implementation, beyond the fact that `py__call__` methods need to be defined.

**Comment by davidhalter** [comment]
You're pretty much right, until you're uncertain :)

I'm also a bit uncertain, so I might be wrong as well. If I were you I would start writing tests in `test/completion/pep0484*`.

We should probaby return a context similar to `OverloadFunction`.

```
class NewTypeFunction(_BaseTypingContext):
    def py__call__(self, arguments):
        return ContextSet(NewType(evaluator, contextualized_node.parent_context, contextualized_node.node, type_context_set) for contextualized_node in arguments.get_calling_nodes())

# Not sure if this should be a class and have ClassMixin, but we can just keep it like this I guess?
class NewType(Context):
    def __init__(self, evaluator, parent_context, tree_node, type_context_set):
        super(NewType, self).__init__(evaluator, parent_context)
        self._type_context_set = type_context_set
        self.tree_node = tree_node

    def py__call__(self, arguments):
        return self._type_context_set
````

This is all quite ugly, with long lines etc. I just wrote this, because it's probably something in that direction. It at least shouldn't be much more complex. The get_calling_nodes is there to use it as a goto point. That's what the tree_node is generally about.

Hope this helps :)
