### ISSUE TITLE
Drop support for EOL Python 2.6 and 3.3?

### ISSUE THREAD

**Issue by hugovk** [davidhalter/jedi#1016]
It looks like significant effort is going into maintaining support for EOL Python versions. When they reach EOL that means they're no longer receiving security updates.

![image](https://user-images.githubusercontent.com/1324225/34263159-38b766bc-e677-11e7-918b-54bc889cfff0.png)

https://en.wikipedia.org/wiki/CPython#Version_history

Here's the pip installs for jedi from PyPI for the last month (via `pypinfo --percent --pip --markdown jedi pyversion`).

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.6            |   44.4% |        155,231 |
| 3.5            |   27.5% |         96,124 |
| 3.4            |   22.2% |         77,788 |
| 2.7            |    5.2% |         18,142 |
| 3.7            |    0.4% |          1,559 |
| 3.3            |    0.2% |            800 |
| 2.6            |    0.0% |             30 |
| 3.2            |    0.0% |              5 |

From these numbers, it looks like 2.6 and 3.3 can be safely dropped.

This would allow the code to be modernised and ease the maintenance burden quite a bit.

Thoughts?

**Comment by valentjedi** [comment]
I would say that this is an absolutely beautiful idea. But I'm not that familiar with the Jedi source code, and I can't tell how this will simplify maintenance.

**Comment by hugovk** [comment]
Some of the most recent commits have been to try and wrangle 2.6 and 3.3 into place (eg. https://github.com/davidhalter/jedi/commit/e526cb1ae3c8f58f1bb7c91e8adc4d965f247cc7 and https://github.com/davidhalter/jedi/commit/62915686afa37da21ff42605e5f8b9fd7bcdf6ab).

It would look something like https://github.com/davidhalter/jedi/pull/1017, and some more of https://github.com/adamchainz/flake8-comprehensions/blob/master/README.rst#examples are possible too.

**Comment by davidhalter** [comment]
I'm definitely dropping Python 2.6 in the release that contains the virtualenv branch. Probably not dropping 3.3 though. That's probably going to take another year or at least a few months.

Thanks for the research!

**Comment by hugovk** [comment]
Sounds good. Of the two, there's definitely more benefit in dropping 2.6.

**Comment by davidhalter** [comment]
Closing this one in favor of #1018 and #1019. Thanks for your work!
