### ISSUE TITLE
'test' directory is not properly exclude during build

### ISSUE THREAD

**Issue by david-geiger** [davidhalter/jedi#1024]
Hi,

Since commit b70cef735a3d0fed7d9f46252804675923980c8e jedi doesn't build anymore due to some invalid syntax, to fix this issue and exclude properly 'test' directory I added this patch:

-      packages=find_packages(exclude=['test']),

+      packages=find_packages(exclude=['test', 'test.*']),

http://svnweb.mageia.org/packages/cauldron/python-jedi/current/SOURCES/jedi-0.11.1-properly-exclude-test-directory.patch?view=markup&pathrev=1190629

**Comment by davidhalter** [comment]
That is strange it seems to work for me. What setuptools version are you using?

**Comment by david-geiger** [comment]
On Mageia Cauldron we are using setuptools 36.2.4 release.

**Comment by davidhalter** [comment]
Can you tell me what you executed? `python setup.py sdist`?

**Comment by david-geiger** [comment]
We use the following macros:
%build
%py2_build

%install
%py2_install

That:

%py2_build=
CFLAGS="-O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4" /usr/bin/python2 setup.py  build --executable="/usr/bin/python2 -s" 
  sleep 1

and %py2_install=
CFLAGS="-O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4" /usr/bin/python2 setup.py  install -O1 --skip-build --root /home/david/rpmbuild/BUILDROOT/%{name}-%{version}-%{release}.x86_64

**Comment by davidhalter** [comment]
Sorry I'm not an expert in Python packaging. Why do you use build and not just `python setup.py sdist bdist_wheel`? That's what I do and it seems to work fine.

**Comment by david-geiger** [comment]
Because this is used in our spec file to generate a srpm + rpm package, see:

http://svnweb.mageia.org/packages/cauldron/python-jedi/current/SPECS/python-jedi.spec?view=markup&pathrev=1190629

**Comment by davidhalter** [comment]
I'm just saying that in general you could use one wheel for both Python 2/3. But that might not be possible with your package system.

Thanks for the patience.
