### ISSUE TITLE
Missing api_type with ImplicitNSName / error in __repr__

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1033]
When trying to print a `<ImplicitNSName: vim>` definition, I get this error
(via __repr__):

```
Traceback (most recent call last):
  File ".../jedi-vim/pythonx/jedi_vim.py", line 133, in wrapper
    return func(*args, **kwargs)
  File ".../jedi-vim/pythonx/jedi_vim.py", line 300, in goto
    print(d)
  File ".../jedi-vim/pythonx/jedi/jedi/api/classes.py", line 366, in __repr__
    return "<%s %s>" % (type(self).__name__, self.description)
  File ".../jedi-vim/pythonx/jedi/jedi/api/classes.py", line 523, in description
    typ = self.type
  File ".../jedi-vim/pythonx/jedi/jedi/api/classes.py", line 151, in type
    return self._name.api_type
  File ".../jedi-vim/pythonx/jedi/jedi/evaluate/filters.py", line 48, in api_type
    return self.parent_context.api_type
AttributeError: 'NoneType' object has no attribute 'api_type'
```

1. Should there be a separate `api_type`?
2. Should there be a fallback "unknown", so that `__repr__` would never crash there?

**Comment by blueyed** [comment]
This happens when using jedi-vim's goto on `self._vim` (the `_vim` part): https://github.com/Shougo/deoplete.nvim/blob/a338ca8bbee086cc7b9265ae181f22de86d38491/rplugin/python3/deoplete/deoplete.py#L45

Without the `print(d)` it crashes in `PythonToVimStr`, since `d.module_path` is None (which also applies to `d.column` at least.

Code: https://github.com/davidhalter/jedi-vim/blob/510b1c94e48b226b5ede11b716441ae064fc997e/pythonx/jedi_vim.py#L298

**Comment by blueyed** [comment]
The class names are: `<ImplicitNSName: vim>` and `<ModuleName: neovim@(1, 0)>`.
`definitions` are: `[<Definition unknown-api_type vim>, <Definition module neovim>]`

How does Jedi know that it is the `neovim` module that gets assigned in `Deoplete.__init__` to `self._vim`?!

**Comment by davidhalter** [comment]
> Should there be a separate api_type?

Maybe namespace? What's your opinion?

> Should there be a fallback "unknown", so that __repr__ would never crash there?

This is debatable. I tend to say no, because it's a bug and it needs to be fixed anyway. If you use "unknown", you just hide bugs.

**Comment by blueyed** [comment]
"namespace" makes sense to me, if it does for you.

Can you shed some light on my question:

> How does Jedi know that it is the neovim module that gets assigned in Deoplete.__init__ to self._vim?!

**Comment by davidhalter** [comment]
> How does Jedi know that it is the neovim module that gets assigned in Deoplete.__init__ to self._vim?!

Well, it just checks for executions of `Deoplete`.

I now made so we are using `module` as a name after all, because this is also how Python names it (see commit).

**Comment by davidhalter** [comment]
Ok. I think I got this now :)

The last thing that I corrected was part of jedi-vim. Please check it quickly, I think it makes sense. (It's a very very small commit and I was too lazy to create a PR, sorry ;))

The other commits (jedi) are about not parent_context handling (actually not about the api_type).

**Comment by blueyed** [comment]
Thanks!
Looks good to me.
