### ISSUE TITLE
test/* is installed

### ISSUE THREAD

**Issue by isuruf** [davidhalter/jedi#1035]
From this line https://github.com/davidhalter/jedi/blob/6bab112bb73a5ee879425db216b3a743934694f2/setup.py#L35 I assume that `test` is not supposed to be installed, but it is installed when using `pip install jedi`

**Comment by davidhalter** [comment]
What's in there?

**Comment by isuruf** [comment]
3 folders `completion  test_api  test_evaluate`.
If you download https://pypi.python.org/packages/50/ca/d71f5a427601c98eadabfd73104cacbec8cc230e8416158decf61a48b0c6/jedi-0.11.1-py2.py3-none-any.whl#md5=94b9e5518f5280ec3d595998173c1d19 you can see it

**Comment by davidhalter** [comment]
Hmm I guess 4e52acbf26b6d52e26e757cb04817d17c5464331 fixes this, right? That was not part of 0.11.1.
