### ISSUE TITLE
logout：'import warnings' failed; traceback: 

### ISSUE THREAD

**Issue by ycz0926** [davidhalter/jedi#1036]
hello，the jedi logout`'import warnings' failed; traceback: `,when i use it with emacs's elpy package
env:
python 3.6
img:
![_007](https://user-images.githubusercontent.com/18224691/35493169-58afebcc-04ec-11e8-8790-11e827d243b6.jpg)

**Comment by davidhalter** [comment]
Dude you gotta be a bit more precise ;)

Please attach at least the traceback, a good description would be helpful as well (code used, etc).

**Comment by ycz0926** [comment]
@davidhalter hi，david，the emacs only logout the infomation above whether the debug on or off.
when i open a python txt file and remove the cursor, emacs will output the info, you can get more detail at [here](https://github.com/jorgenschaefer/elpy/issues/1134)

**Comment by ycz0926** [comment]
@davidhalter  but the solution is not suit for me

**Comment by davidhalter** [comment]
Dude, this is not a jedi issue. Don't just open tickets without first investigating. I'm not paid for that. There is probably an issue with your installation. Just trash your computer or everything on it and try again with a clean install :)

No seriously: This is not a jedi bug, if you can reproduce it with jedi calls from Python I'll be happy to reopen.

**Comment by ycz0926** [comment]
@davidhalter  ok :)
