### ISSUE TITLE
goto_definitions with `super().foo()` and same class name goes to current

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1044]
If you have a class `Foo` inheriting from `Foo` (defined in the same file or imported), `goto_definitions` on `super().foo()` in the child method will return the definition of the child method itself, but should return the parent's.

TEST CASE:
```python
source = """
class Foo():
    def foo(self):
        pass


class Foo(Foo):
    def foo(self):
        super().foo()
"""

from jedi.api import Script

s = Script(source, line=len(source.split("\n")))

d = Script(source, line=len(source.split("\n"))-1, column=19).goto_definitions()
d1 = d[0]

assert d1.line == 3, (d1.line, d1.get_line_code(), d1)
```

**Comment by davidhalter** [comment]
A small edge case. Thanks for discovering and reporting it. :)
