### ISSUE TITLE
test is installed

### ISSUE THREAD

**Issue by wimglenn** [davidhalter/jedi#1045]
This distribution trying to create a "test" subdirectory in site-packages and that's causing issues in some CI workflows.

I saw https://github.com/davidhalter/jedi/issues/1035 which was closed, though it doesn't seem to be actually fixed on PyPI yet - jedi is still installing tests in the 0.11.1 distribution.  The names 'completion', 'test_api', and 'test_evaluate' will need to be excluded.

Could you make a new release please?  Thanks!

**Comment by davidhalter** [comment]
There will be a new release pretty soon. The current master branch is unfortunately not as stable as I'd like it to be, yet. So you will just have to wait for maybe one more month.
