### ISSUE TITLE
Doesn't understand within-package namespace imports

### ISSUE THREAD

**Issue by djhogan** [davidhalter/jedi#1050]
For example, it completes functions like exp, log, and arcsinh when I type numpy.core., but the numpy package imports these functions into the numpy namespace. Jedi doesn't seem to understand this. When I type numpy. I don't get these completions.

**Comment by davidhalter** [comment]
That is strange. I just checked and it seems to work for me (both on 0.11.1 and master):

```
>>> jedi.Script('import numpy; numpy.exp').completions()
[<Completion: exp>, <Completion: exp2>, <Completion: expand_dims>, <Completion: expm1>]
>>> jedi.Script('import numpy; numpy.core.exp').completions()
[<Completion: exp>, <Completion: exp2>, <Completion: expm1>]
```

**Comment by davidhalter** [comment]
No answer. Closing. Please give me more specific information if you want this resolved.
