### ISSUE TITLE
Autocompletion missing functions

### ISSUE THREAD

**Issue by NerdsvilleCEO** [davidhalter/jedi#1051]
Hello,
  I am noticing that on packages that are installed w/ pip rather than the stdlib, I don't see all of the method definitions, for example, when getting completion for pytest, I don't see pytest.raises

Example below, last completion I see is pytest.main

![screen shot 2018-02-22 at 7 55 33 am](https://user-images.githubusercontent.com/5251847/36539907-5b88d4fe-17a6-11e8-88ee-5014ecf53f24.png)

**Comment by NerdsvilleCEO** [comment]
Further, in the REPL I see the same

```
>>> source = '''
... import pytest
... pytest.'''
>>> script = jedi.Script(source, 3, len('pytest.'), '')
>>> script.completions()
[<Completion: cmdline>, <Completion: hookimpl>, <Completion: hookspec>, <Completion: main>, <Completion: UsageError>, <Completion: _preloadplugins>, <Completion: __all__>, <Completion: __doc__>, <Completion: __file__>, <Completion: __name__>, <Completion: __package__>, <Completion: __version__>]
```

**Comment by NerdsvilleCEO** [comment]
@davidhalter am I missing something here?

**Comment by davidhalter** [comment]
For me pytest.raises completes.What jedi version/pytest version are you running?

**Comment by NerdsvilleCEO** [comment]
```
appuser@350f3ca30aa3:~$ pip freeze | grep "jedi\|pytest"
jedi==0.11.1
pytest==2.9.2
pytest-bdd==2.18.2
pytest-cov==2.5.1
pytest-django==2.9.1
pytest-django-haystack==0.3.0
pytest-logging==2015.11.4
pytest-ordering==0.5
pytest-pythonpath==0.7.1
appuser@350f3ca30aa3:~$ python --version
Python 2.7.14
```

**Comment by davidhalter** [comment]
Well, just check how things are imported in pytest 2.9.2. It's absolutely impossible to understand that with static analysis. This is one of the cases that is not really fixable. The only way this would ever be fixed is by having a plugin infrastructure in Jedi. But that's still kind of far away.

PS: Just update your pytest version. There have been quite a few fixes and improvements in the last two years. :)

**Comment by NerdsvilleCEO** [comment]
ok thanks @davidhalter 👍 will test

**Comment by NerdsvilleCEO** [comment]
Works, closing this!! :)
