### ISSUE TITLE
Missing types from typing module (PEP484)

### ISSUE THREAD

**Issue by reiv** [davidhalter/jedi#1052]
It looks like there are a few members from the `typing` module that are missing in `jedi_typing.py` which results in no completions being provided for those types. One particular example is `Set[T]` (the generic form of `builtins.set`); currently, this would have to be written as `MutableSet[T]`, which doesn't cover all of the methods that the builtin `set` exposes. Is this omission intentional, and if not, would you be open to a PR that fills in the missing types? I understand that user-defined generics is explicitly [mentioned](https://jedi.readthedocs.io/en/latest/docs/features.html#type-hinting) as one of the tricky ones, but some of the others seem pretty trivial to implement.

**Comment by davidhalter** [comment]
You can obviously PR this. I just think that the fix is non-trivial, because I don't want to duplicate everything in `jedi_typing.py`. Somehow the default should be to use the official typing module, except if there's an entry in `jedi_typing.py`.  This is something that I've recently implemented for builtin objects (like str, list, etc). It's called `jedi.evaluate.filters.BuiltinOverwrite`. Not sure if you could simply use that. But something similar would probably do the trick.

**Comment by davidhalter** [comment]
I just realized that it has nothing to do with what I just wrote.

I have looked at the typing module quickly. I'm not sure if even in typing access to all those functions is intended. It inherits from `AbstractSet[T]`. I don't see where the methods like `pop` would come from. I think that is what we need to understand first.

**Comment by reiv** [comment]
Regarding your comment about not wanting to duplicate everything: so the idea then is to make Jedi smarter by having it inspect the original `typing` module to glean information on how to implement those types rather than defining them "from scratch", so to speak? That does indeed sound a little more complicated and possibly out of my league... could we perhaps use the `jedi_typing.py` approach of "copying" what's in `typing` as a bandaid fix while a more general solution is worked on?

As for where the methods come from, I reckon those are inherited because of the `extra` keyword in the definition of [`typing.MutableSet`](https://github.com/python/cpython/blob/3.6/Lib/typing.py#L1832) which refers to [`collections.abc.MutableSet`](https://github.com/python/cpython/blob/5bf74859fe253f0e8ff73ba699cd1a7e2dfbcea3/Lib/_collections_abc.py#L556), where `pop()` and friends are defined. But [`typing.Set`](https://github.com/python/cpython/blob/3.6/Lib/typing.py#L1895) also inherits from the builtin `set`, so I don't know where it ends up looking. It's all a bit magic because of the liberal use of metaclasses :-)

**Comment by davidhalter** [comment]
Ok. I think I finally understand it. The logic is in `_make_subclasshook` and it's all about the `__subclasshook__`. I'm not really sure how to proceed. I don't want to just hack this. I would actually like to support it in a bit more sophisticated way.

If we're going to make that work we have to check if it's a class defined in the typing module that has an `extra` argument. However to make that work we have to overwrite all the class contexts. You can do this with something like the following code:

```
class OverwrittenTypingClass():
    def __init__(self, typing_class_context):
         self._typing_class_context = typing_class_context

    def get_filters(self):
        for f in filters:
            yield f
        for f in extra_context.get_filters():
            yield f

    def __getattr__(self, name):
         return getattr(self._typing_class_context, name)
```

Now the tricky part is to actually get the extra_context.

**Comment by davidhalter** [comment]
I guess all the types should now be included since typeshed is now a first-class citizen.
