### ISSUE TITLE
Can't complete python3 code when using jedi running on python2

### ISSUE THREAD

**Issue by Csomnia** [davidhalter/jedi#1055]
I try to complete python3 code by adding sys_path when create Script object.
I run this code under python 2.7.12. jedi 0.11.1
`sc = jedi.Script('import htt', 1, len('import htt'), sys_path='/usr/lib/python3.5/')`
`sc.completions()`

[traceback here](https://paste.ubuntu.com/p/bbbJJn6RvB/)

**Comment by davidhalter** [comment]
In Python3 this will be possible with environments. Please test #1053 and report back any issues you will still be having.
