### ISSUE TITLE
Version 0.12 is not on PyPI

### ISSUE THREAD

**Issue by yan12125** [davidhalter/jedi#1061]
As title, the PyPI page still says that 0.11 is the current version: https://pypi.python.org/pypi/jedi

Also, a 0.12 tag is missing: https://github.com/davidhalter/jedi/tags

(I noticed this when looking at the change log https://github.com/davidhalter/jedi/blob/master/CHANGELOG.rst#0120-2018-01-01)

**Comment by davidhalter** [comment]
0.12.0 is in development. It was never released. The only thing that's wrong is that the date is already set in the changelog title. It's obviously wrong.

**Comment by yan12125** [comment]
Thanks for the explanation and sorry for the noise.

2018-03-15 22:14 GMT+08:00 Dave Halter <notifications@github.com>:

**Comment by davidhalter** [comment]
No problem :) Part of it is my fault.
