### ISSUE TITLE
Possible autocomplete types

### ISSUE THREAD

**Issue by Alexey-T** [davidhalter/jedi#1069]
Maybe it’s done, sorry. I want some call which gets list of possible auto completion line kinds, ie —
Func ie def
Class
Var
Module 
Etc..... 
good to see all variants and see if new kind appears.

**Comment by davidhalter** [comment]
Ok. I probably won't implement that call, but we could at least document this better. I agree that currently there is not good enough documentation about this.

**Comment by Alexey-T** [comment]
It’s not hard to add this call and return a list ..

**Comment by davidhalter** [comment]
Yeah, but I don't want it in the API.

**Comment by krassowski** [comment]
I understand that adding an API call is not in scope, but would it be a good idea to add typing annotation, like:

```python
from typing import Literal

NameType = Literal['module', 'class', 'instance', 'function', 'param', 'path', 'keyword', 'statement']

@property
def type(self) -> NameType:
    pass
```

This could help catch some issues downstream.

PS. For future, would prefer me to open new issues, or follow-up in the existing ones like here?

**Comment by krassowski** [comment]
Also, should the documentation include the recently added `namespace` type?

**Comment by davidhalter** [comment]
It should, feel free to create a PR for it. I think both of those things are things that I would just merge :)
