### ISSUE TITLE
`column` parameter is not in a valid range

### ISSUE THREAD

**Issue by bstaint** [davidhalter/jedi#1073]
When line_string contain multi bytes will raise ValueError, `vim.current.window.cursor[1]` not equal `len(line_string)`:

code `jedi\api\__init__.py` line 129:
```
        line_len = len(line_string.encode(encoding))
```
can be fixed it.

**Comment by davidhalter** [comment]
I'm not sure that's what I want. Actually I think people shouldn't really use bytes for code. So maybe jedi-vim has to fix this. Can you open an issue there, please?
