### ISSUE TITLE
Removing "param" from output

### ISSUE THREAD

**Issue by kootenpv** [davidhalter/jedi#1074]
Using Python3.7 and jedi 0.11.1 (also tested older version like 0.10.0), you can see in the image that I get "param" in the output.

![eldoc](https://user-images.githubusercontent.com/2746227/38420673-d57d9c3e-39a4-11e8-9930-8d15c7c096f3.png)

It seems redundant as I've never seen a "non-param". It's not so much a trouble with this example, but long argument lists look pretty bloated.

I looked at emacs/elpy, and it does not seem to originate from there, but from jedi itself.

How can I remove this?

**Comment by kootenpv** [comment]
When I fall back to jedi 0.9.0 it is not there anymore.

**Comment by kootenpv** [comment]
The pull requesst on emacs-jedi did not solve it.

**Comment by davidhalter** [comment]
This will be solved in Jedi once we have a better representation for params in general. In Jedi 0.9.0 the description was just wrong to not include `param`. For now plugin developers just have to deal with this. Probably going to be better in 0.13.0.

**Comment by valignatev** [comment]
What else could it be if not 'param'. I mean, I thought that 'param' is here to disambigue something, but I can't think of something else in call tip.

**Comment by davidhalter** [comment]
The API that people are using is called `description`. It has nothing to do with listing params. It's something that is supposed to be used when using goto_assignments for example. The API that you guys want simply has never existed. :)

**Comment by valignatev** [comment]
Got it, makes sense then :+1:

**Comment by kootenpv** [comment]
Makes sense indeed. Maybe we can persuade Jedi (with a mind trick) that having a `call_signature` method belongs in there as many depending on it would otherwise define it :-)

**Comment by davidhalter** [comment]
There's an API for this now.
