### ISSUE TITLE
Can't complete time.strptime return struct_time class (Implement typing.NamedTuple)

### ISSUE THREAD

**Issue by bstaint** [davidhalter/jedi#1075]
```
import jedi      

print(jedi.Script('import time;a = time.strptime("2018", "%Y");a.').completions())
```
output: []

**Comment by davidhalter** [comment]
Depends on #839. We need to start using typeshed.

**Comment by davidhalter** [comment]
typing.NamedTuple doesn't properly work in Jedi, that's now the problem.

I'm postponing this, because it doesn't seem to be useful for a lot of users for now and preferring other things.

**Comment by davidhalter** [comment]
It is working now.

NamedTuple's are probably supported if you use it like this:

```
class FooBar(NamedTuple):
    foo: int
    bar: int
```

and not like this:
```
FooBar = NamedTuple(
    'FooBar',
    [('foo', int), ('bar', int)]
)
```

The latter implementation is a way to work with Python 2 code, which is almost end of life.
