### ISSUE TITLE
Getting return types from definitions (like Definition().execute())

### ISSUE THREAD

**Issue by ColinKennedy** [davidhalter/jedi#1076]
I'm writing a tool that could greatly benefit from the feature described in this pull request:

https://github.com/davidhalter/jedi/pull/635

Specifically, This is along the lines of what I was expecting

```
import jedi

source = '''
import collections

def my_func(arg1, arg2=collections.OrderedDict()):
    if arg1:
        return False

    return arg2
'''

obj = jedi.names(source)

functions = [definition for definition in jedi.names(source)
             if definition.type == 'function']
function = functions[0]
print(function.return_types)
```

The output of print would be something that could be used to retrieve the return types

```
# Result: [<Definition class bool>, <Definition class OrderedDict>]  #
```

elad661's PR does do this but unfortunately it was not implemented. I've tried going through old commits to see if I can understand the current API and write it myself but I'm having trouble finding the information needed.

If this feature already exists or is doable in the current API, would you please let me know? If not, what might be needed to add it?

**Comment by davidhalter** [comment]
It would actually be extremely easy. I'm just not sure if I want this API at the moment, but maybe in a few months. There's quite a lot of people wishing for a more flexible API.

For a long time I didn't do that, because some parts of the internals were buggy, so new API calls would have meant even more bugs. But now that the internals are fixed, I think we can start tackling these issue. There's also quite a few people wishing for more information about parameters.

**Comment by ColinKennedy** [comment]
I can understand avoiding new features if the foundation isn't quite solid. It is just hard to avoid talking about since Jedi is such a great standard for static analysis.

For the time being, I can probably begin refactoring my tools based on the elad661's repo unless you recommend against it. The fork is a couple years old now, after all. What do you think?

**Comment by davidhalter** [comment]
I would strongly advice you not to do that. Contrary to many other open source project I have been actively working on this one for 15+ hours a week. So the difference should be quite big (v0.9.0 is ~2000 commits ago). If you really just want something you can just use Jedi's internals.

IMO this should do the job (not actually well tested, just out of my head):

```
>>> import jedi
>>> func, = jedi.Script('def x(): return 1\nx').goto_definitions()
>>> func
<Definition def x>
>>> func.type
'function'
>>> func._name.infer().execute_evaluated()
ContextSet(<CompiledObject: 1>)
>>> from jedi.api.classes import Definition
>>> defs = [Definition(func._evaluator, c.name) for c in func._name.infer().execute_evaluated()]
>>> defs[0].name
'int'
>>> defs[0].description
'instance int'
```

So IMO you should just be using something like this and then once we support your request switch to the official API.

**Comment by davidhalter** [comment]
should be working now, please test.
