### ISSUE TITLE
Configure autocomplete to only suggest 'public-facing' symbols

### ISSUE THREAD

**Issue by zhammer** [davidhalter/jedi#1078]
Is there a way to configure Jedi's autocomplete to only suggest 'public-facing' symbols from a module / object? Let's say I import the following ```jedi_test``` module:

```py
"""jedi_test module."""

import json

_PRINT_FMT = 'Your json is: "{}""'

def print_json(val):
    """Print a value as json"""
    print(_PRINT_FMT.val)
```
I would only want ```jedi_test.``` to autocomplete to ```jedi_test.print_json```. This would mirror the behavior of the python interpreter ```help()``` function:
```
Help on module jedi_test:

NAME
    jedi_test - jedi_test module.

FUNCTIONS
    print_json(val)
        Print a value as json

FILE
    /Users/zhammer/code/scrap/jedi_test.py
```
Instead, Jedi autocomplete suggests every symbol in the jedi_test namespace, including all dunder methods (ie ```__doc__```), all underscore-prefixed implementation details (ie ```_PRINT_FMT```) and all imported modules (ie ```json```).

![screen shot 2018-04-07 at 7 03 47 pm](https://user-images.githubusercontent.com/6956487/38461131-70e2991c-3a96-11e8-94f3-8bc48eece5ad.png)

Jedi's [settings documentation](https://jedi.readthedocs.io/en/latest/docs/settings.html) doesn't seem to provide a solution, and I can't find any issues on the matter.

Does anyone know a way to do this? I can't imagine I'm alone in wanting a more concise autocomplete output.

**Comment by davidhalter** [comment]
The problem is that the import is as public as everything else. How would you want to differentiate between an import that you want to complete and another one that you don't want to complete?

**Comment by zhammer** [comment]
I guess the issue with imports is if i'm editing the module that imports a module, I want to have autocomplete for that imported module, but if I'm importing an external module, I don't want to autocomplete to the modules the external module imports.

That being said, filtering out symbols that begin with an underscore seems pretty simple. Is there any built-in pattern omission config? Otherwise I can see if I can play around with the ```emacs``` wrapper to omit suggestions matching ```_*```

**Comment by davidhalter** [comment]
There's nothing to filter those out, because it's just so easy to do that yourself:

[c for c in script.completions() if not c.name.startswith('_')]

For now the editors have to implement that themselves if they need it.

**Comment by dlech** [comment]
> The problem is that the import is as public as everything else. How would you want to differentiate between an import that you want to complete and another one that you don't want to complete?

I don't remember where I saw this (pyright or mypy?) but the solution is to only include names from imports if the `import ... as` name was the same as the import. So `json` from `import json` would not be included in the  completions but `json` from `import json as json` would be included.

**Comment by davidhalter** [comment]
> So json from import json would not be included in the completions but json from import json as json would be included.

This is in general the way how stubs work. I'm pretty sure Jedi also respects that, but in Python files (where people usually do not work like that) all of the names are "public" by default.

> I assume the comments above still apply and jedi has not changed in this regard since 2018?

Correct.

**Comment by dlech** [comment]
Thanks for the clarification.
