### ISSUE TITLE
Exception: There's an issue (XXX != XXX) with the diff parser

### ISSUE THREAD

**Issue by galeo** [davidhalter/jedi#1081]
There are lots of **Exception** errors occurred **randomly** with the diff parser reporting that **"there is an issue (XXX != XXX)..."**

Here is an example file code:
```python
from django import forms
from django.forms.widgets import Textarea

from django_comments.forms import CommentForm
from django_comments.forms import COMMENT_MAX_LENGTH▌# <-- cursor is here
```

**The error log:**
```
Exception("There's an issue (16 != 6) with the diff parser. Please report:
---
+++
@@ -3,14 +3,4 @@

 from django_comments.forms import CommentForm
 from django_comments.forms import COMMENT_MAX_LENGTH
-
-
-
-
-
-
-
-
-
-
 ",)
```
This issue may relate to #1000,  which you recently closed.

Thanks for your great work on this tool!

**Comment by davidhalter** [comment]
Oh wow. Do you see those often? I almost never have those. Can you see a pattern? The problem is that I have a hard time at reproducing those. Once I have a reproduction case it's usually quite easy to fix.

If you have any idea it would be interesting. Or you can also wait for the next release.

There's also the chance that you wait for the next release and see if it's better.

**Comment by galeo** [comment]
I'm using the current development version (master branch) of jedi and parso. Recently I see lots of these errors, but I can't figure out the pattern. I will try to find out how to reproduce this issue. 

Thanks!

**Comment by davidhalter** [comment]
Can you maybe send some code of yours? If you don't want to make it public you can also send it by email. I'm wondering if it has something to do with how you write code and that causes it, because I have only rarely seen issues like this one and many users seem to be fine.

**Comment by alwc** [comment]
I come across the same problem too. Here is a reproducible case:

1. `<leader>g` on [`predict`](https://github.com/fastai/fastai/blob/master/fastai/learner.py#L357)
2. `<leader>g` on [`predict_with_targs_ `](https://github.com/fastai/fastai/blob/master/fastai/model.py#L223)

```
Traceback (most recent call last):
  File "/home/alex/dotfiles/nvim/plugged/jedi-vim/pythonx/jedi_vim.py", line 141, in wrapper
    return func(*args, **kwargs)
  File "/home/alex/dotfiles/nvim/plugged/jedi-vim/pythonx/jedi_vim.py", line 214, in get_script
    environment=get_environment(),
  File "/home/alex/dotfiles/nvim/plugged/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 119, in __init__
    cache_path=settings.cache_directory
  File "/home/alex/dotfiles/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/__init__.py", line 383, in parse_and_get_code
    return self.grammar.parse(code=code, path=path, **kwargs), code
  File "/home/alex/dotfiles/nvim/plugged/jedi-vim/pythonx/parso/parso/grammar.py", line 76, in parse
    return self._parse(code=code, **kwargs)
  File "/home/alex/dotfiles/nvim/plugged/jedi-vim/pythonx/parso/parso/grammar.py", line 126, in _parse
    new_lines=lines
  File "/home/alex/dotfiles/nvim/plugged/jedi-vim/pythonx/parso/parso/python/diff.py", line 163, in update
    % (last_pos, line_length, ''.join(diff))
Exception: There's an issue (284 != 283) with the diff parser. Please report:
---
+++
@@ -280,5 +280,4 @@

     for h in hooks: h.remove()
     return summary
-

Traceback (most recent call last):
  File "/home/alex/dotfiles/nvim/plugged/jedi-vim/pythonx/jedi_vim.py", line 141, in wrapper
    return func(*args, **kwargs)
  File "/home/alex/dotfiles/nvim/plugged/jedi-vim/pythonx/jedi_vim.py", line 305, in goto
    definitions = script.goto_assignments()
AttributeError: 'NoneType' object has no attribute 'goto_assignments'
```

**Comment by davidhalter** [comment]
It looks like https://github.com/davidhalter/jedi/issues/1121 fixed this. I just did a new release. Please test. I'll reopen if it's still an issue.

**Comment by alwc** [comment]
Works fine for now! Thanks!
