### ISSUE TITLE
np.zeros, np.array, etc. not correctly identified

### ISSUE THREAD

**Issue by memeplex** [davidhalter/jedi#1083]
I've observed the following while using jedi-vim but I think it's related to jedi itself:

* `np.zeros` is identified as `module zeros` and no docstring is shown in the preview window.

* The same for `np.array` (and others).

**Comment by davidhalter** [comment]
This is not the case anymore. I'm pretty sure this was related to the speedups for tensorflow, which have since been reverted. #1116.

This means that it's now slower again, but also more precise.
