### ISSUE TITLE
Completion not always working with context managers

### ISSUE THREAD

**Issue by boojum** [davidhalter/jedi#1084]
## Problem summary
Completion not always works with context managers. Picture is worth a thousand words:
https://asciinema.org/a/35sDlmrobGcLVHQiUfBOgTaG2

## Expected
After the `with` statement I expect the completion to work normally. For example, I expect `conn.cursor()` and `c.execute()` to start completion after `conn` and `c`, respectively. This behaviour occurs with `deoplete-jedi` and `ipython` completion, both using `jedi`.

EDIT: tested against `completor.vim` and `jedi-vim`, which produces the same issue.

## Environment Information
OS:
```
uname -r
4.15.15-1-ARCH
```
Neovim version:
```
nvim -v  
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
Minimal init.vim:
```
let s:plugin_manager=expand('~/.local/share/nvim/site/autoload/plug.vim')
let s:plugin_url='https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
if empty(glob(s:plugin_manager))
    echom 'vim-plug not found. Installing...'
    silent exec '!curl -fLo ' . s:plugin_manager . ' --create-dirs ' . s:plugin_url
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.local/share/nvim/plugged')
Plug 'Shougo/deoplete.nvim', {'do': ':UpdateRemotePlugins'}
Plug 'zchee/deoplete-jedi'
call plug#end()

set completeopt=longest,menu

let g:python_host_prog = (expand('$HOME/.config/pyenv/versions/neovim2/bin/python'))
let g:python3_host_prog = (expand('$HOME/.config/pyenv/versions/neovim3/bin/python'))

let g:deoplete#enable_at_startup = 1

let g:jedi#completions_enabled = 1
```

**Comment by davidhalter** [comment]
sqlite3.connect is a builtin function and it's therefore not that easy to get return types for it. I think your best bet is to wait for #839. In that case we will also try to use https://github.com/python/typeshed which will definitely help you!

**Comment by dimaqq** [comment]
@boojum looks like your "picture" got archived and is no longer visible. Would you perhaps update the description with a summary?

**Comment by boojum** [comment]
> @boojum looks like your "picture" got archived and is no longer visible. Would you perhaps update the description with a summary?

Sure thing! I'll test it and update the description this weekend.

**Comment by davidhalter** [comment]
It looks like 

```
import sqlite3

with sqlite3.connect() as c:
    c.
```

doesn't work, because there is no way that Jedi knows what `__enter__` returns in typeshed.

If you look at  `__enter__`, you can see that it's defined like this:

```
    def __enter__(self, *args, **kwargs): ...
```

I guess I'll wait until mypy solves this issue, because I'm pretty sure they also have this issue.
