### ISSUE TITLE
Jedi complete numbers in a strange way

### ISSUE THREAD

**Issue by djangoliv** [davidhalter/jedi#1085]
Jedi compete numbers with `and`, `if`, `in`, `is`, `not` and `or`.
With auto-completion, this behavior is very annoying.

Example with python interpreter:

```
>>> 0
0and  0if   0in   0is   0not  0or   
>>> 2
2and  2if   2in   2is   2not  2or   
>>> 1
1and  1if   1in   1is   1not  1or   
>>> 5
5and  5if   5in   5is   5not  5or   
>>> 5.2
5.2and  5.2if   5.2in   5.2is   5.2not  5.2or   
```

Regards

**Comment by davidhalter** [comment]
These are correct autocompletions. Everything else would be incorrect (except `j`). I don't understand why you want to use autocompletion there.

**Comment by djangoliv** [comment]
I use jedi in Emacs with company-jedi and when I write a number, I have these suggestions. I don't uderstand why (and where) I need to complete `0` to `and` (for example).

**Comment by Yevgnen** [comment]
This annoys me pretty much too... I'm using `elpy` which uses `Jedi` in emacs...

**Comment by linupi** [comment]
I am using jedi through ptpython and there the completion of numbers destroys the signature display of functions with numerical parameters. 

It would be nice to have a switch in the jedi settings to disable the completion of numbers.

**Comment by davidhalter** [comment]
Happy to receive pull requests about this. Probably we should just ignore completions directly after numbers.
