### ISSUE TITLE
Regression between releases `0.10.2` and `0.11.0` via. `ptpython`

### ISSUE THREAD

**Issue by myii** [davidhalter/jedi#1087]
Filed an issue @ https://github.com/jonathanslenders/ptpython/issues/242.

Quoting below:

> #### Proposal
> 
> https://github.com/jonathanslenders/ptpython/blob/da2c5281f60c2d8a92749709219771ffaa84220f/setup.py#L24
> 
> `jedi>=0.9.0',`
> 
> Change this to either:
> 
> * `jedi>=0.9.0,<=0.10.2',`
> * `'jedi>=0.9.0,<0.11.0',`
> 
> This resolves the issues explained below.
> 
> Also resolves jonathanslenders/ptpython#229.
> 
> #### Description of problems
> 
> Encountered a crash when typing the period of `Revision.`, a [django-reversion](https://github.com/etianen/django-reversion) model:
> 
> ```python-traceback
> In [1]: Revision.Exception in thread Thread-429:
> Traceback (most recent call last):
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/cache.py", line 46, in wrapper
>     return getattr(self, name)
> AttributeError: 'MixedName' object has no attribute '_infer'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/evaluate/compiled/access.py", line 120, in wrapper
>     cache[key]
> KeyError: 140232415539440
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File ".../.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File ".../.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 865, in run
>     completions = list(buffer.completer.get_completions(document, complete_event))
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/prompt_toolkit/contrib/regular_languages/completion.py", line 37, in get_completions
>     self._get_completions_for_match(m, complete_event))
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/prompt_toolkit/contrib/regular_languages/completion.py", line 81, in _remove_duplicates
>     for i in items:
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/prompt_toolkit/contrib/regular_languages/completion.py", line 64, in _get_completions_for_match
>     for completion in completer.get_completions(document, complete_event):
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/ptpython/completer.py", line 127, in get_completions
>     completions = script.completions()
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/api/__init__.py", line 174, in completions
>     completions = completion.completions()
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/api/completion.py", line 102, in completions
>     return sorted(completions, key=lambda x: (x.name.startswith('__'),
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/api/completion.py", line 43, in filter_names
>     k = (new.name, new.complete)  # key
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/api/classes.py", line 436, in complete
>     return self._complete(True)
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/api/classes.py", line 406, in _complete
>     if self._name.api_type == 'param' and self._stack is not None:
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/evaluate/compiled/mixed.py", line 90, in api_type
>     return next(iter(self.infer())).api_type
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/cache.py", line 48, in wrapper
>     result = func(self)
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/evaluate/compiled/mixed.py", line 85, in infer
>     _create(self._evaluator, access_handle, parent_context=self.parent_context)
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/evaluate/compiled/access.py", line 125, in wrapper
>     result = func(evaluator, obj, parent_context)
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/evaluate/compiled/mixed.py", line 205, in _create
>     result = _find_syntax_node_name(evaluator, access_handle)
>   File ".../.pyenv/versions/Django_v2.0.x/lib/python3.6/site-packages/jedi/evaluate/compiled/mixed.py", line 197, in _find_syntax_node_name
>     return module_node, names[-1].parent, path, code_lines
> IndexError: list index out of range
> ```
> 
> * While looking for a solution, found issue jonathanslenders/ptpython#229 with a similar traceback
> 
> After restarting `shell_plus`, found further problems with both autocomplete and the documentation popup while typing `User.objects.get(pk=1)`:
> 
> * Autocomplete problem
>     * Autocomplete is displayed after `User.`
>     * But not working after `User.objects.`
> * Documentation popup
>     * Not displayed at `User.objects.get(`
> 
> #### Solution: Downgrading `jedi` to `0.10.2`
> 
> It was obvious that this must have been working at some point in history, so worked through the [release history](https://pypi.org/project/jedi/#history) installing previous versions of `jedi`.  Once I got to `0.10.2`, **everything mentioned above** started working properly.

**Comment by Carreau** [comment]
I may have a similar in 0.12 with the following snippet:

```
ip = get_ipython()
ip._x = 1
ip.Completer.use_jedi=True
ip._hidden_attr = 1
ip._x = {}
c = ip.Completer
from traitlets.config.loader import Config
from IPython.core.completer import (
    Completion, provisionalcompleter, match_dict_keys, _deduplicate_completions)
cfg = Config()
cfg.IPCompleter.omit__names = 0
c.update_config(cfg)
with provisionalcompleter():

    c.use_jedi = True
    completions = set(c.completions('ip.', 3))
```

**Comment by davidhalter** [comment]
The original issue is resolved. I cannot reproduce yours @Carreau. If it's still a problem with these changes, just open a new issue.
