### ISSUE TITLE
Completions not appropriate for enum members

### ISSUE THREAD

**Issue by brettcannon** [davidhalter/jedi#1090]
From Microsoft/vscode-python#207.

[Enum members](https://docs.python.org/3/library/enum.html#programmatic-access-to-enumeration-members-and-their-attributes) have `name` and `value`, but Jedi thinks the attribute is an `int`.

```python
import enum

class Foo(enum.Enum):
    bar = 0

foo.bar.  # Should complete to `name` & `value`, not `int` attributes.
```

**Comment by davidhalter** [comment]
This is a metaclass issue and can only be resolved with custom code. Might take a while.
