### ISSUE TITLE
Return annotations not returned

### ISSUE THREAD

**Issue by brettcannon** [davidhalter/jedi#1091]
From Microsoft/vscode-python#185:
```python
def foo(a: int) -> bool:
    """Hello"""
    return True

foo()  # Hint lacks return annotation.
```

**Comment by davidhalter** [comment]
My counter question would be: How do you guys calculate that signature? I don't think there's an API for that yet in jedi. I'm planning to change that, but that's probably only going to happen in half a year. I'm closing, because i'm pretty sure this is not a jedi issue, because there's no such API (I read the issue #185).

Happy to be convinced otherwise.

**Comment by brettcannon** [comment]
@DonJayamanne I thought we got our signatures from Jedi? Am I mistaken?

**Comment by davidhalter** [comment]
There's https://github.com/davidhalter/jedi/pull/780 that tries to make what you guys want possible. I haven't merged it, because I first want to change some other fundamental things in the API.

**Comment by DonJayamanne** [comment]
We don't do anything special, all we do is try to get the completions from Jedi for `foo().`

**Comment by davidhalter** [comment]
So what do you mean by ` # Hint lacks return annotation.`?

**Comment by brettcannon** [comment]
I'll have to wait until I'm at work to take a screenshot, but basically if you do:
```python
async def foo(a: int) -> None: pass

foo(42)
```
And hover over `foo(42)` we won't display the `-> None` part of the signature. It was my understanding that we get that info from Jedi (but I obviously could have misunderstood when it was explained to me 😁).

**Comment by davidhalter** [comment]
I would be very surprised if such an API existed in Jedi. :)

Pretty sure you're just trying to generate that signature with what you have available in Jedi, something like:

```
d, = Script('str(').call_signatures()
param_string = ', '.join(p.description.lstrip('param ') for p in d.params)
return f'{d.name}({param_string})'
```

**Comment by davidhalter** [comment]
There's a chance you're using the return signature from the help function, which is probably not a good idea anyway, but it was fixed here: https://github.com/davidhalter/jedi/pull/1099
