### ISSUE TITLE
multiprocessing completions missing

### ISSUE THREAD

**Issue by brettcannon** [davidhalter/jedi#1094]
From Microsoft/vscode-python#588 .

I really don't know if anything can be done since [`multiprocessing.__init__`](https://github.com/python/cpython/blob/master/Lib/multiprocessing/__init__.py) is a bit nuts.

**Comment by davidhalter** [comment]
Will be resolved once typeshed is properly working. #1096 

It's my next goal to get that working.

**Comment by nbm113** [comment]
Seems the issue still there?

![image](https://user-images.githubusercontent.com/48823992/54974161-fe9b6e80-4fcd-11e9-8ff7-5d81f4570c37.png)

VS Code version: 1.32.3
Python Extension version: 2019.2.5558
Python Version: 3.7.1
OS and version: Windows 10 64 educational v1709

**Comment by davidhalter** [comment]
It's working on the typeshed branch. It will hopefully be merged, soon.

**Comment by davidhalter** [comment]
Working with 0.14.0.
