### ISSUE TITLE
No completion if object is asserted pandas DataFrame

### ISSUE THREAD

**Issue by 4217th** [davidhalter/jedi#1097]
Using vim 8 with ycm

```
import pandas

def foo(p1, p2):
    assert isinstance(p1, pandas.DataFrame)
    assert isinstance(p2, pandas.DateOffset)

```
Typing `p2.` will trigger completions but `p1.` will not
Typing `pandas.DataFrame. ` will trigger completions

**Comment by davidhalter** [comment]
I cannot reproduce it. What versions are you using? Also `pandas.DataFrame.` needs to be executed. With isinstance you're making p1 an instance and not just a class.

**Comment by davidhalter** [comment]
No answer.
