### ISSUE TITLE
Regression: Autocomplete not working after typing `User.objects.`

### ISSUE THREAD

**Issue by myii** [davidhalter/jedi#1100]
This issue follows on from #1087, which itself is linked to https://github.com/jonathanslenders/ptpython/issues/242.

> 1. [Non-crash] Autocomplete & Documentation popup not working
>     * `User.objects.` -- No autocomplete after this point
>     * `User.objects.get(` -- Documentation popup not displayed

Having worked though the commit history, I am certain that this regression was introduced by [this commit](https://github.com/davidhalter/jedi/commit/88cfb2cb91bed04de4b3760ab3d48893c2214f41).

While there is no crash, using `ptpython` (via. `shell_plus`) for Django is hampered.  In the meantime, I'm still using `v0.10.2`, which is working fine.

**Comment by davidhalter** [comment]
Yeah, this commit reduces side effects. This was a constant source of bug. Unfortunately this also means that some things cannot be accessed/completed anymore.

User.objects is clearly a descriptor:

```
>>> User.__dict__['objects']
<django.db.models.manager.ManagerDescriptor object at 0x7fdef535c588>
```

The problem with descriptors is that accessing User.objects could also for example call `rm -rf /`. This is clearly not what we want and accidental execution of such things should be avoided at all cost.

Therefore this is not a bug but rather just a thing that Jedi doesn't execute anymore to protect its users.

**Comment by myii** [comment]
@davidhalter Thanks for the explanation.

**Comment by davidhalter** [comment]
@myii If anything this might be fixed with a plugin architecture somewhere in the future, but that's still quite far away.
