### ISSUE TITLE
completion error for groupby when DataFrame is created in a function

### ISSUE THREAD

**Issue by pcluo** [davidhalter/jedi#1103]
The first script runs OK:
```python
import jedi
good_source = \
"""from pandas import read_stata
bar_var = read_stata('bad_file')
bad_var.groupby(['aa'])['bb'].mean()
"""
good_ss = jedi.Script(source=good_source, line=3, column=31)
good_ss.completions()
```

However, this script produces errors on both Windows 10 and macOS:
```python
import jedi
bad_source = \
"""from pandas import read_stata
def bad_fun():
    bar_var = read_stata('bad_file')
    return bar_var	
bad_var = bad_fun()
bad_var.groupby(['aa'])['bb'].mean()
"""
bad_ss = jedi.Script(source=bad_source, line=6, column=31)
bad_ss.completions()
```

Is this expected behavior or an open issue? I first encountered this when using `elpy` on `emacs`. I'm using `pandas 0.22.0` and `jedi 0.12.0`. Thanks for the awesome package. 

Stack Trace File: [log.txt](https://github.com/davidhalter/jedi/files/1947897/log.txt)

**Comment by davidhalter** [comment]
Thank you for the report. Can you PLEASE somehow send me a good stack trace? This one has 70 lines and 1600747 columns. LOL. If you send me something with less then 200 columns I might actually be able to read it. :)

**Comment by pcluo** [comment]
Here you go, sir, [docstring.txt](https://github.com/davidhalter/jedi/files/1948398/docstring.txt) :) I think it is the last line.

**Comment by pcluo** [comment]
Thanks for the fix. But the issue still persists...

I re-run the code with the `master` branch and got the following stack trace: [log_2.txt](https://github.com/davidhalter/jedi/files/1949267/log_2.txt)

Do you think it might be a `pandas` issue? If I change `read_stata` to `read_csv`, there is no error.

**Comment by davidhalter** [comment]
No. Tracebacks are always a jedi issue. :) Just wondering what the cause is here.

**Comment by davidhalter** [comment]
You're right

**Comment by davidhalter** [comment]
Fixed it now. It uncovered a pretty serious other issue that was surprisingly never found (because nobody ever writes `False()`).

It should be solved now. Please test again. Note that it's still extremely slow. However there are already open tickets for that.

**Comment by pcluo** [comment]
Awesome! I don't encounter the exception now. Thanks for the fix.
