### ISSUE TITLE
Autocompletion fails namespace packages

### ISSUE THREAD

**Issue by brokenn** [davidhalter/jedi#1105]
(originally posted as a comment on #122)

I'm failing to get autocompletion working via VSCode/Jedi with a large internal namespace package. I've managed to boil it down to a small example with just Jedi.

I have a namespace package called 'foo', spread across two directories, 'projecta' and 'projectb'
```
$ tree
.
├── projecta
│   └── foo
│       ├── bar
│       │   └── __init__.py
│       └── __init__.py
└── projectb
    └── foo
        ├── baz
        │   └── __init__.py
        └── __init__.py
```

The foo/\_\_init\_\_.py file is identical across both directories:

```
$ cat projecta/foo/__init__.py 
import pkg_resources
pkg_resources.declare_namespace(__name__)

$ cat projectb/foo/__init__.py 
import pkg_resources
pkg_resources.declare_namespace(__name__)
```

And foo/bar/\_\_init\_\_.py and foo/baz/\_\_init\_\_.py contain a single function each:

```
$ cat projecta/foo/bar/__init__.py 
def bar():
  return 'bar'

$ cat projectb/foo/baz/__init__.py 
def baz():
  return 'baz'
```

The namespace packages work in Python as I would expect:
```
$ PYTHONPATH=projecta:projectb python
>>> import foo; import foo.bar; import foo.baz
>>> foo.bar.bar(), foo.baz.baz()
('bar', 'baz')
```
But autocompletion with Jedi is only working for one of the two packages, always the first to be listed in the search path. For example, here it will complete for foo.bar.bar() but not foo.baz.baz()
```
$ PYTHONPATH=projecta:projectb python
>>> source = '''
... import foo; import foo.bar; import foo.baz
... a = foo.bar.b
... b = foo.baz.b
... '''
>>> import jedi
>>> [x.complete for x in jedi.Script(source, 3, 13, '').completions()]
[u'ar']
>>> [x.complete for x in jedi.Script(source, 4, 13, '').completions()]
[]
```
And with the Python Path swapped around, it will complete for foo.baz.baz() but not foo.bar.bar()
```
$ PYTHONPATH=projectb:projecta python
>>> source = '''
... import foo; import foo.bar; import foo.baz
... a = foo.bar.b
... b = foo.baz.b
... '''
>>> import jedi
>>> [x.complete for x in jedi.Script(source, 3, 13, '').completions()]
[]
>>> [x.complete for x in jedi.Script(source, 4, 13, '').completions()]
[u'az']
>>> jedi.__version__
'0.12.0'
```

This is with Jedi 0.12.0

It's entirely possible I've done something wrong and any advice would be appreciated if that is the case. Please let me know if you need any more information.

**Comment by davidhalter** [comment]
Hi @brokenn 

Thank you for the detailed error report! Since I'm a lazy man, would you be able to upload a complete folder as an example?

It's quite a big project and it would make my life easier :)

**Comment by brokenn** [comment]
You're welcome. I've attached a tar.gz to this comment with the folder layout, not sure how else to upload folders here. 

[issue1105.tar.gz](https://github.com/davidhalter/jedi/files/1950157/issue1105.tar.gz)

I tried having a brief look at the Jedi internals but unfortunately I'm not familiar enough with it to diagnose the problem.

**Comment by brokenn** [comment]
Thanks for the quick fix, I can confirm it now works for me on this sample in Python2. I also agree regarding the Python3 switch, hopefully I'll have moved everything over in the near future.
