### ISSUE TITLE
AssertionError: Cannot evaluate the keyword <Keyword: yield>

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1117]
Seeing this when using jedi-vim's goto on CaptureResult in https://github.com/pytest-dev/pytest/blob/08aed1a6bf90e2b8641aa464b41a41f1e400b59e/_pytest/capture.py#L424.

The code is new in the master branch (added in a95274d6), so there might be just something missing.

Python 3.6.5.

**Comment by davidhalter** [comment]
Thanks for the report!
