### ISSUE TITLE
Completion candidates inferred from type annotations in functions

### ISSUE THREAD

**Issue by NahsiN** [davidhalter/jedi#1120]
I apologize if this has been raised in the past but consider the following
```python
import pandas as pd

def foo(df: pd.DataFrame):
    df.he
```
Does jedi (python3 version) support autocompletion in this case? It should suggest head.

**Comment by davidhalter** [comment]
It's not that easy if you look at the code of DataFrame. There are a couple of pandas issues open and I think the fix for these things is probably something like #626. But it might take a while.

**Comment by davidhalter** [comment]
Closing it, because the issue is known and part of some other pandas issues about speed and pandas completions. It's also not something that Jedi can naturally understand.
