### ISSUE TITLE
Diff parser exception when removing newline at the end of file

### ISSUE THREAD

**Issue by micbou** [davidhalter/jedi#1121]
Running the code
```python
import jedi

jedi.Script('a\n\n', 1)
jedi.Script('a\n', 1)
```
results in the traceback
```
Traceback (most recent call last):
  File "script.py", line 12, in <module>
    jedi.Script('a\n', 1)
  File "jedi\jedi\api\__init__.py", line 119, in __init__
    cache_path=settings.cache_directory
  File "jedi\jedi\evaluate\__init__.py", line 383, in parse_and_get_code
    return self.grammar.parse(code=code, path=path, **kwargs), code
  File "parso\parso\grammar.py", line 76, in parse
    return self._parse(code=code, **kwargs)
  File "parso\parso\grammar.py", line 126, in _parse
    new_lines=lines
  File "parso\parso\python\diff.py", line 163, in update
    % (last_pos, line_length, ''.join(diff))
Exception: There's an issue (3 != 2) with the diff parser. Please report:
---
+++
@@ -1,3 +1,2 @@
 a
-

```
This is maybe related to issue https://github.com/davidhalter/jedi/issues/1081.

Configurations:
  - Ubuntu 18.04 64-bit and Windows 7 64-bit;
  - Jedi https://github.com/davidhalter/jedi/commit/6748faa071ebc667a5ca2003300a1e44fdca0254;
  - Parso https://github.com/davidhalter/parso/commit/948f9ccecccf94218e6f81a6a34cd97c7a7efd5d;
  - Python 2.7.15 and 3.6.5.

**Comment by davidhalter** [comment]
Wow. You're awesome. Thanks for finding this one!

**Comment by Aidenhjj** [comment]
i see this issue too (running spacemacs)

**Comment by davidhalter** [comment]
Fixed in https://github.com/davidhalter/parso/commit/c2eacdb81cfd6bbc1c8dfb82abd9300be327f8e1

Please test if it works. Really happy that we found this one.

**Comment by micbou** [comment]
I can confirm it's not raising the exception anymore. Thanks a lot!

**Comment by Aidenhjj** [comment]
Also no bug for me now either, thanks!

**Comment by davidhalter** [comment]
BTW I also released a new parso version, you can just use `pip install parso --upgrade` as well.
