### ISSUE TITLE
Coverage report in project using jedi references non-existent module "blub"

### ISSUE THREAD

**Issue by schavery** [davidhalter/jedi#1122]
Thanks for making Jedi! I wanted to record this information here; so that other might be able to understand.

After introducing `jedi` into our project, our reports from coverage (https://coverage.readthedocs.io/en/coverage-4.5.1/) reference a source file that's not in the project -- `blub` in the root folder. Example:

`blub   NoSource: No source for code: '/home/circleci/project/blub'.`

I tracked this down to some code in the `jedi` project, in `evaluate/compiled/access.py`, where some string is being compiled, into the module named `blub`!

This is totally fine. The fix for us was to omit the `blub` module tin our `.coveragerc` file.

**Comment by andersk** [comment]
It looks like this was fixed in de311b2f2d914a57ef499bdc0a401bdca3fc0056, but not yet in any released version.
