### ISSUE TITLE
sometimes auto complete can not work in vscode 

### ISSUE THREAD

**Issue by github-yxb** [davidhalter/jedi#1126]
vscode version info:
`版本 1.23.1  

提交 d0182c3417d225529c6d5ad24b7572815d0de9ac  
日期 2018-05-10T17:11:17.614Z  
Shell 1.7.12  
渲染器 58.0.3029.110  
Node 7.9.0  
架构 x64`

console info:
```
Traceback (most recent call last):


  File "completion.py", line 634, in watch
    response = self._process_request(rq)
  File "completion.py", line 570, in _process_request
    sys_path=sys.path, environment=self.environment)
  File "jedi\api\__init__.py", line 119, in __init__
    cache_path=settings.cache_directory
  File "jedi\evaluate\__init__.py", line 383, in parse_and_get_code
    return self.grammar.parse(code=code, path=path, **kwargs), code
  File "parso\grammar.py", line 76, in parse
    return self._parse(code=code, **kwargs)
  File "parso\grammar.py", line 126, in _parse
    new_lines=lines
  File "parso\python\diff.py", line 163, in update
    % (last_pos, line_length, ''.join(diff))
Exception: There's an issue (73 != 72) with the diff parser. Please report:
```

**Comment by davidhalter** [comment]
I just pushed a new parso release that probably fixed this issue. Can you tell me what parso version you are using and just upgrade to latest jedi as well?

If you still experience the error in that case, please let me know as much as possible about this error and how it happened.

**Comment by github-yxb** [comment]
Thanks for your reply.
I  found the version for jedi in vscode plugin directory,confirm that version is latest(0.12.0) and parso version is 0.2.0.

The irregularity of this error,so i don't know what happened when the error occurred.But when i restart vscdoe,auto complete can work for a moment.

In my code, have many dynamically defined code.
eg:
```python  
def loadMessageTips(self):
        cf = csv.DictReader(open(self.config_file, "rb"))
        for r in cf:
            if r["name"] != '':
                setattr(self, str(r["name"]), int(r["id"]))
```

**Comment by davidhalter** [comment]
Please upgrade to parso 0.2.1. I have fixed a bug in there that looks very much like the one you just reported. 

Thank you for the report anyway. Since I'm 95% sure that this was just fixed, I'm closing. I'm happy to reopen if you think this is still an issue in parso 0.2.1.
