### ISSUE TITLE
Exception distutils.spawn

### ISSUE THREAD

**Issue by bradprob** [davidhalter/jedi#1130]
Hi,
From the Elpy backend I receive this exception:
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/compiled/subprocess/__main__.py", line 34, in <module>
    from jedi.evaluate.compiled import subprocess  # NOQA
  File "/home/user/.local/lib/python2.7/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/home/user/.local/lib/python2.7/site-packages/jedi/api/__init__.py", line 27, in <module>
    from jedi.api.environment import InterpreterEnvironment
  File "/home/user/.local/lib/python2.7/site-packages/jedi/api/environment.py", line 14, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils.spawn'

**Comment by davidhalter** [comment]
What is your Operating System?  How did you install this Python version?

**Comment by davidhalter** [comment]
distutils should be installed in Python 2, it's in the standard library: https://docs.python.org/2/library/distutils.html

**Comment by micbou** [comment]
Debian-based distributions made the strange decision to split part of the `distutils` module to a separate package for Python 3. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893924. In particular, `distutils.spawn.find_executable` is only available if the `python3-distutils` package is installed which is not the case by default. This means that Jedi doesn't work on a stock Debian-based distribution with Python 3. I would suggest to re-implement [the `find_executable` function](https://github.com/python/cpython/blob/a8eb58546b37a7cd5f332f019bb07388f5212c2d/Lib/distutils/spawn.py#L169-L192) in Jedi to avoid the issue. I can prepare a PR if you are okay with the proposal.

**Comment by davidhalter** [comment]
@micbou Just copy the function to _compatibility.py and we'll be fine I guess.

---

Generally I have to say that I really dislike the way that the Debian maintainers just remove part of the standard library. This is just a stupid idea. People depend on it, because it exactly is part of the stdlib. It's just a really bad idea in general to remove it. But whatever... It pretty much makes me realize why I'm not using Debian. They are so puristic at times...

**Comment by micbou** [comment]
Found this note while browsing the code:

> When dropping Python 2.7 support we should consider switching to `shutil.which`.

Should we copy that function instead?
