### ISSUE TITLE
Jedi does not recognize `not isinstance()` ramifications

### ISSUE THREAD

**Issue by brettcannon** [davidhalter/jedi#1133]
Microsoft/vscode-python#1725

This works:
```python
class MyObject(object):
    def testMethod(self):
        pass

def myFunc(obj):
    if isinstance(obj, MyObject):
        obj.  # Completes for testMethod().
```

This doesn't:
```python
class MyObject(object):
    def testMethod(self):
        pass

def myFunc(obj):
    if not isinstance(obj, MyObject):
        raise Exception
    obj.  # No completions.
```

**Comment by davidhalter** [comment]
I can understand that this would be a nice thing to have. But the semantics are quite complicated (especially considering all the edge cases, i.e. there might be a return in an if or no return or whatever). 

So for now this is not going to be part of Jedi. There's a chance I'll change my mind if I do a Rust implementation.
