### ISSUE TITLE
Jedi autocompletion not working with ipython 6.3?

### ISSUE THREAD

**Issue by arogozhnikov** [davidhalter/jedi#1134]
```bash
$ ipython --version
6.3.1
$ python -c 'import jedi; print(jedi.__version__)'
0.12.0
```

I'm actually checking an example from README (`range(10).cou<TAB>`), which works well in pure python shell after 
```python
>>> from jedi.utils import setup_readline
>>> setup_readline()
```

However, I do not get proper suggestions in IPython (neither before nor after readline). Simple suggestion for `ran<TAB>` are working however.

**Comment by arogozhnikov** [comment]
Ok, after looking into sources I see https://github.com/ipython/ipython/commit/859b4eb5db50cbac06f4d987bc7292d68660ae18

When I turned it back, example started to work, however this messes up with paths in ipython-specific commands like 
```
ls <TAB>
```

**Comment by davidhalter** [comment]
Well I guess that their usage of ls is pretty special. They should probably just check if it starts with ls and then not run Jedi completions.

IMO this should be closed and you should open an issue on the IPython tracker. I'm happy to work with you on that. I'm closing, but please keep commenting if you have further questions.
