### ISSUE TITLE
For scikit-learn methods defined in base classes are sometimes missing

### ISSUE THREAD

**Issue by arogozhnikov** [davidhalter/jedi#1135]
Some methods defined by ancestors are not suggested

```python
from sklearn.ensemble import RandomForestClassifier
RandomForestClassifier().<TAB> # misses .fit (defined in parent of parent), but lists various predict methods (defined in parent)
RandomForestClassifier.<TAB> # everything is ok, running in terminal
```

Different example :

```python
from sklearn.linear_model import LogisticRegression
LogisticRegression().<TAB> # misses predict, defined in second parent
```

```
sklearn == 0.19.1
jedi == 0.12.0
```

**Comment by davidhalter** [comment]
Can you upgrade to Jedi 0.14.0 and see if this is still an issue?

**Comment by arogozhnikov** [comment]
I've updated jedi to 14. IPython now does not show any suggestions for the examples above.

**Comment by davidhalter** [comment]
I don't think you like that more, haha.

**Comment by davidhalter** [comment]
Please upgrade to Jedi 0.15.2 (latest) and try again. There have been some changes around lookups and Jedi 0.14.x might have been worse for IPython users than previous versions. Thanks for checking!

**Comment by jamespreed** [comment]
The 0.15.2 release seems to have fixed several IPython related issues.  In particular, populating methods for an object with a sub-namespace was not working at all.  You could see this in Pandas via:

```
import pandas as pd

df = pd.DataFrame({'A': ['aaa', 'bbb', 'ccc'], 'B':[1,2,3]})
df.A.str.<TAB>   # shows nothing with v<0.15.2
```

Great work, thanks!

**Comment by davidhalter** [comment]
Great, Thanks for the feedback :)

I'm closing, if you're still experiencing issues, let me know.
