### ISSUE TITLE
Cannot complete object from context manager on one-liner statement

### ISSUE THREAD

**Issue by micbou** [davidhalter/jedi#1138]
This is a minor issue but Jedi is unable to complete an object returned by a context manager when the whole `with` statement is written on one line. The code:
```python
import jedi

print(jedi.Script("""
class Test():
    def __enter__(self):
        return 'test'

    def __exit__(self, *args):
        pass

with Test() as test: test.""").completions())
```
outputs an empty list while
```python
import jedi

print(jedi.Script("""
class Test():
    def __enter__(self):
        return 'test'

    def __exit__(self, *args):
        pass

with Test() as test:
    test.""").completions())
```
returns the expected completions.

Configurations:
- Windows 7 64-bit;
- Jedi 62a3f99594c1d4afc029a9985d297fd1af915e38;
- Parso https://github.com/davidhalter/parso/commit/6f385bdba182059e0c46917a414981a6d0894527;
- Python 2.7.15 and 3.6.5.

**Comment by davidhalter** [comment]
It's a parso bug in error recovery. Thanks for finding it. It also appears when using oneline functions and other similar cases where the grammar symbol `suite` is used.

**Comment by davidhalter** [comment]
I had to rewrite the parso's parser generator because of that bug :) So it took me a bit longer. Haha.

**Comment by davidhalter** [comment]
I had to rewrite the parso's parser generator because of that bug :) So it took me a bit longer. Haha.
