### ISSUE TITLE
get_default_environment can return a python3 environment when running on python2

### ISSUE THREAD

**Issue by gatesn** [davidhalter/jedi#1142]
It doesn't seem correct that `jedi.environment.get_default_environment` can return a python3 environment even though jedi is running in python2?

**Comment by davidhalter** [comment]
This was an intentional decision: The latest version has more CPython features to offer.

With the latest Jedi version you need to stop thinking about starting Jedi with a certain Python version and rather use parameters to choose the version.

**Comment by gatesn** [comment]
Can you explain what you mean by choose the python version with parameters?

**Comment by davidhalter** [comment]
With environments, you can just load the environment you want. Just use `env = jedi.get_system_environment('2.7'); jedi.Script(..., environment=env)`.

**Comment by davidhalter** [comment]
BTW: Now the environment matches, 2.7 for 2.7 and 3.7 for 3.7. So this shouldn't be an issue anymore.
