### ISSUE TITLE
Type hinting, rtype module

### ISSUE THREAD

**Issue by jtamagnan** [davidhalter/jedi#1154]
I tried experimenting with returning modules from functions and having auto-completion work on those modules.
I was hoping that using sphinx-like type definitions would work, `:py:mod:`my_module`, `:py:module:`my_module`.
```
import my_module

def get_module_from_path(path):
    """Import a module from path that looks like `my_module`

    :param path: Path to module to load
    :type path: str
    :returns: A python module that looks like my_module
    :rtype: :py:mod:`my_module`
    """
    # Here is where we will dynamically load my_module, based on the
    # given path.
    module = None
    return module


my_module2 = get_module_from_path('path_to_module')
my_module2.|
```
Is there any way to work around this. Using `assert is_instance(my_module2, my_module)` didn't work which makes sense since `my_module2` is not an instance of `my_module`. I'd like to be able to hint that `my_module2` has all the same members as `my_module`

**Comment by davidhalter** [comment]
It's probably not a use case a lot of people have. In general the support for sphinx statements like `:py:mod:` etc is probably non-existent. This was probably never implemented. Sorry for that.

**Comment by davidhalter** [comment]
This is not going to happen, sorry. If you want to make completions better for yourself, please use annotations. Sphinx can probably also deal with those.
