### ISSUE TITLE
API: Environment: create_environment is not deterministic

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1155]
There is no recommended API to explicitly create an Environment from an executable.
`create_environment` currently falls back to based on if something is a file:

```
def create_environment(path, safe=True):
    """
    Make it possible to manually create an environment by specifying a
    Virtualenv path or an executable path.

    :raises: :exc:`.InvalidPythonEnvironment`
    :returns: :class:`Environment`
    """
    if os.path.isfile(path):
        _assert_safe(path, safe)
        return Environment(_get_python_prefix(path), path)
    return Environment(path, _get_executable_path(path, safe=safe))
```

This means that the caller needs to do the same check before to ensure that `path` is treated at the executable.

I suggest that either only executables are supported, or kwargs (executable, path) get used, or distinct functions should be created.

As for jedi-vim I can use `Environment()` directly - but its docstring explicitly states that it should not be used directly:

```
class Environment(_BaseEnvironment):
    """
    This class is supposed to be created by internal Jedi architecture. You
    should not create it directly. Please use create_environment or the other
    functions instead. It is then returned by that function.
    """
```

(I am refactoring the environments currently - on top of https://github.com/davidhalter/jedi/pull/1108)
Related comment there: https://github.com/davidhalter/jedi/pull/1108#issuecomment-388182051

**Comment by davidhalter** [comment]
Yeah. I agree. I actually thought about the fact that this was not the best idea (to have an argument that does multiple things) and now we're stuck in that mess. I should have reacted then and there, but now it's kind of too late. I guess we should just add a new function `create_environment_from_file` or move current behavior away from it.

Not sure what the best move is in terms of naming, but I'm sure that we want to move away from the status quo.

**Comment by micbou** [comment]
Sorry, that's my fault. I think the function should be deprecated in favor of two new functions `create_environment_from_file` (or `create_environment_from_exe`?) and `create_environment_from_venv`. This could be done for release 0.12.1 then `create_environment` would be removed in 0.13.0.

**Comment by davidhalter** [comment]
@micbou No problem. I didn't really spot it either.

**Comment by blueyed** [comment]
Yes, for the end user it is good, but I came across it when using it in jedi-vim (where I then just used `Environment` directly, which is fine in that case).
Feel free to close this for now.

**Comment by davidhalter** [comment]
Thanks for clarifying. I really think that it's fine for now. Let me know if it's a bigger issue or you think that it's something we should rethink.
