### ISSUE TITLE
Latest release on pypi doesn't play nice with python 3.7

### ISSUE THREAD

**Issue by aeroevan** [davidhalter/jedi#1157]
``ipython 6.4.0 has requirement jedi>=0.10, but you'll have jedi -Jedi.is.a.static.analysis.tool.for.Python.that.can.be.used.in.IDEs-editors..Its-historic.focus.is.autocompletion-.but.does.static.analysis.for.now.as.well.-Jedi.is.fast.and.is.very.well.tested..It.understands.Python.on.a.deeper.level-than.all.other.static.analysis.frameworks.for.Python.-Jedi.has.support.for.two.different.goto.functions..It-s.possible.to.search.for-related.names.and.to.list.all.names.in.a.Python.file.and.infer.them..Jedi-understands.docstrings.and.you.can.use.Jedi.autocompletion.in.your.REPL.as-well.-Jedi.uses.a.very.simple.API.to.connect.with.IDE-s..There-s.a.reference-implementation.as.a.-VIM-Plugin.-https-github.com-davidhalter-jedi-vim-which.uses.Jedi-s.autocompletion...We.encourage.you.to.use.Jedi.in.your.IDEs.-It-s.really.easy.-To.give.you.a.simple.example.how.you.can.use.the.Jedi.library-.here.is.an-example.for.the.autocompletion.feature-.import.jedi-.source.-.-....import.datetime-....datetime.da-.script.-.jedi.Script-source-.3-.len-datetime.da-.-example.py-.script-Script-.-example.py-.completions.-.script.completions-.completions.........................................-doctest-.-ELLIPSIS-Completion-.date-.-Completion-.datetime-....-.print-completions-0-.complete-te-.print-completions-0-.name-date-As.you.see.Jedi.is.pretty.simple.and.allows.you.to.concentrate.on.writing.a-good.text.editor-.while.still.having.very.good.IDE.features.for.Python.- which is incompatible.
``

Is a very interesting version.

Installing from git does work though.

**Comment by davidhalter** [comment]
I hope to release a fix tomorrow.

**Comment by davidhalter** [comment]
I just did a new jedi release. I hope that there are not going to be any issues anymore.

**Comment by davidhalter** [comment]
This was the actual issue: https://github.com/davidhalter/jedi/pull/1143
