### ISSUE TITLE
Is it possible to have suggestions of parameters from parent method, if there is super(**kwargs)?

### ISSUE THREAD

**Issue by idchlife** [davidhalter/jedi#1163]
First of all, thanks for jedi! This is insane how it's helpful with different ides (vim, vscode).

Just curious, is it even possible? This feature will be very nice and useful!

What I'm talking about:

```python

class Parent():
  def __init__(self, required: bool = None):
    ...

class Child(Parent):
  def __init__(self, default: int = None, **kwargs):
    self.value = default
    super().__init__(**kwargs)


a = Child(default=10, req <-- here goes suggestiong for required parameter
```

**Comment by micbou** [comment]
This doesn't invalidate your feature request but it would be less confusing if the right syntax were used:
```python
super(**kwargs)
```
should be
```python
super(Child, self).__init__(**kwargs)
```
or simply
```python
super().__init__(**kwargs)
```
in Python 3.

**Comment by davidhalter** [comment]
It's on my todo list, but it's not exactly easy.

**Comment by idchlife** [comment]
@davidhalter thank you very much for your work! Do you have patreon or opencollective for Jedi? DId not find any info in the documentation.

**Comment by davidhalter** [comment]
This should be working now, there is also a test that helps.

@idchlife I do intend to set it up at some point, but while I'm a bit lazy, please consider just giving that money to your favorite charity :) I'll try to post it here once I have it.
