### ISSUE TITLE
subprocess client: do not mute sys.stderr

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1165]
It gets muted in https://github.com/davidhalter/jedi/blob/508ed7e5b8efd946e6a6c6239ee926ce67c6d36a/jedi/evaluate/compiled/subprocess/__init__.py#L287-L291, but that results in e.g. (internal) exceptions not being visible anywhere.

What is the leaking that is mentioned there about?

I would say to either remove this, or add an outer `try-except` to the client in `__main__.py` to catch any exceptions and display them on saved_sys_stderr.

**Comment by davidhalter** [comment]
Sometimes if you load certain modules, they write stuff to stderr. This should not leak IMO. However we could try to read stderr all the time and log the output. I think that would make more sense.

**Comment by blueyed** [comment]
Ok, so you agree to unmute it then?

Do you mean to read and log it always, or just in case of errors, like it gets done now already, when it crashed?

**Comment by blueyed** [comment]
See https://github.com/davidhalter/jedi/pull/1169.

**Comment by davidhalter** [comment]
#1169 was merged.
