### ISSUE TITLE
Script: encoding is not used / API for list of lines

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1167]
The `encoding` kwarg is not used:

https://github.com/davidhalter/jedi/blob/9e66253e3a2aff6b9a96ebdd0c3b26639ecf4654/jedi/api/__init__.py#L75-L87

Also `source_encoding` is documented, but not used.

btw: it might be useful to provide an API for a list of lines (e.g. jedi-vim also joins the list of unicode lines, only for Jedi/parso then splitting them again).

**Comment by davidhalter** [comment]
Thank you for going through the code.
