### ISSUE TITLE
Add '3.7' to _SUPPORTED_PYTHONS in 'jedi/jedi/api/environment.py' ?

### ISSUE THREAD

**Issue by rpdeo** [davidhalter/jedi#1177]
Hello,

I use Elpy for code completion in Emacs. During recent switch to Python 3.7, I lost some of the code completion ability. It would complete everything from standard lib, but not from packages installed in virtualenvs.

I tracked this down to the list _SUPPORTED_PYTHONS from `jedi/jedi/api/environment.py` not having '3.7' in it. I have both 2.7.x and 3.7.0 on my system, and Jedi picks the system 2.7.x python binary and tries to run the Jedi `jedi/evaluate/compiled/subprocess/__main__.py` with it. 

After adding '3.7'  to the list in `api/environment.py`, I get back my completions for packages in the virtualenv, and the python3 binary from my virtualenv is used (as it should, as opposed to the system one.)

I am not familiar enough with the Jedi code-base to know if this is occurring due to a particular combination of a virtualenv with Python 3.7, Emacs 26.1, Elpy 1.22.0, Company 0.9.6, and Jedi 0.12.1.

I have gone through Elpy's python code and it correctly calls `jedi.Script()` with python3.7 from virtualenv, so I am guessing I have identified the issue correctly. But I may be wrong.

The reason I have some doubts is, I also tried out Company 0.9.6 with Anaconda-mode 0.1.12, and 
Jedi 0.12.1, and it was able to show correct code completion without adding '3.7'. I see that anaconda-mode makes a call to `jedi.create_environment()` to discover the virtualenv, and passes the Environment instance to `jedi.Script(..., environment=...)`. This seems missing from Elpy's `elpy/jedibackend.py`, but may be they do this in some other fashion?

Please advise if something else should be done. I am going to put a reference to this in Elpy issue tracker also, so they could also have a look at this.

**Comment by blayz3r** [comment]
Any updates

**Comment by davidhalter** [comment]
Python 3.7 is now part of `_SUPPORTED_PYTHONS` in 0.13.1.

Better support for Python 3.7 is coming with typeshed. The typeshed branch is now 250 commits ahead of master. It will probably still take another 50 at least.

**Comment by davidhalter** [comment]
I'm closing this issue. 3.7 support landed in the typeshed branch (which is now pretty much feature complete). If you want to help me with it, please check it out and let me know if you find any bugs.
