### ISSUE TITLE
Wrong call signatures for Exception (empty)

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1182]
Via https://github.com/davidhalter/jedi-vim/pull/849.

jedi-vim sees an empty list of definitions/call signatures for `Exception`.

ipython reports this:
```
Init signature: Exception(self, /, *args, **kwargs)
Docstring:      Common base class for all non-exit exceptions.
Type:           type
```

(sorry, no `jedi` script to reproduce/show this currently at hand)

According to @davidhalter this might be solved with (better) typeshed support.

**Comment by davidhalter** [comment]
I feel like typeshed support fixed this, I'm getting `*args` now, which is fine.
