### ISSUE TITLE
Jedi completion in Python Interpreter on windows

### ISSUE THREAD

**Issue by brupelo** [davidhalter/jedi#1184]
I've tried following [https://jedi.readthedocs.io/en/latest/docs/usage.html#tab-completion-in-the-python-shell](https://jedi.readthedocs.io/en/latest/docs/usage.html#tab-completion-in-the-python-shell), here's my whole attempt:

    (py364_32) d:\>python -m jedi repl
    d:\virtual_envs\py364_32\lib\site-packages\jedi\api\replstartup.py

    (py364_32) d:\>set PYTHONSTARTUP=d:\virtual_envs\py364_32\lib\site-packages\jedi\api\replstartup.py

    (py364_32) d:\>python
    Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    REPL completion using Jedi 0.12.1
    Jedi: Module readline not available.
    >>> ^Z

    (py364_32) d:\>pip install readline
    Collecting readline
      Using cached https://files.pythonhosted.org/packages/f4/01/2cf081af8d880b44939a5f1b446551a7f8d59eae414277fd0c303757ff1b/readline-6.2.4.1.tar.gz
        Complete output from command python setup.py egg_info:
        error: this module is not meant to work on Windows

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\KneDa\AppData\Local\Temp\pip-install-fj3f4ly4\readline\

    (py364_32) d:\>python
    Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    REPL completion using Jedi 0.12.1
    Jedi: Module readline not available.
    >>>

How to make this feature work on windows?

**Comment by brupelo** [comment]
It seems the solution was just installing pyreadline, after that autocompletion will work :)

Guess the proper fix would be just adding readline as a dependency on linux and pyreadline as a dependency on windows? That way you'll just need to `pip install jedi` and everything will work

**Comment by davidhalter** [comment]
For the reasoning why this one was closed, see #1185.
