### ISSUE TITLE
Problem showing parameter list when calling a classmethod

### ISSUE THREAD

**Issue by petey33** [davidhalter/jedi#1186]
I'm using jedi in emacs via an emacs package called elpy.

When I write a function call to a function that is defined somewhere in my code then emacs  shows me the parameters of the function I'm calling.

My problem is it does not work when the function is a classmethod (decorated with "@classmethod").

Thanks for your help.

**Comment by davidhalter** [comment]
Duplicate: https://github.com/davidhalter/jedi/issues/498
