### ISSUE TITLE
jedi-vim not work for third lib with python 3.7

### ISSUE THREAD

**Issue by xbsura** [davidhalter/jedi#1188]
Hi:
after installing jedi vim, lib such as os, io, and import from my own project work well,  but the third lib can not work

some messages:

:ver
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 22 2018 05:24:30)
macOS version
Included patches: 1-202
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +cmdline_compl     -ebcdic            -hangul_input      -lua               +mouse_xterm       -python            +tag_binary        +vartabs           -xim
+arabic            +cmdline_hist      +emacs_tags        +iconv             +menu              +multi_byte        +python3           +tag_old_static    +vertsplit         -xpm
+autocmd           +cmdline_info      +eval              +insert_expand     +mksession         +multi_lang        +quickfix          -tag_any_white     +virtualedit       -xsmp
-autoservername    +comments          +ex_extra          +job               +modify_fname      -mzscheme          +reltime           -tcl               +visual            -xterm_clipboard
-balloon_eval      +conceal           +extra_search      +jumplist          +mouse             +netbeans_intg     +rightleft         +termguicolors     +visualextra       -xterm_save
+balloon_eval_term +cryptv            +farsi             +keymap            -mouseshape        +num64             +ruby              +terminal          +viminfo
-browse            +cscope            +file_in_path      +lambda            +mouse_dec         +packages          +scrollbind        +terminfo          +vreplace
++builtin_terms    +cursorbind        +find_in_path      +langmap           -mouse_gpm         +path_extra        +signs             +termresponse      +wildignore
+byte_offset       +cursorshape       +float             +libcall           -mouse_jsbterm     +perl              +smartindent       +textobjects       +wildmenu
+channel           +dialog_con        +folding           +linebreak         +mouse_netterm     +persistent_undo   +startuptime       +timers            +windows
+cindent           +diff              -footer            +lispindent        +mouse_sgr         +postscript        +statusline        +title             +writebackup
-clientserver      +digraphs          +fork()            +listcmds          -mouse_sysmouse    +printer           -sun_workshop      -toolbar           -X11
+clipboard         -dnd               -gettext           +localmap          +mouse_urxvt       +profile           +syntax            +user_commands     -xfontset
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework
 AppKit   -mmacosx-version-min=10.13 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.28.0/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/pyt
hon/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.5.1 -lobjc

Messages maintainer: Bram Moolenaar <Bram@vim.org>
"m.py" 3L, 21C
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 22 2018 05:24:30)
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 22 2018 05:24:30)

:python3 import sys; print(sys.version_info)
sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)

:python3 import sys; print(sys.path)
['/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python37.zip', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7', '/usr/local/opt/python/Frameworks/Python
.framework/Versions/3.7/lib/python3.7/lib-dynload', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages', '_vim_path_']

my third lib is in /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages

i dont know how to config to make jedi support 3rd lib, anybody can help?

if i put /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages to the 1st of path, os can not auto complete too

**Comment by davidhalter** [comment]
Python 3.7 is not yet supported. Please wait for a few weeks. I'm working on it.

**Comment by xbsura** [comment]
OK, thanks

**Comment by ScottDWebster** [comment]
Is 3.7 support still forthcoming?

**Comment by davidhalter** [comment]
Yeah. Probably another week until you can at least use Python3.7. Real (and good) Python 3.7 support is coming with #1096, but that issue is a lot of work on my side (like 2-3 months of work, of which I've completed half of it, but since I also work it takes like 5 months).

However  you will probably be able to use Jedi for most cases just fine in 3.7.
