### ISSUE TITLE
Cannot get signature of objects imported from __init__.py

### ISSUE THREAD

**Issue by ColinKennedy** [davidhalter/jedi#1193]
I'm working with an API that combines imports from multiple modules to a `__init__.py` file at the root of the Python package.

When I try to get call signatures of a class which was imported into `__init__.py` using jedi, I found that it does not find the signatures of the class's `__init__` method. 

The file structure is relevant so I'll describe it below (and also include the modules as an attachment).

File structure:

    {root directory which is presumably on the PYTHONPATH}
    - test_out
    - __init__.py
    - item.py

    > cat __init__.py
    from item import Thing

    > cat item.py
    class Thing(object):
        def __init__(self, part, name=''):
            super(Thing, self).__init__()

Now, using Jedi, attempt to get the signatures of `Thing` in a Script.

    # IMPORT STANDARD LIBRARIES
    import textwrap
    
    # IMPORT THIRD-PARTY LIBRARIES
    import jedi
    
    
    def main():
        '''Run the main execution of the current script.'''
        code = textwrap.dedent(
            '''\
            import test_out as test
    
            def main():
                obj = test.Thing()
            '''
        )
        script = jedi.Script(code, len(code.splitlines()), len('    obj = test.Thing('))
        print(script.call_signatures())
    
    
    if __name__ == '__main__':
        main()

(In the attachment, this is called "run_me.py" [jedi_issue_init_package.zip](https://github.com/davidhalter/jedi/files/2259980/jedi_issue_init_package.zip))

run_me.py prints an empty list of signatures.

However replacing `import test_out as test` with `from test_out import item as test` works as expected. The call signature is found, in this case. Also, it's worth noting that classes defined directly in `__init__.py` do get call signatures, as well. Only imported ones seem to not work.

In real-world terms, `test_out` is actually a third-party package which uses the top-level `__init__.py` to expose API functions / classes to the user. Normally I would just import the inner modules and use that but it's recommended not to do this by the provider of the package because the modules and their functions are subject to changes. The `__init__.py` is the public API.

Since it works as long as you import `item.py` directly, it seemed like the issue was related to the fact that `import test_out as test` is importing from `__init__.py` and the callable object was imported (not defined) directly in `__init__.py`.

Could this be fixed?

Environment details:
OS: CentOS Linux release 7.5.1804 (Core)
Python version: 2.7.5
Jedi version: 0.12.1

Please let me know if you need any other information.

**Comment by davidhalter** [comment]
Note that your example is not working on Python3, but only on Python2:

```
$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
REPL completion using Jedi 0.12.1
>>> import test_out
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/jedi_issues/1193/jedi_issue_init_package/test_out/__init__.py", line 1, in <module>
    from item import Thing
ImportError: No module named 'item'
>>> 
$ python2
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
REPL completion using Jedi 0.12.1
>>> import test_out
>>> 
```

Since Jedi uses Python3 by default, you also have to use a Python2 environment in Jedi:

```
script = jedi.Script(                                          
    code, len(code.splitlines()), len('    obj = test.Thing('),
    environment=jedi.get_system_environment('2')               
)                                                              
```

Now everything works great:

```
$ python3 run_me.py 
[<CallSignature: Thing index=0 params=[part, name='']>]
```

This is all intended and working in the same way as Python. Start using Python3 imports, The security support for Python2 is running out in 2020 :).

**Comment by ColinKennedy** [comment]
As mentioned before, `test_out` isn't mine to change but I will let them know to get with the future hahah.

That said, you're completely right and your suggestion works for me. Thanks Dave!
