### ISSUE TITLE
Add IronPython support.

### ISSUE THREAD

**Issue by vicwjb** [davidhalter/jedi#1197]
When I used ironpython to write programs, I found that there was no good editors with good completion support, so I wish the jedi to support ironpython.

**Comment by davidhalter** [comment]
Well, be free to add support for it. I have never used IronPython and I'm not very interested in changing that. But feel free to add support for it. I think the biggest issue is probably the import system. Everything else should work more or less. Maybe typeshed support could also be beneficial (#1096).

**Comment by davidhalter** [comment]
Since I won't do it (and nobody else has come forward either), I'm closing this. If anybody is seriously interested in implementing this, feel free to start a discussion.
