### ISSUE TITLE
get_cached_default_environment should be invalidated if $VIRTUAL_ENV changes

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1200]
https://github.com/davidhalter/jedi/blob/691a5b6c21d97d97da6ef14224f1115cc13f9f3f/jedi/api/environment.py#L190-L192

This is used by jedi-vim, but when a user changes `$VIRTUAL_ENV` it should not take 10 minutes to work.

Not sure how to approach this best.

On the one hand a time based cache does not really make sense here, except for when you install a new version, but then it might still take up to 10 minutes to have an effect.

Therefore I suggest changing it to only cache it by the value of `$VIRTUAL_ENV`.

**Comment by davidhalter** [comment]
I agree. We could probably just make it possible to clean the cache, rename this function and create a function that checks if `$VIRTUAL_ENV` changed and in that case clear the cache.

**Comment by blueyed** [comment]
So it could be cached on the module, and a new function would be added to clear the cache?
