### ISSUE TITLE
jedi.api.names with all_scopes=False extracts a class-scoped variable

### ISSUE THREAD

**Issue by immerrr** [davidhalter/jedi#1202]
Here's a repro example:
```
In [8]: jedi.api.names(textwrap.dedent("""
   ...:     from module import f
   ...:     g = f(f)
   ...:     class C:
   ...:         h = g
   ...: """), 'example.py', all_scopes=False)
Out[8]: 
[<Definition module f>,
 <Definition g = f(f)>,
 <Definition class C>,
 <Definition h = g>]

In [9]: _8[-1].parent()
Out[9]: <Definition class C>
```
IIUC `<Definition h = g>` should not be considered a global definition and thus not returned if `all_scopes=False` is used.

**Comment by davidhalter** [comment]
I agree. If you PR this as a breaking test somewhere I will probably have it easier to fix it.

Thanks for the report!

**Comment by immerrr** [comment]
@davidhalter there you go: #1203

**Comment by davidhalter** [comment]
Fixed by yourself, thanks again!
