### ISSUE TITLE
jedi library not found

### ISSUE THREAD

**Issue by Nikola-Tesla-Mandici** [davidhalter/jedi#1206]
I first read your documentation carefully 3 times. it does not have anything special, then download your addon, install it, activate it, and follow the last 2 steps to configure it, your JEDI library will never be activated, and it could never be used

in your documentation it says that you are going to download the Jedi library, but inside your readme.txt it just says that I have to install it, and it sends me to your documentation, which does not solve the problem because it does not say anything important, nor does it have technical solutions to these problems

How do you intend to make your supplement work with this documentation so ambiguous and so neglected?
![2018-08-22_21-19-04](https://user-images.githubusercontent.com/36495485/44501257-24385200-a652-11e8-9e1a-750be899d280.png)

![2018-08-22_20-57-45](https://user-images.githubusercontent.com/36495485/44501276-37e3b880-a652-11e8-8da2-68f31c5203f3.png)

![2018-08-22_21-04-20](https://user-images.githubusercontent.com/36495485/44501288-47fb9800-a652-11e8-95e4-d21d35ef514d.png)
[https://github.com/JacquesLucke/code_autocomplete/issues/6](url)
![2018-08-22_21-37-13](https://user-images.githubusercontent.com/36495485/44501983-0fa98900-a655-11e8-852f-d36f41e4fee7.png)

**Comment by davidhalter** [comment]
Thanks for all the screenshots, but I still don't really understand what your issue is. I understand that Jedi doesn't install, but you're not installing it with something good.

I think you just need to follow this: https://code-autocomplete-manual.readthedocs.io/en/latest/setup.html

> When there is a error message Jedi library not found you have to use another .zip file in the beginning. Direct download from the github page is not supported, because the Jedi library is a submodule which isn’t included in these downloads. You can either use an official release or use git to download the repository and its submodules (git clone –recursive https://github.com/JacquesLucke/code_autocomplete.git).

**Comment by davidhalter** [comment]
> in your documentation it says that you are going to download the Jedi library, but inside your readme.txt it just says that I have to install it, and it sends me to your documentation, which does not solve the problem because it does not say anything important, nor does it have technical solutions to these problems

Yes you actually just need to install it with pip if you want to use it in your Python version. If you however use Jedi via a plugin (like you) then the plugin is responsible for bringing Jedi. Typically that is done with a git submodule, pip or vendoring. Your plugin seems to use a submodule.

**Comment by Nikola-Tesla-Mandici** [comment]
> > en tu documentación dice que vas a descargar la biblioteca Jedi, pero dentro de tu readme.txt solo dice que tengo que instalarla y me envía a tu documentación, que no resuelve el problema porque no dice Nada importante, ni tiene soluciones técnicas a estos problemas.
> 
> Sí, solo necesitas instalarlo con pip si quieres usarlo en tu versión de Python. Sin embargo, si usa Jedi a través de un complemento (como usted), entonces el complemento es responsable de traer Jedi. Por lo general, esto se hace con un submódulo git, pip o vendedor. Tu plugin parece utilizar un submódulo. Probablemente solo necesites decir algo así `git submodule update --init`.

I regret the absence the university and the work consumes me, I will try the suggestions and I will feedback, so that if someone happens to have a prompt solution
