### ISSUE TITLE
Zip files support

### ISSUE THREAD

**Issue by fabal** [davidhalter/jedi#1207]
It seems like zipped python packages are not supported by Jedi (python **2.7.14**, jedi **0.12.0**).
Could this be supported?

> This issue has been discovered using vscode's python [extension](https://github.com/Microsoft/vscode-python/issues/2428).

**Comment by davidhalter** [comment]
There is `.egg` support. I'm not sure if it's working properly in Python 2.7, but it has definitely been working for Python 3.

I know that it doesn't work if Python was compiled without unzip support.

**Comment by fabal** [comment]
Thanks for the update. The python we're using has unzip support though.
If you could confirm that Jedi does support zipped eggs with python 2.7 when you get a chance that would be greatly helpful.

**Comment by davidhalter** [comment]
I'm totally fine with pyc files being loaded by Jedi from zip files. I don't see why that should not be possible. Maybe there are limitations, but I have no idea. Someone would need to investigate here and I personally won't do it.

**Comment by davidhalter** [comment]
This was fixed by the new import system. While the fix didn't target this issue, this issue was probably fixed as a side effect. Tested with Python 3.7.

@hoefling Thanks for providing great reproduction steps. This helped tremendously in checking if it was still an issue.

**Comment by hoefling** [comment]
@davidhalter thanks, glad the report was useful!
