### ISSUE TITLE
Completion on relative imports for packages with common name point to wrong package

### ISSUE THREAD

**Issue by brettcannon** [davidhalter/jedi#1209]
From Microsoft/vscode-python#2450
 
Basically if you have a package named `spam` and another one called `foo.spam`, relative imports for modules in `foo.spam` actually complete to things in `spam` instead.

**Comment by sancau** [comment]
Having the same issue (using YouCompleteMe + Vim).

**Comment by davidhalter** [comment]
Please check it now. It took me a long time to get this right. It's on the typeshed branch. It's also somewhat improved on master, but some relative imports are still not working on master.

Please test and let me know if it works (on the typeshed branch).
