### ISSUE TITLE
PEP 557 dataclass support

### ISSUE THREAD

**Issue by crowsonkb** [davidhalter/jedi#1213]
It would be good to have [PEP 557](https://www.python.org/dev/peps/pep-0557/) [dataclass](https://docs.python.org/3/library/dataclasses.html) static analysis support.

**Comment by jamescasbon** [comment]
One thing I noticed about this was that for both dataclasses and attrs (davidhalter/jedi-vim#816), inspect gets the signature correct.  This seems to use __anottations__ - can jedi use the same technique?


```
import attr
import dataclasses
import inspect
import jedi


class Vanilla:
    def __init__(self, name_of_arg=1):
        self.name_of_arg = name_of_arg


@dataclasses.dataclass
class Dataclass:
    name_of_arg: int = 1


@attr.s(auto_attribs=True)
class Attr:
    name_of_arg: int = 1


if __name__ == '__main__':
    source = "import foo; foo.X(name_of"
    l = len(source)

    for cname in ('Vanilla', 'Dataclass', 'Attr'):

        print(cname)
        src = source.replace('X', cname)
        script = jedi.Script(src, 1, len(src), 'example.py')
        print('completions', script.completions())
        cls = globals()[cname]
        print('inspect', inspect.signature(cls.__init__))
        print()
```

```
$ python foo.py                                                                                                                     (613ms)  
Vanilla
completions [<Completion: name_of_arg>]
inspect (self, name_of_arg=1)

Dataclass
completions []
inspect (self, name_of_arg: int = 1) -> None

Attr
completions []
inspect (self, name_of_arg: int = 1) -> None
```

**Comment by davidhalter** [comment]
@jamescasbon Your test doesn't make any sense. Did you mean to use `Interpreter` (which would probably mean you use Jedi from IPython) or are you using it in an editor and the classes `Vanilla`, etc are just completely ignored?

**Comment by davidhalter** [comment]
It should be fine now. It's a bit tedious to write all that stuff, because I pretty much have to reimplement dataclasses (something like 50-100 LOC). But at least it works here now.
