### ISSUE TITLE
Flags in `re` module (`re.A` and others) do not work since Python 3.6.

### ISSUE THREAD

**Issue by foxik** [davidhalter/jedi#1225]
Using latest stable version of `jedi` and `parso` (0.12.1 and 0.3.1), `re.A` and other flags in `re` module are not included in computed completions (result of jedi.Script().completions()).

The problem is that since Python 3.6, they are added to the `re` module by updating `globals()`: https://github.com/python/cpython/blob/3.6/Lib/re.py#L161.

Given that parsing such source is probably beyond "reasonable", maybe the missing flags could be added by some exception list?

**Comment by davidhalter** [comment]
This is going to be solved, once typeshed is fully used: #1096.

In the typeshed branch it's already working, but a lot of other things are not. So please stay put. It will probably take a month or two until this is issue is solved. I'm closing, because a solution exists, it's just not merged, yet.
