### ISSUE TITLE
Handle python version

### ISSUE THREAD

**Issue by nigredo13** [davidhalter/jedi#1227]
Hi,
perhaps it was already answered...
I use jedi in my IDE that is written in python 2.7. 
But new projects are in python 3.x, so when I go to the definitions of some standard module function jedi brings me to the 2.7 source.
Is there some way to tell jedi in which version the source I'm working on is ?

**Comment by davidhalter** [comment]
There is an easy way to do this, you can specify environments, you can use `jedi.find_system_environments()` to find available versions. You can also use `jedi.get_system_environment('3')` to get the default Python3 environment or `jedi.get_system_environment('3.6') to get a more specific one.

The Environment needs to be given to the `jedi.Script()` instance.
