### ISSUE TITLE
Minor: date incorrect in news entry for 0.13.0

### ISSUE THREAD

**Issue by PeterJCLaw** [davidhalter/jedi#1231]
This is a really minor thing, but feels like it could confuse someone in the future.

The date reads "2018-01-02", yet as the entry dates from October 2nd, I think it should read "2018-10-02" (note transposition of the digits 1 and 0 in the month). I'm guessing this was a typo and is easily fixed.

**Comment by davidhalter** [comment]
I somehow forgot to push to master. It was fixed in 0.13.1. Thanks for noticing :)

**Comment by PeterJCLaw** [comment]
Ah, I was thinking of https://github.com/davidhalter/jedi/issues/1063#issuecomment-426095936, apologies for the lack of clarity.

**Comment by davidhalter** [comment]
Fixed that as well, thanks :)
