### ISSUE TITLE
Intellisense does not work within {} inside f-strings

### ISSUE THREAD

**Issue by DonJayamanne** [davidhalter/jedi#1232]
Original issues in VS Code:

![2797_unnecessary_suggest_f-string](https://user-images.githubusercontent.com/11466735/46550823-008c3c80-c88b-11e8-983a-0d3a8dda1bf2.gif)

https://github.com/Microsoft/vscode-python/issues/2797#issuecomment-427447698
https://github.com/Microsoft/vscode-python/issues/2386

**Comment by DonJayamanne** [comment]
I guess its just another one of those edge cases.

**Comment by davidhalter** [comment]
Feels like this was fixed a while ago in parso (or at least in jedi 0.14.0). Haven't had complaints anymore about f-strings.
