### ISSUE TITLE
Cannot get `goto_definitions` to Pytorch functions with retroactive docstrings

### ISSUE THREAD

**Issue by rhaps0dy** [davidhalter/jedi#1234]
The consequence is that one cannot get completions or docstrings from [Pytorch](http://pytorch.org/) methods. Here is how to reproduce this:

```py
import jedi
jedi.Script("import torch; torch.from_numpy", 1, 17).goto_definitions()
#                             ^ cursor is here
# response from REPL: [<Definition module torch>]
jedi.Script("import torch; torch.from_numpy", 1, 23).goto_definitions()
#                                   ^ cursor is here
# response from REPL: []   (an empty list)
```

I don't know enough about how jedi evaluates source files to properly debug this. However I reckon it's related to the fact that `torch` imports all functions from a C library, and adds the docstrings retroactively, e.g.

```py
add_docstr(torch.from_numpy,
           r"""
from_numpy(ndarray) -> Tensor
```

etc. (from https://github.com/pytorch/pytorch/blob/master/torch/_torch_docs.py#L1594-L1613 )

I would be very grateful if someone could give some guidance on where to look in jedi in order to fix this, or if someone could find a fix. Thank you for your time.

**Comment by davidhalter** [comment]
There is currently no way to fix this, because the way they add it is very very strange.

I think this has to wait until #626 is completed. Once we have a proper plugin infrastructure, this would be possible. For now it's not.

**Comment by t-vi** [comment]
Just a quick shout: PyTorch sould get type hint stub files in pytorch/pytorch#12500 .
Maybe this, combined #839, will already resolve quite a bit of the issues.
If there is a good way to make it easier for Jedi to get to the docstrings, do let me know, I could see if I can amend this.

P.S.. A type hint stub preview [is available](https://gist.github.com/t-vi/0d0ae013072f96f50fa11fbc2287e33b).

**Comment by davidhalter** [comment]
They have stub files now so this should be solved. Thanks for adding it!

@t-vi BTW: At least for Jedi, adding docstrings to stubs is not necessary. Jedi does gather that information from the original module.
