### ISSUE TITLE
`from ... import ...` for 'typing' leads to incorrect reported code structure

### ISSUE THREAD

**Issue by brettcannon** [davidhalter/jedi#1241]
Microsoft/vscode-python#2098

```python
from typing import Dict, Any, Union, Optional
```

That gets reported as `Dict` defining `Any` and `Union`. (The classifications of what the things are also off, but I'm not sure if that's our fault or not.)

![image](https://user-images.githubusercontent.com/54418/47190015-394cfc80-d2f4-11e8-8b73-9d97275ae81c.png)

**Comment by davidhalter** [comment]
I'm working on including typeshed, so this is all going to change radically. Hopefully only a few weeks until everything is working (including this).

**Comment by davidhalter** [comment]
Please let me know what you are using to generate this outline. I'm extremely unsure if that's even Jedi. I'm pretty sure it's not and I'm therefore closing this issue. 

The thing is, there's not really an outline feature in Jedi, so either you're abusing something in Jedi, or you're using something I'm not aware of, that could be used like this.
