### ISSUE TITLE
Is there a command that returns all available modules

### ISSUE THREAD

**Issue by amosbird** [davidhalter/jedi#1247]
I'm trying to build a interface in emacs that mimic the `go-import-add` command in python using jedi. Is there a command for listing available modules?

**Comment by davidhalter** [comment]
There is no such command. What do you have in mind? Just normal Python modules? Do you care about submodules?

I think the easiest option to implement this with Jedi is to just say `jedi.Script('import ').completions()`. This would give you all the possible module names.

If you don't care about builtin modules or namespaces, you could also use `pkgutil.iter_modules` (which Jedi is also using).

**Comment by davidhalter** [comment]
No answer given, I'm therefore closing.
