### ISSUE TITLE
Jedi on sublimeText3 too slow.

### ISSUE THREAD

**Issue by onebits** [davidhalter/jedi#1251]
When I typing code. It's very lagging...
For example:
content = res.content.decode('utf-8')
When I typing these code, on first "c" its lag..  res. its lag..
How to fix it ???
not a large file.
Look when i typing res. 
![jedi_lag](https://user-images.githubusercontent.com/40101424/48302838-d2aaaf80-e53c-11e8-9fd4-52ab08efd680.gif)

**Comment by davidhalter** [comment]
Please copy the code here, so we can try to reproduce!

**Comment by onebits** [comment]
@davidhalter 
import requests
with requests.session() as s:
    content = res.content.decode('utf-8')

try to type this.
The isuse was happend from 'content'

**Comment by davidhalter** [comment]
This is not the complete code.

**Comment by davidhalter** [comment]
This can only be fast with #1059. So I close this ticket in favor of that one.
