### ISSUE TITLE
no completions for @property decorated methods in Interpreter mode

### ISSUE THREAD

**Issue by Brow71189** [davidhalter/jedi#1259]
This script should reproduce the problem:
 
```python
import jedi

class B:
    def __init__(self):
        pass

    def see_me(self):
        pass

class A:
    def __init__(self):
        pass

    @property
    def b(self):
        return B()
    
    def get_b(self):
        return B()

a = A()

script = jedi.Interpreter('a.b.', [locals()])
comps = script.completions()
print('Interpreter completion (property): ', comps)

script = jedi.Interpreter('a.get_b().', [locals()])
comps = script.completions()
print('Interpreter completion (method): ', comps)
```
executing the script prints:

    Interpreter completion (property):  []
    Interpreter completion (method):  [<Completion: see_me>, ...]

When the method with the `@property` decorator is called, no completion is found by jedi. The "normal" method works just fine.
Also, when putting everything until `a = A()` into a string and using `jedi.Script` instead of `jedi.Interpreter` the correct completion is found for the `@property` decorated method, too.

**Comment by davidhalter** [comment]
This is working again. (Jedi 0.15.0). See discussions in #1299.
