### ISSUE TITLE
[Typeshed branch] Fail to cache module for path in root

### ISSUE THREAD

**Issue by micbou** [davidhalter/jedi#1264]
On the `typeshed` branch, running the code
```python
import jedi
jedi.Script('', path='/foo').completions()
```
raises the following exception
```python
Traceback (most recent call last):
  File "jedi\cache.py", line 141, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script.py", line 6, in <module>
    jedi.Script('', path='/foo').completions()
  File "jedi\api\__init__.py", line 181, in completions
    self._evaluator, self._get_module(), self._code_lines,
  File "jedi\cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "jedi\api\__init__.py", line 161, in _get_module
    self._evaluator.module_cache.add(names, ContextSet([module]))
  File "jedi\evaluate\imports.py", line 44, in add
    self._name_cache[string_names] = context_set
TypeError: unhashable type: 'list'
```
This doesn't occur if the path has more than one component (e.g. `/foo/bar`) or if it's the root itself. No issue on the `master` branch.

An easy fix would be to [always convert `string_names` to a tuple here](https://github.com/davidhalter/jedi/blob/881ffadb5cde7984c10e7857374e603356ace55a/jedi/evaluate/imports.py#L44) but this could hide a real issue.

**Comment by davidhalter** [comment]
Should be fixed now, please recheck.

**Comment by davidhalter** [comment]
Should be fixed now, please recheck.

**Comment by micbou** [comment]
Yes, I confirm it's fixed. Thanks!

**Comment by davidhalter** [comment]
If you have a bit of time, what is your general perception of the typeshed branch? Is it slower? Is it better?
