### ISSUE TITLE
Vim's omni completion does not work from Windows and macOS from f9cbc65

### ISSUE THREAD

**Issue by kashewnuts** [davidhalter/jedi#1266]
# Problems summary

Omni completion does not work from Windows and mac from [f9cbc65](https://github.com/davidhalter/jedi/commit/f9cbc65f2d114d6252a1b42f9deb958d54ab7b95)

- Windows: [subprocess/__main__.py](https://github.com/davidhalter/jedi/blob/bd1010bbd2693f189ff780eb21fc4294071cb280/jedi/evaluate/compiled/subprocess/__main__.py) opens in a separate window, and "Pattern not found" occurs from `f9cbc65`.
- macOS: "Pattern not found" occurs from `f9cbc65`.

## Expected

Revert `f9cbc65` and Omni complementation will work in Vim.
I have confirmed that it will work with versions before `f9cbc65` and after reverting commit.

## Environment:

|OS|Vim Version|Python Version|
|--|-----------|--------------|
|Windows 10 PRo|[Vim8.1.0005](https://github.com/koron/vim-kaoriya/releases/download/v8.1.0005-20180520/vim81-kaoriya-win64-8.1.0005-20180520.zip)|[3.5.4](https://www.python.org/ftp/python/3.5.4/python-3.5.4-amd64.exe)|
|macOS Sierra| [macvim 8.0.1633](https://github.com/splhack/macvim-kaoriya/releases/download/20180324/MacVim-KaoriYa-20180324.dmg)|[3.6.4](https://www.python.org/ftp/python/3.6.4/python-3.6.4-macosx10.6.pkg)|

**Comment by davidhalter** [comment]
Can you please post this in jedi-vim's issue tracker? This definitely the wrong one. Also note that there's probably already an issue for the Windows issue:

https://github.com/davidhalter/jedi-vim/issues/870

**Comment by kashewnuts** [comment]
Understood. I register to jedi-vim's issue tracker.

**Comment by zhanghang1989** [comment]
Is this solved? I am still having this trouble on MacOS High Sierra.

**Comment by davidhalter** [comment]
Please check the jedi-vim tracker. However there are a number of issues open at the moment.
