### ISSUE TITLE
Idea: documentation from inferred types

### ISSUE THREAD

**Issue by dimaqq** [davidhalter/jedi#1272]
How cool it would be if types inferred by jedi would be visible in autogenerated documentation.

Jedi understands type hints and sphinx doc types.

Ii'm thinking about the inverse of that...

**Comment by davidhalter** [comment]
Apart from generating type annotations for params/executions, what do you have in mind?

**Comment by dimaqq** [comment]
I was thinking just that actually, simply not having to type `: str` or `-> None` when that can be inferred.

**Comment by dimaqq** [comment]
Perhaps that should be a feature of mypy instead actually.

**Comment by davidhalter** [comment]
Closing in favor of #987, which is essentially the same.

@dimaqq It will probably be a feature of Jedi at some point, because the information is available. it's just a bit of work to confirm something to annotations.
