### ISSUE TITLE
Test failing with parso 0.3.2

### ISSUE THREAD

**Issue by FlingeR** [davidhalter/jedi#1274]
The following test is failing:
https://github.com/davidhalter/jedi/blob/95f835a014527f405db87b5352a9ac8f78683439/test/test_integration.py#L44

I think that is related to the f-string changes on parso 0.3.2.

Cheers.
Elias.

**Comment by davidhalter** [comment]
Thanks for mentioning it. I released parso v0.3.4.

Tests are passing again: https://travis-ci.org/davidhalter/jedi
