### ISSUE TITLE
Autocompletion Issue on Field of Field

### ISSUE THREAD

**Issue by mlangkabel** [davidhalter/jedi#1275]
Hi, currently I am the main author of the [SourcetrailPythonIndexer](https://github.com/CoatiSoftware/SourcetrailPythonIndexer), which we are basing on Jedi. First of all, thank you for providing and maintaining this great project!

However, when running Jedi on the following code, I encountered some strange behavior:

```python
class Bar:
    pass

class Foo:
    def __init__(self):
        self.bar = Bar()
        self.bar.baz = 9

foo = Foo()
baz = foo.bar.baz
print(baz)
```

Running Jedi to complete on `baz = foo.` (2nd last line) results in `bar` and `baz`, even though `baz` is not a field of `Foo`.
Running Jedi to complete on `baz = foo.bar.` does not result in any completions.

**Comment by davidhalter** [comment]
Thanks for finding this. `baz` definitely shouldn't be a completion. However `foo.bar.` won't return `baz`, it will only return all the underscore methods. This makes sense. side effects on classes  are not supported in Jedi (yet).

BTW: Please make sure to subscribe to #1063.

**Comment by mlangkabel** [comment]
Thank you for looking into this!
