### ISSUE TITLE
IPython completion (jedi.Interpreter) very slow when cwd is on NFS

### ISSUE THREAD

**Issue by roebel** [davidhalter/jedi#1276]
hello,

I am a longtime user of IPython and therefore the integrated jedi completer. I was mostly working on a Mac (no nfs) and completion does not create any issues there. Now I have turned to work on a Linux machine with my HOME directory mounted via NFS. There, I regularly have the problem that command completion blocks for quiet a while (20-30s) when I uncautiously hit TAB for completion (triggering jedi).

In studying this a little bit closer I found that I can avoid the completion problem by means of

  1. run ipython on a directory that is not on NFS
  2. setting Completer.use_jedi=False

I also tried to move the jedi_cache from the NFS folder to a local folder. This did not help. 
While I know that due to limited bandwidth our NFS is not extremly fast, still
 simply doing an 
```
ls . 
```
in the same NFS folder does not take more than a fraction of a second.
I searched a while in the ipython and jedi source code to find what might trigger the very sow response, but the only thing I found for now was that disabling jedi solves the problem, which is the solution I selected for the moment. I wonder if anybody can suggest a less dramatic approach.

Here a few details of my environment - I doubt this will make a difference though.

### Environment information
System: # 1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
Python: Python 3.6.8 |Anaconda custom (64-bit)| (default, Dec 30 2018, 01:22:34)

#### packages used
  jedi                      0.13.2                   py36_0
  ipython                   7.2.0            py36h39e3cac_0
  ipython_genutils          0.2.0                    py36_0

**Comment by davidhalter** [comment]
There shouldn't be a lot of file reads. I'm wondering what is happening there. Could you maybe debug it a bit more? You can also run strace or something similar.

**Comment by roebel** [comment]
yes strace that was a bright idea  - I have done this with jedi enabled
ipython  and get the following result (extract)

open("/net/inavouable/manage.py", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000009>
stat("/net/inavouable/setup.py", 0x7fff3a880400) = -1 ENOENT (No such file or directory) <0.000008>
stat("/net/inavouable/.git", 0x7fff3a880400) = -1 ENOENT (No such file or directory) <0.000008>
stat("/net/inavouable/.hg", 0x7fff3a880400) = -1 ENOENT (No such file or directory) <0.000008>
stat("/net/inavouable/requirements.txt", 0x7fff3a880400) = -1 ENOENT (No such file or directory) <0.000007>
stat("/net/inavouable/MANIFEST.in", 0x7fff3a880400) = -1 ENOENT (No such file or directory) <0.000008>
open("/net/.jedi/project.json", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.003116>
open("/net/manage.py", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.004675>
stat("/net/setup.py", 0x7fff3a880400)   = -1 ENOENT (No such file or directory) <0.004693>
stat("/net/.git", 0x7fff3a880400)       = -1 ENOENT (No such file or directory) <0.002670>
stat("/net/.hg", 0x7fff3a880400)        = -1 ENOENT (No such file or directory) <0.002670>
stat("/net/requirements.txt", 0x7fff3a880400) = -1 ENOENT (No such file or directory) <0.004387>
stat("/net/MANIFEST.in", 0x7fff3a880400) = -1 ENOENT (No such file or directory) <120.126989>
open("/.jedi/project.json", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000148>

So if I understand correctly all runs fast until stat("/net/MANIFEST.in") which  hangs for 120s.

/net is our directory for automounting NFS and MANIFEST.in is unfortunately a computer name in our network which triggers the automounter but MANIFEST.in is not prepared for being automounted, and so this operation has a timeout of about 2min.

So this seems to be the result of an unfortunate coincidence. 
May be you have an idea how to work around this?

Thanks

**Comment by roebel** [comment]
In fact I would very much not like to trigger autmounting anything while searching for completion in ipython but I am not sure whether given the strategy of finding projects this can be avoided.

**Comment by davidhalter** [comment]
If I were you I would just modify the variable `_CONTAINS_POTENTIAL_PROJECT` in `api/project.py`. Ths won't solve the problem in the long term, but it's at least a workaround and you might not even be working on this anymore in a year.

**Comment by roebel** [comment]
Good! I fixed it now with

  import jedi.api.project
  jedi.api.project._CONTAINS_POTENTIAL_PROJECT= ("setup.py",  '.git', '.hg', 'requirements.txt')

in my ipython profile.

> you might not even be working on this anymore in a year.
Things have changed - linux fell out of favour a few years ago, but due to a number of technical changes it will be the system of choice for as long as GPU calculations and AI remains a hot topic.

The new solution is clearly much more refined then disabeling jedi alltogether, still MANIFEST.in
files can be part of projects I am working on.

A  better solution would be if I could exclude directories from _is_potential_project
for example by means of adding a function to the project module that allows modifying
a list of directories that would never be considered as projects and _is_potential_project using this list to not run file tests inside these directories.

As I am maintaing numerous python installations on our linux machines that are used by many other colleagues it would be a bit difficult to do this as a local change. Would you be willing to consider a pull request if I come up with a working patch for such a modification?

Thanks
Axel

**Comment by davidhalter** [comment]
Sorry, but no. I think it's perfectly fine way to ask for a project. I mean come on, we're using a `stat()`. This system call shouldn't be that slow. I don't know what's wrong with your disk, but that's strange. - even it being NFS and all.

IMO the proper way for this issue is to fix your own issue. Since that might not be feasible, I would say roll out the hack that's now working for you. In the future you can replace this with custom `Script(..., project=my_local_directory)`. This will obviously be a public API and there's an easy way to use it.

**Comment by roebel** [comment]
I don't quite understand the reaction -  it may be you did not understand my explanantions correctly - my home directory is automounted (if you dont know autofs  see https://wiki.archlinux.org/index.php/Autofs) this means doing stat in the top level directory does not do NFS it does try to mount an NFS share (if such share exists). 

Now it happens that MANIFEST.in is the name of one of our computers (because we have a festival that is called MANIFEST and the server is related to that.) But it happens that this computer cannot be mounted, which leads to a timeout of 2min.

Please see wikipedia:
>/net
>A very common default automounter local path is of the form /net/hostname/nfspath where >hostname is the host name of the remote machine and nfspath is the path that is exported over >NFS on the remote machine. This notation generally frees the system manager from having to >manage each exported path explicitly via a central automounter map. 
So sure it is a rare coincidence that we have a machine with that name, still nothing seem wrong with that. On the other hand, given /net is a custom location for mounting machines, it seems not correct to assume it holds projects. Please note that mounting machines here triggers quite a machinery, and I don't think it is fine to trigger that for five names each time I hit TAB.

That said - I don't see how Script would be of any help for me, it is not me that implements completion it is IPython. If I understand your future vision correctly I would need to change IPythons code ?

Finally, I understand that you don't like patching your code behind the scenes - but it was you that started that idea. If you see a more clean solution, that's would be fine as well. 

If not - don't mind.

**Comment by davidhalter** [comment]
I'm just saying, that at the moment I don't see a fix that is beneficial to the majority of people vs. you.

I can understand that this is quite annoying for you - but I have to find a solution that works for most people.

**Comment by roebel** [comment]
I perfectly understand.

I currently am a bit under stress, once I have more time I may simply fork and create a version that does not search projects in /net or (from my point of view even better)  does not search projects in folders not belonging to the current user and for my own use build an anaconda package from that here

https://anaconda.org/roebel

thanks for your kind help and thanks for sharing your work.
Best
