### ISSUE TITLE
[Question]Using Jedi to get full qualified name of objects

### ISSUE THREAD

**Issue by maldil** [davidhalter/jedi#1278]
Hello Everyone,  

I am trying to use Jedi to do a python program analysis. I want to  know from the community, whether my requirement can be done using Jedi. 

Consider the following example, I want to get the fully qualified name of the `se` object referenced in the below code as `tensorflow.Session`. Is it possible with Jedi?
```
import tensorflow as tf

def run (se):
    x1 = tf.constant([1,2,3,4])
    x2 = tf.constant([5,6,7,8])
    result = tf.multiply(x1, x2)
    res = se.run(result) ## How to get the fully qualified name of se as tensorflow.Session
    print (res)

if __name__ == '__main__':
    en = tf.Session()
    run (en)
```

1. Does Jedi infer the types considering the third party libraries installed in the virtual environments ?

**Comment by davidhalter** [comment]
Please at least try to read the documentation next time ;-)

There is a property called full_name, that can help you with getting the qualified name. It's not exactly the same, but it will probably suffice.

Also third party libraries are very well understood and virtual envs are handled. So it shouldn't be a problem.
