### ISSUE TITLE
linter doesn't dig context managers

### ISSUE THREAD

**Issue by dimaqq** [davidhalter/jedi#1280]
test.py:

```py
with open("/dfga", "r") as fin:
    fin.read()
```

invocation:

```sh
> python -m jedi linter test.py
/path/to/test.py:1:27: E2 NameError: name 'fin' is not defined.
```

**Comment by davidhalter** [comment]
Thanks for trying the linter. I'll keep it open. However note that the linter is currently not being developed and I doubt that it will be for another year. We probably will create a database index #1059 first and then do proper linting. In the current iteration the linter is just not good enough anyway, so I don't even bother.

**Comment by davidhalter** [comment]
Looks like this was a more general error.
