### ISSUE TITLE
Jedi provides no completions for typed lists

### ISSUE THREAD

**Issue by d3r3kk** [davidhalter/jedi#1281]
Using this source code:

```python
from typing import List


class Test:
    name: str

    def __init__(self, name: str) -> None:
        self.name = name


class_t: List[Test] = []
class_t.
```

Jedi will return the empty list for completions on `class_t.` on the last line.

## Repro
1. Unzip this code ([typed_lists.zip](https://github.com/davidhalter/jedi/files/2853293/typed_lists.zip))
2. Open a terminal window
3. Navigate to wherever the unzipped code is
4. Create a venv `python -m venv .venv` (Windows, use `py -m venv .venv`)
5. Activate the venv `. .venv/bin/activate` (Windows, use `.venv\Scripts\activate` (or `Activate.ps1` if in powershell)
6. Install latest pip and jedi `python -m pip install -U pip jedi`
7. Run the `jedi_repro.py` script

### Expected results:

All run scenarios on the script result in > 0 completions.

### Observed results:

Only non-list or non-typed list scenarios result in > 0 completions.
Typed list scenarios all result in 0 completions.

---
*Note, this issue was originally discovered and reported on the VS Code Python Extension by @joeyak*, see Microsoft/vscode-python#4343

**Comment by davidhalter** [comment]
Can you please test with the typeshed branch?

**Comment by d3r3kk** [comment]
You bet. I may not have gotten this correctly though - please let me know if I haven't set things up quite right.

For clarity, here's my original results from running my `jedi_repro.py` script with the current `jedi-0.13.3`.
```
(.venv) D:\dev\typed_lists> python .\jedi_repro.py
Typed List, type=Custom Class, empty list [0])
Untyped List, 1 member of type Custom Class [46])
Typed List, type=str, declared only [0])
Untyped List, empty list [46])
Typed List, type=str, empty list [0])
Typed List, type=str, 1 member [0])
Typed Variable, type=str, Unset [78])
Untyped Variable, set to type str [78])
```

## Repro (update)

**Revised step 6** Install latest pip `python -m pip install -U pip` (19.0.3 at time of writing).

**Step 6.5** Install the typeshed branch of `jedi`. (Windows) `python -m pip install git+https://github.com/davidhalter/jedi.git@typeshed`

## Observed Result:
Results from running `jedi_repro.py`:
```
(.venv) D:\dev\typed_lists> python .\jedi_repro.py
Typed List, type=Custom Class, empty list FAILED, Exception [WinError 3] The system cannot find the path specified: 'D:\\dev\\typed_lists\\.venv\\lib\\site-packages\\jedi\\third_party\\typeshed\\stdlib'
Untyped List, 1 member of type Custom Class FAILED, Exception [WinError 3] The system cannot find the path specified: 'D:\\dev\\typed_lists\\.venv\\lib\\site-packages\\jedi\\third_party\\typeshed\\stdlib'
Typed List, type=str, declared only FAILED, Exception [WinError 3] The system cannot find the path specified: 'D:\\dev\\typed_lists\\.venv\\lib\\site-packages\\jedi\\third_party\\typeshed\\stdlib'
Untyped List, empty list FAILED, Exception [WinError 3] The system cannot find the path specified: 'D:\\dev\\typed_lists\\.venv\\lib\\site-packages\\jedi\\third_party\\typeshed\\stdlib'
Typed List, type=str, empty list FAILED, Exception [WinError 3] The system cannot find the path specified: 'D:\\dev\\typed_lists\\.venv\\lib\\site-packages\\jedi\\third_party\\typeshed\\stdlib'
Typed List, type=str, 1 member FAILED, Exception [WinError 3] The system cannot find the path specified: 'D:\\dev\\typed_lists\\.venv\\lib\\site-packages\\jedi\\third_party\\typeshed\\stdlib'
Typed Variable, type=str, Unset FAILED, Exception [WinError 3] The system cannot find the path specified: 'D:\\dev\\typed_lists\\.venv\\lib\\site-packages\\jedi\\third_party\\typeshed\\stdlib'
Untyped Variable, set to type str FAILED, Exception [WinError 3] The system cannot find the path specified: 'D:\\dev\\typed_lists\\.venv\\lib\\site-packages\\jedi\\third_party\\typeshed\\stdlib'
```

I found it odd that there was some files missing with a directory named `typeshed`, so I tried to install `typeshed` into my venv, alas no joy.

However, the target path of the `typeshed` seems different than what I'd expect, so I added this to my setup:

## Repro (Updated, again)
**Step 6.6** Install typeshed into the third_party target folder of jedi. (Windows) `python -m pip install -t .venv/Lib/site-packages/jedi/third_party typeshed`

## Observed Results
```
(.venv) PS D:\dev\typed_lists> python .\jedi_repro.py
Typed List, type=Custom Class, empty list [48])
Untyped List, 1 member of type Custom Class [48])
Typed List, type=str, declared only [48])
Untyped List, empty list [48])
Typed List, type=str, empty list [48])
Typed List, type=str, 1 member [48])
Typed Variable, type=str, Unset [80])
Untyped Variable, set to type str [80])
```

🎆 Huzzah! 🍾

**Comment by davidhalter** [comment]
thirdparty/typeshed is a git submodule :) But in any case I guess it's fine now so I will close. I'm still working on stabilizing that branch.
