### ISSUE TITLE
Incorrect options in autocompletion list

### ISSUE THREAD

**Issue by rbhanot4739** [davidhalter/jedi#1284]
I am using NCM2 as auto completion engine with NeoVim and below is my environment and config details

**OS** - `Ubuntu 16.04 LTS`
**Neovim** - `NVIM v0.3.2-208-g2841e89`

There seems to be some issue with `jedi` where in the options in the completion menu are not correct, it goes on to search the entire file tree and shows even the folders as modules in the completion list, I assume this due to change https://github.com/davidhalter/jedi/commit/4b276bae87a3170672f7ddb3e00f5851fe24d562
Here are the sample screenshots when used with both the language server and a separate completion for source `ncm2`.

![image](https://user-images.githubusercontent.com/19793591/52853457-b624a180-3141-11e9-9b45-30e46911381d.png)

![image](https://user-images.githubusercontent.com/19793591/52853462-b9b82880-3141-11e9-9011-a63bc421388b.png)

**Comment by rbhanot4739** [comment]
Any update on this?

**Comment by davidhalter** [comment]
I don't see the problem? There might be Python files in those folders?!

IMO this behavior is totally fine and even wanted. If there's Python files in `Pictures`, that's a folder you want to see. In the future we could check if a subtree contains Python files, but that's probably too hard to do.

Also: If you want to contribute to Open Source in a meaningful way, don't ask questions like "any update on this" a day after your initial post. That is just plain disrespectful to both the people working for free for you and to the other people in currently almost 150 open issues/pull requests for an answer.

If you want to actually contribute, try fixing stuff and creating pull request instead.
