### ISSUE TITLE
jedi crashes during completion

### ISSUE THREAD

**Issue by majuscule** [davidhalter/jedi#1288]
Jedi occasionally seems to get into a bad state and drops the following stacktrace:

```
Traceback (most recent call last):
  File "~/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 253, in completions
    completions = script.completions()
  File "~/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 179, in completions
    completions = completion.completions()
  File "~/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 98, in completions
    completion_names = self._get_context_completions()
  File "~/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 126, in _get_context_completions
    grammar, self._code_lines, self._module_node, self._position
  File "~/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/helpers.py", line 133, in get_stack_at_position
    raise SystemError("This really shouldn't happen. There's a bug in Jedi.")
SystemError: This really shouldn't happen. There's a bug in Jedi.
```

Unfortunately I am not sure how to reliably reproduce. 

##### jedi-vim version

 - jedi-vim git version: 0.9.0-67-gd02a72e
 - jedi git submodule status:  bd1010bbd2693f189ff780eb21fc4294071cb280 pythonx/jedi (v0.13.1)
 - parso git submodule status:  f1ee7614c921e538aa093cd96c78e9aaced7a8ca pythonx/parso (v0.3.3)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.version: `3.6.6 (default, Jul 17 2018, 18:14:44), [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]`
 - global site module: `~/.conda/envs/project/lib/python3.6/site.py`

##### Jedi

 - path: `~/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.13.1

##### Jedi environment: <SameEnvironment: 3.6.6 in ~/.conda/envs/project>

 - executable: ~/.conda/envs/project/bin/python3
 - sys_path:
    - `~/.conda/envs/project/lib/python36.zip`
    - `~/.conda/envs/project/lib/python3.6`
    - `~/.conda/envs/project/lib/python3.6/lib-dynload`
    - `~/.local/lib/python3.6/site-packages`
    - `~/.conda/envs/project/lib/python3.6/site-packages`

##### Known environments

 - <Environment: 3.6.6 in ~/.conda/envs/project> (~/.conda/envs/project/bin/python3.6)
 - <Environment: 3.5.2 in /usr> (/usr/bin/python3.5)
 - <Environment: 2.7.12 in /usr> (/usr/bin/python2.7)

##### Settings

```
  omnifunc=ale#completion#OmniFunc
        Last set from ~/.vim/bundle/ale/autoload/ale/completion.vim
  completeopt=menu,menuone,noselect,noinsert
        Last set from ~/.vim/bundle/ale/autoload/ale/completion.vim
```

**Comment by majuscule** [comment]
Just realized this only happens when i have `set paste`.

**Comment by Shougo** [comment]
>     * jedi git submodule status:  [bd1010b](https://github.com/davidhalter/jedi/commit/bd1010bbd2693f189ff780eb21fc4294071cb280) pythonx/jedi (v0.13.1)

0.13.2 is already released.  It seems old.

>     * parso git submodule status:  f1ee7614c921e538aa093cd96c78e9aaced7a8ca pythonx/parso (v0.3.3)

parso 0.3.4 is already released.  It seems old.

**Comment by davidhalter** [comment]
I will close this one since we have fixed similar issues in the recent past. See e.g. https://github.com/davidhalter/jedi/issues/1279

Thanks @Shougo for pointing this out.
