### ISSUE TITLE
Autocomplete doesn't work on type-hinted module classes as function parameters 

### ISSUE THREAD

**Issue by asavaritayal** [davidhalter/jedi#1292]
**Environment data**

- VS Code version: 1.31.0
- Extension version: 2019.1.0
- OS and version: macOS Mojave 10.14.3
- Python and version: 3.6.6
- Type of environment used: venv
- Affected Python packages: azure-functions 1.0.0b3

**Actual behavior**

VS Code doesn't auto-complete type-hinted method attributes in a function. 

![53509583-f0127380-3a70-11e9-921e-3e1dadf1e1c5](https://user-images.githubusercontent.com/8435148/53510239-55b32f80-3a72-11e9-9a84-77d899327d27.png)

**Expected behavior**

Expected behavior is similar to auto-complete for direct library references. 

![image](https://user-images.githubusercontent.com/8435148/53509664-17694080-3a71-11e9-9f7f-a7b017a8f6fb.png)

**Steps to reproduce**

![python1](https://user-images.githubusercontent.com/8435148/53509829-7f1f8b80-3a71-11e9-96b7-e55a9ce22d9d.gif)

**Comment by davidhalter** [comment]
If you want you can try the typeshed branch. Pretty much all the annotation stuff has been rewritten there. :) Just make sure to checkout the submodule as well.

**Comment by davidhalter** [comment]
Pretty sure this is working now, please use Jedi 0.14.0.

You probably have to wait for https://github.com/microsoft/vscode-python/issues/6294.
