### ISSUE TITLE
Limit or restrict the allowed keywords

### ISSUE THREAD

**Issue by lilliesAndRoses** [davidhalter/jedi#1303]
This is not an issue, but a question.
I want to use Jedi for a restricted editor where I want only select keywords to be allowed.
As an example, I do not want to support lambdas or closures.
Can I exclude this through any setting or do I need to tweak some code to achieve this?
Another use case is can I configure Jedi to allow only Python 2.7 builtins?

**Comment by davidhalter** [comment]
If you want to use Python 2.7 builtins you have to use a Python 2 Environment. This is definitely possible, but you might need to change your editor plugin.

I'm not sure what you mean with closures. You cannot disable lambda completion, this is also not something that will change. The only thing about keyword completions that will change is how Jedi completes directly after numbers (`3and`). There's an issue somewhere that deals with this, but I'm too lazy to search.

I'm closing this one, but happy to answer more questions.

**Comment by lilliesAndRoses** [comment]
No issues with closing the issue. 
What I need here is a capability by which not all the mumbo-jumbo of Python world is exposed.
I am looking for something by which I can control which 'features' or 'constructs' of python are shown in auto-completion. This may sound a little weird request but imagine a restricted IDE for young children where gradually different features of language are introduced/exposed. In the very first introductory version, I may not want to show lambda functions; I may not want to allow the user to create new classes. 
Currently, the only way I see to control this is by editing the grammar file in the 'parso'.
Is there any other way out?

**Comment by davidhalter** [comment]
Not really ;-) Restricting the grammar is of course an option, as is just creating a facade to filter certain things. Or a combination of those two.

This is really a "new" feature and I don't feel like I know how to help you with any of it. Jedi does work with a subset of Python of course.

Generally this feels like something where you want to create a wrapper around Jedi to get things done.

**Comment by lilliesAndRoses** [comment]
Thanks for sharing your ideas.
