### ISSUE TITLE
Unable to goto_assignment for for-loop-iterator

### ISSUE THREAD

**Issue by mlangkabel** [davidhalter/jedi#1304]
Consider the following code:
```python
for n in [1, 2, 3]:
  print(n)
```
If I call goto_assignment with a script on line 2, column 9 (e.g. the `n` inside the `print` call), jedi provides the location line 1, column 4 (e.g. the location of `n` inside the `for` statement), which is all nice and good.

However, if I call goto_assignment with a script on line 1, column 4, jedi does not return anything at all. I would expect it to provide the location line 1, column 4 for this case as well. What do you think?

Edit; Tested on commit 77a7792a

**Comment by davidhalter** [comment]
I agree!

**Comment by davidhalter** [comment]
Thanks for the report!
