### ISSUE TITLE
Unable to complete on an attribute defined via a property

### ISSUE THREAD

**Issue by ngoldbaum** [davidhalter/jedi#1305]
Following on from #1027, I don't seem to get "foo" or "bar" printed out:

```python
class CompleteAttrs(object):
    def __getattr__(self, name):
        if name == 'foo':
            return 1
        if name == 'bar':
            return 2
        raise AttributeError(name)

    def __dir__(self):
        return ['foo', 'bar'] + object.__dir__(self)

class MyClass(object):
    _ca = None

    @property
    def ca(self):
        if self._ca:
            return self._ca
        self._ca = CompleteAttrs()
        return self._ca

from jedi.api import Interpreter

itp = Interpreter("foo.ca.", [{'foo': MyClass()}])
for c in itp.completions():
    print(c.name)
```

If I add `property` to `ALLOWED_DESCRIPTOR_ACCESS` in `jedi/evaluate/compiled/access.py` then I get the result I expect, however it seems this breaks `test_property_error_oldstyle`. 

If this is intended behavior Is there a way I can keep my cached property attributes that are set up like this without breaking tab completion in IPython, or does jedi want me to define attributes at runtime in the `__init__` methods of my objects?

**Comment by ngoldbaum** [comment]
I guess this is a repeat of #1299

**Comment by davidhalter** [comment]
Thanks for checking the other tickets as well, that helps :) I guess it's kind of the same.

As I noted before, the problem with this is that Jedi wants to avoid code execution.

Would it help you if Jedi understood this properly:

```
    def ca(self) -> CompleteAttrs:
```

I know this is a bit cumbersome to write and think about, but it would at least help with autocompletion. Another pending thing would be a flag to enable code execution, but I feel like that's just a bad idea.

**Comment by ngoldbaum** [comment]
The type hint solution would be fine, although that won't fix old code that's already in the wild.
