### ISSUE TITLE
AssertionError: speed issue test_os_path_join

### ISSUE THREAD

**Issue by Ikke** [davidhalter/jedi#1306]
I'm building jedi for Alpine Linux, and run against an [AssertionError][0] when running the test suite on aarch64:
> assert single_time < time_per_run, message
--
597 | E AssertionError: speed issue <function test_os_path_join at 0xffffb721c6a8>, 0.4082823395729065
598 | E assert 0.4082823395729065 < 0.3

Because aarch64 is not the fastest platform, it can be expected that it perfoms slower. Is this a serious issue, or something we can work around?

[0]:https://cloud.drone.io/alpinelinux/aports/1099/3/2

**Comment by davidhalter** [comment]
It's not a problem at all. The speed tests have some margins, but essentially they are just there to alarm me that something went wrong and the build got significantly slower. It would probably also fail on old hardware.

**Comment by Ikke** [comment]
Thanks.

For now I have patched the threshold to be a bit higher to get the tests passing.
