### ISSUE TITLE
Goto assignement confuses variable and function names

### ISSUE THREAD

**Issue by mlangkabel** [davidhalter/jedi#1310]
Consider the following code:
```python
foo = 9

def foo(baz=foo):
  print(baz)
```
If I call goto_assignment with a script on the location where `foo` is used as a default argument for the function parameter `baz`, jedi provides the location of the definition of the function `foo`, instead of providing the location of the variable definition of `foo`, which is defined two lines above. When I rename the function to `bar`, jedi works as expected.

**Comment by drunkwcodes** [comment]
I think it worked well like that, which points out the fact of problematic definition change.

**Comment by davidhalter** [comment]
I think I fixed this a few months ago and now it's working in 0.14.0.
