### ISSUE TITLE
goto_assignments(follow_imports=True) goes to package's __init__.py

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1315]
`goto_assignments(follow_imports=True)` appears to not handle "from package
import module" correctly.

I would expect it to go to the module (`starlette/responses.py`), but it goes to `starlette/__init__.py`, which only has an assignment for `__version__`.

Test script:

```python
import jedi

source = "from starlette import responses"
script = jedi.Script(source, 1, len(source))

d1 = script.goto_assignments(follow_imports=True)[0]
d2 = script.goto_assignments()[0]
```

```
(Pdb++) d1.module_path
'…/Vcs/starlette/starlette/__init__.py'
(Pdb++) d2.module_path
'…/Vcs/starlette/starlette/responses.py'
(Pdb++) d1.module_name
'starlette'
(Pdb++) d2.module_name
'responses'
(Pdb++) d1
<Definition module responses>
(Pdb++) d2
<Definition module responses>
```

Beside of that the `description` of `Definition` (used in the repr) should get improved/fixed (to not be the same for both really).  (Having good repr methods is really crucial for people not used to the code after all.)

**Comment by davidhalter** [comment]
Just checked and it looks like this was fixed along the lines (latest master). Please test.
