### ISSUE TITLE
goto_assignments not working when a submodule name shadows top-level, with relative imports

### ISSUE THREAD

**Issue by spookylukey** [davidhalter/jedi#1317]
For example, if I have `foo/sys/bar.py` with some definition:

    THING = 1

 and in `foo/sys/baz.py` I have a relative import:

    from .bar import THING

Then `goto_assignments()` for `THING` returns an empty list. This applies if `sys` is replaced with any top-level module (anything from stdlib or any other installed package).

If I replace `sys` with some other module name that has no clash with a top-level name, then `goto_assignments` returns a `Definition` as expected.

Here are the steps which should reproduce it for you:

    cd ~/devel
    mkdir my_project
    cd my_project
    mkvirtualenv --python=`which python3.6` -a `pwd` my_project

    # Set of my sys.path to include project, and test that it works:
    echo `pwd` > ~/.virtualenvs/my_project/lib/python3.6/site-packages/my_project.pth  
    touch import_sanity_test.py
    cd ~                                                     
    python -c 'import import_sanity_test'   || echo 'sys.path not set up right'

    # Go back to project
     cd ~/devel/my_project  
    mkdir -p foo/normal foo/sys
    touch foo/__init__.py            
    touch foo/normal/__init__.py     
    touch foo/sys/__init__.py        
    echo 'THING = 1' > foo/normal/bar.py              
    echo 'THING = 1' > foo/sys/bar.py                 
    echo 'from .bar import THING' > foo/normal/baz.py 
    echo 'from .bar import THING' > foo/sys/baz.py    
    pip install jedi
    
    python -c 'import jedi; print(jedi.Script("from .bar import THING", 1, 17, "foo/normal/baz.py").goto_assignments())' 
    python -c 'import jedi; print(jedi.Script("from .bar import THING", 1, 17, "foo/sys/baz.py").goto_assignments())'
Results:

    [<Definition module THING>]
    []

Expected result:

    [<Definition module THING>]
    [<Definition module THING>]

Note that the shadowing is in the name of the sub-module, not the parent module, so I wouldn't expect any problems. If I use an absolute import instead the definition is found correctly.

I tried creating a bug for this, but my first attempt didn't show the bug, I'm not sure how the test environment might be different or what the exact things are that are triggering it, so I thought a clear bug report would be better.

The bug also exhibits if jedi is installed in a different virtual environment and an `Environment` is passed to `Script`, and if absolute paths to the modules are passed. In other words, I can't find a way around it other than renaming all affected modules, or using absolute imports everywhere.

**Comment by spookylukey** [comment]
After testing with master, this seems to work now, but I may need to re-open, because I thought I was originally seeing this bug on master.

**Comment by spookylukey** [comment]
I can confirm now - this bug affects 0.13.3, but not master.

**Comment by davidhalter** [comment]
Yeah I fixed some things about relative imports. Unfortunately the really big fixes for relative imports (everything should work there, and I really mean that, I wrote a ton of tests) are on the typeshed branch.
