### ISSUE TITLE
Make PySide2 stubs work when loaded through Qt.py

### ISSUE THREAD

**Issue by fredrikaverpil** [davidhalter/jedi#1318]
With PyCharm, all you have to do is to `pip install pyside2 qt.py` into your venv, and autocompletion/intellisense will work thanks to the official PySide2 stubs:

![pycharm](https://user-images.githubusercontent.com/994357/57138455-fe537780-6db2-11e9-88f9-f6a2d384ec26.png)

This is what happens with jedi in vscode:

![jedi](https://user-images.githubusercontent.com/994357/57138469-06abb280-6db3-11e9-8ca9-25fbc985efa5.png)

...and just for completion, this happens with the Python language server (jedi disabled) in vscode (not relevant here):

![pylangserver](https://user-images.githubusercontent.com/994357/57138510-1f1bcd00-6db3-11e9-9792-5df292e3b719.png)

This was all tested using PySide2 5.12.3.

**Comment by dwtd** [comment]
I tried this on my Windows 7 workstation and it doesn’t seem to work.  The .pyi files are nowhere to be found.

This is immediately after installing PySide2 v5.12.13 and Qt.py.  Is it possible this is OS-dependent? (looks like you’re on a Mac?)

**Comment by fredrikaverpil** [comment]
On my mac, I just `pip install pyside` and I see this:

```bash
fredrik@faverpil ~/code/repos/stubs/venv/lib/python3.7/site-packages/pyside2 
$ ls *.pyi
Qt3DAnimation.pyi       QtCore.pyi              QtNetwork.pyi           QtScxml.pyi             QtWebEngine.pyi
Qt3DCore.pyi            QtDataVisualization.pyi QtOpenGL.pyi            QtSensors.pyi           QtWebEngineCore.pyi
Qt3DExtras.pyi          QtGui.pyi               QtPositioning.pyi       QtSql.pyi               QtWebEngineWidgets.pyi
Qt3DInput.pyi           QtHelp.pyi              QtPrintSupport.pyi      QtSvg.pyi               QtWebSockets.pyi
Qt3DLogic.pyi           QtLocation.pyi          QtQml.pyi               QtTest.pyi              QtWidgets.pyi
Qt3DRender.pyi          QtMacExtras.pyi         QtQuick.pyi             QtTextToSpeech.pyi      QtXml.pyi
QtCharts.pyi            QtMultimedia.pyi        QtQuickWidgets.pyi      QtUiTools.pyi           QtXmlPatterns.pyi
QtConcurrent.pyi        QtMultimediaWidgets.pyi QtRemoteObjects.pyi     QtWebChannel.pyi
```

You don't see them inside the package?

**Comment by dwtd** [comment]
Unfortunately no.  I also installed via pip (`pip install pyside2 qt.py`), but when I attempt the same `ls`, I get this:
```
$ cd venv/Lib/site-packages/pyside2
$ ls *.pyi
ls: cannot access '*.pyi': No such file or directory

$ python --version
Python 3.6.6
```
The directory seems to contain everything _but_ .pyi files.  I get nothing from a `find` command run from the `venv` root.

**Comment by ColinKennedy** [comment]
I installed PySide2 / Qt.py for Python 2 and the .pyi files are there for me

	$ cd /home/selecaoone/.local/lib/python2.7/site-packages/PySide2 && ls *.pyi
	Qt3DAnimation.pyi  Qt3DRender.pyi           QtGui.pyi                QtNetwork.pyi       QtQuick.pyi          QtSql.pyi           QtWebChannel.pyi        QtWidgets.pyi
	Qt3DCore.pyi       QtCharts.pyi             QtHelp.pyi               QtOpenGL.pyi        QtQuickWidgets.pyi   QtSvg.pyi           QtWebEngineCore.pyi     QtX11Extras.pyi
	Qt3DExtras.pyi     QtConcurrent.pyi         QtLocation.pyi           QtPositioning.pyi   QtRemoteObjects.pyi  QtTest.pyi          QtWebEngine.pyi         QtXmlPatterns.pyi
	Qt3DInput.pyi      QtCore.pyi               QtMultimedia.pyi         QtPrintSupport.pyi  QtScxml.pyi          QtTextToSpeech.pyi  QtWebEngineWidgets.pyi  QtXml.pyi
	Qt3DLogic.pyi      QtDataVisualization.pyi  QtMultimediaWidgets.pyi  QtQml.pyi           QtSensors.pyi        QtUiTools.pyi       QtWebSockets.pyi

I installed using 

    python -m pip install PySide2 Qt.py --user

**Comment by davidhalter** [comment]
@dwtd You might need to try `pip install --upgrade`.

@ColinKennedy  @fredrikaverpil So I suppose with the current master branch completion for PySide2 is not working but not for Qt.py?!

**Comment by ColinKennedy** [comment]
I'll have to look into this more over the weekend as I'm short for time but I wasn't aware that Jedi supported .pyi files. https://github.com/davidhalter/jedi/issues/839

Also there's a thread on PyCharm / Intellisense support which may be relevant to this issue thread.
https://github.com/mottosso/Qt.py/issues/199

**Comment by dwtd** [comment]
Thanks, all.  I tried the same install on my Mac, and sure enough, the .pyi files are installed there.  Looks like this might be specific to Windows 7.  I also tried copying the .pyi files from my Mac to my PC (total hack I know) but no luck there either.

@davidhalter Thanks for the suggestion.  I confirmed that the python modules in my virtual environment are all current.

@ColinKennedy Thanks for the link to the other thread.  I had actually started there, wasn't able to get things working, and then found this thread.

I'll switch my project back to pure PySide2 for now, but I'm happy to help troubleshooting if you all have additional ideas.

**Comment by fredrikaverpil** [comment]
I can confirm that I also do not see the *.pyi files on Windows. I have posted about this [in the PySide2 gitter channel](https://gitter.im/PySide/pyside2?at=5ce81dfdad024978c620ba67).

> @ColinKennedy @fredrikaverpil So I suppose with the current master branch completion for PySide2 is not working but not for Qt.py?!

@davidhalter I am unsure how I can make use of the master branch to try it out. I am using vscode. Can I somehow replace the bundled jedi with the master branch one?

**Comment by fredrikaverpil** [comment]
@davidhalter I realized jedi is just dumped into a folder within the vscode-python extension. I tried replacing it, but then jedi broke completely, it seems. I have [reached out](https://twitter.com/fredrikaverpil/status/1132009301533450240?s=20) to some of the devs to see if they can give me a pointer on any additional steps I must take...

**Comment by fredrikaverpil** [comment]
@davidhalter I got jedi from master branch working in vscode now. I can confirm that autocomplete works with PySide2 but not with Qt.py.

![pyside2](https://user-images.githubusercontent.com/994357/58355475-c5b83280-7e74-11e9-88c2-1e580191326b.png)

![qtpy](https://user-images.githubusercontent.com/994357/58355479-c94bb980-7e74-11e9-8149-dce3e1a17a51.png)

I am not sure what this proves, as the autocompletion with PySide2 fine worked with jedi 0.12.0 (bundled with the current vscode extension).

**Comment by fredrikaverpil** [comment]
It's possible that something needs to be done with the vscode-python custom [completion.py](https://github.com/microsoft/vscode-python/blob/master/pythonFiles/completion.py) file to make this all work?

**Comment by fredrikaverpil** [comment]
Quick proof of stubs working in vscode:

![Screenshot 2019-05-24 at 23 43 11](https://user-images.githubusercontent.com/994357/58358096-b7badf80-7e7d-11e9-8f0e-39a9f7604192.png)

Although the stubs bundled with PySide2 cannot be loaded through Qt.py (which is what this issue is about).

**Comment by fredrikaverpil** [comment]
Apparently, the .pyi files are not bundled on Windows for some reason...

Here is a quick test of using .pyi files in vscode: https://github.com/davidhalter/jedi/issues/1318#issuecomment-495796223
Unfortunately, the PySide2-bundled .pyi files are not picked up by Qt.py - which that issue is all about.

**Comment by davidhalter** [comment]
For the second step you could also just write: `self.environment = jedi.api.environment.get_cached_default_environment()`.

**Comment by fredrikaverpil** [comment]
> For the second step you could also just write: ...

@davidhalter ah, yes - much better. 

Do you think that the Qt.py "passthrough" is not working because of jedi or because of vscode's jedi implementation?

**Comment by davidhalter** [comment]
The Qt passthrough is not working, because it's dynamic. If you look at the source code, you can see that it's even really hard to understand for a human.

There's a couple of possible solutions:

- Just don't use Qt.py and use PySide2 instead :)
- Copy the stubs from PySide2 and save them inside Qt-stubs.
- Remap Qt to to PySide in Jedi.
- Write your own Qt module that looks like this:

```
try:
    from PySide2 import *
except ImportError:
    from PyQt4 import *
```
Not sure though how much of the logic inside Qt.py is actually needed.

There's absolutely no way Jedi ever understands the crazy logic of Qt.py without hardcoding it.

**Comment by fredrikaverpil** [comment]
> If you look at the source code, you can see that it's even really hard to understand for a human.

Which source code are you referring to?
I am guessing you mean Qt.py 😉 and in case you have the time;

I am one of the developers behind Qt.py and all it really does is replace itself with the Qt binding you have available in your environment (e.g. PySide2). The core purpose of Qt.py is to provide a way to write PySide2 code which is backwards compatible with PySide/PyQt4 (and will also work with PyQt5). And for this purpose, the way the replacement is performed gets complicated. For example, a certain module was moved between Qt4 and Qt5 and thus needs remapping.

Qt.py is [widely used and adopted](https://github.com/mottosso/Qt.py#whos-using-qtpy) in the feature films business, where a bunch of Qt-based 3D/animation software which has Python scripting capabilities are used in a variety of versions within the same company. Nobody wants to maintain separate code for all of these Qt bindings and Qt.py makes it possible avoid that.

So, as you might imagine us working with Qt.py sorely miss the intellisense/autocompletion... and here we are 😄 

For some reason, this kind of "passthrough" just works in PyCharm and I am trying to figure out how this is possible and if this can somehow be enabled for my favourite editor (vscode) as well, and Jedi looks like my best bet right now. But I take it then that you don't think Jedi can enable this behavior?

There is no way I can add the location of the desired .pyi files to `sys.path` manually or something?

> Remap Qt to PySide in Jedi.

Oh, this sounds interesting but I am not sure in which way you mean. How would I go about trying this?

___

I just tweaked the file structure a little bit and now I can actually make use of the vanilla PySide2 .pyi files when using Qt.py. So perhaps this is the best way forward: https://github.com/mottosso/Qt.py/issues/199#issuecomment-496025846 unless you can come to think of a less brute force approach?

Either way, I am very grateful for your work and I am super happy to see you devoted your time to add support for typeshed/stubs!

As soon as jedi hits 0.14.0 I'll make a PR to get it into vscode! ❤️

**Comment by davidhalter** [comment]
> Oh, this sounds interesting but I am not sure in which way you mean. How would I go about trying this?

It's something that would need either a plugin structure for Jedi (which isn't public, yet) or we have to hard-code it within Jedi, which I really don't like.

So IMO tweaking the file structure is probably the best idea for now. Since you create a compatibility layer between different projects, separate stubs are probably the way to go anyway.

**Comment by fredrikaverpil** [comment]
Ok. Thanks for clarifying. I will close this issue.
