### ISSUE TITLE
Auto-completion does not work for Image object created using Image.open() method when using PIL

### ISSUE THREAD

**Issue by jdhao** [davidhalter/jedi#1322]
I am using deoplete-jedi to provide auto-completions inside Neovim. I found out that auto-completion does not work if I create an Image object instance using [Image.open()](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.fromarray) method when using [Pillow](https://pillow.readthedocs.io/en/stable/index.html). But for Image instance created using [Image.new()](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.new) method, the auto-completion works correctly. 

The below code shows the differences:

```
import jedi

source1 = '''
from PIL import Image
im = Image.new('test.jpg', (128, 128))
im.
'''

script1 = jedi.Script(source1, 4, len('im.'), 'example1.py')
print(script1.completions())

source2 = '''
from PIL import Image
im = Image.open('test.jpg')
im.
'''
script2 = jedi.Script(source2, 4, len('im.'), 'example2.py')
print(script2.completions())
```

Since the two methods both return an Image object, I do not know why the auto-completion behaves differently.

# Version info
+ Python: Python 3.6.8
+ jedi: 0.13.3 
+ Pillow: 5.2.0

**Comment by davidhalter** [comment]
Please don't post in two places, I answered on stackoverflow as well:

https://stackoverflow.com/questions/56023777/jedi-completion-does-not-work-for-image-object-created-using-image-open-method

The problem typically is that things like `Image.open()` do things like caching, where it's pretty much impossible to infer the right type.

In this example (look at https://github.com/python-pillow/Pillow/blob/master/src/PIL/Image.py#L2690), Jedi tries to follow `im` -> `_open_core(...)` -> other `im` -> `factory(...)` -> `factory` seems like `factory, accept = OPEN[i]` -> but what is `OPEN` -> it's defined as an empty `{}`, and filled in `register_open()` or from the outside -> `register_open` is not called in the same file.

And that's where Jedi stops searching for solutions. So you can see it's not always possible to infer types. Even I'm not sure what the returned type will be and I tried to look at it for 10 minutes. The solution is usually stubs/type annotations for this.

**Comment by jdhao** [comment]
Thanks for your answer. I tried to use type annotations to help jedi infer the returned types. I tried two ways  : function annotations and inline type hints for assignment, as indicated [here](https://github.com/davidhalter/jedi/blob/master/docs/docs/features.rst#type-hinting). But only function annotation works.

# Function annotation (works)

I find the source file of `Image.open()` in my system and change the following definition

```
 def open(fp, mode="r") :
```

to 

```
 def open(fp, mode="r") -> Image:
```

Now the auto-completion works for instance returned by `Image.open()`.

# Inline type hints for assignment

But if I use the inline type hints for the returned types, the auto-completion does not work anymore. My test script is:

```
import jedi

source = '''
from PIL import Image
im = Image.open('test.png')  # type: Image
im.
'''

script = jedi.Script(source, 4, len('im.'), 'example.py')
print(script.completions())
```

The print function shows an empty list.

**Comment by davidhalter** [comment]
Type hints should probably work quite a bit better once the typeshed branch (or the second version ts2 branch) is merged.
