### ISSUE TITLE
Argument list is shown in docstring area in few cases

### ISSUE THREAD

**Issue by karrtikr** [davidhalter/jedi#1327]
[Original Issue tracker link on vscode-python](https://github.com/microsoft/vscode-python/issues/5577)
Related issues:
- [Intellisense parameter info is incorrectly formatted if declaration is too long #4127](https://github.com/microsoft/vscode-python/issues/4127)
- [#5610](https://github.com/microsoft/vscode-python/issues/5610)

## Expected behaviour

Show all args at the appropriate place.

## Actual behaviour

![image](https://user-images.githubusercontent.com/16167062/57346506-57d7ef80-7181-11e9-8d28-5e710abf0d2d.png)

![image](https://user-images.githubusercontent.com/16167062/57303932-eeb89380-7110-11e9-9f0a-17012c1bfc9c.png)

Full arg list is not shown in the correct area and disappear when typing.

## Steps to reproduce:
1. `import torch`
2. `torch.nn.Conv2d(`
3. wait for the signature help
4. type first few args and the rest of them disappear

---

**Comment by davidhalter** [comment]
This was fixed in Jedi 0.14.0 (just checked).
