### ISSUE TITLE
Parameter intellisense in some cases doesn't directly appear, unless function is modified

### ISSUE THREAD

**Issue by karrtikr** [davidhalter/jedi#1328]
Please refer to [vscode-python #5623](https://github.com/microsoft/vscode-python/issues/5623) for elaborate description. Do let me know if you need anything else.

### STEPS TO REPRODUCE

- Create this file, and check intellisense of parameters `ss` and `lyst` within function. Observed results are printed within functions.

```
#!/usr/bin/env python
# encoding: utf-8
# ===============================================================================
#
#         FILE:
#
#        USAGE:
#
#  DESCRIPTION:
#
#      OPTIONS:  ---
# REQUIREMENTS:  ---
#         BUGS:  ---
#        NOTES:  ---
#       AUTHOR:  YOUR NAME (),
#      COMPANY:
#      VERSION:  1.0
#      CREATED:
#     REVISION:  ---
# ===============================================================================

import time
from functools import wraps

def count_run_time(func):
    """
    计时修饰器

    :param func:
    :return:
    """
    @wraps(func)
    def _func(*args, **kwargs):
        _start = time.time()
        rt = func(*args, **kwargs)
        print("[func: %s] cost @%.6fs" % (func.__name__, time.time() - _start))
        return rt
    return _func

def example_1(ss: int, lyst: list):
    print("working")

def example_3(ss: int, lyst: list):
    """
    33. some doc

    :param s1:
    :return:
    """
    print("working")

@count_run_time
def example_5(ss: int, lyst: list):
    print("ss ok, lyst not, abc lyst??")

@count_run_time
def example_7(ss: int, lyst: list):
    """
    33. some doc

    :param s1:
    :return:
    """
    print("ss not, lyst not, abc lyst??")

```

### CURRENT BEHAVIOR

![exp](https://github.com/x2x4com/py_ds/raw/master/docs/vscode-python_5.gif)

From the observations, I see two factors:

No decorator, no doc string - WORKS
No decorator, doc string - WORKS
Decorator, no doc string - PARTIALLY WORKS
Decorator, and doc string - DOESN'T WORK

**Comment by davidhalter** [comment]
Hi @karrtikr Thanks for these issues. If you want to help further (especially with this issue), please write it with proper Jedi calls. It's way clearer what happens and I can reuse your Jedi calls to write proper Jedi tests to fix your issue.

**Comment by karrtikr** [comment]
Hey @davidhalter ,
Apologies, i am not aware of Jedi calls as well, have to look at them from scratch.
Tagging the original issue author, @x2x4com, if he wants to help further.

**Comment by davidhalter** [comment]
0.14.0 makes this work. My machine had issues with the huge gifs. Please next time just give me the code with comment instructions ;-)
