### ISSUE TITLE
Go to definition (F12) doesn't go to a global variable defined in Python source file

### ISSUE THREAD

**Issue by karrtikr** [davidhalter/jedi#1329]
[vscode-python #5034](https://github.com/microsoft/vscode-python/issues/5034)

## Environment data

- VS Code version: 1.32.3
- Extension version: 2019.3.6215
- OS and version: Windows 10
- Python version: 3.7.3

## Expected behaviour

Pressing F12 on a global variable defined in a Python source file should simply go to its definition.

## Actual behaviour

Go to definition on a global variable defined in a Python source file results in a "No definition found" message.

## Steps to reproduce:
1. Copy the following code:
```
import socket

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
```
2. Place your caret over AF_INET, and press F12. This results in a  "No definition found" message.

**Comment by davidhalter** [comment]
For me this is working (current master branch). The problem is that AF_INET is defined in `_socket` which is a builtin module. There is no Python definition and VS code probably decides not to show that it's in a builtin module.

See the shortened version:
```
>>> import jedi
>>> jedi.Script('import socket; socket.AF_INET').goto_definitions()
[<Definition full_name='socket.AddressFamily', description='instance AddressFamily'>]
>>> jedi.Script('import socket; socket.AF_INET').goto_assignments()
[<Definition full_name='_socket.AF_INET', description='instance AF_INET'>]
```

**Comment by davidhalter** [comment]
I just realized that it's defined in typeshed. So my bad, it should actually go to definition.

**Comment by davidhalter** [comment]
It's working now in 0.14.0.
