### ISSUE TITLE
Line breaks disrupt natural flow of text in tooltip parameter hints

### ISSUE THREAD

**Issue by karrtikr** [davidhalter/jedi#1330]
**FEATURE REQUEST:** Improve support for natural flow of text in tooltip

Original issue: [vscode-python #5633](https://github.com/microsoft/vscode-python/issues/5633)

## Environment data

- VS Code version: 1.33.1
- Extension version (available under the Extensions sidebar): 2019.4.12954
- OS and version: Arch Linux
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.3

## Expected behaviour

Tooltip text flows naturally disregarding hard breaks in the original docstring. 

## Actual behaviour

Natural text flow is interrupted because of the interaction between the width of the tooltip popup and the location of hard breaks in the docstring (which assume a larger viewport).

![image](https://user-images.githubusercontent.com/16167062/57346506-57d7ef80-7181-11e9-8d28-5e710abf0d2d.png)

**ISSUE HERE**
```
of several
input
planes
```
Hardbreak after "input" interrupt the natural flow.

## Steps to reproduce:
**JEDI AS INTELLISENSE IS SELECTED**
1. Create a python file
1. `import torch`
2. `torch.nn.Conv2d(`
3. wait for the signature help

## Some suggestions

Many editors (vscode included) provide heuristic text formatters as builtins or as extensions.

* Vim: http://vimdoc.sourceforge.net/htmldoc/change.html#fo-table
* Emacs: the famous `Alt-q` (fill-paragraph) https://www.gnu.org/software/emacs/manual/html_node/emacs/Fill-Commands.html
* Rewrap (vscode extension): https://marketplace.visualstudio.com/items?itemName=stkb.rewrap
* magic-reflow (atom extension): https://github.com/josh-berry/magic-reflow

Moreover, font size could be reduced (indeed, for a tooltip, current size looks too big).  Atom does this and the popups are really not much larger than vscode ones, but the layout of the text is superior.

## Related issues

https://github.com/microsoft/vscode-python/issues/5577, https://github.com/microsoft/vscode-python/issues/5610, https://github.com/microsoft/vscode/issues/14165,
https://github.com/microsoft/vscode/issues/38663

Some of the referenced issues suggest that changes upstream could improve the situation for vscode-python, but anyway I believe there still is room for improvement and no popup width short of 80 characters will ever be right, anyway.

**Comment by davidhalter** [comment]
Good idea. I'm currently reworking the docstring stuff anyway.

**Comment by memeplex** [comment]
I'm not sure whether it is jedi that does this or vscode, but some docstrings are better formatted than others (I mean, not in the parameter hints popup, but similar text at other popups). See for example the screenshot in https://github.com/microsoft/vscode-python/issues/5633#issuecomment-494181217.

**Comment by davidhalter** [comment]
Closing this, because as mentioned in #1366, there's for example RST docstrings that are not a paragraph. The same is true for a lot of other things that people use in different ways. If you can give me a good algorithm to fix this for at least RST, I might reconsider, but until that point I will close it.
