### ISSUE TITLE
Does not handle following instance created via `await`

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1335]
Given the following test file, goto-definition works for `foo` on instances for `c`, and `d`, but not `e` (the last one), which gets instantiated via `e = await C.async_for_x()`.

```python
class C:
    @classmethod
    def for_x(cls) -> "C":
        return cls()

    @classmethod
    async def async_for_x(cls) -> "C":
        return cls()

    def foo(self):
        pass


c = C()
c.foo()

d = C.for_x()
d.foo()


async def f():
    e = await C.async_for_x()
    e.foo()
```

I am using Jedi master (7bd36692, i.e. with typeshed), and it uses the ` -> "C"` return annotation.

**Comment by davidhalter** [comment]
Just investigated. It's a bug. async def doesn't seem to work in combination with classmethod.

**Comment by blueyed** [comment]
Awesome, thanks!
