### ISSUE TITLE
goto might end up in .pyi file

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1338]
Given the following script:
```python
import requests


class _HeaderDict(requests.packages.urllib3._collections.HTTPHeaderDict):
    pass
```

Both goto methods (in jedi-vim) on `HTTPHeaderDict` will end up in the `.pyi` file (`jedi-vim/pythonx/jedi/jedi/third_party/typeshed/third_party/2and3/requests/packages/urllib3/_collections.pyi`).

Bisected to https://github.com/davidhalter/jedi/commit/329270e4446a3fd1fd3a06efc470b04e736bba08.

(Note that on that commit it also fails to "goto requests" (jedi-vim: Couldn't find any definitions for this.), but that is fixed on Jedi master (4b32626).)

Jedi v0.13.3 fails to goto "HTTPHeaderDict" ("Couldn't find any definitions for this."):
`requests.packages.urllib3` fails already, caused by dynamic imports I guess: https://github.com/kennethreitz/requests/blob/6f81e78dfe0b7419bde97cae594febfffab8e431/requests/packages.py ..

So there is likely not much Jedi can do there easily, and having goto go to the type definitions is better than nothing maybe then, but confused me (therefore this issue).

Maybe jedi-vim should display a message in this case for example?

**Comment by davidhalter** [comment]
Yeah, IMO this is something that IDE's have to care about. IDE's can just check if the output is a stub: `Definition.is_stub()`, which is what jedi-vim could do.

At the same time, if there's really a need, we could also add a parameter like `goto_definitions(allow_stubs=True)`.

**Comment by blueyed** [comment]
Great.
Thanks for the input - closing this then.
I think it is fine for now, especially with regard to Jedi.

**Comment by blueyed** [comment]
I think it might be useful even to explicitly goto a stub, e.g. to check where/how a type is defined.

I've tried this quickly in jedi-vim by filtering definitions/assignments by `x.is_stub()`, but it does not appear to work - at least if there are non-stub definitions.

Do you think it makes sense?  How should this be implemented with regard to the Jedi API - is it possible already?

**Comment by davidhalter** [comment]
Sorry I didn't mention this, but I'm already using something like that. I will push it soon. It's just very rough at the moment, but it will appear in a PR.

Just FYI you can use Definition.goto_stubs() for one direction and Definition.goto_assignments() for the other.

**Comment by blueyed** [comment]
Great, looking forward to it (but no hurry :))
