### ISSUE TITLE
Automatically or manually unload modules to free memory

### ISSUE THREAD

**Issue by felixhao28** [davidhalter/jedi#1340]
Hi I am using jedi in a service and it processes a lot of code a day. That leads to the issue of a very large memory consumption because all modules are loaded. Each jedi process takes 3Gb of memory and I have 4 such processes. My suggestion is can we have a way to unload less frequently used modules to keep the memory consumption in check?

**Comment by davidhalter** [comment]
Yes, I agree. I'm actually surprised that nobody has brought this up previously. I've known for a while that it's a problem, but a lot of people seem to be working with less modules (myself included).

If you want to change something, please consider working on parso's caching mechanism. There's probably the problem.

My personal take on it is that we probably have to get rid of "old" parsed modules every once in a while, but I don't really have time to do that at the moment. Jedi itself doesn't really do caching, it's just parso.

BTW: One of the issues with Python is that it doesn't really release memory, it just holds it so you can reuse it later.

**Comment by davidhalter** [comment]
Now instead of 3 GB, those processes should take probably like 600MB. I hope that's not too much. But in general, it's just hard to optimize with Python. Let me know if this is OK for you. Long term I might rewrite Jedi in Rust and at that point, it would definitely take less memory (and Rust can free memory as well).

**Comment by felixhao28** [comment]
I installed 1TB of memory on our server as a "workaround". It is still good to know there is a software-based solution.

**Comment by davidhalter** [comment]
LOL. Can you please tell me what you are working on? I would be very interested, because that sounds like an extreme amount of Python files.

**Comment by felixhao28** [comment]
![py](https://user-images.githubusercontent.com/2417391/71813794-924daf80-30b5-11ea-8e71-2c9ab1b45276.gif)

A code completion service powered by deep learning. It used to be a web service. Now we are also releasing a version to run the service on client-side. It supports python and java for now and javascript is coming next.

**Comment by davidhalter** [comment]
So basically you're working for a competitor of kite.com? Or https://tabnine.com/?

**Comment by felixhao28** [comment]
Exactly

**Comment by davidhalter** [comment]
Is there a product that one can try/look at?

**Comment by felixhao28** [comment]
Here 👉  https://github.com/aixcoder-plugin/localservice
