### ISSUE TITLE
Jedi's install_requires claims it works with old parso, but this doesn't appear to be true

### ISSUE THREAD

**Issue by njsmith** [davidhalter/jedi#1348]
According to jedi's `install_requires`, all it needs is `parso >= 0.3.0`.

But judging from https://github.com/python-trio/trio/pull/1121, it looks like actually even parse 0.4.0 isn't good enough – we get:

```
>   from parso.python.tree import ExprStmt, SyncCompFor
E   ImportError: cannot import name 'SyncCompFor' from 'parso.python.tree' (/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/parso/python/tree.py)
```

So I guess the `install_requires` should be updated to say `parse >= 0.5.0`.

**Comment by davidhalter** [comment]
Was this a problem when installing Jedi or not? I mean do I have to make a new release?

**Comment by njsmith** [comment]
Eh, I guess it might cause some minor hiccups for others, but no, it's not urgent for us.

**Comment by johnraz** [comment]
Hey there, just for the record but parso <= 0.4.0 is affected by a security issue:

_Sourced from The GitHub Security Advisory Database._

> High severity vulnerability that affects parso
> A deserialization vulnerability exists in the way parso through 0.4.0 handles grammar parsing from the cache. Cache loading relies on pickle and, provided that an evil pickle can be written to a cache grammar file and that its parsing can be triggered, this flaw leads to Arbitrary Code Execution.
>
> Affected versions: <= 0.4.0

It might be better to create a release and make a statement about the security threat being fixed.

**Comment by njsmith** [comment]
@johnraz Jedi and parso are maintained by the same person, so he's very aware :-).
That CVE warning is ~99% wrong; the discussion is at https://github.com/davidhalter/parso/issues/75
But basically the security threat is "if someone has already taken over your box, then they can take over your box again". So... not really an issue.
Also, Github's claim that it's been fixed is 100% wrong – the new version of parso didn't change anything related to that.

**Comment by johnraz** [comment]
Wow, sorry for the confusion and the noise @njsmith and thanks a ton for clarifying.
