### ISSUE TITLE
Crash in 0.14, folder not found

### ISSUE THREAD

**Issue by Alexey-T** [davidhalter/jedi#1350]
CudaText plugin PythonIntel autocompletion
```
<Python 3.7.3 in /usr>
Init: cuda_python_intel
Traceback (most recent call last):
..
  File "/home/user/.config/cudatext/py/cuda_python_intel/jedi/evaluate/gradual/typeshed.py", line 57, in _get_typeshed_directories
    base_list = os.listdir(base)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.config/cudatext/py/cuda_python_intel/jedi/third_party/typeshed/stdlib'
```

i can't see file typeshed/stdlib. You missed it?

**Comment by Alexey-T** [comment]
I got 0.14 release as ZIP file (Releases in GH) so maybe smth is missed in zip?

**Comment by davidhalter** [comment]
The zip file release is useless, because it contains a submodule. Just use `git clone --recursive https://...` or `pip install jedi

**Comment by davidhalter** [comment]
I also don't seem to be able to remove those zip file download links in the settings, so I guess I will close.
