### ISSUE TITLE
Decorating a function with functools.lru_cache crashes jedi?

### ISSUE THREAD

**Issue by rumo** [davidhalter/jedi#1353]
I've noticed that Jedi autocompletion(in IPython and Jupyter Lab) fails for some starting points, narrowing the issue down shows this happens for (externally loaded) functions with a lru_cache decorator.
Running the following directly in a cell gives me correct auto-complete for sysl[TAB]:

    from functools import lru_cache

    @lru_cache(maxsize=128)
    def syslogs_to_df():
    	pass

but when I %%writefile lru_test the same cell, then import the function with "from lru_test import syslogs_to_df", and then type sysl[TAB], I get(with %config IPCompleter.debug=True):

    Oops Jedi has crashed, please report a bug with the following:
    """

    s"""

Any idea why that would cause problems or how to best debug further?

**Comment by davidhalter** [comment]
I get an AssertionError. So I can reproduce. Will fix it ASAP.

**Comment by rumo** [comment]
awesome, thanks for the fix!
