### ISSUE TITLE
Override builtin from DLL

### ISSUE THREAD

**Issue by Gravityzwell** [davidhalter/jedi#1359]
It appears to me that if jedi finds a match in compiled Python for builtins, e.g., for str.find, it doesn't consider str.find in builtins.pyi. So if I wanted to replace a docstring with something I wrote (for my own use) it seems impossible.

Is there some way to give priority to the pyi if something is defined in both? FYI, PyCharm always reads from .py/.pyi so I can update builtins in PyCharm by modifying those files.

**Comment by davidhalter** [comment]
Which Jedi version are you running? And I really don't understand your issue. Why would you ever want to override str.find?

**Comment by Gravityzwell** [comment]
I had assumed that jedi was pulling docstrings from the compiled Python binary.  I don't know if that assumption is correct. str.find was only an example, but I might want to add my own detail such as clarifying return values or other notes like a reminder of case sensitivity or whatever I find helpful to me.

Not a big deal, as I can either forget it for jedi, or code around it other ways if I care. But I thought the pyi was supposed to take priority so I didn't know if it was a bug or my misunderstanding.

**Comment by davidhalter** [comment]
You didn't answer my question ;-) Which Jedi version are you running?

**Comment by Gravityzwell** [comment]
Sorry, 0.14.0, the release zip, not from trunk.

**Comment by davidhalter** [comment]
Why don't modify the typeshed versions? Doesn't that work?

**Comment by Gravityzwell** [comment]
That's exactly what I was doing, BUT now I see it was my mistake. I had added signature+docstring without realizing there was the default entry later in the file. :)
In fact it appears to work exactly as it should. Thanks for the great work!
