### ISSUE TITLE
How to convert CallSignature to inspect.Signature?

### ISSUE THREAD

**Issue by ericsnowcurrently** [davidhalter/jedi#1360]
[`CallSignature`](https://jedi.readthedocs.io/en/latest/docs/api-classes.html#jedi.api.classes.CallSignature) provides some useful information.  So does the corresponding [`inspect.Signature`](https://docs.python.org/3/library/inspect.html#inspect.Signature).  However, the relationship between the two is unclear.  Would it be possible to add something like a `CallSignature.as_signature()` that would do the conversion?

**Comment by ericsnowcurrently** [comment]
Related: #1361

**Comment by davidhalter** [comment]
Comment of #1361 applies to this as well.

**Comment by davidhalter** [comment]
Why do you need an `inspect.Signature` object? Would it be good enough if `CallSignature` had the same capabilities as `inspect.Signature`?

**Comment by ericsnowcurrently** [comment]
The exact type doesn't matter.  It's only that `inspect.Signature` is a known commodity, from the stdlib.  So I can use it with any other code that already understands it.  I don't have an actual use case currently.  However, I thought of it while writing up #1361 (since conversion to `inspect.Signature` would indicate that issue is resolved).  I think it is a natural comparison to draw and I'd expect others to consider how `CallSignature` and `inspect.Signature` are related.  `CallSignature.as_signature()` (or whatever) would settle that question, regardless of utility, as well as ensuring that `CallSignature` has all the expected info for a Python signature.  Doing that through a compatible API instead of a method would work as well (but I'd expect it to be extra work).

All that said, ultimately this is more of a hypothetical (as I personally don't need it), and I'm not volunteering to do the work, so feel free to close this issue. :)

**Comment by davidhalter** [comment]
I feel like  in `Signature` we have a similar way to deal with signatures now as in `inspect.Signature`. Of course this is not exactly the same, but I don't feel like that should be the case anyway.

Feel free to open issues if you need more things in the API. At this point it's probably easy to add, because all the data is there internally.
