### ISSUE TITLE
Indicate if a parameter is positional-only or keyword-only.

### ISSUE THREAD

**Issue by ericsnowcurrently** [davidhalter/jedi#1361]
(see #1357 & #1358)

As far as I can tell, the parameters in [`CallSignature.params`](https://jedi.readthedocs.io/en/latest/docs/api-classes.html#jedi.api.classes.CallSignature) do not indicate if they are positional-only or keyword-only.  This information is useful, e.g. to indicate to users.

**Comment by ericsnowcurrently** [comment]
The same applies to `*args` and `**kwargs`.

**Comment by davidhalter** [comment]
There's a ton of issues that deal with this. I tried to fit it into the current released, but realized that it would take me a few weeks more so I released it.

This feature is on the top of my list. Just give me a bit of time. All the information is available in the internal API, it's just a matter of API design and documentation now.

**Comment by ericsnowcurrently** [comment]
No worries.  Thanks!

**Comment by davidhalter** [comment]
There's an API for this in the next version.
