### ISSUE TITLE
Give hints of windows packages on linux server

### ISSUE THREAD

**Issue by felixhao28** [davidhalter/jedi#1367]
I am using Jedi in a linux-based web service and installed all dependencies on that machine. However some users use windows-only packages such as "pywin32", which cannot be `pip install`ed on linux. Is there a way to mitigate this issue? E.g. install pywin32 on Windows and copy it to the linux server?

**Comment by davidhalter** [comment]
Yes, that's pretty much the only way how you could do that I think. If there are stubs for the package somewhere that might of course also work.
