### ISSUE TITLE
ValueError: `line` parameter is not in a valid range.

### ISSUE THREAD

**Issue by fgheng** [davidhalter/jedi#1379]
hello, i am using neovim with plugin coc, this plugin using jedi as python completor, but when i use, it shows below

```bash
[coc.nvim] Jedi error: Traceback (most recent call last):
  File "completion.py", line 624, in watch
    response = self._process_request(rq)
  File "completion.py", line 574, in _process_request
    sys_path=sys.path, environment=self.environment)
  File "/home/forever/Software/anaconda3/envs/keras/lib/python3.7/site-packages/jedi/api/__init__.py", line 132, in __init__
    raise ValueError('`line` parameter is not in a valid range.')
ValueError: `line` parameter is not in a valid range.

```

do you know what happend? thank you very much

**Comment by davidhalter** [comment]
I have no idea. Probably the given column is indeed wrong, as the error suggests. Are you dealing with unicode?

**Comment by fgheng** [comment]
maybe, i rewrite my vim config and the problem does not occur, i do not know what happend, emm.

thank you very much

**Comment by davidhalter** [comment]
No idea what the problem was. But these kind of problems should probably be reported to the jedi-vim/youcompleteme tracker first.

**Comment by tgy** [comment]
Still having this error raised today

**Comment by sndmndss** [comment]
Any fix?
