### ISSUE TITLE
Non-__doc__ document support

### ISSUE THREAD

**Issue by tkf** [davidhalter/jedi#138]
I suggest to support "attribute docstrings" and "additional docstrings" mentioned by PEP 257:

> String literals occurring elsewhere in Python code may also act as documentation. They are not recognized by the Python bytecode compiler and are not accessible as runtime object attributes (i.e. not assigned to `__doc__`), but two types of extra docstrings may be extracted by software tools:
> 1. String literals occurring immediately after a simple assignment at the top level of a module, class, or `__init__` method are called **"attribute docstrings"**.
> 2. String literals occurring immediately after another docstring are called **"additional docstrings"**.
> 
> -- [PEP 257 -- Docstring Conventions](http://www.python.org/dev/peps/pep-0257/)

Sphinx autodoc also support fetching document from comment started by `#:`.  This may be useful for some people.
http://sphinx-doc.org/ext/autodoc.html#directive-autoattribute

I may be going to work on this issue at some point but feel free to start working on it if someone wants to do that.  Also, advices on where to start is very welcome.

**Comment by erichiller** [comment]
`variable = value  #: definition` 
or
```
#: definition
variable = value
```
style Documentation is exactly what I've been looking for!

**Comment by davidhalter** [comment]
Attribute docstrings are now supported.

It's been a while, but thanks again for the discussions @tkf. It helped a lot back in the days, especially the testing improvement pull requests you made.

If you're ever back to the Python world, you're definitely very welcome to contribute again :).
