### ISSUE TITLE
Duplicated "import"

### ISSUE THREAD

**Issue by felixhao28** [davidhalter/jedi#1386]
For a very simple case like this:

```python
from app import
```

jedi.Script.completions returns an "import".

Minimal reproduce case:

```python
import jedi
s = "from app import"
print(jedi.Script(s, 1, len(s)).completions())
```

Output (tested on jedi-0.15.1):

```
[<Completion: import>]
```

Is this legal?

**Comment by felixhao28** [comment]
The "app" file is not present in the workspace.

**Comment by davidhalter** [comment]
This is legal, because the complete attribute tells you that you cannot complete anything there:

```
>>> jedi.Script(s, 1, len(s)).completions()[0].complete
''
>>> jedi.Script(s, 1, len(s) - 1).completions()[0].complete
't'
```

**Comment by felixhao28** [comment]
Thank you! For people who might have googled here, there is a complete document on the returned type of completions(): https://jedi.readthedocs.io/en/latest/docs/api-classes.html#jedi.api.classes.Completion
