### ISSUE TITLE
Parameters on signatures not respecting array like elements

### ISSUE THREAD

**Issue by dalthviz** [davidhalter/jedi#1387]
Hi, when retrieving the parameters list of a signature that has array like parameters (e.g a tuple), the given list of parameters shows elements of such parameter as individual parameters. As an example, you can check the signature of `numpy.concatenate`:

#### numpy.concatenate signature: `numpy.concatenate((a1, a2, ...), axis=0, out=None)`

```python
>>>from jedi import Script
>>>txt = """import numpy as np
...np.concatenate(
..."""
>>>script = Script(txt, 2, 15)
>>>call_signature = script.call_signatures()[0]
>>>params = [param.name for param in call_signature.params]
>>>params
['(a1', 'a2', '...)', 'axis', 'out']
```
The result I was expecting should be something like `['(a1, a2, ...)', 'axis', 'out']`

As discussed with @ccordoba12 https://github.com/spyder-ide/spyder/pull/10016#issuecomment-522016940

**Comment by ccordoba12** [comment]
@davidhalter, I'm the Spyder maintainer and assigned @dalthviz to solve this issue in Jedi. Could you point him in the right direction so he can start looking at this?

**Comment by davidhalter** [comment]
As pointed out in other places as well, this docstring parsing is not really the way to go. Alternatives are stubs, annotations and proper `inspect.Signature` objects.

I'm might even remove this parsing of docstrings altogether when I drop Python 2/3.4 support next year. Have you guys tried to convince the numpy guys to use `__signature__`, annotations or stubs?

**Comment by davidhalter** [comment]
Closing, because this is really more of a discussion. Parsing of docstrings for function signatures is deprecated and will probably be removed in future releases.
