### ISSUE TITLE
0.15.1:  test suite fails

### ISSUE THREAD

**Issue by kloczek** [davidhalter/jedi#1390]
<pre>$ python3 -V
Python 3.8.0b3
</pre>

<pre>+ /usr/bin/python3 setup.py test
running test
Searching for parso&gt;=0.5.0
Reading https://pypi.org/simple/parso/
Downloading https://files.pythonhosted.org/packages/a3/bd/bf4e5bd01d79906e5b945a7af033154da49fd2b0d5b5c705a21330323305/parso-0.5.1-py2.py3-none-any.whl#sha256=63854233e1fadb5da97f2744b6b24346d2750b85965e7e399bec1620232797dc
Best match: parso 0.5.1
Processing parso-0.5.1-py2.py3-none-any.whl
Installing parso-0.5.1-py2.py3-none-any.whl to /home/tkloczko/rpmbuild/BUILD/jedi-0.15.1/.eggs
writing requirements to /home/tkloczko/rpmbuild/BUILD/jedi-0.15.1/.eggs/parso-0.5.1-py3.8.egg/EGG-INFO/requires.txt

Installed /home/tkloczko/rpmbuild/BUILD/jedi-0.15.1/.eggs/parso-0.5.1-py3.8.egg
running egg_info
writing jedi.egg-info/PKG-INFO
writing dependency_links to jedi.egg-info/dependency_links.txt
writing requirements to jedi.egg-info/requires.txt
writing top-level names to jedi.egg-info/top_level.txt
reading manifest file &apos;jedi.egg-info/SOURCES.txt&apos;
reading manifest template &apos;MANIFEST.in&apos;
warning: no files found matching &apos;jedi/parser/python/grammar*.txt&apos;
warning: no files found matching &apos;jedi/third_party/typeshed/README&apos;
warning: no previously-included files matching &apos;*.pyc&apos; found under directory &apos;*&apos;
writing manifest file &apos;jedi.egg-info/SOURCES.txt&apos;
running build_ext
/home/tkloczko/rpmbuild/BUILD/jedi-0.15.1/jedi/parser_utils.py:297: SyntaxWarning: invalid escape sequence \w
  return re.match(&apos;\w*(&quot;&quot;&quot;|\&apos;{3}|&quot;|\&apos;)&apos;, leaf.value).group(1)
REPL completion using Jedi 0.15.1
Traceback (most recent call last):
  File &quot;setup.py&quot;, line 23, in &lt;module&gt;
    setup(name=&apos;jedi&apos;,
  File &quot;/usr/lib/python3.8/site-packages/setuptools/__init__.py&quot;, line 145, in setup
    return distutils.core.setup(**attrs)
  File &quot;/usr/lib64/python3.8/distutils/core.py&quot;, line 148, in setup
    dist.run_commands()
  File &quot;/usr/lib64/python3.8/distutils/dist.py&quot;, line 966, in run_commands
    self.run_command(cmd)
  File &quot;/usr/lib64/python3.8/distutils/dist.py&quot;, line 985, in run_command
    cmd_obj.run()
  File &quot;/usr/lib/python3.8/site-packages/setuptools/command/test.py&quot;, line 229, in run
    self.run_tests()
  File &quot;/usr/lib/python3.8/site-packages/setuptools/command/test.py&quot;, line 247, in run_tests
    test = unittest.main(
  File &quot;/usr/lib64/python3.8/unittest/main.py&quot;, line 100, in __init__
    self.parseArgs(argv)
  File &quot;/usr/lib64/python3.8/unittest/main.py&quot;, line 124, in parseArgs
    self._do_discovery(argv[2:])
  File &quot;/usr/lib64/python3.8/unittest/main.py&quot;, line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File &quot;/usr/lib64/python3.8/unittest/main.py&quot;, line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File &quot;/usr/lib64/python3.8/unittest/loader.py&quot;, line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File &quot;/usr/lib64/python3.8/unittest/loader.py&quot;, line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File &quot;/usr/lib64/python3.8/unittest/loader.py&quot;, line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File &quot;/usr/lib/python3.8/site-packages/setuptools/command/test.py&quot;, line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File &quot;/usr/lib64/python3.8/unittest/loader.py&quot;, line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File &quot;/usr/lib/python3.8/site-packages/setuptools/command/test.py&quot;, line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File &quot;/usr/lib64/python3.8/unittest/loader.py&quot;, line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File &quot;/usr/lib/python3.8/site-packages/setuptools/command/test.py&quot;, line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File &quot;/usr/lib64/python3.8/unittest/loader.py&quot;, line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File &quot;/usr/lib/python3.8/site-packages/setuptools/command/test.py&quot;, line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File &quot;/usr/lib64/python3.8/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/home/tkloczko/rpmbuild/BUILD/jedi-0.15.1/jedi/evaluate/compiled/subprocess/__main__.py&quot;, line 52, in &lt;module&gt;
    host_sys_version = [int(x) for x in sys.argv[2].split(&apos;.&apos;)]
IndexError: list index out of range
error: Bad exit status from /var/tmp/rpm-tmp.FWCzzy (%check)
</pre>

**Comment by davidhalter** [comment]
`/usr/bin/python3 setup.py test` is not supported. Please let me know if it fails with py.test.
