### ISSUE TITLE
Pygame autocomplete fails on nested levels

### ISSUE THREAD

**Issue by davaponte** [davidhalter/jedi#1393]
Supose this code
**import pygame
pygame.**

It will work. But then 
**import pygame
pygame.draw.**

doesn't work. It return this:

[<Completion: info>, <Completion: name>, <Completion: reason>, <Completion: urgent>, <Completion: warn>, <Completion: _NOT_IMPLEMENTED_>, <Completion: __annotations__>, <Completion: __class__>, <Completion: __delattr__>, <Completion: __dict__>, <Completion: __dir__>, <Completion: __doc__>, <Completion: __eq__>, <Completion: __format__>, <Completion: __getattr__>, <Completion: __getattribute__>, <Completion: __hash__>, <Completion: __init__>, <Completion: __init_subclass__>, <Completion: __module__>, <Completion: __ne__>, <Completion: __new__>, <Completion: __nonzero__>, <Completion: __reduce__>, <Completion: __reduce_ex__>, <Completion: __repr__>, <Completion: __setattr__>, <Completion: __sizeof__>, <Completion: __slots__>, <Completion: __str__>]

If you run in a python console 
import pygame
dir(pygame.draw)

you'll get the right answer that Jedi does not return:

['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'aaline', 'aalines', 'arc', 'circle', 'ellipse', 'line', 'lines', 'polygon', 'rect']

**Comment by davaponte** [comment]
A little more information:
Another test based in the examples from your documentation (1.4.3 Examples)

Open a python console:
```
import jedi
source = '''import pygame; pygame.'''                        <--- This will work
script = jedi.Script(source, 1, 22, '')
completions = script.completions()
completions                                                                <---- Ok
source = '''import pygame; pygame.draw.'''                <---- Nested level won't work
script = jedi.Script(source, 1, 27, '')
completions = script.completions()
completions                                                                <---- Return not relevant data

```
Tested on Python 3.6.8, LinuxMint 19.2 Tina, Linux 4.15.0-60-generic
Jedi (installed with pip3):
Installing collected packages: parso, jedi
Successfully installed jedi-0.15.1 parso-0.5.1

Gladly I will give more information about this.

**Comment by davaponte** [comment]
I was making some research abot the bug to help you. It seems that Jedi is ignoring the builtin_funcion_or_method results. 

Please run this code and you will see the results what Jedi is omiting:

```
import pygame
result=[]
for i in dir(pygame.draw):
    result.append((getattr(pygame.draw, i), type(getattr(pygame.draw, i)).__name__))
print(result)
```
Yoy'll get:

[('pygame module for drawing shapes', 'str'), ('/home/hal/.local/lib/python3.6/site-packages/pygame/draw.cpython-36m-x86_64-linux-gnu.so', 'str'), (<_frozen_importlib_external.ExtensionFileLoader object at 0x7ff56cff7ac8>, 'ExtensionFileLoader'), ('pygame.draw', 'str'), ('pygame', 'str'), (ModuleSpec(name='pygame.draw', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x7ff56cff7ac8>, origin='/home/data/.local/lib/python3.6/site-packages/pygame/draw.cpython-36m-x86_64-linux-gnu.so'), 'ModuleSpec'), (<built-in function aaline>, 'builtin_function_or_method'), (<built-in function aalines>, 'builtin_function_or_method'), (<built-in function arc>, 'builtin_function_or_method'), (<built-in function circle>, 'builtin_function_or_method'), (<built-in function ellipse>, 'builtin_function_or_method'), (<built-in function line>, 'builtin_function_or_method'), (<built-in function lines>, 'builtin_function_or_method'), (<built-in function polygon>, 'builtin_function_or_method'), (<built-in function rect>, 'builtin_function_or_method')]

Where the buit in functions associated with pygame.draw appear: aalines, arc, circle, ellipse, line, lines, polygon, rect

I hope that will help you to fix the bug.

**Comment by davaponte** [comment]
I was making some research abot the bug to help you. It seems that Jedi is ignoring the builtin_funcion_or_method results.

Please run this code and you will see the results what Jedi is omiting:

import pygame
result=[]
for i in dir(pygame.draw):
    result.append((getattr(pygame.draw, i), type(getattr(pygame.draw, i)).__name__))
print(result)

Yoy'll get:

[('pygame module for drawing shapes', 'str'), ('/home/hal/.local/lib/python3.6/site-packages/pygame/draw.cpython-36m-x86_64-linux-gnu.so', 'str'), (<_frozen_importlib_external.ExtensionFileLoader object at 0x7ff56cff7ac8>, 'ExtensionFileLoader'), ('pygame.draw', 'str'), ('pygame', 'str'), (ModuleSpec(name='pygame.draw', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x7ff56cff7ac8>, origin='/home/hal/.local/lib/python3.6/site-packages/pygame/draw.cpython-36m-x86_64-linux-gnu.so'), 'ModuleSpec'), (, 'builtin_function_or_method'), (, 'builtin_function_or_method'), (, 'builtin_function_or_method'), (, 'builtin_function_or_method'), (, 'builtin_function_or_method'), (, 'builtin_function_or_method'), (, 'builtin_function_or_method'), (, 'builtin_function_or_method'), (, 'builtin_function_or_method')]

Where the buit in functions associated with pygame.draw appear: aalines, arc, circle, ellipse, line, lines, polygon, rect

I hope that will help you to fix the bug.

**Comment by davaponte** [comment]
I was making some research abot the bug to help you. It seems that Jedi is ignoring the **builtin_function_or_method** results.

Please run this code and you will see the results what Jedi is omiting:
```
import pygame
result=[]
for i in dir(pygame.draw):
    result.append((getattr(pygame.draw, i), type(getattr(pygame.draw, i)).__name__))
print(result)
```
You'll get:

`[('pygame module for drawing shapes', 'str'), ('/home/hal/.local/lib/python3.6/site-packages/pygame/draw.cpython-36m-x86_64-linux-gnu.so', 'str'), (<_frozen_importlib_external.ExtensionFileLoader object at 0x7ff56cff7ac8>, 'ExtensionFileLoader'), ('pygame.draw', 'str'), ('pygame', 'str'), (ModuleSpec(name='pygame.draw', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x7ff56cff7ac8>, origin='/home/hal/.local/lib/python3.6/site-packages/pygame/draw.cpython-36m-x86_64-linux-gnu.so'), 'ModuleSpec'), (<built-in function aaline>, 'builtin_function_or_method'), (<built-in function aalines>, 'builtin_function_or_method'), (<built-in function arc>, 'builtin_function_or_method'), (<built-in function circle>, 'builtin_function_or_method'), (<built-in function ellipse>, **'builtin_function_or_method'),** (<built-in function line>, 'builtin_function_or_method'), (<built-in function lines>, 'builtin_function_or_method'), (<built-in function polygon>, 'builtin_function_or_method'), (<built-in function rect>, 'builtin_function_or_method')]`

Where the buit in functions associated with pygame.draw appear: **aaline, aalines, arc, circle, ellipse, line, lines, polygon, rect**

I hope that will help you to fix the bug including the **builtin_function_or_method** results.

**Comment by einarpersson** [comment]
+1 Same problem here

(https://github.com/microsoft/vscode-python/issues/7278)
VS Code version: 1.38.0
Extension version (available under the Extensions sidebar): 2019.9.34911
OS and version: Ubuntu 18.04
Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.3
Type of virtual environment used: conda
Relevant/affected Python packages and their versions: Pygame

**Comment by ElGusanitoPLAY** [comment]
+1 Same problem here

VS Code version: 1.39.2
Extension version: 2019.10.44104
OS and version: Ubuntu 18.04
Python version: Python 3.7.5

**Comment by davidhalter** [comment]
I'm still interested in your pygame version. As long as nobody answers this, I cannot help.

**Comment by einarpersson** [comment]
@davidhalter I'm having this issue right now, using the following versions:
Pygame: `1.9.6`
VSCode: `1.40.0` 
Python: `3.7.3`

Anything else? :)

**Comment by davidhalter** [comment]
@illume You merged this before: https://github.com/pygame/pygame/pull/413

But it seems like it has been removed again. What do you think about this issue? Your code was removed by this commit: https://github.com/pygame/pygame/commit/3c25456e1308f50128ca8190db029df072d2ceea#diff-3e9a996991a8c1951a6d6e69526b16dd

------

Essentially I don't think this should be fixed by Jedi. This is just hard to understand and pygame should fix it by either providing stubs or the workaround that they have provided before.

Since I don't think there's anything left to do here, I'm closing this issue.
