### ISSUE TITLE
goto_assignments: does not find correct definition for bs4.BeautifulSoup.find_all

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1396]
Given `t_bs4.py`:
```python
import jedi

source = """
import bs4
soup = bs4.BeautifulSoup()
soup.find_all()
"""

script = jedi.Script(source, 4, 5)

definitions = script.goto_assignments(follow_imports=True)
print(definitions)
print([(x.module_path, x.line, x.column)
       for x in definitions])
```

Running `python t_bs4.py` in a virtualenv where "beautifulsoup4==4.8.0" is installed shows:

```
[<Definition full_name='bs4.BeautifulSoup.find_all', description='def find_all'>]                                                                                                                                    
[('…/.venv/lib/python3.7/site-packages/bs4/__init__.py', 1264, 8)]                                                                                            
```

However the file has only 616 lines.

The position appears to refer to:
```
.venv/lib/python3.7/site-packages/bs4/element.py                                                                                                                                                                     
1264:    def find_all(self, name=None, attrs={}, recursive=True, text=None,                                                                                                                                          
 ```

This causes an error in jedi-vim then:

> 'Cursor position outside buffer'

Tried with latest release and master (66022ed).

Reminded me of https://github.com/davidhalter/jedi/issues/1315, which is working though by now.

**Comment by blueyed** [comment]
https://github.com/davidhalter/jedi-vim/issues/962#issuecomment-549130564 appears to have a simpler test case.

**Comment by davidhalter** [comment]
I just answered a similar question on stackoverflow: https://stackoverflow.com/questions/58594395/jedi-python-autocompletions-hints-not-showing-methods-or-suggestions

> The problem is basically that the code in bs4.element.Tag._find_all (which is what Soup.find does), is so hard to infer, that Jedi just doesn't understand it. When I'm reading the code, I'm not even quite sure what the return types can be. So how would Jedi understand... Anyway: The solution would be to give the find method an annotation to show what types it returns. It's currently just very unclear what gets returned there.

I don't really think there's a solution for the type inference of this, but we should definitely fix the `Cursor position outside buffer`.

**Comment by davidhalter** [comment]
I just realized that you didn't even ask about the type inference of `find_all()`. So just forget my comment, your original issue is still there.

**Comment by davidhalter** [comment]
Very glad that you found this one. It always confused me that jedi-vim sometimes went to the wrong file. For a while I suspected jedi-vim might be the one to blame, but it turns out it was all me ;-)

Thanks!
