### ISSUE TITLE
Script.call_signatures() returns signatures when outside of parenthesis

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1399]
Given `t_callsig.py`:
```python
import jedi

source = """
def foo(*args):
    pass
foo()  # _
"""

script = jedi.Script(source, 4, 9)

sigs = script.call_signatures()
print(sigs)
```

It prints:
```
[<CallSignature: index=0 foo(*args)>]
```

According to the doc it should return an empty list: https://github.com/davidhalter/jedi/blob/66022edf14a711d7468d2ca02101a36f95e6ea4d/jedi/api/__init__.py#L353-L365

(This affects jedi-vim which displays call signatures then (out of scope))

**Comment by davidhalter** [comment]
Thanks! That's definitely a bug. I have observed similar behavior, but couldn't exactly point to what it was.

**Comment by davidhalter** [comment]
If you have more reproductions, when it's not working, I'm really happy to work on them!
