### ISSUE TITLE
find_virtualenvs: make looking at/for $VIRTUAL_ENV optional

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1407]
To get more control about it, it would be good to being able to skip the magic there (https://github.com/blueyed/jedi/blob/313fdde394cd431a2c8241bc5408f2078e7c5330/jedi/api/environment.py#L274-L279).

Using `$VIRTUAL_ENV` might be good as a fallback, but falls short when it gets changed / is different in the process using Jedi (e.g. Vim).

For jedi-vim I'd like to use `$VIRTUAL_ENV` set in Vim manually, without Jedi using its `$VIRTUAL_ENV` on top.

It might be good enough to add a new keyword argument `use_envvar` (better name?) to control this - or refactor it into two distinct methods - keeping the current behavior then with the existing function.

What do you think?

**Comment by davidhalter** [comment]
So the new signature  would be `find_virtualenvs(use_envvar=True): ...`?

**Comment by davidhalter** [comment]
I would suggest to use `use_virtual_env_var=True` instead. If you're ok, I will implement this.

**Comment by blueyed** [comment]
@davidhalter 
Sounds good :+1:
