### ISSUE TITLE
PyCharm Debug error in Python2

### ISSUE THREAD

**Issue by hsautessella** [davidhalter/jedi#1410]
I've come across an error when using jedi in a program run using PyCharm's debugger and Python 2. I get an `InvalidPythonEnvironment` error.

#### To reproduce:
<s>(Only tested on Windows 10)</s>
- Open the below script in PyCharm and select a Python2 interpreter
```python
import jedi
import sys

print("Python version: " + sys.version)
print("Jedi version: " + jedi.__version__)

script = "import numpy as np\nnp."
j_script = jedi.Script(script, 2, 3, "")
print(j_script.completions())
```
- Run the script normally (Shift+F10) and it will execute without errors
- Now run the script in Debug (Shift+F9). The following error will be raised:
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.1.3\helpers\pydev\pydevd.py", line 2066, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2019.1.3\helpers\pydev\pydevd.py", line 2060, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2019.1.3\helpers\pydev\pydevd.py", line 1411, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Program Files\JetBrains\PyCharm 2019.1.3\helpers\pydev\pydevd.py", line 1418, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/sauh/jedi_test.py", line 8, in <module>
    j_script = jedi.Script(script, 2, 3, "")
  File "C:\Users\sauh\AppData\Local\Continuum\anaconda3\envs\py2\lib\site-packages\jedi\api\__init__.py", line 115, in __init__
    project, environment=environment, script_path=self.path
  File "C:\Users\sauh\AppData\Local\Continuum\anaconda3\envs\py2\lib\site-packages\jedi\evaluate\__init__.py", line 94, in __init__
    self.compiled_subprocess = environment.get_evaluator_subprocess(self)
  File "C:\Users\sauh\AppData\Local\Continuum\anaconda3\envs\py2\lib\site-packages\jedi\api\environment.py", line 113, in get_evaluator_subprocess
    return EvaluatorSubprocess(evaluator, self._get_subprocess())
  File "C:\Users\sauh\AppData\Local\Continuum\anaconda3\envs\py2\lib\site-packages\jedi\api\environment.py", line 79, in _get_subprocess
    exc))
jedi.api.environment.InvalidPythonEnvironment: Could not get version information for 'C:\\Users\\sauh\\AppData\\Local\\Continuum\\anaconda3\\envs\\py2\\python.exe': InternalError(u'The subprocess C:\\Users\\sauh\\AppData\\Local\\Continuum\\anaconda3\\envs\\py2\\python.exe has crashed (EOFError(), stderr=).',)
```
The script runs fine in both cases when using Python3.

Is this something anyone has come across before? Is there a workaround?

I've tracked the error down to line 251 of [`evaluate.compiled.subprocess.__init__`](https://github.com/davidhalter/jedi/blob/master/jedi/inference/compiled/subprocess/__init__.py), perhaps something to do with the PyCharm debugging process interfering with the jedi process?

Below is a stripped down conda environment that can be used to reproduce the issue (although I think any Python2 environment will throw the error):
`conda create -n py2jedi python=2.7 jedi numpy`
```
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
certifi                   2019.9.11                py27_0
icc_rt                    2019.0.0             h0cc432a_1
intel-openmp              2019.4                      245
jedi                      0.15.1                   py27_0
mkl                       2019.4                      245
mkl-service               2.3.0            py27h0b88c2a_0
mkl_fft                   1.0.14           py27h44c1dab_0
numpy                     1.16.5           py27h5fc8d92_0
numpy-base                1.16.5           py27hb1d0314_0
parso                     0.5.1                      py_0
pip                       19.2.3                   py27_0
python                    2.7.16               hcb6e200_0
setuptools                41.2.0                   py27_0
six                       1.12.0                   py27_0
sqlite                    3.29.0               h0c8e037_0
vc                        9                    h7299396_1
vs2008_runtime            9.00.30729.1         hfaea7d5_1
wheel                     0.33.6                   py27_0
wincertstore              0.2              py27hf04cefb_0
```

**Comment by davidhalter** [comment]
I'll gladly keep this open for a while. But if it's only Python 2 I will not invest time into it, because I will probably drop support for Python 2 sometime next year.

**Comment by davidhalter** [comment]
Also what version is this binary: `C:\\Users\\sauh\\AppData\\Local\\Continuum\\anaconda3\\envs\\py2\\python.exe`?

**Comment by hsautessella** [comment]
It's 2.7.16, but I've also tested on 2.7.10 with the same result. 

I realize Python 2 support is being dropped soon, so appreciate you won't want to spend too much time on this. I was mostly wondering if anyone else had seen this and found some workaround, or you could think of one?

**Comment by davidhalter** [comment]
The problem is that the subprocess seems to be crashing, so without a better idea why this is not working I have no idea. Not sure if PyCharm is doing weird stuff with the binary or that specific Python installation.

Also what are you working on? Maybe if I understand your usecase better.

**Comment by hsautessella** [comment]
I'm working on https://github.com/mantidproject/mantid, which includes a Python script editor. The editor is built on [QScintilla](https://qscintilla.com/), however the autocompletion is not great, so we were hoping to use jedi to supply the completions.

I'm essentially just [using `jedi.Interpreter` to generate the completions](https://github.com/mantidproject/mantid/blob/23628_expand_code_completion_in_workbench/qt/python/mantidqt/widgets/codeeditor/codecompleter.py), then passing them to QScintilla to display (any comments on more efficient jedi usage are welcome).

The example I gave in the issue recreates the same error I'm getting in my development branch. Things run fine in PyCharm when not running in Debug, however running in Debug crashes when `jedi.Interpreter()` is called. 

I've recreated the issue on several environments now, including on Ubuntu 18.04.

**Comment by davidhalter** [comment]
In the next version, Python 2 support will be deprecated. I will therefore not debug any Python 2 problems anymore. Sorry.

I'm actually not really celebrating new year's eve, but I'm celebrating Python 2's end of life: https://pythonclock.org/
