### ISSUE TITLE
Autocomplete regression for working with mock library

### ISSUE THREAD

**Issue by maxwellmckinnon** [davidhalter/jedi#1415]
Autocomplete does not work again in latest ipython and latest jedi with mock

Regression occurred from jedi==0.14.0 (working) to 0.14.1 (broken) and persists in latest 0.15.1 (broken)

The repro steps below mimic the issue that occurs in the experience of working with mock in the jupyter notebook.

```
jedi==0.15.1
ipython==7.8.0
Python 3.7.4
```

Repro steps
```
In [1]: import IPython
In [2]: ipy = IPython.get_ipython()
In [3]: from unittest import mock
In [4]: ipy.Completer.all_completions("mock.")
Out[4]: []

In [5]: ipy.Completer.all_completions("mock.p")
Out[5]: ['mock.partial', 'mock.patch', 'mock.pprint']
```

I would expect `mock.` to give a list of many possible things to expand to, including `patch`.

However, this similar issue is not broken in 7.8.0, so uninstalling jedi or downgrading ipython don't fix it:
This is similar to this issue:
https://github.com/davidhalter/jedi/issues/1373
https://github.com/ipython/ipython/issues/11798

# Search for where the regression happened
Works on
```
ipython==7.7.0
no jedi
```
```
ipy.Completer.all_completions("mock.")
Out[1]:
['mock.ANY',
 'mock.Base',
 'mock.BaseExceptions',
 'mock.CallableMixin',
 'mock.DEFAULT',
 'mock.FILTER_DIR',
 'mock.FunctionTypes',
 'mock.MagicMixin',
 'mock.MagicMock',
 'mock.MagicProxy',
 'mock.MethodType',
 'mock.MethodWrapperTypes',
 'mock.Mock',
 'mock.ModuleType',
 'mock.NonCallableMagicMock',
 'mock.NonCallableMock',
 'mock.PropertyMock',
 'mock.builtins',
 'mock.call',
 'mock.create_autospec',
 'mock.file_spec',
 'mock.inplace',
 'mock.inspect',
 'mock.io',
 'mock.magic_methods',
 'mock.mock_open',
 'mock.numerics',
 'mock.partial',
 'mock.patch',
 'mock.pprint',
 'mock.right',
 'mock.seal',
 'mock.sentinel',
 'mock.sys',
 'mock.wraps']
```

Doesn't work on
```
ipython==7.7.0
jedi==0.15.1
```
```
ipy.Completer.all_completions("mock.")
Out[1]: []
```

Works on
```
ipython==7.8.0
jedi==0.13.3
```

Doesn't work on
```
ipython==7.8.0
jedi==0.14.1
```

Doesn't work on
```
ipython==7.8.0
jedi==0.15.0
```

Doesn't work on
```
ipython==7.8.0
jedi==0.15.1
```

Works on
```
ipython==7.8.0
jedi==0.14.0
```

# Workaround
What's unfortunate is that the latest version that fixes this, 0.14.0, also has the bug with autocompletion on numpy. Sadly, `pip uninstall jedi` seems to be the best option again.

**Comment by davidhalter** [comment]
I found this issue and realized that it was even worse for Python 3.5, but it should be fixed now (obviously you have to wait for the next release).

Thanks again for filing this and let me know if you find other stuff like this!
