### ISSUE TITLE
function overloads returns are treated as unions

### ISSUE THREAD

**Issue by AmjadHD** [davidhalter/jedi#1416]
this is a replica of https://github.com/palantir/python-language-server/issues/666
I have two files:
mod.py
```python
def f(value):
    pass
```
and mod.pyi:
```python
from typing import List, Dict, overload


@overload
def f(value: List[str]) -> str: ...


@overload
def f(value: Dict[str, str]) -> Dict[str, str]: ...
```
I'm using pyls (which uses jedi for completion) in sublime text with it's [LSP client](https://github.com/tomv564/LSP), I was testing completions in this case and it turned out that jedi does not consider the signature when providing completions but rather treats the result of any call to the function `f` as a Union of the return types of its overloads (`Union[str, Dict[str, str]]`)

![image](https://user-images.githubusercontent.com/33235928/66006834-62887d80-e4b0-11e9-9851-334e1c58605e.png)

I think it should instead consider the return type per function signature and provide completions accordingly, and if there's no overload variant for a certain call then it should not provide completions at all.

**Comment by davidhalter** [comment]
Just tested it and I think you're right, this is not correct. Not sure how easy it is to fix, though.

**Comment by davidhalter** [comment]
Thanks for reporting. This ended up being surprisingly easy to fix. Let me know if you find other issues.

> and if there's no overload variant for a certain call then it should not provide completions at all

I currently decided to return all possible return variants in that case. Most of the people use Jedi for completions and usually it still helps.

Of course it should be as precise as possible if an overload variant matches.
