### ISSUE TITLE
goto_assignement goes to the stub and not the actual implementation

### ISSUE THREAD

**Issue by AmjadHD** [davidhalter/jedi#1423]
See https://github.com/palantir/python-language-server/issues/675
I many cases, when i execute goto definition using pyls on a symbol it goes to the stub file instead of the actual implementation
```python
import os.path

os.path.dirname(...)
```
Invoke goto definition on `dirname`
it opens up the symbol location in "...\python\python37\lib\site-packages\jedi\third_party\typeshed\stdlib\2and3\ntpath.pyi"
while it should open "...\Python\Python37\Lib\ntpath.py"
pyls uses goto_assignement for Goto Definition request:
https://github.com/palantir/python-language-server/blob/8db7654f9c3786f579416ec42e6a6625003ee43a/pyls/plugins/definition.py#L11-L13

**Comment by davidhalter** [comment]
This is strange, I cannot reproduce. I'm not using Windows, so I'm not sure what is happening there. Maybe someone else can help to try to reproduce this. Maybe @micbou?

Also what Jedi version are you using?

**Comment by AmjadHD** [comment]
> Also what Jedi version are you using?

0.15.1

**Comment by davidhalter** [comment]
Please upgrade Jedi to 0.15.2 and try again.

Also I would be interested in this output:
```
$ python
>>> import jedi
>>> defs = jedi.Script('import os.path; os.path.dirname').goto_definitions()
>>> print([(d, d.module_path) for d in defs])
```

For me this outputs:
```
[(<Definition full_name='os.path.dirname', description='def dirname'>, '/usr/lib/python3.5/macpath.py'), (<Definition full_name='os.path.dirname', description='def dirname'>, '/usr/lib/python3.5/ntpath.py'), (<Definition full_name='os.path.dirname', description='def dirname'>, '/usr/lib/python3.5/posixpath.py')]
```
For me it is

**Comment by AmjadHD** [comment]
I can confirm that this happens no more in 0.15.2
>Also I would be interested in this output:
>```
>$ python
>>>> import jedi
>>>> defs = jedi.Script('import os.path; os.path.dirname').goto_definitions()
>>>> print([(d, d.module_path) for d in defs])
>```

```
[(<Definition full_name='os.path.dirname', description='def dirname'>, 'C:\\Users\\Lehdhili\\AppData\\Local\\Programs\\Python\\Python38\\lib\\ntpath.py'), (<Definition full_name='os.path.dirname', description='def dirname'>, 'C:\\Users\\Lehdhili\\AppData\\Local\\Programs\\Python\\Python38\\lib\\posixpath.py')]
```

**Comment by davidhalter** [comment]
Thanks!
