### ISSUE TITLE
TestSetupReadline.test_import fails with Python 3.8

### ISSUE THREAD

**Issue by mcepl** [davidhalter/jedi#1429]
When testing python-jedi with new Python 3.8 for openSUSE, python-jedi fails in this testmethod.

[Full build log](https://github.com/davidhalter/jedi/files/3768843/_log.txt).

```
[   59s] =================================== FAILURES ===================================
[   59s] ________________________ TestSetupReadline.test_import _________________________
[   59s] 
[   59s] self = <test.test_utils.TestSetupReadline testMethod=test_import>
[   59s] 
[   59s]     def test_import(self):
[   59s]         s = 'from os.path import a'
[   59s]         assert set(self.completions(s)) == {s + 'ltsep', s + 'bspath'}
[   59s]         assert self.completions('import keyword') == ['import keyword']
[   59s]     
[   59s]         import os
[   59s]         s = 'from os import '
[   59s]         goal = {s + el for el in dir(os)}
[   59s]         # There are minor differences, e.g. the dir doesn't include deleted
[   59s]         # items as well as items that are not only available on linux.
[   59s]         difference = set(self.completions(s)).symmetric_difference(goal)
[   59s]         difference = {x for x in difference if not x.startswith('from os import _')}
[   59s]         # There are quite a few differences, because both Windows and Linux
[   59s]         # (posix and nt) libraries are included.
[   59s] >       assert len(difference) < 38
[   59s] E       AssertionError: assert 51 < 38
[   59s] E        +  where 51 = len({'from os import EX_NOTFOUND', 'from os import MFD_ALLOW_SEALING', 'from os import MFD_CLOEXEC', 'from os import MFD_HUGETLB', 'from os import MFD_HUGE_16GB', 'from os import MFD_HUGE_16MB', ...})
[   59s] 
[   59s] test/test_utils.py:83: AssertionError
[   59s] ____ test_compiled_signature[pow-pow(x, y, z=None, /)-names4-op4-version4] _____
[   59s] 
[   59s] Script = functools.partial(<class 'jedi.api.Script'>, environment=<Environment: 3.8.0 in /usr>)
[   59s] environment = <Environment: 3.8.0 in /usr>, code = 'pow'
[   59s] sig = 'pow(x, y, z=None, /)', names = ['x', 'y', 'z']
[   59s] op = <built-in function ge>, version = (3, 5)
[   59s] 
[   59s]     @pytest.mark.parametrize(
[   59s]         'code, sig, names, op, version', [
[   59s]             ('import math; math.cos', 'cos(x, /)', ['x'], ge, (2, 7)),
[   59s]     
[   59s]             ('next', 'next(iterator, default=None, /)', ['iterator', 'default'], ge, (2, 7)),
[   59s]     
[   59s]             ('str', "str(object='', /) -> str", ['object'], ge, (2, 7)),
[   59s]     
[   59s]             ('pow', 'pow(x, y, z=None, /) -> number', ['x', 'y', 'z'], lt, (3, 5)),
[   59s]             ('pow', 'pow(x, y, z=None, /)', ['x', 'y', 'z'], ge, (3, 5)),
[   59s]     
[   59s]             ('bytes.partition', 'partition(self, sep, /) -> (head, sep, tail)', ['self', 'sep'], lt, (3, 5)),
[   59s]             ('bytes.partition', 'partition(self, sep, /)', ['self', 'sep'], ge, (3, 5)),
[   59s]     
[   59s]             ('bytes().partition', 'partition(sep, /) -> (head, sep, tail)', ['sep'], lt, (3, 5)),
[   59s]             ('bytes().partition', 'partition(sep, /)', ['sep'], ge, (3, 5)),
[   59s]         ]
[   59s]     )
[   59s]     def test_compiled_signature(Script, environment, code, sig, names, op, version):
[   59s]         if not op(environment.version_info, version):
[   59s]             return  # The test right next to it should take over.
[   59s]     
[   59s]         d, = Script(code).goto_definitions()
[   59s]         context, = d._name.infer()
[   59s]         compiled, = _stub_to_python_context_set(context)
[   59s]         signature, = compiled.get_signatures()
[   59s] >       assert signature.to_string() == sig
[   59s] E       AssertionError: assert 'pow(base, exp, mod=None)' == 'pow(x, y, z=None, /)'
[   59s] E         - pow(base, exp, mod=None)
[   59s] E         + pow(x, y, z=None, /)
[   59s] 
[   59s] test/test_evaluate/test_signature.py:36: AssertionError
[   59s] ==== 2 failed, 881 passed, 24 skipped, 1677 deselected, 5 xfailed in 22.03s ====
```

**Comment by davidhalter** [comment]
Thanks for reporting this. I wasn't able to reproduce this with my (older) Python 3.8, but now that it's final I can finally reproduce it. (the second test)

The first test is a bit weirder, because it doesn't fail on my Ubuntu. Could you provide me a `python3.8 -c 'import os; print(dir(os))`.

**Comment by mcepl** [comment]
``abuild@stitny:~> python3.8 -c 'import os; print(dir(os))'


['CLD_CONTINUED', 'CLD_DUMPED', 'CLD_EXITED', 'CLD_TRAPPED', 'DirEntry', 'EX_CANTCREAT', 'EX_CONFIG', 'EX_DATAERR', 'EX_IOERR', 'EX_NOHOST', 'EX_NOINPUT', 'EX_NOPERM', 'EX_NOUSER', 'EX_OK', 'EX_OSERR', 'EX_OSFILE', 'EX_PROTOCOL', 'EX_SOFTWARE', 'EX_TEMPFAIL', 'EX_UNAVAILABLE', 'EX_USAGE', 'F_LOCK', 'F_OK', 'F_TEST', 'F_TLOCK', 'F_ULOCK', 'GRND_NONBLOCK', 'GRND_RANDOM', 'MFD_ALLOW_SEALING', 'MFD_CLOEXEC', 'MFD_HUGETLB', 'MFD_HUGE_16GB', 'MFD_HUGE_16MB', 'MFD_HUGE_1GB', 'MFD_HUGE_1MB', 'MFD_HUGE_256MB', 'MFD_HUGE_2GB', 'MFD_HUGE_2MB', 'MFD_HUGE_32MB', 'MFD_HUGE_512KB', 'MFD_HUGE_512MB', 'MFD_HUGE_64KB', 'MFD_HUGE_8MB', 'MFD_HUGE_MASK', 'MFD_HUGE_SHIFT', 'MutableMapping', 'NGROUPS_MAX', 'O_ACCMODE', 'O_APPEND', 'O_ASYNC', 'O_CLOEXEC', 'O_CREAT', 'O_DIRECT', 'O_DIRECTORY', 'O_DSYNC', 'O_EXCL', 'O_LARGEFILE', 'O_NDELAY', 'O_NOATIME', 'O_NOCTTY', 'O_NOFOLLOW', 'O_NONBLOCK', 'O_PATH', 'O_RDONLY', 'O_RDWR', 'O_RSYNC', 'O_SYNC', 'O_TMPFILE', 'O_TRUNC', 'O_WRONLY', 'POSIX_FADV_DONTNEED', 'POSIX_FADV_NOREUSE', 'POSIX_FADV_NORMAL', 'POSIX_FADV_RANDOM', 'POSIX_FADV_SEQUENTIAL', 'POSIX_FADV_WILLNEED', 'POSIX_SPAWN_CLOSE', 'POSIX_SPAWN_DUP2', 'POSIX_SPAWN_OPEN', 'PRIO_PGRP', 'PRIO_PROCESS', 'PRIO_USER', 'P_ALL', 'P_NOWAIT', 'P_NOWAITO', 'P_PGID', 'P_PID', 'P_WAIT', 'PathLike', 'RTLD_DEEPBIND', 'RTLD_GLOBAL', 'RTLD_LAZY', 'RTLD_LOCAL', 'RTLD_NODELETE', 'RTLD_NOLOAD', 'RTLD_NOW', 'RWF_DSYNC', 'RWF_HIPRI', 'RWF_NOWAIT', 'RWF_SYNC', 'R_OK', 'SCHED_BATCH', 'SCHED_FIFO', 'SCHED_IDLE', 'SCHED_OTHER', 'SCHED_RESET_ON_FORK', 'SCHED_RR', 'SEEK_CUR', 'SEEK_DATA', 'SEEK_END', 'SEEK_HOLE', 'SEEK_SET', 'ST_APPEND', 'ST_MANDLOCK', 'ST_NOATIME', 'ST_NODEV', 'ST_NODIRATIME', 'ST_NOEXEC', 'ST_NOSUID', 'ST_RDONLY', 'ST_RELATIME', 'ST_SYNCHRONOUS', 'ST_WRITE', 'TMP_MAX', 'WCONTINUED', 'WCOREDUMP', 'WEXITED', 'WEXITSTATUS', 'WIFCONTINUED', 'WIFEXITED', 'WIFSIGNALED', 'WIFSTOPPED', 'WNOHANG', 'WNOWAIT', 'WSTOPPED', 'WSTOPSIG', 'WTERMSIG', 'WUNTRACED', 'W_OK', 'XATTR_CREATE', 'XATTR_REPLACE', 'XATTR_SIZE_MAX', 'X_OK', '_Environ', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_execvpe', '_exists', '_exit', '_fspath', '_fwalk', '_get_exports_list', '_putenv', '_spawnvef', '_unsetenv', '_wrap_close', 'abc', 'abort', 'access', 'altsep', 'chdir', 'chmod', 'chown', 'chroot', 'close', 'closerange', 'confstr', 'confstr_names', 'copy_file_range', 'cpu_count', 'ctermid', 'curdir', 'defpath', 'device_encoding', 'devnull', 'dup', 'dup2', 'environ', 'environb', 'error', 'execl', 'execle', 'execlp', 'execlpe', 'execv', 'execve', 'execvp', 'execvpe', 'extsep', 'fchdir', 'fchmod', 'fchown', 'fdatasync', 'fdopen', 'fork', 'forkpty', 'fpathconf', 'fsdecode', 'fsencode', 'fspath', 'fstat', 'fstatvfs', 'fsync', 'ftruncate', 'fwalk', 'get_blocking', 'get_exec_path', 'get_inheritable', 'get_terminal_size', 'getcwd', 'getcwdb', 'getegid', 'getenv', 'getenvb', 'geteuid', 'getgid', 'getgrouplist', 'getgroups', 'getloadavg', 'getlogin', 'getpgid', 'getpgrp', 'getpid', 'getppid', 'getpriority', 'getrandom', 'getresgid', 'getresuid', 'getsid', 'getuid', 'getxattr', 'initgroups', 'isatty', 'kill', 'killpg', 'lchown', 'linesep', 'link', 'listdir', 'listxattr', 'lockf', 'lseek', 'lstat', 'major', 'makedev', 'makedirs', 'memfd_create', 'minor', 'mkdir', 'mkfifo', 'mknod', 'name', 'nice', 'open', 'openpty', 'pardir', 'path', 'pathconf', 'pathconf_names', 'pathsep', 'pipe', 'pipe2', 'popen', 'posix_fadvise', 'posix_fallocate', 'posix_spawn', 'posix_spawnp', 'pread', 'preadv', 'putenv', 'pwrite', 'pwritev', 'read', 'readlink', 'readv', 'register_at_fork', 'remove', 'removedirs', 'removexattr', 'rename', 'renames', 'replace', 'rmdir', 'scandir', 'sched_get_priority_max', 'sched_get_priority_min', 'sched_getaffinity', 'sched_getparam', 'sched_getscheduler', 'sched_param', 'sched_rr_get_interval', 'sched_setaffinity', 'sched_setparam', 'sched_setscheduler', 'sched_yield', 'sendfile', 'sep', 'set_blocking', 'set_inheritable', 'setegid', 'seteuid', 'setgid', 'setgroups', 'setpgid', 'setpgrp', 'setpriority', 'setregid', 'setresgid', 'setresuid', 'setreuid', 'setsid', 'setuid', 'setxattr', 'spawnl', 'spawnle', 'spawnlp', 'spawnlpe', 'spawnv', 'spawnve', 'spawnvp', 'spawnvpe', 'st', 'stat', 'stat_result', 'statvfs', 'statvfs_result', 'strerror', 'supports_bytes_environ', 'supports_dir_fd', 'supports_effective_ids', 'supports_fd', 'supports_follow_symlinks', 'symlink', 'sync', 'sys', 'sysconf', 'sysconf_names', 'system', 'tcgetpgrp', 'tcsetpgrp', 'terminal_size', 'times', 'times_result', 'truncate', 'ttyname', 'umask', 'uname', 'uname_result', 'unlink', 'unsetenv', 'urandom', 'utime', 'wait', 'wait3', 'wait4', 'waitid', 'waitid_result', 'waitpid', 'walk', 'write', 'writev']``

**Comment by davidhalter** [comment]
The second part was fixed a while ago (that's also why the CI passes again). cc @bmwiedemann

**Comment by davidhalter** [comment]
The second part is now also fixed (maybe). However if it doesn't work, I won't invest much more work here for now. This is not really a bug, more like an annoying CI failure. Once typeshed starts using the `os.MFD_* variables, it will probably fix itself.
