### ISSUE TITLE
It doesn't work with django.

### ISSUE THREAD

**Issue by iogf** [davidhalter/jedi#1430]
It is not getting completions for django. No idea why it used to work when on py2.

**Comment by davidhalter** [comment]
Please use code to describe your issue. It works for me and I use it daily, so the problem is probably with your setup.

**Comment by iogf** [comment]
The code that i use it is:

https://github.com/vyapp/vy/blob/master/vyapp/plugins/jedi.py

That is how i use jedi in Vy.

Some idea of what is going on?

**Comment by iogf** [comment]
It is also failing to get docs in situations like:

~~~python
import requests
requests.<hitcomplete>
~~~

It return the list of possible completions aka Completion instances
however it doesn't contain the docstring for each one of the possibilities.

If you try:

~~~python
import requests
requests.ge<hitcomplete>
~~~

It displays the completion 'get' with the docs though.

**Comment by davidhalter** [comment]
Sorry, but this is definitely not a Jedi issue. If it is, please post the relevant `jedi.Script` samples like: `print(jedi.Script('import requests; requests.').completions())`.

No idea what goes wrong in your case. If I had to guess, you probably have the wrong environments activated.
