### ISSUE TITLE
goto_assignments duplicate definitions

### ISSUE THREAD

**Issue by bstaint** [davidhalter/jedi#1434]
code:
```
import jedi
script = jedi.Script("import requests;rep = requests.get(""); rep.status_code")

for d in script.goto_assignments(follow_imports=True):
    print(d.module_path, d.line, d.column, d.name)
```

when not install requests output
>/srv/pyenv/tmp-6b9425ffa0313c2/jedi/third_party/typeshed/third_party/2and3/requests/models.pyi 104 4 status_code

after install requests:
> /srv/pyenv/tmp-6b9425ffa0313c2/jedi/third_party/typeshed/third_party/2and3/requests/models.pyi 104 4 status_code
/srv/pyenv/tmp-6b9425ffa0313c2/jedi/third_party/typeshed/third_party/2and3/requests/models.pyi 104 4 status_code
/srv/pyenv/tmp-6b9425ffa0313c2/jedi/third_party/typeshed/third_party/2and3/requests/models.pyi 104 4 status_code

**Comment by davidhalter** [comment]
Thanks for the report!  There was definitely a pretty nasty bug behind this. However, I'm not really sure if this bug persists without stubs. So if you find anything similar again, feel free to report.
