### ISSUE TITLE
jedi looks did not recognize 'inspect'

### ISSUE THREAD

**Issue by Shane-XB-Qian** [davidhalter/jedi#1436]
abc = inspect.getframeinfo(inspect.currentframe())
abc.
---------------
no completion after 'abc.'

even added type hint,
abc = inspect.getframeinfo(inspect.currentframe()) # type: inspect.Traceback

and can not recognize '_getframe' too:
xyz = sys._getframe() # type: frame
xyz.
---------------
no completion after 'xyz.'

**Comment by davidhalter** [comment]
`inspect.getframeinfo` will work, once Jedi supports `typing.NamedTuple`: #1075.

`_getframe()` is filtered intentionally, because it's a "private" method. For now I don't intend to change that for now.

**Comment by Shane-XB-Qian** [comment]
thanks your answer. looking forward it ..
btw, some attr from parent class sometime was not recognized also, just say - but you should know already ..
