### ISSUE TITLE
Broken code completion with (Type[TypeVar]) -> TypeVar

### ISSUE THREAD

**Issue by pappasam** [davidhalter/jedi#1443]
Thank you in advance for looking into this! Jedi is an amazing library and I rely on it every day.

## Issue

`typing.TypeVar`, when used in conjunction with `typing.Type`, breaks completion in `jedi==0.15.1`.

* Python versions tested: `3.7.5` and `3.8.0`, to the same effect.

## Benefits to fixing this issue (eg, why prioritize?)

Although this issue may seem esoteric, it's a pattern I love and one I think may be underused because of its lack of jedi support.

IMHO, fixing this issue will make generically typed constructor functions work well with text editors, which will increase the usage of generically typed functions as constructors (a pattern I much love). This will move the whole Python community toward "typed Duck typing" and into a brave new future for Python.

That said, I'm not a Jedi master. I can try looking into it, but I raise the issue in case someone else with more command of the force can be of service.

## Broken Example: typing.Type with typing.TypeVar

```python
import jedi

source = """
from typing import Type, TypeVar, Any

T = TypeVar("T")

class MyClass:
    def __init__(self, my_attr: Any) -> None:
        self.my_attr = my_attr

def generic_func(a: Any, b: Type[T]) -> T:
    return b(a)

my_class = generic_func("another_value", MyClass)
my_class.
""".strip()

script = jedi.Script(source, 13, 9, "source.py")
print([completion.complete for completion in script.completions()])
```

This prints the following:

```console
[]
```

## Working Example: typing.Type with a class object

```python
import jedi

source = """
from typing import Type, TypeVar, Any

T = TypeVar("T")

class MyClass:
    def __init__(self, my_attr: Any) -> None:
        self.my_attr = my_attr

def generic_func(a: Any, b: Type[MyClass]) -> MyClass:
    return b(a)

my_class = generic_func("another_value", MyClass)
my_class.
""".strip()

script = jedi.Script(source, 13, 9, "source.py")
print([completion.complete for completion in script.completions()])
```

This prints:

```console
['my_attr', '__annotations__', '__class__', '__delattr__', '__dict__',
'__dir__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__',
'__init__', '__init_subclass__', '__module__', '__ne__', '__new__',
'__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__',
'__slots__', '__str__']
```

## Notes

* The `Type[T] -> T` syntax is recognized by mypy, so it's definitely a valid way to pass generic class objects as arguments to a function with the intent of returning typed results.

**Comment by davidhalter** [comment]
Thanks for the good issue description!

I feel like if anyone wants to look into this, please have a look at `jedi/inference/gradual/annotation.py` and its `_infer_type_vars` function. It's probably not that hard to fix, because this case is not as hard as `Iterable[T]` detection.

IMO the only thing we need to do here is something like:

```
    elif isinstance(annotation_value, LazyGenericClass):
        if name == 'Iterable': [...]
    elif isinstance(annotation_value, WhateverType[T]HasAsItsClass):
        if name == 'Type':
            given = annotation_value.get_generics()     
            if given:                                   
                for nested_annotation_value in given[0]:
                    _merge_type_var_dicts(
                        type_var_dict,
                        _infer_type_vars(
                            nested_annotation_value,
                            ContextSet(v for v in value_set if v.is_class())
                        )
                    )
```

This is essentially the same code that we're also using for `Iterable`, with the difference being that here we filter for `is_class`, which might not even be necessary. We could even just pass `value_set` directly. I might even prefer this. Not sure right now.

Needs obviously a bit of work and testing, but feel free to work on it @pappasam  :)
