### ISSUE TITLE
Could not init the Code for the class inherited

### ISSUE THREAD

**Issue by CreatorZZY** [davidhalter/jedi#1444]
(In vscode)just like:
```python
import matplotlib.pyplot as plt
fig = plt.figure()
fig.a<HERE NO INIT APPEAR.>(add_subplot(,,,))
```
or 
```python
import pandas as pd
df=pd.DataFrame({'x':list([1,1,1,1])})
df.i<HERE NO INIT APPEAR.>(iloc[,])
```

Another question is how to process the pyls(Python-language-server) with jedi in vscode?
Thanks.

**Comment by davidhalter** [comment]
> Another question is how to process the pyls(Python-language-server) with jedi in vscode?

No idea about this, sorry. This tracker is only about Jedi the library. I have never looked into pyls.

There are plenty of pandas issues around in the Jedi tracker. I know that some things are not properly working, but it's not really possible to change this for now. It's just very complicated code that is hard to understand. They should probably provide stubs or annotations.

I have also quickly looked up matplotlib. This is a similar issue, a lot of side effects and caches make it impossible to understand what matplotlib does there. They should also use stubs or annotations.

Sorry, I don't see any action being taken here, it's just too hard to understand this stuff.
