### ISSUE TITLE
auto-completion items not shown for newly added func in python3.8

### ISSUE THREAD

**Issue by laowu2019** [davidhalter/jedi#1445]
Hi David, thanks for the amazing tool. 

I have two problems. The first one is that I knew these is a newly added func `dist` in python3.8 math lib, so I tried it in VS Code, but the func never shows up in completion list. Is there any compitiability issue with python3.8 for jedi?

the second one is that I am localizing python3.8 by adding Chinese equivalent functions to srouce C files and then comiling them, but the builtin functions of Chinese version just don't show up in VS Code as well. 

Can you shed some light on how to make jedi work in my situation?

Best Regards

**Comment by bstaint** [comment]
math.dist must update typeshed to commit: https://github.com/python/typeshed/commit/62bbdf856cb0b4d0742427c822d26340ab0eecd2

**Comment by laowu2019** [comment]
@bstaint Thanks. Problem solved!

**Comment by davidhalter** [comment]
@bstaint We should definitely update typeshed for the next release, but it's also important to point out that using the "official" typeshed causes issues with Jedi. I'm not sure how bad it is, but there are patches in "my" typeshed repository that are needed to get the Jedi test suite passing.

@laowu2019 

> the second one is that I am localizing python3.8 by adding Chinese equivalent functions to srouce C files and then comiling them, but the builtin functions of Chinese version just don't show up in VS Code as well.

I don't really understand what you want.

**Comment by laowu2019** [comment]
@davidhalter Basically I am extending python by adding functions and classes with chinese names, which are otherwise exact copies of existing ones. With the help of @bstaint , i.e. adding info to the pyi files, chinese names now show up in auto-completion lists as well as english names. Thanks again for your wonderful tool.

**Comment by davidhalter** [comment]
I guess we're done here. Let me know I was mistaken and you still wanted changes.
