### ISSUE TITLE
KeyError: 'Age'  During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by pratyut121** [davidhalter/jedi#1447]
![Screenshot 2019-11-25 at 16 35 57](https://user-images.githubusercontent.com/58171497/69536012-24d13e00-0fa3-11ea-97c5-0dfc48ddc3ac.png)
While coding the following program:

file = ('///Users/pratyutpannadas/desktop/Health seeking internship analysis.xlsx')
xls =pd.read_excel(file)
#xls.columns
df = pd.read_excel('///Users/pratyutpannadas/desktop/Health seeking internship analysis.xlsx', 'Sheet1')

df.columns
plt.hist(df['Age'])
plt.show()

Error:  KeyError                                  Traceback (most recent call last)
/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2896             try:
-> 2897                 return self._engine.get_loc(key)
   2898             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'Age'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-15-f0578910cee0> in <module>
     12 df.columns
     13 
---> 14 plt.hist(df['Age'])
     15 plt.show()

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2978             if self.columns.nlevels > 1:
   2979                 return self._getitem_multilevel(key)
-> 2980             indexer = self.columns.get_loc(key)
   2981             if is_integer(indexer):
   2982                 indexer = [indexer]

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2897                 return self._engine.get_loc(key)
   2898             except KeyError:
-> 2899                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2900         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2901         if indexer.ndim > 1 or indexer.size > 1:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'Age'

**Comment by davidhalter** [comment]
Sorry but the traceback has no Jedi in it. How did you end up in this issue tracker? :) I think you should probably stackoverflow.

I'm closing this, because it's clearly off-topic. However, the KeyError probably means that your data doesn't have an `Age` column or whatever. I have never used pandas, so I'm definitely only guessing.
