### ISSUE TITLE
lru_cache prevents autocomplete from doing its thing

### ISSUE THREAD

**Issue by ulodciv** [davidhalter/jedi#1449]
I copy/pasted from https://github.com/microsoft/vscode-python/issues/8766

## Environment data

- VS Code version:
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:30.162Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.9-300.fc31.x86_64

- Extension version (available under the Extensions sidebar): 2019.11.50794
- OS and version: Fedora 31
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.5
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: N/A
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977): Jedi

## Expected behaviour

Autocomplete works with methods decorated with lru_cache.

## Actual behaviour

Autocomplete doesn't work with methods decorated with lru_cache.

## Steps to reproduce:
With the following code:
```
from functools import lru_cache


class Foo:
    def a1(self):
        return
    def a2(self):
        return
    def a3(self):
        return


class Bar:

    def foo1(self) -> Foo:
        return Foo()

    @lru_cache()
    def foo2(self) -> Foo:
        return Foo()


bar = Bar()
```
Type `bar.foo1().` and you see `a1`, `a2`, `a3` suggested by autocomplete:
![image](https://user-images.githubusercontent.com/26261271/69529756-25e97780-0f71-11ea-8892-69ccfedc89ab.png)

Type `bar.foo2().` and nothing is suggested by autocomplete.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

- The actions described in steps to reproduce don't seem to add anything to Python logs. 

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

- The actions described in steps to reproduce don't seem to add anything to the console, other than what would be added after pausing writing for a second or two.

**Comment by bstaint** [comment]
@davidhalter, Maybe can ignore annotation funcdef decorators.

 patch:
```diff
diff --git a/inference/syntax_tree.py b/inference/syntax_tree.py
index ea815c9..7abf25c 100644
--- a/inference/syntax_tree.py
+++ b/inference/syntax_tree.py
@@ -748,6 +748,10 @@ def _apply_decorators(context, node):
     else:
         decoratee_value = FunctionValue.from_context(context, node)
     initial = values = ValueSet([decoratee_value])
+    # Ignore annotation funcdef decorators.
+    if node.type == 'funcdef' and node.annotation:
+        return values
+
     for dec in reversed(node.get_decorators()):
         debug.dbg('decorator: %s %s', dec, values, color="MAGENTA")
         with debug.increase_indent_cm():

```

**Comment by davidhalter** [comment]
Thanks for your proposal. It would also be an option to just ignore it for `lru_cache`. Considering what's better.

**Comment by davidhalter** [comment]
The challenge is actually understanding this signature (not sure if that's really possible): 
```
@overload
def lru_cache(maxsize: Optional[int] = ..., typed: bool = ...) -> Callable[[Callable[..., _T]], _lru_cache_wrapper[_T]]: ...
```

Jedi understand this part:

```
@overload
def lru_cache(maxsize: Callable[..., _T], typed: bool = ...) -> _lru_cache_wrapper[_T]: ...
```

**Comment by davidhalter** [comment]
@bstaint I looked at it and realized that typeshed already solves this problem, it's just that Jedi didn't implement that case properly.
