### ISSUE TITLE
goto_assignments not found self.variable

### ISSUE THREAD

**Issue by leandrogmuller** [davidhalter/jedi#1450]
Hello.

I need to find assignment position from source.
But object instaces self from class not return any position instance.
self.var1 = "test"
self.var1....

Example check source: scr = jedi.Script(source, 2,9)
mylist = scr.goto_assignments()
return empty mylist
If the test without "self", return the position on list from source.

```python
import jedi
source = "class A:\n \
    def __init__(self): \n \
        self.R = \"a;b;c\" \n \
        \n \
class B(A):\n \
    def __init__(self):\n \
        super().__init__(self)\n \
        a = self.R.split(";")\n \
"

scr = jedi.Script(source, 8, 18)

goto = scr.goto_definitions()
usages = scr.usages()
sign = scr.goto_assignments()
print("sign", len(sign))
for s in sign:
    print(s.full_name, s.line, s.column, s.desc_with_module)
print("----------")
print("usages", len(usages))
for s in usages:
    print(s.full_name, s.line, s.column, s.desc_with_module)
print("----------")
print("goto", len(goto))
for s in goto:
    print(s.full_name, s.line, s.column, s.desc_with_module)
print("----------")
```

**Comment by davidhalter** [comment]
Please post a full reproduction, that would help tremendously. :)

**Comment by leandrogmuller** [comment]
I changed the post with my source exemple.
You can see the sign variable not return when the self.R was created.

**Comment by leandrogmuller** [comment]
Please, could you delete the post.
I found the soluction, I need to save my source on temp file.
