### ISSUE TITLE
Deoplete-jedi causes vim to crash when editing a specific file

### ISSUE THREAD

**Issue by gtcooke94** [davidhalter/jedi#1457]
I originally opened this issue in the `Deoplete` repository. It was determined that this was an issue in Jedi, so I'm just copying the text from that issue here. Here's a link to that issue:
https://github.com/deoplete-plugins/deoplete-jedi/issues/239

# Problem summary
Deoplete-jedi causes vim to crash when editing a certain file. I've got the file to the minimum I could. If I delete any one of these lines, the steps to reproduce below don't cause a crash. It also doesn't crash except when done on the line specified in the reproduction steps (below the `def`). It does still error if everything is not named `a`, I just did that to make it even smaller.:
```
global a
def a(a):
a = a[a]
if a:
    a += a + 2
```

## Expected
Normal completion expected

## Environment Information

 * OS: Mojave 10.14.6
 * Neovim version: 0.3.4 Release, LuaJIT 2.0.5

## Provide a minimal init.vim with less than 50 lines (required)

```vim
set nocompatible              " be iMproved, required
filetype off                  " required 
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
"call vundle#begin('~/some/path/here')
Plugin 'VundleVim/Vundle.vim' 
Plugin 'Shougo/deoplete.nvim'
Plugin 'deoplete-plugins/deoplete-jedi'
call vundle#end()            " required
filetype plugin indent on    " required
let g:deoplete#enable_at_startup = 1
let g:python3_host_prog = '/Users/gcooke/.virtualenvs/neovim/bin/python3'
let g:python_host_prog = '/Users/gcooke/.virtualenvs/neovim2/bin/python2'
call deoplete#custom#source('jedi', 'is_debug_enabled', 1)
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```

## Generate logfiles if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/nvim-log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc

Then look at and attach the files `/tmp/nvim-log_{PID}` and
`/tmp/deoplete.log` here.

## Steps to reproduce the issue after starting Neovim (required)

 1. Run `nvim {script posted above} -u minimal.vimrc`
 2. Go to line 2, press `o` to enter `insert` mode on the next line (the line below the `def`)
 3. Type `if`
 4. A completion window will show briefly, then vim will start showing tons of error messages. I can't exit out of this except by killing my tmux pane.

## Screen shot (if possible)
![image](https://user-images.githubusercontent.com/16962414/70456184-a2a14900-1a7b-11ea-8d93-93d2223efca7.png)

## Upload the logfile(s)
I'm not seeing the `/tmp/nvim-log_{PID}` file.
[deoplete.log](https://github.com/deoplete-plugins/deoplete-jedi/files/3940880/deoplete.log)

**Comment by davidhalter** [comment]
Can you give me a screenshot/log where you hit `G` (Captital G)? I need the end of the traceback :)

Thanks for the report!

**Comment by Shougo** [comment]
![スクリーンショット_2019-12-11_08-40-34](https://user-images.githubusercontent.com/41495/70578751-fe8dde00-1bf1-11ea-848d-dc31b3b17931.png)

Hi.  I have uploaded the screenshot.
It seems infinite recursion.

**Comment by davidhalter** [comment]
Thanks again for the precise report. It makes it so much easier to fix it if there's an easy reproduction :)

**Comment by Shougo** [comment]
Thank you!
