### ISSUE TITLE
Filter out invalid signatures

### ISSUE THREAD

**Issue by AmjadHD** [davidhalter/jedi#1462]
Knowing that jedi has type inference capabilities, is it possible to add a way to filter out invalid signatures, e.g:
```python
from typing import overload

@overload
def f(x: str, y: int): ...
@overload
def f(x: str, y: bool): ...
@overload
def f(x: list, y: bool): ...

def f(x, y):
    pass
```
```python
f(
```
should return all signatures
```python
f("Hello", 
```
The last signature is dropped
```python
f([],
```
Only the last signature is returned.

Related to #1416.

**Comment by davidhalter** [comment]
Good point, we don't do this yet.

**Comment by AmjadHD** [comment]
The filtering should also take in consideration the number of parameters of each signature, optional parameters, `*args` and `**kwargs` ...

**Comment by davidhalter** [comment]
We might do that, but we should show always at least one signature (even if it doesn't match completely).

**Comment by AmjadHD** [comment]
I thought this should be added as an optional parameter for `find_signatures(...)` and be disabled by default, or as a an attribute for `CallSignature`.
> but we should show always at least one signature (even if it doesn't match).
Why ?

**Comment by davidhalter** [comment]
> > but we should show always at least one signature (even if it doesn't match).

> Why ?

Because users care about that information. They would rather have it so they can see that it doesn't match, than not have anything shown.

**Comment by davidhalter** [comment]
I feel like we are not going to do this for the following reasons:

1. It's quite a lot of work for a feature that doesn't really help, it might do the opposite of help for some people.
2. IMO it probably confuses people more than anything else.
3. Overloaded signatures are quite rare. There are obviously some in the standard library, but you don't get to work on them all the time.

So all in all this is just not worth it. If anyone else disagrees, feel free to comment here and I might eventually reopen if there's a lot of people thinking differently.
