### ISSUE TITLE
Performing a "lazy" import with Jedi

### ISSUE THREAD

**Issue by rovitotv** [davidhalter/jedi#1464]
Greetings,
    I am trying to integrate Jedi with the editor called [exofrills](http://exofrills.org/).  The exofrills maintainer has reasonably requested that Jedi be a optional import and a lazy import.  The optional import was easy but the lazy import with Jedi using importlib.util is not working.  I wrote this very simple test case:

```python
import importlib.util
import sys

def lazy(fullname):
    """performs a lazzy and optional import"""
    try:
        return sys.modules[fullname]
    except KeyError:
        try:
            spec = importlib.util.find_spec(fullname)
            if spec != None:
                module = importlib.util.module_from_spec(spec)
                loader = importlib.util.LazyLoader(spec.loader)
                # Make module with proper locking and get it inserted into sys.modules.
                loader.exec_module(module)
                return module
            else:
                return None # the module is not found so return None
        except ModuleNotFoundError:
            return None

if __name__ == "__main__":
    jedi = lazy("jedi")
    os = lazy("os")
    print(os.name)
    source = '''
    import json
    json.lo'''
    script = jedi.Script(source)
    completions = script.complete(3, len('json.lo'))
    print(completions)
```

The code above fails with the following error:

```bash
python test_jedi_lazy_import.py
posix
Traceback (most recent call last):
  File "test_jedi_lazy_import.py", line 29, in <module>
    script = jedi.Script(source)
  File "/home/rovitotv/anaconda3/lib/python3.7/importlib/util.py", line 250, in __getattribute__
    raise ValueError(f"module object for {original_name!r} "
ValueError: module object for 'jedi' substituted in sys.modules during a lazy load
```

Take note the os module lazy import is working fine but the Jedi module is throwing a ValueError.  Any help or guidance would be much appreciated.  I am using Ubuntu 18.04 with Python 3.7.3 and Python 3.6.9 for testing.  Thank you!

**Comment by davidhalter** [comment]
@rovitotv Sorry I have no idea why this is not working. I have never worked with `LazyLoader` before and I don't intend to. For such things I just use a global in a function that loads it if it's None or something like this. I don't really like the complexities of the import system.

**Comment by davidhalter** [comment]
I'm closing this, since I don't think it's an issue with Jedi. If you identify an issue, please let me know, but unfortunately I cannot really help you here. 

Feel free to keep discussing this, I will also still try to answer.

**Comment by rovitotv** [comment]
Thanks @davidhalter I agree with you the import system is complex so I submitted a pull request just as you suggest with a global function:
https://github.com/scopatz/xo/pull/31
