### ISSUE TITLE
Jedi version 0.15.2 not working at all with the Python extension

### ISSUE THREAD

**Issue by karrtikr** [davidhalter/jedi#1470]
I tried updating jedi used in the Python extension from 0.15.1 and 0.15.2 (https://github.com/microsoft/vscode-python/issues/9243), and almost all the tests failed as the intellisense is no longer working with the extension. We probably need to change something at our end.

I looked at the CHANGELOG (https://github.com/davidhalter/jedi/blob/master/CHANGELOG.rst#0152-2019-12-20) but couldn't find any major changes. Were there some change to API calls which could've caused this?

**Comment by davidhalter** [comment]
This is really weird. The API hasn't changed at all. Did you upgrade parso as well? That might have been your issue.

**Comment by karrtikr** [comment]
I actually didn't. Will try asap.

**Comment by karrtikr** [comment]
It works, thank you!

**Comment by davidhalter** [comment]
It is not mentioned, because it is mentioned in `setup.py`. `pip install jedi` should automatically install parso at the right version.

But you're probably right that I should mention it in Changelog the next time.

**Comment by brettcannon** [comment]
I've also opened an issue on ourselves to start using pip-tools to manage our transient dependencies in hopes of avoiding this on our end in the future.
