### ISSUE TITLE
Signature help for range(...) changed

### ISSUE THREAD

**Issue by karrtikr** [davidhalter/jedi#1471]
I am not sure if this is an issue or not. Our tests detected a change in signature help for `range(...)` for 0.15.2.

This is how it used to look earlier when you type an open bracket.
![image](https://user-images.githubusercontent.com/13199757/72019017-aad8d980-321d-11ea-85ca-26d7d4a86205.png)

This is how it looks now.
![image](https://user-images.githubusercontent.com/13199757/72019079-d2c83d00-321d-11ea-8426-2ff30bf36eaf.png)

Was this intentional? Is the second image the more common usecase for range()? If I had to guess, I would say first one is actually used more.

**Comment by davidhalter** [comment]
This is your guys' issue. You only use one signature. Jedi returns multiple signatures. This might be the case, because you use `Definition.params`. Use `Definition.get_signatures` instead. There you can find all the signatures.
