### ISSUE TITLE
Honor "if False:  # TYPE_CHECKING"

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1472]
pytest does not use `if TYPE_CHECKING`, but `if False:  # TYPE_CHECKING`, recommended by flake8:

> TYP001 guard import by `if False:  # TYPE_CHECKING`: TYPE_CHECKING (not in 3.5.0, 3.5.1)

I think it would be good if Jedi would handle those comments (maybe requiring the exact comment).

The alternative would be trying to import it from `typing_extensions` I guess, but that would require code changes to pytest.  The other alternative is dropping support for Python < 3.5.2, which will eventually be done, of course.

(via https://github.com/pytest-dev/pytest/pull/6434)

Related Jedi issue: https://github.com/davidhalter/jedi/issues/1127

**Comment by davidhalter** [comment]
Why does pytest use this and not just the variable?

**Comment by blueyed** [comment]
To support Python 3.5.0/3.5.1 I assume.

**Comment by davidhalter** [comment]
Makes sense.

It's just that I already started removing support for some things for 3.5. So 3.6 is really the target for Jedi to support. 3.5 is going to be end of life in 10 months :)

So I guess I'm closing, because this will solve itself in a few months.
