### ISSUE TITLE
Handle packages defined through apipkg (pylib)

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1473]
pylib (used by pytest) uses [apipkg](https://github.com/pytest-dev/apipkg): https://github.com/pytest-dev/py/blob/1058b29ce8aac2f9ca0944d3cf1aff8fc0ddb58c/py/__init__.py#L29-L156

This causes Jedi to not find e.g. `py.path` or `py.path.local` then.

I cannot tell if apipkg is widely used, and it is planned to get rid of pylib with pytest in the long run, but maybe this is something that could be supported easily.

**Comment by davidhalter** [comment]
This is a classical example that can you can work around by using stubs. They could either add it to their library or you/others can create a stub repository (`py-stubs`). Jedi searches for these.

I generally only write custom code if these conditions are fulfilled:

- The library has an extremely wide adoption
- Stubs don't help to solve the issue
