### ISSUE TITLE
Tk().geometry goto not work

### ISSUE THREAD

**Issue by bstaint** [davidhalter/jedi#1474]
code:
```
import jedi

script = jedi.Script('''from tkinter import Tk
root = Tk()
root.geometr''')

for c in script.completions():
    print(c.goto())
```
output:
```
[<Definition full_name='tkinter.Wm.geometry', description='geometry = wm_geometry'>]
```

Should be get wm_geometry definition?

And `jedi\api\classes.py`, `jedi\api\__init__.py` _goto function param should be consistent?
miss `'follow_builtin_imports`, `follow_imports`.
```
Traceback (most recent call last):
  File "1.py", line 8, in <module>
    print(c.goto(follow_imports=True))
  File "E:\Downloads\jedi\api\classes.py", line 361, in goto
    return self._goto(**kwargs)
TypeError: _goto() got an unexpected keyword argument 'follow_imports'
```

**Comment by davidhalter** [comment]
> Should be get wm_geometry definition?

No, goto doesn't follow assignments. So IMO it shouldn't follow `geometry = wm_geometry`.

> And jedi\api\classes.py, jedi\api\__init__.py _goto function param should be consistent?
> miss 'follow_builtin_imports, follow_imports.

What do you need it for? We could make it consistent, but I'm still interested why you would need that.

**Comment by bstaint** [comment]
> No, goto doesn't follow assignments. So IMO it shouldn't follow geometry = wm_geometry.

`infer` get empty too,  what should I get wm_geometry definition, it make improve get `statement` completion.

> What do you need it for? We could make it consistent, but I'm still interested why you would need that.

No, I just write confusion code:
```
import jedi

script = jedi.Script('''from tkinter import Tk
root = Tk()
root.geometr''')

for c in script.completions():
    print(c.goto(follow_imports=True))

```
will trackback, i think API should be consistent.
