### ISSUE TITLE
RFC: API Renamings

### ISSUE THREAD

**Issue by davidhalter** [davidhalter/jedi#1476]
I'm very interested in a bit of feedback on naming for the Jedi API. So cc'ing a few people, so I might get answers (@blueyed @dbrgn)

Currently the `Script` names are `completions`, `goto_assignments`, `goto_definitions`, `call_signatures` and `names.

Now I want to clean this up a bit. The new names will be

- complete
- goto  (goes to a name's definition)
- infer  (inferres types for any statement)
- help  (basically a goto with more documentation information)
- get_context (returns the current context)
- find_signatures? (returns signatures of the call a user is currently in)
- list_names? (returns all names/definitions of a Python file)

Especially `find_signatures` and `list_names` are a bit long and also not very nice. I'm considering naming them just `signatures` and `names`, but those are not verbs, so I'm a bit conflicted.

So looking for opinions. What are the best names?

**Comment by blueyed** [comment]
> find_signatures

Why not `get_signatures`?  (not much shorter ;))
Also `get_names` would be more consistent probably.

**Comment by davidhalter** [comment]
Probably makes sense, if there's no other feedback, I just use those names. (Especially, because they are one character shorter :)).

**Comment by dbrgn** [comment]
I think `get_signatures` and `get_names` are fine :slightly_smiling_face:

**Comment by davidhalter** [comment]
Ok. If you guys think `get_*` is better, would you guys think that `get_completions` is also better than `complete`?

Maybe @feuermurmel has also an idea about this kind of stuff :). But please read from the beginning.

**Comment by davidhalter** [comment]
It's now `goto`, `infer`, `complete`, `get_signatures`, `get_names`, `get_references`, `get_context` and `get_help`. If you don't like something about these names, please comment ASAP.

**Comment by asmeurer** [comment]
As far as I'm concerned the old names were good enough. It's not really worth breaking the API over, although you haven't made it clear what your deprecation and removal process will be.

**Comment by davidhalter** [comment]
For now it's not deprecated (but I'm planning to do it). The difference is also that the new names have different functionality: They now take line and column as an argument. So that's in the end the bigger break, that `Script` will not take `line, column` as parameters anymore.
