### ISSUE TITLE
DeprecationWarning from cache.py

### ISSUE THREAD

**Issue by charlesdong1991** [davidhalter/jedi#1481]
I am not very sure if this is the right place to post, seems a deprecation warning is raised after the upgrading of jedi.

```
E   AssertionError: Caused unexpected warning(s): [('DeprecationWarning', DeprecationWarning('Deprecated since version 0.16.0. Use get_signatures()[...].params'), '/home/vsts/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/jedi/cache.py', 111)]
```

**Comment by davidhalter** [comment]
Yes, this is because you guys (or whoever implements Jedi stuff) uses `Definition(...).params`. So you have to replace that.

**Comment by davidhalter** [comment]
BTW: This was already deprecated in Jedi 0.15.0. It just didn't raise a warning back then.

**Comment by charlesdong1991** [comment]
thanks for your quick explanation!

**Comment by TomAugspurger** [comment]
@charlesdong1991 did you raise an issue with IPython?
