### ISSUE TITLE
_compatibility.find_module behavior is not aligned with importlib

### ISSUE THREAD

**Issue by superbobry** [davidhalter/jedi#1483]
I've been trying to use Jedi with a VFS (see discussion #1419), and discovered that the behavior of `_compatibility.find_module` when importing a submodule is different from `importlib.find_spec`. 

Reproducer (using Python 3.7):

```
import importlib
import sys

import jedi


class Finder:

    def find_spec(self, fullname, path, target=None):
        print(fullname, path, target)
        return None


sys.meta_path.insert(0, Finder())


importlib.util.find_spec("foo.bar")
# ==> foo None None
# ==> foo.bar ['/tmp/foo'] None



jedi.Script(
    "import foo.bar; foo.bar.boo",
    environment=jedi.api.environment.InterpreterEnvironment()
).completions()
# ==> foo None None
# ==> bar ['/tmp/foo'] None
```

---

I think the difference is due to the way `find_module_py34` and `find_module_py33` use the `full_name` argument. During import of `foo` these the values of these arguments are equal, but when we get to `foo.bar`, `string` becomes just `"bar"` whereas `full_name` remains `"foo.bar"`. And for some reason, `find_module_py*` functions prefer `string` over `full_name`:

https://github.com/davidhalter/jedi/blob/bec87f7ff82b0731713c6520a14c213341b4cecf/jedi/_compatibility.py#L79
https://github.com/davidhalter/jedi/blob/bec87f7ff82b0731713c6520a14c213341b4cecf/jedi/_compatibility.py#L89
https://github.com/davidhalter/jedi/blob/bec87f7ff82b0731713c6520a14c213341b4cecf/jedi/_compatibility.py#L112

Does this look like a bug in `find_module_py*` functions or is the bug somewhere upstream, i.e. in the caller of `find_module`? Happy to submit a PR with a fix regardless.

**Comment by davidhalter** [comment]
Good questions. I'm not really sure why I decided to go with certain things. It's been a long time ago when that code was written and the code might very well be buggy. I think I wrote it back when Python 3.3 just came out and then we added some parts for 3.4 (so it's been a few years). Some APIs might have changed, or we might have used them wrongly.

I'm very open to changes there. If it passes the test suite, I'm pretty sure it's all fine.
One thing is important though: If it executes any code, I'm not going to merge. Jedi does not execute Python files. Generally `importlib` has a tendency to import files.

**Comment by davidhalter** [comment]
It looks like you're right according to this: https://docs.python.org/3/library/importlib.html#importlib.util.find_spec

So just create a PR and we'll discuss from there. Don't worry about 3.4 support (we're going to remove support anyway). Python 2 is also not that important, because in one or two minor releases, that might also be gone.

PS: I'm still a bit confused why they allow both ways. IMO it's just confusing and doesn't really help with anything, but whatever. I'm generally not a fan of the dotted syntax in strings, because it just complicates things with file names. But that's really off-topic.

**Comment by davidhalter** [comment]
@superbobry Still want to do this? :)

**Comment by davidhalter** [comment]
I had a look at this. It looks like it's way harder than I imagined. I feel like this could work well if there were not namespace packages. That's where tests fail with `python3.8 -m pytest -I` and the patch below.

My experience with importlib is that it's extremely complicated and doesn't work for all cases (without side effects). That's why I implemented my own wrapper.

So I won't be working on this. If somebody else picks this up I'm happy to contribute if you find the actual issues. I'm pretty sure this can be solved by only working with `_compatibility.py`. So it's a fairly isolated problem.

I might have a look at this again when I remove Python 2 (in summer), but don't expect too much. I'm closing for now, since this has really no priority for me.

```
diff --git a/jedi/_compatibility.py b/jedi/_compatibility.py
index d895001..fa37ccb 100644
--- a/jedi/_compatibility.py
+++ b/jedi/_compatibility.py
@@ -76,7 +76,8 @@ def find_module_py34(string, path=None, full_name=None, is_global_search=True):
             # ignore those.
             continue
 
-        spec = find_spec(string, p)
+        print(string, full_name, p, file=sys.stderr)
+        spec = find_spec(full_name or string, p)
         if spec is not None:
             loader = spec.loader
             if loader is None and not spec.has_location:
@@ -84,6 +85,8 @@ def find_module_py34(string, path=None, full_name=None, is_global_search=True):
                 full_name = string if not path else full_name
                 implicit_ns_info = ImplicitNSInfo(full_name, spec.submodule_search_locations._path)
                 return implicit_ns_info, True
+            elif loader is not None:
+                return _from_loader(loader, full_name or string)
             break
 
     return find_module_py33(string, path, loader)
diff --git a/test/test_inference/test_imports.py b/test/test_inference/test_imports.py
index 9ec393e..739d1a1 100644
--- a/test/test_inference/test_imports.py
+++ b/test/test_inference/test_imports.py
@@ -4,6 +4,8 @@ Tests".
 """
 
 import os
+import sys
+import importlib
 
 import pytest
 from jedi.file_io import FileIO, KnownContentFileIO
@@ -12,6 +14,7 @@ from jedi._compatibility import find_module_py33, find_module
 from jedi.inference import compiled
 from jedi.inference import imports
 from jedi.api.project import Project
+from jedi import Script, InterpreterEnvironment
 from jedi.inference.gradual.conversion import _stub_to_python_value_set
 from jedi.inference.references import get_module_contexts_containing_name
 from ..helpers import cwd_at, get_example_dir, test_dir, root_dir
@@ -482,3 +485,34 @@ def test_relative_import_star(Script):
     script = Script(source, 'export.py')
 
     assert script.complete(3, len("furl.c"))
+
+
+def test_meta_path_object(monkeypatch):
+    """See GH #1483. This tests that a full path is given and is working."""
+
+    results = []
+
+    class Finder:
+        def find_spec(self, fullname, path, target=None):
+            if fullname != 'jedi.inference.finder':
+                results.append((fullname, path, target))
+            return None
+
+    monkeypatch.setattr(sys, 'meta_path', [Finder()] + sys.meta_path)
+    with pytest.raises(ImportError):
+        assert not importlib.util.find_spec("foo.bar.baz.jedi")
+        assert len(results) == 1
+        assert results[0] == ("foo.bar.baz.jedi", [], None)
+
+    results = []
+
+    script = Script(
+        "import simple_import.module; simple_import.module.boo",
+        environment=InterpreterEnvironment(),
+        _project=Project(get_example_dir()),
+    )
+    assert not script.infer()
+    # ==> bar ['/tmp/foo'] None
+    assert len(results) == 2
+    assert results[0] == ("simple_import", None, None)
+    assert results[1] == ("simple_import.module", [get_example_dir('simple_import')], None)
```
