### ISSUE TITLE
Scikit-learn has autocomplete type "module" when it should seemingly be "function"

### ISSUE THREAD

**Issue by nscozzaro** [davidhalter/jedi#1486]
Hi, I'm wondering why, for example, `load_iris` in `sklearn` is being autocompleted with a type "module" instead of a "function"? I'm building an application that uses this type information, so it causes me a problem that the type isn't what I expect. 

`load_iris` documentation: https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html#sklearn.datasets.load_iris

Below I have a screenshot showing use of the autocomplete in JupyterLab:
![image](https://user-images.githubusercontent.com/15185105/73460291-40abe400-4346-11ea-833c-b3695c2d7579.png)

Screenshot from load_iris source code (https://github.com/scikit-learn/scikit-learn/blob/b194674c42d54b26137a456c510c5fdba1ba23e0/sklearn/datasets/_base.py#L326):
![image](https://user-images.githubusercontent.com/15185105/73460885-3a6a3780-4347-11ea-950a-0e40f1b3a61a.png)

**Comment by davidhalter** [comment]
Jedi version?

**Comment by davidhalter** [comment]
I doubt that this is a Jedi issue. `jedi.Interpreter('from sklearn.datasets import load_ir', []).complete()[0].type` returns `function`. 

This might be a JupyterLab issue or you might have an old version.

Closing, because this is probably not a Jedi issue, but happy to help you find your issue, so feel free to keep responding.

**Comment by nscozzaro** [comment]
Thank you @davidhalter -- Jupyter installed Jedi version 13 automatically, so manually upgrading to version 16 solved the problem for me. 
One question, what is the easiest way to use Jedi (or similar tool) to parse an entire python library, e.g. sklearn, into one JSON file? I need to achieve a format like:
```
{ 
    libraries: [
        {
            name: sklearn,
            children: [
                {
                      name: module1,
                      type: module,
                      children: [...more modules...]
                }, 
                {
                      name: function1, 
                      type: function
                      params: [
                           {
                                 name: param1,
                                 type: Boolean,
                                 default: False
                           }
                      ]
                }
            ]
        },
       {...other libraries...}
    ]
}
```

**Comment by davidhalter** [comment]
I'm not sure you need type inference. If you don't, you don't need to use Jedi. Just use https://github.com/davidhalter/parso. It's what Jedi uses as well to parse source code. Does that make sense?

**Comment by nscozzaro** [comment]
The type inference is necessary for my application in order to know whether an output is compatible with an input on these nodes. For example, if one function returns type "bool" and another accepts type "int" for a specific parameter, I need to leverage that type information in order to prevent a user connecting ports with different types.

**Comment by davidhalter** [comment]
Yeah, I can probably not help you with that. In some distant future, #1059 might be a good option for you. But for now this is just not really working. Mostly for performance reasons I decided not to make certain APIs public. Maybe `get_type_hint()` helps you (I just added that yesterday), but I doubt that it will help you with all cases.

**Comment by gramster** [comment]
Speaking of `get_type_hint`, that doesn't seem to be defined on `Definition`? At least I have a Definition which has type 'function' and there is not `get_type_hint` method (I installed jedi from head of repo today).

**Comment by davidhalter** [comment]
It's definitely defined on master. I just checked again.

**Comment by gramster** [comment]
Yes, you're right - I foolishly did not uninstall my PyPI installed version before installing the repo-built version and my environment was still picking up the old install. Thanks!

**Comment by davidhalter** [comment]
@gramster Do you have a specific usage in mind for this?

**Comment by nscozzaro** [comment]
Hi @davidhalter, 

I'm also not seeing the type (module/class/function) for this Tensorflow autocomplete:
e.g. https://www.tensorflow.org/api_docs/python/tf/keras/Sequential
![image](https://user-images.githubusercontent.com/15185105/78604163-5f879480-7827-11ea-9eb5-9b95aee5e160.png)

I'm using Jedi 0.16.0

**Comment by davidhalter** [comment]
Can you give me `jedi.Interpreter('from tensorflow import ', [globals()]).complete()`?

**Comment by stonebig** [comment]
from jedi master (0.17alpha) , there are datas coming back
![image](https://user-images.githubusercontent.com/4312421/78695758-cf1c8300-78fe-11ea-921f-62325c4ab7ea.png)

**Comment by nscozzaro** [comment]
> Can you give me `jedi.Interpreter('from tensorflow import ', [globals()]).complete()`?

![image](https://user-images.githubusercontent.com/15185105/78696809-ebec9280-78cd-11ea-9c12-618a87e1ba13.png)

**Comment by davidhalter** [comment]
I'll get back to you. But please don't take pictures anymore of stuff. I want to copy things, this way I have to re-type it ;-).

**Comment by nscozzaro** [comment]
Thanks for the support. And you got it, no more screenshots.

**Comment by davidhalter** [comment]
Can you retry with 0.17.0, just so we are sure that it wasn't fixed along the line?

**Comment by nscozzaro** [comment]
Hi, I just tried 0.17.0, but unfortunately `jedi.Interpreter('from tensorflow.keras import ', [globals()]).complete()` still returns empty when I would expect it to return the classes and functions that are in that module.

**Comment by davidhalter** [comment]
Just checked again why this is happening: Tensorflow 2.1.0 uses a directory that pretty much contains nothing (especially no keras folder). It then modifies the sys modules (see code below). Sys module modifications are not understood by Jedi. And if you read the code below, you can probably understand why. So if don't undo this change, I guess they should just write stubs.

For now I'm not going to do anything. This is an issue with tensorflow code IMO. Most of the time these kind of structures are pretty stupid and don't really provide a benefit.

```
def _forward_module(old_name):
  parts = old_name.split(".")
  parts[0] = parts[0] + "_core"
  local_name = parts[-1]
  existing_name = ".".join(parts)
  _module = _LazyLoader(local_name, globals(), existing_name)
  return _sys.modules.setdefault(old_name, _module)
```

**Comment by davidhalter** [comment]
Please let us continue the tensorflow discussion in #1391.
