### ISSUE TITLE
Crash if import loader is missing inpect methods (is_package)

### ISSUE THREAD

**Issue by iwanb** [davidhalter/jedi#1487]
With a custom importer some inpect methods might be missing (AFAIK they are not mandatory):
https://docs.python.org/3/library/importlib.html#importlib.abc.InspectLoader

In particular the code uses is_package without checking if it's implemented:
https://github.com/davidhalter/jedi/blob/e930f478611d86e29ed0353b0421ee1c861d81f1/jedi/_compatibility.py#L116

I encountered this due to pytest's custom importer for assertion rewriting. 
[jedi_trace.txt](https://github.com/davidhalter/jedi/files/4138964/jedi_trace.txt)

I'll also raise an issue in pytest so inspect support can be added.

**Comment by davidhalter** [comment]
I feel like I fixed it. Now the loader can have pretty much no methods and Jedi should at least not crash. Thanks for the report!

**Comment by iwanb** [comment]
Great, thanks!
