### ISSUE TITLE
Fix documentation link in the description message

### ISSUE THREAD

**Issue by leotada** [davidhalter/jedi#1489]
In the description message we have this link:
http://jedi.readthedocs.io/
and not work.

Please change to this link:
https://jedi.readthedocs.io/en/latest/

Other solution is fix the redirection.

**Comment by davidhalter** [comment]
Thanks a lot for letting me know! I feel like this has been broken for a long time. I didn't change the URL, because the issue was with the readthedocs settings.

Please test again and check if it's still broken.
