### ISSUE TITLE
doc: outdated for "goto" / unused follow_builtin_imports

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1492]
The docstring(s) appears to need some revisiting:
https://github.com/davidhalter/jedi/blob/3ad3dc08b8bf9d749b2d0d9fca038657711c82f2/jedi/api/__init__.py#L277-L288

The argument follow_builtin_imports is not used also.

**Comment by davidhalter** [comment]
Thanks! Hopefully my change makes sense.
