### ISSUE TITLE
"goto" for type comments

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1493]
Given:

```python
foo = None  # type: Optional[MyBar]
```

It would be nice if "goto" worked in the type comment, for both `Optional` and `MyBar`.

The workaround is to not have it as a comment.

The debug function shows:
```
speed: init 120.3422384262085                                                         
speed: parsed 120.3444356918335
dbg: Start: goto
 dbg: Start: infer
 dbg: End: infer
dbg: End: goto
```

(with regard to that it might be also to log/say what was detected at the position, and/or why nothing was considered)

Related: https://github.com/davidhalter/jedi/issues/946

**Comment by davidhalter** [comment]
> The workaround is to not have it as a comment.

Yes. :)

I definitely won't implement this. It's quite a bit of work and it's "from the past", i.e. made for Python 2. IMO I'd rather stop support type comments in the future altogether (meaning no type inference anymore). If tools don't support the comments, people will not use them, which is a plus in my book. These comments are not proper syntax.

Do you actually use them in Python 3 only code bases?

**Comment by blueyed** [comment]
:+1: 
Good point of view.
We're using them in pytest for compat with Python 3.5.

**Comment by davidhalter** [comment]
Makes sense. I quickly thought about that as well, but Python 3.5 is going to be end of life in September. I would guess that Python 2 usage at this point will be higher.

**Comment by blueyed** [comment]
Does not really make too much sense though.  I've spent time with supporting 3.5.{0,1} there even.
I think requiring 3.6+ is good by now, older releases are still available etc.
