### ISSUE TITLE
No inference for function with generic list argument and return

### ISSUE THREAD

**Issue by PeterJCLaw** [davidhalter/jedi#1497]
While `jedi` is able to correctly infer similar generic typed functions, it seems to have an issue with `List[T]` as a parameter or return type (or both). Changing the parameter and return type to another generic type, for example `Tuple[T]`, seems to fix this, though changing only one (for example to signature `(List[T]) -> Tuple[T]`) still demonstrates the issue.

I've put a bunch of examples in https://gist.github.com/PeterJCLaw/388aeb36c9c8c6d9db14c8407501bbf9, which what I was experimenting with, but the failing case is:

``` python
from typing import List, TypeVar

T = TypeVar('T')

def typed_list_generic_passthrough(x: List[T]) -> List[T]:
    return x

# the failure happens whether or not this list has a type annotation
list_str = ['abc', 'def']  # type: List[str]

for d in typed_list_generic_passthrough(list_str):
    #? str()
    d
```

**Comment by davidhalter** [comment]
Thanks! This is probably just a small issue that we could solve with better matching of inputs.

If you want to work on this, there's `jedi/inference/gradual/annotation.py` and the `_infer_type_vars` function where this probably fails. So a simple bugfix (modifying an if) in that function will probably help :).

**Comment by PeterJCLaw** [comment]
> Changing the parameter and return type to another generic type, for example `Tuple[T]`, seems to fix this, though changing only one (for example to signature `(List[T]) -> Tuple[T]`) still demonstrates the issue.

Hrm, turns out that this was working because I'd failed to import `typing.Tuple` in my test script. Changing that results in that case also failing.

Declaring the function as `Iterable[T]` does indeed make things work as desired though.

**Comment by PeterJCLaw** [comment]
> Thanks! This is probably just a small issue that we could solve with better matching of inputs.
> 
> If you want to work on this, there's `jedi/inference/gradual/annotation.py` and the `_infer_type_vars` function where this probably fails. So a simple bugfix (modifying an if) in that function will probably help :).

Thanks, I'll have a look at that :)

**Comment by PeterJCLaw** [comment]
Ok, I think I've got my head around the way the data is modelled here and what `_infer_type_vars` is doing. As much as I think I _could_ just modify that to work for `Collection`, `Sequence`, `List`, `Tuple` (etc.) that doesn't feel like a very sustainable solution, even just for the known types. It also completely doesn't cope with user-defined generic types.

I _think_ we want a solution which looks at the type annotation of the parameter and the apparent type of the argument and tries to align them. In the simplest case, this would realise that they're the same type and do roughly what's done now (possibly with the special handling for collapsing iterables etc.). In the more interesting cases it would need to look up the inheritance chain of the argument's type to see if it overlaps with the type of the parameter in order to determine the mapping of the generic aspects of the argument to those in the parameter.

With that in mind, it would be great to have your input on how to approach this. I can see that `jedi` does some inheritance chain walking as part of the logic for getting members to complete (though I haven't quite figured out exactly where). Would you recommend using that as a basis for this or would we need to take a different approach in order to deal with type annotations?

**Comment by davidhalter** [comment]
Let me think for a bit :)

**Comment by PeterJCLaw** [comment]
I've been having a play with this and have some things which kinda work (making use of the existing `py_mro__` support to walk the inheritance hierarchy, with some inspiration from the implementation from `is_sub_class_of`), though nothing reliable yet.

I think there might be some benefit in extracting some of the logic from `is_sub_class_of` to something which returns the match (and then `is_sub_class_of` becomes a light wrapper around whether that returned `None` or not). Not sure yet if what we want will be close enough that and/or just duplicating the logic might be cleaner anyway.

---

I also did some testing around user-defined generics, which I'd expected not to work at all (based on reading `_infer_type_vars`. To my surprise these _do_ already work, which is great :), but suggests I've misunderstood some of how this works. I'll keep digging.

**Comment by davidhalter** [comment]
Thanks a lot for looking into it. Some of the code I wrote there definitely has issues and I'm happy to have someone else reviewing it.

> I think there might be some benefit in extracting some of the logic from is_sub_class_of to something which returns the match

Good idea! I'm not 100% sure it's needed, because there might be other options, but I'm not really sure either. I don't like these isinstance checks at all, so I'd be happy if we find a more general solution.

> To my surprise these *do* already work, which is great :), but suggests I've misunderstood some of how this works. I'll keep digging.

I'm now also trying to understand again how this works, because I don't really understand how generics work anymore :).

Turns out I would actually disagree with you. They don't work:

```
from typing import Generic, TypeVar

T = TypeVar('T')
V = TypeVar('V')


class WithTypeVar(Generic[T]):
    def __init__(self, t: T): ...
    def lala(self) -> T: ...


def foo(c: WithTypeVar[T]) -> WithTypeVar[T]: ...


#? float()
foo(WithTypeVar(1.0)).lala()
#? float()
foo(WithTypeVar[float](1.0)).lala()
```

This is not working (and it should probably?!).

It took me quite a while to understand again why `_infer_type_vars` is the way it is. If we were only inferring from stuff like `List[int]`, it would be really easy to get it's generics and just return that. However historically (like more than a year ago) it was more like there were generic lists like `List[int]` and there were normal lists like `[1, 2, 3]`. These two types didn't have a lot in common at that time. `value.py__class__()` was basically `List[int]` in one and `list` in the other.

However this has changed! At the moment when I `print(value_set.py__class__())` in `_infer_type_vars` it says `S{<GenericClass: <ClassValue: <Class: list@896-946>>[S{<ClassValue: <Class: int@138-220>>}]>}` for the above example. On that class you could call `.get_generics()` on that to have exactly what you want.

So if we use that information (`value_set.py__class__()`), we could probably indeed get it to work with a better abstraction. At some point we would need to match subclasses (like you suggested) to avoid matching `Iterable` with `Type`.

I suspect that my first example won't work well where I call `WithTypeVar(1.0)`. This probably doesn't translate to `WithTypeVar[float]`. It's probably still `WithTypeVar`. But that's a separate bug that we should tackle after refactoring `_infer_type_vars`.

**Comment by PeterJCLaw** [comment]
> > I think there might be some benefit in extracting some of the logic from is_sub_class_of to something which returns the match
> 
> Good idea! I'm not 100% sure it's needed, because there might be other options, but I'm not really sure either. I don't like these isinstance checks at all, so I'd be happy if we find a more general solution.

Thanks :) I thiiink there might still need to be some specific handling for at least `Type`, but I'm hoping that everything else will "just" fall out. We might need something to cope with `Tuple[int, str]` being `Iterable[Union[str, int]]`, but I hope we can push that into the `Tuple` code (if it doesn't do it already; I've not checked).

> > To my surprise these _do_ already work, which is great :), but suggests I've misunderstood some of how this works. I'll keep digging.
> 
> I'm now also trying to understand again how this works, because I don't really understand how generics work anymore :).
> 
> Turns out I would actually disagree with you. They don't work:

Not sure what I had working here (it might have been a function which returns a user-defined generic rather than accepting one, not sure). When I tried it again this evening I agree that they don't currently work. Glad they also don't work for you ;)

I'm hoping that this is something which a general solution would make work though.

> It took me quite a while to understand again why `_infer_type_vars` is the way it is. If we were only inferring from stuff like `List[int]`, it would be really easy to get it's generics and just return that. However historically (like more than a year ago) it was more like there were generic lists like `List[int]` and there were normal lists like `[1, 2, 3]`. These two types didn't have a lot in common at that time. `value.py__class__()` was basically `List[int]` in one and `list` in the other.

Aha, yeah, I'd wondered about that.

> However this has changed! At the moment when I `print(value_set.py__class__())` in `_infer_type_vars` it says `S{<GenericClass: <ClassValue: <Class: list@896-946>>[S{<ClassValue: <Class: int@138-220>>}]>}` for the above example. On that class you could call `.get_generics()` on that to have exactly what you want.
> 
> So if we use that information (`value_set.py__class__()`), we could probably indeed get it to work with a better abstraction. At some point we would need to match subclasses (like you suggested) to avoid matching `Iterable` with `Type`.

Yup, this lines up with what I've got so far :+1:

> I suspect that my first example won't work well where I call `WithTypeVar(1.0)`. This probably doesn't translate to `WithTypeVar[float]`. It's probably still `WithTypeVar`. But that's a separate bug that we should tackle after refactoring `_infer_type_vars`.

I've not tested that code exactly, though I think it will probably also work -- I'm seeing something fairly similar to the `GenericClass` print you've got above for my user-defined generic type:

```
    _infer_type_vars(  # is called with:
        <GenericClass: <ClassValue: <Class: CustomGeneric@67-70>>[S{<TypeVar: T>}]>,
        S{_GenericInstanceWrapper(<TreeInstance of <GenericClass: <ClassValue: <Class: CustomGeneric@67-70>>[S{<ClassValue: <Class: int@138-220>>}]>(<ValuesArguments: []>)>)}
    )
```

Agree it would be reasonable to ignore this for now if it doesn't fall out of the changes for other types.

In case it's useful, I've put the test cases I'm currently using in a gist at https://gist.github.com/PeterJCLaw/4ea00c946a5737995f6b38dcea9a7c71.

**Comment by davidhalter** [comment]
> Thanks :) I thiiink there might still need to be some specific handling for at least Type, but I'm hoping that everything else will "just" fall out. We might need something to cope with Tuple[int, str] being Iterable[Union[str, int]], but I hope we can push that into the Tuple code (if it doesn't do it already; I've not checked).

Yes. Exactly! Type is probably a special case, but most other cases should just work with generic handling. Just in case you're looking for the inheritance tree, look at `py__mro__()`.

> it might have been a function which returns a user-defined generic rather than accepting one, not sure

Returning user-defined generics should work. It's just that we cannot read it's "inputs".

> In case it's useful, I've put the test cases I'm currently using in a gist at [..]

Thanks! I might look into it if you get stuck, but for now I'm letting you do the work :).
