### ISSUE TITLE
goto() returns nothing for class attribute with type annotation

### ISSUE THREAD

**Issue by xiaochuanyu** [davidhalter/jedi#1502]
```python
import jedi # version 0.16

source = '''
class A:
    class_attr = 1
    class_attr_with_hint: int = 2

    @classmethod
    def do(cls):
        cls.class_attr = 2  # line 8
        cls.class_attr_with_hint = 2  # line 9
'''
script = jedi.Script(source, path='test.py')
definitions = script.goto(line=8, column=13)
print(definitions)
definitions = script.goto(line=9, column=13)
print(definitions)
```
This prints:
```
[<Definition full_name='test.A.class_attr', description='class_attr = 1'>]
[]
```
But I was expecting something like:
```
[<Definition full_name='test.A.class_attr', description='class_attr = 1'>]
[<Definition full_name='test.A.class_attr_with_hint', description='class_attr_with_hint = 2'>]
```

**Comment by davidhalter** [comment]
Looks like this is a bug.

**Comment by PeterJCLaw** [comment]
As I've been doing things with type annotation recently, I had a look at this.

Stepping through this, we end up in [`ClassFilter._access_possible`](https://github.com/davidhalter/jedi/blob/1874e9be8132fec2ece54b12548ec551f0020abc/jedi/inference/value/klass.py#L107-L119) which looks like it's (arguably correctly) detecting that this variable is annotated as being an instance variable and shouldn't be available in a non-instance context.

That codepath doesn't seem to pick up on type comments though, so if you really do want to annotate the attribute but don't want to mark it a `ClassVar` then you could do that (though I wouldn't really recommend it).

(For posterity: I've put some demos in https://gist.github.com/PeterJCLaw/ca10117b4534dc6ba2c0b30bd2fc781a)

I don't know whether or not we'd expect jedi to offer up the definition here. While `mypy` won't actually object to you assigning to an instance attribute within a class method (it's not clear to me why [PEP 526](https://www.python.org/dev/peps/pep-0526/#class-and-instance-variable-annotations) allows this while preventing the reverse), it doesn't seem to be considered an expected thing to do.

**Comment by davidhalter** [comment]
Thanks a lot for the research Peter. You're indeed right. I didn't really understand/remember that part. Since annotations are provided, Jedi uses those (and not the provided values).

The annotation is not a ClassVar, so as Peter says this is actually a problem in @xiaochuanyu's code. You should write it like this if you want to write it correctly: `class_attr_with_hint: ClassVar[int] = 2`. In that case it will work.

I'm closing, because this is definitely wanted behavior. The annotations are just not correct.

**Comment by xiaochuanyu** [comment]
I guess I just didn't expect Jedi to "disagree" with mypy in this case. In terms of editing experience, I get no warning from mypy and Jedi doesn't work.
[mypy docs](https://mypy.readthedocs.io/en/stable/class_basics.html#class-attribute-annotations
) seem to explicitly indicate annotating a class variable with `ClassVar` as optional. It doesn't explain the motivation behind it though.
> It’s not necessary to annotate all class variables using ClassVar. An attribute without the ClassVar annotation can still be used as a class variable.  However, mypy won’t prevent it from being used as an instance variable...

There is actually this part in PEP 526 buried under [rejected/postponed proposals](https://www.python.org/dev/peps/pep-0526/#rejected-postponed-proposals) that seem **imply** omitting  `ClassVar` means instance variable by default; only if you read too much into it that is.
> Add also InstanceVar to the typing module: This is redundant because instance variables are way more common than class variables. The more common usage deserves to be the default.

**Comment by davidhalter** [comment]
You might be right. I might have understood you wrong before. Does mypy not show any issues in your case?

I'm open to changing Jedi's behavior for your case. However if the code looks like `class_attr_with_hint: int`, I would say that it shouldn't work. If it however looked like `class_attr_with_hint: int = 2` (your case), I'm kind of fine with allowing that, because there is an actual definition on the class.

**Comment by xiaochuanyu** [comment]
> Does mypy not show any issues in your case?

It seems `mypy` is very lenient about class vs instance.
I ran `mypy` (no parameters) on the following as well as some testing using `jedi-vim`:
```
from typing import ClassVar


class A:
    class_attr: int = 1  # line 5
    class_attr_classvar: ClassVar[int] = 1  # line 6

    @classmethod
    def class_method(cls):
        cls.class_attr = 2
        cls.class_attr_classvar = 2

    def instance_method(self):
        self.class_attr = 2
        self.class_attr_classvar = 2


a = A()
a.class_attr = 3  # Jedi does not shows class level definition (but should it?)
a.class_attr_classvar = 3  # mypy: Cannot assign to class variable "class_with_classvar" via instance

A.class_attr = 2  # Jedi does not shows class level definition
A.class_attr_classvar = 2  # Jedi shows class level definition
```
There is just that one error where I commented `mypy`'s output.
