### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Ekopalypse** [davidhalter/jedi#1503]
[_get_string_prefix_and_quote](https://github.com/davidhalter/jedi/blob/master/jedi/api/strings.py#L92) may return None, but [_patches_quote_at_position](https://github.com/davidhalter/jedi/blob/master/jedi/api/strings.py#L101) does not take this into account.

Happens to me when trying to write a byte string like b' or b"
but does not happen when writing f' or f"

Windows7 x64
Python 3.7
Jedi 0.16.0

**Comment by petobens** [comment]
Is this the same as https://github.com/deoplete-plugins/deoplete-jedi/issues/248? Or should i open a new issue?

**Comment by davidhalter** [comment]
@petobens That's a different issue.

**Comment by petobens** [comment]
@davidhalter thanks. See https://github.com/davidhalter/jedi/issues/1506

**Comment by davidhalter** [comment]
Fixed on the refactor branch will be part of 0.17.0.

Thanks for the report!
