### ISSUE TITLE
typeshed module try_to_load_stub method TypeError

### ISSUE THREAD

**Issue by petobens** [davidhalter/jedi#1506]
Reproducible steps in https://github.com/deoplete-plugins/deoplete-jedi/issues/248

**Comment by petobens** [comment]
No clues about this one yet right? This essentially breaks pandas completions which (at least for me) is a big deal. Thanks in advance!

**Comment by davidhalter** [comment]
I'm trying to look at this soon. I'm trying to wrap up work on Jedi in the next few days.

**Comment by petobens** [comment]
Thanks!
