### ISSUE TITLE
Wrong highlighting of current argument

### ISSUE THREAD

**Issue by orgads** [davidhalter/jedi#1510]
```
def foo(b: 'Test a b c', c: 'Test a b c'):
    return b

foo()
```

When you open the parentheses, the last b (from c's annotation) is highlighted, and after comma, the last c is highlighted.

![image](https://user-images.githubusercontent.com/1246544/74825221-3c099880-5312-11ea-96a8-f7eb647898ff.png)
![image](https://user-images.githubusercontent.com/1246544/74825250-475cc400-5312-11ea-8dcd-7f242960f0ca.png)

Also happens without annotations:

```
def bar(b, abc, c, kcj):
    return b

bar() # b from abc is highlighted, then abc, then c from kcj
```

Reported on microsoft/vscode-python#10197

**Comment by davidhalter** [comment]
As I wrote upstream, this is probably not a Jedi issue but a vscode-python issue, it works perfectly fine in jedi-vim and there are pretty good tests. (Since I wrote the code I also know that Jedi would never match what you showed me). So they must have done some "magic" on their end...
