### ISSUE TITLE
Jedi doesn't respect import paths

### ISSUE THREAD

**Issue by hutchisr** [davidhalter/jedi#1513]
Given a local sub-package or module that has the same name as a top level package or module, for example:

```
my_project
|   my_package
    |    __init__.py
    |    celery.py
```

Contents of `my_project/my_package/celery.py`:

```python
from __future__ import absolute_import # for compatibility with python2, not needed in python3

import celery


celery.Celery('tasks')
```

Contents of `my_project/my_package/__init__.py`:
```python
```
Jedi treats `import celery` line as importing local module (the current file, which is actually `my_package.celery`) into its self instead of the top level package (the one actually named `celery`).

Expected behavior

 `import celery` should import `celery`, not the local module, `my_package.celery`

Steps to reproduce:

1. create a package or module inside another package with the same local name as another package or module in python's path.
2. import the package or module

**Comment by davidhalter** [comment]
Jedi's trying to guess the sys path with some intelligence. For all more custom use cases there's the project branch now (available once 0.17.0 is out).

What Jedi version are you running? You might run an old one that had such issues.

**Comment by davidhalter** [comment]
ping

**Comment by davidhalter** [comment]
Closing because there was no answer. I'm happy to reopen if answers are given.

**Comment by hutchisr** [comment]
@davidhalter Sorry for the slow response. I do not see a version 0.17.0 available on pypi. I  installed from the master branch of this git repository but I'm not getting any autocomplete results at all using that version.

**Comment by davidhalter** [comment]
Do you get tracebacks?
