### ISSUE TITLE
Script.goto_assignments might return duplicates

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1514]
Noticed this with jedi-vim on https://github.com/pytest-dev/pytest/blob/ff7b5db/src/_pytest/config/argparsing.py#L118 on `names`, where it returns:

```
[
  <Definition full_name='_pytest.config.argparsing.Argument.names', description=
'def names'>,
  <Definition full_name='_pytest.config.argparsing.Argument.names', description='de
f names'>,
]
```

Comparing them with `==` results in `True`, but ids are different.

While jedi-vim could filter out duplicates this appears to indicate an issue with Jedi.

I hope this is easily reproducible for you.

Jedi master (30738a0), parso master (287a86c).

Related issue: https://github.com/davidhalter/jedi/issues/1434.

**Comment by davidhalter** [comment]
Hmm strange, I cannot reproduce :/. Leaving this open for a bit. Maybe you can recheck with latest master? Although I doubt that anything relevant changed there...

**Comment by davidhalter** [comment]
Oh sorry, I can reproduce now. For some strange reason it does give me only one result in jedi-vim...

**Comment by davidhalter** [comment]
And now that I pulled in latest jedi-vim I can also reproduce there. Strange... Maybe that was a consequence of the stuff you changed around goto and when the windows shows. Anyway now we're all good :)
