### ISSUE TITLE
Absent `__init__.py` breaks autocomplete and goto functionality

### ISSUE THREAD

**Issue by ak04nv** [davidhalter/jedi#1516]
Starting Python version 3.3 it uses [Implicit Namespace Packages](https://www.python.org/dev/peps/pep-0420/). This Python version has been included in the Sublime Text 3. But if an empty `__init__.py` isn't contained in the module autocomplete and goto definition doesn't work cause `goto` daemon returns an empty suggestions list.

**Comment by davidhalter** [comment]
It should work without issues. There's a ton of tests that ensure that it works.

Is there a way you can reproduce your example? Maybe the Jedi version you are using is very old?

**Comment by ak04nv** [comment]
> Maybe the Jedi version you are using is very old?
Bingo! 0.14.1
Closing issue.
