### ISSUE TITLE
Arguments to a  `lambda` aren't autocompleted

### ISSUE THREAD

**Issue by siddhant3s** [davidhalter/jedi#1523]
Hi, I just started using Jedi in VSCode. First of all, I'm impressed by how far this tool is able to work. 
I had a small question or bug or perhaps a feature request. Let's say I have a higher-order-function which takes argument of type `Data` and a Callable from `Data -> int`:
```python
@dataclass
class Data:
  name: str
  value: int
def operate(a: Data, op: Callable[[Data], int]) -> int:
  return op(a)
```

Now when I try to use `operate`, I would likely be passing a `lambda` as second argument:
```python
operate(Data("foo", 42), lambda x: x.| # doesn't auto-complete
```
The above code doesn't auto-complete. Is this expected? It would be great if we can have this auto-complete as many Data-manipulation libraries could benefit from it. 
MyPy for example, can correctly infer the type of `x` and complains if I do `x.asdf`
Thank you.

```

**Comment by davidhalter** [comment]
This is expected. Jedi is able to deal with this case very well for type inference, but completions at this place are quite a bit more complex.

I'm going to think a bit about this. It's probably pretty hard to implement for a small amount of use cases, but I still see how this could be useful.

**Comment by davidhalter** [comment]
Also note that Mypy has the unfair advantage that you cannot give it broken code :P

**Comment by siddhant3s** [comment]
Thank you so much David for clarifying that this is indeed a new feature.

If you have any loose ideas about this, let me know. I can see if I can take a stab at it.

**Comment by davidhalter** [comment]
I just looked at this again in detail. While it would be possible to do this, it's just quite annoying to cover all the error recovery cases. It's also something only a few people use. Lambdas are quite rare in Python code bases. I therefore choose to not implement this.

If somebody wants to do this, feel free, but it's probably going to be a lot of annoying work.
