### ISSUE TITLE
UncaughtAttributeError: 'PythonNode' object has no attribute 'context'

### ISSUE THREAD

**Issue by OutOfFocus4** [davidhalter/jedi#1524]
Ran into this while using VSCode.

Have reproduced using Jedi v0.16.

### Setup
1. Install Django (I used version 3.0.4) and Jedi
2. Run this:
```python
import jedi
site_packages = '***path to django install***'
script = jedi.Script(path=f'{site_packages}/django/core/management/base.py', line=13, column=45)
script.goto_definitions()
```

### Expected Output
Jedi finds the definition of the function `color_style` in `base.py`

### Actual Output
Really long stacktrace, ending with
```python
jedi.inference.utils.UncaughtAttributeError: 'PythonNode' object has no attribute 'context'
```

See https://github.com/microsoft/vscode-python/issues/10468 for the output from VSCode.

**Comment by davidhalter** [comment]
I was not able to reproduce in Django, but from the traceback I could write a test that was reproducing this issue.

Thanks for the report!
