### ISSUE TITLE
is it possible to use *.pyi instead of *.py

### ISSUE THREAD

**Issue by Levitanus** [davidhalter/jedi#1525]
I'm using jedi through anaconda SublimeText3 plugin, but if it's already implemented and can be specified via other realization — I would be grateful for the advice.

I keep the stub (`*.pyi`) files for the pypi package, and, recently, noticed that jedi resolves much more complex cases within code typed inside the main code base (`*.py`), than when type hints are placed at the stubs. So, I would like to use stub files primarily, within fallback to the raw source (like mypy does).

For example, now some constructions look like this:

```Python
import reapy as rpr

tr = rpr.Project().get_selected_track(0)  # Type here is rpr.Track,
                                          # but jedi doesn't know.
                                          # But it is in the stubs.
send = tr.sends[0]
# send = rpr.Send()  # need this line for make jedi completion work
print(send, send.midi_source)
```

**Comment by Levitanus** [comment]
Sorry, can't assume why it started to work after the anaconda reinstallation...
Please, let this issue live for a while, I'll close it as soon as realize what happened.

**Comment by davidhalter** [comment]
>  So, I would like to use stub files primarily, within fallback to the raw source (like mypy does).

This is already the case. Stubs are preferred to the actual implementations.

> Sorry, can't assume why it started to work after the anaconda reinstallation...

Might be, because with that you reinstalled Jedi in a higher version. Bugs might have prevented you from using

> Please, let this issue live for a while, I'll close it as soon as realize what happened.

Sorry, but it's not a clear issue, so I'm closing. Feel free to open a new one or comment here. I still read comments on closed tickets, so I could also reopen.
