### ISSUE TITLE
Taking all possible return types from a function

### ISSUE THREAD

**Issue by LimaEduardo** [davidhalter/jedi#1530]
Hello!

As the title says, i'm trying to get all possible return types from a function. I'm using the code below for testing 

![image](https://user-images.githubusercontent.com/22041670/77866194-62bbc880-7208-11ea-900d-dc16a7d87bab.png)

I'm using jedi like this:
![image](https://user-images.githubusercontent.com/22041670/77866332-f392a400-7208-11ea-98ba-eada1e9a3d10.png)

From what I understand from the documentation, when I call name.infer() in the definition with the name "result" it should return a list of possible inferences (bool and str). However, only "str" is returning.

Is this a bug or am I using the tool in the wrong way?

Thanks in advance.

**Comment by davidhalter** [comment]
Can you please paste the code here instead of posting pictures? That way I can just copy it and test it as well. (Sorry I'm lazy :))

**Comment by LimaEduardo** [comment]
Ok!

The code used for testing (I put it in a separate file):

```python
def test_function():
    a = int(input())
    if a % 2 == 0:
        return True
    return "False"

result = test_function() 


```

Code that I wrote for type inference

```python
script_names = jedi.Script(path=file_path).get_names(all_scopes=True, definitions=True)
for name in script_names:
    inferences = name.infer()
```

**Comment by davidhalter** [comment]
> From what I understand from the documentation, when I call name.infer() in the definition with the name "result" it should return a list of possible inferences (bool and str). However, only "str" is returning.

This is wrong. `infer` returns the inferred value. For your function, this is just the function itself. If you want to get the return types, you need to use `script_names[0].execute()`.

However there's still a bug where only strings are returned. However that's for a completely different reason.

**Comment by LimaEduardo** [comment]
Is it difficult to fix? 

Let me know if I can help with anything.

**Comment by davidhalter** [comment]
No it was not difficult. It's probably pretty hard if you don't know the code base, but since I play with it almost every day :)
