### ISSUE TITLE
any way to support portable python?

### ISSUE THREAD

**Issue by carter54** [davidhalter/jedi#1531]
when I used jedi in a portable python, which is packed by Pyinstaller
```
jedi.find_system_environments()
```
return no result.
when I specified a system 'python_path' in jedi.Project by
```
python_path = 'C:\\Users\\xx\\AppData\\Local\\Continuum\\anaconda3\\python.exe'
project = jedi.Project(path=project_path,
                                   python_path=python_path
                                  )
```
it ended up with an error when calling 'jedi.create_environment' api
```
Traceback (most recent call last):
  File "jedi\inference\compiled\subprocess\__init__.py", line 251, in _send
  File "jedi\_compatibility.py", line 390, in pickle_load
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jedi\api\environment.py", line 75, in _get_subprocess
  File "jedi\inference\compiled\subprocess\__init__.py", line 263, in _send
jedi.api.exceptions.InternalError: The subprocess C:\Users\h00416555\AppData\Local\Continuum\anaconda3\python.exe has crashed (EOFError('Ran out of input'), stderr=).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 53, in prediction_by_jedi
  File "jedi\api\__init__.py", line 185, in __init__
  File "jedi\inference\__init__.py", line 88, in __init__
  File "jedi\api\project.py", line 209, in get_environment
  File "jedi\api\environment.py", line 369, in create_environment
  File "jedi\api\environment.py", line 67, in __init__
  File "jedi\api\environment.py", line 80, in _get_subprocess
jedi.api.environment.InvalidPythonEnvironment: Could not get version information for 'C:\\Users\\xx\\AppData\\Local\\Continuum\\anaconda3\\python.exe': InternalError("The subprocess C:\\Users\\xx\\AppData\\Local\\Continuum\\anaconda3\\python.exe has crashed (EOFError('Ran out of input'), stderr=).")
```

this error only happened when I use a portable python packed by Pyinstaller. Any way to get around with it? Thanks

**Comment by davidhalter** [comment]
Jedi version?

**Comment by carter54** [comment]
@davidhalter 0.17.0

**Comment by davidhalter** [comment]
How are you already using that version? Did you just use master? It hasn't been released.

I have no idea what's wrong with your Python version, but it looks like it's somehow broken and that's probably not because of Jedi. My guess is that reinstalling it fixes this. There's probably just something wrong with `C:\\Users\\xx\\AppData\\Local\\Continuum\\anaconda3\\python.exe` or the standard library modules.

Also what's the Python version in there?

**Comment by carter54** [comment]
@davidhalter 
Yes, I use master and python version is 3.7. I think I figured out the problem... It is the problem caused by Pyinstaller. After packing the code by Pyinstaller, 
```
sys.executable
```
cannot get the systempython interpreter, it only return 'the bootloader in either the one-file app or the executable in the one-folder app' (https://pyinstaller.readthedocs.io/en/latest/runtime-information.html#using-sys-executable-and-sys-argv-0)

**Comment by davidhalter** [comment]
I hope the fix that I now provided works. Please test it and let me know. Essentially we're using the InterpreterEnvironment instead of executing `sys.executable`, now.

**Comment by gjthompson1** [comment]
@carter54 were you able to get Jedi to work with PyInstaller? I'm able to import jedi but using `Script` isn't working.

```
print("jedi.__version__", jedi.__version__)
print("jedi.get_default_environment()", jedi.get_default_environment())
try:
    script = jedi.Script("x = 1")
except Exception as e:
    print(e)
```

```
jedi.__version__ 0.18.0
jedi.get_default_environment() <jedi.api.environment.InterpreterEnvironment object at 0x11062f580>
Python version 3.9 is currently not supported.
```

@davidhalter Is there something obvious that I am missing?

**Comment by davidhalter** [comment]
Please print the whole stack.

**Comment by gjthompson1** [comment]
Just updated the original comment, hmm PyInstaller might not be including `parso` properly...

**Comment by gjthompson1** [comment]
Actually this might be what I am missing https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-jedi.py

**Comment by gjthompson1** [comment]
For anyone coming here this was the fix for me. Basically to get Jedi to work with PyInstaller there are some data files in `parso` that are required.

PyInstaller `.spec` file.

```
from PyInstaller.utils.hooks import collect_data_files

datas = collect_data_files('parso')
```

Then add `datas` to `Analysis()` in spec.

Requirement is `pyinstaller-hooks-contrib`
