### ISSUE TITLE
Get jedi working in Kate

### ISSUE THREAD

**Issue by Palexer** [davidhalter/jedi#1539]
Hello,
This is not really an issue but a question:
I wanted to use Kate for small Python projects for a long time now, so I'm happy that I found jedi.
But I can't get it to work and I don't really know what to do even though I read the the docs. I'm using Manjaro Linux (based on Arch) as my OS.

**Comment by davidhalter** [comment]
I have no idea about Kate. I have never used it. Apparently you can enable Jedi somehow: https://kate-editor.org/2013/05/31/a-rich-python-console-and-more-in-kate-editor/

**Comment by davidhalter** [comment]
I think there's not much more I can tell you. Since this is not a Jedi issue I'm closing.

However if you have any more questions, feel free to ask here. I'm happy to continue the discussion.
