### ISSUE TITLE
Jedi has wrong sys.path when started from pyenv virtual environment 

### ISSUE THREAD

**Issue by mrclary** [davidhalter/jedi#1540]
### The Problem
When working from a pyenv virtual environment and attempting to get completions for a conda envrionment, jedi does not establish the correct sys.path, resulting in failed completion. Working from an anaconda environment and attemping to get completions for a pyenv environment works properly.

### MWE summary
* create two virtual environments
  * Anaconda environment with `jedi` and `scipy`
  * Pyenv envrionment with `jedi` and `pandas`
* Use jedi in one environment and get completion from the other environment

### Example 1: use conda; completions from pyenv; successful
```
$ conda create -n conda-jedi python=3.7.7 jedi scipy
$ conda activate conda-jedi
(conda-jedi) $ python
Python 3.7.7 (default, Mar 26 2020, 10:32:53) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> env = jedi.create_environment('/Users/rclary/.pyenv/versions/pyenv-jedi/bin/python', safe=False)
>>> env
<Environment: 3.7.7 in /Users/rclary/.pyenv/versions/3.7.7/envs/pyenv-jedi>
>>> env.get_sys_path()
['/usr/local/mdsplus/pydevices', '/Users/rclary/.pyenv/versions/3.7.7/Python.framework/Versions/3.7/lib/python37.zip', '/Users/rclary/.pyenv/versions/3.7.7/Python.framework/Versions/3.7/lib/python3.7', '/Users/rclary/.pyenv/versions/3.7.7/Python.framework/Versions/3.7/lib/python3.7/lib-dynload', '/Users/rclary/.pyenv/versions/3.7.7/envs/pyenv-jedi/lib/python3.7/site-packages']
>>> jedi.Script(r"""import pa\n""", line=1, column=len('import pa'), environment=env).completions()
[<Completion: pandas>, <Completion: parser>, <Completion: parso>, <Completion: pathlib>]
>>> 
```

### Example 2: use pyenv; completions in conda; unsuccessful
```
$ pyenv virtualenv 3.7.7 pyenv-jedi
$ pyenv activate pyenv-jedi
(pyenv-jedi) $ pip install jedi pandas
(pyenv-jedi) $ python
Python 3.7.7 (default, Apr  6 2020, 11:49:38) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> env = jedi.create_environment('/Users/rclary/anaconda3/envs/conda-jedi/bin/python', safe=False)
>>> env
<Environment: 3.7.7 in /Users/rclary/.pyenv/versions/3.7.7/envs/pyenv-jedi>
>>> env.get_sys_path()
['/usr/local/mdsplus/pydevices', '/Users/rclary/anaconda3/envs/conda-jedi/lib/python37.zip', '/Users/rclary/anaconda3/envs/conda-jedi/lib/python3.7', '/Users/rclary/anaconda3/envs/conda-jedi/lib/python3.7/lib-dynload', '/Users/rclary/.pyenv/versions/3.7.7/envs/pyenv-jedi/lib/python3.7/site-packages']
>>> jedi.Script(r"""import sc\n""", line=1, column=len('import sc'), environment=env).completions()
[<Completion: sched>, <Completion: scripts>]
>>> 
```

Notice that for the unsuccessful case, the environment description incorrectly indicates the pyenv-jedi environment and the `get_sys_path()` returns the wrong site-package path. The result is missing `<Completions: scipy>`

**Comment by davidhalter** [comment]
Please try Jedi 0.17.0 (just released it) to make sure it was not fixed by accident :).

**Comment by davidhalter** [comment]
Also what is the path of scipy? Something like

```
>>> import scipy
>>> scipy
```

would probably help.

**Comment by mrclary** [comment]
Thanks for responding!
I have found the same behavior with 0.17.0

```
>> pyenv activate pyenv-jedi 
pyenv-virtualenv: prompt changing will be removed from future release. configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior.
(pyenv-jedi) >> python
Python 3.7.7 (default, Apr  6 2020, 11:49:38) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> jedi.__version__
'0.17.0'
>>> env = jedi.create_environment('/Users/rclary/anaconda3/envs/conda-jedi/bin/python', safe=False)
>>> env
<Environment: 3.7.7 in /Users/rclary/.pyenv/versions/3.7.7/envs/pyenv-jedi>
>>> env.get_sys_path()
['/usr/local/mdsplus/pydevices', '/Users/rclary/anaconda3/envs/conda-jedi/lib/python37.zip', '/Users/rclary/anaconda3/envs/conda-jedi/lib/python3.7', '/Users/rclary/anaconda3/envs/conda-jedi/lib/python3.7/lib-dynload', '/Users/rclary/.pyenv/versions/3.7.7/envs/pyenv-jedi/lib/python3.7/site-packages']
>>>jedi.Script(r"""import sc\n""", environment=env).complete(line=1, column=len('import sc'))
[<Completion: sched>, <Completion: scripts>]
>>> import scipy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'
>>> exit()
(pyenv-jedi) >> pyenv deactivate
>> conda activate conda-jedi
(conda-jedi) >> python
Python 3.7.7 (default, Mar 26 2020, 10:32:53) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.__file__
'/Users/rclary/anaconda3/envs/conda-jedi/lib/python3.7/site-packages/scipy/__init__.py'
>>> 
```

**Comment by davidhalter** [comment]
Hmmmm, `/Users/rclary/anaconda3/envs/conda-jedi/lib/python3.7` is in the path, which is good, but then `/Users/rclary/.pyenv/versions/3.7.7/envs/pyenv-jedi/lib/python3.7/site-packages` is in the path instead of `/Users/rclary/anaconda3/envs/conda-jedi/lib/python3.7/site-packages`. 

I suspect that this is not a Jedi error, but something wrong with your environment. Jedi literally starts a Python process and reads the sys path from there. I mean there might be an issue in `jedi/inference/compiled/subprocess/__main__.py`, but that's pretty much the only place that I could think of.

Can you maybe run `/Users/rclary/anaconda3/envs/conda-jedi/bin/python` from your pyenv environment? What's the sys path if you look at it from there?

**Comment by mrclary** [comment]
> Hmmmm, `/Users/rclary/anaconda3/envs/conda-jedi/lib/python3.7` is in the path, which is good, but then `/Users/rclary/.pyenv/versions/3.7.7/envs/pyenv-jedi/lib/python3.7/site-packages` is in the path instead of `/Users/rclary/anaconda3/envs/conda-jedi/lib/python3.7/site-packages`.

Exactly.

> Can you maybe run `/Users/rclary/anaconda3/envs/conda-jedi/bin/python` from your pyenv environment? What's the sys path if you look at it from there?

Excellent idea. wish I'd thought to check that before; unfortunately, no insight there:
```
(pyenv-jedi) >> /Users/rclary/anaconda3/envs/conda-jedi/bin/python
Python 3.7.7 (default, Mar 26 2020, 10:32:53) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/local/mdsplus/pydevices', '/Users/rclary/anaconda3/envs/conda-jedi/lib/python37.zip', '/Users/rclary/anaconda3/envs/conda-jedi/lib/python3.7', '/Users/rclary/anaconda3/envs/conda-jedi/lib/python3.7/lib-dynload', '/Users/rclary/anaconda3/envs/conda-jedi/lib/python3.7/site-packages']
>>> 
```
This shows the correct site-packages directory for the conda environment.

**Comment by mrclary** [comment]
Okay, I've got some info to help out here:
An environment is not provided to the `GeneralizedPopen` object instantiated in `jedi/inference/compiled/subprocess/__init__.py`. This results in the subprocess inheriting the existing shell environment variables, which can tend to muck things up. Indeed, if I simply add the keyword argument `env={}`, everything works as expected.
```python
process = GeneralizedPopen(
    args,
    stdin=subprocess.PIPE,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    # Use system default buffering on Python 2 to improve performance
    # (this is already the case on Python 3).
    bufsize=-1,
    env={}
)
```
Upon deeper investigation, in my particular case, it seems the offending environment variable is `__PYVENV_LAUNCHER__=/Users/rclary/.pyenv/versions/3.7.7/envs/pyenv-jedi/bin/python`.

Nevertheless, in general, when working across different python kernels, I've found it more robust to start subprocesses with explicit environments, only passing what I know the subprocess needs (or empty as in the above case), rather than letting it inherit any number of environment variables that can muck things up.

I'm sure that a clean environment should work well for *nix systems, but I'm not sure about Windows.

**Comment by davidhalter** [comment]
I 100% agree. Can you make a pull request out of this? Maybe with a small comment why env is important so nobody deletes it in the future.

Thanks for your research!
