### ISSUE TITLE
Inference should not suggest local variables when only kwargs are legal

### ISSUE THREAD

**Issue by eric-wieser** [davidhalter/jedi#1541]
Given the following function:
```python
def foo(*, a=1, z=2):
    pass
```
And the following input
```
foo(
```
There are only 3 legal completions:

* `a=`
* `z=`
* `**`

However, jedi offers the entire local, global, and builtin namespace:
```
In [1]: import jedi

In [2]: s = jedi.Script("def foo(*, a=1, z=2): pass\nfoo(")

In [3]: s.complete(2, 4)
Out[3]:
[<Completion: a=>,
 <Completion: abs>,
 ...
```
even though
```python
foo(abs)
```
would be a `TypeError`

**Comment by davidhalter** [comment]
Makes sense. I also removed keywords from autocompletion that were already given as a param.
