### ISSUE TITLE
NotADirectoryError passing a file path to get_default_project

### ISSUE THREAD

**Issue by PeterJCLaw** [davidhalter/jedi#1552]
It _looks_ like `get_default_project` might be able to cope with file paths (certainly the logic at the end of the function checks `isdir`), however in practise we get an error if the path to an existing file is given.

Stacktrace:
```
  File ".../jedi/api/project.py", line 383, in get_default_project
    return Project.load(dir)
  File ".../jedi/api/project.py", line 92, in load
    with open(cls._get_json_path(path)) as f:
NotADirectoryError: [Errno 20] Not a directory: '.../project/demo.py/.jedi/project.json'
```

If this is expected, it might be worth updating the docstring to clarify that a directory path is expected (and remove the `isdir` check at the bottom of the function?).

**Comment by davidhalter** [comment]
Makes sense, I'm not sure what makes more sense. What do you think?

**Comment by PeterJCLaw** [comment]
Yeah, I'm not sure to be honest. If the intent of the API is to work around directories only, then this exception type actually isn't bad (though the path it mentions definitely looks a little confusing).

On the other hand, allowing this to accept a file would be fairly easy (check `isfile` and call `dirname` on it).

I guess it depends on what we expect the API to be. I think it would be reasonable for the `Project` class to require a directory (given that projects are intended to be directories), though `get_default_project` feels more like a convenience function where it would be suitable to accept files too (it looks like it accepted files in the past).

**Comment by davidhalter** [comment]
I decided to allow file paths in get_default_project. It makes it easier to just throw any path at it.
