### ISSUE TITLE
Autocompletion error for python while using CoC - VIM

### ISSUE THREAD

**Issue by surmish** [davidhalter/jedi#1555]
Why does this keep showing up? I have jedi and python installed. I saw a similar issue but the submitter closed it without posting the resolution.

```
[coc.nvim] Jedi error: Traceback (most recent call last):
  File "completion.py", line 624, in watch
    response = self._process_request(rq)
  File "completion.py", line 574, in _process_request
    sys_path=sys.path, environment=self.environment)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jedi/api/__init__.py", line 133, in __init__
    project._sys_path = sys_path
AttributeError: 'NoneType' object has no attribute '_sys_path'
```

The line 133 in __init__.py mentioned above has the following code with a TODO:
```python
# TODO deprecate and remove sys_path from the Script API.
if sys_path is not None:
  project._sys_path = sys_path                                                                                              
  warnings.warn(
    "Deprecated since version 0.17.0. Use the project API instead, "
    "which means Script(project=Project(dir, sys_path=sys_path)) instead.",
    DeprecationWarning,
    stacklevel=2
  )
```       
Is the TODO relevant to the error I'm seeing? It seems so because `project._sys_path` seems to be `NoneType` and due to this looking for the attribute `._sys_path` results in an error. Can you please look into this?

**Comment by davidhalter** [comment]
What is CoC? This was fixed in #1551.

**Comment by surmish** [comment]
Thank you David. I should probably pull in these changes. By CoC (Conquer of Completion), I meant this: https://github.com/neoclide/coc.nvim

**Comment by davidhalter** [comment]
There's just too many different VIM plugins that offer code completion with Jedi. :) This is like the 10th.
