### ISSUE TITLE
RecursionError on Completion.docstring() call

### ISSUE THREAD

**Issue by konomith** [davidhalter/jedi#1565]
`jedi` is unable to extract the docstring of `django.db.models.ExpressionList`, resulting in a `RecursionError`.  
Steps to reproduce:  
* Tested on a fresh virtualenv with `python 3.8.0`.
``` bash
/tmp$ pip list
Package    Version
---------- -------
Django     2.2.12 
jedi       0.17.0 
parso      0.7.0  
pip        20.0.2 
pytz       2020.1 
setuptools 46.1.3 
sqlparse   0.3.1  
wheel      0.34.2 
``` 

* Narrowing down the offending object:  
``` python
>>> import jedi
>>> s = jedi.Script('from django.db import models; models.')
>>> compls = s.complete()
>>> for c in compls:
>>>     try:
>>>         d = c.docstring()
>>>     except Exception:  # remove this to get the stacktrace
>>>         print(c)
<Completion: ExpressionList>
```
* The full stacktrace can be found here: https://pastebin.com/QAPNmvDc
* The docstring can be found here: https://github.com/django/django/blob/2.2.12/django/db/models/expressions.py#L819

**Comment by davidhalter** [comment]
I might have fixed this on master a few commits ago. Can you retry on latest master?

**Comment by konomith** [comment]
Can confirm that indeed it works with the latest master. Thanks!
