### ISSUE TITLE
Add ".venv" to `jedi.inference.references._IGNORE_FOLDERS`

### ISSUE THREAD

**Issue by pappasam** [davidhalter/jedi#1566]
".venv" is a popular virtual environment folder name; `project.search` gets really mucked up when it isn't ignored.

I've gotten around this issue in https://github.com/pappasam/jedi-language-server with the following line:

```python
import jedi.inference.references
# TODO: remove this once Jedi ignores '.venv' folders by default
# without this line, Jedi will search in '.venv' folders
jedi.inference.references._IGNORE_FOLDERS = (
    *jedi.inference.references._IGNORE_FOLDERS,
    ".venv",
)
```

We can also consider making this `_IGNORE_FOLDERS` a jedi configuration. I can make it configurable in my language server for end users, but I figure we probably want an official jedi API that isn't quite as "private" as the above. What do you think?

**Comment by davidhalter** [comment]
Thanks for looking into this. I think configuration options like this for venvs are probably the wrong idea.

I think it might be better to just remove venv's from the equation, if there's a `bin/activate`. I'm however also happy to just add the `.venv` to the `_IGNORE_FOLDERS` upstream.

**Comment by davidhalter** [comment]
And btw: The above API is private. It may change at any time.

**Comment by pappasam** [comment]
Understood. And that’s exactly why I opened this issue!
