### ISSUE TITLE
Go to definition doesn't highlight the last character

### ISSUE THREAD

**Issue by karrtikr** [davidhalter/jedi#1568]
Please try this out in VSCode.

This is a screenshot with an example of code affected:
![peek-definitions](https://user-images.githubusercontent.com/10964663/80796835-8627b980-8ba0-11ea-9810-002ca587855f.png)

```python
def foo(a):
    return a

foo(True)
```

Right click on `foo` and click `Go to definition`. The last character is not highlighted.

**Comment by davidhalter** [comment]
This is probably a VSCode bug. I do not know of a Jedi API that would even allow for this. Jedi does not have the concept of an end position. So you probably wrote some custom code in VSCode that is buggy.

**Comment by karrtikr** [comment]
I see, will transfer back until further investigation is done.

**Comment by davidhalter** [comment]
I will close for now. Let me know if you find anything.
