### ISSUE TITLE
Exclude `'` from completion name when inside string

### ISSUE THREAD

**Issue by muffinmad** [davidhalter/jedi#1569]
```python
Python 3.7.4 (default, Sep 28 2019, 16:39:19) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> script = jedi.Script("foo = {'key': 0}; foo['")
>>> print(script.complete(1, 22)[0].name) #  point is after [
'key'
>>> print(script.complete(1, 23)[0].name) #  point is after last '
'key'
```

Inserting completion name at the end of in this code:
```python
foo = {'key': 0}; foo[
```
will result
```python
foo = {'key': 0}; foo['key'
```

But inserting completion name at the end of this code:
```python
foo = {'key': 0}; foo['
```
will result
```python
foo = {'key': 0}; foo[''key'
```

IMO it would be better to not completion name include `'` in the later case.

Thank you!

**Comment by davidhalter** [comment]
That's because you are using the wrong API. You have to use `script.complete(1, 22)[0].complete`. Does that help?

**Comment by muffinmad** [comment]
I think yes, thank you.

I use `Completion.name` as `insertText` property in [LSP completion request](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_completion) response. As documentation notes, `insertText` is subject to interpretation by the client side. I can now use `Completion.complete` to provide `textEdit` instead and leave it to LSP clients.

So if there are no plans to make something like `Completion.complete_full`, feel free to close this issue.

Thanks again!
