### ISSUE TITLE
 Type of substraction result of datetime and datetime is not reported as timedelta

### ISSUE THREAD

**Issue by luabud** [davidhalter/jedi#1577]
#### Reported in https://github.com/microsoft/python-language-server/issues/1542#issuecomment-624205386 by @cdeil 

I see a related bug in the vscode type inference - with Jedi enabled.

Reproducer:
```python
from datetime import datetime, timedelta
now = datetime.utcnow()
future = datetime(2020, 6, 1)
delta = future - now
```

VSCode thinks delta is `datetime.datetime`, but it's a `datetime.timedelta` object.

![Screenshot 2020-05-05 at 19 40 58](https://user-images.githubusercontent.com/852409/81097822-b8227e00-8f08-11ea-8628-52acf2fc9bda.png)

**Comment by davidhalter** [comment]
Turns out that we don't analyze `__sub__` (typeshed is correct here). Happy to help anybody that wants to work on this one.

**Comment by PeterJCLaw** [comment]
Looks like `jedi` doesn't handle `__add__` quite right either -- `sith` reports that the type of inferring a `datetime` plus a `timedelta` is the union of `datetime` and `timedelta`.

**Comment by PeterJCLaw** [comment]
@davidhalter I think I've got a fix for this, in `_infer_comparison_part`, though it doesn't feel like that's entirely the best place for the fix -- that function is going to get quite big if we expand out all the operators to be handled directly in there. Supporting both `__sub__` and also `__rsub__` seems fairly easy too.

For context, here's the snippet:
```python
# elif str_operator == '-':
if l_is_num and r_is_num:
    return left.execute_operation(right, str_operator)

# new bits
left_sub = left.py__getattribute__('__sub__')
if left_sub:
    return left_sub.py__call__(arguments.ValuesArguments([ValueSet([right])]))

right_sub = right.py__getattribute__('__rsub__')
if right_sub:
    return right_sub.py__call__(arguments.ValuesArguments([ValueSet([left])]))
```

I'm guessing ideally we'd push the attribute lookup & call logic into `execute_operation`?
However at the moment it seems that `_infer_comparison_part` does the checking for whether or not the inputs are expected to produce a useful result at each stage, which would be somewhat hard to do in the general case if we're pushing everything into `execute_operation`.

Do you have thoughts on how to keep (or even if we still want to keep) the current fallback behaviour of taking the union of the input types?

**Comment by davidhalter** [comment]
ahhhhhhhhh sorry I already fixed this locally. My bad should have marked it.

**Comment by davidhalter** [comment]
Fixed it like 5 hours ago.

**Comment by davidhalter** [comment]
I'm not used to other people actually fixing open tickets, so I will start to assign myself if I fix something that (if it's not a 10min of work fix).

The solution I pushed is pretty similar to your suggestion and I think it's a pretty good solution. I'm happy to discussing it, if you have other suggestions.

I'm not sure I'm 100% finished with this feature (which is why I didn't push it 4 hours ago).
