### ISSUE TITLE
`_pseudotreenameclass` as `BaseName` type

### ISSUE THREAD

**Issue by muffinmad** [davidhalter/jedi#1578]
```python
Python 3.7.4 (default, Sep 28 2019, 16:39:19) 
>>> from jedi import Script
>>> Script('from typing import Any\n').get_names()[0].type
'_pseudotreenameclass'
```

Please consider adding `_pseudotreenameclass` to the valid values list for [`BaseName.type`](https://jedi.readthedocs.io/en/latest/docs/api-classes.html#jedi.api.classes.BaseName.type) or maybe return `class` instead.

Thanks!

**Comment by davidhalter** [comment]
Good point. Want to fix it yourself? You have to add an `api_type = u'class'` to `_PseudoTreeNameClass`.

**Comment by muffinmad** [comment]
Done.
