### ISSUE TITLE
Support signatures for Django models

### ISSUE THREAD

**Issue by PeterJCLaw** [davidhalter/jedi#1587]
For some model `Book`, we'd ideally have signatures attached to the `__init__` and `objects.create` methods so that you get useful signature information in the following cases:

- `Book(author<tab>`
- `Book.objects.create(author<tab>`
- `Book.objects.filter(author__name<tab>`

@davidhalter for the last case, were you hoping that Jedi would know that `name` is a member of the related `Author` model and offer it as a completion?
That would be really cool if so, though might take some careful experimentation to get right -- I suspect that `_` is not considered as a word separator by most editors, so Jedi might have to offer up `author__name__whatever` rather than just the `name` or `whatever` part.

**Comment by davidhalter** [comment]
> @davidhalter for the last case, were you hoping that Jedi would know that name is a member of the related Author model and offer it as a completion?

> That would be really cool if so, though might take some careful experimentation to get right -- I suspect that _ is not considered as a word separator by most editors, so Jedi might have to offer up author__name__whatever rather than just the name or whatever part.

Not 100% sure if I understand. But yes, we would just autocomplete the full `author__name__whatever`. But only if author was previously there. That's also where I'm realizing that this feature might be a bit harder than expected. Maybe we have to modify Jedi a bit to make this work and basically use `__` as a separator.

So it would be nice to have that feature, but not necessary (to release 0.17.1). Whereas I think we should make the simpler case like `Book.objects.filter(author<tab>` possible.

**Comment by davidhalter** [comment]
I pushed two more relevant commits that fix signature completions. I did not try to make completions possible for things like `actor__email__contains=`. However that would probably need a major refactoring, because that's a pretty new concept that is only present in Django.
