### ISSUE TITLE
Question about specify 'path' in jedi.Project

### ISSUE THREAD

**Issue by carter54** [davidhalter/jedi#1596]
Thanks for the great project. I'm using Jedi with version 0.17.0 and meet following problem.

When I want to specify a project path in Jedi (not the current project when I executing the code), I use 
```
current_code_project_path = "D:\\project1"   # the project path contains the current executing code
target_project_path = "D:\\project2"   # the target project path I want jedi to deal with
project = jedi.Project(path=target_project_path)  # specify the target_project_path in jedi.Project
script = jedi.Script(code=code, project=project)
completions = script.complete(4, 10)  # completion
```

In the following example, when I use the completion in
```
# if A2 is a module in target_project_path (project2)
from A2.
```
I was expecting some completion results from the submodule from A2 in target_project_path. However, It doesn't work. 

But I can get some infer results which I do not expect in the following example
```
# if A1 is a module in current_code_project_path (project1)
from A1.
```
Jedi have some completion results from the submodules in A1.

It seems like 'path' variable in the jedi.Project() class doesn't work...
At the end, I found that I should manually set 'sys_path' in the jedi.Project(), otherwise, it will use the sys_path in the default environment. 
```
environment = jedi.get_default_environment()
sys_path = environment.get_sys_path()
```
If I want to use jedi for completion in the target_project_path, I have to delete the current_code_project_path in th sys_path, and append the target_project_path.
Is there any simple way to specify a project path in jedi completion? 

Thx in advance!

**Comment by davidhalter** [comment]
The path is added to the sys path in your case. Please provide a ZIP file or something that I can unpack and use to reproduce your issue.

**Comment by carter54** [comment]
[Projects.zip](https://github.com/davidhalter/jedi/files/4679525/Projects.zip)
Hi @davidhalter Please have a look at this zip file. It has following structure:
```
-project1
    --jedi_test.py
    --util
        --__init__.py
        --args_checker.py
        --test3.py
        --test4.py
-project2
    --util
         --test1.py
         --test2.py
```

modify the abs path (current_code_project_path and target_project_path) in jedi_test.py within project1
```
import jedi

code = '''import os
import sys

from util.'''

current_code_project_path = 'D:\\Projects\\project1'   # the project path contains the current executing code
target_project_path = 'D:\\Projects\\project2'   # the target project path I want jedi to deal with
project = jedi.Project(path=target_project_path)  # specify the target_project_path in jedi.Project
script = jedi.Script(code=code, project=project)
completions = script.complete(4, 10)  # completion
print(completions)
```
I was expecting to get the completion results from project2 
```[<Completion: test1>, <Completion: test2>]```
but jedi only return the result from project1
```[<Completion: args_checker>, <Completion: test3>, <Completion: test4>]```

I also noticed that, if I delete '__init__.py' file in project1.util, jedi return completion result from both project1 and project2
```
[<Completion: args_checker>, <Completion: test1>, <Completion: test2>, <Completion: test3>, <Completion: test4>]
```

**Comment by davidhalter** [comment]
I set `target_project_path = '../project2'`, because I'm on Linux. It works perfectly fine: 

```
python3.8 jedi_test.py 
[<Completion: test1>, <Completion: test2>]

```

Which Python version are you using?

**Comment by carter54** [comment]
I am using python3.7. I think I have found the reason...
I run the code in pycharm, in the pycharm config, following two options were selected, thus the current project path was added in the sys_path...
![image](https://user-images.githubusercontent.com/26741594/83088010-3071fe80-a0c5-11ea-9e73-79056435c057.png)
If I unselect them, jedi works perfectly fine. 
Sorry for the confusion.

**Comment by davidhalter** [comment]
No problem. Thanks for finding it yourself :)
