### ISSUE TITLE
"# -*- coding: future_fstrings -*-" causes navigating forever

### ISSUE THREAD

**Issue by friendship1** [davidhalter/jedi#1604]
When "coding: future_fstrings" used without future-fstrings installed, (at Python 3.6.9)
vscode-python extension function **"Go to references", "Find all references" and "Go to Definition" wait forever**

example code)
```
# -*- coding: future_fstrings -*- 
def nothing():
    print("hi")
nothing()
```

Obviously, the solution is to install future-fstrings, with "pip3 install future-fstrings" command.

But it took quite a while to find a solution.
I wish people could find this problem easily.
(eg. appropriate error indication for this problem)

I'm using jedi for completion. Below are some additional information.
-   VS Code version: 1.45.1
-   Extension version (available under the Extensions sidebar): 2020.5.80290
-   OS and version: Ubuntu 18.04.1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: future-strings
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977): Jedi
-   Value of the `python.languageServer` setting: Microsoft

**Comment by davidhalter** [comment]
I'm pretty sure this is not a Jedi issue, at least not on master/v0.17.0 branch. Can you reproduce if you upgrade to the latest version?

I even checked v0.15.2 and it's also not an issue. I suspect it's an issue with their backend.

**Comment by friendship1** [comment]
As i checked it myself, it seems that jedi has no problems.
I'll close this issue and reopen vscode-python's.
Thank you.
[https://github.com/microsoft/vscode-python/issues/11937](https://github.com/microsoft/vscode-python/issues/11937)

**Comment by davidhalter** [comment]
Thanks for looking into it!
