### ISSUE TITLE
Jedi has wrong sys.path when target environment has non-standard library location

### ISSUE THREAD

**Issue by mrclary** [davidhalter/jedi#1617]
@davidhalter,
Okay, when I submitted #1540, the problem arose when the host environment was a pyenv environment and the target environment was a conda environment. The solution was that the target environment should not inherit system environment variables from the host environment, i.e. the `CompiledSubprocess` should spawn a clean environment. Well, this works as it should when the target environment python libraries are in a standard relative location, i.e. `../lib` relative to the the executable. Unfortunately, this does not work for target environments where the python libraries are not in a standard location, such as for python embedded in MacOS applications (see [Spyder Mac App](https://github.com/spyder-ide/mac-application))

Python provides a mechanism for handling this, namely by setting the `PYTHONHOME` environment variable to the base directory of the libraries. This, along with other potential `PYTHON...` environment variables, were causing the problem outlined in #1540. Essentially, the wrong python environment variables were being inherited by the subprocess and mucking things up. In the absence of `PYTHONHOME`, it will find the libraries in the standard location.

So, I still think that starting a python subprocess with a clean environment is the correct paradigm, I now think that the solution provided for #1540 in #1546 is incomplete and should include a mechanism for passing explicit environment variables to the subprocess. `Popen` already does this, of course, with the `env` keyword arg. I propose modifying `CompiledSubprocess` to accept an `env` keyword argument that will be passed to the subprocess. The default should be an empty dictionary, but the user has the option to pass in envrionment variables explicitly, if needed.

What are your thougthts?

**Comment by davidhalter** [comment]
I guess this is a good proposal. Since this is not very important to me, are you willing to do this in a PR?

I would probably not name it `env`, but `environment_variables` instead. But that's really just a minor detail.

**Comment by mrclary** [comment]
I'll be happy to submit the PR.
I suggested `env` only because that is the keyword used by `Popen`.
I'm not a fan of long names; how about `env_vars`?

**Comment by davidhalter** [comment]
That's fine.

**Comment by davidhalter** [comment]
Fixed by #1619
