### ISSUE TITLE
Completion of modules which don't exist in a virtual environment

### ISSUE THREAD

**Issue by ANtlord** [davidhalter/jedi#1620]
Hello!

I've noticed that jedi provides completion for modules which don't exist in a virtual environment. Is it expected behaviour? I have `requests` library but it's not included in a virtual environment but Jedi completes it still.

```sh
(.venv) ➜  atest python
Python 3.8.3 (default, May 15 2020, 00:00:00)
[GCC 10.1.1 20200507 (Red Hat 10.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'
>>> import sys
>>> sys.path
['', '/mnt/home/wantlord/develop/atest/.venv/lib64/python38.zip', '/mnt/home/wantlord/develop/atest/.venv/lib64/python3.8', '/mnt/home/wantlord/develop/atest/.venv/lib64/python3.8/lib-dynload', '/usr/lib64/python3.8', '/usr/lib/python3.8', '/mnt/home/wantlord/develop/atest/.venv/lib/python3.8/site-packages']
>>> import jedi
>>> jedi.Script('import requests; requests.').complete()[:5]
[<Completion: adapters>, <Completion: api>, <Completion: auth>, <Completion: codes>, <Completion: compat>]
>>>
(.venv) ➜  atest file /usr/lib/python3.8/site-packages/requests
/usr/lib/python3.8/site-packages/requests: directory
(.venv) ➜  atest pip freeze
jedi==0.17.1
parso==0.7.0
```
It shows that the virtual environment has Jedi and Parso only. A python interactive console can't import `requests` but Jedi sees it regardless it stays outside of the virtual environment. The dump shows `sys.path` so I suspect jedi checks the paths one by one when it is looking for symbols. In my opinion it's correct behaviour but the `sys.path` consists of system paths so it confuses me.

Do I have something wrong with my `virtualenv` or is it an issue?

**Comment by davidhalter** [comment]
That is a good question...

I can kind of reproduce this, if I'm in a venv the same happens to me. I would say it's an issue, but I might be wrong and we're just loading the wrong environment. So it might take a moment until I find the reason for this.

**Comment by davidhalter** [comment]
I'm not sure if I should leave this here as a bug or not. 

I found that the reason for this is that it is part of typeshed. This means that the stubs are available at all times. If you do a goto, you will only go to the stubs. Of course it's not optimal that typeshed stubs get included if the original library is missing. However it's also not that much of a problem IMO. The same might happen now that the Django stubs are always available.

**Comment by ANtlord** [comment]
True, true. It goes to a typeshed file. I think it's not a big deal. Sorry for the false issue. Do you mind if close it?

**Comment by davidhalter** [comment]
I already fixed it. :)
