### ISSUE TITLE
Supported way to "extract" project's root path from a `jedi.Project` class

### ISSUE THREAD

**Issue by bstaletic** [davidhalter/jedi#1622]
YCM currently does the following:

```python
    project_directory = settings.get( 'project_directory' )
    if not project_directory:
      default_project = jedi.get_default_project( os.path.dirname( request_data[ 'filepath' ] ) )
      project_directory = default_project._path
    return jedi.Project( project_directory,
                         sys_path = settings[ 'sys_path' ],
                         environment_path = settings[ 'interpreter_path' ] )
```

In other words, if the user did not specify what is the project root, we call `get_default_project( current_file )._path`. This is because we *always* want to pass `sys_path`, but only sometimes do we have something useful to pass for the `project_directory`. Since `_path` is supposed to be "private", what's the supported way of doing this?

**Comment by davidhalter** [comment]
We can probably make path public.

**Comment by bstaletic** [comment]
That was quick. Thanks!
