### ISSUE TITLE
Support completions on contextlib.contextmanager functions

### ISSUE THREAD

**Issue by PeterJCLaw** [davidhalter/jedi#1624]
For example, if you have a function like this:
``` python
@contextlib.contextmanager
def capture_stdout() -> Iterator[io.StringIO]:
    yield io.StringIO()
```
It would be great if when you used that you got completions on the context object:
``` python
with capture_stdout() as buffer:
    buffer.
```

**Comment by PeterJCLaw** [comment]
Interestingly, this works:
``` python
with contextlib.closing(complex(2, 2)) as f:
    f.re # offers "real"
```

**Comment by davidhalter** [comment]
Are you going to look into it @PeterJCLaw? No need to hurry.

**Comment by PeterJCLaw** [comment]
I'm probably not going to have time to look at this in the next week or so. Will update if I do have a look though.
