### ISSUE TITLE
Interpreter TAB-completions hide private members (starting with _) ?

### ISSUE THREAD

**Issue by bformet** [davidhalter/jedi#1626]
Hi,
We are doing a python REPL based on ptpython.
Is there a way to hide from the completions list everything considered "private" (starting with `_` or `__`) ?
(unless the user types the first underscore)

Thanks

**Comment by davidhalter** [comment]
No. This is intentional. If you want to hide them, you can easily do that yourselves. IMO it is also a bad idea to hide those, because a lot of them (at least non-magic methods) are very relevant information.

**Comment by bformet** [comment]
Thanks for your reply.

I'd be happy to do that myself, but I'm struggeling with the "easily" part. Any hint would be welcome.

Sorry to bother, I guess this is more of a question for stackoverflow.

**Comment by davidhalter** [comment]
Read the documentation and try it out :)

```
for completion in Script(...).complete():
    if not completion.name.startswith('_'):
        # do something with the completion object
```
