### ISSUE TITLE
jedi latest version runtime error for Windows

### ISSUE THREAD

**Issue by jdhao** [davidhalter/jedi#1627]
I am using deoplete-jedi which in turn depends on Jedi. It seems that the latest version of Jedi or master branch of Jedi will error out for Windows.

Here is the MWE to reproduce this issue:

```
import jedi

source1 = '''
import os
os.
'''

script1 = jedi.Script(source1, 3, len('os.'), 'example1.py')
print(script1.completions())
```

Here is the test summary for different combination of platform and jedi version:

| platform | jedi version | error out? |
|----------|--------------|------------|
| Windows  | 0.16.0       | No         |
| Windows  | 0.17.0       | Yes        |
| Linux    | 0.16.0       | No         |
| Linux    | 0.17.0       | No         |

On both Linux and Windows, Python is provided by Anaconda and the version is 3.6.5.

Here is the traceback when error occurs:

```
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\jedi\inference\compiled\subprocess\__init__.py", line 261, in _send
    is_exception, traceback, result = pickle_load(self._get_process().stdout)
  File "D:\Anaconda\lib\site-packages\jedi\_compatibility.py", line 396, in pickle_load
    return pickle.load(file, encoding='bytes')
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\jedi\api\environment.py", line 75, in _get_subprocess
    info = self._subprocess._send(None, _get_info)
  File "D:\Anaconda\lib\site-packages\jedi\inference\compiled\subprocess\__init__.py", line 273, in _send
    stderr,
jedi.api.exceptions.InternalError: The subprocess D:\Anaconda\python.exe has crashed (EOFError('Ran out of input',), stderr=).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_jedi.py", line 8, in <module>
    script1 = jedi.Script(source1, 3, len('os.'), 'example1.py')
  File "D:\Anaconda\lib\site-packages\jedi\api\__init__.py", line 185, in __init__
    project, environment=environment, script_path=self.path
  File "D:\Anaconda\lib\site-packages\jedi\inference\__init__.py", line 90, in __init__
    self.compiled_subprocess = environment.get_inference_state_subprocess(self)
  File "D:\Anaconda\lib\site-packages\jedi\api\environment.py", line 114, in get_inference_state_subprocess
    return InferenceStateSubprocess(inference_state, self._get_subprocess())
  File "D:\Anaconda\lib\site-packages\jedi\api\environment.py", line 80, in _get_subprocess
    exc))
jedi.api.environment.InvalidPythonEnvironment: Could not get version information for 'D:\\Anaconda\\python.exe': InternalError("The subprocess D:\\Anaconda\\python.exe has crashed (EOFError('Ran out of input',), stderr=).",)
```

**Comment by davidhalter** [comment]
This is probably an issue with your Anaconda installation. `0.17.0` has been out for a while, so I doubt there's a fundamental issue on Windows (Also the CI passes on Windows). You can try `0.17.1` or master, but I guess that would also fail. 

You can always avoid this error by using `InterpreterEnvironment`.

Sorry, but I won't be able to help you with this. This is not enough information. I would need at least a better traceback or access to your machine. You could try something like `D:\\Anaconda\\python.exe -m jedi.inference.compiled.subprocess /path/to/parso 2`, maybe that yields a better exception.

**Comment by jdhao** [comment]
version 0.17.1 and master branch also crashes. I tried:

```
D:\\Anaconda\\python.exe -m jedi.inference.compiled.subprocess D:\\Anaconda\\Lib\\site-packages\\parso 2 test_jedi.py
```

or 

```
D:\\Anaconda\\python.exe -m jedi.inference.compiled.subprocess D:\\Anaconda\\Lib\\site-packages\\parso 2
```

The command won't run and hangs. I am not familiar with Jedi. Can you be more specific what should I run?

**Comment by davidhalter** [comment]
> The command won't run and hangs.

That's supposed to happen. I have no idea what's wrong in that case. Sorry I would need access to your machine to debug this.

**Comment by jdhao** [comment]
Unfortunately, this is my work PC which can not be accessed from outside the company.

My python version is 3.6.5. Can you reproduce this issue with a conda virtual env? Meanwhile, I will try to install jedi with plain python from the python official site to see if this issue persists.

**Comment by mattlink** [comment]
This happened to me on RHEL 7.6 using python3.8 in a virtualenv coupled with Coc.nvim. Downgrading to jedi 0.17.0 fixed the issue.

**Comment by davidhalter** [comment]
We are not passing the environment variables anymore since (v0.17.0). This is probably the problem for you @mattlink .

**Comment by davidhalter** [comment]
See also 803c3cb271ead297c4fe3ca916b54ed05a623459

**Comment by Shougo** [comment]
@jdhao Can you bisect the issue?

**Comment by davidhalter** [comment]
Can you try master branch again? We just changed something about environment variables again.

**Comment by jdhao** [comment]
@davidhalter  Trying latest jedi from master:

```
pip install git+https://github.com/davidhalter/jedi.git@master
```

Now it works fine with deplete. No crash observed so far.

**Comment by davidhalter** [comment]
I guess I'm closing :) Feel free to open a new issue if it's an issue again!
