### ISSUE TITLE
Completion suggestions fail for inherited dictionary objects

### ISSUE THREAD

**Issue by smithsp** [davidhalter/jedi#1631]
Consider:
```python
import jedi
s = '''a = dict()

a['b'] = 'help'
print(isinstance(a,dict))

a['
'''
interp = jedi.Script(s)
print(interp.complete(6,3)[0].complete)
```
This appropriately suggests `b'` as the completion.  But if the type of `a` is changed to an inherited class:
```python
import jedi
s = '''
class adict(dict):
    pass
a = adict()

a['b'] = 'help'
print(isinstance(a,dict))

a['
'''
interp = jedi.Script(s)
print(interp.complete(9,3)[0].complete)
```
Then I get the contents of the current directory for completion, instead of the keys of the dictionary `a`.  Am I doing something wrong, or is this a bug?  (Otherwise jedi is awesome - thanks.)

**Comment by davidhalter** [comment]
This is not a bug. This is to be expected. Dictionary completions just exists for dicts. For everything else it would be too much work and too little gain.

I also think that it's generally not a good idea to inherit from builtins.

**Comment by smithsp** [comment]
@davidhalter As usual, I appreciate the prompt response.  I was giving this example to give a minimum working example, but perhaps it was not the appropriate example.  I am actually using `jedi.Interpreter`, instead of `jedi.Script`, and I have an inherited dict as a member of the optional namespace which seems like it should be possible to offer completions via `jedi` for the keys.  If you point me to the place where dictionary key completions are suggested, then perhaps I could look into it myself, as I think it perfectly normal to inherit from builtins.   Perhaps it is a matter of having the parsed script tell me what the object is that is being completed, and querying the `jedi.Interpreter` namespaces for that object.

**Comment by davidhalter** [comment]
Oh, ok. Sorry, I always assume people are talking `Script`. I get way more complaints about that :).

I'm actually a bit surprised that this does not seem to be working. It looks like the `array_type` in `jedi.inference.compiled.access` seems to be doing the right thing for this already and is returning dict for subclasses of dict. So maybe you can write a small test with `Interpreter` so I can reproduce?

**Comment by smithsp** [comment]
@davidhalter Thanks for your patience.  Here is the example:
```python
import jedi

class adict(dict):
    pass
d = dict()
ad = adict()

d['b'] = 'help'
ad['b'] = 'help2'

sd="d['"
sad = "ad['"

interpd = jedi.Interpreter(sd,[locals()])
assert interpd.complete(1,2)[0].complete=="'b'"
interpad = jedi.Interpreter(sad,[locals()])
assert interpad.complete(1,3)[0].complete=="'b'"
```

**Comment by davidhalter** [comment]
Seems like this is working:

```
>>> sd="d['"
>>> sad = "ad['"
>>> import jedi
>>> 
>>> class adict(dict):
...     pass
... 
>>> 
>>> d = dict()
>>> ad = adict()
>>> 
>>> d['b'] = 'help'
>>> ad['b'] = 'help2'
>>> 
>>> sd="d['"
>>> sad = "ad['"
>>> jedi.Interpreter(sd,[globals()]).complete()
[<Completion: 'b'>]
>>> jedi.Interpreter(sad,[globals()]).complete()
```

You just used `locals()` instead of `globals()`.

**Comment by smithsp** [comment]
@davidhalter Thanks for trying, but there seems to be some difference between running at the command line (REPL) and running in a script.  If I take the following
```python
import jedi
import pprint

class adict(dict):
    pass
assert 'adict' in locals()
assert 'adict' in globals()

d = dict()
ad = adict()

d['b'] = 'help'
ad['b'] = 'help2'

sd="d['"
sad = "ad['"
pprint.pprint(globals())
interpd = jedi.Interpreter(sd,[globals()])
assert interpd.complete()[0].complete=="b'"
interpad = jedi.Interpreter(sad,[globals()])
assert interpad.complete()[0].complete=="b'"
print('Success')
```
and put it in a script (`test_jedi.py`) and execute it as `python test_jedi.py`, then it fails, but if I do `python < test_jedi.py` then it succeeds.  Redirecting output to a file, then doing a diff of the two methods (to see the difference in `globals()` yields:
```diff
5,6c5,6
<  '__file__': 'test_jedi.py',
<  '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x10e076c50>,
---
>  '__file__': '<stdin>',
>  '__loader__': <class '_frozen_importlib.BuiltinImporter'>,
16a17
> Success
```
Do you know why the change in `__loader__` or `__file__` would make a difference in whether it works?

**Comment by davidhalter** [comment]
Yay, we finally have a matching case :)

I'm pretty sure it's actually really easy to fix now. These cases usually happen if Jedi is a bit too smart :)

The cause is probably not having `get_key_values` defined on https://github.com/davidhalter/jedi/blob/master/jedi/inference/compiled/mixed.py#L29 . This class does the magic behind things that are defined both as a Python variable and in a Python file. To make things more clear: When given as a file, Jedi can look things up in that file. With stdin there is no such file, it's essentially just a stream of Python code that cannot be looked at again. In the former case Jedi has more knowledge and obviously uses its knowledge wrongly.

**Comment by davidhalter** [comment]
As I said, it was really easy to fix. Thanks for your patience and clarifying what was wrong for you.

**Comment by smithsp** [comment]
Thanks @davidhalter .  Dare I ask what the typical release cycle is, if there is one?

**Comment by davidhalter** [comment]
There's no cycle per se. I ususally do a release every two months. The last one was a month ago. So this would probably be like one more month. But this release might also be a bit special. It's the last release that supports Python 2, so it might take a slight bit longer.

At the same time, there's only two issues open that might make it into that release, so it might not take very long anymore.
