### ISSUE TITLE
Use GitHub releases feature instead of issue or mailing list

### ISSUE THREAD

**Issue by bnavigator** [davidhalter/jedi#1637]
https://github.com/davidhalter/jedi/issues/1063#issuecomment-660322700
> I am switching to a mailing list instead of this issue.
>
> Please write an empty email to `jedi-announce+subscribe@googlegroups.com` to subscribe. Alternatively you can of course also join here: https://groups.google.com/g/jedi-announce.
>
> I might post the next few updates here as well, but the mailing list will be where the releases will be announced in the future.

Why not just us the "Releases" feature on GitHub? If you actually release a tag instead of just tagging the version, people watching for releases get notified. And you get to write proper release announcements, too.

https://github.com/davidhalter/jedi/releases/new

**Comment by davidhalter** [comment]
Thanks for making me aware of this. But I like mailing lists very much for announcements. They are decentralized and do their job very well.

IMO It's also good to not depend on GitHub for everything. If I ever want to move to GitLab or whatever (no guarantee that GitHub is going to be the good guy forever), I'm happy if at least the announcements are decentralized.

**Comment by davidhalter** [comment]
Feel free to continue the discussion. I'm closing, but still reading.

Also as an additional information: I already do "releases" on GitHub. I use tags with messages, so in a way you can just get them here: https://github.com/davidhalter/jedi/releases.

**Comment by bnavigator** [comment]
> Also as an additional point: I already do "releases" on GitHub. I use tags with messages, so in a way you can just get them here: https://github.com/davidhalter/jedi/releases.

You can "get them", but my point is: If you actually make it a real release, people watching the repository ("Watching" or "Releases only") get a notification. Just creating a tag does not trigger a notification. Compare the rendering of your releases page to other projects, e.g. https://github.com/python-control/python-control/releases. Note the green extra tag and the different style.

I am sure that I am not the only one who is hesitating to subscribe to another service or mailing list. Subscribing to the [PyPI RSS feed](https://pypi.org/rss/project/jedi/releases.xml) for new releases is also good enough for me to get notified about a new version so I can start to create a new package for openSUSE. Anyway, just a suggestion.
