### ISSUE TITLE
TypeError on cropped file size slice

### ISSUE THREAD

**Issue by agnash** [davidhalter/jedi#1639]
Hi there,

I'm running the latest update of Jedi provided via the Microsoft VSCode Python extension and hitting an error when loading a larger import. The import is `botostubs`.

**Reproduction env:**
MacOS
VSCode v1.47.2
VSCode Python extension v2020.7.94776 (w/ Jedi v17.1)

**Reproduction steps:**
1. `import botostubs`

2. Command-click on import to go-to source

**Expected result:**
Source loads and auto-complete via IntelliSense should generally work

**Actual result:**
Source does not load and autocomplete does not work.
In VSCode's python log, the last lines of the generated stack trace are as follows:
```
  File "<redacted>/.vscode/extensions/ms-python.python-2020.7.94776/pythonFiles/lib/python/jedi/inference/__init__.py", line 191, in parse_and_get_code
    code = code[:settings._cropped_file_size]
TypeError: slice indices must be integers or None or have an __index__ method
```
**Investigation:**

In https://github.com/davidhalter/jedi/blob/master/jedi/settings.py, you're setting `_cropped_file_size = 10e6  # 1 Megabyte`.

However, as the error states, slice indices must be int or None or have the \_\_index__ method, and type(10e6) is float.

**Comment by davidhalter** [comment]
True, I was pretty surprised that this is a float. Thanks for the precise report!
