### ISSUE TITLE
Add completions for the replace function in dataclasses

### ISSUE THREAD

**Issue by jembishop** [davidhalter/jedi#1640]
Hi I noticed that completions work for dataclasses
```python
import jedi

script = """from dataclasses import dataclass, replace
@dataclass(frozen=True)
class Hello:
   foo: int
a = Hello(fo"""
print(jedi.Script(script).complete())
```
`[<Completion: foo=>, <Completion: format>]`

But the `replace` function in dataclasses does not
```python
script = """from dataclasses import dataclass, replace
@dataclass(frozen=True)
class Hello:
   foo: int
a = Hello(foo=1)
b = replace(a, fo"""
print(jedi.Script(script).complete())
```
`[]`

Is it possible to make this work? I can give it a stab myself if you are too busy (though I have zero experience with jedi). 

Thanks

**Comment by davidhalter** [comment]
While it is possible to make this work, I'm not sure I actually want custom code for this.

It's just too much of a niche use case and I'm not sure I want to maintain this in the future. I'll think about it and will decide later.

**Comment by jembishop** [comment]
Ok thank you for considering. The use case for me would be a patching a typed config, where it is very useful to see the available options with autocomplete.

**Comment by davidhalter** [comment]
Alright. I think I have come to understand the issue at hand.

In case of  `replace(instance, ` we need to infer `instance` somehow and we need to understand that it's the first argument. To do this we need to have an additional  argument in `get_key_values(self, arguments: TreeArguments)`. The big problem is that the actual arguments is not a proper syntax node, it's an error node (the bracket does not terminate). You would therefore need to somehow feed the error node to `TreeArguments` or create something like `ErrorTreeArguments` and at least implement `Arguments.unpack` for it.

Once that's done, you can just create a small entry in `plugins/stdlib.py`, add a few lines and it will probably work well. However, the first part is the hard part. Once that's done I'm happy to add instructions for the second one.

I don't think this is important enough, so I won't do it. If you want, you can try to work on it. But notice that finding the instance (first argument) is going to be quite hard. Everything else is pretty much 5 lines of code.

**Comment by jembishop** [comment]
OK, sounds like a challenge! I'll see if I can implement this. Thanks for providing instructions.

**Comment by davidhalter** [comment]
It's a hard one though, just saying :).

**Comment by jembishop** [comment]
Yeah I know enough now to know that I don't know anything! I don't think I can implement this, thanks for your help anyway

**Comment by davidhalter** [comment]
Thanks for trying anyway :)
