### ISSUE TITLE
Completions are broken again

### ISSUE THREAD

**Issue by KOLANICH** [davidhalter/jedi#1644]
```pythkn
In [1]: import jedi
In [2]: jedi.Script("jedi.").complete()
Out[2]: []
```

Jedi version: 9d1587a41d3847213f5d72ab95dfa2aef36b65a6
Parso version: 6405a1227fb17ef778164f11af0cac50d6941f84
Python version: 3.8.2

**Comment by davidhalter** [comment]
This is not supposed to work. You need to import jedi first.
