### ISSUE TITLE
[0.17.2] Keeps users from upgrading to parso>=0.8.0

### ISSUE THREAD

**Issue by hartwork** [davidhalter/jedi#1648]
Hi!

Commit 209e2713fd699b8a54aa4c8bbd0915e6c51f2092 already has the fix to stop blocking an update to parso>=0.8.0 [like this one](https://github.com/hartwork/jawanndenn/pull/56). Would be great to have a new release containing that fix. Thanks in a advance! :pray: 

On a side note, please consider dropping `<0.9.0` or at least loosening it to `<1.0.0` because it's guaranteed to become a problem at some point and [forces Linux distros to patch it away](https://github.com/gentoo/gentoo/commit/e020c002dd8839c478164f03858740d7566ce342#diff-9bf8013948a3a4f70c36f54394c56d01) again and again already — not ideal. So if that could be dropped, that would rock. Happy to make a pull request as needed.

Best, Sebastian

CC @davidhalter

**Comment by davidhalter** [comment]
Hi Sebastian

No this is intentional. I break backwards compatibility in minor releases and 0.17.2 won't properly work with 0.8.0+.

I think if you are patching it away, it can cause bugs, which are probably a bad idea.

**Comment by hartwork** [comment]
Hi Dave,

thanks for your reply! Any new release of `master` would help, be it 0.17.3 or 0.18.0. Is something like that an option to you?

Thanks in advance! :pray:

**Comment by davidhalter** [comment]
0.18.0 is coming soon, but might take a week or two.

**Comment by hartwork** [comment]
Thank you!

**Comment by hartwork** [comment]
> 0.18.0 is coming soon, but might take a week or two.

@davidhalter any news?

**Comment by hartwork** [comment]
@davidhalter any updates on this matter?

**Comment by davidhalter** [comment]
Sorry for the delay.

I currently don't think really have the time to look into finishing a lot of things.

However I also don't think that this is pressing. Jedi 0.17.2 works great and the newer versions (parso 0.8 and Jedi 0.18) have absolutely no advantage. They only drop Python 2/3.5, so one could argue that they are worse.

**Comment by hartwork** [comment]
Personally, I have two places where I need to deal with this blocker. This multiplies by an unknown factor to everyone using Django and caring about being up to date, e.g. by using Dependabot or crons calling to `pip list --outdated`. So to me it's less about the very changes but about getting rid of incompatibility, exclusion list entries and the like.

Are there related tasks where you need help and where there's an actual chance to reduce the bottleneck factor by helping out?

**Comment by davidhalter** [comment]
What has this to do with Django and why is it a blocker?

**Comment by hartwork** [comment]
Sorry, let me clarify:
- By "blocker" I meant one package blocking another update. This gets me and others into situations like zombie pull requests (https://github.com/hartwork/jawanndenn/pull/56), need to add exclude items, and so on.
- With regard to Django, I should have been more precise and said IPython. I use Django and IPython together everywhere (for it's management command `shell`). So effectively, all my Django projects depend on IPython, jedi, parso. I should have been more precise, sorry.

**Comment by davidhalter** [comment]
But my point being: Why do you need to upgrade parso? Because if you don't, there's absolutely no reason to upgrade anything else.

**Comment by hartwork** [comment]
> But my point being: Why do you need to upgrade parso?

I explained that in detail above already, let me quote:

>     * By "blocker" I meant one package blocking another update. This gets me and others into situations like zombie pull requests ([hartwork/jawanndenn#56](https://github.com/hartwork/jawanndenn/pull/56)), need to add exclude items, and so on.

And also:

> This multiplies by an unknown factor to everyone using ~Django~ IPython and caring about being up to date, e.g. by using Dependabot or crons calling to `pip list --outdated`. So to me it's less about the very changes but about getting rid of incompatibility, exclusion list entries and the like.


What do you want to know more about in detail?

**Comment by davidhalter** [comment]
Ok. I guess I don't understand why a stalled pull request is an issue. 

I see that `pip list --outdated` can be an issue. However one could argue that this is also an issue of `pip list --outdated`. IMO it should only list things that could be updated. Parso cannot be updated, because Jedi has an upper bound.

Sorry, but I guess this is not enough of an argument to justify an urgent release.

**Comment by hartwork** [comment]
@davidhalter you just released parso 0.8.1 with bugfixes that I [cannot apply](https://github.com/hartwork/jawanndenn/pull/142) because jedi 0.17.2 is still blocking updates to parso beyond >=0.8.0. Are any of those bug fixes affecting parso 0.7.1?

**Comment by davidhalter** [comment]
Some do, but they are not really important. Almost all bugfixes are fixing very small issues around obscure Python features or add better parsing for Python 3.9/3.10.

**Comment by hartwork** [comment]
Thanks a lot for addressing the issue in jedi 0.18.0 :pray: :tada:
