### ISSUE TITLE
python-parso 0.8.0 breaks jedi

### ISSUE THREAD

**Issue by mcepl** [davidhalter/jedi#1650]
Hi, when trying to upgrade python-parso in openSUSE/Factory with version 0.8.0, we got 1438 tests in the jedi test suite failed.

Does this [complete log with all details](https://github.com/davidhalter/jedi/files/5074456/_log.txt.zip) make any sense to you? Do we do something wrong?

**Comment by davidhalter** [comment]
Yes. Jedi 0.17.2 is not compatible with parso 0.8.0.

Jedi 0.18.0 will be compatible with parso 0.8.0. It's specified in `setup.py`.

**Comment by mcepl** [comment]
And do you have any idea when jedi 0.18.0 will come?

**Comment by davidhalter** [comment]
Probably in the next few weeks.

**Comment by erdseb** [comment]
Related: #1648, #1659

**Comment by MaxGhenis** [comment]
For posterity, I verified that this is no longer an issue when updating jedi to 0.18.0 (released earlier today) and parso.

**Comment by mcepl** [comment]
> For posterity, I verified that this is no longer an issue when updating jedi to 0.18.0 (released earlier today) and parso.

Yes, the latest python-jedi 0.18.0 together with python-parso 0.8.1 pass all tests for me as well. Thank you!
