### ISSUE TITLE
Basename.docstring() returns string 'None'

### ISSUE THREAD

**Issue by bnavigator** [davidhalter/jedi#1651]
Hi,

currently the [openSUSE Tumbleweed development package for Jedi](https://build.opensuse.org/package/show/devel:languages:python/python-jedi) and packages depending on it (e.g. PyLS) fail, because the [parso package](https://build.opensuse.org/request/show/826257) is about to get updated to 0.8.0 and there is no concept of version pinning for this rolling release disribution.

I don't know if you plan to release a new Jedi version in the next few days, so [I tried to cherry-pick the commits](https://github.com/davidhalter/jedi/compare/v0.17.2...bnavigator:fixpath) which look like they deal with the changed parso handling of Pathlib:
- db0e907
- 480a464
- a16f52b9
- 829dda3
- f12ed208

After resolving the merge conflicts I got all tests to pass except one: `test_inference/test_mixed.py:test_signature` fails because the returned docstring by `s.docstring()` contains `'None'` as string.

https://github.com/davidhalter/jedi/blob/216f976fd5cab7a460e5d287e853d11759251e52/test/test_inference/test_mixed.py#L88-L102

```
[  127s] =================================== FAILURES ===================================
[  127s] ________________________________ test_signature ________________________________
[  127s] 
[  127s]     @pytest.mark.skipif(sys.version_info[0] == 2, reason="Ignore Python 2, EoL")
[  127s]     def test_signature():
[  127s]         """
[  127s]         For performance reasons we use the signature of the compiled object and not
[  127s]         the tree object.
[  127s]         """
[  127s]         def some_signature(foo):
[  127s]             pass
[  127s]     
[  127s]         from inspect import Signature, Parameter
[  127s]         some_signature.__signature__ = Signature([
[  127s]             Parameter('bar', kind=Parameter.KEYWORD_ONLY, default=1)
[  127s]         ])
[  127s]     
[  127s]         s, = jedi.Interpreter('some_signature', [locals()]).goto()
[  127s] >       assert s.docstring() == 'some_signature(*, bar=1)'
[  127s] E       AssertionError: assert 'some_signatu...ar=1)\n\nNone' == 'some_signature(*, bar=1)'
[  127s] E         - some_signature(*, bar=1)
[  127s] E         + some_signature(*, bar=1)
[  127s] E         ?                         +
[  127s] E         + 
[  127s] E         + None
[  127s] 
[  127s] test/test_inference/test_mixed.py:104: AssertionError
```

I could trace it to this line, but then I got lost:
https://github.com/davidhalter/jedi/blob/216f976fd5cab7a460e5d287e853d11759251e52/jedi/api/classes.py#L298-L309

```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /home/abuild/rpmbuild/BUILD/jedi-0.17.2/test/test_inference/test_mixed.py(102)test_signature()
-> assert s.docstring() == 'some_signature(*, bar=1)'
(Pdb) print(s)
<Name full_name='jedi.api.interpreter.NamespaceObject.some_signature', description='def some_signature'>
(Pdb) print(s._name)
MixedName(<CompiledName: (<CompiledValueName: string_name=NamespaceObject>).some_signature>)
(Pdb) print(s._name.py__doc__)
<bound method CompiledName.py__doc__ of <CompiledName: (<CompiledValueName: string_name=NamespaceObject>).some_signature>>
(Pdb) print(type(s._name.py__doc__()))
<class 'str'>
(Pdb) source s._name.py__doc__
333         def py__doc__(self):
334             value, = self.infer()
335             return value.py__doc__()
(Pdb) p s._name.infer
<bound method MixedName.infer of MixedName(<CompiledName: (<CompiledValueName: string_name=NamespaceObject>).some_signature>)>
(Pdb) p s._name.infer()
S{<MixedObject: <function test_signature.<locals>.some_signature a..; <FunctionValue: <Function: some_signature@95-97>>>}
```

So I added this: (610165df9e91e658b799f184af0481b470f91298)
```diff
diff --git a/jedi/api/classes.py b/jedi/api/classes.py
index 4e0d2635..a47a919a 100644
--- a/jedi/api/classes.py
+++ b/jedi/api/classes.py
@@ -298,6 +301,8 @@ class BaseName(object):
         if isinstance(self._name, ImportName) and fast:
             return ''
         doc = self._get_docstring()
+        if doc == 'None':
+            doc = ''
         if raw:
             return doc
```

I don't know if this is a result of the selective cherry-picking and not relevant for the next version or whether this information could be useful for you. So here it is.

Cheers,
Ben

**Comment by davidhalter** [comment]
Please for the love of god don't try to get parso 0.8.0 running with Jedi 0.17.2. If I understand you correctly, this is what you're trying to do. This will not and never work. Just wait until Jedi 0.18.0 is released.

**Comment by bnavigator** [comment]
Well, the unit tests [are passing](https://build.opensuse.org/package/show/home:bnavigator:branches:devel:languages:python/python-jedi). Are you telling me, the unit tests don't cover whether jedi is working with a given environment? ;)

**Comment by davidhalter** [comment]
That's exactly what I'm saying. Unit tests can only do so much.

Also why hurry? Parso 0.7.x is in a good shape and there is absolutely no reason to upgrade as long as Jedi 0.18.0 is not out.

**Comment by bnavigator** [comment]
Yeah, hence the ";)"

My only cause for impatience is, that someone updated parso in the OBS devel project and submitted an SR into Factory. This will block a staging project until Jedi passes.

Now if I submit my patch, exactly that will happen. You are saying I will break things. So better not submit it.

**Comment by davidhalter** [comment]
Yeah, I would prefer that. I also recommend to downgrade parso again if Jedi is also used.

Why does OBS need parso?

**Comment by bnavigator** [comment]
With "OBS", I mean the openSUSE Build Service, not the video application.

Fortunately, Jedi is in Ring1 for openSUSE Staging, so the updated Parso will not [make its way into the real distribution](https://build.opensuse.org/request/show/826257) (which is built from "Factory") until the Jedi tests pass in the respective staging project. That is currently [Staging:H](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:H/python-jedi), but I guess, as soon as Parso gets unstaged again, this link won't be relevant anymore.
