### ISSUE TITLE
Broken autocorrect due to conda installing jedi 0.15

### ISSUE THREAD

**Issue by thomasaarholt** [davidhalter/jedi#1654]
On Windows 10, latest conda with conda-forge added, I notice that tab-completion no longer works in IPython, Jupyter Notebook or Lab.
On inspection, I notice that I've got `jedi 0.15` (not `0.17.2`) installed, despite creating a fresh and small conda environment that day.

`conda create --name test jedi` tries to install `jedi 0.15.2`. I notice that if I force `jedi=0.17`, the `parso` package goes from version 0.8 to 0.7.1. That is the only difference in the environments. (and tab-completion works now)

I don't fully understand how conda resolves dependencies, so its unclear to me where the bug lies. I suspect a number of people are experiencing autocorrect not working on new environments at the moment.

Here is the list of differing packages:
```bash
$ conda create --name test jedi
  jedi               conda-forge/win-64::jedi-0.15.2-py38_0
  parso              conda-forge/noarch::parso-0.8.0-pyh9f0ad1d_0
```

```bash
$ conda create --name test jedi=0.17
  jedi               conda-forge/win-64::jedi-0.17.2-py38h32f6830_0
  parso              conda-forge/noarch::parso-0.7.1-pyh9f0ad1d_0
```

**Comment by thomasaarholt** [comment]
On further inspection I see that this commit which changes the dependency from parso < 0.8 to parso > 0.8, was made after the July 17th (latest) release. For some reason, conda prefers including `parso = 0.8` over `jedi = 0.17.2` when installing jedi.

Could I suggest creating a 0.17.3 release to handle this issue?

**Comment by davidhalter** [comment]
0.18.0 will be created soon, but as I mentioned in another issue as well, this is a conda issue and should therefore be reported there.

**Comment by thomasaarholt** [comment]
Apologies for not searching through the closed issues. I would have expected a related issue to stay open to prevent further creation like I just did. I'll take a look and see if there exists a conda issue, and if not, create one.
