### ISSUE TITLE
Latest tagged version (v0.17.2) is incompatible with latest tagged version of parso (v0.8.0)

### ISSUE THREAD

**Issue by phinfinity** [davidhalter/jedi#1659]
Hi,

It looks like the latest tagged version won't test properly against the latest version of parso (since parso now uses Path objects) and the fixes for that doesn't have a new tagged version yet. Looks like they're fine from the latest git commit. Could you please add a new latest tagged version that works with parso?

Ran into this while trying to update some package versions.

Thanks very much!

**Comment by davidhalter** [comment]
Please read the other closed issues.

**Comment by erdseb** [comment]
Related: #1648, #1650
