### ISSUE TITLE
PosixPath object has not attribute 'endswidth'

### ISSUE THREAD

**Issue by petobens** [davidhalter/jedi#1661]
I originally reported this issue (with details) on the deoplete-jedi vim plugin (https://github.com/deoplete-plugins/deoplete-jedi/issues/266) but I was told it's probably a jedi issue. Thanks in advance

**Comment by davidhalter** [comment]
I'm pretty sure you are using parso 0.8.0. No idea how you got that. I'm closing, because this is either a Jedi development version (with an outdated parso) or a new parso version that you should not be using (see setup.py).

**Comment by petobens** [comment]
parso version was indeed the problem. Thanks for clearing that up. Sorry for the noise
