### ISSUE TITLE
Consider using isort?

### ISSUE THREAD

**Issue by PeterJCLaw** [davidhalter/jedi#1664]
@davidhalter just wondering if you'd be interested in using [`isort`](https://github.com/timothycrosley/isort) to format the imports within Jedi?
I use it in a lot of other projects and I find it speeds up adding imports quite a bit as you can just put them in the file wherever you are (at the right scope) and it'll deal with pulling them up to the top of the file. This avoids a loss of context just to add an import.

It's fairly configurable, so it should be possible to maintain the current layout style if you want it to. (it looks like `multi_line_output=2` plus `use_parentheses=False` is the current layout, but with sorting)

**Comment by davidhalter** [comment]
I would strongly prefer not to add it. I don't think it adds real value and I don't really want to run it locally. So if you think it's really important, I might reconsider. But I personally don't have a reason to use it.
