### ISSUE TITLE
AttributeError for posix path

### ISSUE THREAD

**Issue by rjpower4** [davidhalter/jedi#1666]
Using jedi in emacs  currently gives the following error: 

```
<a lot of other stuff>
...

  File "/usr/lib/python3.8/site-packages/jedi/inference/value/module.py", line 159, in is_stub
    if self._path is not None and self._path.endswith('.pyi'):
AttributeError: 'PosixPath' object has no attribute 'endswith'
```

With the update to the `PosixPath` it no longer has `endswith`. I think this is fixed in the repo currently, but package maintainers bringing down the most recent tag, i.e. 0.17.2 don't have this fixed yet. Is there a new tag expected any time soon?

**Comment by davidhalter** [comment]
Your parso version and Jedi version are not matching. Jedi 0.17.2 is NOT compatible with parso 0.8.0.

This might be because of a bug in conda, if you are using that (see the last couple of issues).

Also please next time search the last few issues (there's a ton of them that ask the same thing).
