### ISSUE TITLE
`goto` uses Django stubs instead of Django source

### ISSUE THREAD

**Issue by OutOfFocus4** [davidhalter/jedi#1667]
I am using Visual Studio code with the Python extension to develop Django applications. Since the extension was updated to use jedi 0.17+, using the "Go to definition" on model managers and view methods opens a stub file rather than the Python file in the Django library.

As an example, I created a file `/tmp/example/demo.py` with the following contents:

```python
from django.db import models


class Demo(models.Model):
	pass

Demo.objects.bulk_create
```

Then I ran the following in a python shell:

```python
import jedi
with open('demo.py', 'r') as file:
    source = file.read()
script = jedi.Script(source=source, project=jedi.get_default_project('/tmp/example'))
print(script.goto(line=7, column=22)[0].module_path)
# prints /tmp/example/venv/lib/python3.8/site-packages/jedi/third_party/django-stubs/django-stubs/db/models/query.pyi
```

**Comment by davidhalter** [comment]
Not sure if this is something we should fix, but I understand that this is not correct and will leave it open.

**Comment by davidhalter** [comment]
Sorry wrong tag.

**Comment by davidhalter** [comment]
This is a django stubs issue. You should probably report it [here](https://github.com/typeddjango/django-stubs).

`_BaseQuerySet` does not exist in Django and Jedi tries to jump to that.

**Comment by davidhalter** [comment]
Reported it myself: https://github.com/typeddjango/django-stubs/issues/551

I really think that this is not a Jedi issue and needs to solved upstream.
