### ISSUE TITLE
docstring() call results in a RecursionError

### ISSUE THREAD

**Issue by djr7C4** [davidhalter/jedi#1677]
When using Jedi to complete 'cq.' after 'import cadquery as cq', a Recursion error occurs.  This is specifically with CadQuery 2.0 installed in a Python 3.7 miniconda environment.  I used 3.7 instead of 3.8 because the conda cadquery package is not set up to use 3.8 yet.  See the attached files for a minimal example and the backtrace.  The directory /home/user/conda-test/jedi is the directory where I have cloned the jedi repository.

I'm including the setup process I used since I found that the setup process for cadquery is a bit finicky to get right.  After installing miniconda3, run the following.  Combining some of these commands seems to cause problems for unknown reasons.

    conda install -c conda-forge -c cadquery python=3.7
    conda install -c conda-forge -c cadquery cadquery=2
    conda install -c conda-forge -c cadquery cq-editor=0.1.1

I've tested this with both 17.2 and the current master branch.  The behavior is the same in both cases although the output below is specifically with the master branch (04572422d4e4e650de85f54fd7dc7c4e50d7fbce as of this report).  This may be related to #1565.  However, since that bug was fixed according to that issue, I am reporting this separately.

[files.zip](https://github.com/davidhalter/jedi/files/5322473/files.zip)

**Comment by davidhalter** [comment]
I'm going to leave this open for a while, but if nobody is going to have a simpler reproduction case for this, I will close again. I would like to fix this, but I need to reproduce it somehow.

**Comment by djr7C4** [comment]
I'll see if I can come up with a simpler example that doesn't involve
cadquery.

**Comment by djr7C4** [comment]
I'll try to come up with a standalone example that doesn't use cadquery.

**Comment by djr7C4** [comment]
I've created a minimal version of CadQuery (2 files with 1 line of code each) that shows the problem.  I reproduced this bug in Jedi 17.2 with Python 3.8 (no Conda installation is necessary).  To reproduce the bug, just run `jedi_example.py`.  It needs to be run from inside the directory that contains it (otherwise, it will not find cq_example.py).

Note that a non-existent module called `selectors` is being imported in the modified CadQuery modules.  This was a real module in the original CadQuery code but removing it doesn't seem to affect this bug so I have deleted it for simplicity.

[minimal_example.zip](https://github.com/davidhalter/jedi/files/5352110/minimal_example.zip)

**Comment by davidhalter** [comment]
Thanks! I can reproduce this and it's definitely a bug.

**Comment by davidhalter** [comment]
Thanks again for filing a great reproduction sample. Most of the time it's not nearly as easy to reproduce something. So it's appreciated.

**Comment by djr7C4** [comment]
No problem!  I use Jedi all the time in Emacs through jedi.el so I appreciate your work on this project.
