### ISSUE TITLE
Keep in memory cache for longer and  possibly as long as needed

### ISSUE THREAD

**Issue by asif-mahmud** [davidhalter/jedi#1679]
From the documentation i saw this settings - `jedi.settings.call_signatures_validity`. Does it control how long the in memory cache stays alive ? if so, is it possible to keep the in memory cache alive for as long as needed. I mean, as long as a project is being worked on, jedi should keep the symbols in memory for faster completion.

**Comment by davidhalter** [comment]
No that's not it. This cache is a very bad version of a cache and does not really help with anything more than call signatures (and even there it might be buggy, especially if you use a high number).

For caching, this is the issue: https://github.com/davidhalter/jedi/issues/1059
