### ISSUE TITLE
invalid syntax for star-unwrapped enumeration values

### ISSUE THREAD

**Issue by relikd** [davidhalter/jedi#1680]
Hey there dear people,

not sure if this is the right place. I am using jedi with Anaconda in Sublime Text.
I do get an “invalid syntax” error for legitimate python3 code:

```python
x = [['RAM', 8, 8], ['CPU', 3.5]]
for kind, *values in x:
    print(f'{kind} has {len(values)} hardware components')
```

It is not a major issue but would be nice if my IDE would not complain about it 😄

**Comment by relikd** [comment]
Also, this is valid syntax but is not recognized as such:

```python
def funny():
    return f'''{'hi'}'''
```

**Comment by davidhalter** [comment]
jedi parso versions?

**Comment by relikd** [comment]
v0.17.1 I think https://github.com/DamnWidget/anaconda/commit/e8aeef9e591135af24cb56ed2d0a3a419dc38d00#diff-b9a7ec1566e6291ac30adb624c0aafe9a85eb5b92919299a551461840b883349R30

**Comment by davidhalter** [comment]
Not sure what it was, but in general Jedi only recognizes syntax for the Python version that you are using (in Jedi terms this is called an `Environment`).
