### ISSUE TITLE
Analysis displays errors even if code is correct

### ISSUE THREAD

**Issue by jl0pd** [davidhalter/jedi#1683]
Jedi displays error messages even if code is correct. 
Example, `range` takes 1 to 3 parameters, but analysis says that it takes 4

```python
import jedi

code = """
for i in range(10):
    pass
"""

script = jedi.Script(code)
print(script._analysis()[0].message)
```

`TypeError: <Name: __init__@1074,12>() takes from 3 to 4 arguments (2 given).`

Version: 0.17.1

**Comment by davidhalter** [comment]
The `_analysis` command is basically in maintenance mode and not public. It will not be developed further.

If there's ever something like it I will rewrite Jedi in Rust. 

How did you even come up with trying it?
