### ISSUE TITLE
Feature request: smart case completion

### ISSUE THREAD

**Issue by infokiller** [davidhalter/jedi#1685]
Right now, it's possible to either use case sensitive, or case insensitive completion.

A very useful feature implemented by many tools (vim, ripgrep, etc.) is "smart case": when the input is fully lowercase, it behaves like case-insensitive matching, but when the input has at least one uppercase char, it behaves like case sensitive completion.

Thanks!

**Comment by davidhalter** [comment]
If you want this you will probably have to implement it yourself. It's probably not even hard :) You can basically just look at the fuzzy code completion and do something similar for smart case completions.

I personally won't do it, so if you don't do it, I will close.

**Comment by infokiller** [comment]
OK, I will close this and I'll take a look at implementing this. I figured I should open an issue before working on this anyway to make sure you're fine with merging it and no one else is working on it.

On the other hand, I didn't know there's fuzzy search!
I don't see a way to enable it with `jedi.settings`. Is there a way to enable it for IPython?

**Comment by davidhalter** [comment]
> OK, I will close this and I'll take a look at implementing this. I figured I should open an issue before working on this anyway to make sure you're fine with merging it and no one else is working on it.

You did the right thing :)

> I don't see a way to enable it with jedi.settings. Is there a way to enable it for IPython?

Check the documentation, it's part of the `complete` API and just a param.
