### ISSUE TITLE
How to figure out completion prefix without `completion.complete` in fuzzy mode?

### ISSUE THREAD

**Issue by infokiller** [davidhalter/jedi#1687]
Hi,

I'm trying to make IPython use fuzzy completion, however it doesn't work right now because `Completion.complete` [is None for fuzzy completions](https://github.com/davidhalter/jedi/commit/41a6591d88efcbf29832844e877b863a49d1d8ff).
From what I can see, IPython needs this field [to compute which prefix should be replaced](https://github.com/ipython/ipython/blob/master/IPython/core/completer.py#L1956) in the completion input. For example, if the current text is `os.ab` and there's an `abort(` completion, IPython needs to know that after accepting the completion the new text is `os.abort(` and not `os.ababort(` or something else.

Is there a way to get the same information with fuzzy completions?

Thanks

**Comment by davidhalter** [comment]
At the moment there's no such thing, but I agree that this would probably be interesting.

Thinking about doing something for this.

**Comment by davidhalter** [comment]
Is `Completion._like_name_length` what you are searching for? It's not public at the moment, but we could make it public (of course with a better name).

So if that's what you want, do you have a better idea for a name? Maybe also @PeterJCLaw has a better idea. Something like `replace_char_count` maybe?

**Comment by infokiller** [comment]
Yes, I think `_like_name_length` will work.

**Comment by infokiller** [comment]
This is the provisional PR I want to send IPython: https://github.com/ipython/ipython/compare/master...infokiller:add-jedi-fuzzy

Will need to make `_like_name_length` public first.
@davidhalter let me know if you want me to rename `_like_name_length` to something public.

**Comment by davidhalter** [comment]
I'm happy to make it public, but I need a better name :)

**Comment by infokiller** [comment]
Is `completion_prefix_len` inaccurate?

**Comment by davidhalter** [comment]
make it `get_completion_prefix_length()` and we're good. You can just return that from `_like_name_length`.

**Comment by infokiller** [comment]
I see the `Completion` class uses properties (for example in https://github.com/davidhalter/jedi/blob/master/jedi/api/classes.py#L687), do you prefer a function or a property?
