### ISSUE TITLE
YCM in python runtime error Can‘t jump jump to definition

### ISSUE THREAD

**Issue by tricomm** [davidhalter/jedi#1690]
# Issue Prelude

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [x] I have read and understood YCM's [CONTRIBUTING][cont] document.
- [x] I have read and understood YCM's [CODE_OF_CONDUCT][code] document.
- [x] I have read and understood YCM's [README][readme], **especially the
  [Frequently Asked Questions][faq] section.**
- [x] I have searched YCM's issue tracker to find issues similar to the one I'm
  about to report and couldn't find an answer to my problem. ([Example Google
  search.][search])
- [x] If filing a bug report, I have included the output of `vim --version`.
- [x] If filing a bug report, I have included the output of `:YcmDebugInfo`.
- [x] If filing a bug report, I have attached the contents of the logfiles using
  the `:YcmToggleLogs` command.
- [x] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [x] If filing a bug report, I have included a minimal test case that reproduces
  my issue, using `vim -Nu /path/to/YCM/vimrc_ycm_minimal`, including what I
  expected to happen and what actually happened.
- [x] If filing a installation failure report, I have included the entire output
  of `install.py` (or `cmake`/`make`/`ninja`) including its invocation
- [x] **I understand this is an open-source project staffed by volunteers and
  that any help I receive is a selfless, heartfelt _gift_ of their free time. I
  know I am not entitled to anything and will be polite and courteous.**
- [x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps.**F

Thank you for adhering to this process! It ensures your issue is resolved
quickly and that neither your nor our time is needlessly wasted.

# Issue Details

> Provide a clear description of the problem, including the following key
> questions:

* What did you do?
when I input, ":YcmCompleter GoTodefiniton" in a python file
this file can run rightly. 
> Include steps to reproduce here.

1. `vim -Nu /path/to/YCM/ycm_vimrc_minimal`
2. `:edit test.py`
3. Enter insert mode and type `.....`

> Include description of a minimal test case, including any actual code required
> to reproduce the issue.

> If you made changes to `vimrc_ycm_minimal`, pase them here:

```
<contents of ycm_vimrc_minimal>
```

* What did you expect to happen?
I want to jump to the definiton of function in it‘s definition file
> Include description of the expected behaviour.

* What actually happened?
<img width="1203" alt="Screen Shot 2020-10-29 at 12 23 57 AM" src="https://user-images.githubusercontent.com/24520221/97468877-b77f1780-1980-11eb-8d00-7e8f6685aedc.png">

> Include description of the observed behaviour, including actual output,
> screenshots, etc.

# Diagnostic data

## Output of `vim --version`

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep  9 2020 23:27:04)
Unknown option argument: "--vision"
More info with: "vim -h"
siiyrang@siiydeMacBook ~ % vim -vision
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep  9 2020 23:27:04)
Garbage after option argument: "-vision"
More info with: "vim -h"
siiyrang@siiydeMacBook ~ % vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep  9 2020 23:27:04)
macOS version
Included patches: 1-1650
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl              +title
-clientserver      +job               +persistent_undo   -toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               +ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.15 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.32.0/lib/perl5/5.32.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/config-3.8-darwin -lpython3.8 -framework CoreFoundation  -lruby.2.7

```

## Output of `YcmDebugInfo`

```
Printing YouCompleteMe debug information...
-- Resolve completions: Up front
-- Client logfile: /var/folders/vr/q2r0ll7j3zzbkfjtkrvk9m2r0000gn/T/ycm_xlv25cq4.log
-- Server Python interpreter: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3
-- Server Python version: 3.8.5
-- Server has Clang support compiled in: True
-- Clang version: clang version 10.0.0
-- No extra configuration file found
-- Python completer debug information:
--   Python interpreter: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3
--   Python root: /Users/siiyrang/Documents/project/HomeWork/CV assigment2
--   Python path: ['/Users/siiyrang/Github/PaddleDetection', '/Users/siiyrang/Documents/project/HomeWork/CV assigment2', '/Lib
rary/Frameworks/Python.framework/Versions/3.8/lib/python38.zip', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python
3.8', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload', '/Users/siiyrang/Library/Python/3.8/lib/p
ython/site-packages', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages']
--   Python version: 3.8.5
--   Jedi version: 0.17.2
--   Parso version: 0.7.1
-- Server running at: http://127.0.0.1:61571
-- Server process ID: 35161
-- Server logfiles:
--   /var/folders/vr/q2r0ll7j3zzbkfjtkrvk9m2r0000gn/T/ycmd_61571_stdout_ryksfhbs.log
--   /var/folders/vr/q2r0ll7j3zzbkfjtkrvk9m2r0000gn/T/ycmd_61571_stderr_i9qugv7b.log
```

## Output of `YcmDiags`

```
No warnings or error detected.
```

## Output of `git rev-parse HEAD` in YouCompleteMe installation directory

```
paste output here
```
vimrc_ycm_minimal

" windows default encoding is not supported
set encoding=utf-8

" If you using neovim and python isn't loading, copy your python setup from your
" vimrc here:
"
" let g:python3_host_prog = '/path/to/python3/with/neovim/module'
"
" But remember that neovim is not officially supported, so please reproduce in
" Vim.

" Enable debugging
let g:ycm_keep_logfiles = 1
let g:ycm_log_level = 'debug'

" If the base settings don't repro, paste your existing config for YCM only,
" here:
" let g:ycm_....

" Load YCM (only)
let &rtp .= ',' . expand( '<sfile>:p:h' )
filetype plugin indent on

## Contents of YCM, ycmd and completion engine logfiles
Traceback (most recent call last):
  File "/Users/siiyrang/.vim/bundle/YouCompleteMe/python/ycm/client/base_request.py", line 73, in HandleFuture
    return _JsonFromFuture( future )
  File "/Users/siiyrang/.vim/bundle/YouCompleteMe/python/ycm/client/base_request.py", line 256, in _JsonFromFuture
    raise MakeServerException( response.json() )
ycmd.responses.ServerError: RuntimeError: Can't jump to definition.

> Reproduce the issue with `vim -Nu /path/to/YCM/vimrc_ycm_minimal`, which
> enabled debug logging and other useful diagnostics.  Include a link to a
> [gist][] containing all of the log files listed by `:YcmToggleLogs`.

## OS version, distribution, etc.

macOS 10.15.7

## Output of build/install commands
when I input, ":YcmCompleter GoTodefiniton"

there show,RuntimmError: Can't jump to definition
> Include link to a [gist][] containing the invocation and entire output of
> `install.py` if reporting an installation issue.

[cont]: https://github.com/ycm-core/YouCompleteMe/blob/master/CONTRIBUTING.md
[code]: https://github.com/ycm-core/YouCompleteMe/blob/master/CODE_OF_CONDUCT.md
[readme]: https://github.com/ycm-core/YouCompleteMe/blob/master/README.md
[faq]: https://github.com/ycm-core/YouCompleteMe/wiki/FAQ
[search]: https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fgithub.com%2Fycm-core%2FYouCompleteMe%2Fissues%20python%20mac
[gist]: https://gist.github.com/

—————————————————————————————————————————
there is a simple test case
text.py is follow

import cv2
import numpy
print("sad")
cv2.addText()
numpy.amax()

when I input :YcmCompleter GoTodefinition for "cv2", "numpy", "print", "addText" and "amax" everything is correct, but except the addText(). for addText() it log a error “RuntimmError: Can't jump to definition”.
actually I can't jump every function in opencv(cv2)
but when keep my cursor on the cv2's function I can see the doc file and the command ":YcmCompleter GetDoc
"is work well.

**Comment by davidhalter** [comment]
Please describe your issue properly. I don't really understand the issue and I'm not interested in information about YCM or VIM.

You can however post this issue to the YCM tracker if you want to.

**Comment by tricomm** [comment]
> Please describe your issue properly. I don't really understand the issue and I'm not interested in information about YCM or VIM.
> 
> You can however post this issue to the YCM tracker if you want to.

sorry,I'm not familiar with jedi. I send this issue in YCM's issue they tell my it is a jedi problem, and advice my push this problme here.
actually it make me confuse. maybe YCM is using jedi service.

**Comment by davidhalter** [comment]
This all makes sense. I still don't understand your issue.
