### ISSUE TITLE
Goto doesn't find a reference in a nested for in loop

### ISSUE THREAD

**Issue by epicmonkey** [davidhalter/jedi#1691]
In the example below I'm selecting a reference to `y` and then calling `goto`.

Expected result: a list including `for y in step(1, -.05, 41))`
Actual result: an empty list.

I'm running the latest release: Jedi==0.17.2. Upd: the same happening in master branch rev. 69750b9bf0c41c3a202a77621c14994f1f2dbcba

```
>>> a = '''\
... rows = (("*" if abs(mandelbrot(complex(x, y))) < 2 else " "
...         for x in step(-2.0, .0315, 80))
...         for y in step(1, -.05, 41))
...
... "\n".join("".join(row) for row in rows)
... '''
>>> j = jedi.Script(a)
>>> v = j.get_names(references=True, all_scopes=True)[5]
>>> v
<Name full_name='__main__.y', description='y'>
>>> v.goto()
[]
```

However, Jedi works as expected if I do the same for `x`:
```
>>> v = j.get_names(references=True, all_scopes=True)[4]
>>> v
<Name full_name='__main__.x', description='x'>
>>> v.goto()
[<Name full_name='__main__.x', description='for x in step(-2.0, .0315, 80)'>]
```

**Comment by davidhalter** [comment]
Thanks for the report and the good reproduction case!
