### ISSUE TITLE
Complete returns a strange docstring if property has a return type hints None or Optional[...]

### ISSUE THREAD

**Issue by magro11** [davidhalter/jedi#1695]
Hello,

I would like to show this issue based on the following example (script **test.py**):

```
from typing import Optional, List

class Test:

    @property
    def prop1(self) -> int:
        """Returns prop1."""
        return 1
    
    @property
    def prop2(self) -> List[int]:
        """Returns a list of integer (prop2)."""
        return [2, 3, 4]
    
    @property
    def prop3(self) -> Optional[List[int]]:
        """Returns None or a list of integer (prop3)."""
        return [2, 3, 4]
    
    @property
    def prop4(self) -> None:
        """Non-sense property."""
        return None
```

The class **Test** has four different properties with different type hints for the returned value.

Now I use Jedi (**0.17.2**) together with Python 3.7.0 (Win 10, x64) and try to get the docstrings and type_hints of these properties. Therefore I created the following test script:

```
import jedi

code = \
"""import test
myTest = test.Test()
p1 = myTest.prop"""

script = jedi.Script(code=code)
compl = script.complete(line=3, column=14)

for c in compl:
    print(f"----- {c} -----")
    print("Docstring:\n", c.docstring())
    print("Return type:\n", c.get_type_hint())
```

This script is stored in the same folder than **test.py**, such that the import statement in the `code` literal can be resolved.

The output looks like this:

```
----- <Completion: prop1> -----
Docstring:
 Returns prop1.
Return type:
 int
----- <Completion: prop2> -----
Docstring:
 Returns a list of integer (prop2).
Return type:
 List[int]
----- <Completion: prop3> -----
Docstring:
 NoneType()

Returns None or a list of integer (prop3).
Return type:
 Optional[List[int]]
----- <Completion: prop4> -----
Docstring:
 NoneType()

Non-sense property.
Return type:
 None
```

I am wondering, why the docstring of `prop1` and `prop2`, that are neither `None` nor `Optional[...]` contains the original
docstring only (this is what I would expect), however the docstrings of `prop3` and `prop4` start with **NoneType()**, followed
by a new line and the original docstring.

Is this desired behaviour?

Thank you very much.

**Comment by davidhalter** [comment]
> Is this desired behaviour?

No :)

Thanks for the report!
