### ISSUE TITLE
Extract variable only extracts first occurence

### ISSUE THREAD

**Issue by blayz3r** [davidhalter/jedi#1697]
![image](https://user-images.githubusercontent.com/12205650/99215671-a1a38c00-27a1-11eb-915e-82696885f211.png)
![image](https://user-images.githubusercontent.com/12205650/99215690-b1bb6b80-27a1-11eb-8eed-7341b3d39179.png)

**Comment by blayz3r** [comment]
See https://github.com/pappasam/jedi-language-server/issues/49

**Comment by davidhalter** [comment]
I'm happy to have a discussion with anyone that wants to implement this, but I will close for now. I don't think this is a necessary feature.
