### ISSUE TITLE
Use function annotations

### ISSUE THREAD

**Issue by davidhalter** [davidhalter/jedi#170]
Jedi basically supports function annotations. I never implemented the final stage of autocompletion, because function annotations have not been defined to be anything specific in Python 3. But probably it would be a good idea to implement it. (~ 10 line patch for Jedi)

I thought about it for a little while and then remembered that [pep 3107][1] talks about this:

> Despite yet more discussion, it was decided not to standardize a mechanism for annotation interoperability. Standardizing interoperability conventions at this point would be premature. We would rather let these conventions develop organically, based on real-world usage and necessity, than try to force all users into some contrived scheme.

I realized that Jedi is exactly the software that should try to define the usage of these function annotations.

I thought about this again, because @ceronman posted this article: http://ceronman.com/2013/03/12/a-powerful-unused-feature-of-python-function-annotations/

[1]: http://www.python.org/dev/peps/pep-3107/

**Comment by leebrooks0** [comment]
What is the status here re autocompletion? It seems like it is easy to implement (first comment says about 10 lines of code).

**Comment by dbrgn** [comment]
For the record:

https://www.python.org/dev/peps/pep-0483/
https://www.python.org/dev/peps/pep-0484/

**Comment by davidhalter** [comment]
@leebrooks0 The status is that we haven't implemented anything. A path at this point would be more complicated than 10 LOC, because there's the whole mypy stuff now (as defined in PEP 484).

@dbrgn Thanks!

**Comment by mikn** [comment]
With https://github.com/ambv/typehinting now accepted and slated for release in 3.5, it would be really cool if it could go into Jedi. Is there any plan for it? @davidhalter

**Comment by davidhalter** [comment]
Well, there's no specific plan, because I don't really have time right now to do it. But if someone's willing to do it, I would be happy to support.

**Comment by mikn** [comment]
If you have a concrete outline or idea of how to implement it within jedi,
I may have time. :)

**Comment by davidhalter** [comment]
Sorry for the big delay :) I forgot about it.

But: I guess we should start by ignoring the `typing` module. We should just make it possible for Jedi to understand normal references (should be fairly easy). The annotations are already scanned. Maybe you need to improve the parser as well.

Once that's merged, we can start dealing with the special cases: e.g. https://www.python.org/dev/peps/pep-0484/#forward-references. And in the end we start to support the typing module.

**Comment by carlsverre** [comment]
Any update on this?  Now that 3.5 has landed with the typing module it would be an awesome feature to have in Jedi.  @mikn are you working on this already?

**Comment by reinhrst** [comment]
I fully agree this would be a great addition (especially since much of my own code uses this annotation style).

Last weekend I spent a day trying to get some understanding on where and what needed to be done. It seems indeed that the first step, ignoring `typing` all together, should not take too much work. Have to say though that I didn't get much further than that, and will probably only be able to work on it again next weekend. Would appreciate to hear about any progress others are making, since it would be great not doing work double :).

**Comment by mikn** [comment]
I have not started any work yet, so it is up for grabs for whomever feels
inclined. :)

**Comment by davidhalter** [comment]
@reinhrst Since this issue is now 2.5 years old, I wouldn't be too afraid of people solving the same thing ;-)

**Comment by blueyed** [comment]
Do I understand this issue correctly, so that it would enhance the type hinting experience (https://jedi.readthedocs.org/en/latest/docs/features.html#type-hinting)?  Is that the main feature of this issue?

**Comment by davidhalter** [comment]
@blueyed Yes it is. However this issue would implement support for annotations instead of just docstrings. You can read all about the new "typing" module in Python here: https://www.python.org/dev/peps/pep-0484.

**Comment by nicolas33** [comment]
This would be a great feature. I widely use objects created dynamically (I'm developing a framework) and Jedi is currently inoperative on those objects. Using any other type hinting would be redundant with the annotations.
