### ISSUE TITLE
Crash on file not present on disk

### ISSUE THREAD

**Issue by mdedonno1337** [davidhalter/jedi#1703]
When I use the Hover command of nvim.coc on a function within a file that is not saved on disk, I have a hard crash a neovim.
The traceback indicate that the file can not be opened.

The solution could be to add a try/catch block arround this line https://github.com/davidhalter/jedi/blob/69750b9bf0c41c3a202a77621c14994f1f2dbcba/jedi/api/__init__.py#L140

as follows:

```
        if code is None:
            # TODO add a better warning than the traceback!
            try:
                with open(path, 'rb') as f:
                    code = f.read()
            except IOError:
                code = ''
```

Happy to make the PR if OK for you.
Thanks

**Comment by davidhalter** [comment]
> The traceback indicate that the file can not be opened.

This should be handled by the plugin. This behavior is correct.
