### ISSUE TITLE
no signature found for complete of method with contextmanager decorator

### ISSUE THREAD

**Issue by magro11** [davidhalter/jedi#1705]
Hello,

I tried to get a completion of a method (including its signature), that is decoreated by ```contextlib.contextmanager```.
The `jedi.Script.complete` method is able to find the correct method, however the signature (using `get_signatures()`
returns an empty list. I expected to get one signature with the arguments of the decorated method.

Here is an example:

```
code = """from contextlib import contextmanager

@contextmanager
def contextfunc(arg: str):
    print("start", arg)
    yield
    print("done", arg)

with contextfunc("foo"):  # this is line 9, col 15 is between letter n and c
    # do anything
    pass
"""

import jedi

script = jedi.Script(code=code, path="")
cmpls = script.complete(line = 9, column = 15)
print(cmpls)
cmp0 = cmpls[0]
print(cmp0.name)
print(cmp0.get_signatures())
```

The print out is:

```
[<Completion: contextfunc>]
contextfunc
[]  -> this is the output of get_signatures()
```

Is this desired behaviour? It would be great if the complete method would return the full signature `contextfunc(arg: str)`.

Thank you.

**Comment by davidhalter** [comment]
Version?

**Comment by magro11** [comment]
Oh, sorry. I missed that information:

I have the following system:
Win 10
Python 3.7.0 (the standard Python installation)
Jedi 0.17.2
Parso 0.8.0

Cheers
Marc

**Comment by davidhalter** [comment]
Fixed. Thanks for the report!
