### ISSUE TITLE
no signatures for `typing` module functions

### ISSUE THREAD

**Issue by pappasam** [davidhalter/jedi#1709]
Jedi: 0.17.2
Python: 3.8.6
OS: Ubuntu 20.04

Typing module functions return empty signatures, even when they do have a signature. See below for some examples:

```python
import jedi
import os

code = """from typing import cast
cast()
"""

script = jedi.Script(code=code, path="")
signatures = script.get_signatures(line=2, column=5)
print(signatures)

code2 = """from typing import TypeVar
TypeVar()
"""

script2 = jedi.Script(code=code2, path="")
signatures2 = script2.get_signatures(line=2, column=8)
print(signatures2)

code3 = """import os
os.path.join()
"""

script3 = jedi.Script(code=code3, path="")
signatures3 = script3.get_signatures(line=2, column=13)
print(signatures3)
```

First 2 print statements show an empty list. The 3rd print statement, for `os.path.join`, should print completed signatures.

```txt
[]
[]
[<Signature: index=0 join(path: _StrPath, *paths: _StrPath) -> Text>, <Signature: index=0 join(path: _BytesPath, *paths: _BytesPath) -> bytes>]
```

**Comment by davidhalter** [comment]
They finally improved the annotations for `typing`. Now I was finally able to remove some hacks :)

`overload` and `TypedDict` are not properly defined in typeshed and therefore don't have the correct signatures.

Please let me know if you find something that's not correct (other than that).
