### ISSUE TITLE
Compatibility with parso 0.8.1

### ISSUE THREAD

**Issue by bignose-debian** [davidhalter/jedi#1710]
Currently (version `0.17.2`), this package dependencies limit the `parso` library to `parso < 0.8.0`.

The [current available parso version](https://pypi.org/project/Pillow/#history) is 0.8.1.

**Comment by bignose-debian** [comment]
Please leave this issue open (as it describes an actual issue), to be closed when a new release of jedi resolves this.

**Comment by davidhalter** [comment]
This is not an actual issue. People can keep using 0.8.1. It's not an issue. These are independent projects. Nothing is security relevant and some Parso things are not used by Jedi, so I update it whenever I feel like it.

**Comment by bignose-debian** [comment]
> People can keep using 0.8.1.

Okay, good to know. That contradicts the [current PyPI ‘jedi’ package](https://pypi.org/project/jedi/) metadata:

```
Requires-Dist: parso (<0.8.0,>=0.7.0)
```

> These are independent projects.

That doesn't match the package metadata, which makes the Jedi package dependent on specific versions of Parso.

So, this issue is reporting that the PyPI package of Jedi, restricts Parso to a version lower than what is currently available from PyPI.

**Comment by davidhalter** [comment]
> That doesn't match the package metadata, which makes the Jedi package dependent on specific versions of Parso.

What I mean with that is that there is no reason to assume Jedi always supports the latest Parso. Jedi uses an older Parso version for good reasons.

If you don't want to deal with this, just use Parso 0.7, which is still perfectly fine.

**Comment by davidhalter** [comment]
0.18.0 was just released.
