### ISSUE TITLE
InternalError: The subprocess /mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/bin/python has crashed.

### ISSUE THREAD

**Issue by bensonlew** [davidhalter/jedi#1713]
929         volcano_pd
 930        volcano_pd.dropna(inplace=True)
 931        volcano_pd.columns = ['seq_id', 'log2fc', 'log10pvalue', 'significant', 'regulate']
 932        bool_ind = volcano_pd['log10pvalue'] > stat_cutoff
 933        volcano_pd.loc[bool_ind, 'log10pvalue'] = stat_cutoff
 934        volcano_pd_nosig = volcano_pd[volcano_pd['significant'] == 'no']
 935        if volcano_pd_nosig.shape[0] > 8000:
 936            volcano_pd_sig = volcano_pd[volcano_pd['significant'] == 'yes']
 937            volcano_pd_nosig = volcano_pd_nosig.sample(frac=0.5)
 938            if volcano_pd_nosig.shape[0] > 12000:
 939                volcano_pd_nosig = volcano_pd_nosig.sample(frac=0.7)
 940            if volcano_pd_nosig.shape[0] > 12000:
 941                volcano_pd_nosig = volcano_pd_nosig.sample(frac=0.7)
 942            volcano_pd = pd.concat([volcano_pd_sig, volcano_pd_nosig], axis=0)
 943        volca
 944        down_list = list()
 945        up_list = list()
 946        nosig_list = list()

in 929 complete  quickly    but in 943 it complete The following error and used 100% of cpu

``----> 1 comp2.complete()

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/api/completion.pyc in complete(self)
    170             return prefixed_completions
    171
--> 172         cached_name, completion_names = self._complete_python(leaf)
    173
    174         completions = list(filter_names(self._inference_state, completion_names,

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/api/completion.pyc in complete_python(self, leaf)
    311
    312                 if not kwargs_only:
--> 313                     completion_names += self._complete_global_scope()
    314                     completion_names += self._complete_inherited(is_function=False)
    315

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/api/completion.pyc in complete_global_scope(self)
    377         completion_names = []
    378         for filter in filters:
--> 379             completion_names += filter.values()
    380         return completion_names
    381

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/filters.pyc in values(self)
    239
    240     def values(self):
--> 241         return [n for filter in self._filters for n in filter.values()]
    242
    243     def __repr__(self):

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/filters.pyc in values(self)
     89         return self._convert_names(
     90             name
---> 91             for name_key in self._used_names
     92             for name in self._filter(
     93                 _get_definition_names(self._used_names, name_key),

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/filters.pyc in _convert_names(self, names)
     84
     85     def _convert_names(self, names):
---> 86         return [self.name_class(self.parent_context, name) for name in names]
     87
     88     def values(self):

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/filters.pyc in <genexpr>((name_key,))
     91             for name_key in self._used_names
     92             for name in self._filter(
---> 93                 _get_definition_names(self._used_names, name_key),
     94             )
     95         )

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/filters.pyc in _filter(self, names)
    118         names = super(ParserTreeFilter, self)._filter(names)
    119         names = [n for n in names if self._is_name_reachable(n)]
--> 120         return list(self._check_flows(names))
    121
    122     def _is_name_reachable(self, name):

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/filters.pyc in _check_flows(self, names)
    133                 value_scope=self._parser_scope,
    134                 node=name,
--> 135                 origin_scope=self._origin_scope
    136             )
    137             if check is not flow_analysis.UNREACHABLE:

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/flow_analysis                              .pyc in reachability_check(context, value_scope, node, origin_scope)
     81             origin_scope = origin_scope.parent
     82
---> 83     return _break_check(context, value_scope, first_flow_scope, node)
     84
     85

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/flow_analysis                                  .pyc in _break_check(context, value_scope, flow_scope, node)
     96             flow_node = flow_scope.get_corresponding_test_node(node)
     97             if flow_node is not None:
---> 98                 reachable = _check_if(context, flow_node)
     99     elif flow_scope.type in ('try_stmt', 'while_stmt'):
    100         return UNSURE

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/flow_analysis                                  .pyc in _check_if(context, node)
    116             return UNSURE
    117
--> 118         types = context.infer_node(node)
    119         values = set(x.py__bool__() for x in types)
    120         if len(values) == 1:

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/context.pyc in infer_node(self, node)
    220     def infer_node(self, node):
    221         from jedi.inference.syntax_tree import infer_node
--> 222         return infer_node(self, node)
    223
    224     def create_value(self, node):

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/syntax_tree.p                                yc in infer_node(context, element)
    155             return _infer_node(context, element)
    156         else:
--> 157             return _infer_node_if_inferred(context, element)
    158
    159

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/syntax_tree.p                                  yc in _infer_node_if_inferred(context, element)
    168         if predefined_if_name_dict is not None:
    169             return _infer_node(context, element)
--> 170     return _infer_node_cached(context, element)
    171
    172

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/cache.pyc inwrapper(obj, *args, **kwargs)
     42                 if default is not _NO_DEFAULT:
     43                     memo[key] = default
---> 44                 rv = function(obj, *args, **kwargs)
     45                 memo[key] = rv
     46                 return rv

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/syntax_tree.p                                  yc in _infer_node_cached(context, element)
    173 @inference_state_method_cache(default=NO_VALUES)
    174 def _infer_node_cached(context, element):
--> 175     return _infer_node(context, element)
    176
    177

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/debug.pyc in wrapper(*args, **kwargs)
     80     def wrapper(*args, **kwargs):
     81         with increase_indent_cm():
---> 82             return func(*args, **kwargs)
     83     return wrapper
     84

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/syntax_tree.pyc in wrapper(context, *args, **kwargs)
     81         except KeyError:
     82             inference_state.inferred_element_counts[n] = 1
---> 83         return func(context, *args, **kwargs)
     84
     85     return wrapper

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/syntax_tree.pyc in _infer_node(context, element)
    255         return context.infer_node(element.children[2])
    256     else:
--> 257         return infer_or_test(context, element)
    258
    259

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/syntax_tree.pyc in infer_or_test(context, or_test)
    485         else:
    486             types = _infer_comparison(context, types, operator,
--> 487                                       context.infer_node(right))
    488     debug.dbg('infer_or_test types %s', types)
    489     return types

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/context.pyc in infer_node(self, node)
    220     def infer_node(self, node):
    221         from jedi.inference.syntax_tree import infer_node
--> 222         return infer_node(self, node)
    223
    224     def create_value(self, node):

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/syntax_tree.pyc in infer_node(context, element)
    155             return _infer_node(context, element)
    156         else:
--> 157             return _infer_node_if_inferred(context, element)
    158
    159

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/syntax_tree.pyc in _infer_node_if_inferred(context, element)
    168         if predefined_if_name_dict is not None:
    169             return _infer_node(context, element)
--> 170     return _infer_node_cached(context, element)
    171
    172

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/cache.pyc in  wrapper(obj, *args, **kwargs)
     42                 if default is not _NO_DEFAULT:
     43                     memo[key] = default
---> 44                 rv = function(obj, *args, **kwargs)
     45                 memo[key] = rv
     46                 return rv

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/syntax_tree.pyc in _infer_node_cached(context, element)
    173 @inference_state_method_cache(default=NO_VALUES)
    174 def _infer_node_cached(context, element):
--> 175     return _infer_node(context, element)
    176
    177

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/debug.pyc in wrapper(*a                                                            rgs, **kwargs)
     80     def wrapper(*args, **kwargs):
     81         with increase_indent_cm():
---> 82             return func(*args, **kwargs)
     83     return wrapper
     84

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/syntax_tree.pyc in wrapper(context, *args, **kwargs)
     81         except KeyError:
     82             inference_state.inferred_element_counts[n] = 1
---> 83         return func(context, *args, **kwargs)
     84
     85     return wrapper

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/syntax_tree.pyc in _infer_node(context, element)
    183     typ = element.type
    184     if typ in ('name', 'number', 'string', 'atom', 'strings', 'keyword', 'fstring'):
--> 185         return infer_atom(context, element)
    186     elif typ == 'lambdef':
    187         return ValueSet([FunctionValue.from_context(context, element)])

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/syntax_tree.pyc in infer_atom(context, atom)
    323
    324     elif isinstance(atom, tree.Literal):
--> 325         string = state.compiled_subprocess.safe_literal_eval(atom.value)
    326         return ValueSet([compiled.create_simple_object(state, string)])
    327     elif atom.type == 'strings':

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/compiled/subprocess/__init__.pyc in wrapper(*args, **kwargs)
    120                 func,
    121                 args=args,
--> 122                 kwargs=kwargs,
    123             )
    124             # IMO it should be possible to create a hook in pickle.load to

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/compiled/subprocess/__init__.pyc in run(self, inference_state, function, args, kwargs)
    219
    220         assert callable(function)
--> 221         return self._send(id(inference_state), function, args, kwargs)
    222
    223     def get_sys_path(self):

/mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/lib/python2.7/site-packages/jedi/inference/compiled/subprocess/__init__.pyc in _send(self, inference_state_id, function, args, kwargs)
    230     def _send(self, inference_state_id, function, args=(), kwargs={}):
    231         if self.is_crashed:
--> 232             raise InternalError("The subprocess %s has crashed." % self._executable)
    233
    234         if not is_py3:

InternalError: The subprocess /mnt/ilustre/users/sanger-dev/sg-users/liubinxu/work/spacemacs/miniconda2/bin/python has crashed.``

**Comment by davidhalter** [comment]
Since this is Python 2 and the next release does not support Python 2 anymore, I'm going to close.

However note that this is likely a bug in an underlying library. This is why I use a subprocess in the first place, so that there is an exception and not a crash of the process. Typically this is a segmentation fault in an extension library.
