### ISSUE TITLE
Quick thanks for your efforts! 🥇

### ISSUE THREAD

**Issue by carltongibson** [davidhalter/jedi#1718]
Not an issue, but... 

Just want to say thank you for your work on Jedi, and everything that went into the recent release. 

Please do (also) make sure you take an end-of-year break too 😀

Thanks so much!

**Comment by davidhalter** [comment]
Thanks for reaching out! Not sure if I will get an end-of-year break. But I will try :).

I would also like to say that I have been working with Django since like 12 years. It's what brought me to Python originally. Thank you continuing to maintain Django!
