### ISSUE TITLE
Thonny - Autocomplete error: __init__() takes from 1 to 2 positional arguments but 5 were given

### ISSUE THREAD

**Issue by saavedra29** [davidhalter/jedi#1724]
Operation system: Linux
Python version: 3.8.5
Thonny version: 3.2.7
Jedi version : 0.18.0

When I'm trying to autocomplete on Thonny i get the exact error that i describe on the title. I checked several older versions of Jedi and this doesn't happen.

**Comment by davidhalter** [comment]
This is definitely an issue of your Jedi implementation. Please report it there.
