### ISSUE TITLE
Add autocompltion to dict proxy

### ISSUE THREAD

**Issue by thebestnom** [davidhalter/jedi#1725]
I saw you added a way to auto complete attr proxy (https://github.com/davidhalter/jedi/issues/997)
Should we add way to add something similar for dict proxy(I can write PR if axcepted)

Like when
``` python
class Test:
    def __getattr__(self, name):
        #...
        return proxied_dict[name]
```

**Comment by davidhalter** [comment]
I guess you mean `__getitem__`, right?

**Comment by thebestnom** [comment]
Nope, I did meant `__getatte__`, but it should work for both I guess

**Comment by davidhalter** [comment]
Oh ok now I understand. If you write it with enough tests, I'm happy to accept such an implementation.

**Comment by thebestnom** [comment]
Ok, Ill try to do it later this week, thanks for the comment 😄

**Comment by davidhalter** [comment]
Since nothing has happened, I'm going to close. But I'm still happy to discuss a PR :)
