### ISSUE TITLE
write to docs about possible text prefixes

### ISSUE THREAD

**Issue by Alexey-T** [davidhalter/jedi#1729]
CudaText plugin shows N prefixes for different things

- statement
- function
- module

can you write to docs about ALL possible prefixes? this will help users to find all icon files for all cases.
@olehl

**Comment by davidhalter** [comment]
I don't understand at all what you want here. Please be more specific.

**Comment by Alexey-T** [comment]
here I see several prefixes from Jedi: function, param, class, keyword.
![Screenshot from 2021-01-10 12-57-27](https://user-images.githubusercontent.com/4154978/104119841-80938d80-5343-11eb-8248-582a0e3b81f7.png)

**Comment by OlehL** [comment]
@Alexey-T see link below:
https://jedi.readthedocs.io/en/latest/docs/api-classes.html#jedi.api.classes.BaseName.type

> Valid values for type are `module`, `class`, `instance`, `function`, `param`, `path`, `keyword`, `property` and `statement`.
