### ISSUE TITLE
Jedi 0.17.0 jedi.find_system_environments() fails on Linux ARM Raspberry Pi

### ISSUE THREAD

**Issue by Alexey-T** [davidhalter/jedi#1730]
I use old hardware on Raspberry Pi (2 or 3).
SUBJ can find only one py environment- Py 2.7. But I have here also Py 3.4. 

by choosing the /usr/bin/python3.4 file I configured the env. (I use CudaText plugin, i called plugin command to choose env, browsed for file /usr/bin/python3.4.)
so Py34 environment is working ok.
@OlehL

**Comment by Alexey-T** [comment]
here is listing of /usr/lib:
[log.txt](https://github.com/davidhalter/jedi/files/5792782/log.txt)

```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux
```

**Comment by Alexey-T** [comment]
@OlehL

**Comment by davidhalter** [comment]
Python3.4 support has been dropped in 0.17.0. That's probably the issue. Python 3.5 has been dropped in 0.18.0.
