### ISSUE TITLE
Idea to suggest additional ';' or '("

### ISSUE THREAD

**Issue by Alexey-T** [davidhalter/jedi#1733]
CudaText plugin works. it will be better if Jedi gives additional info for 'auto completion' items:
next char to insert after the Id.
For ex, 

1)

    import cu

it can suggest char ';' to insert "import cups;" with ';'.

2)

    os.path.ex

it can suggest char '(" to insert "os.path.exists(" with brace.
@olehl

**Comment by davidhalter** [comment]
I won't implement it. So if you do it I might merge it and the API would probably look like this:`.complete(..., include_operators=False)`.

**Comment by OlehL** [comment]
First case in my opinion is not a good idea. See https://www.flake8rules.com/rules/E703.html

**Comment by Alexey-T** [comment]
Okay.... also we can 'detect' that char by kind of completion item.

**Comment by davidhalter** [comment]
For the latter I would recommend adding `add_bracket_after_function`.

I also did not understand your issue correctly, I thought you meant operator completion in general. Only completion for `;` is something that won't get merged here.
