### ISSUE TITLE
Deferred error whenever a character is typed

### ISSUE THREAD

**Issue by gossagomez** [davidhalter/jedi#1735]
Hi,

Here is the is the traceback: 

`ERROR:epc:TypeError('__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given')`

It is always the same error. Also, autocompletion only work when using ` jedi:start-dedicated-server`.

Thanks

**Comment by davidhalter** [comment]
Please post this to your emacs? plugin's issue tracker. This is very likely to be an issue in there not a Jedi issue. You can probably use Jedi 0.17.2 for the time being, because they are probably not compatible with latest Jedi.
