### ISSUE TITLE
Calling `ParamName.infer_default` raises AttributeError.

### ISSUE THREAD

**Issue by jonathanslenders** [davidhalter/jedi#1738]
```python
  File "/home/jonathan/git/ptpython/ptpython/signatures.py", line 96, in from_jedi_signature
    default=p.infer_default(),
  File "/home/jonathan/.virtualenvs/lm/lib/python3.8/site-packages/jedi/api/classes.py", line 864, in infer_default
    return _values_to_definitions(self._name.infer_default())

Exception 'SignatureParamName' object has no attribute 'infer_default'
```

In the above stack, ``p`` is a ``jedi.api.classes.ParamName`` obtained by iterating through the ``params`` attribute of a ``jedi.api.classes.Signature`` instance.

edit: also worth noting that this is in a REPL, using ``jedi.Interpreter``. 

(Happens on latest master commit of Jedi, as well as on v0.18.0.)

**Comment by davidhalter** [comment]
> edit: also worth noting that this is in a REPL, using jedi.Interpreter.

Well, once I read @jonathanslenders, it's that I expected. :) Still thanks for clarifying.

**Comment by davidhalter** [comment]
Will be fixed in the release I'm doing the next few days. Thanks for reporting!
