### ISSUE TITLE
Type Hint Jedi

### ISSUE THREAD

**Issue by ThatXliner** [davidhalter/jedi#1743]
[MyPy][mp] is screaming at me when I am writing Python code using Jedi. Can you please add [type hints](https://www.python.org/dev/peps/pep-0484/)?
[mp]: https://github.com/python/mypy

**Comment by davidhalter** [comment]
There are some. I'll leave it up to @PeterJCLaw to add them wherever he deems them necessary. I will definitely not type the whole code base, it's just too much work.

**Comment by ThatXliner** [comment]
> I will definitely not type the whole code base, it's just too much work.


I probably can

**Comment by davidhalter** [comment]
I also don't prefer that.
