### ISSUE TITLE
unhandled operator ':' in PythonNode(subscriptlist, ...

### ISSUE THREAD

**Issue by Carreau** [davidhalter/jedi#1748]
The traceback is pretty long so is here:

https://gist.github.com/Carreau/9bea1682d339cec801b08d7d3fc3af0e

it ends up with 

```
/jedi/inference/syntax_tree.py", line 229, in _infer_node
    raise AssertionError("unhandled operator %s in %s " % (repr(element.value), origin))
AssertionError: unhandled operator ':' in PythonNode(subscriptlist, [<Operator: :>, <Operator: ,>, PythonNode(subscript, [<Operator: :>, PythonNode(factor, [<Operator: ->, <Number: 1>])])])
```
in 
```python
    elif typ == 'operator':
        # Must be an ellipsis, other operators are not inferred.
        if element.value != '...':
            origin = element.parent
            raise AssertionError("unhandled operator %s in %s " % (repr(element.value), origin))
        return ValueSet([compiled.builtin_from_name(inference_state, 'Ellipsis')])

```

Here is a MRP:

```
$ cat jd.py
data = """from scipy import linalg

SAb = linalg.clarkson_woodruff_transform(Ab, sketch_n_rows)
SA = SAb[:, :-1]
"""

from jedi import Interpreter

i = Interpreter(data, [{}])
i.infer(4, 0)
```

Which is a subset of the last example of https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.clarkson_woodruff_transform.html, (Yes I am trying to infer all the types of all the token in all the examples of scipy...)

Jedi master: ee30843f2231c3c51f61961cda1d2d6fad185f93 (Feb 1st) , parso  master: 93206f6eba3fe29a200c328c11535e58c56e9635 (Jan 26) , scipy 1.5.0 

Hope this error make sens to you; I guess it may be a parsing error as  `:` likely should not be on operator ? 
Let me know what I can do to help narrow that down on fix it.

**Comment by davidhalter** [comment]
No parsing error. A plain `:` is probably just not handled. Thanks for the report!

**Comment by RuRo** [comment]
I am having a similar (?) issue with the following snippet:
```python
data = '''def foo():
    """What?

    This. Al
    """
    pass
'''

from jedi.api import Script

i = Script(data)
i.complete(line=4, column=10)
```
with
```
  File "/usr/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 229, in _infer_node
    raise AssertionError("unhandled operator %s in %s " % (repr(element.value), origin))
AssertionError: unhandled operator '.' in <PythonErrorNode: This.@3,0> 
```

**Comment by Neburski** [comment]
> I am having a similar (?) issue with the following snippet:
> 
> ```python
> data = '''def foo():
>     """What?
> 
>     This. Al
>     """
>     pass
> '''
> 
> from jedi.api import Script
> 
> i = Script(data)
> i.complete(line=4, column=10)
> ```
> 
> with
> 
> ```
>   File "/usr/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 229, in _infer_node
>     raise AssertionError("unhandled operator %s in %s " % (repr(element.value), origin))
> AssertionError: unhandled operator '.' in <PythonErrorNode: This.@3,0> 
> ```

I have the same issue. Using the provided example, I can reproduce the issue. When using jedi in combination with deoplete-jedi in neovim, the issue appears to only be triggered when working on docstrings.

**Comment by davidhalter** [comment]
Thanks for reporting this. These were actually two separate, but should be fixed on a branch that will be released in the next few days (will be part of Jedi 0.18.1).
