### ISSUE TITLE
Pydantic Plugin

### ISSUE THREAD

**Issue by henighan** [davidhalter/jedi#1749]
First off thanks for making jedi, it's been boosting my productivity for years!

I'm considering making a plugin for [Pydantic](https://github.com/samuelcolvin/pydantic). It has an API very similar to `dataclasses`, which means `get_signatures` does not work out-of-the-box. However, since jedi already supports dataclasses, perhaps I would only need to figure out how to reuse [`DataclassWrapper`](https://github.com/davidhalter/jedi/blob/ee30843f2231c3c51f61961cda1d2d6fad185f93/jedi/plugins/stdlib.py#L602) for any object inheriting from `pydantic.BaseModel`?. You've pointed others like me to `get_metaclass_filters` (see [here](https://github.com/davidhalter/jedi/issues/1401#issuecomment-532417710)). But I haven't quite figure out how to get it to work. Is `get_metaclass_signatures` the more relevant method in this case?

Any pointers would be appreciated. I'm perfectly happy to keep this in my own fork. I understand that you may only be interested in supporting a limited number of plugins, and that parts of the standard library (eg dataclasses) take precedent.

**Comment by davidhalter** [comment]
Hi @henighan Thanks for trying to help. I generally won't accept third party plugins. The reason for this is mostly maintenance. In general after a few years I have to maintain that code.

So, sorry for not helping with this, but it's a choice I'm making to ease maintenance of the code in 5-10 years.

**Comment by spookylukey** [comment]
As a workaround if you are using Pydantic `dataclass`, I've found this to be quite effective (but not perfect):

```py
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    from dataclasses import dataclass  # noqa:F811


@dataclass
class Foo:
    bar: int
    # etc.
```

Since Jedi appears to support [TYPE_CHECKING from PEP-0484](https://www.python.org/dev/peps/pep-0484/#runtime-or-type-checking), this makes `Foo` appear to Jedi as a stdlib dataclass instead of a Pydantic dataclass.

**Comment by Morikko** [comment]
https://github.com/davidhalter/jedi/pull/2049 should add support for Pydantic completion. Feedback are welcome.
