### ISSUE TITLE
Completion types for class instance return statement

### ISSUE THREAD

**Issue by krassowski** [davidhalter/jedi#1752]
While class instance type is correctly recognized by `Script.infer()`:

```python
from jedi import Script
test_cases = 'keyword, test_CC, test_xx, test_ff, test_DD.test_yy'

source = f'''
import keyword

class test_CC:
    pass

class test_DD:
    @property
    def test_yy():
        pass

test_xx = test_DD()

def test_ff():
    pass

for variable in [{test_cases}]:
    variable'''
script = Script(source)
# note: test_DD.test_yy is is "property" so its line is in another file
defs = sorted(script.infer(), key=lambda d: d.line)
[d.type for d in defs]
```

```
['module', 'class', 'instance', 'function', 'property']
```

It does not work correctly for `Script.complete()`:

```python
def only(x):
    assert len(x) == 1
    return x[0]

completion_defs = [
    only(Script(source + '\n\n' + case[:-1]).complete())
    for case in test_cases.split(', ')
]
[d.type for d in completion_defs]
```

```
['module', 'class', 'statement', 'function', 'property']
```

As demonstrated above other types (although the test is not exhaustive) are recognized correctly by both. Is this a known limitation of the completion functionality, or a bug that needs fixing?

**Comment by davidhalter** [comment]
You should compare `complete` with `goto` and not `infer()`. `infer()` will never return the statement type, but goto and complete will, mostly for performance reasons. If you need to infer the exact type you have to use `[d for name in script.complete() for d in name.infer()]`.

So this is definitely intentional.
