### ISSUE TITLE
Suppport for python 3.10 alpha 6

### ISSUE THREAD

**Issue by leahein** [davidhalter/jedi#1756]
It doesn't look like jedi supports the latest features of python `3.10.0a6`. Specifically, support for pattern matching syntax.

![image](https://user-images.githubusercontent.com/15165051/111350197-3e930a80-8658-11eb-90ce-1d0958d2f547.png)

I understand this is a [fairly recent python release](https://github.com/python/cpython/releases/tag/v3.10.0a6), but couldn't seem to find anything in development yet working to support this, so I wanted to raise this as a feature that will need to be supported.

**Comment by leahein** [comment]
Related to #1732

**Comment by davidhalter** [comment]
Won't happen for a long time. The blocker is actually https://github.com/davidhalter/parso/issues/138

3.10 might not be supported when it's released. It might take a long time for this to arrive. I currently don't have the motivation to put in a few days of work for a Python feature that I actually dislike. I'm sure it will eventually arrive, but it will take its time.

**Comment by Real-Gecko** [comment]
https://github.com/davidhalter/parso/issues/138 is almost two years old and Python 3.11 is on the horizon with planned release in October 22. Any progress?
