### ISSUE TITLE
Package installation fails in some cases

### ISSUE THREAD

**Issue by wlievens** [davidhalter/jedi#1762]
Jedi is a transitive dependency of a project of mine, and I manage dependencies through **poetry**.

When installing in a default virtual environment location, jedi installs just fine.
However, when I override the virtual environment location to a specific path, installation of Jedi fails.

Though this may sound like a poetry/pip/venv issue, I've only seen this happen with Jedi so that's why I reporting it here.

I get this error (with some paths censored):

```
  • Installing jedi (0.18.0)

  EnvCommandError

  Command venv\...\Scripts\pip.exe install --no-deps file:///C:/Users/USERNAME/AppData/Local/pypoetry/Cache/artifacts/cf/3e/f1/d313abb555f08e890ded67441fc7072b96ff089e87715b5d8d1b094696/jedi-0.18.0-py2.py3-none-any.whl errored with the following return code 1, and output:
  Processing c:\users\USERNAME\appdata\local\pypoetry\cache\artifacts\cf\3e\f1\d313abb555f08e890ded67441fc7072b96ff089e87715b5d8d1b094696\jedi-0.18.0-py2.py3-none-any.whl
  Installing collected packages: jedi
  ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\...\\venv\\...\\Lib\\site-packages\\jedi\\third_party\\typeshed\\third_party\\2and3\\requests\\packages\\urllib3\\packages\\ssl_match_hostname\\_implementation.pyi'
```

Any idea?

**Comment by davidhalter** [comment]
This part looks extremely weird to me: `C:\\...\\venv\\...\\Lib\\`. I would probably report it in poetry.

IMO the setup.py for Jedi is extremly simple, does nothing magical. I'm closing, but feel free to keep the discussion going.

**Comment by wlievens** [comment]
That part is the censored path, sorry I didn't make that any more clear.

If the jedi setup does nothing out of the ordinary, I suppose you are correct. I ended up removing the dependency that caused jedi to be included so for me it is resolved.
