### ISSUE TITLE
in 0.18version the compele return no params in type of function,but in0.17.2 it has params

### ISSUE THREAD

**Issue by wanpengxyzz** [davidhalter/jedi#1766]

**Comment by davidhalter** [comment]
Please provide a proper reproduction. Closing until such information is given.

**Comment by wanpengxyzz** [comment]
In version 0.18
![image](https://user-images.githubusercontent.com/1539435/113957776-74d83a00-9852-11eb-8378-a50a2cef87b8.png)

In version 0.17.2
![image](https://user-images.githubusercontent.com/1539435/113957927-c1bc1080-9852-11eb-8346-db877129b543.png)

code:
import jedi
code = '''from jedi import Script
x=Script()
x. 
'''
script = jedi.Script(code,path="test.py") 
completes = script.complete(3,2)
