### ISSUE TITLE
Rename in list comprehensions and generators does not work as expected

### ISSUE THREAD

**Issue by karthiknadig** [davidhalter/jedi#1767]
```python
x = (f for f in [1,2,3,4,5] if f%2==0)
```

Rename 'f' to 'y'.

Expected:
```
x = (y for y in [1,2,3,4,5] if y%2==0)
```

Actual:
```
x = (y for f in [1,2,3,4,5] if f%2==0)
```

**Comment by PeterJCLaw** [comment]
Duplicate of #1764 I think?

**Comment by karthiknadig** [comment]
It is the same. I am not sure if there is a platform difference, but on windows the actual looks slightly different. Only the symbol that I highlight gets changed and no other symbol is updated.

In #1764 it changes one of them but not all.
