### ISSUE TITLE
Rename symbol not working with attributes in class operator implementation

### ISSUE THREAD

**Issue by DoS007** [davidhalter/jedi#1769]
![T9n1mhg028](https://user-images.githubusercontent.com/11618958/114314773-5b5a1b00-9afc-11eb-9dff-35c603bffb54.gif)

See https://github.com/microsoft/vscode-python/issues/15922 

Copied content (if the other issue is changed): 

## Environment data

-   VS Code version: 1.55.1
-   Extension version (available under the Extensions sidebar): v2020.10.332292344
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): -
-   Relevant/affected Python packages and their versions: -
-   Relevant/affected Python-related VS Code extensions and their versions: -
-   Value of the `python.languageServer` setting: Jedi

## Expected behaviour

```
class MyClass:
    def __init__(self, my_attribute):
        self.my_attribute = my_attribute
    
    def __eq__(self, other):
        return self.my_attribute == other.my_attribute
```

Now rename the instance attribute: [`Symbol Rename`](https://code.visualstudio.com/docs/editor/refactoring#_rename-symbol) (shortcut F2) on `my_attribute` (in `self.my_attribute` in line 3) and rename it e.g. to `my_attribute2`. You'll see that `other.my_attribute` won't be changed accordingly.

This also happens when adding type hints. The above code renaming should just work (because there is enough information for the refactoring tool to act correctly). But I even tried type hints (see [PEP 484](https://www.python.org/dev/peps/pep-0484/ )). Because of class name usage in definition of the class itself you have to use [Forward References](https://www.python.org/dev/peps/pep-0484/#forward-references). 

<pre><code>class MyClass:
    def __init__(self, my_attribute):
        self.my_attribute = my_attribute
    
    def __eq__(self, other<b>: "MyClass"</b>):
        return self.my_attribute == other.my_attribute</code></pre>

or instead of Forward References using something of the future [PEP 563](https://www.python.org/dev/peps/pep-0563/):

<pre><code>from __future__ import annotations 

class MyClass:
    def __init__(self, my_attribute):
        self.my_attribute = my_attribute
    
    def __eq__(self, other<b>: MyClass</b>):
        return self.my_attribute == other.my_attribute</code></pre>

But even with those type hints `Symbol Rename` does not work correctly.

It should work correctly.

## Actual behaviour

It does not work correctly.

## Steps to reproduce:
See above

![T9n1mhg028](https://user-images.githubusercontent.com/11618958/114314773-5b5a1b00-9afc-11eb-9dff-35c603bffb54.gif)

Edit: This seems to be a Jedi specific problem. (Microsoft language server doesn't has this problem)

Edit 2: Can someone maybe check, if the problem also exists with JediLSP? Couldn't install it yet. Maybe the problem is on the python extensions side for jedi?

_____

Edit 3: Installed now vscode and tested jedilsp and pylance (was using vscodium before but that had problems with both). On jedilsp the version with the type hints works correctly (which jedi didn't, so it was more of an extension problem).

**But: Still: In the version without type hints the renaming does not happen.** I installed pylance and it recognized it and renamed it. When using pycharm, it asks about that renaming case and per default renames then as well.

**Comment by davidhalter** [comment]
> Installed now vscode and tested jedilsp and pylance (was using vscodium before but that had problems with both). On jedilsp the version with the type hints works correctly (which jedi didn't, so it was more of an extension problem).

IMO everything works as designed then. It should work with type hints and shouldn't without.

> But: Still: In the version without type hints the renaming does not happen. I installed pylance and it recognized it and renamed it. When using pycharm, it asks about that renaming case and per default renames then as well.

This is something that's simply not fixable. How would Jedi know that `other` is a `MyClass`? This is simply a heuristic. I know that we could theoretically assume this, but I'm not sure that's a great idea. I will definitely keep it in mind for the Rust version that I'm writing, but this will not happen in Jedi. Sorry. There are a lot of cases where Python's dynamic nature is kind of a problem. And I chose to not use heuristics for all of these (because it makes Jedi also slower).

**Comment by DoS007** [comment]
> Thanks for writing the detailed report though! 
You're welcome. Thank you for devloping such a great tool.

> This is something that's simply not fixable. How would Jedi know that `other` is a `MyClass`? This is simply a heuristic. I know that we could theoretically assume this, but I'm not sure that's a great idea. I will definitely keep it in mind for the Rust version that I'm writing, but this will not happen in Jedi. Sorry. There are a lot of cases where Python's dynamic nature is kind of a problem. And I chose to not use heuristics for all of these (because it makes Jedi also slower).

I understand. Would it be possible to handle this like pycharm does? Inquiring the user on such a case, to let him/her choose what to do or do things like LSP not support such inquiring?

Greets DoS

**Comment by davidhalter** [comment]
> I understand. Would it be possible to handle this like pycharm does? Inquiring the user on such a case, to let him/her choose what to do or do things like LSP not support such inquiring?

AFAIK the LSP protocol does not support this (I have read it quite thoroughly). IMO that's the correct approach with such names. However it's still unlikely that Jedi will support this, because the Jedi's API is probably not made for this. However I will keep it in mind for the next autocompletion project that I'm doing :).

**Comment by DoS007** [comment]
@davidhalter Thank you.

Just to add: I appreciate your work. People like you make the world a better place.

Greets DoS007

**Comment by DoS007** [comment]
@davidhalter As an update: "Code Actions" form newer Language Server Protocol Version could allow the interactive behaviour?

This is also what pycharm used in my testing, which seems as the way to go if it isn't clear like in shown case above.

**Comment by davidhalter** [comment]
Could you point me to the change you mean in the LSP?

**Comment by davidhalter** [comment]
> Illustrating Example-Code generated with Claude, hopefully it is correctly showing the use:

Why would you ever send me this? Please don't ever send maintainers AI garbage. This is just almost never worth anything.

> ShowMessageRequest:

I don't understand what this means immediately and how I would use it. It would be interesting if you could show me how other LSP servers/clients use this and how we would typically use this as a concept. It would also be interesting to know if this is an intended workflow from the side of LSP (i.e. what is the history of this command). You avoided actually doing any of the important and interesting work. I know that LSP is adding new functionality and I'm even subscribed the official repo. I'm pretty sure I have heard bout ShowMessageRequest before, but I don't know the details. And that's where the work and all the interesting details lie.

And please don't ever send anyone AI garbage that you haven't tested. It's just so utterly worthless and useless and it triggers the hell out of me.

**Comment by DoS007** [comment]
@davidhalter 
> Why would you ever send me this? Please don't ever send maintainers AI garbage. This is just almost never worth anything.

> And please don't ever send anyone AI garbage that you haven't tested. It's just so utterly worthless and useless and it triggers the hell out of me.

Ok, sorry. Thanks for the advice. I'm not as advanced, so thanks for the feedback. So in your experience AI generated code is not good in most cases (even with the best AIs)?

> > ShowMessageRequest:
> 
> I don't understand what this means immediately and how I would use it. It would be interesting if you could show me how other LSP servers/clients use this and how we would typically use this as a concept. It would also be interesting to know if this is an intended workflow from the side of LSP (i.e. what is the history of this command). You avoided actually doing any of the important and interesting work. I know that LSP is adding new functionality and I'm even subscribed the official repo. I'm pretty sure I have heard bout ShowMessageRequest before, but I don't know the details. And that's where the work and all the interesting details lie.

Ah, ok. Like I said, I'm not as adavanced in this topic. I was happy that i found that api when i searched and thought the knowledge about that this API part might be the solution for the problem would be already helpful in some way.

**Comment by davidhalter** [comment]
> So in your experience AI generated code is not good in most cases (even with the best AIs)?

AI generated code can be fine. But only if you actually understand what it's doing and if you have tested it. In my opinion if you are like you said "I'm not as advanced" I would heavily advice against using an AI. AIs in my opinion are either for people that do not know how to code and just try to get something running or for people that have 10 years+ of experience in the industry that understand software extremely well. The problem with AI is that it's really just extremely good at looking like something sophisticated, while being miles away from understanding when it actually doesn't know and cannot answer. Experienced engineers have a good feeling about what they don't know and what they have to look up.

So I would advise you to just throw your AI into the garbage and try to understand the language/libraries you are using really really well and then after a few years you can start using it again (or not, because you don't really need it). I personally feel like AI needs at least one more evolution step until it's actually practical for people with good but limited knowledge.
