### ISSUE TITLE
`Script.help` returns `Name` of class instead of `Name` of `__init__`

### ISSUE THREAD

**Issue by E1k3** [davidhalter/jedi#1773]
`Script.help` finds the class, but not the `__init__` function.
Because of this, calling `help` on a class instantiation or on its opening bracket only makes the class docstring available, but not the `__init__` docstring.

This basically forces devs to write the `__init__` documentation in the class docstring if they want working help windows when instantiating objects of their class.

Reproducing example:
```
from jedi import Script

s = Script(code='''
class A:
    """Class docstring"""

    def __init__(self, param):
        """Init docstring
        param: ..."""
        self.param = param


A
A()
A(
''')
for h in s.help(11, 0):
    print(h.docstring())
print("---")
for h in s.help(12, 0):
    print(h.docstring())
print("---")
for h in s.help(13, 1):
    print(h.docstring())

```
Prints "Class docstring" for all lines, but I would expect "Init docstring" at least for the last line and maybe both docstrings in the second to last line.

**Comment by davidhalter** [comment]
> This basically forces devs to write the __init__ documentation in the class docstring if they want working help windows when instantiating objects of their class.

I think it's a weird concept to have both an __init__ and a class docstring. Jedi works fine if you have either, but ignores the `__init__` one if you have both.

Do you think it necessary to return both?

**Comment by E1k3** [comment]
Personally I don't think it is strictly necessary, but PEP 257 suggests they both have different purposes and are not interchangeable: https://stackoverflow.com/questions/54189661/docstring-in-class-or-init-constructor/54189717#54189717

**Comment by davidhalter** [comment]
> The docstring for a class should summarize its behavior and list the public methods and instance variables.

This is something that I have never seen in any Python code.

However fair enough. If you want this change, feel free to change it and I will merge it if it's well tested. Otherwise I will probably close. I'm not sure if a change is needed on `inference/value/klass.py`'s (where `py__doc__` would need to be implemented/overwritten) or if a change is needed on `inference/names.py`.

**Comment by davidhalter** [comment]
Closing, because I won't be changing this. But I'm happy to receive PRs that change this, as long as it's well tested.
