### ISSUE TITLE
SyntaxError non-default argument follows default argument false negative

### ISSUE THREAD

**Issue by mzjp2** [davidhalter/jedi#1776]
Hey folks,

I'm on Jedi 0.18.0 and using VSCode specifically. I just noticed that Jedi is flagging the following function signature as a:

```
SyntaxError: non-default argument follows default argument
```

signature:

```python
def f(*args, blah):
    pass
```

**Comment by davidhalter** [comment]
This should be fixed with parso 0.8.2. Upgrade and retry :)
