### ISSUE TITLE
Integrate Black into CI

### ISSUE THREAD

**Issue by bbugyi200** [davidhalter/jedi#1785]
While working on https://github.com/davidhalter/jedi/pull/1784, I spent too much time reformatting my code to make it look prettier (e.g. by wrapping long lines). Would there be any interest in integrating [black](https://github.com/psf/black) into jedi's CI process? This is quickly becoming the standard (for good reason IMO). We would, ofcourse, have to blacken the codebase first.

**Comment by davidhalter** [comment]
No. I don't want to reformat everything for now. This does not mean this is a no forever, it's just for now I don't want it.

BTW: I also think that code styles is something devs obsess over and it shouldn't be that important.

**Comment by bbugyi200** [comment]
> BTW: I also think that code styles is something devs obsess over and it shouldn't be that important.

@davidhalter I 1000% agree. That's why I use black, so I never have to think about code styling.
