### ISSUE TITLE
get_signature() for functools.wraps()-decorated function contains parameter list of undecorated function

### ISSUE THREAD

**Issue by smheidrich** [davidhalter/jedi#1791]
Consider the following minimal reproducible example:

```python
from functools import wraps

def f(x: int, y: float):
  "docstring of f"
  pass

@wraps(f)
def g(*args, **kwargs):
  f(*args, **kwargs)

g()
```

We try to obtain and print the signature for the call to `g()` at the end via `get_signature()`:

```python
from jedi import Script

with open("example.py") as f:
  scr = Script(f.read())

sigs = scr.get_signatures(11, 2)

for sig in sigs:
  print(sig.to_string())
```

This yields `f(*args, **kwargs)`. So the function's name was correctly obtained from the wrapped function (`f` instead of `g`), but the parameter list is that of `g`. In my opinion, it would be better if the parameter list was also taken from the decorated function, as this is the behavior of e.g. Python's own `inspect.signature()` (which yields `<Signature (x: int, y: float)>` for `g`).

I tested this with Jedi 0.18 from PyPI as well as the current revision from the git repo (41652507b3de645a8a4329299e8e40bff68c8da7) and Python 3.9.2.

## Behavior in Jedi 0.15

This might be a regression compared to Jedi 0.15. Slightly modified version of the signature-obtaining code above:

```python
from jedi import Script

with open("example.py") as f:
  scr = Script(f.read(), line=11, column=2)

sigs = scr.call_signatures()

for sig in sigs:
  print(sig.to_string())
```

 After installing via `pip install jedi==0.15 parso==0.7`, this yields (correctly, in my opinion) `f(x: int, y: float)`.

**Comment by smheidrich** [comment]
It works fine for something like this, which I guess would be more typical usage for `functools.wraps()`:

```python
from functools import wraps

def f(x: int, y: float):
  "docstring of f"
  pass

def do_wrap(func):
  @wraps(func)
  def g(*args, **kwargs):
    return func(*args, **kwargs)
  return g

g = do_wrap(f)
g()
```

But this gets the parameter list right even if you remove `functools.wraps`, i.e. just by looking at where `*args, **kwargs` are actually going. This should work for the original example above as well, shouldn't it?

**Comment by davidhalter** [comment]
> . In my opinion, it would be better if the parameter list was also taken from the decorated function, as this is the behavior of e.g. Python's own inspect.signature() (which yields <Signature (x: int, y: float)> for g)

I'll consider it.

What bugs me more is the fact that the star argument expansion logic failed. Jedi should have inferred `x: int, y: float` regardless of  the `wraps` decorator. There's like 50 tests for this and this very simple case slipped through.

**Comment by smheidrich** [comment]
I can definitely see the argument for not using the `wraps()`-based signature when it doesn't match what is inferred from the function body, as it's purely "advisory" in that case. But then again, so are type hints.

Either way I agree that in this specific case, inference should've worked it out independently of `wraps()` anyway.

**Comment by davidhalter** [comment]
> But then again, so are type hints.

The difference is that type hints are backed by PEPs and are pretty well defined, whereas with stuff like `wraps` it's basically just heuristics and APIs that work in certain ways.

**Comment by smheidrich** [comment]
Oh I see, that makes sense. Feel free to close this then.

**Comment by PeterJCLaw** [comment]
I think I've seen this too, though in the case I'd seen it I'd put it down to the code in question doing something a bit unusual (which it is, though I'm pretty sure it had worked in the past).

Bisecting this a bit, it looks like this changed between v0.15.1 and v0.15.2, specifically it looks like edb17b8e7cc95e898b1b6ebc77106f913094ee68 is related (that's the first commit which `git bisect` finds with the wrong signature). I don't have time right now to dig in more than that, but hopefully this is useful when we come to look at this. (I may have some time later or over the weekend)

**Comment by davidhalter** [comment]
I wouldn't spend too much time looking at v0.15. It's pretty old and the "regression" was probably due to other factors. The fact that `wraps` does not return the wrapped signature is probably a very simple fix.

The other thing I mentioned with star args inference is probably a bit harder to fix (was also not part of v0.15.1).

**Comment by PeterJCLaw** [comment]
It looks like at least part of the issue here is to do with the wrapping being done at the module level rather than nested in a function. Specifically the following example, which doesn't rely on the function being passed as an argument does get the right signature:

``` python
import functools

def f(x: int, y: float):
    pass

def do_wrap():
    @functools.wraps(f)
    def wrapper(*args, **kwargs):
        return f(*args, **kwargs)
    return wrapper

works = do_wrap()
works()  # f(x: int, y: float)
````

I think this is due to how `jedi.inference.star_args._iter_nodes_for_param` works -- it seems that that function contains the assumption that wrapping won't happen at module scope. I've got a change which fixes that by adjusting how it looks up the `FunctionNode` that I've put up as https://github.com/davidhalter/jedi/pull/1793.

**Comment by smheidrich** [comment]
Thanks for fixing this! :+1:
