### ISSUE TITLE
Attempting to import Jedi in python 3.8 results in ImportError: cannot import name 'indent_block' from 'jedi.common'

### ISSUE THREAD

**Issue by Shellcat-Zero** [davidhalter/jedi#1797]
As described in the title, anything attempting to import Jedi results in `ImportError: cannot import name 'indent_block' from 'jedi.common'`.

Jedi version: 0.34.2
Python version: 3.8.2

This error does not occur in python 3.9.

**Comment by Shellcat-Zero** [comment]
In case it is useful, here is the summary output of `python3.8 -m pytest`:
```
1069 failed, 579 passed, 4 skipped, 5 xfailed, 2159 errors in 478.19s (0:07:58)
```

**Comment by davidhalter** [comment]
This is usually an issue with leftover pyc files from an upgrade. Just do a clean reinstallation.

**Comment by Shellcat-Zero** [comment]
@davidhalter Thanks, this actually occurred after a fresh install. 
`pip install --upgrade --force-reinstall jedi-language-server jedi`
did not work but,
`pip uninstall jedi-language-server jedi` and then `pip install jedi-language-server` 
did the trick!

**Comment by Shellcat-Zero** [comment]
I am actually suspecting that there was some odd conflict (version conflict?) with `python-language-server` which subsequently gave me error messages after these Jedi operations, and I ended up uninstalling python-language-server as well to silence the errors from it.
