### ISSUE TITLE
Can't override bundled stubs

### ISSUE THREAD

**Issue by aivarannamaa** [davidhalter/jedi#1809]
I'd like to provide my own pyi-file for completing `os` module in MicroPython projects.

Tried passing following `Project` to my `Script`:

```python
jedi.Project(path=my_working_dir, sys_path=[my_pyi_dir], smart_sys_path=False)
```

With this I got expected completions for modules not present in stdlib (eg. `machine`), but for `os.` Jedi offered completions from `jedi.third_party.typeshed`.

Is this expected behavior or a bug? Are there ways for overriding bundled stubs?

If this is a bug, then where to look for getting this sorted out?

**Comment by davidhalter** [comment]
Generally Jedi tries to follow https://www.python.org/dev/peps/pep-0561/#type-checker-module-resolution-order

However, I cannot guarantee this is working properly. I suspect that Jedi only checks if there is an `os.pyi` next to the `os.py` and then falls back to typeshed. You could just use an `os-stubs` directory and put your stubs there. I feel like that's probably the best solution.

**Comment by aivarannamaa** [comment]
Regarding docstring issue, here's a distilled experiment:


My stubs dir contains builtins.pyi with following content:

```
def print(a: int, b: str) -> float:
    """docstring for print"""


def prince(a: int, b: str) -> float:
    """docstring for prince"""
```

When I execute following script

```python
from jedi.inference.gradual import typeshed

def _patched_get_typeshed_directories(version_info):
    yield typeshed.PathInfo("/home/annamaa/python_stuff/thonny/thonny/plugins/microbit/api_stubs", False)

typeshed._get_typeshed_directories = _patched_get_typeshed_directories

from jedi import Script

s = Script(code="""prin""")
comps = s.complete()

for comp in comps:
    print("--------------------------")
    print(comp.name)
    print(comp.docstring())

```

... I get following output:

```
--------------------------
prince
prince(a: int, b: str) -> float

docstring for prince
--------------------------
print
print(a: int, b: str) -> float

print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
```

As you can see, the docstring for `print` is not what I gave in the stub file.

Can you recommend how can I force `jedi` to prefer the docstring in the stub file?

**Comment by davidhalter** [comment]
This is not possible, sorry. Stub files provide stubs and not docstrings. Docstrings are part of the implementation IMO.

**Comment by aivarannamaa** [comment]
Yet, jedi did pick up docstring from stub file for my `prince` function. It looks like a `prefer_stubs` argument, like you have introduced in other places, could help here.

Can you give me some pointers about where to look if I'd like to fix this for myself using patches?

**Comment by davidhalter** [comment]
It's probably somewhere in the `py__doc__` methods.

------

I'm going to close this one, since I do not think there's anything to do here. IMO the behavior is fine. Overriding the typeshed stubs is not supported, because Jedi depends on some pretty specific things in there. So if you yourself want to do it, feel free, but I'm pretty sure Jedi will break in one or the other spot if you just pick the "official" typeshed.
