### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [davidhalter/jedi#1813]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
[Markus_Elfring@fedora lokal]$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/jedi/lokal -name '*.py')
```

How do you think about to improve six source code places? :thinking:

-----

:crystal_ball: How would a corresponding refactoring be achieved by the means of the software “Jedi”?

**Comment by davidhalter** [comment]
One issue out to be enough, you don't have to create multiple ones with the exact same content. Closing in favor of https://github.com/davidhalter/parso/issues/200

**Comment by elfring** [comment]
:thought_balloon: Did you notice that the shown Perl command example would generate different updates for the referenced software projects (even if the number of affected source code places is accidentally the same)?

**Comment by elfring** [comment]
:thought_balloon: Do you find [any information from the release of the software “Python 2.0”](https://docs.python.org/3/whatsnew/2.0.html#augmented-assignment "Augmented assignments") relevant for further development considerations?

**Comment by davidhalter** [comment]
Dude stop posing the same questions in two different issue trackers that are both part of *my* projects.
