### ISSUE TITLE
Limit completion to variables that contain only the corresponding enumeration type.

### ISSUE THREAD

**Issue by hongyi-zhao** [davidhalter/jedi#1815]
Can `jedi` supply the right type hints that tells the completer what values re.compile(..., flags) takes, as [this issue](https://github.com/python-lsp/python-lsp-server/issues/101#issuecomment-955839044) commented? 

Regards,
HZ

**Comment by davidhalter** [comment]
Sorry I'm not sure I understand the question. It is unclear where you want type hints and which output you would want.

**Comment by PeterJCLaw** [comment]
This is likely technically possible, but almost certainly not something you actually want. I'll answer in more detail on the original issue.
In terms of whether jedi can provide the (raw) information you're after, I believe it already does as a result of exposing the type signatures (if it doesn't that may be a bug, but such a bug is separate to what you're after here).

**Comment by davidhalter** [comment]
@PeterJCLaw The thing is just that `re.compile` should be part of typeshed, which has annotations. Like you said we expose this information. So my guess is that the lsp code is just "wrong".

**Comment by davidhalter** [comment]
@hongyi-zhao I'm closing, because in the discussion in https://github.com/python-lsp/python-lsp-server/issues/101#issuecomment-956762069, @PeterJCLaw clearly showed why it would not make sense to use this in Jedi.
