### ISSUE TITLE
Bugfix/Python 3.10 compatible release date

### ISSUE THREAD

**Issue by Kojoley** [davidhalter/jedi#1816]
I am working on IPython futureproofing and it requires unreleased fixes (https://github.com/davidhalter/jedi/pull/1795) to pass the tests. I did not find a release schedule and asking here about when it could be expected. 

It is not that IPython Python 3.10 compatible release would be entirely blocked by Jedi, but some functionality will not work and it is annoying to workaround bugs,

**Comment by davidhalter** [comment]
Thanks for bringing it up. I will hopefully find time this weekend.

**Comment by davidhalter** [comment]
v0.18.1 is released.

Have fun :)
