### ISSUE TITLE
No completions for asynccontextmanager

### ISSUE THREAD

**Issue by jerluc** [davidhalter/jedi#1818]
I have not been able to get any asynccontextmanagers (e.g. `httpx.AsyncClient`) to actually work and show completions with jedi, so I decided to make a simple test case to show how normal contextmanagers work but async ones do not:

```python
import jedi


code = """\
import typing


class Thing:
    def get_num(self) -> int:
        return 10


class OtherThing:
    def __init__(self, thing: Thing):
        self.thing = thing

    def __enter__(self) -> Thing:
        return self.thing

    def __exit__(self, exc_type, value, traceback):
        pass


class AsyncOtherThing:
    def __init__(self, thing: Thing):
        self.thing = thing

    async def __aenter__(self) -> Thing:
        return self.thing

    async def __aexit__(self, exc_type, value, traceback):
        pass


def sync_test():
    with OtherThing(Thing()) as th:
        th.


async def async_test():
    async with AsyncOtherThing(Thing()) as th:
        th.
"""


script = jedi.Script(code=code)

completions = script.complete(line=33, column=11)
assert len(completions) > 0
assert completions[0].complete == "get_num"

completions = script.complete(line=38, column=11)
assert len(completions) > 0
assert completions[0].complete == "get_num"
```

In fact, in the failing case, there are no completions at all that are generated.

I believe this might be some kind of bug, but I'm not exactly sure where I can even start to try debugging this particular case. Any pointers on where to start looking would be much appreciated!

jedi version: 0.18.0
Python version: 3.7.9

**Comment by davidhalter** [comment]
I can reproduce. Thanks for the precise issue!

**Comment by jerluc** [comment]
Thanks for confirming @davidhalter. I did a little more digging and it looks like the type inference itself is what's a bit off:

```python
import jedi


code = """\
import typing


class Thing:
    def get_num(self) -> int:
        return 10


class OtherThing:
    def __init__(self, thing: Thing):
        self.thing = thing

    def __enter__(self) -> Thing:
        return self.thing

    def __exit__(self, exc_type, value, traceback):
        pass


class AsyncOtherThing:
    def __init__(self, thing: Thing):
        self.thing = thing

    async def __aenter__(self) -> Thing:
        return self.thing

    async def __aexit__(self, exc_type, value, traceback):
        pass


def sync_test():
    with OtherThing(Thing()) as th:
        th.


async def async_test():
    async with AsyncOtherThing(Thing()) as th:
        th.
"""


script = jedi.Script(code=code)

infs = script.infer(line=33, column=10)
assert len(infs) > 0
assert infs[0].name == "Thing", infs[0].name

infs = script.infer(line=38, column=10)
assert len(infs) > 0  # Fails due to no inferences being returned
assert infs[0].name == "Thing", infs[0].name
```

After tracing the call stack a bit further, I ended up with this minor patch:

```patch
diff --git a/jedi/inference/syntax_tree.py b/jedi/inference/syntax_tree.py
index 192328f3..8e7fd043 100644
--- a/jedi/inference/syntax_tree.py
+++ b/jedi/inference/syntax_tree.py
@@ -738,7 +738,9 @@ def tree_name_to_values(inference_state, context, tree_name):
         types = infer_expr_stmt(context, node, tree_name)
     elif typ == 'with_stmt':
         value_managers = context.infer_node(node.get_test_node_from_name(tree_name))
-        enter_methods = value_managers.py__getattribute__('__enter__')
+        enter_method_name = '__aenter__' if node.parent.type == 'async_stmt' else '__enter__'
+        enter_methods = value_managers.py__getattribute__(enter_method_name)
+        # TODO how do I unwrap the Coroutine?
         return enter_methods.execute_with_values()
     elif typ in ('import_from', 'import_name'):
         types = imports.infer_import(context, tree_name)
```

Which now at least improves the type inference to correctly detect a `Coroutine[Thing, ..., ...]`, but I'm not sure where to go from here to "unwrap" the type (or if this is actually even the best way to make this change). My naive understanding is that when an `async with awaitable_func() as name:` statement is encountered, we should get a sort of "nesting" effect:

- Enter `async with`
  - Enter `awaitable_func() as name`
    - Get type of `awaitable_func()` as `Coroutine[Thing, ..., ...]`
    - Set type of `name` to `Coroutine[Thing, ..., ...]`
  - Exit `awaitable_func() as name`
  - Unwrap `Coroutine[Thing, ..., ...]` to `Thing`
- Exit `async with`

But I'm not very familiar with the jedi codebase and could use any pointers!

**Comment by davidhalter** [comment]
Oh wow, I guess that's actually where you would have to fix the bug.

In general you can probably call:

```
enter_methods.execute_with_values().py__await__().py__stop_iteration_returns()
```
or

```
enter_methods.py__await__().py__stop_iteration_returns()
```

But this is without actually trying it. Does this help? Otherwise you can try to activate `jedi.set_debug_info()`, that might help me at least :)

**Comment by davidhalter** [comment]
The question I guess is in general how do you get from `Coroutine[Thing, ..., ...]` to `Thing`. You can generally follow the annotations here. `Coroutine` inherits from `Awaitable`, which has an `__await__`. Then you will get a `Generator` object, which you can "unpack" with `py__stop_iteration_returns`.

**Comment by jerluc** [comment]
Thanks for the advice and insight @davidhalter, I sent a short patch for this in #1819.

**Comment by davidhalter** [comment]
I just did a new release v0.18.1. Thanks again for the fix!

If you are interested in working more on Jedi, I'm more than happy to help you with potential issues. Just let me know what you want to work on if that's the case. :)
