### ISSUE TITLE
Getting error on completions

### ISSUE THREAD

**Issue by Greed058** [davidhalter/jedi#1825]
I was newly setting up neo-vim and I came across this error whenever I wrote anything in a file 
`Jedi error: Traceback (most recent call last):
  File "/home/deexeet/.config/coc/extensions/node_modules/coc-python/pythonFiles/complet
ion.py", line 696, in <module>
[coc.nvim] Jedi error:     import jedi
ModuleNotFoundError: No module named 'jedi'`

I don't know if Jedi is not installed properly or something else 
I installed Jedi through PIP and I tried to install it through Coc by writing `:CocInstall coc-python`

It says `[coc.nvim] Error on load extension from "/home/deexeet/.config/coc/extensions/node_modu
les/coc-python": item.dispose is not a function`

 and auto-complete doesn't work

**Comment by davidhalter** [comment]
I'm not sure what's wrong there, but I'm pretty sure I cannot assist you with Coc stuff :) I'm not using it myself and installing Jedi definitely works. Also `item.dispose` does not sound like something that's part of Jedi, so please open an issue in the coc tracker.
