### ISSUE TITLE
Go to definition with `auto_import_modules` seems not working correctly in version `0.18.1`

### ISSUE THREAD

**Issue by goingtosleep** [davidhalter/jedi#1829]
Context:
- Neovim with `jedi-language-server` and `coc-jedi`.
- `jedi` version `0.18.1`.
- `"numpy"` in `auto_import_modules` setting.
- The code:

```python
import numpy as np

np.random.rand()
```

Expected:
Go to definition of `rand()` function will end up in stub file definition.

Actual:
Go to definition of `rand()` function shows error "definition not found".

After reading the diff between version `0.18.0` and `0.18.1`, I found line 121 [here](https://github.com/davidhalter/jedi/blob/master/jedi/inference/gradual/typeshed.py#L121) would possibly be the point:

```python
# Below line is line 121
if not prefer_stubs or import_names[0] in settings.auto_import_modules:
    return python_value_set

stub = try_to_load_stub_cached(inference_state, import_names, python_value_set,
                                                    parent_module_value, sys_path)
if stub is not None:
    return ValueSet([stub])
return python_value_set
```

If we have non-empty `settings.auto_import_modules`, for example `auto_import_modules = ["numpy"]`, even when `prefer_stubs=True`, the if statement in line 121 is executed and `python_value_set` is returned. Then the stub loading code (from line 124 to the rest) won't be executed, and so "go to definition" will be "not found".

I'm not so sure, but after modifying line 121 to:
```python
if not prefer_stubs:
    if import_names[0] in settings.auto_import_modules:
        return python_value_set
```

The behavior is the same as `jedi 0.18.0`, go to definition shows me the stub definition.

Btw, happy new year and thank you to all the contributors for a great library. I used `pyright` but converted to `jedi` because `pyright` missed some completions I need. With stubs, `jedi` completion is fast enough for me 😄

**Comment by davidhalter** [comment]
I'm not sure I can make `auto_import_modules` work correctly. It is basically just a hack to get certain things fast. The idea is that it skips all kind of parsing/inference steps.

Have you tried to use it without `auto_import_modules`? Is it too slow for you?

**Comment by goingtosleep** [comment]
Yeah, without `auto_import_modules`, go to definition works well, but the completion is a bit slow for me. I use `numpy, pandas, matplotlib and scipy` a lot 🤨.
I thought we can fix line 121 as above, and the `goto` will behave like 'v0.18.0' (go to stub `.pyi` file instead of "not found" error). Is it against something you're planning, or I misunderstood something?

**Comment by davidhalter** [comment]
It is not against anything particular. It's just that you kind of defeat the purpose of `auto_import_modules` if you start loading stuff again. The idea of that option is to get some kind of completions, but maybe not always the correct ones. If you want to get correct completions, just do not use it. It's something inherently broken and if I'm not sure I would make it public again.

I understand that it's slow and I'm working on an alternative in Rust, but I can unfortunately not help you here.

However feel free to ask questions.

**Comment by davidhalter** [comment]
> I used pyright but converted to jedi because pyright missed some completions I need.

Can you give me an example? Just because I'm interested.

**Comment by goingtosleep** [comment]
> > I used pyright but converted to jedi because pyright missed some completions I need.
> 
> Can you give me an example? Just because I'm interested.
There are a few, I can recall two:
```python
import pyarrow
pyarrow.Table.fr   # should show: from_pandas(), from_arrays()...
```

```python
import sqlalchemy
sqlalchemy.engine.u   # should show: url, URL...
```
Both `pyright` and `VSCode` show me no suggestion for those 2 examples.
Thank you for the explanation. Very excited about the Rust version of Jedi 😄
