### ISSUE TITLE
constructor hinting for attrs

### ISSUE THREAD

**Issue by glyph** [davidhalter/jedi#1835]
I noticed that calltips for `__init__` treat dataclasses correctly but do not treat attrs classes correctly.

This could be implemented as a quick-and-dirty solution by treating `attrs.define` and `attrs.field` as simple aliases for `dataclasses.dataclass` and `dataclasses.field`; 90% of the relevant functionality overlaps, and the stuff that doesn't is generally not necessary for a basic calltip.

**Comment by davidhalter** [comment]
That's definitely possible. I probably won't work on this for now, but if anyone is interested, this should probably not be that hard.

**Comment by timrid** [comment]
Probably it would be better to use `dataclass_transforms` directly (https://github.com/microsoft/pyright/blob/main/specs/dataclass_transforms.md). I have seen that for this there is also a new PEP in work to include `dataclass_transforms` in the `typing` module. And it is already supported by attrs from v21.1.0.

**Comment by davidhalter** [comment]
AFAIK this is something specific to pyright, right? It might be worth looking at it. Thanks for bringing it up!

**Comment by timrid** [comment]
Currently this is only supported by pyright/pylance. But they created an draft PEP. See [here](https://mail.python.org/archives/list/typing-sig@python.org/thread/EAALIHA3XEDFDNG2NRXTI3ERFPAD65Z4/). So maybe this is added to the typing module in the future.

**Comment by asford** [comment]
@davidhalter I've taken a stab at the trivially-proximal implementation of this in #1885.

**Comment by davidhalter** [comment]
Great changes @asford! I will close this one, since your PR makes this work like a charm. I also agree with your comment in the PR that we should probably focus on `PEP 681 dataclass_transforms` if we want to go further.

The PR is not merged yet, but will be very soon I guess.

**Comment by Morikko** [comment]
https://github.com/davidhalter/jedi/pull/2049 adds support for dataclass_transform. Feedback are welcome.
