### ISSUE TITLE
No module tooltips for non-built-in packages in remote conda environment

### ISSUE THREAD

**Issue by tobiscode** [davidhalter/jedi#1839]
Issue Type: <b>Bug</b>

_I reported this bug originally in the VS Code Python Extension repository (https://github.com/microsoft/vscode-python/issues/18563), but was told that this repo is probably the better location. Happy to provide additional logs._

# Behaviour
## Expected vs. Actual

No tooltips for non-built-in packages when accessing a remote server via SSH and using a conda environment.

- Tooltips for built-ins work
- The file linting, the selected Python intepreter, and debugging, all work, with the correct conda environment
- On a local installation, all tooltips work

Sorry if this ends up being better suited for the the remote-ssh repository, or one of the Jedi repositories - I wasn't able to pinpoint the problem source.

The "Python" output console doesn't show any errors, and the "Python Language Server" output is empty.

## Steps to reproduce:

1. Connect to an SSH workspace, create an empty Python file, type `import numpy`
2. Hover over `numpy`, expecting the tooltip - nothing shows up (not even "loading" or something else)

## Things I tried:

- changing conda environments
- killing all VS Code processes via a terminal and restarting
- changing linter from flake8 to pylint
- wait for newer versions of VS Code - this has been an issue for me for the past months
- no problem when using Pylance

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.10
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Jedi

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Jedi"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Jedi"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: true
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

insidersChannel: "off"

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.0.1814523869
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 4.18.0-348.2.1.el8_5.x86_64

**Comment by davidhalter** [comment]
@pappasam Can you maybe clarify which functionality this is about? I have no idea what tooltips are in VSCode/LSP or your server.

**Comment by pappasam** [comment]
https://github.com/pappasam/jedi-language-server/blob/5de3717b4185d9d32e9a17ad963a38787850cca4/jedi_language_server/server.py#L340

This functionality basically wraps `Script.help`.

I think this issue may be related to Jedi's handling of PYTHONPATH when working with conda environments (instead of normal Python virtualenvs): https://github.com/pappasam/coc-jedi/issues/4

That said, since I don't use Conda, I've haven't had much luck figuring out how to resolve any issues involving Conda.

**Comment by pappasam** [comment]
Basically, the use is pointing out how my language server doesn't seem to be aware of 3rd party packages installed through conda. I believe `jedi-language-server` is installed outside of the user's conda environment and does not know how to recognize / find the conda environment. For regular virtual environments, jedi is able to identify them even if the `jedi-language-server` library is installed outside of the currently-active venv.

**Comment by davidhalter** [comment]
Isn't there some option to provide a path from vscode? Jedi can deal with venvs just fine, but you need to tell it where to scan for them or give it an explicit path, so it "knows".

**Comment by davidhalter** [comment]
I doubt that this is a Jedi issue. Unless it's more clear it is, I'm closing for now.
