### ISSUE TITLE
ֿgotodef/autocomplete issues for python 3.10 syntax

### ISSUE THREAD

**Issue by omerdun** [davidhalter/jedi#1843]
I know python 3.10 is pretty new and saw there is already an [open issue](https://github.com/pappasam/jedi-language-server/issues/187) regarding syntax highlighting just wanted to note a few cases where it looks like gotodef doesn't work as well.

```python
with (open("foo") as one, open("foo") as two, open("foo") as three):
      print(one)
      print(two)
      print(three)
```
Trying to do go to def in VSCode using jedi language server on one/two/three fails, also autocomplete doesn't work for those.

```python
match points: 
    case (Point(x1, y1), Point(x2, y2) as p2): 
        print(p2)
```

Trying to do go to def in VSCode using jedi language server on p2 fails, also autocomplete doesn't work for it.

```python
match [1, 2]:
    case [test_a, test_b]:
        print(test_a)
````

Trying to do go to def in VSCode using jedi language server on test_a fails, also autocomplete doesn't work for it.

**Comment by davidhalter** [comment]
Mostly requires https://github.com/davidhalter/parso/issues/138

**Comment by davidhalter** [comment]
Closing, because this is a parso issue.
