### ISSUE TITLE
Injection of dynamic members

### ISSUE THREAD

**Issue by meatballs** [davidhalter/jedi#1845]
I'm using a library where the members of one of its modules are created 'on the fly' at runtime based on the content of a yaml file.

Is there any way I can 'inject' the existence of those into jedi? I have the yaml file available within my project, so I can easily parse it myself.

(I'm looking at creating a python-lsp-server plugin to do this).

Many thanks!

**Comment by davidhalter** [comment]
No. Sorry :)

**Comment by davidhalter** [comment]
(And BTW I think this is almost always an anti-pattern)

**Comment by meatballs** [comment]
Oh well. Thanks anyway for the response!
