### ISSUE TITLE
how jedi get auto completions from a module

### ISSUE THREAD

**Issue by zhouwei25** [davidhalter/jedi#1848]
I want to know how jedi get auto completions from a python module.
------

when I run first:

<img width="1271" alt="infoflow 2022-04-08 12-38-40" src="https://user-images.githubusercontent.com/52485244/162364745-70908d2c-d36c-42f4-a650-3db95dd21724.png">

Should it run `import paddle` first?  but there is not any module of paddle in `sys.modules.keys()`, so paddle may be import again each time and trigger an error.

but when I run seconed time:

<img width="1273" alt="infoflow 2022-04-08 12-39-26" src="https://user-images.githubusercontent.com/52485244/162364813-5af8bae6-44db-4fdf-bffa-008719ce0195.png">

An error has occurred, I think that it's because of the auto completions mechanism bug of jedi.  Does anyone have an opinion on that?

related to https://github.com/davidhalter/jedi/issues/1849

**Comment by davidhalter** [comment]
I feel like Jedi doesn't do very weird stuff. AFAIK it uses `__import__`. My feeling is that this is a `paddle` issue.

**Comment by davidhalter** [comment]
I do not think Jedi is doing very weird things here. I have also no idea how to debug this. Please let me know if I can help something, but for now I'll close.
