### ISSUE TITLE
jedi import module twice

### ISSUE THREAD

**Issue by zhouwei25** [davidhalter/jedi#1849]
when I first run `import paddle;paddle.` , and use TAB to auto-complete:

![infoflow 2022-04-08 15-08-36](https://user-images.githubusercontent.com/52485244/162383158-5bde680e-b18b-4f1e-897c-2e593664dd06.png)

`import paddle` shoule run first, but there is not any module of paddle in `sys.modules.keys()`? 

![infoflow 2022-04-08 15-11-49](https://user-images.githubusercontent.com/52485244/162383403-a8b16451-65fb-42f8-b5c1-29ae3066bfbf.png)

But ,when I run it on linux/windows, all paddle module  is in `sys.modules.keys()`.

This problem will result that `paddle` module will be reloaded each time when I use TAB, does anyone notice this problem?

related to https://github.com/davidhalter/jedi/issues/1848

**Comment by davidhalter** [comment]
Let's just only use #1848 for this issue.
