### ISSUE TITLE
Completion hides some parameters depending on the order they are specified in

### ISSUE THREAD

**Issue by joelostblom** [davidhalter/jedi#1856]
I have noticed that function parameters sometimes gets hidden and don't show up in the completion. Take the `random.triangular` function for example:

```python
import jedi
import random

to_complete = 'random.triangular('
completions = jedi.Interpreter(to_complete, [globals()]).complete(line=1, column=len(to_complete))
[c for c in completions if c.name.endswith('=')]

# Output as expected:
# [<Completion: low=>, <Completion: high=>, <Completion: mode=>]
```

If I change the input string to `to_complete = 'random.triangular(low=5,'`, the output is `[ <Completion: high=>, <Completion: mode=>]` as expected. However, if I start with any of the other to parameters, e.g.  `to_complete = 'random.triangular(high=5,'` the output is just `[<Completion: mode=>]` and the `low` parameter is hidden:

![image](https://user-images.githubusercontent.com/4560057/168405964-6864c944-f2f7-4d7a-9e34-c08df58aee2b.png)

The same behavior occurs if I start with `low` and then have `mode` as the second parameter (`high` gets hidden):

![image](https://user-images.githubusercontent.com/4560057/168406015-fdd73c9e-e4c4-4fe9-85f6-f27f12894475.png)

If I start with `low` and have `high` as the second parameter, then `mode` shows up correctly:
![image](https://user-images.githubusercontent.com/4560057/168406042-9dd57cc0-9668-4c82-9b6e-a4ae331c4e4b.png)

This is with Jedi installed from github as of yesterday ('0.18.1') and IPython 8.4.0dev. I see this behavior both on master and the branch I pushed yesterday https://github.com/davidhalter/jedi/pull/1855

**Comment by davidhalter** [comment]
Thanks a lot for reporting this, I feel like I always wondered why there were these issues with keyword params sometimes.

**Comment by joelostblom** [comment]
Thank you for the fix!
