### ISSUE TITLE
exclude 'dlg_' items when autocompletion is called for 'DLG_'

### ISSUE THREAD

**Issue by Alexey-T** [davidhalter/jedi#1859]
Is there an option to do SUBJ, ie exclude items which do not fit by casing? It is needed for Python! DLG_ and dlg_ id's are different things (upcase usually means constants).
I use Jedi 0.18.1, latest, on Ubuntu 20 x64. Python 3.8.

**Comment by davidhalter** [comment]
There's `jedi.settings.case_insensitive_completion = False`. Does that help?

**Comment by Alexey-T** [comment]
Tks!
