### ISSUE TITLE
infer / goto does not work e.g. os.abort()

### ISSUE THREAD

**Issue by SebastianBolte** [davidhalter/jedi#1863]
I'm trying to get goto for os.abort() but got an empty list:

>>> import jedi
>>> code = '''
... import os
... os.abort()'''
>>> script=jedi.Script(code)
>>> script.infer(2,6)
[]
>>> script.infer(2,1)
[]
>>> script.goto(2,6)
[]
>>> script.goto(2,1)
[]
>>>

Am I doing something wrong? sys.path contains the lib folder of the python installation where os.py is located.

**Comment by SebastianBolte** [comment]
Sorry, wrong line number. It's working.

**Comment by qmmp123** [comment]
@SebastianBolte May be close issue?
