### ISSUE TITLE
How to import non .py files

### ISSUE THREAD

**Issue by SebastianBolte** [davidhalter/jedi#1865]
I would like to be able to import non .py files for auto completion etc. Can you please tell were I have to adapt the jedi - code. I've tried to adapt the imports.py line 517 but had no success.

**Comment by davidhalter** [comment]
Are they Python files, but they do not end with `.py`?

**Comment by SebastianBolte** [comment]
They have some little differences, but in general yes.

**Comment by davidhalter** [comment]
I'm not sure how to do that for imports for now and this also won't be supported. There's definitely hacks (probably around sys.metapath if you just want to play with it).

However if you pass your file to `Script`, it doesn't matter what file ending it has, imports for other file endings just won't work.
