### ISSUE TITLE
Thoughts on using readline menu-complete instead of complete?

### ISSUE THREAD

**Issue by slmb3** [davidhalter/jedi#1868]
Probably opinionated, but readline's `menu-complete` is a much better way of handling completions than `complete`, because it can cycle through multiple matches without user needing to type in more characters. Example below.
If disagree or if there's a good reason not to do this by default, maybe we could add some examples in the docs how to override? 

Default behavior with `complete`: https://github.com/davidhalter/jedi/blob/7ff0d2d5952d1f4bd216a9df0fa7171b20d0512c/jedi/utils.py#L114
```
$ env PYTHONSTARTUP="$(python -m jedi repl)" python
>>> setup = 'foo'
>>> myset = se <<<pressing tab 3x
myset = set ...attr  ...up
>>> myset = set
myset = set ...attr  ...up
>>> myset = set
myset = set ...attr  ...up
>>> myset = set
```

Using `menu-complete` instead of `complete`
```
$ env PYTHONSTARTUP="$(python -m jedi repl)" python
>>> import readline
>>> readline.parse_and_bind('tab: menu-complete')
>>> setup = 'foo'
>>> myset = se <<<press tab 1x
myset = set ...attr  ...up
>>> myset = set
```
Pressing tab again changes buffer line to 
```
>>> myset = setattr
```

Pressing tab again changes buffer line to 
```
>>> myset = setup
```

**Comment by davidhalter** [comment]
I couldn't even get it working on my Ubuntu. However it doesn't really matter. This is something users can easily change and the default is the default that Python already has. So I do not see any reason to change that. (Also I personally prefer no cycling over cycling by a lot, but that's my own preference).
