### ISSUE TITLE
absolute import failure when importing from a namespace package

### ISSUE THREAD

**Issue by OmmyZhang** [davidhalter/jedi#1869]
Let files be like this

```shell
$ tree
.
├── a
│   └── a1.py
├── b
│   └── b1.py
├── c
│   └── a.py
└── main.py
```

In `c/a.py`, importing from `b/*` is fine 

![image](https://user-images.githubusercontent.com/17777309/184616621-509aa7f3-7dd9-4bfc-80ad-af3c444a1d4e.png)

but finding things from `a/*` fails

![image](https://user-images.githubusercontent.com/17777309/184616806-e65469b0-67c4-4d23-a3a7-174c388cdc1b.png)

It even tries to import thing in `c/a.py`

![image](https://user-images.githubusercontent.com/17777309/184616988-0fe16b5c-c1bc-42f3-b337-7d4c33dfdcf0.png)

When it's a regular package

```shell
$ tree           
.
├── a
│   ├── a1.py
│   └── __init__.py
├── b
│   └── b1.py
├── c
│   └── a.py
└── main.py
```

It works as excepted.

![image](https://user-images.githubusercontent.com/17777309/184617487-2e3e2295-7dd0-4f6a-a682-ce806ee8eeb5.png)

**Comment by davidhalter** [comment]
I'm pretty sure this is, because Jedi does not know where the start of a package is. Typically adding a `setup.py` to the root fixes this (because then it looks like a package).
