### ISSUE TITLE
too slow for multiple call this api

### ISSUE THREAD

**Issue by wiyr** [davidhalter/jedi#1872]
https://github.com/davidhalter/jedi/blob/695f0832b4518ec412e520dadf227b02b105fe99/jedi/api/project.py#L298

I think this ios should be cached since multiple call `project.search` will cost too much time.

**Comment by davidhalter** [comment]
Won't be fixed in Jedi, will be fixed in my rewrite of Jedi in Rust. The relevant issue is #1059.
