### ISSUE TITLE
[bug] jedi: IndentationError: unexpected indent

### ISSUE THREAD

**Issue by Freed-Wu** [davidhalter/jedi#1873]
Refer <https://github.com/pappasam/jedi-language-server/issues/223>

`test.py` can work normally. However, jedi-language-server will give an error: `jedi: IndentationError: unexpected indent`

```python
with (
    open("LICENSE") as f,
    open("README.md") as g,
):
    pass
```

![Screenshot from 2022-08-24 13-51-06](https://user-images.githubusercontent.com/32936898/186340696-5f0057c5-a148-4878-a9eb-0a5262877200.png)

**Comment by davidhalter** [comment]
Part of https://github.com/davidhalter/parso/issues/138
