### ISSUE TITLE
pytest fixtures tmpdir and tmpdir_factory not found on pytest 7

### ISSUE THREAD

**Issue by marciomazza** [davidhalter/jedi#1880]
Since pytest `7.0.0` the fixtures `tmpdir` and `tmpdir_factory` were moved to a `Pluggy` plugin class, so are not found anymore by jedi.

This partially breaks #791.

The change was made here: https://github.com/pytest-dev/pytest/commit/e6eac28f0

**Comment by davidhalter** [comment]
This should be fixed now on master.
