### ISSUE TITLE
Match statement error

### ISSUE THREAD

**Issue by amogusussy** [davidhalter/jedi#1883]
In VSCode, when you use the match statement it gives a syntax error.

This [issue](https://github.com/microsoft/vscode-python/issues/17745) was made on the official vscode-python repo nearly a year ago, but is still yet to be solved, and they said it is due to jedi not supporting it yet.

**Comment by davidhalter** [comment]
I'll keep this open here for now, because you are not the first to open an issue about that.

The relevant issue is https://github.com/davidhalter/parso/issues/138.

**Comment by davidhalter** [comment]
Closing, because this is a parso issue.
