### ISSUE TITLE
Autocomplete on custom descriptor class

### ISSUE THREAD

**Issue by delfick** [davidhalter/jedi#1884]
Hello,

I was redirected here from https://github.com/python-lsp/python-lsp-server/issues/275, I'll repeat the body of that here.

I have the following code:

```
import typing as tp

T = tp.TypeVar("T")


class Property(tp.Generic[T]):
    def __init__(self, kls: type[T]):
        self.kls = kls

    def __get__(self, instance=None, cls=None) -> T:
        return self.kls()


class Thing:
    @classmethod
    def property(cls: type[T]) -> Property[T]:
        return Property(cls)


class Other(Thing):
    def add_things(self):
        pass


class Stuff:
    other = Other.property()


other = Stuff().other
reveal_type(other)
# Mypy correctly thinks other is of type `Other`
# but pylsp gives vim.lsp.buf.completion() an empty list

```

mypy understands that `Stuff().other` is of type `Other` but pylsp doesn't

But if I have this code:

```
import typing as tp

T = tp.TypeVar("T")


class Thing:
    @classmethod
    def property(cls: type[T]) -> property:
        return property(lambda s: cls())


class Other(Thing):
    def add_things(self):
        pass


class Stuff:
    other = Other.property()


other = Stuff().other
reveal_type(other)
# Mypy incorrectly thinks other is of type `Any`
# but pylsp _does_ give "add_things" to vim.lsp.buf.completion()
```

Then mypy thinks `Stuff().other` is of type `Any` but pylsp correctly figures out that it is of type `Other` and autocompletes `add_things`

Should jedi be able to handle autocompleting on my custom descriptor?

**Comment by davidhalter** [comment]
I feel like the problem is probably `property(cls: type[T]) -> Property[T]:` and not the descriptor itself.

**Comment by delfick** [comment]
If I don't do that then mypy doesn't realise the Property returns an instance of the subclass I've called property on and that reveal_type returns `Any`

**Comment by delfick** [comment]
I was gonna add a note about another case where it doesn't work  ([this](https://gist.github.com/delfick/d21c2afc19a1dc275b79952093c38381) worked but [this](https://gist.github.com/delfick/d29a19b165d5e7bcf0b6d775da347c1f) did not), but then I realised I had an old jedi (0.17.2) and on upgrading to (0.18.2) jedi works correctly! :) including original query. Thanks!
