### ISSUE TITLE
Support being run from zip files

### ISSUE THREAD

**Issue by DUOLabs333** [davidhalter/jedi#1892]
Right now, to get a python process open so it can pass in code, it starts up by calling the location of the main.py file in jedi. However, of course, you can't get this file in zipapps. So, instead a possibility is just run the folder, not the file --- that should work in both zips and the file system.

**Comment by davidhalter** [comment]
I do not understand your problem at all.

**Comment by DUOLabs333** [comment]
Jedi calls inference/compiled/__main__.py as a different subprocess. However, if jedi is in a zip file, this won't work. This can be fixed by calling inference/compile, as this will work everywhere, and will do the same thing.

**Comment by davidhalter** [comment]
> This can be fixed by calling inference/compiled/subprocess, as this will work everywhere, and will do the same thing.

I do not know what you mean by that.

------

Do you know that you can just use an `InterpreterEnvironment` and Jedi won't call a different subprocess?

**Comment by DUOLabs333** [comment]
In inference/compiled/subprocess/__init__.py, _MAIN_PATH is inference/compiled/subprocess/__main__.py. Just set it to inference/compiled/subprocess instead.

I didn't know about `InterpreterEnvironment` --- I'm not using Jedi directly, but with jedi-language-server, so I guess I'll open an issue with them.

**Comment by DUOLabs333** [comment]
How exactly would you use `InterpreterEnvironment`? The docs were not very clear.

**Comment by DUOLabs333** [comment]
Ok, tracked [here](https://github.com/pappasam/jedi-language-server/pull/238). Thanks for the idea.

**Comment by DUOLabs333** [comment]
Maybe jedi could detect whether if it's in a zip file any be default, offer InterpreterEnvironment?

**Comment by davidhalter** [comment]
How would you do that?
