### ISSUE TITLE
Get reference in type annotation

### ISSUE THREAD

**Issue by enadeau** [davidhalter/jedi#1898]
Jedi seems to not pick up reference that are in type annotation or in f-string. This creates issue when using rename has to reference are not changed.

This snippet prints only one reference when it should find three.
```py
import jedi
source = '''
class Foo:
    def return_me(self) -> "Foo":
        return

    def __str__(self) -> str:
        return "foo"
'''
s = f"My class {Foo()}"

script=jedi.Script(code=source)
for ref in script.get_references(line=2, column=7):
    print(ref)
```
Output:
```
<Name full_name='__main__.Foo', description='class Foo'>
```

I don't know if that is conscious choice, but it would be able to pick those references. I'd be happy to help, maybe by coding a failing test first, if someone can point me where it should go.

**Comment by davidhalter** [comment]
Can you maybe send the full reproduction code? I feel like you removed the jedi calls.

**Comment by davidhalter** [comment]
Yes, the issue with the references is unfortunate, but I'm not sure this is very easy. I would probably argue that people should just use `from __future__ import annotations` and not use the strings.

You could try to scan for all functions in a file and then check all annotations and parse those (if they are strings), look for the name and try to resolve it. It's probably not extremely easy, but definitely possible.

**Comment by enadeau** [comment]
I agree with you the use for `from __future__ import annotations` is the way it should be done. I'm closing the issue
