### ISSUE TITLE
iPython Jedi completion result timing depends sensitively on CWD

### ISSUE THREAD

**Issue by jdtsmith** [davidhalter/jedi#1899]
At ipython/ipython#13866 I reported an issue in which completions inside an `astropy.units` object (`x.unit.[Tab]`) produce results in widely varying amounts of time, depending on the _current working directory_.  If iPython is in a deep directory (like `~/`) Jedi actually crashes.  Not-so-deep but significant (`~/code`) takes 30 or 40s, and a shallow directory at the end of the tree structure completes in about a second, with the same results.  

So it seems a static analysis of the entire directory tree, starting at iPython's current working directory, is occurring.  It's not clear why.  Reproduction recipe in the above.  See also #1446.

**Comment by davidhalter** [comment]
I think this should be fixed now. I disabled a complex interaction that did not make sense at all for interpreter completions. Please quickly check if this indeed fixes your issue. For me the pre/post commit is:

```
CPU times: user 221 ms, sys: 3.15 ms, total: 224 ms
CPU times: user 7.46 s, sys: 241 ms, total: 7.7 s
```

Thanks again for the good reproduction and issue. 

I'll suggest to leave the downstream IPython issue in https://github.com/ipython/ipython/issues/13866 open until I make a release.

**Comment by jdtsmith** [comment]
Thanks.  What's the easiest way to try your new fix with an existing iPython.

**Comment by davidhalter** [comment]
I personally feel like that's the way:

https://jedi.readthedocs.io/en/latest/docs/installation.html#manual-installation-from-github

Maybe uninstall Jedi first and check it's really gone.

**Comment by jdtsmith** [comment]
This fix works well.  Thanks!
