### ISSUE TITLE
Question/Feature request: Can I disable adding `name=` during autocompletion of function arguments?

### ISSUE THREAD

**Issue by jpfeuffer** [davidhalter/jedi#1900]
If not, how does Jedi decide when it is valid to add them? Can I change something in my typing maybe?
C functions in python do not allow for named arguments.

**Comment by davidhalter** [comment]
The best way to change this is to use positional only arguments for your stubs. Does this work for you?

**Comment by davidhalter** [comment]
No reply, I'm therefore closing.
