### ISSUE TITLE
how to stop pre-filling variables for functions

### ISSUE THREAD

**Issue by jablka** [davidhalter/jedi#1905]
Hello, this is not a bug, but rather a question.

Say we have a function with some parameter/attribute to be passed in.
```python
def myfunction(myvar):  
    pass
```  
When calling the function (writing the code), Jedi automatically pre-fills (suggests) the parameter. 
```python
myfunction(myvar)
```
It is annoying for me. How can I disable this? And particularly in VSCode (since I'm using this.)
Thank you.

**Comment by PeterJCLaw** [comment]
This is a feature of the `jedi-language-server` package, previously reported in https://github.com/pappasam/jedi-language-server/issues/124 and now tracked in https://github.com/microsoft/vscode-python/issues/15858. While Jedi provides some of the underlying support for this behaviour, it defaults to being disabled and its use is ultimately configured by the VSCode plugin.

**Comment by davidhalter** [comment]
Thanks @PeterJCLaw
