### ISSUE TITLE
How can I search class name in project？

### ISSUE THREAD

**Issue by coollemen** [davidhalter/jedi#1906]
Hai guys，I want to search class name in project. The code like this:

project = jedi.get_default_project()
results = project.complete_search("class QWidget", all_scopes=True)
    for r in results:
        print(r.description)

but the results is none. I can only search class name form my py files or buildin type.
How can I search class in third lib , like pandas,pyside6?

**Comment by davidhalter** [comment]
You would probably need to initialize the project in the third party lib. Otherwise it's not supported, mostly for performance reasons.
