### ISSUE TITLE
Simple way to distinguish imports from exports

### ISSUE THREAD

**Issue by vsoch** [davidhalter/jedi#1913]
Hi! I'm new to jedi, so apologies if I missed this in the docs. I'm doing some basic parsing, and I'm interested to distinguish imports (what the module file needs) vs. exports (what the module file provides). It's not as simple as distinguishing between `module` and everything else, because for example, this would be labeled as a class:

```
import typing.Union
```
And I don't think we can try to namespace things, because someone might import a relative path of some kind that doesn't have the parent module we are interested in. What I'm doing now is very hacky and bad, and I'm hoping there is a better solution - for the time being I'm just looking for the word "import" in the line code:

```python
if "import " in entity.get_line_code():
       imports.add(entry['fullname'])
       continue
```
and that will work for simple cases, but I suspect erroneous if I had like:

```bash
def myfunctionimport ():
    ...
```
I was trying to see if I could use any of `is_stub` or `is_definition` but those don't seem to distinguish either. Any advice would be appreciated, and thanks for the help!

**Comment by davidhalter** [comment]
I personally think you should work with a syntax tree instead. Jedi is probably not the right solution here.

Maybe use parso? There you can simply iterate over all nodes and filter what you need.

Closing, because I usually forget these issues, but feel free to comment, I'm happy to keep responding.

**Comment by vsoch** [comment]
That's great advice - I'll check it out https://github.com/davidhalter/parso many thanks!

**Comment by vsoch** [comment]
One quick question - just want to ask if this parses statically still? It looks like it tokenizes and uses ast (so I think so?) but wanted to ask. https://github.com/davidhalter/parso/blob/master/parso/parser.py

**Comment by davidhalter** [comment]
parso is a parser generator, so it does nothing else than parsing. Also Jedi uses parso. It doesn't use `ast` nor does it generate a custom AST. It results in a simple syntax tree.
