### ISSUE TITLE
Add '3.11' among _SUPPORTED_PYTHONS

### ISSUE THREAD

**Issue by mcepl** [davidhalter/jedi#1914]
https://github.com/davidhalter/jedi/blob/b0025ee6bac9a7ed1ec4041f38cfdd9f14dc54d3/jedi/api/environment.py#L20

We should ‘3.11’ here.

**Comment by davidhalter** [comment]
Feel free to PR it. Ideally this would also come with all the tests enabled in CI (if it isn't already the case).

**Comment by mcepl** [comment]
I am a maintainer of more than two thousand packages in openSUSE/SLE, I really cannot afford to have checked out repositories for all of them. And this change is so trivial (and [tests with it run](https://build.opensuse.org/package/show/devel:languages:python/python-jedi)) that I leave it to you as an exercise.
