### ISSUE TITLE
Change link to python language server

### ISSUE THREAD

**Issue by zerocewl** [davidhalter/jedi#1920]
the old [python-language-server](https://github.com/palantir/python-language-server) seems to be outdated / deprecated and might be replaced by a link to the current version / fork of [python-lsp-server](https://github.com/python-lsp/python-lsp-server)

> python-lsp-server is a fork created by the community because I was the maintainer of this repo but lost my write permissions several months ago. So, it's not something "official", it's just what we needed to do out of necessity.
> 
> There's no one around to merge PRs, so it's not possible to add a note to the Readme. But I don't know if the Palantir guys plan to support this project later on their own (I doubt that, but who knows).

also see related issue comments in the old pyls repo:

https://github.com/palantir/python-language-server/pull/901#issuecomment-771180214  
https://github.com/palantir/python-language-server/pull/901#issuecomment-779483328
https://github.com/palantir/python-language-server/issues/935

**Comment by davidhalter** [comment]
Feel free to PR this.
