### ISSUE TITLE
Stubbing PYD file command ?

### ISSUE THREAD

**Issue by SheepDomination** [davidhalter/jedi#1928]
What is the command required to stub a `pyd` file to a `pyi `file using jedi ?

**Comment by davidhalter** [comment]
There is no way to do this with Jedi. There also won't be. This is done manually.

**Comment by SheepDomination** [comment]
I meant like how other generators for example; stubgen. How is this done manually using Jedi, what is the command ?

**Comment by davidhalter** [comment]
I don't understand. What do you want to do using Jedi?

**Comment by SheepDomination** [comment]
Can Jedi not stub PYD files for use in auto-completion etc ?

**Comment by davidhalter** [comment]
No. Why don't you use stubgen? Jedi can use those stubs.

**Comment by SheepDomination** [comment]
I read someone mentioned that Jedi can stub pyd files; that is why I asked.
