### ISSUE TITLE
`AssertionError: Can only be here when children` when completing in a `with a, b as bobj:` block

### ISSUE THREAD

**Issue by Zalewa** [davidhalter/jedi#1931]
# Steps to reproduce

1. Create an incomplete code file that looks like this (let's call it `jedifail.py`):
```python
with open("a"), open("b") as bfile:
   bfile.
```
Keep the dot at the end for completion purposes. This is valid Python, regardless of the utility of the code.

2. Create a completion helper script that utilizes jedi (let's call it `jedicomplete.py`)
```python
#!/usr/bin/env python3
import sys
import jedi


def main():
    script_path = sys.argv[1]
    with open(script_path, "r") as scriptf:
        code = scriptf.read()
    project = jedi.Project(".")
    script = jedi.Script(code=code, path=script_path, project=project)
    symbols = script.complete(line=len(code.split("\n")) - 1, column=len(code.split("\n")[-2]))
    print(symbols)


if __name__ == "__main__":
    main()
```

3. Run `python3 ./jedicomplete.py ./jedifail.py`

# Expected result

The script `jedicomplete.py` is intended to provide completion for the final line in the script. It should produce completion list for the `bfile` object.

# Actual result

A lengthy stack trace appears with an error message:
```
   ...
jedi/inference/gradual/annotation.py", line 405, in find_type_from_comment_hint_with
    assert len(node.children[1].children) == 3, 
AssertionError: Can only be here when children[1] is 'foo() as f'
```

# Description

This is caused by the `with` block where there are two elements in the block. One element uses the `as` keyword to assign to a variable, but the other doesn't. It is important that the one that **doesn't** is **first**. The problem disappears if you swap the placement of the elements, or if both elements use the `as` keyword or if neither doesn't. 

Also, only the first element matters, so:
```python
# This is OK
with open("a") as afile, \
     open("b"), \
     open("c") as cfile:
    cfile.
```
but
```python
# This fails
with open("a"), \
     open("b") as bfile, \
     open("c") as cfile:
    cfile.
```

# Version

* jedi 0.18.2.
* Also fails in the current HEAD (2023-04-28 825c6b93bf67f5b44552357db52a11b3f62cf864)

**Comment by davidhalter** [comment]
Fixed in 6ea5ad7b192cca53d312737a191faab7680dd3f9
