### ISSUE TITLE
How to get doctring like Pythin built-in help function?

### ISSUE THREAD

**Issue by Toni-SM** [davidhalter/jedi#1932]
Hi

Tried the following:

```python
import jedi

line, column = 2, 5
code = """import os
os.getcwd()
"""

script = jedi.Script(code, path="")
h = script.help(line, column)
print(h[0].docstring())
```

Got:
 
> getcwd() -> str

Expected (something like `help(os.getcwd)`): 

> getcwd()
>   Return a unicode string representing the current working directory

**Comment by davidhalter** [comment]
The problem is that this is a builtin function and there is therefore no way to do this:

```
>>> import os
>>> os.getcwd
<built-in function getcwd>
```

**Comment by davidhalter** [comment]
You might however try to enable `Project(load_unsafe_extensions=True)`. That might help.
