### ISSUE TITLE
`Interpreter` completions ignore `namespaces` when `code` contains object instantiation

### ISSUE THREAD

**Issue by seeM** [davidhalter/jedi#1938]
Firstly, thanks for this amazing library 😄!

I've encountered an odd issue where Jedi excludes completions from a provided namespace when the completed `code` has the object instantiation.

For example:

```python
import pandas as pd

from jedi.api import Interpreter

df = pd.DataFrame({'mycolumn': [7]})
namespaces = [{'df': df}]

# These completions include the `mycolumn` attribute.
code = 'df.'
interpreter = Interpreter(code, namespaces)
completions1 = interpreter.complete(1, 3)
print([completion.complete for completion in completions1 if completion.complete == 'mycolumn'])
# ['mycolumn']

# These completions don't include the `mycolumn` attribute.
# The only difference is that `code` contains the import and definition of `df`, which seems to
# make Jedi prefer static analysis and ignore the namespace.
code = '''
import pandas as pd
df = pd.DataFrame({'mycolumn': [7]})
df.
'''.strip()
interpreter = Interpreter(code, namespaces)
completions2 = interpreter.complete(3, 3)
print([completion.complete for completion in completions2 if completion.complete == 'mycolumn'])
# []
```

This is an issue for my case where I'd particularly like for completions to include the dataframe's columns, which are gettable as attributes on `df`.

**Comment by davidhalter** [comment]
Hi @seeM 

When does this ever happen? I'm just wondering where you have this problem.

This is a very special case that we could potentially special case, but I'm a bit hesitant, because this is really something that is not supported by the Python type system (at the moment). But we could theoretically make that work with a bit of custom code. But I would want to know your use case first.

**Comment by seeM** [comment]
Ah, you're right that it is quite a special case! I'm working on an editor that has a language server (powered by Jedi) with access to the kernel.

**Comment by davidhalter** [comment]
Yeah, I would say we probably don't want to special case it then. If a lot of IPython/Jupyter folks had issues, it would have been more of a benefit I guess.

**Comment by seeM** [comment]
Any suggestions for how to work around this on my end?

**Comment by davidhalter** [comment]
Why is this not executed once the user writes it?

```
import pandas as pd
df = pd.DataFrame({'mycolumn': [7]})
```

I mean you could of course always fork Jedi and do whatever you want with it, but that's probably pretty complicated.
