### ISSUE TITLE
Too many packages listed as docs requirements 

### ISSUE THREAD

**Issue by aqeelat** [davidhalter/jedi#1947]
Do we really need all of these packages to build the docs?
https://github.com/davidhalter/jedi/blob/f2444b4be5e6040308fa587041957d6596dee500/setup.py#L55-L82

**Comment by davidhalter** [comment]
I'm not sure. I guess most of them are indirect packages. But why do you care? This is probably only running in a Sandbox on Read the docs.

I'm closing. If you want to research what the exact dependencies we need, feel free to send a PR and I'll consider it. Note however that I want to pin all the indirect dependencies as well.

**Comment by aqeelat** [comment]
@davidhalter I was searching for packages that still use `six` to help them drop support for python 2. I then saw that jedi was using very old package versions and I just wanted to make sure if they were top level dependencies or not.

Also, I agree with pinning all dependencies but I think we should visually separate them so that we can know what is safe to upgrade, what is no longer needed, etc. (I would suggest poetry but that's a whole other thing.)
