### ISSUE TITLE
Feature to specify custom builtins for Script

### ISSUE THREAD

**Issue by btyoung** [davidhalter/jedi#1948]
Our organization has two cases where python files have additional modules pre-imported and added to the namespace.  For linting in pyflakes/flake8 I've been able to handle this well using the --builtins flag, and I was hoping for a similar input to Script (and maybe Project?) so that we can benefit from jedi introspection of those pre-imported modules.

I suspect there may already be a way to do this (monkey-patching/subclassing Script, something about stubs, a plugin acknowledging updates could be a challenge), buy I'm having trouble making sense of it.

**Comment by davidhalter** [comment]
> --builtins flag

What does that do?

> I suspect there may already be a way to do this (monkey-patching/subclassing Script, something about stubs, a plugin acknowledging updates could be a challenge), buy I'm having trouble making sense of it.

There are two things that you might be missing: `jedi.settings.auto_import_modules` and `Project(load_unsafe_extensions=True)`. Does that help?

**Comment by btyoung** [comment]
If I run ``flake8 script.py`` on a script that reads ``time = Epoch('1-Jan-2000 ET')`` it will flag an error that ``Epoch`` is not defined.  If I run ``flake8 --builtins Epoch script.py``, it will pass.  In the context of Jedi, I'd want it to know that Epoch is a class from the Monte module so that introspection could work properly (i.e. pretend that 'from Monte import *' is at the top).

I thought I had looked at auto_import_modules and thought it was just about pre-caching some imports for dynamic imports and speed, which is different than me wanting to use scripts that skip the import and expect a class/function to still exist.

**Comment by davidhalter** [comment]
Sorry, but that use case is not supported and will not be supported (it's literally the first time somebody wants that in 10+ years).
