### ISSUE TITLE
Test failures with Python 3.12

### ISSUE THREAD

**Issue by hugovk** [davidhalter/jedi#1955]
The [second Python 3.12 release candidate](https://discuss.python.org/t/python-3-12-0rc2-final-release-candidate-released/33105/5?u=hugovk) is out! :rocket:

> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.

Python 3.12.0 final is due out in two weeks: [2023-10-02](https://peps.python.org/pep-0693/).

See also https://dev.to/hugovk/help-test-python-312-beta-1508/

---

However, adding 3.12 to the CI like in https://github.com/hugovk/jedi/commit/7e5d82113a10a1eaeb04228a9919322cedc29b24 results in [three failed tests](https://github.com/hugovk/jedi/actions/runs/6207769604):

```pytb
=================================== FAILURES ===================================
________________________ TestSetupReadline.test_import _________________________

self = <test.test_utils.TestSetupReadline testMethod=test_import>

    def test_import(self):
        s = 'from os.path import a'
        assert set(self.complete(s)) == {s + 'ltsep', s + 'bspath'}
        assert self.complete('import keyword') == ['import keyword']
    
        import os
        s = 'from os import '
        goal = {s + el for el in dir(os)}
        # There are minor differences, e.g. the dir doesn't include deleted
        # items as well as items that are not only available on linux.
        difference = set(self.complete(s)).symmetric_difference(goal)
        difference = {
            x for x in difference
            if all(not x.startswith('from os import ' + s)
                   for s in ['_', 'O_', 'EX_', 'MFD_', 'SF_', 'ST_',
                             'CLD_', 'POSIX_SPAWN_', 'P_', 'RWF_',
                             'SCHED_'])
        }
        # There are quite a few differences, because both Windows and Linux
        # (posix and nt) librariesare included.
>       assert len(difference) < 30
E       AssertionError: assert 39 < 30
E        +  where 39 = len({'from os import CLONE_FILES', 'from os import CLONE_FS', 'from os import CLONE_NEWCGROUP', 'from os import CLONE_NEWIPC', 'from os import CLONE_NEWNET', 'from os import CLONE_NEWNS', ...})

test/test_utils.py:88: AssertionError
______________________ test_create_environment_executable ______________________

    def test_create_environment_executable():
>       environment = create_environment(sys.executable)

test/test_api/test_environment.py:116: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
jedi/api/environment.py:365: in create_environment
    _assert_safe(path, safe)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

executable_path = '/opt/hostedtoolcache/Python/3.12.0-rc.2/x64/bin/python'
safe = True

    def _assert_safe(executable_path, safe):
        if safe and not _is_safe(executable_path):
>           raise InvalidPythonEnvironment(
                "The python binary is potentially unsafe.")
E           jedi.api.environment.InvalidPythonEnvironment: The python binary is potentially unsafe.

jedi/api/environment.py:411: InvalidPythonEnvironment
_______________________________ test_next_docstr _______________________________

inference_state = <jedi.inference.InferenceState object at 0x7f00c1f6b680>

    def test_next_docstr(inference_state):
        next_ = compiled.builtin_from_name(inference_state, 'next')
        assert next_.tree_node is not None
        assert next_.py__doc__() == ''  # It's a stub
        for non_stub in _stub_to_python_value_set(next_):
>           assert non_stub.py__doc__() == next.__doc__
E           AssertionError: assert 'next(iterato...topIteration.' == 'Return the n...topIteration.'
E             - Return the next item from the iterator.
E             + next(iterator[, default])
E               
E             - If default is given and the iterator is exhausted,
E             + Return the next item from the iterator. If default is given and the iterator
E             - it is returned instead of raising StopIteration.
E             + is exhausted, it is returned instead of raising StopIteration.
E             ? ++++++++++++++

test/test_inference/test_compiled.py:34: AssertionError
=========================== short test summary info ============================
FAILED test/test_utils.py::TestSetupReadline::test_import - AssertionError: assert 39 < 30
 +  where 39 = len({'from os import CLONE_FILES', 'from os import CLONE_FS', 'from os import CLONE_NEWCGROUP', 'from os import CLONE_NEWIPC', 'from os import CLONE_NEWNET', 'from os import CLONE_NEWNS', ...})
FAILED test/test_api/test_environment.py::test_create_environment_executable - jedi.api.environment.InvalidPythonEnvironment: The python binary is potentially unsafe.
FAILED test/test_inference/test_compiled.py::test_next_docstr - AssertionError: assert 'next(iterato...topIteration.' == 'Return the n...topIteration.'
  - Return the next item from the iterator.
  + next(iterator[, default])
    
  - If default is given and the iterator is exhausted,
  + Return the next item from the iterator. If default is given and the iterator
  - it is returned instead of raising StopIteration.
  + is exhausted, it is returned instead of raising StopIteration.
  ? ++++++++++++++
====== 3 failed, 3724 passed, [156](https://github.com/hugovk/jedi/actions/runs/6207769604/job/16853293060#step:6:157) skipped, 5 xfailed in 106.94s (0:01:46) ======
```

**Comment by PeterJCLaw** [comment]
The `TestSetupReadline::test_import` failure seems to be due to increasing platform differences; I've put a fix for that in https://github.com/davidhalter/jedi/pull/1956/commits/254aefd8ebfea745b86543167682766830e94bed.

The `test_next_docstr` failure looks like it's maybe to do with the docstring of that function changing in Python 3.12. @davidhalter would be good to get your thoughts on what the right solution is for this one (I'm not clear what the test is validating).

The `InvalidPythonEnvironment` error seems to only reproduce in GitHub Actions -- I'm not seeing that locally. I'm not sure why it should be specific to Python 3.12, though evidently it is. Will keep digging on this.

Overall though the fact that the tests for 3.12 source under 3.12 runtime pass in CI (and these issues feel to me like test issues) suggests that Jedi is mostly in a good place for 3.12 support.

**Comment by PeterJCLaw** [comment]
> The `InvalidPythonEnvironment` error seems to only reproduce in GitHub Actions -- I'm not seeing that locally. I'm not sure why it should be specific to Python 3.12, though evidently it is. Will keep digging on this.

This looks like it was a result of Jedi not knowing that 3.12 was a valid version; https://github.com/davidhalter/jedi/pull/1956/commits/770cdade00dfdd5114f55f6d4a40a88bee315140 should fix that.

> Overall though the fact that the tests for 3.12 source under 3.12 runtime pass in CI

I was wrong about this; the 3.12-on-3.12 tests weren't included in the linked CI run. It looks like these are also failing.

> these issues feel to me like test issues

Despite the above corrections, this is still true.

---

There are two other sets of failures:
- things related to the docstring & signature for `next` (which feel like they're a result of the docs for that function having changed)
- a test around Django stubs which seems broken to Django<3.1 (which we pin to) not fully supporting Python 3.12 yet (#1959 will hopefully address this)

**Comment by davidhalter** [comment]
Answered in your pull request https://github.com/davidhalter/jedi/pull/1956. I'm pretty sure you're almost done. Thanks a lot for taking care of this!!

**Comment by davidhalter** [comment]
Just FYI, because I forgot about it: The `next` issues were caused by CPython changes that are kind of a regression, see this https://github.com/python/cpython/issues/107526 CPython issue.
