### ISSUE TITLE
Jedi.names is not working

### ISSUE THREAD

**Issue by mohamedayman15069** [davidhalter/jedi#1967]
Hello, 
Thank you for this important Tool. Now, I am encountring a big issue. The code was working some time with jedi.names. Now, It is not working, however.
The Error: 
 generate_one_file
    all_names = jedi.names(line, all_scopes=True, definitions=True, references=True)
AttributeError: module 'jedi' has no attribute 'names'

**Comment by davidhalter** [comment]
Version?

**Comment by mohamedayman15069** [comment]
jedi                      0.17.0

**Comment by davidhalter** [comment]
Please upgrade.
