### ISSUE TITLE
Missing docstring for pandas functions

### ISSUE THREAD

**Issue by lukelbd** [davidhalter/jedi#1968]
**Originally posted [here](https://github.com/python-lsp/python-lsp-server/issues/477).**

Overview
---------

Currently when I help info for the [`read_csv`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)  or [`read_table`](https://pandas.pydata.org/docs/reference/api/pandas.read_table.html) [pandas](https://pandas.pydata.org/docs/index.html) functions, the docstring help is missing, even though it is present on `pd.read_csv.__doc__` or `help(pd.read_csv)` within a python session (see below).

Strangely, this issue does not occur for other pandas functions e.g. [`read_fwf`](https://pandas.pydata.org/docs/reference/api/pandas.read_fwf.html), so it must be something particular to the docstring implementation on those two functions. If it helps here's the [`read_csv`](https://github.com/pandas-dev/pandas/blob/v2.1.2/pandas/io/parsers/readers.py#L848-L948) and [`read_fwf`](https://github.com/pandas-dev/pandas/blob/v2.1.2/pandas/io/parsers/readers.py#L1285-L1393) source.

Is there any way `jedi` can be improved to cover their docstring implementation and consistently capture the `__doc__` text? Thanks!

Versions
---------
```sh
jedi                      0.18.0             py310h2ec42d9_3      conda-forge
pandas                    1.4.2              py310h514ec25_1      conda-forge
python                    3.10.12            had23ca6_0_cpython   conda-forge
python-lsp-server         1.8.2              pyhd8ed1ab_0         conda-forge
python-lsp-server-base    1.8.2              pyhd8ed1ab_0         conda-forge
```

Current behavior
-----------------

`read_csv` docstring:

<img width="850" alt="Screenshot 2023-11-01 at 12 29 53" src="https://github.com/python-lsp/python-lsp-server/assets/19657652/688af547-d6b8-4cae-ba58-f4b630423c58">

`read_csv` in jedi/pylsp:

```python
In [4]: import jedi; jedi.Script("import pandas as pd; pd.read_csv").help(column=30, line=1)[0].docstring(raw=True)
Out[4]: ''
```

<img width="850" alt="Screenshot 2023-11-01 at 12 28 56" src="https://github.com/python-lsp/python-lsp-server/assets/19657652/50f51314-d77f-40ae-a238-fde40684460b">

Desired behavior
-----------------

`read_fwf` docstring:

<img width="850" alt="Screenshot 2023-11-01 at 12 30 07" src="https://github.com/python-lsp/python-lsp-server/assets/19657652/fca4f8e4-1c68-4ca3-a2ba-b2d66899626b">

`read_fwf` in jedi/pylsp:

```python
In [3]: import jedi; jedi.Script("import pandas as pd; pd.read_fwf").help(column=30, line=1)[0].docstring(raw=True)
Out[3]: "Read a table of fixed-width formatted lines into DataFrame.\n\nAlso supports optionally iterating or breaking of the file\ninto chunks.\n\nAdditional help can be found in the `online docs for IO Tools\n<https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.\n\nParameters\n----------\nfilepath_or_buffer : str, path object, or file-like object\n    String, path object (implementing ``os.PathLike[str]``), or file-like\n    object implementing a text ``read()`` function.The string could be a URL.\n    Valid URL schemes include http, ftp, s3, and file. For file URLs, a host is\n    expected. A local file could be:\n    ``file://localhost/path/to/table.csv``.\ncolspecs : list of tuple (int, int) or 'infer'. optional\n    A list of tuples giving the extents of the fixed-width\n    fields of each line as half-open intervals (i.e.,  [from, to[ ).\n    String value 'infer' can be used to instruct the parser to try\n    detecting the column specifications from the first 100 rows of\n    the data which are not being skipped via skiprows (default='infer').\nwidths : list of int, optional\n    A list of field widths which can be used instead of 'colspecs' if\n    the intervals are contiguous.\ninfer_nrows : int, default 100\n    The number of rows to consider when letting the parser determine the\n    `colspecs`.\n**kwds : optional\n    Optional keyword arguments can be passed to ``TextFileReader``.\n\nReturns\n-------\nDataFrame or TextFileReader\n    A comma-separated values (csv) file is returned as two-dimensional\n    data structure with labeled axes.\n\nSee Also\n--------\nDataFrame.to_csv : Write DataFrame to a comma-separated values (csv) file.\nread_csv : Read a comma-separated values (csv) file into DataFrame.\n\nExamples\n--------\n>>> pd.read_fwf('data.csv')  # doctest: +SKIP"
```

<img width="850" alt="Screenshot 2023-11-01 at 12 29 15" src="https://github.com/python-lsp/python-lsp-server/assets/19657652/a204c76d-2567-47dd-80e4-d476c1e476ae">

**Comment by davidhalter** [comment]
The issue here is that the docstring of `read_csv` is generated during runtime and not an actual docstring: https://github.com/pandas-dev/pandas/blob/a60ad39b4a9febdea9a59d602dad44b1538b0ea5/pandas/io/parsers/readers.py#L848-L860
So there is no way static analysis is going to be able to help here. 

The `read_fwf` function has a proper docstring, that's why it works.
