### ISSUE TITLE
Enum name auto-completion without parentheses

### ISSUE THREAD

**Issue by jhonabreul** [davidhalter/jedi#1974]
`python.analysis.completeFunctionParens` setting allows to enable/disable whether parentheses are added on function/class name auto-completion, including enums.

It could be a good feature to have a setting that enables this for classes/functions only, excluding enums. I know enums are classes in Python, but it would be a good thing not to have to remove the added parentheses after an enum name is auto-completed but keep that behaviour for classes and functions

**Comment by davidhalter** [comment]
After a small test, this is not a Jedi issue. Jedi has such  a setting, but it only completes functions. The `completeFunctionParens` is probably a custom implementation of jedi-language-server or something like that. If you really feel like this is a Jedi issue, please try to write a reproducer with Jedi only.

Sorry I could not help. But this is probably an upstream issue.
