### ISSUE TITLE
Does Jedi support type inference for type annotations that include generics?

### ISSUE THREAD

**Issue by WutingjiaX** [davidhalter/jedi#1992]
I have an example like this：
```
from dataclasses import dataclass
from typing import Dict

@dataclass
class MyClass:
    id_to_name: Dict[int, str]

my_instance = MyClass(id_to_name={1: "Alice", 2: "Bob"})
my_instance.id_to_name
```
then I want to infer the type of id_to_name with infer() API。But the result is：
![image](https://github.com/davidhalter/jedi/assets/152422088/c9b168fe-6e49-4ab9-9aec-be10ae0edd93)

It loses the generic info。

update：
I find that to access some protected Attribute，I can get generic info，like this：
![img_v3_02ae_5b593dca-54e3-4b8e-a878-9b27b3bf60dg](https://github.com/davidhalter/jedi/assets/152422088/dd6f06d0-95b7-4e76-bcc0-54a1df656494)

But why wasn't this information serialized into the name or full_name fields?

**Comment by davidhalter** [comment]
I assume however that `my_instance.id_to_name[0]` is working though? Jedi does not currently give you the generics as part of full_name or anything else. That's just a visual limitation. However AFAIK generics should still work in that case for autocompletion/type inference.

**Comment by WutingjiaX** [comment]
thx~
