### ISSUE TITLE
Some simple Not expressions cannot infer types

### ISSUE THREAD

**Issue by WutingjiaX** [davidhalter/jedi#2015]
the code is:
```
a = {}
res = not a
```
jedi can't infer the type of **res**

The root cause is the following code snippet：
```
def infer_factor(value_set, operator):
    """
    Calculates `+`, `-`, `~` and `not` prefixes.
    """
    for value in value_set:
        if operator == '-':
            if is_number(value):
                yield value.negate()
        elif operator == 'not':
            b = value.py__bool__()
            if b is None:  # Uncertainty.
                return
            yield compiled.create_simple_object(value.inference_state, not b)
        else:
            yield value
```

Because b is None and just return without do anything. I'm not familiar with the reason of # Uncertainty. But by the over-infer, 
Would it be better to return a bool type ？

**Comment by davidhalter** [comment]
Yes that would also be fine.

**Comment by WutingjiaX** [comment]
I glad to create a PR for this issue. But I'm not familiar with how to create a "bool" type. In most other case, it will return a _compiled_ value that means _True/False/[True, False]_. 

Does just returning `_bool_to_value(value.inference_state, True)` in this place have any side effects?(though It will finally be converted to bool in `_stub_to_python_value_set`)

**Comment by davidhalter** [comment]
I think `self.inference_state.builtins_module.py__getattribute__('bool').execute_anotation()` should probably do the job. But it's been a while.

While you're at it: Could you change the case where you changed the inference for `x in y` as well to the same code?
