### ISSUE TITLE
Sort completions so that the one most resembling the typing code comes first

### ISSUE THREAD

**Issue by hongquan** [davidhalter/jedi#2017]
With this example code:

```py
from logbook import Logger


logger = Logger(__name)
```

Every time I type: `logg`, Jedi will return

```
Logger
logger
```

whereas I expect:

```
logger
Logger
```

**Comment by davidhalter** [comment]
Where should the order be different? And how would we know which one to sort first?

**Comment by hongquan** [comment]
The difference is:
- Current behavior:

```
Logger (uppercase first)
logger
```
- My expect:

```
logger (lowercase first)
Logger 
```

Because I'm typing `logg` (lowercase), I expect the lowercase suggestion comes first. It it comes later, I have to type more to navigate to it.

**Comment by hongquan** [comment]
I added a PR with a test case  to demonstrate my idea better.
