### ISSUE TITLE
Missing completions when using auto_import_modules

### ISSUE THREAD

**Issue by FlorianKroiss** [davidhalter/jedi#2021]
Hi, 

I'm using jedi via python-lsp-server, which uses `jedi.settings.auto_import_modules = ["numpy"]` by default.
Using this setting, I get no completions on `import numpy.`, however, I do get completions on `from numpy import `, which seems odd.

Maybe as a small reproducing example:
```python
import jedi

jedi.settings.auto_import_modules = ["numpy"]
script = jedi.Script("from numpy import ")
print(f"{len(script.complete())=}")

script = jedi.Script("import numpy.")
print(f"{len(script.complete())=}")
```
This prints 
```
len(script.complete())=591
len(script.complete())=0
```

Removing the line `jedi.settings.auto_import_modules = ["numpy"]` prints:
```
len(script.complete())=615
len(script.complete())=30
```

Is this working as intended?

I'm using jedi==0.19.1 and numpy==1.26.3

**Comment by davidhalter** [comment]
Why do you need to use `import numpy.`? It fundamentally does something else than `from numpy import `.

I think I'm going to close, because if you use `jedi.settings.auto_import_modules = ["numpy"]`, you are actually trying to disable parts of Jedi and this is not expected to work after it.

**Comment by FlorianKroiss** [comment]
Ok, I wasn't exactly sure what `jedi.settings.auto_import_modules`, but that seems fair
