### ISSUE TITLE
environment._try_get_same_env does not handle msys2

### ISSUE THREAD

**Issue by liltaylor** [davidhalter/jedi#2029]
Starting at line 211 of environment.py the system is checked for the presence of a python executable. The executable path is guessed based on the operating system. In case os.name is 'nt' only the cases 'Script\python.exe'  and 'python.exe' (with no path) are checked. 

Alas, in case one is running python in Windows from an installation on msys2, os.name is still 'nt' but the installation is "unix style" so the path to the python executable is actually 'bin/python'. 

Please check unix style installation paths also in the Windows case.

**Comment by davidhalter** [comment]
I feel like that's fine. If you want to work within obscure environments, you should just provide the environment path yourself.
