### ISSUE TITLE
Autocorrect bug when completing files names in Code OSS-based IDEs

### ISSUE THREAD

**Issue by jthomasmock** [davidhalter/jedi#2032]
When using Jedi as the Language Server in Code OSS-based IDEs or in VS Code, auto-complete of file names at the `.` is incorrect. 

The text is auto-completed at the `.` instead of replacing the prior text.

Thank you for your time in reviewing this issue.

As an example, see the video below in VS Code with Jedi as the Language Server:

https://github.com/user-attachments/assets/3b6cf2eb-f419-4bfa-82e1-e4356745b3c1

**Comment by PeterJCLaw** [comment]
Are you sure this is a Jedi issue rather than an issue with the Language Server implementation? Jedi is just the parsing/suggestions library and doesn't (as far as I know) handle any of the UI stuff, including handling once a given suggestion has been chosen by the user.

**Comment by jthomasmock** [comment]
That is possible, but I couldn't reproduce the issue with Pylance as I don't believe it has file auto-completion out of the box?

**Comment by davidhalter** [comment]
Can you please file this against https://github.com/pappasam/jedi-language-server? It's kind of hard to help you here. Not sure why this happens, but it doesn't feel like a Jedi issue.

**Comment by jthomasmock** [comment]
I will close this in favor of https://github.com/pappasam/jedi-language-server/issues/325 unless it's determined to be in Jedi proper.

My apologies for the churn on this repo!
