### ISSUE TITLE
Few tests fails with the `pkg` installed

### ISSUE THREAD

**Issue by mtelka** [davidhalter/jedi#2034]
I assume this is OpenIndiana (or illumos/Solaris) specific.

When there is the `pkg` Python package installed (which is our package manager, so it is always installed) the following tests fails:
```
test/test_api/test_classes.py::test_inheritance_module_path
test/test_inference/test_imports.py::test_correct_zip_package_behavior
test/test_inference/test_imports.py::test_find_module_package_zipped
test/test_inference/test_imports.py::test_zip_package_import_complete
```

When I do this:
```
mv /usr/lib/python3.9/vendor-packages/pkg{,.save}
```
then all above tests pass.

Could you please consider to make tests to pass even with the `pkg` installed?

Thank you.

**Comment by davidhalter** [comment]
Feel free to send a PR that fixes this for your specific usecase. You can just rename `test/examples/pkg` and change all related tests. However I don't have the time to do this now and I doubt somebody else will, so I'm closing.

But I am happy to merge a pull request.
