### ISSUE TITLE
Broken inheritance diagram in current documentation

### ISSUE THREAD

**Issue by bluthej** [davidhalter/jedi#2041]
While going through the documentation, I noticed that [this section](https://jedi.readthedocs.io/en/latest/docs/development.html#module-jedi.inference.base_value) of the online docs was broken. I was able to reproduce that locally, and found that I was missing the `dot` executable, because I installed `graphviz` with `pip` instead of my package manager it seems. After installing it with my package manager I did recover the graph.

So I'm thinking `dot` wasn't accessible on whatever machine was used to build the docs. Note that this is has been the case since version `0.19.2`, so the stable version of the documentation is also affected by this.

**Comment by davidhalter** [comment]
Yeah, feel free to send a pull request if you are able to fix it.
