### ISSUE TITLE
Suggestion: automated type checking at debug/test time (Also: Improve documentation about debugging Jedi)

### ISSUE THREAD

**Issue by tkf** [davidhalter/jedi#236]
I found it is hard to debug Jedi.  One of the reason is that what function takes and returns is unclear.

Duck typing is good, but it is not helping debugging when you hit attribution error and find out that wrongly typed object is passed to the function at three frames up.

The idea is to activate type checking decorator only when debugging and testing, using something like this:
```py
import os


def debugging(*decos):
    def decorator(func):
        if os.environ.get('JEDI_DEBUG'):
            for d in decos:
                func = d(func)
        # func is uncharged if $JEDI_DEBUG is not set
        return func
    return decorator
```

And then we can use it like this (The type checking decorators below are only for demonstration [1]):
```py
def takes(type):
    def decorator(func):
        def wrapper(i):
            assert isinstance(i, type)
            return func(i)
        return wrapper
    return decorator


def returns(type):
    def decorator(func):
        def wrapper(*args, **kwds):
            r = func(*args, **kwds)
            assert isinstance(r, type)
            return r
        return wrapper
    return decorator


@debugging(takes(int), returns(float))
def sample(i):
    return i * 1.0


sample(1)
sample(1.0)   # error!
```

Unlike the normal usage of the type checking decorator (`sample_0` below), there is no runtime penalty if `$JEDI_DEBUG` is not set.
```py
@takes(int)
@returns(float)
def sample_0(i):
    return i * 1.0
```

The bonus is that it acts as "documentation" for developers.

My speculation could be wrong.  Probably we just have to refactor it more and document it more.  But I also think that we could get some benefit from automated type checking for complex project like Jedi.  What do you think?

[1] For type checking decorator I found this: http://code.activestate.com/recipes/426123-method-signature-checking-decorators/.  The license is BSD so I guess it is OK to include in LGPL software.  I've never used this so I'd like to see other suggestions.

**Comment by davidhalter** [comment]
There's quite a bit of documentation now.
