### ISSUE TITLE
iterators + strings + getattr completion

### ISSUE THREAD

**Issue by dbrgn** [davidhalter/jedi#24]
``` python
class FooBar(object):
    raboof = 'fourtytwo'

target = u'' 
for char in reversed(['f', 'o', 'o', 'b', 'a', 'r']):
    target += char

answer = getattr(FooBar, target)
answer.<tab>
```

...doesn't work. Jedi sucks so much.

**Comment by MathieuDuponchelle** [comment]
I need closure, did you *actually* get that pint ?

**Comment by davidhalter** [comment]
NO! :D

**Comment by MathieuDuponchelle** [comment]
Awwww

**Comment by dbrgn** [comment]
Arrgh @MathieuDuponchelle, why did you bring that up :(

@davidhalter remind me next time we meet :D

**Comment by hashier** [comment]
5 years later, did we get a happy ending and a pint of Murphy's?

**Comment by dbrgn** [comment]
Good call! I added an entry to my calendar on June 1st: "Invite @davidhalter in case the pandemic has faded away".

**Comment by davidhalter** [comment]
I like this thread :D

----- 

He didn't even bring a pint of Murphy's to my wedding :)

**Comment by dbrgn** [comment]
Well, YOU on the other hand you didn't even offer your guests a chair, we had to sit on the floor!!!

---

*(PS: To be precise, we sat on pillows on a meadow and it was awesome!)*

*(PPS: This @davidhalter guy even forced all his guests sing "Bohemian Rhapsody" in full length before we were allowed to eat!)*

*(PPPS: I also like this thread 😄)*

**Comment by hashier** [comment]
Since I saw Threema in your profile @dbrgn maybe there is a > 0 % chance that you and @davidhalter every go to the CCC (Chaos Communication Congress)? If the pandemic every fades out and you go, I would offer free friendship counseling over some Murphies or Mate that I would provide. I think what you have is worth fighting for! <3 Don't just throw it away.

**Comment by davidhalter** [comment]
@hashier I'm usually not at CCC, I'm just watching the talks :). @dbgrn has attended at least once AFAIK. But if you're ever in Zurich let us know (or if I'm ever in Oslo I will let you know) :).

**Comment by Anu-bhav** [comment]
Man this is like a running meme, I was reading the documentation and I came here to find this still active. 😂👍

**Comment by pvgmenegasso** [comment]
Those little gold nuggets you find lying around in issue discussions.

**Comment by dbrgn** [comment]
￼

It really happened!

**Comment by davidhalter** [comment]
Simple Feature: Takes 2 years to implement
Management: Delays payment for 8 years

Thanks Danilo! :)

**Comment by MathieuDuponchelle** [comment]
Finally! Closure
