### ISSUE TITLE
Complete pytest

### ISSUE THREAD

**Issue by dbrgn** [davidhalter/jedi#257]
Completion in pytest does not work.

```
In [1]: import jedi

In [2]: jedi._quick_complete('import pytest; pytest.')
Out[2]: 
[<Completion: cmdline>,
 <Completion: main>,
 <Completion: pytest>,
 <Completion: UsageError>,
 <Completion: _preloadplugins>,
 <Completion: __all__>,
 <Completion: __version__>]
```

There are many attributes missing:

```
In [3]: import pytest

In [4]: pytest.
pytest.Class            pytest.Instance         pytest.cmdline          pytest.fixture          pytest.set_trace
pytest.Collector        pytest.Item             pytest.collect          pytest.importorskip     pytest.skip
pytest.File             pytest.Module           pytest.deprecated_call  pytest.main             pytest.xfail
pytest.Function         pytest.Session          pytest.exit             pytest.mark             
pytest.Generator        pytest.UsageError       pytest.fail             pytest.raises           
```

**Comment by blueyed** [comment]
@davidhalter 
> pytest uses `__import__`, which is not supported by Jedi.

Is that still the case, or has there been progress in that regard?

> I'm pretty sure that Jedi will never support such a complicated import procedure. I don't know why they have it

AFAIK this is done for the plugin system, which is also used internally.
I could imagine to improve it so that at least the builtin plugins would be completed.

Is there a way to whitelist e.g. this specific module to allow for code execution to discover imports?  (assuming that this is the main issue here)

What about some callback that could be provided to help Jedi here?

**Comment by davidhalter** [comment]
I'm currently on holidays (have been for 2 weeks already), might still take another week until I answer.

**Comment by davidhalter** [comment]
>>  pytest uses `__import__`, which is not supported by Jedi.

> Is that still the case, or has there been progress in that regard?

Yes, that is still the case. However the big difference is that the import logic in Jedi is very similar to Python's. This means that implementing `__import__` would probably not be a lot of work.

I'm not sure if this would really help you, though (for this problem). 

> I could imagine to improve it so that at least the builtin plugins would be completed.

What would be your plan? 

> Is there a way to whitelist e.g. this specific module to allow for code execution to discover imports? (assuming that this is the main issue here)

There's currently no whitelist. Well, maybe there is. But I'm not sure if `setings.auto_import_modules` is the right point to start. 

> What about some callback that could be provided to help Jedi here?

Well, tell me what you need and we talk :)
