### ISSUE TITLE
Look at doctests

### ISSUE THREAD

**Issue by asmeurer** [davidhalter/jedi#279]
I would suggest combining the ideas from docstrings.py and dynamic.py to look at doctests to guess parameter and return types.  Some potential issues:

- Should all docstrings in a file be searched parsed, or only the one for the function in question? 

- We could attempt to use the output of the docstrings, but it's tricky, because it is the string form, so 

```
>>> a(1)
2
```

could mean that `a(2)` returned `2`, or it could mean that it returned some object whose string form is `"2"`. 

- There are different conventions for doctests:

1. The doctest is run in the scope of the module containing the function. 

2. The doctest is run in a scope of its own (this is how the SymPy doctests work)

3. The doctest is run in some special scope (I guess this is how the NumPy doctests work, because they all reference names like `np`, which are defined neither in the doctest nor in the source file). 

I guess `python -m doctest` defaults to the first way. 

Unless you foresee any major issues that might come up, I can take a shot at implementing this.

**Comment by davidhalter** [comment]
I doubt I'll ever implement this. This is something that would be nice, but is at the same time simply not having the impact I would like it to have.

If someone still wants to implement this, I'm fine with it. I won't do it however. There so many things that help completion more than this issue.
