### ISSUE TITLE
REPL completion doesn't complete keyword arguments

### ISSUE THREAD

**Issue by asmeurer** [davidhalter/jedi#292]
Keyword arguments for functions aren't completed in the repl completion.

**Comment by davidhalter** [comment]
I hope (and I'm pretty confident) that we can tackle this in the `0.11.0`.

This issue has a lot of side issues that need to be tackled first, with the main issue being compatibility with 3.5/3.6's `inspect.signature` (which is what I would be using).

**Comment by Carreau** [comment]
Subscribing. Thanks !

**Comment by davidhalter** [comment]
Ok. It's finally working in Python 3. Python 2 does not support inspect.signature and I'm too lazy to reimplement that (people should just switch anyway).

At this point in time it's the fifth oldest open jedi issue :)
