### ISSUE TITLE
Cannot see attribs of class when defined dinamically

### ISSUE THREAD

**Issue by Alexey-T** [davidhalter/jedi#301]
code

	import sys
	import time
	import os

	class Info():
		pass
	info = Info()    
	info.debug = False
	info.time = time.time()
	info.fn = sys.argv[1]
	info.datadir = os.path.dirname(__file__)

now i call autocomplete after "info." and DON'T see my attribs. i mean attribs debug/time/fn/datadir.

**Comment by davidhalter** [comment]
It will not be fixed for now. I know this and if I ever have the time I'll try to fix it.
