### ISSUE TITLE
Provide Base Class Info in goto_definitions

### ISSUE THREAD

**Issue by blink1073** [davidhalter/jedi#324]
It would be nice to get the base class(es) for documenting a class, for example, `OrderedDict(dict)`.  This functionality used to exist as a public variable, but is now private.  Spyder currently has this functionality.

```python
>>> import jedi
>>> code = 'from collections import OrderedDict'
>>> script = jedi.Script(code, 1, len(code))
>>> defn = script.goto_definitions()[0]
>>> defn.doc
u'OrderedDict(self, *args, **kwds)\n\nDictionary that remembers insertion order'
>>> supers = defn._definition.base.supers
>>> supers
[<Param: dict @25,18>]
```

**Comment by davidhalter** [comment]
BTW: If you want to have this now, this should be really easy to do:

Something like this would do it, but would need testing:

```
class Definition():
    [...]
    def supers(self):
        try:
            return [Definition(self._evaluator, c) for c in self._definition.py__classes__(self._evaluator)]
        except AttributeError:
            return None  # Maybe that's not a good idea to return None and we should throw an AttributeError.
    [...]
```

Just if you're still interested in this feature. I won't do it, because I don't need it right now.

**Comment by blink1073** [comment]
I think we're getting along fine without it.  You can feel free to close this one if you like.
