### ISSUE TITLE
Normal memory usage?

### ISSUE THREAD

**Issue by spillz** [davidhalter/jedi#335]
I have a long-running python jedi process controlled by Code::Blocks IDE. I have noticed that when working with big libraries like numpy or pandas that each time I retrieve a completion hint or call tip on one of those modules anywhere between 0 and 2MB of memory is swallowed and apparently never freed. I can easily have a process running jedi on only those libs that consumes a couple of hundred MBs. 

1. Is that expected memory usage?
2. Is there any way to free some of the memory being used short of killing the process without also hurting performance?

PS: I should caveat that it's possible that jedi isn't the offender here, but something in my implementation, but thought I would check to see what's considered normal.

**Comment by davidhalter** [comment]
Memory usage should be much better now and nobody has complained in a long time.

**Comment by b52** [comment]
It's still an issue. I use jedi in Atom using `autocomplete-python` and it happens to freeze my PC from time to time because it uses all my 16GB of RAM.

The code I write is mostly using the SciPy stack, e.g., scipy, numpy, SimpleITK, etc.

**Comment by davidhalter** [comment]
Which Jedi version?

**Comment by Viele** [comment]
I also have this problem of a python process all of a sudden taking up all 24gb of ram.
I've tried Sublime with anaconda and Atom with autocomplete-python. Both use Jedi.
The problem arises when I add an extra path in the package, pointing to my Autodesk Maya 2017 devkit code completion folder. In there are just 60mb of stub files for autocompletion (pyMel, PySide2 and OpenMaya)

then when I want to use the autocomplete, a python process starts that takes up all memory and writes cache files to \AppData\Roaming\Jedi. It stops when there are about 12GB of cache files, with python then still taking ~3GB of ram.
Win10
version is 0.10.0

**Comment by davidhalter** [comment]
Oh gosh. That is unfortunate. Can you open a new ticket about this? It's not really related to the original issue.

I can see the problems you are facing and I think there should be a limit of how many files Jedi crawls.
