### ISSUE TITLE
get_code() fidelity

### ISSUE THREAD

**Issue by ganwell** [davidhalter/jedi#346]
I started this discussion via email, so we start right in the middle :-)

I want to write a re-factoring based on AST transformation. So it is important that get_code() will reproduce original formatting 100% accurate, or people will hate the re-factoring.

I noticed that get_code() is quite sloppy, so we agreed that I rewrite get_code. It will use the start_pos and token_lists to recreate the code. I also noticed that not everything we need has a token_list and start_position. For example docstrings are missing it. We already agreed that I add this functionality. So here is my proposal:

Could we make string literals a representation object? So we can place it in the docstring member. I would implement ```__str__()``` so we don't break existing code. The string literal object would have a start_position and maybe some other meta information like line-count. I would even place it in the token_lists (if it doesn't break too much). At the moment string literals are just plain token-tuples. (see below)

```python
    
    code_basic_features = '''
    def a_function(a_argument, a_default = "default"):
        """A docstring"""
    
        a_string = """What about this?
    <- This I mean"""
        a_result = 3 * a_argument
        print(a_result)  # a comment
        if a_default == "default":
            return str(a_result)
        else:
            return None
    '''
    prs = parser.Parser(code_basic_features)
    scope1 = prs.top_module.subscopes[0]
    freeze.freeze(scope1.statements[0])

->  (('docstr', ''),
     ('_assignment_details', ()),
     ('token_list',
      ((('names',
         ((('parent', 'seen: <Name: a_string@5,4>'), ('_start_pos', (5, 4))),)),),
       (52, '=', (5, 13)),
       (3, '"""What about this?\n<- This I mean"""', (5, 15)))),
     ('_set_vars', None),
     ('as_names', ()),
     ('_names_are_set_vars', False),
     ('_commands', None))
```

**Comment by davidhalter** [comment]
@ganwell get_code() now works very well and produces the code with correct whitespace. This means that this issue has been fixed along the way.

It should be easy now to play with refactoring.
