### ISSUE TITLE
Support for Flask custom import of extensions

### ISSUE THREAD

**Issue by vlevit** [davidhalter/jedi#361]
Flask adds a custom importer to sys.meta_path to import flask extensions in a special way, so that

    import flask.ext

will actually try to import `flask_ext` first and then `flaskext`. You can find the responsible code in the [Flask repo][flask].
Clearly, jedi can't find those extensions imported with `import flask.ext`.
Since support of `sys.meta_path` is likely not possible without the actual code evaluation, I would like to ask is there any good way to make jedi understand such imports.

[flask]: https://github.com/mitsuhiko/flask/blob/master/flask/ext/__init__.py

Have a nice year!

**Comment by davidhalter** [comment]
This was added a long time ago!
