### ISSUE TITLE
Letting Jedi understand swig generated libs

### ISSUE THREAD

**Issue by lorubenet** [davidhalter/jedi#383]
Hi Jedi devs,
Thanks for the great software. It works very nicely for me. 

It has however failed so far to work with swig generated libraries, which is rather bad for my daily work. So I had a look at the code and found that Jedi is prepared to read the comments inside functions. This works however only if these comments are written in Sphynx or Epydoc. 

In swig one can add: 

```
%feature("autodoc", "1");
```

in the XX.i file. This adds the necessary information in the resulting python file for code completion in form of a comment. The format is however different than those supported by Jedi. 

An example of this format is:

``` python
def equal(self, *args):
   """equal(SwigPyIterator self, MyObject other) -> bool"""
```

which is rather easy to parse. (this can be multi line as well with every line a different overload... I haven't spent time on that though)

So I had a look at Jedi's code and found the place where these things get parsed. This is in  'docstrings.py'.
So I did the following change:

``` python
DOCSTRING_PARAM_PATTERNS = [
    r'\s*:type\s+%s:\s*([^\n]+)',  # Sphinx
    r'\s*@type\s+%s:\s*([^\n]+)',  # Epydoc
    r'.*[(,](\w+)%s[,)]',          # swig autodoc
]

DOCSTRING_RETURN_PATTERNS = [
    re.compile(r'\s*:rtype:\s*([^\n]+)', re.M),  # Sphinx
    re.compile(r'\s*@rtype:\s*([^\n]+)', re.M),  # Epydoc
    re.compile(r'.*->\s+(\w+)'),                 # swig autodoc
]
```

where I only added the regexps for swig. 

Now completion works well on my swig generated library. You might want to improve on the regexps before using this code, I'm by no means a guru on them. 

What doesn't work is the completion the first time I run. So if I type (I'm using YCM in (g)vim) "MyObject." gives no completions found. I remove the point and type it again, then it works... a minor glitch I can live with. No idea what can cause this.

**Comment by davidhalter** [comment]
Not sure if it's still an issue, but I'm not going to work on this.

Just use annotations, they are awesome and exactly for this. (and they work!)
