### ISSUE TITLE
Discussion: Jedi wrapper module using server-client architecture to deal with multiprocessing, async interface, multiple Python version, cache lock, etc.

### ISSUE THREAD

**Issue by tkf** [davidhalter/jedi#385]
From https://github.com/davidhalter/jedi/issues/384#issuecomment-37860688 (discussion about multithreading / multiprocessing) and https://github.com/davidhalter/jedi/issues/340#issuecomment-37878924 (discussion about asynchronous interface), I got this idea of creating a "wrapper" module of Jedi with server-client architecture which launches possibly multiple Jedi processes behind the scene, to solve problems such as:
- Multiple Python versions.  Jedi parses Python stdlib and import `*.so` so it is not possible to complete Python 3 modules while running Jedi in Python 2.  However, getting completions for both Python 2 and 3 can be useful when you are writing Python 2/3 compatible module.
- Async interface.  Due to the GIL, and intense computation required by Jedi, it is not feasible to have async interface within Jedi.
- Cache locking/sync:  Jedi does not lock cache files.  Also, when cache is updated in two processes, later one might override the former one.
- Cache update triggered by file modification:  When some modules are updated, Jedi has to wait until next access to update the cache.  If we can trigger cache update by file modification then Jedi can be faster.

If we have a centralized server, a pool of workers and clients to connect to the workers then we can solve the above problems nicely.  I think it is also consistent with a philosophy of keeping Jedi itself minimal and free of external modules.

Client part of this module can expose (blocking) API which is exactly the same as Jedi itself.  Then, every editor can just import this wrapper module instead of Jedi to use it, without much change to the editor plugin.  If the editor has an async support, then it can use async API of this client module.

Maybe my suggestion over complicates the problem, but I think it is worth discussing it anyway, since some problems are better _not_ solved in Jedi.  Delegating these problems to other module can be a good option to consider.

**Comment by fjfnaranjo** [comment]
I will like to add a little information here about jedi-vim so it can be taken into account when anyone starts working on this.

I have been using this https://github.com/nakamuray/jedi-rpc.vim to fix all my problems related to Python+virtualenv version compatibility problems and package discovery in jedi-vim. All credit goes to @nakamuray , of course.

What this little Vim module does is intercepting the jedi-vim interface and run all jedi calls in the current system's python. In other words: If you launch Vim inside an activated Python virtual environment, you can use all the options in jedi-vim with whatever version of Python you have in the venv. The internal Python inside Vim is not used for anything related to jedi or jedi-vim, just by the jedi-rpc adapter.

What I wanted to say is that to keep supporting this kind of schemes it will be nice if the server is able to be launched as a in-environment process. This will allow it to be sensible to whatever tools and libraries can be found in the environment.

I guess jedi already uses a Python 2+3 approach to cover a many cases as possible. If we keep this jedi will be able to adapt completely to the environments.

We can event add support for https://github.com/pypa/pipenv or `.env` files.

Your thoughts about this?

**Comment by davidhalter** [comment]
@fjfnaranjo The virtualenv support is actually kind of finished in the virtualenv branch. There are still possibilities to do what you asked for.

I will try to wrap up that work in the next few days weeks and propose a new API that fixes most of the problems we've had in virtualenvs. The RPC approach might not be bad, but I think just moving builtin evaluation to another library has a lot of advantages.

Generally I don't think that there will be a jedi wrapper module using a server/client architecture in the short future. If anything that will come when Python 2.7/3.3/3.4 are deprecated so asyncio and (async commands) could be used. That's probably speaking about 2021, which means that it's still going to take 3 years - at least.

**Comment by fjfnaranjo** [comment]
@davidhalter Sorry to hear that :( There are lots of ppl using 2.7 and they will miss a good chance to do all the stuff jedi is going to do (I recently read you talking about refactoring ;) ). But I totally understand your position.

I tend to do half of my stuff in PyDev and the other half directly using Vim. The combination of jedi and jedi-vim is something I am very happy to have available. I don't care waiting for the occasional two or three seconds when I deserve them and it keeps my tools up to the modern expectations.

Let me use this opportunity to thank you about your work. It is useful to lots of people and fill an important hole left by the modern IDEs when you switch to a terminal window.

I will wait for the virtualenv branch and test it in my different environments. If I find a good reason to stick to the RPC approach I may try someday to port the jedi-rpc code to the jedi-vim project so it can live there if you wish to adopt it (is quite simple) and the original author doesn't oppose too much.

**Comment by davidhalter** [comment]
I'm not sure if the rpc approach is even needed. What you really want is an approach where you're actually able to continue typing (async completions). I think that would be the big break-through. AFAIK YouCompleteMe has already done that, so there's probably not much of a hurry.

**Comment by dbrgn** [comment]
YCM complete-as-you-type with the Jedi backend (and a server-client model, btw) works really nicely.

**Comment by davidhalter** [comment]
Most of the issues here are fixed or not really an issue.

> Multiple Python versions. 

This is very much possible now. Please use https://jedi.readthedocs.io/en/latest/docs/api.html#environments. 

> Async interface.

Jedi will stay synchronous for now. I don't see the advantage in creating a third-party async framework for Jedi. Jedi is mostly CPU-bound. Using async/await won't help at all. Since Python has the GIL only separate processes really help. For this the easiest way is probably using Microsoft's Language Server Protocol. It might not be feature complete, but it has a lot to offer. There are a few competing implementations. The palantir version is probably the most mature, but I haven't looked into it.

- https://github.com/palantir/python-language-server
- https://github.com/pappasam/jedi-language-server
- https://github.com/sourcegraph/python-langserver (archived)

> Cache locking/sync

While there is currently no cache locking (for pickled cache files), because it's not really a problem. The files are not written/read very often and we haven't had any complaints in years. If this is an issue for you, please open a new issue and let us know.

> Cache update triggered by file modification

This is something that might be interesting in the future. The ticket for this however is #1059. If anything we will look at this at that point.
