### ISSUE TITLE
Jedi + Python3 unable to complete in open file context

### ISSUE THREAD

**Issue by DamnWidget** [davidhalter/jedi#412]
This is happening when Python 3 is used, for example, using Python3 interpreter on this example:

    print(Script('with open("xxx") as fd:\n    for line in fd:\n        line.').completions())

give you back `[]`, no completions but same example using Python2.7 give you back the full string object completions list.

This has been reported in anaconda as well https://github.com/DamnWidget/anaconda/issues/164

Something related with scopes maybe?

**Comment by davidhalter** [comment]
Well, at least now it doesn't work in either Python 2 or 3. Haha.
