### ISSUE TITLE
multiprocessing autocompletion fails with Python 3.4.1 [old: functions named arguments fail...]

### ISSUE THREAD

**Issue by Jiehong** [davidhalter/jedi#432]
IPython currently offers arguments completions of functions. It would be very cool if jedi could offer those completions as well.

Here is an example using Pool whose signature is:  class multiprocessing.Pool([processes[, initializer[, initargs[, maxtasksperchild]]]])

    from multiprocessing import Pool
    Pool(pro

M-x jedi:complete, and you can see the current completions (emacs):
![current completion](https://cloud.githubusercontent.com/assets/1061229/3516341/de496cfe-06df-11e4-9628-f395c1552416.png)

Now, the same in IPython (qtconsole):
![IPython completions](https://cloud.githubusercontent.com/assets/1061229/3516346/ed508714-06df-11e4-97bf-5e4cf1554c11.png)

Could jedi also provide named arguments such as IPython does (displayed as processes= for instance)?

**Comment by davidhalter** [comment]
I don't think understanding `globals().update` is coming to Jedi in the next two years so I'm closing this as "won't fix".
