### ISSUE TITLE
Incorrect linter error

### ISSUE THREAD

**Issue by public** [davidhalter/jedi#446]
There seems to be two bugs going on here?

Given this code

``` python
def f(x):
    return len([]) - 2
```

I get this error

```
/home/alex/code/cryptography/jt.py:2:19: E11 TypeError: unsupported operand type(s) for +: <CompiledObject: <type 'int'>> and <CompiledObject: 2>

```

This code is valid, and the error message doesn't make any sense. There are no `+` operations in this?

**Comment by davidhalter** [comment]
This is fixed now, but please don't report more linter issues. That code is trash and will be refactored at some point or straight on be discontinued.

**Comment by davidhalter** [comment]
This is fixed now, but please don't report more linter issues. That code is trash and will be refactored at some point or straight on be discontinued.
