### ISSUE TITLE
Incorrect "has no attribute" linter errors when using CFFI modules

### ISSUE THREAD

**Issue by public** [davidhalter/jedi#447]
`FFILibrary` objects seem to confuse the linter into thinking they have no attributes. Could this be due to the attributes being set conditionally at run time? The attribute names it uses are parsed out of C source code. I suspect the attributes might actually be bound to the instances inside the cffi CPython extension too.

**Comment by davidhalter** [comment]
For now the linter won't support dynamically set attributes.

Besides: The linter is currently not in active development, I'm using my time to improve other things.
