### ISSUE TITLE
linter doesn't recognize self as an implicit first argument

### ISSUE THREAD

**Issue by asmeurer** [davidhalter/jedi#455]
I'm not sure how to make a smaller example to reproduce this. Maybe the memoize decorator is screwing it up?

With https://github.com/conda/conda/blob/472387e165e6c734af3ef8527529203593376336/conda/logic.py#L120 I get

```
/Users/aaronmeurer/Documents/Continuum/conda/conda/logic.py:120:27: E6 TypeError: Xor() takes from 3 to 4 arguments (3 given).
/Users/aaronmeurer/Documents/Continuum/conda/conda/logic.py:122:27: E6 TypeError: And() takes from 3 to 4 arguments (3 given).
/Users/aaronmeurer/Documents/Continuum/conda/conda/logic.py:124:26: E6 TypeError: Or() takes from 3 to 4 arguments (2 given).
```
- The first error message must be wrong, because "Xor() takes from 3 to 4 arguments (3 given)" should not be an error (3 is between 3 and 4).
- They are all counting arguments wrong. They are counting the arguments including `self` and keyword arguments at the definition, but they don't count `self` when the function is called. This is most clear from the last error about Or(), which is correct (`Or` is `def Or(self, f, g, polarity=None)` and is called as `self.Or(c, f)`.
- I would try to make the error messages match Python's as close as possible, e.g., "TypeError: f() takes from 1 to 2 positional arguments but 3 were given" for `def f(x, y=1)`.

**Comment by davidhalter** [comment]
It looks like this part was fixed along the way. However there are obviously some other issues with the linter (actually a lot of them). I just decided not to follow up with the other errors. The linter is basically dead.

I'm working on rewriting Jedi in Rust and maybe at that point we can use it to find actual errors.
