### ISSUE TITLE
Autocomplete inherited methods when overriding in child class

### ISSUE THREAD

**Issue by kerryz** [davidhalter/jedi#458]
From an [issue from Anaconda](https://github.com/DamnWidget/anaconda/issues/180):

When working with frameworks, a very common pattern is to inherit from a provided class and then overriding the class methods/fields to customize behavior.

When writing this new customized child class, a very helpful tool is the autocomplete-functionality of both the method that I'm trying to override and also the autocompletion of the required arguments. This functionality is provided in IDEs like PyCharm and PyDev.

# Example
```python
from django.db import models
    
class TestModel(models.Model):
    def sav
```

A dropdown should appear here with a suggestion to autocomplete to `save`, and writing a left parenthesis should then generate all the parameters:

```python
class TestModel(models.Model):
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        models.Model.save(self, force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)
```

Maybe an autocompletion to `super(TestModel, self).save(...)` would be better, or not generating the super call at all would also be acceptable (though preferably it should be generated), but this is the behavior in the Eclipse plugin PyDev (a dropdown is generated in which you can choose the option: `save (Override method in models.Model)` when pressing the autocomplete keybinding `CTRL + Space`)

I.e. my suggestion is to make Jedi aware of a cursor being inside a (child) class that is inheriting from another (parent) class, and when trying to override methods *and fields* (defined in the parent class) from within the child class, Jedi should autocomplete the fields and methods and also their arguments.

**Comment by Nahtrezer** [comment]
Sorry for bumping old thread, but feature described by topicstarter would be very useful.
Is there any possibility to turn it on?

**Comment by blueyed** [comment]
@Nahtrezer 
It is not implemented yet, so cannot be turned on.

**Comment by davidhalter** [comment]
Done!

**Comment by blueyed** [comment]
Please note that you need to use Jedi's `dev` branch for this to work in jedi-vim.

**Comment by fx-kirin** [comment]
How to use this feature? I'm using jedi v0.11.1 through jedi-vim, but not autocompleted. I checked commit `647a4db ` is contained in v0.11.1.

    class ParentClass(object):
        def __init__(self, a, b, c):
            pass
            

    class TestClass(ParentClass):
        def __init__{hit ctrl-n here}

I'm currently asking the same question in stackoverflow.

https://stackoverflow.com/questions/49640881/python-super-class-method-auto-completion-or-snippets-in-vim

**Comment by blueyed** [comment]
I do not think this is possible as of now. 647a4db appears to be only about parent methods, but not args itself.

**Comment by singhravi1** [comment]
Is there any possible solution for this right now?

**Comment by davidhalter** [comment]
About what?

**Comment by singhravi1** [comment]
Auto-completing the child method of an overriding class while using jedi.
And also, when i click on the the overriding method linked via super() like, super().dummy_method(..), it does not take me to its definition.

**Comment by davidhalter** [comment]
> Auto-completing the child method of an overriding class while using jedi.

Not exactly sure what you mean with that.

> And also, when i click on the the overriding method linked via super() like, super().dummy_method(..), it does not take me to its definition.

That should work. At least it does for me. (v0.13.3+).

**Comment by singhravi1** [comment]
> 
>     > Auto-completing the child method of an overriding class while using jedi.
> 
> Not exactly sure what you mean with that.

 Like suggesting params for the method
    
> 
> > And also, when i click on the the overriding method linked via super() like, 
> 
> > super().dummy_method(..), it does not take me to its definition.
> 
> That should work. At least it does for me. (v0.13.3+).

Not working for me maybe because i'm writing the method from parent of the current parent class

**Comment by davidhalter** [comment]
> Like suggesting params for the method

Please open an issue if you want that. This was about something else.

> Not working for me maybe because i'm writing the method from parent of the current parent class

That doesn't work and probably won't for quite some time. It's also a bad idea IMO in many cases and in the few cases where it's a good idea, it's probably easy enough to remember. If you want a solution for this, use `abc.ABC` with `abc.abstractmethod` (which then works with Jedi).

**Comment by fangjunzhou** [comment]
I think the issue of method override completion with parameters is still not resolved. I've searched online but it seems nobody is talking about it.

Take test file test/completion/context.py in 647a4db326104be57415258514f6920e3603d42c for example:

As I mentioned in https://github.com/davidhalter/jedi/commit/647a4db326104be57415258514f6920e3603d42c#r150509859, an ideal completion with parameter in line 13 should be

```python
#? ['func(self, foo)']
def f
```

**Comment by davidhalter** [comment]
Jedi just doesn't do that yet, but I wouldn't oppose pull requests into this direction, if it's well done.
