### ISSUE TITLE
linter doesn't honor isinstance() if it's part of a longer expression

### ISSUE THREAD

**Issue by encukou** [davidhalter/jedi#460]
With the code:

    def some_func(obj):
        if isinstance(obj, str) and obj.lower() == 'secret':
            print('Bingo!')
        else:
            print('Try again')

    some_func([])
    some_func(1)

I get:

    x.py:3:40: E1 AttributeError: <eArray of <Array: list[]>> has no attribute lower.

The isinstance check only works if it's the only thing in the `if` expression.

**Comment by davidhalter** [comment]
Seems to have been fixed along the lines
