### ISSUE TITLE
linter thinks bound methods are plain functions

### ISSUE THREAD

**Issue by encukou** [davidhalter/jedi#461]
Running the linter on this valid code:

    class Foo:
        def bar(self):
            return

    foo = Foo()
    print(foo.bar.__func__)
    print(foo.bar.__self__)

gives:

    $ python -m jedi linter /tmp/x.py
    /tmp/x.py:8:18: E1 AttributeError: <CompiledObject: <class 'function'>> has no attribute __func__.
    /tmp/x.py:9:18: E1 AttributeError: <CompiledObject: <class 'function'>> has no attribute __self__.

**Comment by davidhalter** [comment]
I have fixed this issue. However note that the linter is currently not in active development and posting further issues (on the linter) probably doesn't make any sense.
