### ISSUE TITLE
usages() finds wrong uses in assignments

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#473]
Take the following source:

``` Python
def newval(bla):
    return bla + 1


def foo(bar):
    bar = bar + 1
    return bar


def baz(bar):
    bar = newval(bar)
    return bar
```

In `foo`, calling `usages` on the left-hand side `bar` of the assignment correctly returns the locations for the left-hand side `bar` and the `bar` being returned, and not the `bar` argument and `bar` on the right-hand side.

In `baz`, calling `usages` on the left-hand side `bar` of the assignment incorrectly returns the argument to `newval` on the right-hand side in addition to the left-hand side and return arguments.

In `baz`, calling `usages` on the argument to `newval` actually returns _only_ the function parameter, not even the argument to `newval`.

Reproduction:

``` Python
SOURCE = """\
def newval(bla):
    return bla + 1


def foo(bar):
    bar = bar + 1
    return bar


def baz(bar):
    bar = newval(bar)
    return bar
"""

import jedi

print("bar in foo is correct")
s = jedi.Script(source=SOURCE, line=6, column=4)
print("Wanted: {}".format([(6, 4), (7, 11)]))
print("Got   : {}".format([(u.line, u.column) for u in s.usages()]))
print("")

print("bar in baz is incorrect")
s = jedi.Script(source=SOURCE, line=11, column=4)
print("Wanted: {}".format([(11, 4), (12, 11)]))
print("Got   : {}".format([(u.line, u.column) for u in s.usages()]))
print("")

print("bar in baz is incorrect")
s = jedi.Script(source=SOURCE, line=11, column=17)
print("Wanted: {}".format([(10, 8), (11, 17)]))
print("Got   : {}".format([(u.line, u.column) for u in s.usages()]))
print("")
```

**Comment by exploide** [comment]
I guess my finding is highly related to this issue, so I'm not going to open a new one.

But this is an even simpler example of how `usages()` does not work in certain cases:

Code to inspect:
```python
my_list = [1, 2, 3, 4, 5]
length = len(my_list)
```

Things to do with jedi:
```python
s = jedi.Script(source=the_above, line=1, column=1)
s.usages()
```

Which leads to `[<Definition my_list = [1, 2, 3, 4, 5]>]`

I would expect that it finds `my_list` inside the `len` function.

Found this while using the autocomplete-python package for Atom. sadovnychyi/autocomplete-python/issues/162

**Comment by davidhalter** [comment]
It looks like both of these issues are not reproducible anymore with the latest Jedi version.
