### ISSUE TITLE
False positive:  unsupported operand type(s) for +

### ISSUE THREAD

**Issue by dimaqq** [davidhalter/jedi#475]
This error is false positive:

```
/my/private/source.py:134:28: E11 TypeError: unsupported operand type(s) for +: <CompiledObject: 28> and <CompiledObject: <type 'int'>>
```

Code in question:

```
        max_prefix_len = 28 - len(self.ip_suffix)
```

Here, `self.ip_prefix` is always a string.

**Comment by davidhalter** [comment]
This is fixed now, but please don't report more linter issues. That code is trash and will be refactored at some point or straight on be discontinued.
