### ISSUE TITLE
Completion hangs

### ISSUE THREAD

**Issue by pratz** [davidhalter/jedi#476]
I am using XUbuntu 14.04

Attached is the snap shot where completion hangs completely and python fills up the memory entirely.
![jedi_goto_def](https://cloud.githubusercontent.com/assets/925565/4118824/9dea5302-32a5-11e4-97d2-b0f9b7df58be.png)

**Comment by davidhalter** [comment]
Can you send me the big file that you were talking about?

**Comment by pratz** [comment]
@davidhalter Its long time dude, sorry I do not have that file now.

**Comment by davidhalter** [comment]
That's fine. It's probably more my fault than yours ;-)

I'll just close it for now. I still think though, that Jedi should not import files above a certain size.
