### ISSUE TITLE
Completion for imports after module name (`import os.`)

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#478]
There appears to be no completion after `import os._`?! (`_` being the cursor, and e.g. `os.path` should be in the list of completions)

It works for `from os import _`.

I am using jedi with YouCompleteMe (I have updated jedi to the current dev branch with the same result), but have also tested it with `setlocal omnifunc=jedi#completions` from jedi-vim.

I was under the impression that this used to work?!

**Comment by davidhalter** [comment]
It actually works now. Whatever. Haha.
