### ISSUE TITLE
A New Parser

### ISSUE THREAD

**Issue by davidhalter** [davidhalter/jedi#480]
This is something I've been thinking for about a while. **I really need feedback.** I'm not a parser expert, please tell me at least what parser type I should implement.

The old parser
===========

The current parser is not a real parser. It's a multi-step fault-tolerant mess, that has allowed Jedi to be able to complete in almost any context. This is a very good feature, it makes it easy to detect call signatures (because even in the worst possible code constructions, we detect parentheses). It's also really comfortable for autocompletion, because it helps the evaluation step to understand its context better.

However, this comes with a big drawback: At no point in time we generate a proper AST, that can be played with. For example there's no certainty that a statement actually has a right side. It could as well just be empty. This is really annoying, because while evaluating, we have to check for "empty" statements a couple of times.

Another issue with the current parser is the fact that it doesn't allow you to regenerate the whitespace correctly. For proper refactoring support this would be tremendously important. Jedi would have supported refactoring a long time ago, if it were not for the parser.

It should be possible to compensate the above advantages of the old parser with a bit of logic.

Features of a new parser
==================

- Generating a proper and valid Python AST (more like a concrete syntax tree with all the whitespace definitions and useless brackets)
- Error Recovery. We would ignore wrong statements, but it's important to keep parsing for autocompletion.
- Being able to memorize all whitespace between tokens, see also #456
- Memory/Speed optimized. (Speed optimizations will not be that important, because with the fast parser combination (which parses only parts of the tree it's going to be fast enough for autocompletion)
- Ignore wrong indentation while being able to tell if there's wrong indentation in a syntax tree.

Side goals
---------------

- Keeping track of Syntax/Indentation Errors. This would be nice for Jedi's static analysis.
- The parser scopes (functions/classes) should keep dictionaries of defined names instead of lists to improve the speed of name lookups.

Notes
--------

- The new parser doesn't necessarily need to do all the things above at the same time.
- The pylint guys were interested in adapting the Jedi parser as well. I will add them to the discussion.

Milestones
========

I'm not going to describe how I want the AST to be. The new AST is the fact is going to be modeled way more towards Python's grammar. We're going to be able to easily work with precedences, instead of generating them separately.

1. Change the current AST more into the direction the new one is going to be.
2. Change the parser without refactoring support
3. Add refactoring support.
4. Add exact Syntax/Indentation errors [optional]

This is possibly the work of about two months of time, but it would really help the readability of Jedi code and I think that's important.

What are your thoughts? Is there a parser type you prefer for parsing Python? PEG? Bottom-up? Top-Down? I'm really not an expert in that topic and if anyone wants to give me any advice, I'd be glad to hear you out :)

~ Dave

**Comment by wilywampa** [comment]
Caling `jedi#usages()` on `T` in `T = numpy.arange(5)` in the following code:
```python
import numpy

T = numpy.arange(5)
y = numpy.arange(10).T
```
causes the following error/traceback:
```
('yess', Node(simple_stmt, [<ExprStmt:   arange = multiarray.arange@364,0>, <Whitespace: u'\n'>]))
Traceback (most recent call last):
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi_vim.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi_vim.py", line 162, in goto
    definitions = script.usages()
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/api/__init__.py", line 549, in usages
    names = usages.usages(self._evaluator, definitions, module)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/api/usages.py", line 32, in usages
    result = evaluator.goto(name)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 333, in goto
    types = self.eval_element(call)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 168, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 234, in eval_trailer
    new_types += self.find_types(typ, node)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 106, in find_types
    return f.find(scopes, search_global)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/finder.py", line 44, in find
    names = self.filter_name(scopes, search_global)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/finder.py", line 180, in filter_name
    self.scope)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/flow_analysis.py", line 49, in break_check
    return _break_check(evaluator, stmt, base_scope, element_scope)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/flow_analysis.py", line 76, in _break_check
    return reachable & _break_check(evaluator, stmt, base_scope, element_scope.parent)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/flow_analysis.py", line 75, in _break_check
    if base_scope != element_scope and base_scope != element_scope.parent:
AttributeError: 'NoneType' object has no attribute 'parent'
```

**Comment by davidhalter** [comment]
All right. All tests pass again. It's still slow, I now have to add the "fast parser" again, which may take a few weeks but then we're done. I have changed pretty much the whole library. The evaluation process looks quite different and name lookups are now way simpler and better structured.

@wilywampa Thanks for testing! I think all of the above issues are now resolved (I've tested them and cannot reproduce any of them). The first one (`with`) needed an extra fix, the rest was fixed alone the lines.

**Comment by asmeurer** [comment]
Is it API compatible with the old version? Can I drop it into my existing emacs-jedi setup to give it a try?

**Comment by davidhalter** [comment]
Yeah. The API hasn't changed at all if I'm not mistaken. If everything works well, you shouldn't notice any difference at all (except that it's slower).

**Comment by davidhalter** [comment]
I'm kind of disappointed in the performance of the parser. It's 4 times slower than my previous stupid solution. Now I have to find ways to speed it up.

**Comment by asmeurer** [comment]
If you're looking for a profiler I've found pyinstrument to be very useful.

**Comment by davidhalter** [comment]
Oh wow. I was mistaken. I just read the wrong number. New parser is faster & more memory efficient. Yay for that, haha. I was disappointed the whole day and did nothing, because of that. Haha.

So I just have to add a "fast parser" solution as well (which is partial file caching).

**Comment by blink1073** [comment]
Here's what I get:

```python
Master:
In [2]: %time jedi.Script('import numpy as np; np.one', 1, 25, None).complete()
CPU times: user 2.78 s, sys: 52.7 ms, total: 2.83 s
Wall time: 2.83 s
Out[2]: [<Completion: ones>, <Completion: ones_like>]

In [3]: %time jedi.Script('import numpy as np; np.one', 1, 25, None).complete()
CPU times: user 9.28 ms, sys: 1.54 ms, total: 10.8 ms
Wall time: 9.54 ms
Out[3]: [<Completion: ones>, <Completion: ones_like>]



Parser:
In [2]: %time jedi.Script('import numpy as np; np.one', 1, 25, None).completions()
CPU times: user 529 ms, sys: 21.9 ms, total: 550 ms
Wall time: 550 ms
Out[2]: [<Completion: ones>, <Completion: ones_like>]

In [3]: %time jedi.Script('import numpy as np; np.one', 1, 25, None).completions()
CPU times: user 27.6 ms, sys: 1.77 ms, total: 29.3 ms
Wall time: 28 ms
Out[3]: [<Completion: ones>, <Completion: ones_like>]
```

**Comment by dbrgn** [comment]
> Oh wow. I was mistaken. I just read the wrong number. New parser is faster & more memory efficient. Yay for that, haha. I was disappointed the whole day and did nothing, because of that. Haha.

Haha. Well done :D

**Comment by davidhalter** [comment]
I'm done. Well mostly. The fast parser is now also working with the new parser, but there are still performance issues. I have to investigate a little bit. However it shouldn't be a big issue for the general Jedi user. Therefore I'm pushing it both to dev/master.

```
$ git rev-list origin/master..parser --count
766
$ git rev-list origin/dev..parser --count
518
```

**Comment by dbrgn** [comment]
\o/ congrats!

**Comment by blink1073** [comment]
Great work David!
