### ISSUE TITLE
Inconsitent usage results

### ISSUE THREAD

**Issue by jussij** [davidhalter/jedi#481]
The following script shows the usages of x variable:

    import jedi

    source = '''\
    def f():
        x = 3
        if 1 == 2:
            x = 4
        else:
            del x
    '''

    script = jedi.Script(column=5, source=source, line=2)  # x = 3
    print 'Usages (x = 3):\n' + '\n'.join([str(u.description) + ' (' + str(u.line) + ', ' + str(u.column) + ')' for u in script.usages()])

    script = jedi.Script(column=9, source=source, line=4)  # x = 4
    print 'Usages (x = 4):\n' + '\n'.join([str(u.description) + ' (' + str(u.line) + ', ' + str(u.column) + ')' for u in script.usages()])

    script = jedi.Script(column=12, source=source, line=6)  # del x
    print 'Usages (del x):\n' + '\n'.join([str(u.description) + ' (' + str(u.line) + ', ' + str(u.column) + ')' for u in script.usages()])

The output produced is:

    Usages (x = 3):
    x (2, 4)
    x (6, 12)
    Usages (x = 4):
    x (4, 8)
    x (6, 12)
    Usages (del x):
    x (2, 4)
    x (4, 8)
    x (6, 12)

As shown in the output the actual usage differs depending on which of the x values is used as the reference point.

**Comment by davidhalter** [comment]
Closing, in favor of #473, it's really the same issue.
