### ISSUE TITLE
Support for characteristic

### ISSUE THREAD

**Issue by hynek** [davidhalter/jedi#488]
Hi,

I’m the author of [characteristic](https://characteristic.readthedocs.org/), a package that is supposed to make the usage of data classes in Python much easier.

Unfortunately it uses `setattr` (and may do even worse black magic for performance reasons later) and therefore jedi doesn’t pick up the defined attributes.  But since they are explicitly declared using a decorator, I figure it could be feasible for you to support it directly?  I’d be eternally indebted. :)

Cheers,
Hynek

P.S. For context, it has around 500 downloads a day from PyPI and is somewhat popular in the Twisted-verse: https://warehouse.python.org/project/characteristic/

**Comment by hynek** [comment]
I’m gonna close this since characteristic is deprecated in favor of [attrs](https://attrs.readthedocs.io/en/stable/) which is according to some [The One Python Library Everyone Needs](https://glyph.twistedmatrix.com/2016/08/attrs.html). ;) (~13k DL/day btw)

attrs uses class attributes so it works better; if you’d like to add deeper support, there’s a lot of meta data for jedi to harvest if it wanted to. :)

**Comment by spookylukey** [comment]
@davidhalter I was about to file a ticket about supporting `attrs`, especially for providing help for the dynamically generated `__init__` method, and found this ticket.

It looks like there is some enthusiasm about supporting `attrs`. If I were to start work on this, is there a recommended approach? Is it OK to have builtin support for this kind of 3rd party library directly in jedi, or is there some kind of plugin system it should be using?

**Comment by davidhalter** [comment]
There is no plugin system, yet. We would need to define one, first. Builtin support is not an option IMO.

**Comment by hynek** [comment]
I think though that a ticket for attrs support would be fair game?

**Comment by davidhalter** [comment]
If you want, you can create a ticket for a plugin system, if you want. There's also no support for Django models, which is probably a more pressing issue (in terms of users and what I'm using myself). I think a plugin system should be open to anyone.

**Comment by glyph** [comment]
As I understand it the correct ticket for further discussion here is #626 ?

**Comment by davidhalter** [comment]
Yes.
