### ISSUE TITLE
Not showing function signatures for class methods

### ISSUE THREAD

**Issue by jatcwang** [davidhalter/jedi#498]
I just recently started using `jedi.vim`. I noticed that my class methods doesn't seem to be showing the function signatures when I use them. Here's a test script:

```
import jedi

source = """\
class Blah:
    @classmethod
    def tt(cls, a, b):
        return cls()
Blah.tt(
"""

script = jedi.Script(column=8, source=source, line=5)
sig = script.call_signatures()
print(sig[0].params)

other = """\
class Blah:
    @staticmethod
    def tt(a, b):
        return a
Blah.tt(
"""

script = jedi.Script(column=8, source=other, line=5)
sig = script.call_signatures()
print(sig[0].params)
```

I get the output

```
[<_Param *args>, <_Param **kwargs>]
[<_Param a>, <_Param b>]
```

So it seems like `@staticmethod` works but not `@classmethod`

I'm using python 3, but python 2 seems to give me the same output for the test script.

Is this a bug?

Thanks!

**Comment by jatcwang** [comment]
Closing to clear my issue queue.

**Comment by davidhalter** [comment]
Reopening, because this is actually an issue. Sorry ;-)
