### ISSUE TITLE
Call signatures not displayed after 'return'

### ISSUE THREAD

**Issue by wilywampa** [davidhalter/jedi#501]
As an example, if I type `return reduce(`, no call signature is displayed. Would it be sufficient to add this to helpers.py? It works for my example but I don't know what the side effects might be.

```python
    if isinstance(user_stmt, pr.KeywordStatement):
        user_stmt = user_stmt.stmt
```

**Comment by davidhalter** [comment]
Seems to be working now :-)

Just complain if it doesn't.
