### ISSUE TITLE
Support for NumPy and Google-style Sphinx docstrings

### ISSUE THREAD

**Issue by westurner** [davidhalter/jedi#504]
*Sources*

* http://jedi.jedidjah.ch/en/latest/docs/features.html#type-hinting
* http://jedi.jedidjah.ch/en/latest/docs/development.html#docstrings
* https://github.com/davidhalter/jedi/blob/master/jedi/evaluate/docstrings.py

* https://pypi.python.org/pypi/sphinxcontrib-napoleon (sphinx.ext.napoleon in Sphinx 1.3+)
  * https://bitbucket.org/birkenfeld/sphinx/src/tip/sphinx/ext/napoleon/
  * https://bitbucket.org/birkenfeld/sphinx-contrib/src/tip/napoleon/
* https://github.com/numpy/numpydoc (see: sphinx.ext.napoleon)

(Adapted) From https://pypi.python.org/pypi/sphinxcontrib-napoleon :

Google-style:

```python
def func(arg1, arg2):
    """Summary line.

    Extended description of function.

    Args:
        arg1 (int): Description of arg1
        arg2 (str): Description of arg2

    (Yields:)
    Returns:
        bool: Description of return value


    """
    return True
```

NumPy style:
```python
def func(arg1, arg2):
    """Summary line.

    Extended description of function.

    Parameters
    ----------
    arg1 : int
        Description of arg1
    arg2 : str
        Description of arg2

    Returns
    -------
    bool
        Description of return value

    """
    return True
```

**Comment by WoLpH** [comment]
@davidhalter Can I simply add a few regexes here to fix it? https://github.com/davidhalter/jedi/blob/dev/jedi/evaluate/docstrings.py

Seems like something that wouldn't take me too long to fix and I'd be happy to create a pull request (including tests of course).

**Comment by davidhalter** [comment]
I guess I'm ok with this feature being added to Jedi since a few people are interested.

@WoLpH Yes, adding a few regexes would probably be good enough! It shouldn't be a big change TBH.

**Comment by Erotemic** [comment]
@davidhalter 
I just wanted to comment to say that my project (https://github.com/Erotemic/ibeis) uses google style docstrings quite extensively. It would be great to see this feature added.

**Comment by davidhalter** [comment]
There's still an pull request open that would add google style docstrings to Jedi. I think that's good enough. I'm happy to merge it if somebody implements it properly. This issue doesn't need to be open anymore.

**Comment by WoLpH** [comment]
If anyone is looking for an intermediate solution, the pull request I've proposed has been working fine for me for the last year.
