### ISSUE TITLE
Type hinting for imported types

### ISSUE THREAD

**Issue by dseuss** [davidhalter/jedi#507]
I am not quite sure whether it's a bug or a feature, but type hinting of function parameters seems to ignore qualified imports:
~~~
import numpy
def test(abc):
    """@type abc: numpy.ndarray"""
    abc.|
~~~
completes properly (even without the import), but
~~~
import numpy as np
def test(abc):
    """@type abc: np.ndarray"""
    abc.|
~~~
does not.

**Comment by davidhalter** [comment]
I have rechecked this one and it seems to work. This means that renaming an import is working. I've tested it with datetime.

To be honest `numpy.ndarray` isn't even in the completion list when I import numpy. But that's an entirely different issue.
