### ISSUE TITLE
Interpreter: completions from namespaces all have type=='module'

### ISSUE THREAD

**Issue by florianlink** [davidhalter/jedi#511]
When using the Interpreter() API, all completions have the type 'module'.

The problem seems to be in Interpreter._simple_complete(self, path, like)    
```python
...
completions = []
for namespace in namespaces:
  for name in dir(namespace):
    if name.lower().startswith(like.lower()):
      scope = self._parser.module()
      n = FakeName(name, scope)
      completions.append((n, scope))
return completions
```
because each FakeName Completion will have the parser module as scope, so the type will be 'module'.
 
If I patch the method like below, I get better types, but it is unclear to me if using CompiledObject()
is always the right thing...

```python
...
completions = []
for namespace in namespaces:
for name in dir(namespace):
   if name.lower().startswith(like.lower()):
     parserScope = self._parser.module()
     scope = compiled.CompiledObject(getattr(namespace, name), parserScope)
     n = FakeName(name, scope)
     completions.append((n, scope))
return completions
```

**Comment by davidhalter** [comment]
This has been changed. The interpreter is now in a pretty good shape I believe. I just rewrote the whole thing. :-)
