### ISSUE TITLE
call_signatures: can't distiguish beween class and instance calls on builtins

### ISSUE THREAD

**Issue by florianlink** [davidhalter/jedi#515]
Both str().capitalize() and str.capitalize() lead to the same CallSignature, there is no way to distinguish between class function call (with self) and instance calls.

'''def TEST001_class_member_str():
  source = '''
str.capitalize(
'''
  script = jedi.Script(source, len(source.splitlines()), len('str.capitalize('), 'example.py')
  signatures = script.call_signatures()
  print signatures [0]
  print signatures [0].parent()

def TEST001_instance_member_str():
  source = '''
str().capitalize(
'''
  script = jedi.Script(source, len(source.splitlines()), len('str().capitalize('), 'example.py')
  signatures = script.call_signatures()
  print signatures [0]
  print signatures [0].parent()
'''

**Comment by davidhalter** [comment]
Fixed, thanks!
