### ISSUE TITLE
Support for dynamically created classes

### ISSUE THREAD

**Issue by danihodovic** [davidhalter/jedi#516]
Hi, I'm currently using SublimeJedi and I've noticed that there is no support for dynamically created classes.

According to the Python docs these two ways of creating a class should be equal.

> > > class X(object):
> > > ...     a = 1
> > > ...
> > > X = type('X', (object,), dict(a=1))

Is it possible for SublimeJedi to autocomplete methods in dynamically created classes by looking at the classes and the dict it inherits?

**Comment by davidhalter** [comment]
For anyone attempting this (maybe @Rested):

This can be solved by modifying `builtins_type` in `jedi/plugins/stdlib.py`. You can check how it was done for `EnumInstance`, which is a similar approach. The dictionary keys can in the third position can be checked by using something like

```
# [in builtins_type]:
if bases or dicts:                            
    # It's a type creation... maybe someday...
    return [
        AnonymousTypeInstance(name, base_tuple, dct)
        for base_tuple in bases
        for dct in dcts
        for name in names
    ]

...

class AnonymousTypeInstance(LazyValueWrapper):
    ...
    def get_filters(self):
        for base in self.base_tuple.py__iter__():
            for filter in base.get_filters():
                yield filter
        def iter_dct():
            for key in self.dct.py__iter__():
                if is_string(key):
                    yield key.get_safe_value(), NO_VALUES
        yield DictFilter(dict(iter_dct()))

    def py__name__(self):
        return str(self.name)  # Should probably be something else
```

Needs obviously a lot of testing with edge cases and the code is ugly and quite a few things are missing :).

**Comment by davidhalter** [comment]
I just realized that this might not make sense to work on, because if the strings are known at "compile time", then it makes never sense to use it. In that case people should just use classes.

You guys can also give me an example where it would make sense to use such a thing, I cannot imagine such a thing, so I'm closing. It's just not worth the time and effort to implement/maintain this.
