### ISSUE TITLE
Typehinting: Collection element types?

### ISSUE THREAD

**Issue by yurikhan** [davidhalter/jedi#517]
Hello,

with Jedi, it is possible to say that a parameter is a tuple and specify the types of the elements:

```python
def foo(bar):
    """
    :type bar: (str, int)
    """
    bar[0].| # lists str methods
```

Is there any way of saying that a certain parameter is a collection and all its elements have a certain type? e.g:

```python
def foo(bar, baz, quux):
    """
    :type bar: [int] # list of int
    :type baz: {str} # set of str
    :type quux: {str: [int]} # dict from str to list of int
    or
    :type bar: list[int]
    :type baz: set[str]
    :type quux: dict[str, list[int]]
    """
```

The former syntax mirrors the tuple syntax; the latter AFAIU is [understood by PyCharm](https://www.jetbrains.com/pycharm/webhelp/type-hinting-in-pycharm.html).

*Expected behavior:* At a minimum, completion for `bar.|`, `baz.|` and `quux.|` should display list, set and dict methods respectively. Ideally, element type hints would be used for completing expressions that are known to derive from elements of bar, baz and quux, e.g. `bar[0].|` lists int methods, `[s.| for s in baz]` lists str methods.

*Observed behavior* (in emacs-jedi, for a `set[str]` type hint):

```
Company: An error occurred in auto-begin
Company: Back-end (company-jedi company-files) async timeout with args (candidates .)
```

It would be even more awesome if it were possible to say that a dict has such-and-such keys and that this key has a value of this type and that key has a value of that type, like:

```python
def foo(bar):
    """
    :type bar: {'name': str, 'age': int}
    """
```

**Comment by svermeulen** [comment]
Support for adding type hints for local variables or return values would be nice too (like those described [here](http://pydev.org/manual_adv_type_hints.html).

Python 3 style annotations would be a nice to have as well, which from what I understand is something like:

    def foo(bar:int):
        pass

**Comment by davidhalter** [comment]
I think that with the support for PEP 484 there's a good way to do a lot with type systems.

Both of these cases work now:

```
import typing
def x(a: typing.Union[str, dict]):
    a.

def x(a):
    '''
    :type a: typing.Union[str, dict]
    '''
    a.
```
