### ISSUE TITLE
Emacs - Jedi not recognising dist-packages libraries

### ISSUE THREAD

**Issue by madhavan020985** [davidhalter/jedi#523]
Jedi assumes all library files are sitting in  
````javascript
 $HOME/.emacs.d/.python-environments/default/local/lib/python2.7/site-packages/
```` 
where python-environments is jedi's default virtualenv. For source code lookup outside this folder, it burps 
````javascript
No definition found
````
How can i instruct jedi to lookup in 
````javascript 
/usr/local/lib/python2.7/dist-packages
```` 
instead of its original path?
note: i am living happily with no virtenv & i choose to keep it that way. so, does jedi work with no virtenv and all lib files in one place. and my m/c is ubun-14.04, emacs24.

**Comment by davidhalter** [comment]
So are you installing Jedi in a virtualenv?

**Comment by madhavan020985** [comment]
no david, i used melpa package-install to do the work... during the course, it complained virtualenv bin couldn't be found. so i did pip install virtualenv & then installed jedi. and it kind of worked somewhat.

**Comment by davidhalter** [comment]
Hmm strange. I think I have changed a few things about virtualenvs in the dev or parser branch. Let's wait until that gets merged and talk about this again at that point.

**Comment by madhavan020985** [comment]
okay david, jedi.parser.Parser("some-code-goes-here").module.subscopes... i am trying to understand more about scope objects in your jedi package. Does this scope have any prototype (or) superclass? if yes, where? tx..

**Comment by tbekolay** [comment]
@madhavan020985, please see https://github.com/tkf/emacs-jedi/issues/184 for some fixes to this issue (which is `jedi.el` specific).
