### ISSUE TITLE
Melpa installs 0.7.0 - old versioned jedi

### ISSUE THREAD

**Issue by madhavan020985** [davidhalter/jedi#524]
hi david,  My pip installed jedi is versioned  0.8.1-final0. whereas, melpa has put __version__ = 0, 7, 0 jedi in my .emacs folder. How can i use latest version jedi inside emacs?
Why i need this?
i am debugging another issue that dist_packages are not added to jedi's syspath. so i found that the code related to python import path is sitting in jedi/evaluate/sys_path#get_sys_path in pip installed jedi. Now, when i checked my melpa installed jedi code, it doesn't have any folder called as jedi/evaluate. so, i am clueless about how to check the entries in jedi's syspath...

**Comment by davidhalter** [comment]
Hi!

Well, you have to complain about that at your "emacs/jedi" plugin maintainer. Jedi is not an emacs package, it's just a Python library.
