### ISSUE TITLE
Point to readthedocs instead of jedidjah

### ISSUE THREAD

**Issue by cdeil** [davidhalter/jedi#525]
It seems that HTTPS certificate for the current docs page is invalid: https://jedi.jedidjah.ch/
Can you point to here instead from the README to get rid of this annoyance?
http://jedi.readthedocs.org/

**Comment by davidhalter** [comment]
Yeah. I guess that's ok, if there's no easy way of getting https to work there.

**Comment by davidhalter** [comment]
But I get the same HTTPS issue if I access RTD directly: https://jedi.readthedocs.com/en/latest/

**Comment by cdeil** [comment]
Use `.org` and not `.com`:
https://jedi.readthedocs.org/en/latest/

**Comment by IanLee1521** [comment]
This can be closed with #550 being merged.
