### ISSUE TITLE
Relative star imports (old: Is this a bug?)

### ISSUE THREAD

**Issue by realitee** [davidhalter/jedi#536]
```
import jedi

source = """
from furl import furl
furl.
"""

script = jedi.Script(source,3,5, '')

completions = script.completions()
```

with the code above,it can not get the right completions in my computer, Can someone check it ?again?

**Comment by davidhalter** [comment]
What is wrong? What do you get, what would you want?

**Comment by realitee** [comment]
I test the code in ipython,the completions is below:
###########################
[<Completion: abc>,
 <Completion: attemptstr>,
 <Completion: basestring>,
 <Completion: callable_attr>,
 <Completion: COLON_SEPARATED_SCHEMES>,
 <Completion: DEFAULT_PORTS>,
 <Completion: Fragment>,
 <Completion: FragmentCompositionInterface>,
 <Completion: FragmentPathCompositionInterface>,
 <Completion: furl>,
 <Completion: is_valid_encoded_path_segment>,
 <Completion: is_valid_encoded_query_key>,
 <Completion: is_valid_encoded_query_value>,
 <Completion: is_valid_port>,
 <Completion: join_path_segments>,...]
#################################

this is not right,see it:(use ipython)

##########################
In [8]: from furl import furl

In [9]: furl.
furl.add         furl.host        furl.path        furl.register
furl.args        furl.join        furl.pathstr     furl.remove
furl.copy        furl.load        furl.port        furl.scheme
furl.fragment    furl.mro         furl.query       furl.set
furl.fragmentstr furl.netloc      furl.querystr    furl.url
#########################
did I do something wrong? If not,this maybe a bug.

**Comment by davidhalter** [comment]
I suppose its a bug. :) They have a relative star import in `__init__.py`. Might be the cause.

**Comment by davidhalter** [comment]
This is really interesting! I have not actually known about the exact behavior of the import logic.

Python `from X.Y import Z` checks the dictionary first for Z, but not X and Y. This needs to be changed in Jedi. I thought files would always be "preferred".

**Comment by davidhalter** [comment]
Fixed.
