### ISSUE TITLE
wheel package format

### ISSUE THREAD

**Issue by stonebig** [davidhalter/jedi#537]
Would it be possible to have a wheel package format on pypi for jedi ?

**Comment by davidhalter** [comment]
Why?

**Comment by stonebig** [comment]
It's for building a "pure-wheel" python distribution.

If all packages I used are "wheel" , then I can build winpython by pointing all dependancies resolution to a local directory.

Today I can't, because an update from pypi can create unpredictable results.
==> so missing dependancies are discovered per users.

Tomorrow, if all packages used are wheels  I'll be able to let the build process check and resolve dependancies on the 'controled' set of wheels, and raise an issue if I missed one.

So, Why not adding a wheel package next to the .tar package ?

**Comment by davidhalter** [comment]
> So, Why not adding a wheel package next to the .tar package ?

Well, aren't wheels are platform specific? Wouldn't I be forced to upload wheels for all platforms? Jedi is not platform specific and if it's easy to upload, I can of course do it.

**Comment by stonebig** [comment]
If your package is pure python (2 and 3), it's just a matter of doing something like
````
python setup.py sdist bdist_wheel --universal
````

After this initial success:

- you can consider to add requirements.txt for dependencies resolving during the wheel installation, but apparently you have no needs (?).

- you can consider adding a section in `setup.cfg`, to remove the `--universal` need:

````
[bdist_wheel]
universal = 1
````

**Comment by davidhalter** [comment]
Jedi doesn't have requirements. I think I'm just going to add a wheel distribution as well.

**Comment by stonebig** [comment]
thanks !

**Comment by IanLee1521** [comment]
:+1: Though I've preferred to use [Twine](https://pypi.python.org/pypi/twine):

    pip install twine
    python setup.py sdist bdist_wheel
    twine upload dist/*

**Comment by stonebig** [comment]
How is it possible that `Twine`isn't referenced on the main page of  http://pythonwheels.com/  ?
(it is filled up with `python setup.py sdist bdist_wheel upload` instead)

**Comment by asmeurer** [comment]
I think twine is independent of using wheels. It's mainly an improved upload to PyPI experience.

**Comment by davidhalter** [comment]
`bdist_wheel` works great! Let me know if you are having issues!

(BTW I had to do `pip install wheel` first!)

**Comment by stonebig** [comment]
Thanks!
