### ISSUE TITLE
>2 second lag in some cases using python 3

### ISSUE THREAD

**Issue by svermeulen** [davidhalter/jedi#540]
Forgive me if this is a known issue, I couldn't find it listed in the backlog.  I just started using Jedi with Vim to help edit python 3 scripts.  It works ok so far, but occasionally it locks up for sometimes as long as 2 seconds after triggering completion.  I tried looking into it briefly myself and turned on `jedi#enable_speed_debugging`, which resulted in this output:

https://dl.dropboxusercontent.com/u/2959315/temp/error_output.png

Which seems to point to some imports like datetime taking quite a long time

**Comment by svermeulen** [comment]
The ability to set a timeout would resolve this for me as well.  I'd be much happier just not getting completion data in these cases.

**Comment by davidhalter** [comment]
How quick is it the second time you run it?

IMHO we just need an async solution. A timeout is not really a good solution either.

**Comment by svermeulen** [comment]
Same speed, I get the same output every time.

**Comment by davidhalter** [comment]
Can you post the source code, so I can try to understand it?

**Comment by davidhalter** [comment]
ping
