### ISSUE TITLE
'UnboundLocalError: local variable 'path' referenced before assignment' still occurs in master and pip version

### ISSUE THREAD

**Issue by diogo149** [davidhalter/jedi#541]
I'm getting the error described here: https://github.com/jorgenschaefer/elpy/issues/364 in both the jedi version from pypi and installing from master, and applying the fix here: https://github.com/davidhalter/jedi/commit/b26f51ded225e21dddbb792d42239d5e75ae3659 works perfectly.

I'm not sure if there's any reason why one wouldn't merge the changes from develop into master, but doing so should solve the issue for others. (:

**Comment by davidhalter** [comment]
Well, because master is "stable" and I wasn't sure if that branch was stable at the time.

There will be a merge quite soon.

**Comment by davidhalter** [comment]
Closing this, because it's not really an issue anymore and I hope to merge soon.
