### ISSUE TITLE
Inline type hinting

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#542]
It would be nice to allow for type hinting within a function, above an assignment.

(via https://github.com/davidhalter/jedi/issues/421#issuecomment-45447033)

**Comment by davidhalter** [comment]
Can you elaborate?

**Comment by blueyed** [comment]
I would like to use something like this:

    # :type client: Client
    client = get_some_client()

This could be useful when jedi does not get it correctly (as with #543).

**Comment by davidhalter** [comment]
Hmm, what ways of using comments as type hinting are there already (in PyCharm, PyDev, etc)?

**Comment by blueyed** [comment]
I don't know.

**Comment by blueyed** [comment]
Here's how PyDev does it: http://pydev.org/manual_adv_type_hints.html

**Comment by dset0x** [comment]
PyCharm has a similar feature: https://www.jetbrains.com/pycharm/help/type-hinting-in-pycharm.html#d281633e18247

**Comment by reinhrst** [comment]
#664 will allow PEP484-style type-hinting

**Comment by davidhalter** [comment]
I'm closing this one, because we're merging very very soon.
