### ISSUE TITLE
Support for Factory Boy / DjangoModelFactory

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#543]
It would be great if Jedi would support DjangoModelFactory (from Factory Boy,
http://factoryboy.readthedocs.org/en/latest/recipes.html):

```
# models.py
class User(models.Model):
    first_name = models.CharField()
    group = models.ForeignKey(Group)


# factories.py
import factory
from . import models

class UserFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = models.User

    first_name = factory.Sequence(lambda n: "Agent %03d" % n)
    group = factory.SubFactory(GroupFactory)
```

The model / class being returned is named / referred to in `Meta.model`.

It's also supported to refer to the model as a string, e.g. `'models.User'`.

Currently Jedi completes the properties of the factory class, but not the
object that is being created through calling it:

```
user = UserFactory()
```

Here is the `__call__` method: https://github.com/rbarrois/factory_boy/blob/master/factory/base.py#L72

**Comment by davidhalter** [comment]
Also depends on #626. I'm closing this, because it will most likely not be part of Jedi, but part of a third party module. Generally writing code for these classes is just a bit annoying, so I will leave it up to other people once an API exists :)
