### ISSUE TITLE
Inconsistent handling of script directory

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#544]
Given this directory structure:

```
./pkg/repro.py
./pkg/__init__.py
./pkg/subpkg/__init__.py
```

And these contents for `pkg/repro.py`:

``` Python
import jedi

import pkg.subpkg

s = jedi.Script(
    source="""\
import pkg.sub
""",
    line=1, column=14
)
print [proposal.name for proposal in s.completions()]
```

I get the following behavior:

```
$ python -m pkg.repro
[]
$ PYTHONPATH=`pwd` python -m pkg.repro
[u'subpkg']
```

As the contents of `repro.py` indicate, `pkg.subpkg` is importable in both calls, but Jedi only finds it if the calling directory is added explicitly to the path. I would expect Jedi to find the module even in the first case.

Incidentally, a script `test.py` in the same directory as `pkg` that only does `import pkg.repro` makes this work correctly wherever it is called from.

I'm not sure if this is strictly speaking a bug, so feel free to close this issue if you think it isn't :-)

(Originally reported in jorgenschaefer/elpy#481)

**Comment by davidhalter** [comment]
Just call `pkg/repro.py` as a script and not as a module and report back.

**Comment by jorgenschaefer** [comment]
Calling `pkg/repro.py` as a script won't find `pkg.subpkg` in the import statement on line 3:

```
$ python pkg/repro.py 
Traceback (most recent call last):
  File "pkg/repro.py", line 3, in <module>
    import pkg.subpkg
ImportError: No module named pkg.subpkg
```

(This is just a minimal reproduction case, the situation where we found this behavior is a lot more complex – it's solvable by adding the path to `PYTHONPATH`, so it's not a huge problem, but I figured I'd let you know of a possible problem :-))

**Comment by davidhalter** [comment]
All right. I agree with you, that path should be included.

**Comment by davidhalter** [comment]
I remember now why this behaves like it behaves.

It doesn't include the `.` path, because that used to be very confusing in quite a few cases. Some editor plugins would modify the current directory or you would have virtual envs with different paths. Long story short, this just caused a lot of unintended side effects.

It's been a long time, but I think my decision was: Leave defining the sys.path up to the plugin implementation. Otherwise fall back to a conservative stdlib only.

Is that ok for you

**Comment by jorgenschaefer** [comment]
It's a bit confusing, because `python -m` finds the module, but the module does not find itself, but otherwise I'm fine with this. Thanks for looking into it. :-)

**Comment by davidhalter** [comment]
I get weird results currently when trying this. I'm reopening.

**Comment by davidhalter** [comment]
The sys path stuff has all been cleaned up with projects. I'd be happy if you took a look at it and gave me some feedback (you can also open new issues). It's in `jedi.api.project`. The API is currently not publicly documented and usable, but it will be in the future.
