### ISSUE TITLE
max recursion limit with new parser code and buildout project

### ISSUE THREAD

**Issue by mfussenegger** [davidhalter/jedi#545]
Since the new parser code has been merged I wanted to give it a try. But it seems like the buildout support got broken in the re-write.

In ``sys_path.py`` the ``_check_module`` function is missing its second argument (in line 158) but after adding that it runs into the max recursion limit as seen in the following gist.

https://gist.github.com/mfussenegger/1a036789c29eeb620d32.

**Comment by davidhalter** [comment]
Thanks! Well, probably buildout is not well tested then.
