### ISSUE TITLE
Current version on PyPI doesn't play well with latest setuptools (PEP 440)

### ISSUE THREAD

**Issue by asmeurer** [davidhalter/jedi#547]
When trying to use a package that depends on jedi, I am getting the warning

```
PEP440Warning: 'jedi (0.8.1-final0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
```

This is causing bad behavior for me, because jedi 0.8.1 is already installed, but it is trying to reinstall it, because it doesn't recognize the version 0.8.1-final0 as >= 0.8.1. 

Can you reupload 0.8.1 to PyPI without the -final0 in the version (and please don't use -final0 in future versions)?

**Comment by davidhalter** [comment]
I think I did that already?

**Comment by asmeurer** [comment]
Ah, I see now. Sorry for the noise. I was working with a conda package I had built against the older version.
