### ISSUE TITLE
Attribute errors

### ISSUE THREAD

**Issue by imfede** [davidhalter/jedi#555]
Hi, I'm using jedi with emacs, thanks to elpy. After a while it started giving me the following errors. Note that I do not changed anything in the configuration/source files/workflow to make this happen (not that I know of, at least). Those errors show up very often when i type, leading me to think they are generated every time jedi tries to complete what i'm writing. 
Emacs throws those two errors:
```
deferred error : (error "\"AttributeError(\\\"'Definition' object has no attribute 'line_nr'\\\",)\"")
deferred error : (error "\"AttributeError(\\\"'Script' object has no attribute 'complete'\\\",)\"")
```

I've already upgraded to jedi 0.9.0 as suggested by the mantainer of the elpy github page.
If you wish to know more, please read https://github.com/jorgenschaefer/elpy/issues/514 where i've included the full error before upgrading to 0.9.0
Now it does not show that helpful pop-up with the stacktrace ecc, it just doesn't work and it throws the above errors. If i can get the trace to show up I'll let you know.
Thx in advance

**Comment by davidhalter** [comment]
@jorgenschaefer It looks like you're using the old deprecated API commands `line_nr` and `complete`. They were deprecated a few versions ago. Is that correct?

**Comment by jorgenschaefer** [comment]
Hm. That should not be the case, Elpy switched to the new API a few versions ago as well (the only occurrence of `complete` is the member variable `complete` on a completion proposal). @imfede, is it possible that you have an older version of Elpy installed somewhere that you accidentally included?

The original error posted on the Elpy tracker had something about a `Flow` object not having an attribute called `name`, which sounds entirely different from this problem now?

**Comment by davidhalter** [comment]
@jorgenschaefer Yes. That sounds like an actual bug :-)

**Comment by imfede** [comment]
Ok, this is entirely my fault. After a lot of time fiddling round with various settings, reinstalling the last version of elpy&jedi; I discovered that i had an ancient version of jedi.el still lingering around. After removing it, all the aforementioned problems disappeared. 
Special thanks to @jorgenschaefer for the initial support and for pointing me in the right direction :-)
> is it possible that you have an older version of Elpy installed somewhere that you accidentally included?

**Comment by davidhalter** [comment]
Awesome, thanks guys :)
