### ISSUE TITLE
print(value, ...)

### ISSUE THREAD

**Issue by dridk** [davidhalter/jedi#557]
Why Jedi autocomplete print with : print(value,...) !
it'is really borring ! I always have to remove "..." by hand

**Comment by davidhalter** [comment]
What are you typing? Where are you using autocompletion?
Which autocompletion tool are you using?

**Comment by dridk** [comment]
editor : sublime text 3 
typing in python :   "prin"  THEN press CTRL+SPACE to autocomplete
what it show : " print(value,...) "
what I want :  " print(value)"

**Comment by davidhalter** [comment]
@dridk That is not a Jedi issue. That is an issue of either `SublimeJEDI` or `anaconda`. Jedi is just the library that does the whole logic behind it, but is not responsible for the output. Please report it there!
