### ISSUE TITLE
goto_definitions on pyqtSlot signal causes AttributeError

### ISSUE THREAD

**Issue by pronobis** [davidhalter/jedi#568]
The original bug has been first reported for anaconda, but it turns out it's actually a problem in Jedi. Please see this report for bug description and discussion:
https://github.com/proofit404/anaconda-mode/issues/78

**Comment by davidhalter** [comment]
Please upgrade Jedi to the latest commit first and then report back. Thanks :)

**Comment by davidhalter** [comment]
N
