### ISSUE TITLE
goto assignement regression?

### ISSUE THREAD

**Issue by ColinDuquesnoy** [davidhalter/jedi#571]
Hello, 

Looks like there is a regression with ```Script.goto_assignments```. I noticed this issue because I have a few integration tests (pyqode) that are failing since you released jedi 0.9. 

I managed to reproduce the error with pure call to jedi API:

- test script:

```python
import jedi
code = 'foo = 10;print(foo)'
print(jedi.Script(code, column=len(code) - 2).goto_assignments())
```

- jedi 0.8.1 results:

```[<Definition foo = 10>]```

- jedi 0.9 results:

```[ ]```

**Comment by cpdean** [comment]
copying and pasting the test script into a repl yields the jedi 0.8.1 results:

```
$ mkvirtualenv jedi
Using real prefix '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7'
New python executable in jedi/bin/python2.7
Also creating executable in jedi/bin/python
Installing setuptools, pip, wheel...done.
$ python --version
Python 2.7.10
$ pip install jedi
Collecting jedi
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB)
    100% |████████████████████████████████| 159kB 1.3MB/s
Installing collected packages: jedi
Successfully installed jedi-0.9.0
$ python
Python 2.7.10 (default, Jul 13 2015, 12:18:59)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> code = 'foo = 10;print(foo)'
>>> print(jedi.Script(code, column=len(code) - 2).goto_assignments())
[<Definition foo = 10>]
>>>
$ pip freeze
jedi==0.9.0
wheel==0.24.0
```
I can't reproduce the issue.

jedi==0.9.0, python 2.7.10, OSX 10.9.5

**Comment by davidhalter** [comment]
Awesome, thanks!

**Comment by davidhalter** [comment]
Wait, sorry it doesn't work for me on the current linter branch, strange.

**Comment by cpdean** [comment]
:trump: womp womp

**Comment by cpdean** [comment]
ah yeah nvm what i said earlier.

I wasn't able to reproduce it in python2, but the error does show up in python3 -- which is probably what you're testing the linter branch in.

added failing test case with run instructions here https://github.com/cpdean/jedi/commit/d24b341866eb6540c537e8820212b177b4c327d4

**Comment by davidhalter** [comment]
Awesome, thanks!

**Comment by davidhalter** [comment]
Thanks for helping out with testing @cpdean!

Thanks for the issue @ColinDuquesnoy!
