### ISSUE TITLE
Semantic keyword completion

### ISSUE THREAD

**Issue by davidhalter** [davidhalter/jedi#580]
It would be nice if Jedi supported semantic keyword completion. Currently Jedi only lists keywords and adds them to the completion list. This doesn't make sense.

For example:

- `as` should never be able to be completed at the start of a line. (except after a `\`)
- keywords like `continue`, `try`, etc. should only be added after whitespace.

This is the easy part. It's getting more complicated if you want to check if it's possible to write `if`, for example it cannot be written after a bracket `(`, but after a name `x`: `x if foo else 3`.
To do that, we can either write a lot of code by hand or maybe abuse the parser somehow (inluding Parser.error_statements).

**Comment by squidarth** [comment]
@davidhalter I'm going to start taking a stab at this today
