### ISSUE TITLE
classmethod: no completion on instance of cls

### ISSUE THREAD

**Issue by ColinDuquesnoy** [davidhalter/jedi#582]
I tend to use the following code a lot, but jedi is unable to give completions on instance of cls:

```python
from PyQt5 import QtWidgets

class DlgPreferences(QtWidgets.QDialog):
    def __init__(self, parent):
        super().__init__()

    @classmethod
    def edit_preferences(cls, parent):
        dlg = cls(parent)
        dlg.  # no completion here
        cls.  # here I have some completions
```

This works fine in pycharm.

**Comment by davidhalter** [comment]
Yeah. Buggy :)

**Comment by davidhalter** [comment]
Trying to tackle this, I've realized that it's not that easy. I want a generic solution for this, but I think some parts of the Jedi core are still not good enough to actually do that. Might take another year ;)
