### ISSUE TITLE
Autocompletion for tkinter module unavailable

### ISSUE THREAD

**Issue by cryzed** [davidhalter/jedi#583]
Please see the issue [here](https://github.com/DamnWidget/anaconda/issues/315) for more detailed information. To sum it up: Jedi doesn't provide any autocompletion suggestions for the tkinter module or any of its submodules using Python 3.4.3 on Windows 7. The used Jedi version seems to be [0.9.0](https://github.com/DamnWidget/anaconda/blob/master/anaconda_lib/jedi/__init__.py).

**Comment by cryzed** [comment]
Any reason this wasn't marked as a bug as of yet? Was the error not reproducible?

**Comment by davidhalter** [comment]
Because I simply haven't marked it, yet :) (forgot to).

**Comment by cryzed** [comment]
Alright, thank you!

**Comment by Tantalus13A98B5F** [comment]
Sorry but I've got a question. I'm not understanding "mark". Doesn't Jedi word by parsing the code? Could you please tell me some more about this bug?

**Comment by davidhalter** [comment]
He meant marking the issue. I honestly have no idea about why Tkinter is not working. Haven't had time to look into it, yet.

**Comment by Tantalus13A98B5F** [comment]
Get it. Thanks.

**Comment by cryzed** [comment]
It actually [works again](http://i.imgur.com/hgjZvrX.png), using Sublime Text 3, Build 3095 and Python 3.4.3. I'm honestly not sure what changed since opening this bug.

**Comment by davidhalter** [comment]
@Tantalus13A98B5F Does it work for you as well? 

@cryzed Which jedi-vim version are you using?

**Comment by Tantalus13A98B5F** [comment]
I'm using the SublimeJEDI package for Sublime Text 3083 and it still goes wrong but just now I find that jedi works fine with tkinter in anaconda. That's it.

**Comment by davidhalter** [comment]
@Tantalus13A98B5F Well, since SublimeJedi just recently updated to Jedi 0.9.0, could you try again with it's latest commit?

**Comment by Tantalus13A98B5F** [comment]
One interesting thing. After I install Anaconda my SublimeJEDI comes right. Is it something related to memoization? By the way, both the version numbers are 0.9.0 but obviously the contents are different.

**Comment by Tantalus13A98B5F** [comment]
Recently updated....Sublime didn't give me any message so I didn't notice...Thanks.

**Comment by Tantalus13A98B5F** [comment]
The new one works fine. According to previous experience this issue may be caused by `\\$` which indicates the line to be continued not handled properly (for there used to be a `KeyError: '\\\r\n'`) in an old version of Jedi. Maybe this issue can be closed. (SublimeJEDI did something really NICE. They changed to version number to 0.9.0 before they really updated jedi version to 0.9.0 and stiil I can't get the new version from Package Control...orz

**Comment by davidhalter** [comment]
I will close then. Thanks :)
