### ISSUE TITLE
Jedi not autocompleting when *args or **kwargs are present in function definition

### ISSUE THREAD

**Issue by dougthor42** [davidhalter/jedi#588]
### Summary

In Spyder 2.3.4, Jedi autocompletion does not work when `*args` or `**kwargs` are present in a function definition.

### Steps to Reproduce
1. Open up a new python file.
2. Type the following:

    ```python
    def function(*args):
        my_variable = 5
        my_v
    #      ^ Press `tab` here
    ```

3. After typing `my_v`, press <kbd>Tab</kbd>. Notice that no autocompletion happens
4. Replace `*args` with `**dict_of_args`.
5. Press <kbd>Tab</kbd> in the same location as before. Again, autocompletion does not work.
6. Remove `**dict_of_args` and repeat. Autocompletion now works.

### Expected Output

Autocompletion of variable names should work even if `*args` or `**kwargs` are present in function definition.

### Additional Info

Cross-posted in [Spyderlib Issue #2439](https://github.com/spyder-ide/spyder/issues/2439)

Version: jedi 0.9.0

**Comment by davidhalter** [comment]
I cannot reproduce it. Could you try to reproduce it with direct Jedi calls? Also, have you tried to update to Jedi 0.9.0?

**Comment by dougthor42** [comment]
I'm not familiar with the direct calls, but I'll try my hand at it come Monday.

Also, I'm already on version 0.9.0.

**Comment by dougthor42** [comment]
It seems that Jedi is fine:

```
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> src = """def function(*args):
...     my_variable = 5
...     my_"""
>>> script = jedi.Script(src, 3, 6, '')
>>> script
<Script: ''>
>>> script.completions()
[<Completion: my_variable>]                                 # Correct
>>> src = """def function(*args):
...     my_variable = 5
...     fun"""
>>> script = jedi.Script(src, 3, 6, '')
>>> script.completions()
[<Completion: function>, <Completion: FutureWarning>]       # Correct
>>> src = """def function(*args):
...     my_variable = 5
...     arg"""
>>> script = jedi.Script(src, 3, 6, '')
>>> script.completions()
[<Completion: args>, <Completion: ArithmeticError>]         # Correct
```

---------
I looked into it a bit more, and it appears that Spyder has switched *back* to Rope for now. I thought it was using Jedi. So this bug is actually an issue with Rope.

Sorry about that!

**Comment by davidhalter** [comment]
Thanks for testing again! :)
