### ISSUE TITLE
bracket_start is wrong with str assignment

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#597]
I've noticed that `bracket_start` appears to be off with the following code (`|` being the cursor):

    foo = str(|)

It returns 3, but it should be 7 (1-based).

    jedi.Script("foo = str()", 1, 10).call_signatures()[0].bracket_start
    Out[11]: (1, 3)

The same applies to `foobar = str()`, where the offset should have changed, but it returns `3` for it, too.

**Comment by davidhalter** [comment]
I remember working on this and it should be working, now. Can you please check again? I will already close, but let me know if it's still not right!

(The example above returns `(1, 9)` now, which is correct IMO).

**Comment by blueyed** [comment]
Yes, confirmed.  It was fixed in 7ddc9c9.

Thanks!
