### ISSUE TITLE
Support linter hints

### ISSUE THREAD

**Issue by mriehl** [davidhalter/jedi#600]
I run jedi linting on a fairly big project, and basically the only error it reports is on the following code block:

``` python
        current_frame = inspect.currentframe()
        previous_frame = current_frame.f_back
        name_of_previous_frame = previous_frame.f_globals['__name__']
```

The reported error:

```
[WARN]  /data/home/mriehl/workspace/pybuilder/src/main/python/pybuilder/__init__.py:29:39: E1 AttributeError: <CompiledObject: None> has no attribute f_back.
```

What I'd like is to be able to tell jedi to ignore this line, so that I can break my build when jedi finds other problems. For example pep8 ignores lines when it finds the comment `noqa`.

**Comment by davidhalter** [comment]
Before implementing this, we should probably check how pylint, pyflakes and pycharm do this.

**Comment by mriehl** [comment]
* pep8: honors `# noqa` [for certain checks](https://github.com/jcrocholl/pep8/blob/master/docs/intro.rst)
* pylint: basically ignores it because the authors/maintainers think it's better than other linters.. but there's `# pylint: disable=all`. So their explicit goal is to **not** share a convention with the other tools
* flake8: (combines pep8 and pyflakes) honors `# NOQA`
* pyflakes: I wasn't able to find anything

**Comment by davidhalter** [comment]
I just decided not to follow up with this. The linter is basically dead.

I'm working on rewriting Jedi in Rust and maybe at that point we can use something like this, but it's far away and features like these are even further away.
