### ISSUE TITLE
No completion for subprocess with inner method before import

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#607]
Given the following code snippet there's no completion after `subprocess.`.

This is triggered by having an inline function before it, and the import not at the top of the file.

```
class Writer():
    def write(self):
        def foo():
            pass

        import subprocess
        subprocess.
```

It works with this:

```
import subprocess

class Writer():
    def write(self):
        def foo():
            pass

        subprocess.
```

This also works:

```
class Writer():
    def write(self):
        import subprocess
        subprocess.
```

I am using jedi-vim and jedi 7b50bb0.  I have not tested it outside of jedi-vim.

**Comment by blueyed** [comment]
The same is true for completion of just the following (if there's an inner method before it):

    foo = {}
    foo.

**Comment by davidhalter** [comment]
Strange, thanks for the report!

**Comment by blueyed** [comment]
> Edit: I seem to have different results (for the first example, Python 3.4):

Sorry I wasn't clear enough in my last comment: the full code would be:

    class Writer():
        def write(self):
            def foo():
                pass

            foo = {}
            foo.

**Comment by davidhalter** [comment]
Ok, thanks! It could be a `parser.fast` issue!

**Comment by davidhalter** [comment]
I have an xfailing test for this in the fast parser tests. I'm not sure when I'm going to fix it, because I might just refactor the whole fast parser.

**Comment by blueyed** [comment]
This appears to be fixed by now, closing.

@davidhalter 
The only xfail test seems to be b1fbc51 / `test_parentheses_in_string` though.
Please verify that this is covered correctly in the tests.

**Comment by davidhalter** [comment]
Just leaving it open. Since the "fast" parser has been replaced by a "diff" parser, it will definitely not be an issue anymore (in this sense), but miight have other issues.

**Comment by davidhalter** [comment]
This one seems to be fixed still and I assume that it's not really an issue anymore. The parser works now in very different ways and has very different issues.
