### ISSUE TITLE
Infinite recursion when a global variable is not defined globally

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#610]
Backtrace:

```
Traceback (most recent call last):
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 290, in _name_to_types
    search_global=True)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 290, in _name_to_types
    search_global=True)
[...]
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 79, in __init__
    self.scope = evaluator.wrap(scope)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 93, in wrap
    if isinstance(element, tree.Class):
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

A user managed to identify this problem as happening when a global variable is referenced from two different functions using the `global` keyword, the variable is not defined in the global scope at all, and Jedi tries to complete methods from the object.

Reproduction with Python 2.7.3 and Jedi 0.9.0:

```Python
import jedi

source = '''\                                                                   
def funct1():                                                                   
    global global_dict_var                                                      
    global_dict_var = dict()                                                    
                                                                                
def funct2():                                                                   
    global global_dict_var                                                      
    q = global_dict_var.copy()                                                  
    print(q)                                                                    
'''

script = jedi.Script(line=7, column=28, source=source)
script.completions()
```

Originally reported as jorgenschaefer/elpy#519

**Comment by cpdean** [comment]
should jedi infer that `global_dict_var` can only be brought into scope by running `funct1` first?

What should happen if there are more than one functions that have globally-leaking side effects, like this?

```
def funct1():                                                                   
    global global_dict_var                                                      
    global_dict_var = dict()       

def other_funct1():                                                                   
    global global_dict_var                                                      
    global_dict_var = list()                                                       

def funct2():                                                                   
    global global_dict_var                                                      
    q = global_dict_var.copy()                                                  
    print(q) 
```

**Comment by cpdean** [comment]
I've added the failing test case to the suite https://github.com/cpdean/jedi/commit/88d11bfbf7d5e5d68ce62280f024629bd910e271

@davidhalter even if the first function is called within the scope of the second, as I've done, does this make sense for jedi to be able to infer that global will be a dict?  or should jedi error-out early before the recursion depth gets exceeded?

**Comment by davidhalter** [comment]
> What should happen if there is more than one function that have globally-leaking side effects, like this?

Well, that is a good question. I don't really have a solid answer for it. I would probably just return all three. I don't actually know what Jedi does, because I haven't touched the globals logic for a long time. IMO, we should either return all of them, None or evaluate more precisely which value that variable can have at any given point.

> @davidhalter even if the first function is called within the scope of the second, as I've done, does this make sense for jedi to be able to infer that global will be a dict? or should jedi error-out early before the recursion depth gets exceeded?

Jedi should be able to infer the correct types in your examples. If it doesn't, I'm pretty sure that a certain cache check is missing. I think it makes sense for Jedi to infer there, but that is debatable.

**Comment by cpdean** [comment]
what about in the original case where the first function isn't called?

**Comment by davidhalter** [comment]
Doesn't make a difference. Jedi works with lazy evaluation (backtracking). That function is just ignored, because it doesn't contain a return value that would be needed. This is obviously not correct Python evaluation (since it matters if it was executed or not), however Jedi just ignores certain function, because full evaluation of the source code would be difficult and time intensive.
