### ISSUE TITLE
__call__ autocomplete does not work.

### ISSUE THREAD

**Issue by breerly** [davidhalter/jedi#613]
Parameters do not autocomplete for this example:

```
class Test(object):
    def __call__(self, hello):
        pass

t = Test()
t("hi")  # did not autosuggest params!
```

**Comment by breerly** [comment]
Looks like Pycharm doesn't support either:

https://youtrack.jetbrains.com/issue/PY-12425

**Comment by davidhalter** [comment]
Good idea. But low priority. :)
