### ISSUE TITLE
Module names completion doesn't work in IPython

### ISSUE THREAD

**Issue by nevillegao** [davidhalter/jedi#614]
I write following lines in .pythonrc:
from jedi.utils import setup_readline
setup_readline()

When I launch ipython, completion doesn't work.
In [1]: import st"TAB"  # nothing happens here

**Comment by davidhalter** [comment]
It seems to not work properly with IPython, see also PR https://github.com/davidhalter/jedi/pull/321.

However there seem to be people working on this (on the IPython side). I think they want to make Jedi the default for IPython.
