### ISSUE TITLE
can't complete c++ classes exposed via boost.python

### ISSUE THREAD

**Issue by jsholmes** [davidhalter/jedi#615]
I'm using jedi-vim.  for any completion of a boost.python exposed class, it just prints:
ImportError: No module named Boost.Python.

I think this is because of the way boost.python exposes things.

Consider a c++ class Foo.  If I expose this via boost.python, in python, if I do:

```
> python
import foo
help(foo)
```

I see something like:

```python
class Foo(Boost.Python.instance)
    Method resolution order:
        Foo
        Boost.Python.instance
        __builtin__.object
```
Boost.Python isn't actually anything in python, though:

```
In [8]: help Boost.Python
  File "<ipython-input-8-ec5e154aa705>", line 1
    help Boost.Python
             ^
SyntaxError: invalid syntax


In [9]: import Boost.Python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-849dd2676ec2> in <module>()
----> 1 import Boost.Python

ImportError: No module named Boost.Python
```

It would be great if jedi would just ignore the failed import and do completions based on the methods already exposed via the Foo class, maybe?  I guess it's relying on __name__ of a class being something that's a valid identifier, but that seems like a flawed assumption?

**Comment by davidhalter** [comment]
`help Boost.Python` is a syntax Error. You have to call it like this:

    help(Boost.Python)

**Comment by jsholmes** [comment]
I was calling it like that, in my first try..  Sorry for the bad copy/paste.

Here's more detail:

```python

Traceback (most recent call last):
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi_vim.py", line 110, in wrapper
    return func(*args, **kwargs)
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi_vim.py", line 321, in show_call_signatures
    signatures = get_script().call_signatures()
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi/jedi/api/__init__.py", line 521, in call_signatures
    self.source, self._pos)
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi/jedi/cache.py", line 93, in wrapper
    value = next(generator)
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi/jedi/cache.py", line 115, in cache_call_signatures
    yield evaluator.eval_element(call)
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi/jedi/evaluate/__init__.py", line 257, in eval_trailer
    new_types += self.find_types(typ, node)
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi/jedi/evaluate/__init__.py", line 117, in find_types
    scopes = f.scopes(search_global)
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi/jedi/evaluate/finder.py", line 109, in scopes
    return ((n, None) for n in self.scope.names_dicts(search_global))
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi/jedi/evaluate/cache.py", line 43, in wrapper
    rv = list(rv)
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi/jedi/evaluate/representation.py", line 189, in names_dicts
    for s in self.base.py__mro__(self._evaluator)[1:]:
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi/jedi/evaluate/compiled/__init__.py", line 68, in py__mro__
    return tuple(create(evaluator, cls, self.parent) for cls in self.obj.__mro__)
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi/jedi/evaluate/compiled/__init__.py", line 68, in <genexpr>
    return tuple(create(evaluator, cls, self.parent) for cls in self.obj.__mro__)
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi/jedi/evaluate/compiled/__init__.py", line 505, in wrapper
    result = func(evaluator, obj, parent, module)
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi/jedi/evaluate/compiled/__init__.py", line 520, in create
    faked = fake.get_faked(module and module.obj, obj)
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi/jedi/evaluate/compiled/fake.py", line 102, in get_faked
    result = _faked(module, obj, name)
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi/jedi/evaluate/compiled/fake.py", line 73, in _faked
    module = get_module(obj)
  File "/Users/john/.dotfiles/vim/macos_vundles/jedi-vim/jedi/jedi/evaluate/compiled/fake.py", line 67, in get_module
    return __import__(imp_plz)
ImportError: No module named Boost.Python
```

**Comment by jsholmes** [comment]
As for boost python: https://wiki.python.org/moin/boost.python/HowTo

**Comment by jsholmes** [comment]
Note also, that I can complete based on the class name, but not a class instance.

e.g.:

```python
# assume Foo has some method .bar() and is in package foo, extension package _foo.

f = Foo()
f.   # <-- this gives the No module named Boost.Python error

Foo.  # <-- this shows the .bar() method like: bar       function: foo._foo.Foo.bar
```

**Comment by davidhalter** [comment]
I still don't get how I would install that, which PyPI package it is and where the source code of `boost.python` lies. Can you help me out? I tried the boost website, but it's way too complicated.

**Comment by wrosecrans** [comment]
Boos python isn't going to be in PyPI  because it isn't directly useful
from Python.  It's a library used from C++ when you have C++ classes that
you want to make available to Python.  You might theoretically create some
module in PyPI by wrapping a native code library using Boost.Python.  I
once used it in an application I wrote to expose guts of the application to
an embedded Python script editor.  I wrote a blog post about some of that,
maybe skimming it will clarify for you more readily than digging through
all the boost docs:

https://willrosecrans.wordpress.com/2015/01/31/embedding-python-in-my-app-part-ii-the-desolation-of-documentation/

Because all of the Boost.Python classes show up as "built in" you won't be
able to have Jedi directly parse python source to figure out what makes up
a Boost Python class from first principles.  It would have to be done live
from introspection because it can all happen arbitrarily at run time in C++
code.

**Comment by davidhalter** [comment]
But how do you install it then? It's still accessible from the shell. See, I'm still tapping in darkness.

And what does `help(Boost.Python)` yield?

**Comment by jsholmes** [comment]
```python
In [2]: help(Boost.Python)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-588980a249ac> in <module>()
----> 1 help(Boost.Python)

NameError: name 'Boost' is not defined
```

Here's some more info on this: https://wiki.python.org/moin/boost.python/ExportingClasses

Boost.python produces a .so file that python is able to expose.

So for example, for an exposed module called foopy, it will produce something like:

```bash
foopy/
    __init__.py
    _foopy.so
```

The foopy/__init__.py will have:
```python
from ._foopy import *
```

Then if I do, in python, help(foopy), I see:

```python
Help on package foopy:

NAME
    foopy

FILE
    /lib/foopy/__init__.py

DESCRIPTION
    # Some stuff about foopy

PACKAGE CONTENTS
    _foopy

...
```

And if I do help(foopy._foopy), I get:

```python
Help on module foopy._foopy in foopy:

NAME
    foopy._foopy

FILE
    /lib/foopy/_foopy.so

CLASSES
    Boost.Python.enum(__builtin__.int)
        FooType
    Boost.Python.instance(__builtin__.object)
        SomeClass
        AMoreDifferentClass

...
```

It looks like probably Jedi could support this using the auto_import_module feature, though I can't figure out how to enable that from jedi-vim?

```
jedi.settings.auto_import_modules = ['hashlib']
Modules that are not analyzed but imported, although they contain Python code. This improves autocompletion for libraries that use setattr or globals() modifications a lot.
```

**Comment by jsholmes** [comment]
and just for completeness, if I do:
help(foopy._foopy.AMoreDifferentClass)

I get something like:

```python
Help on class AMoreDifferentClass in module foopy._foopy:

class AMoreDifferentClass(Boost.Python.instance)
 |  Method resolution order:
 |      AMoreDifferentClass
 |      Boost.Python.instance
 |      __builtin__.object
 |
 |  Methods defined here:
 |
 |  __init__(...)
 | ...
```

**Comment by davidhalter** [comment]
Ok. I get it. Hmm I think this is just a Jedi bug. It should probably return None if there's an ImportError at that point. And then later we have to check for the case where `get_module` returns None and we're done.

I think that's all there is to it. Maybe make a comment as well that this catch happens, because of Boost.Python.

**Comment by jsholmes** [comment]
Ok.  Let me know if you want me to test out a fix.

**Comment by davidhalter** [comment]
I will probably not do it for the next few months. If you want me to help you (if you do a PR), let me know it.

**Comment by davidhalter** [comment]
The import error is being caught at the moment, so this issue would be fixed.
