### ISSUE TITLE
import jedi failed

### ISSUE THREAD

**Issue by Jellyrick** [davidhalter/jedi#619]
In [4]: import pydoc_topics
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-cb99eaab0f29> in <module>()
----> 1 import pydoc_topics

ImportError: No module named pydoc_topics

**Comment by davidhalter** [comment]
Where does this come from? How did you achieve this or how can we reproduce this?

**Comment by Jellyrick** [comment]
i wan't use jedi in youcomplete me. system is centos 7.0 , when use :YcmCompleter GotoDefinition in .py ycm tips "ImportError: Error importing jedi. Make sure the jedi submodule has been checked out". but I have already do this. so i open ipython, just put  "import jedi", will reproduce this

**Comment by davidhalter** [comment]
@Jellyrick Pretty sure this is an issue with YCM. I'm also pretty sure that you just didn't install it correctly. Go to their issue tracker or try it with their very well written installation docs again.
