### ISSUE TITLE
issue on completion when importing scipy

### ISSUE THREAD

**Issue by oracleyue** [davidhalter/jedi#620]
(I have known the intrinsic complicate issue in `scipy`, as indicated in https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/mMiv9QslB4E.)

Could you confirm the following problem of "jedi"? Is it a bug or just the way I misused python? Thanks!
 
`jedi` seems to have slightly problems in understanding the following `import` statement:
```python
from scipy import linalg
```
When I run `linalg.`, there is no regular functions in list, but certain ones like `__xxx__`. This is legal in python, which I have tested on completion in IPython. In addition, the following import also fails to work in `jedi`
```python
import scipy.linalg
scipy.linalg. (<--- no completion; valid in IPython completion)
```

I would not say it's a big bug, since `jedi` understands the other `import` style:
```python
import scipy.linalg as la
```
When I run `la.`, everything works fine. Currently I use `import scipy.linalg as linalg` as alternative to `from scipy import linalg`, whose style seems pretty odd. 
Moreover, `jedi` actually understand `from ... import ...` statement, e.g.
```python
from scipy.linalg import norm
```
When I use `norm()`, `jedi` gives the correct call signatures.

In a sum, it seems that problem only happens when using `from scipy import ...` to import subpackages (like `linalg`, `optimize`, etc.; these are actually directories, according to the webpage I attached at beginning).

May I ask whether there would be lots of work to make `jedi` understand `from scipy import linalg`?
Thanks a lot!

(FYI, I use emacs-jedi, and have fired the same issue https://github.com/tkf/emacs-jedi/issues/243. I posted it here again since I am not sure whether the developers of jedi can see that issue. 
If it bumps, please delete this one.)

**Comment by davidhalter** [comment]
Probably a Jedi issue, but I have currently no time to track it down.

**Comment by davidhalter** [comment]
I have trouble to get good completions for `scipy.linalg`, but at least I get the same for some import styles. I know that I have refactored the import logic. I'm pretty sure it's working now, so I'm closing.

Feel free to comment if it's not working and I will reopen.
