### ISSUE TITLE
Dependency of auto-complete

### ISSUE THREAD

**Issue by MagisDing** [davidhalter/jedi#623]
I have just switched form auto-complete mode to company mode, but the error message 
>Warning (emacs): Unable to activate package `jedi'.
Required package `auto-complete-1.4' is unavailable
 
pops out. Do I have to install "auto-complete" (even I don't use it) to activate jedi?

**Comment by davidhalter** [comment]
This is not a Jedi issue. Try reporting it in the corresponding tracker (company mode?). Jedi doesn't have anything to do directly with emacs.
