### ISSUE TITLE
Jedi could not find modules in eggs

### ISSUE THREAD

**Issue by immerrr** [davidhalter/jedi#627]
I stumbled upon this several days ago when tried to look up a freshly installed module that came in a wheel package.  The problem seems to be that pre33-module finder uses `imp` module that does not support eggs:

https://github.com/davidhalter/jedi/blob/fbe26ab64a75753eb4f3baa268e8bfd3b4310a7c/jedi/_compatibility.py#L57

It could be improved by reimplementing module lookup mechanism using ``pkgutil.ImpLoader`` for regular modules and ``zipimport.zipimporter`` for eggs.  And during reimplementation we can make it work on custom lists, not necessarily `sys.path`, so the `sys.path` swap trick will become unnecessary, too.

**Comment by davidhalter** [comment]
Yeah, should definitely be improved. Thanks for the report.

**Comment by davidhalter** [comment]
How is that related to your latest pull request?

**Comment by immerrr** [comment]
It is not related, at least directly. It will help to further separate `Evaluator.sys_path` and the `sys.path`  as you won't need to do the `sys.path, oldpath = sys_path, sys.path` trick. But other than that I think they are pretty independent.

**Comment by davidhalter** [comment]
I was thinking about the egg-links.

**Comment by immerrr** [comment]
egg-links to me really seem like a NIH version of .pth links implemented for "pkg_resources".

**Comment by immerrr** [comment]
Ah, indeed, I have forgotten about that. Egg files are added to path with .pth files installed by setuptools/pip, so any improvement in module loading will be useless until .pth files are handled.

**Comment by sadovnychyi** [comment]
@immerrr maybe you could try to test my PR?

https://github.com/davidhalter/jedi/pull/745

**Comment by davidhalter** [comment]
This should have been fixed by #745. If it didn't get fixed, let me know!
