### ISSUE TITLE
No support for python 3.5 under virtualenv

### ISSUE THREAD

**Issue by nicorevin** [davidhalter/jedi#629]
I have no omni completion (and jump-to-declarations) for all packages except my current working project.
Throws `Omni completion (^O^N^P) Pattern not found`.
Works ok with python2.7 for example. 

Env: linux 4.2.2, vim 7.4.884, jedi 0.9.0, latest vim-jedi...

Point me please how can I help to add support for python3.5

**Comment by davidhalter** [comment]
Can you try to confirm this with just Jedi (use `jedi.api.Script.completions()`)?

**Comment by nicorevin** [comment]
Ok with that
```Python
In [20]: from jedi.api import Script                                                                                                                                                 

In [21]: source = '''from flask import j'''

In [22]: s = Script(source)

In [23]: s.completions()
Out[23]: [<Completion: json>, <Completion: json_available>, <Completion: jsonify>]```

**Comment by nicorevin** [comment]
So, seems like jedi-vim completion works only with 2.7. Both 3.4 and 3.5 do not work. If it matters, I'm using archlinux. jedi-vim is installed via Vundle.

**Comment by davidhalter** [comment]
What do you mean with `do not work`? Is the output empty? Or is there an exception?

**Comment by nicorevin** [comment]
`Omni completion (^O^N^P) Pattern not found`

**Comment by davidhalter** [comment]
This is not the output of IPython, it's the output of VIM.

**Comment by nicorevin** [comment]
I've mentioned that jedi itself works ok under different environments, but in vim it works only in python2 virtualenv.

**Comment by davidhalter** [comment]
Hmm ok. Then please add it to jedi-vim as an issue. Thanks.

It might have to do something with the virtualenv/VIM combination.
