### ISSUE TITLE
Hinting the type using docstring of class

### ISSUE THREAD

**Issue by emacsway-qarea** [davidhalter/jedi#631]
Hi all.
It will be great to add hinting the type using docstring of class like here https://www.jetbrains.com/pycharm/help/type-hinting-in-pycharm.html#d290117e333
Otherwise, it is difficult to work if the project uses the dependency injection.
Thanks.

**Comment by davidhalter** [comment]
> Otherwise, it is difficult to work if the project uses the dependency injection.

Can you give me an example, please?

**Comment by emacsway-qarea** [comment]
Hi, @davidhalter 
Thanks for answer.
See example in screen-shot http://joxi.ru/xAeJ3ONSjvD4ry

**Comment by davidhalter** [comment]
Hmm ok. Is that a feature that is generally used like that? (Because it might be a bit confusing in comination with the `__init__` function).

**Comment by emacsway-qarea** [comment]
Not always. As C.Martin says, "The class takes no direct steps to resolve its dependencies; it is completely passive." (Clean Code, 157). It can be also resolved by getter/setter, but usually our team uses simple property for it.

**Comment by davidhalter** [comment]
What I meant to ask is: Are docstrings at the start of a class generally used like that? (Because it might be a bit confusing in comination with the __init__ function). Might it not be possible that a lot of people start the class with definitions for the `__init__` function?

**Comment by emacsway-qarea** [comment]
Currently I just define required variable (for example self.dao.engine) in python shell, and call "M-x python-shell-completion-complete-or-indent" or "M-x completion-at-point function" in file buffer.
Because elpy [disables](https://github.com/jorgenschaefer/elpy/blob/3e7e08d14998063ce254cd1934786e7e212b99e3/elpy.el#L3101) call completion-at-point function, I've [bind](https://bitbucket.org/emacsway/.emacs.d/src/a9efa266fe252cd59491326c620c00817dc22b6a/init.el?at=default&fileviewer=file-view-default#init.el-37) completion-at-point function to "C-c TAB".

So, it works for me. But our developers, what uses PyCharm, uses for this purpose docstrings of class. It's documented feature of PyCharm. And more convenient way.

I think, it will be great to check class attributes docstrings only if it can't be resolved in any other way (by constructor __init__). Or just override class defined types by __init__ defined types.

**Comment by emacsway-qarea** [comment]
> start the class with definitions for the __init__ function?

Usually __init__() used to define state of object, not dependencies. [Great article](http://www.martinfowler.com/articles/injection.html) about DI. Three ways to inject dependencies: Constructor Injection, Setter Injection, and Interface Injection.

**Comment by davidhalter** [comment]
I think this should be implemented. But I don't have time for it, now.

**Comment by emacsway-qarea** [comment]
HI, @davidhalter
I've created [hinting the type for rope](https://github.com/python-rope/rope/pull/133) at this weekend.
It's need me for refactoring. Btw, I've adopted a few functions from your jedi (with link to author, of course).
But I still using jedi for autocomplete.
I'll try to find time to do it for jedi.

**Comment by emacsway-qarea** [comment]
[Currently added](https://github.com/davidhalter/jedi/compare/master...emacsway:master) supporting of type hinting using docstrings of class interface.
Have left to do only type hinting for class attributes.

**Comment by davidhalter** [comment]
Ok. I'm still not 100% sure what you want. Because when I look at your tests I don't see anything "new". I don't really understand the code, so I cannot tell.

Know that I'm very hesitant in merging something about docstring types now, because this is not the default way anymore of doing type annotations. PEP 484 has changed this quite a bit. #664 will introduce type annotations with comments and that will also be enough for your example above.

**Comment by emacsway-qarea** [comment]
> I'm still not 100% sure what you want.

- Currently I've added type hinting using docstrings defined in interface. There is no need anymore copy type definition from class interface to class realization.

The next step is type hinting for class attributes:
- https://www.jetbrains.com/pycharm/help/type-hinting-in-pycharm.html#d290117e333
- https://github.com/emacsway/rope/blob/master/ropetest/docstringstest.py#L63

> Know that I'm very hesitant in merging something about docstring types now, because this is not the default way anymore of doing type annotations. PEP 484 has changed this quite a bit. #664 will introduce type annotations with comments and that will also be enough for your example above.

- It will be great. https://www.jetbrains.com/pycharm/help/type-hinting-in-pycharm.html#d316912e149
Yes, it solves my problem. I work with Python2 and many developers uses PyCharm. Thanks.

**Comment by davidhalter** [comment]
> and many developers use PyCharm

This has nothing to do with PyCharm, it's a PEP.

**Comment by emacsway-qarea** [comment]
I mean, currently only PyCharm supports pep-0484. So, pep-0484 is satisfy me, because it can be used by all team, if VIM and Emacs also will support pep-0484.

Btw, it well be good to support for Python2 type hinting based on docstrings of class interface (not realization). I've already [implemented it](https://github.com/davidhalter/jedi/compare/master...emacsway:master).

**Comment by davidhalter** [comment]
Fixed!

**Comment by emacsway** [comment]
Thanks!
