### ISSUE TITLE
autocomplete support for compiled .dll libraries

### ISSUE THREAD

**Issue by mostaphaRoudsari** [davidhalter/jedi#632]
Does jedi support autocomplete for binary libraries. I'm using [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) which is built on top of  jedi - for IronPython development. I'm not sure if this is a limitation with jedi or the plugin doesn't use jedi's full functionality.

**Comment by davidhalter** [comment]
Well, Jedi supports compiled libraries, but I'm not sure if it supports anything that works just with IronPython. There's currently no support for IronPython, if it works it does, but probbly it doesn't.

**Comment by mostaphaRoudsari** [comment]
Thanks @davidhalter for the note. I have tried with a couple of libraries (e.g. clr) and it didn't work. What would be the best approach to get it started. For now I modified the code for the package (and not Jedi) to get it to work for my purpose using API documentation and [it works for the libraries that I use the most](https://gist.github.com/mostaphaRoudsari/eeeeb97490683650a35d#file-autocomplete-gif) but that's pretty hacky. Is it something that I can play around with? What is the best approach to get it started?

**Comment by davidhalter** [comment]
I have no idea. I don't even understand the actual problem.

**Comment by mostaphaRoudsari** [comment]
Sorry for the long delay to reply.
To be more specific does Jedi support auto-complete for .NET dll libraries. How does Jedi deals with [System](https://msdn.microsoft.com/en-us/library/system(v=vs.110).aspx) for example?  How does Jedi deals with ```import System``` in a .py file? It currently doesn't work but is it possible to get it to work? and where should I get started. I hope this makes it a little bit more clear. Thanks :)

**Comment by davidhalter** [comment]
Well, as I said, there's no explicit support for IronPython. Since you're running it and you're using `autocomplete-python` at the same time, the actual issue will probably be that `autocomplete-python` is not using IronPython but just normal Python. This makes sense for an autocompletion plugin, but it's not what you want.

If you're interested in this, please first just run Jedi's test suite on IronPython and post the results here. I'm not sure if it even works (and I cannot test it, since I don't have a windows installed here).

**Comment by mostaphaRoudsari** [comment]
Great! That sounds like a  good starting point. I will be on vacation next week but I will give it a try once I get back.

**Comment by mostaphaRoudsari** [comment]
I'm closing this issue for now. It seems to be easier to be done using [omni-sharp](https://github.com/OmniSharp/omnisharp-roslyn/issues/372). Thanks for your support.

**Comment by gtalarico** [comment]
https://github.com/gtalarico/ironpython-stubs
