### ISSUE TITLE
Script.call_signatures fails for decorated functions

### ISSUE THREAD

**Issue by shiyuangu** [davidhalter/jedi#634]
Hi, 
    Jedi seems not able to get the signatures for decorated functions.  In the following example, Script.call_signatures() returns "kwargs" which is not useful. 

``` python
import jedi
from elasticsearch import Elasticsearch
source = """from elasticsearch import Elasticsearch
es = Elasticsearch()
es.search()"""
script = jedi.Script(source,3,10,"tmp.py")

>> script.call_signatures()[0].params
returns:  [<_Param **kwargs>]
```

The signature of the es.search() is  as follows (the full source code can be downloaded from https://www.elastic.co/downloads/elasticsearch)

``` python
   @query_params('_source', '_source_exclude', '_source_include',
        'allow_no_indices', 'analyze_wildcard', 'analyzer', 'default_operator',
        'df', 'expand_wildcards', 'explain', 'fielddata_fields', 'fields',
        'from_', 'ignore_unavailable', 'lenient', 'lowercase_expanded_terms',
        'preference', 'q', 'request_cache', 'routing', 'scroll', 'search_type',
        'size', 'sort', 'stats', 'suggest_field', 'suggest_mode',
        'suggest_size', 'suggest_text', 'terminate_after', 'timeout',
        'track_scores', 'version')
    def search(self, index=None, doc_type=None, body=None, params=None):
```

**Comment by davidhalter** [comment]
I'm not sure how to solve this. Even when we start to speak about API perspectives. We could of course ignore decorators. But what if someone doesn't use them, should we also ignore them?

```

def _search(self, index=None, doc_type=None, body=None, params=None):
    pass

def search(*args, **kwargs):
    # do something that could be done within a generator.

Should we also ignore that as well? Because it's fundamentally the same issue. In context of certain class methods or APIs this is definitely used a lot.

**Comment by davidhalter** [comment]
This is now working a lot better, since Jedi tries to resolve `**kwargs` now.

However, the logic for `elasticsearch` is so complicated that it's almost impossible to understand how the query params can be used. If we ever want to make this possible, we should look into a plugin system (#626).

So it's better, but it's not perfect. But I'll close this, I don't feel like it needs to be perfect.
