### ISSUE TITLE
Spurious added = in completion candidates

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#643]
Hello! I have seen a few weird cases where Jedi returns all possible completion candidates with an equals sign (`=`) as a suffix, apparently assuming those are possible keyword arguments to the called function. Sadly, this only happens in some files, and only sometimes – the same file can work perfectly fine usually, but break otherwise. I refrained from opening a bug report for a while due to this completely unhelpful description, but as I am now solving the problem by simply stripping equals signs, I figured I'd at least make you aware of this effect in case others report it as well.

(Only slightly) more information at jorgenschaefer/elpy#613

Typical example:

```Python
def foo(barbaz):
    return str(bar_|_
```

This will – under those unclear circumstances – provide a completion candidate of `barbaz=` instead of `barbaz`.

**Comment by davidhalter** [comment]
I have noticed it, too. It happens I think when you call it on names that resolve to params. But I'm not sure.

**Comment by davidhalter** [comment]
Fixed it.
