### ISSUE TITLE
Jedi ignores keyboard-translate in Emacs config

### ISSUE THREAD

**Issue by therabidmachine** [davidhalter/jedi#645]
In my Emacs config I have `keyboard-translate` set up to change brackets I type into parentheses. After I select a completion there is a chance (maybe 50/50) that when I type a bracket expecting it to change to a paren it will stay a bracket.

**Comment by davidhalter** [comment]
Look at the front page, there's a list of emacs plugins. However this is just a Python library that is used by those plugins. Post to the issue tracker of the corresponding project.
