### ISSUE TITLE
Flicker / extraneous output in echo area and *Messages*

### ISSUE THREAD

**Issue by davidswelt** [davidhalter/jedi#648]
Whenever I type the name of a variable that cannot be found, the echo line flickers (momentarily enlarges to accommodate extra output) and then shows "nil".  *Messages* shows:

> no Python documentation found for 'a'
> 
> nil

Expected behavior: if documentation cannot be found, do not output anything in the echo area as not to distract the user.  

Just installed version 0.2.6 from MELPA.
Python mode 6.2.0.
Aquamacs 3.x development version.  Can't get it to work on basic Emacs 25.1.

**Comment by davidhalter** [comment]
I have no idea what this is, it's definitely not a Jedi issue. Please submit this bug to your Jedi emacs plugin issue tracker.

Sorry, I'm not an emacs user, I really cannot help you.
