### ISSUE TITLE
Deferred Error in basic cmd: C-c .

### ISSUE THREAD

**Issue by JoshuaDPItts** [davidhalter/jedi#653]
I am getting the following in emacs after a basic install on OSX (note that I had this working previously on same env):
deferred error : (error "\"AttributeError(\\\"type object 'Script' has no attribute 'goto'\\\",)\"")
I followed a few of the stems recommended to produce traceback, but I'm not sure how much more may be needed for you all to see what's happening:

ERROR:epc:AttributeError("'Script' object has no attribute 'get_in_function_call'",)
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/Users/jpitts/.emacs.d/.python-environments/default/lib/python2.7/site-packages/epc/handler.\
py", line 242, in _handle
    reply = handler(uid, *args)
  File "/Users/jpitts/.emacs.d/.python-environments/default/lib/python2.7/site-packages/epc/utils.py\
", line 51, in new_method
    ret = method(self, *args, **kwds)
  File "/Users/jpitts/.emacs.d/.python-environments/default/lib/python2.7/site-packages/epc/handler.\
py", line 265, in _handle_call
    return ['return', uid, func(*args)]
  File "/Users/jpitts/.emacs.d/.python-environments/default/lib/python2.7/site-packages/jediepcserve\
r.py", line 90, in get_in_function_call
    call_def = jedi_script(*args).get_in_function_call()
AttributeError: 'Script' object has no attribute 'get_in_function_call'

**Comment by davidhalter** [comment]
Jedi is a library. It has nothing to do with emacs. You should post this in your corresponding emacs plugin tracker.

**Comment by JoshuaDPItts** [comment]
I'm not sure how this isn't a jedi issue. I followed all the debugging notes here: http://tkf.github.io/emacs-jedi/latest/ 
which specifically pointed to cases when this library continues to throw this exact error to post a bug here:
https://github.com/davidhalter/jedi/issues

**Comment by davidhalter** [comment]
Ah, Now I see. Still this is not a Jedi error. A Jedi error is something that you can reproduce with Jedi itself. emacs-jedi is calling `Script.get_in_function_call` here, which it shouldn't, because it doesn't exist in Jedi 0.9.0. `Script.get_in_function_call` was deprecated in Jedi 0.6.0 - a very long time ago and has been removed in Jedi 0.9.0.
