### ISSUE TITLE
Shows docstring of own file in imports

### ISSUE THREAD

**Issue by sadovnychyi** [davidhalter/jedi#656]
```python
import jedi
s = jedi.Script('''"""test"""
import a''', 2, 8)
c = s.completions()[0]
print(c.name, c.docstring()) # ('abc', 'test')
```
Expected empty string for docstring, got own docstring instead.

sadovnychyi/autocomplete-python#133

**Comment by davidhalter** [comment]
This is fixed now. However, since this might massively decrease performance, it's not enabled by default. You can enable it with `docstring(fast=False)` (see test changes), but I wouldn't recommend it at this point.
