### ISSUE TITLE
Missing completions in "from X import A, B" form

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#657]
Hello!
For the form `from X import `, Jedi gives correct completions for items in `X`, but for the form `from X import A, `, Jedi offers completions only for global names.

Example:

```Python
import jedi

s1 = jedi.Script("from itertools import ", line=1, column=22)
s2 = jedi.Script("from itertools import chain, ", line=1, column=29)
c1 = s1.completions()
c2 = s2.completions()
```

Here, `c1` contains `chain`, `combinations`, etc., but `c2` contains global `abs`, `all`, etc. I would expect both `c1` and `c2` to be equal.

(Originally reported as jorgenschaefer/elpy#732 )

**Comment by davidhalter** [comment]
I know. Haven't found a very easy way to fix it (the import system completion system is already a huge mess).

**Comment by davidhalter** [comment]
This has significantly improved, when I started using the parser to give Jedi sematic completions.

Now there's no magic anymore in the code and everything should work as expected. (except if the type inferences messes up)
