### ISSUE TITLE
linter: comparing to `...`

### ISSUE THREAD

**Issue by reinhrst** [davidhalter/jedi#670]
The next test fails: (on e34c0b3 )
```
if 1 == ...:
    x = 1
else:
    x = "str"
#? str()
x
```
It doesn't seem to matter what I put before the `...`, feels like jedi always evaluates comparisons to `...` to true.

**Comment by davidhalter** [comment]
Ok. This is something we can definitely fix ( I think).

**Comment by davidhalter** [comment]
I just fixed this. Ellipsis was just ignored (`...`).
