### ISSUE TITLE
goto_definitions() return different results if on first char of attribute

### ISSUE THREAD

**Issue by vheon** [davidhalter/jedi#671]
While I was working on [vheon/JediHTTP](https://github.com/vheon/JediHTTP) for https://github.com/Valloric/ycmd/pull/246 we have discovered this:

```python
import jedi
content = """class Foo(object):
  bar = 1
"""
script = jedi.Script( content, 2, 2 )
script.goto_definitions()
[]
script = jedi.Script( content, 2, 3 )
script.goto_definitions()
[<Definition class int>]
```

being jedi's column 0-based, column 2 should be the `b` of `bar` while 3 should be `a` of `bar`, is that correct?

I don't know if it is specific to attributes or if is true in other scenarios.

**Comment by davidhalter** [comment]
Jedi actually works "between" letters and tries to guess which side it should evaluate. But you're still right, because `2` is between ` b`, which should still work.

**Comment by leonweber** [comment]
Can confirm this. This test fails: 

```python
def test_goto_definition_between_whitespace_and_char():
    s = dedent('''\
    class Foo(object):
        bar = 1
    ''')
    assert len(api.Script(s, line=2, column=4).goto_definitions()) == 1
```

I looked into it and found that tree::get_statement_for_position((2,4)) returns
```<operator: >```. I figured it should return either whitespace or something like identifier. Is that correct or am I missing something?

**Comment by davidhalter** [comment]
Hmm, this seems to work now! I have tested it on latest dev. Please retry and play around with it.
