### ISSUE TITLE
CudaText plugin

### ISSUE THREAD

**Issue by Alexey-T** [davidhalter/jedi#679]
Done. Plugin-- 

- http://sourceforge.net/projects/cudatext/files/addons/plugins/plugin.Python_Intel.zip/download 
- or menu item in Cudatext: Plugins/AddonManager/Install, type "python"

Thanks David

**Comment by Alexey-T** [comment]
Can u add it to list of plugins? Tks.

**Comment by davidhalter** [comment]
No I won't. I will only add editors that are fairly well known and used.
