### ISSUE TITLE
Support for `__iter__()` with loops in them

### ISSUE THREAD

**Issue by reinhrst** [davidhalter/jedi#683]
```
class Iter:
    def __iter__(self):
        i = 0
        while True:
            v = 1
            yield v
            i += 1
a, b = Iter()
#? int()
a
#? int()  <--- this one fails (on the linter branch)
b
```

The `__iter__` method above is a simplified version from the one in `collections.abc.Sequence`: https://hg.python.org/cpython/file/3.5/Lib/_collections_abc.py. Support for it would allow iteration support for all subclasses of `collections.abc.Sequence`.

See also: https://github.com/davidhalter/jedi/pull/663#issuecomment-172317854

**Comment by davidhalter** [comment]
This is kind of a feature request really. We have to restructure our sequences to allow for multiple elements if the length of the sequence is not deterministic.

**Comment by davidhalter** [comment]
Finally fixed this one. Wasn't even that hard :)
