### ISSUE TITLE
Crash on master

### ISSUE THREAD

**Issue by reinhrst** [davidhalter/jedi#685]
Not sure if master is supposed to be stable. However the following code crashes (python 3.4.3):

```
import jedi
source = '''
import asyncio
asyncio.'''

script = jedi.Script(source,)
print(str(script.completions()))
```

**Comment by davidhalter** [comment]
It's probably just a bug.

**Comment by davidhalter** [comment]
It's working with the latest master. (300 commits later, hehe)
