### ISSUE TITLE
Replace Synwrite plugin

### ISSUE THREAD

**Issue by Alexey-T** [davidhalter/jedi#694]
I removed plugin "SynJedi" sinze it's with binary Python package and binary files--and added instead
"Python Intel": u can install it same way, using AddonManager (old plugin deled from AddonManager)

It's even faster (no new Py engine)
Tks David

**Comment by davidhalter** [comment]
I have removed the occurrence of Synwrite for now.

I had to start drawing a line between very well known editors like VIM/atom/etc. and some not so popular ones.

This doesn't mean that it's always going to stay like this. Might look different in a year from now :)
