### ISSUE TITLE
python 2.7 function type hint workaround

### ISSUE THREAD

**Issue by xuboying** [davidhalter/jedi#698]
Really happy to see the improvement for PEP484 type hint, on linter branch
Thanks a lot!
btw, Is there a better workaround than this:

```
def test(e):
    e = e #type: list
    e.append(1)
```

**Comment by davidhalter** [comment]
How do you mean better?

**Comment by xuboying** [comment]
HI David,
You've answered my previous issue: https://github.com/davidhalter/jedi-vim/issues/521
Thanks a lot for that.
I'm new to python, but I really need type hint for gui frameworks.
the e=e looks a bit funny, but actually work, 
if there is a style which does not need assignment, it could be better

**Comment by davidhalter** [comment]
Are you using Python 3?

**Comment by xuboying** [comment]
No, I'm still suing Python 2.7 for compatibility reason. I'm aware of the benfit of using python3 but will not switch soon.

**Comment by davidhalter** [comment]
We haven't implemented all of PEP484. Once we have it will be a bit easier and a single comment will be enough.
