### ISSUE TITLE
Assigning to 'self' in a for cycle breaks completion for it afterwards

### ISSUE THREAD

**Issue by karolyi** [davidhalter/jedi#700]
Hey,

coming from https://github.com/DamnWidget/anaconda/issues/449#issuecomment-191746744, the author of Anaconda said this is a bug in Jedi.

Hence, I'm reporting this bug here.

Please look at the description of https://github.com/DamnWidget/anaconda/issues/449

Cheers,
László

**Comment by davidhalter** [comment]
I have fixed it in a very recent commit.
