### ISSUE TITLE
Getting full path to object

### ISSUE THREAD

**Issue by jkitchin** [davidhalter/jedi#702]
I am trying to get the full path for the "thing" that is at the cursor position. For example, in the following script:

```
#+BEGIN_SRC python
import jedi

source = '''from ase import Atom, Atoms

a = Atoms([])'''

s = jedi.Script(source, 3)
gd = s.goto_definitions()

print('name: ',gd[0].name)
print('mname: ', gd[0].module_name)
print('mpath: ', gd[0].module_path)
print('line: ', gd[0].line)
print('fname: ', gd[0].full_name)
print('parent: ', gd[0].parent().module_name)
#+END_SRC

#+RESULTS:
: name:  Atoms
: mname:  atoms
: mpath:  /Users/jkitchin/Dropbox/python/ase/ase/atoms.py
: line:  24
: fname:  atoms.Atoms
: parent:  atoms
```

What I want to get out is "ase.atoms.Atoms" so I can pass it to pydoc. Is that possible? It seems so close!

**Comment by davidhalter** [comment]
Sorry, this is not possible. `full_name` is broken and needs to be fixed. We don't check the `evaluator.sys_modules` (inversely). This would be necessary to actually find out the complete path for a module (and not just the module)

Would appreciate your help, if you have time :)

**Comment by jkitchin** [comment]
I would be happy to look into it. Any chance you could give me a little more direction? I didn't find any reference to evaluator.sys_modules in the code.  I saw Evaluator.modules in jedi/evaluate/__init__.py, but it looks like it is empty and isn't modified from what I could see.

**Comment by davidhalter** [comment]
Checkout the linter branch :)

**Comment by jkitchin** [comment]
I didn't solve this yet, but I did manage to at least get a list of related modules in the script. The script template looks like this:

```import jedi
s = jedi.Script(\"\"\"%s\"\"\", %s, %s, path=\"%s\")
gd = s.goto_definitions()

if len(gd) > 0:
    script_modules = gd[0]._evaluator.modules
    if len(script_modules) > 0:
        related = '\\n    '.join([smod for smod in script_modules if 'py-' not in smod])
    else:
        related = None

    print('''Help on {0}:

NAME
    {3}

{4}

FILE
    {1}::{2}

OTHER MODULES IN THIS FILE
    {5}
'''.format(gd[0].full_name, gd[0].module_path, gd[0].line, gd[0].name, gd[0].docstring(), related))"````

This script is expanded in emacs and executed to give a pydoc like docstring for the thing at point. (https://github.com/statmobile/pydoc/blob/master/pydoc.el#L755). This works well enough for me.

**Comment by davidhalter** [comment]
I really don't get what you wrote here. Can you maybe format it better? Also stuff like `{3}` doesn't make a lot of sense to me.

**Comment by jkitchin** [comment]
{3} is standard python string format stuff, e.g. in the template above it is replaced by the 4th argument to format (args are 0-indexed). In emacs I insert the contents of a Python script and the cursor position, and then generate a pydoc like buffer about the object at point. The only thing that is new here is the "OTHER MODULES IN THIS FILE" which I get from gd[0]._evaluator.modules

**Comment by davidhalter** [comment]
I still don't get at all what you are trying to tell me...
