### ISSUE TITLE
Parsing symbols error

### ISSUE THREAD

**Issue by ghenom** [davidhalter/jedi#714]
stderr jediProxy
Error (stderr) Traceback (most recent call last):
  File "completion.py", line 309, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 282, in _process_request
    request['id']))
  File "completion.py", line 216, in _serialize_definitions
    'line': definition.line - 1,
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

**Comment by davidhalter** [comment]
There is no `completion.py` file in Jedi. Please report this to the plugin creator.
