### ISSUE TITLE
limit completions to fields present in `__all__`

### ISSUE THREAD

**Issue by Carreau** [davidhalter/jedi#715]
Hi, 

Would it be conceivable to have an option, so that when using `Interpreter`, completion would be limited to the fields present in `__all__`, if `__all__` is present of course. 

I think that one of the usage of all is to hide the underlying complexity of a module/class/object, so it seem logical to also hide it during completion. 

One possibility would be to hide this only when completing just after a `.`.

**Comment by davidhalter** [comment]
This is a hard issue to tackle. At the moment I don't think it is technically feasible and there's also #11 that tried to suggest the exact same thing.

I'm closing, because this s really not on the roadmap. If somebody wants to tackle it, feel free. But it might take you one or two months.
