### ISSUE TITLE
Pre-import modules?

### ISSUE THREAD

**Issue by jbredeche** [davidhalter/jedi#717]
Thanks for an amazing project!

Is there a supported way to add modules to the list of modules that Jedi uses for autocompletion?

For example, instead of:
```
from foo import bar
ba<tab>
```

I was hoping to add the `foo` module to Jedi so that this would work:
```
ba<tab>
```

I could certainly programmatically prepend `from foo import bar` to the source text, but was wondering if there's a cleaner way to do it.

thanks!

**Comment by jbredeche** [comment]
This makes me think of the `eval <code> in <namespace_dict>` facility in Python, which lets you evaluate code using a specific set of global variables.  Is there something like that in Jedi?

**Comment by jbredeche** [comment]
Sorry for the play by play - seems like `global_names_dict_generator` would be a useful place to inject a custom list of globals.  I'll play with this and see what I can come up with!

**Comment by davidhalter** [comment]
What are you trying to accomplish?

**Comment by jbredeche** [comment]
I work on a project (Quantopian) that provides a web-based Python IDE for users.  For historical reasons, we add a bunch of methods to the global namespace so that users can use them without having to import them.  I'd love to use Jedi for autocomplete, but I need a way to teach it about a set of methods that should be added to the global namespace.

**Comment by jbredeche** [comment]
I just found the `Interpreter` class, which seems to support this usecase well since it lets me pass in a list of namespace dictionaries!

**Comment by davidhalter** [comment]
Yes. That's the way to go!

**Comment by davidhalter** [comment]
Seems to be answered. Let me know if something is not working!
