### ISSUE TITLE
Can't complete on `<var>.from`

### ISSUE THREAD

**Issue by Carreau** [davidhalter/jedi#718]
the following snippet raise a KeyError from inside jedi internals:

```python
import jedi
line_buffer='pass; a.from' # want to complete to , – for example – `from_bytes`

namespaces = [{'a':1}]
cursor_pos = len(line_buffer)

interpreter = jedi.Interpreter(line_buffer, namespaces, column=cursor_pos)
```

Changing to `pass; a.from_` works, note the trailing underscore. The `pass;` is necessary.

Full traceback available in a gist: https://gist.github.com/Carreau/26a1ce819f46e65e93bfcfd171e970ea
using 935aec7b7126ab33257b862434512d249210abbd

**Comment by davidhalter** [comment]
This seems to work well, now. Just retry with the latest dev branch.
