### ISSUE TITLE
Do not init colorama on import. 

### ISSUE THREAD

**Issue by Carreau** [davidhalter/jedi#724]
[This line](https://github.com/davidhalter/jedi/blob/6266678064cdae5fa9d71a2d8854aac7503f1db9/jedi/debug.py#L17) activate colorama on jedi import. 

Which lead to a rabbit hole of things which in then lead to `ipython file.py > otherfile` to crash while trying to write to stdout https://github.com/ipython/ipython/issues/9402

Would it be possible to not initialize colorama on import, that swap sys.stdout ?

**Comment by Carreau** [comment]
PS: this happen only if stdout/err are not tty in which case colorama logic is to (not (not wrap)) the streams, and strip ansi sequences.

**Comment by davidhalter** [comment]
This has been solved by #725, thanks @Carreau!
