### ISSUE TITLE
Support PEP 484 type annotations

### ISSUE THREAD

**Issue by kirbyfan64** [davidhalter/jedi#729]
They add quite a bit of information that Jedi could probably use.

**Comment by davidhalter** [comment]
They are already supported partially in the linter branch!

**Comment by kirbyfan64** [comment]
*slaps self* Okay, sorry. I looked in the docs but didn't see anything and didn't think to look in the development branches...

**Comment by davidhalter** [comment]
No problem. I didn't expect you would crawl through development branches. You could have used the issue search for PEP 484 though ;)
