### ISSUE TITLE
metadata.json missing run_requires

### ISSUE THREAD

**Issue by daym** [davidhalter/jedi#733]
it seems the metadata.json in https://pypi.python.org/packages/c4/59/e48a369168a84c8aef9127c227fc3b9f53bc9c528b24c2cda20487bc2deb/jedi-0.9.0-py2.py3-none-any.whl misses the entry for key "run_requires" which would list the runtime requirements. 

Is that on purpose? Does jedi really have no requirements beside Python itself?

I'm trying to package jedi for the GNU Guix distribution and am wondering what the right way to proceed is. I could make run_requires optional or I could ask the jedi maintainers for help in extending their metadata.json . Which do you think is the correct action? Should run_requires be optional?

See https://www.python.org/dev/peps/pep-0426/ for details of the metadata.json format.

The tests seem to need docopt.

**Comment by davidhalter** [comment]
> Does jedi really have no requirements beside Python itself?

Yes. The tests have some requirements. Docopt is not really a requirement (since it's just optional), pytest and tox are. But I doubt that they would be part of `run_requires`?!
