### ISSUE TITLE
jedi staticmethod first param complete error

### ISSUE THREAD

**Issue by JinMaiAymazon** [davidhalter/jedi#735]
I'm sorry, my English is poor.

def A:
----@staticmethod
----def a(param):
--------""":type param: str"""
--------param. # this pop a(param == cls) and not str.xxx
--------assert isinstance(param, str)
--------param. # this pop str.xxx

Another problem is how to use the single-line comments for type completion?
x = y['xxx'] # :type: str
is not complate, i test is not work, and:
x = y['xxx'] # type: str | # @type: str
: (

**Comment by JinMaiAymazon** [comment]
and is very cool!
def __init__(self, config):
----"""
----:param dict config: xxxx
--------:param str partner: xxx
--------:param str private_key: xxx
----"""

:)

**Comment by davidhalter** [comment]
I have no idea what you mean, can you explain yourself?

**Comment by JinMaiAymazon** [comment]
I use spacemacs and python3
this error:
![image](https://cloud.githubusercontent.com/assets/19261950/16368864/ec9d6ec8-3c65-11e6-86d5-1d3aeac55d44.png)
this ok:
![image](https://cloud.githubusercontent.com/assets/19261950/16368872/0c7b1254-3c66-11e6-9e8e-476e8dc4e95f.png)
and this ok, if not staticmethod:
![image](https://cloud.githubusercontent.com/assets/19261950/16368901/7203b676-3c66-11e6-9f88-ac41590c0e2e.png)

**Comment by davidhalter** [comment]
Thanks!

**Comment by JinMaiAymazon** [comment]
Frankly, we thank you for bringing us so easy to use software! :)

**Comment by davidhalter** [comment]
This is not fixed ;)

**Comment by davidhalter** [comment]
I was finally able to solve this one. Thanks again for reporting this.
