### ISSUE TITLE
Fix tests (on Travis)

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#737]
It looks like tests are failing currently (e.g. https://travis-ci.org/davidhalter/jedi/builds/140589895).
This should be fixed.
Any insights in this already?

**Comment by davidhalter** [comment]
They tests fixed AFAIK (it was an issue with travis), but only in the dev branch.

The latest branch (`away`) will hopefully replace master very soon. It might take a week or two to even reach dev, but I'm confident that it will soon happen.
