### ISSUE TITLE
RFE - extract docstring for params from function docstring

### ISSUE THREAD

**Issue by DonJayamanne** [davidhalter/jedi#739]
Currently when getting the parameter information, the docstring is empty.
Could we not extract (via some string parsing) extract this from the docstring and return this information along with the param info.

**Comment by davidhalter** [comment]
What are you talking about?

**Comment by DonJayamanne** [comment]
Sorry, let me be more specific:
Today when we call the method [call_getsignatures](http://jedi.jedidjah.ch/en/latest/docs/plugin-api.html#jedi.api.Script.call_signatures), the docstring for the signature (function is returned in the when using the docstring() method.
When iterating through the parameters of each signature using the "params" property, the docstring() for each of the parameters is empty.

My suggestion is why not determine the documentation of the corresponding parameter from the docstring of the function.

For instance the docstring for function_with_types_in_docstring can be extracted and is returned by jedi.
How about some how trying to parse that string to extract the documentation for the individual parameters?
I guess the problem is how do we support various formats for docstrings.

```
def function_with_types_in_docstring(param1, param2):
    """Example function with types documented in the docstring.

    `PEP 484`_ type annotations are supported. If attribute, parameter, and
    return types are annotated according to `PEP 484`_, they do not need to be
    included in the docstring:

    Args:
        param1 (int): The first parameter.
        param2 (str): The second parameter.

    Returns:
        bool: The return value. True for success, False otherwise.

    .. _PEP 484:
        https://www.python.org/dev/peps/pep-0484/

    """
```

**Comment by davidhalter** [comment]
You are right. This would be a good idea. Parsing it is probably not that hard, since such logic already exists. (`jedi/evaluate/docstrings.py`). However I'm not actually sure on all the API implications.

**Comment by DonJayamanne** [comment]
I agree, maintaining backwards compatibility is necessary as this is widely used. How about we add this feature as an optional one, via an optional parameter to call_Getsignatures. I am more than happy to submit a pull request if you think this is the right approach.

**Comment by davidhalter** [comment]
@DonJayamanne Sorry for not answering back then. Are you still interested in doing such a pull request?

I unfortunately don't really like working with docstrings and so I'm probably not going to do it :).

**Comment by davidhalter** [comment]
Closing for now. Happy to reopen if someone feels like they want to work on this :).

**Comment by DonJayamanne** [comment]
> Sorry for not answering back then. Are you still interested in doing such a pull request?

Oops, sorry for not replying. Somehow missed the original message.
I'm happy for this to be closed. Thanks for considering it.
