### ISSUE TITLE
Issue with cache after updating Jedi version

### ISSUE THREAD

**Issue by sadovnychyi** [davidhalter/jedi#750]
As reported [here](https://github.com/sadovnychyi/autocomplete-python/issues/217) there's some exceptions if you have old cache and trying to use new version of Jedi. It can be easily resolved by removing the cache manually, but maybe there's should be some cache isolation for different versions?

**Comment by davidhalter** [comment]
There is. But if you update very regularly (between a few commits), you might run into trouble sometimes. I forget to increase the parser pickling version from time to time.
