### ISSUE TITLE
A case of missing completions

### ISSUE THREAD

**Issue by magv** [davidhalter/jedi#752]
Hi. Here's a short example of a problem I've run into:

`test.py`:

``` python
import library
from library import *
```

`library/__init__.py`:

``` python
#
#
from .liba import fun_a

def fun_x(s, t, u):
    return s + t + u

__all__ = [ "fun_a", "fun_x" ]
```

`library/liba.py`:

``` python
def fun_a(x, y):
    return x + y
```

If you'll try autocompletion with this file structure like so:

``` python
import jedi
s = jedi.Script(path="<path to test.py>")
for c in s.completions():
    if "fun" in c.name:
        print(c)
```

... you'll get nothing. So both `fun_a` and `fun_x` are missing.

Now, if you'll edit `library/__init__.py` and remove the two initial comments, completion will change: you'll get a completion for `fun_a`, while `fun_x` will still be missing.

---

**Edit**: the stuff I previously said about this being a regression turned out to be false; the regression I was seeing was due to Jedi cache persisting across Jedi version updates. The problem described above is present in both the current dev branch, and in 0.9.0.

**Comment by davidhalter** [comment]
Can you provide that as a zip or a git repository?

**Comment by magv** [comment]
Like this [jedi-issue-752.zip](https://github.com/davidhalter/jedi/files/407451/jedi-issue-752.zip)?

**Comment by davidhalter** [comment]
Thank you for putting it together. It's working for me now. I'm not sure why, but I'm pretty sure it works in the current master branch. I'm closing. Let me know if it still doesn't work and I will reopen.

I have changed a few things about relative imports. That might be the reason why everything works, now.
