### ISSUE TITLE
jedi fails to correctly autocomplete from package with the same name as the module that I'm in

### ISSUE THREAD

**Issue by kendriu** [davidhalter/jedi#755]
I'm using emacs and I have configured `jedi` (via jedi.el) so it autocompletes after dot. Let's assume that I'm writing a module `my_app.my_module` and I have package installed in env called `my_module`. My file `my_app/my_module.py` will look like:
```
import my_module

class SomeClass:
    pass
(...)
my_module.<here_i_expect_autocompletion_from_my_module_package>
```
Now the thing is that `jedi` tries to autocomplete from `my_app.my_module`(giving me `SomeClass`, etc.) not from `my_module` package installed in env.

**Comment by davidhalter** [comment]
How do you start that piece of python code?

**Comment by kendriu** [comment]
It's a fragment of larger application in pyramid framework. In which I have a top-level module `my_app`.

**Comment by davidhalter** [comment]
The problem is probably that pyramid (like django) is modifying the sys.path. This is something that Jedi doesn't understand (yet).

The solution would be to understand pyramid environments. Happy to receive pull requests! However, Jedi doesn't understand all sorts of `sys.path` modifications.
