### ISSUE TITLE
No Completions for import multiple modules

### ISSUE THREAD

**Issue by SolaWing** [davidhalter/jedi#759]
as snapshot shows, import complete after `,` incorrect. expect to complete a list of modules after `s`. complete `path` after `,` is also weird, since it's not `.`.

git version is `8a34481 - (origin/master, origin/HEAD)`

```
Python 3.5.2 (default, Aug  3 2016, 14:43:50)
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import jedi

In [2]: s = 'import os, s'

In [3]: jedi.Script(s, 1, len(s), '').completions()
Out[3]: []

In [4]: jedi.Script(s, 1, len(s) - 1, '').completions()
Out[4]: [<Completion: path>]

In [5]: jedi.Script(s, 1, len(s) - 2, '').completions()
Out[5]: [<Completion: path>]

In [6]: jedi.Script(s, 1, len(s) - 3, '').completions()
Out[6]: [<Completion: os>]
```

**Comment by davidhalter** [comment]
Haha, this is indeed very strange. I think part of it has to do with the `os.path` completion. That is a huge exception in Jedi's import logic and I have therefore never really detected it.

Thx for noticing and posting. I will be fixing this soon, hopefully.

**Comment by davidhalter** [comment]
Thanks for the report with reproduction. Was really easy to fix in the end.
