### ISSUE TITLE
Question: Identify whether cursor is placed within a comment or string

### ISSUE THREAD

**Issue by DonJayamanne** [davidhalter/jedi#762]
Is it possible to use the Jedi library (or some of the non public api - which could later be made public) to determine whether the cursor is positioned within a comment or a string literal (or more importantly the start of a comment or string literal)?

I would like this information to disable the autocomplete/intellisense feature within my extension when the user is typing some comments or a simple string literal.

**Comment by davidhalter** [comment]
It's currently not possible. This could be part of https://github.com/davidhalter/jedi/issues/253.

However that issue currently doesn't have high priority.

**Comment by DonJayamanne** [comment]
@davidhalter , thanks
