### ISSUE TITLE
python import not working

### ISSUE THREAD

**Issue by karimsqualli96** [davidhalter/jedi#766]
hello everyone, i'm started using jedi with vim, the autocompletition work great, but there is a problem with imports, when i type `from module import somthing1-working, no-more-autcomplete`
the first thing imported from the module work with autocompletition, but when i put the comma and try to import another thing its don't work

**Comment by davidhalter** [comment]
Try Jedi's dev branch and report back.

**Comment by karimsqualli96** [comment]
solved thanks, the jedi version comming with vim-jedi was 1 year old.
