### ISSUE TITLE
Does type hinting actually work…?

### ISSUE THREAD

**Issue by MetroWind** [davidhalter/jedi#768]
Try this:

```
x = {}                          # type: typing.Dict[int, dict]
x[0].|                          # Doesn't work.
y = x[0]                        # type: dict
y.|                             # Doesn't work
```

If I put cursor at the specified location at line 2 and 4, Jedi won’t complete. I have Python ~~2.6.6~~2.7.10.

**Comment by davidhalter** [comment]
Jedi version?

**Comment by MetroWind** [comment]
M-x jedi:show-jodi-version:
```
(:emacs-version "24.5.1" :jedi-version “0.2.7”)
((:version "2.7.10 (default, Oct 23 2015, 19:19:21) \n[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]" :name "sys" :file nil)
 (:version "0.9.0" :name "jedi" :file “/somepath/.emacs.d/.python-environments/default/lib/python2.7/site-packages/jedi/__init__.pyc”)
 (:version "0.0.5" :name "epc" :file “/somepath/.emacs.d/.python-environments/default/lib/python2.7/site-packages/epc/__init__.pyc”)
 (:version "0.0.3" :name "sexpdata" :file “/somepath/.emacs.d/.python-environments/default/lib/python2.7/site-packages/sexpdata.pyc”))
```

**Comment by davidhalter** [comment]
Can you try and update to jedi's master branch?

**Comment by MetroWind** [comment]
Tried that.  The version is now
```
(:emacs-version "24.5.1" :jedi-version "0.2.7")
((:version "2.7.10 (default, Oct 23 2015, 19:19:21) \n[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]" :name "sys" :file nil)
 (:version "0.10.0" :name "jedi" :file "/Users/sun/.emacs.d/.python-environments/default/lib/python2.7/site-packages/jedi/__init__.pyc")
 (:version "0.0.5" :name "epc" :file "/Users/sun/.emacs.d/.python-environments/default/lib/python2.7/site-packages/epc/__init__.pyc")
 (:version "0.0.3" :name "sexpdata" :file "/Users/sun/.emacs.d/.python-environments/default/lib/python2.7/site-packages/sexpdata.pyc"))
```
Completion on “y.” seems to work now, but on “x[0].” still doesn’t work.

**Comment by davidhalter** [comment]
Have you imported typing?

**Comment by davidhalter** [comment]
Both of them are working on the dev branch (as long as you import `typing`). I'm not sure if it works on master (and since I'm pushing to master like next week, I don't mind.

**Comment by MetroWind** [comment]
I'm not sure if it's suitable to still comment in here, but I updated my enviornment use Emacs with lsp-mode and Python 3.7. Still the same result.

I then did this test:

    import jedi
    
    source = """import typing
    from typing import List
    
    a: List[str] = ["",]
    a[0]."""
    script = jedi.Script(source, 5, len("a[0]."), "test.py")
    print(script.completions())

On my machine this prints an empty list. Is it supposed to be like this? I have Jedi 0.13.2.

**Comment by MetroWind** [comment]
I'd like to revive this discussion a bit. I updated my Emacs configuration to use lsp-mode with python language server, and the typing hinting still doesn't work. So I did this test:

    import jedi
     
    source = """import typing
    from typing import List
     
    def f(a: List[str]) -> None:
        a[0]."""
    script = jedi.Script(source, 5, 9, "test.py")
    print(script.completions())

This just prints a empty list. Is it supposed to be like this?

**Comment by davidhalter** [comment]
This could for example fail if typing was not installed.

**Comment by MetroWind** [comment]
> This could for example fail if typing was not installed.

What do you mean by “typing was not installed”? I’m using Python 3.7 and I can import typing.

**Comment by davidhalter** [comment]
I see Python 2.7 in your emacs output.

**Comment by MetroWind** [comment]
> I see Python 2.7 in your emacs output.

Oops, my bad. I should have clarify. I’m using 3.7 now.

**Comment by davidhalter** [comment]
I'm still 99% sure that this is an issue on your side (or something that has to do with your setup), because there are a lot of tests that cover exactly this: https://github.com/davidhalter/jedi/blob/master/test/completion/pep0484_typing.py.

Please enable debug mode (`jedi.set_debug_function()`) and report the output back.

**Comment by MetroWind** [comment]
I would not be suprised if this is some stupid mistake I made, but I just couldn't figure out.. Anyway I added the line to my test script:

    import jedi
    
    source = """import typing
    from typing import List
    
    def f(a: List[str]) -> None:
        a[0]."""
    jedi.set_debug_function()
    script = jedi.Script(source, 5, 9, "test.py")
    print(script.completions())

And [this](https://hastebin.com/raw/amiwiyigiq) is the output.

**Comment by davidhalter** [comment]
Oh wait, I think Python 3.7 is still not properly passing and supported even with the latest release. Maybe that's the issue? Can you try with the typeshed branch? There it should probably work, because I tested 3.7 there.

**Comment by MetroWind** [comment]
Ok, I installed the typeshed branch with `setup.py install`, but it won’t run the test script:

    dbg: Start environment subprocess '/path/to/python-bin'
    speed: init 0.25226902961730957
    speed: parsed 0.25416088104248047
    speed: completions start 1.3113021850585938e-05
    Traceback (most recent call last):
      File "/path/to/python/lib/python3.7/site-packages/jedi-0.13.3-py3.7.egg/jedi/cache.py", line 141, in wrapper
        return dct[key]
    KeyError: ((), frozenset())
     
    During handling of the above exception, another exception occurred:
     
    Traceback (most recent call last):
      File "/tmp/test.py", line 10, in <module>
        print(script.completions())
      File "/path/to/python/lib/python3.7/site-packages/jedi-0.13.3-py3.7.egg/jedi/api/__init__.py", line 210, in completions
        self._evaluator, self._get_module(), self._code_lines,
      File "/path/to/python/lib/python3.7/site-packages/jedi-0.13.3-py3.7.egg/jedi/cache.py", line 143, in wrapper
        result = method(self, *args, **kwargs)
      File "/path/to/python/lib/python3.7/site-packages/jedi-0.13.3-py3.7.egg/jedi/api/__init__.py", line 186, in _get_module
        self._evaluator, None, module.string_names, ContextSet([module])
      File "/path/to/python/lib/python3.7/site-packages/jedi-0.13.3-py3.7.egg/jedi/evaluate/gradual/typeshed.py", line 134, in try_to_merge_with_stub
        map_ = _cache_stub_file_map(evaluator.grammar.version_info)
      File "/path/to/python/lib/python3.7/site-packages/jedi-0.13.3-py3.7.egg/jedi/evaluate/gradual/typeshed.py", line 87, in _cache_stub_file_map
        _merge_create_stub_map(_get_typeshed_directories(version_info))
      File "/path/to/python/lib/python3.7/site-packages/jedi-0.13.3-py3.7.egg/jedi/evaluate/gradual/typeshed.py", line 19, in _merge_create_stub_map
        for directory in directories:
      File "/path/to/python/lib/python3.7/site-packages/jedi-0.13.3-py3.7.egg/jedi/evaluate/gradual/typeshed.py", line 54, in _get_typeshed_directories
        base_list = os.listdir(base)
    FileNotFoundError: [Errno 2] No such file or directory: '/path/to/python/lib/python3.7/site-packages/jedi-0.13.3-py3.7.egg/jedi/third_party/typeshed/stdlib'

**Comment by davidhalter** [comment]
I'm not sure if you can install it like that, because typeshed needs to be available (it's a it submodule).

You can simply install it with `pip install -e .` and `git submodule update --init`.

**Comment by MetroWind** [comment]
Ah, ok. Didn’t realize there’s a submodule. And indeed it worked after doing that!

**Comment by davidhalter** [comment]
Now I have also improved setup.py, so it should now be possible to install it without hacking around and there's an error message if typeshed is not checked out.
