### ISSUE TITLE
jedi doesn't get correct autocomplete when assignment is in try ... except

### ISSUE THREAD

**Issue by chrahunt** [davidhalter/jedi#769]
As mentioned on this issue: DonJayamanne/pythonVSCode#284, jedi is not returning the correct completions for submodules in `pygame`. `pygame` uses C extensions which seem to be supported by jedi, but they do their import in a `try ... except`:

``` python
try:
    import pygame.draw
except (ImportError, IOError):
    draw = MissingModule("draw", geterror(), 1)
```

Example script:

``` python
import jedi

s = '''import pygame.draw
pygame.draw.
'''
script = jedi.Script(s, 2, len('pygame.draw.'), 'test.py')
print(', '.join(c.full_name for c in script.completions()))
```

Output:

```
pygame.MissingModule.__init__, pygame.MissingModule.__init__, pygame.MissingModule.__init__, pygame.MissingModule.__init__, pygame.MissingModule.warn, pygame.MissingModule, object.type, object.__delattr__, object.__dir__, object.str, object.__eq__, object.__format__, object.__ge__, pygame.MissingModule.__getattr__, object.__getattribute__, object.__gt__, object.__hash__, pygame.MissingModule.__init__, object.__le__, object.__lt__, object.__ne__, object.__new__, pygame.MissingModule.__nonzero__, object.__reduce__, object.__reduce_ex__, object.__repr__, object.__setattr__, object.__sizeof__, object.__str__, object.__subclasshook__
```

Now if I edit the import in `pygame/__init__.py` to look like:

``` python
try:
    import pygame.draw
except (ImportError, IOError):
    #draw = MissingModule("draw", geterror(), 1)
    pass
```

and run the same script above I receive

```
pygame.draw.aaline, pygame.draw.aalines, pygame.draw.arc, pygame.draw.circle, pygame.draw.ellipse, pygame.draw.line, pygame.draw.lines, pygame.draw.polygon, pygame.draw.rect, pygame.draw.str, pygame.draw.str, pygame.draw.ExtensionFileLoader, pygame.draw.str, pygame.draw.str, pygame.draw.ModuleSpec
```

as expected. So it looks like it is the assignment in the `except` block is causing the issue.

I looked through existing issues for `ImportError`, `try`, `try except`, and didn't see this mentioned anywhere. Is this supported?

**Comment by davidhalter** [comment]
You searched well, my friend, but unfortunately related tickets were in the jedi-vim tracker (which is not the right place for those tickets).

There's https://github.com/davidhalter/jedi-vim/issues/146

I'm still not sure how I would solve the above in a general way, that's why I closed.

**Comment by chrahunt** [comment]
I think it comes down to deciding between using the value resulting from the `try` block and the one from the `except`. Would this be a good approach: recognize control structures of the form `try: ... except (..., ImportError, ...): ...` and only using values in the `except` for autocomplete when an import statement in the `try` block cannot be resolved.

This structure is pretty common for optional imports, so addressing it in this way may also cover some other corner cases. If this sounds fine I can work on it.

**Comment by davidhalter** [comment]
It's not at all common to assign some weird object. I think a library should not be designed like that.

But apart from that, it would obviously be possible to do something like what you describe, but it's really not something with high priority.

**Comment by nsklaus** [comment]
@chrahunt
thanks a lot for your post. now i've edited pygame's __init__.py manualy and i do get my methods signatures popup working. manualy modifying the file as i did may be a little dirty workaround but at least it works, until jedi finds out how to solve this properly.

@davidhalter
i would also be interested in proper solution for this. pygame is a popular framework, and jedi is good to have too. if something could be done about it, that would be great.

**Comment by illume** [comment]
There's a work around for the except issue in pygame now. If there's other pygame related jedi issues, please feel free to report them or cc me on the issue(s).

**Comment by davidhalter** [comment]
I guess I'll close then. There are just too many ways to annoy jedi. That's certainly one and it's not like I'm much closer in changing this. Eventually this might be fixed, but this would involve a lot more work around indexing everything and creating a database. That's not the topic for now.

@illume Thanks for offering your help. I'd definitely consider it.
