### ISSUE TITLE
from module import * doesn't autocomplete

### ISSUE THREAD

**Issue by talkaminker** [davidhalter/jedi#772]
Example:
`jedi.Script("""import collections;collections.Cou""").completions()`
works and gives:
`[<Completion: Counter>]`

while:
`jedi.Script("""from collections import *;Cou""").completions()`
doesn't, returns `[]`

the same is true for any module I tried (os, numpy,...)

I am using python Python 2.7.11 and jedi 0.9.0 (the one in the pip and anaconda right now)
Is this a bug?

**Comment by davidhalter** [comment]
Good catch!

**Comment by i-frost** [comment]
Bump?

**Comment by davidhalter** [comment]
Apparently this was fixed in the latest development version of Jedi (dev branch).
