### ISSUE TITLE
Fix for Py3.5 missing pydoc_data

### ISSUE THREAD

**Issue by Alexey-T** [davidhalter/jedi#774]
Py3.5 embedded (which is python35.dll + python35.zip) misses pydoc_data module (in .zip)
So i suggest for it api/keywords.py patch. Else Jedi dont work.

U do
~~~
try:
    from pydoc_data import topics as pydoc_topics
except ImportError:
    # Python 2.6
    import pydoc_topics
~~~

here do:
~~~
   # Python 2.6
   try:
     import pydoc_topics
   except ImportError:
     pydoc_topics = None
~~~

now for my Py35 DLL i have pydoc_topics==None, and later do check
~~~
  if pydoc_topics is None:
    return ''
~~~

**Comment by davidhalter** [comment]
Can you please be a bit more specific what the problem is?

**Comment by Alexey-T** [comment]
Python35.zip donot contain module pydoc_data. Zip has files .pyc.

**Comment by davidhalter** [comment]
Ok. Could you make a pull request out of this issue? I think the solution makes sense.

Please also add a comment (close to the ImportError) like `The embeddable Python version doesn't come with the whole standard library. Therefore make it optional.

But if you do that. I'm not sure if that is enough. Aren't there other libraries that are also not included (like `copy`, `pickle`, `re`)?

**Comment by Alexey-T** [comment]
I donot see other lib errors. only this. So i make PR now. I tested this pch in plugin for CudaText

**Comment by davidhalter** [comment]
Thanks!
