### ISSUE TITLE
Search for a symbol in a project dir?

### ISSUE THREAD

**Issue by xuhdev** [davidhalter/jedi#778]
I think it can be a quite useful feature if jedi can find all the occurances of a symbol given a specific dir. I couldn't find in the doc now, which I assume is not available yet.

**Comment by davidhalter** [comment]
True. That's not possible, yet. I think we need some form of "project" definition first, because that's what you really want. You want all occurrences of a name (not just the directory).

**Comment by xuhdev** [comment]
@davidhalter Yes, a directory is passed as a parameter to define a project. All occurrences of a symbol are returned.

**Comment by Alexey-T** [comment]
No, it is no good, one folder
Need list of dirs. Eg. my project has n dirs, which i "import", and main dir

**Comment by davidhalter** [comment]
This was implemented in the project branch. The branch will be merged for 0.17.0.

Now there's a dedicated `jedi.Project` (and `jedi.get_default_project`) API.
