### ISSUE TITLE
Quick calc call-notation for a func?

### ISSUE THREAD

**Issue by Alexey-T** [davidhalter/jedi#779]
David, I almost solved how to get notation but i use weird code. it iterates some of params etc. I want to get string

```
 my_func(par1, par2, par3=None, par4=['test'] )
```

so calling notation of func. How to do it?

**Comment by Alexey-T** [comment]
(My weird code is https://github.com/CudaText-addons/cuda_python_intel/blob/master/intel_work.py )

**Comment by davidhalter** [comment]
Yeah I think we should make that posible, but it's currently not.

**Comment by Alexey-T** [comment]
Oh, will wait, tks

**Comment by Alexey-T** [comment]
PullR: i dived into code and found how to do

**Comment by Alexey-T** [comment]
So I fixed PR.
