### ISSUE TITLE
Cannot use tab for autocompletion

### ISSUE THREAD

**Issue by chaonan99** [davidhalter/jedi#781]
Hi,

I'm using Jedi package in Sublime on OSX and Windows. When I use tab to choose autocompletion item, it immediately rolls back (the whole word just won't hold and disappear in a second). The same issue happens on both OSX and Windows, but not always appear, or only in some cases. Besides, it only happens on Python script and when I delete Jedi package the problem disappear too. Does anyone else have the same problem?

**Comment by davidhalter** [comment]
This is not the issue tracker of Jedi for sublime. Please talk to guys that are maintaining those projects. There's a list of sublime projects in the README.
