### ISSUE TITLE
Issue with parser cache and (nested?) namespace packages

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#784]
I've noticed that Jedi fails to find definitions in a particular setup, which is related to cached parsers.
It looks like something gets cached in a wrong way (and `jedi.cache.clear_time_caches(True)` fixes it).

```
% virtualenv venv-django_filter
% source venv-django_filter/bin/activate
% pip install django_filter==0.15
% python django_filter.py
```

``` python
import jedi
# import inspect
# print(inspect.getfile(jedi))

jedi.settings.use_filesystem_cache = False

source = """import django_filters
django_filters.rest_framework.filters.OrderingFilter()
"""

print("=== without path ===")
script = jedi.Script(source, column=42, line=2)
d1 = script.goto_definitions()
assert len(d1)
print("=== without path again ===")
script = jedi.Script(source, column=42, line=2)
d2 = script.goto_definitions()
assert len(d2)
```

I've bisected this and found that with the following commit the following assertion fails already (also in v0.9.0):

commit 8fca3f7 (HEAD, refs/bisect/bad)
Date:   Tue Apr 14 17:36:20 2015 +0200

```
Add a py__name__ call to modules. This makes listing the qualified names of modules possible (in combination with the module_name_cache). Fixes #519.
```

`django_filters/rest_framework/filters.py` ([source](https://github.com/carltongibson/django-filter/blob/73b2228d777d9d97ed622b9b14a6110bf5ba4c7f/django_filters/rest_framework/filters.py)) uses:

``` python
from ..filters import *
```

This was changed in the following commit.  Since then the 2nd assertion fails:

commit ec51891 (refs/bisect/bad)
Date:   Sat Jul 30 02:44:09 2016 +0200

```
Fix nested namespace packages. At least now there's no error anymore. Fixes #743.
```

**Comment by davidhalter** [comment]
We should look at this before or after the next release. I'm currently changing so much that it doesn't make sense to look into it. Pretty sure the parser caches will also change a bit again (I've made some really poor decisions regarding some abstractions).

Thanks for bisecting.

**Comment by davidhalter** [comment]
After digging in for a while I finally found it. It wasn't too hard to correct. Essentially pretty much all relative imports with more than one level were wrong. Thanks for posting.
