### ISSUE TITLE
Unicode issues with Python 3

### ISSUE THREAD

**Issue by DonJayamanne** [davidhalter/jedi#792]
Docstrings are not returned correctly when running Jedi under Python 3.
Jedi Version: 0.9.0
OS: OS X
Instructions:
- Create a file named ```one.py``` with the following contents
```python
# -*- coding: UTF-8 -*-
def m1():
    """
    Кюм 
    """
    pass
```
- Create another file named ```two.py``` with the following contents
```python
from one import m1
m1()
```
- Create a file named ```test.py``` with the following contents
```python
import jedi
script = jedi.api.Script(source=None, line=2, column=2, path='./two.py')
completions = script.completions()
d = completion2[0].docstring()
print(d)
```

In python2.7, the output is as epxected:
```
m1()
Кюм 
```
In Python3.5, the output is as follows:
```
m1()
ÐÑÐ¼ 
```

**Comment by DonJayamanne** [comment]
Closing, not an issue in the current master branch.

**Comment by davidhalter** [comment]
Thanks for checking!!
