### ISSUE TITLE
Stdout/stderr spam when compiled modules are imported

### ISSUE THREAD

**Issue by sadovnychyi** [davidhalter/jedi#793]
Since compiled modules are being actually [executed](https://github.com/davidhalter/jedi/blob/master/jedi/evaluate/compiled/__init__.py#L365) they produce some stdout/stderr output sometimes (like [kivy](https://kivy.org/docs/installation/installation-osx.html)). Seems like isn't expected behavior for me. See https://github.com/autocomplete-python/autocomplete-python/issues/161 and https://github.com/autocomplete-python/autocomplete-python/issues/244.

I'll disable stdout from my plugin to fix this, but maybe it's should be done within Jedi? Feel free to close this if you think otherwise, but I think this should be at least documented. 

```
python -c "import jedi; jedi.api.Script(source='from kivy.properties import ', line=1, column=28).completions()"
[INFO   ] [Logger      ] Record log in /Users/sadovnychyi/.kivy/logs/kivy_16-11-01_20.txt   17:16:03
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v2.7.12 (default, Sep 28 2016, 18:38:03) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

**Comment by davidhalter** [comment]
True, I would also like to have that changed.

**Comment by davidhalter** [comment]
Fixed. Actually had to move all the importing to a subprocess to avoid this.
