### ISSUE TITLE
Instantiation not connected with invocation of _init_

### ISSUE THREAD

**Issue by vossad01** [davidhalter/jedi#800]
When you ask jedi to find where a class's `_init_` is used, it finds explicit invocations and the definition.  However, it does not find class instantiation using the standard (function) syntax.

For example it does not report the 5th line is a use of `__init__`:

```python
class Claz:
    def __init__(self):
        print("Hello")

Claz()
```

Issue discovered using Visual Studio Code, details in situ at DonJayamanne/pythonVSCode#498.  Jedi 0.9.0 appears to be the version in the VS Code extension.  Python 2.7.12

**Comment by davidhalter** [comment]
I'm not sure what you mean. Can you describe a bit better which command you are using and where?

**Comment by vossad01** [comment]
I only know the problem as it presents in Visual Studio Code (issue linked in first post).  Digging into the code for that, it looks like the relevant code would be in [`$pythonVSCode/pythonFiles/release/jedi/api/usages.py`](https://github.com/DonJayamanne/pythonVSCode/blob/master/pythonFiles/release/jedi/api/usages.py) which uses `jedi.evaluate.imports.get_modules_containing_name`

As far is the workflow in Visual Studio Code, given the following file:
```python
class Claz:
    def __init__(self):
        print("Hello")

Claz()
```

If I tell it to "Find All References" of `__init__`, I would expect it to identify `Claz()` as a usage of `__init__`,

```python
class Claz:
    def __init__(self):     <--- Request tooling to find where this is used
        print("Hello")

Claz()    <--- Tooling should see it is used here
```

**Comment by davidhalter** [comment]
Hmm interesting idea. Usages is broken and pretty bad (and I'm not sure why anyone is using it, it's so bad :D).

However, I'm not sure if it's a good idea. It's really not the same name and that's the current limitation. That's a good one. If you consider renaming (refactoring) for example, what would you use it on? `__init__` certainly not. I think if this is something that's happening, it would not include it's own reference, but that's also weird. 

I'm not sure if it's better to let IDE's do such magic. Really not sure.

What do others think? I'm really not sure what to think about this. I tend to say that it's a bad idea.

**Comment by vossad01** [comment]
Under [Caveats, "Malformed syntax"](https://jedi.readthedocs.io/en/latest/docs/features.html#caveats) the Jedi docs state:
>It is a tool that wants to help you. But **YOU** have to know Python, not _Jedi_.

From that perspective, I can see it very easily be argued that this is not a feature Jedi should support.

From the perfective of a user of an IDE, it is something I would expect because (for right or for wrong) IDEs get used for discovery by programmers that that don't know a language or don't know the language well.  These developers on seeing "Find usages" shows no usages other than itself may think it is dead code.  Users who know Python are not so likely to make that mistake; however, there is still the disconnect of having to navigate from the definition of `__init__` to the class declaration when a user wants to utilize the IDE for help with navigation.

For a comparable example pertaining to IDEs, in C# if I ask an IDE for usages of a constructor for a class, I would also expect it to find calls to the constructor when called as `super(...)` from the constructor of a subclass even though it has a different name in that case.

Under a refactoring like _rename_ I do not think the relation is relevant to the refactoring. I would not expect tooling to change the class instantiation calls.  I suppose it could issue an error or warning about renaming a constructor, but that seems likely too specialized.

However, for other possible refactorings such as _introduce parameter_, _change signature_, or _replace constructor with factory method_ knowing this association would be important.

**Comment by davidhalter** [comment]
Closing, since I don't think this is even something were doing in the next 2 years. If someone really has a good solution for this, let's discuss this.
