### ISSUE TITLE
output PEP484 style docstring.

### ISSUE THREAD

**Issue by Cologler** [davidhalter/jedi#801]
Currently:

![picpick-20161109-104029-001](https://cloud.githubusercontent.com/assets/10906962/20125512/f65b7d02-a668-11e6-9bbb-3c486f664bac.png)

Is possible output like:

``` py
set_value(self, value: int) -> (str, None):

blabla docs .......
```

**Comment by davidhalter** [comment]
This might be possible, but be aware that this would take way longer to compute. Maybe with an `add_annotations` param in the future.

**Comment by davidhalter** [comment]
Closing in favor of #987, which is very similar.
