### ISSUE TITLE
Limiting the number of completions to return

### ISSUE THREAD

**Issue by sadovnychyi** [davidhalter/jedi#805]
There are some huge python libraries like `wx` (`brew install wxpython`) with ~4K objects in the root of the module.

```bash
time python -c "import jedi; jedi.api.Script(source='import wx; wx.', line=1, column=14).completions()"

real	0m27.699s
user	0m21.649s
sys	0m3.538s
```

This requires 3GB of RAM to run and a lot of time, with twice more time with dry cache.

How could we deal with such libraries? This would hung any completion provider. My first thought would be to return generator on `.completions()` call instead of precomputing all possible completions, so we could ignore some objects if there's too many of them.

**Comment by davidhalter** [comment]
>  My first thought would be to return generator on

I don't think that's the problem. If you debug this, there's a good chance that the parser is the problem. But let's see.

I think previously it took like 100MB of caches to load wx. What you describe is definitely too much . I'll do my best and try to fix it for the next release.

**Comment by davidhalter** [comment]
Current master:

```
time python -c "import jedi; jedi.api.Script(source='import wx; wx.', line=1, column=14).completions()"

real	0m3.087s
user	0m2.688s
sys	0m0.244s
```

However the first time I did it it looked more like this:

```
 time python -c "import jedi; jedi.api.Script(source='import wx; wx.', line=1, column=14).completions()"
  
real	0m16.783s
user	0m16.288s
sys	0m0.304s
```

However that's the first time, where the parser cache needs to be generated.

It's even better once you run it multiple times in a row:

```
import jedi
import time
from contextlib import contextmanager


@contextmanager
def time_used(text):
    start = time.time()
    yield
    print(text + ' ' + str(time.time() - start))


with time_used('first'):
    jedi.Script(source='import wx; wx.').completions()
with time_used('second'):
    jedi.Script(source='import wx; wx.').completions()
with time_used('third'):
    jedi.Script(source='import wx; wx.').completions()
```

Result:

```
$ python2 test.py
first 3.6000649929
second 0.959644079208
third 0.743054866791
```

Total amount of RAM usage is 180 MB which is also fine IMO. wx is huge and it's very hard to do stuff more efficiently. Let me know what you think. I'm closing. This might have been an issue in an older jedi version, but it's clearly better, now.
