### ISSUE TITLE
Sphinx "param with type" regex requires description to appear on the same line

### ISSUE THREAD

**Issue by sruggier** [davidhalter/jedi#806]
I like to format my docstrings with the parameter descriptions on a new line, like so:

    :param type foo:
        A parameter named foo.

The Sphinx documention implies that this is valid, as in [this example](http://www.sphinx-doc.org/en/1.4.8/domains.html#directive-js:function).

However, the [regex](https://github.com/davidhalter/jedi/blob/be2a97cd36ce1b7d6f587ef122efc3433b1e8ae2/jedi/evaluate/docstrings.py#L31) that Jedi uses to parse such docstrings ends with `[^\n]+`, which requires there to be characters after the closing colon on the first line, or it won't match. It looks like this may not have been intentional: it could just be from copying the same fragment from the two nearby regular expressions, where the `+` is necessary to ensure that the regular expression won't match an with an empty capture. In this case, though, a `*` looks like it would be more appropriate.

**Comment by davidhalter** [comment]
I absolutely agree, the `+` can indeed be a `*`.  Closing in favor of the PR.
