### ISSUE TITLE
There might be a bug about _get_module in Srcipt Class 

### ISSUE THREAD

**Issue by chenfjm** [davidhalter/jedi#810]
The detail please link to [https://github.com/davidhalter/jedi-vim/pull/636]()

**Comment by davidhalter** [comment]
I cannot reproduce this one on master. Are you on windows?

**Comment by davidhalter** [comment]
I would actually prefer it if we spoke about the same bit of code, it would be nice if you just put it together.

**Comment by chenfjm** [comment]
Mac OS, I have solved the goto problem in forked repository(my jedi-vim), thank you !

**Comment by davidhalter** [comment]
Seriously. This issue is just not how issues work. If you have an issue you describe it. You don't just post a link. You cannot do that on stackoverflow and you cannot do that here. I don't have time for that BS.

Create a full replication of the issue with Jedi commands and the
