### ISSUE TITLE
Missing Image in Documentation

### ISSUE THREAD

**Issue by sunnyrjuneja** [davidhalter/jedi#811]
Hi David,

On this page,

https://jedi.readthedocs.io/en/latest/docs/development.html#parser-representation-parser-representation-py

It says: "Class inheritance diagram:" and then skips to the next paragraph. I think there's supposed to be an image there.

**Comment by davidhalter** [comment]
Thanks mate. I think it's fixed now. At least the diagrams show again.

**Comment by sunnyrjuneja** [comment]
Looks good to me.
