### ISSUE TITLE
Context Manager Issues

### ISSUE THREAD

**Issue by Cologler** [davidhalter/jedi#812]
jedi ver: master branch newest (2ba78ab725f1e02dfef8bc50b0204cf656e8ee23).
python ver: 3.5.1

`from contextlib import closing`

![picpick-20161124-131716-001](https://cloud.githubusercontent.com/assets/10906962/20587408/5abf72c2-b248-11e6-8725-5f0c2955e359.png)

expected:
    type is what `closing().__enter__()` return.
actual:
    type is `closing()`.

**Comment by davidhalter** [comment]
Hmm, interesting. I haven't really worked too much with `__enter__`, so I didn't know that. Thanks!

**Comment by davidhalter** [comment]
Fixed, yay :)
