### ISSUE TITLE
KeyError on import completion in the presence of matrix multiplication in lambda expression

### ISSUE THREAD

**Issue by yha** [davidhalter/jedi#813]
Completion in imports does not work if the script contains the "@" operator inside a lambda expression. 
Found on jedi 0.9.0, python 3.5.2 (running inside Spyder from the Anaconda distribution) on Windows 7.

Example:

```
In [22]: jedi.Script('lambda x: x @ x; import n').completions()
Traceback (most recent call last):

  File "<ipython-input-24-9d75c6234bfd>", line 1, in <module>
    jedi.Script('lambda x: a @ x; import n').completions()

[...]

  File "[...]\lib\site-packages\jedi\parser\__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)

KeyError: 'x'
```

**Comment by davidhalter** [comment]
It's working on the dev branch. The relevant code piece that caused this error does not exist anymore.
