### ISSUE TITLE
Wrong index of `call_signatures` ?

### ISSUE THREAD

**Issue by Yevgnen** [davidhalter/jedi#815]
`jedi.Script("def test(a=1, b=2, c=3, d=4):\n    return\n\ntest(1, 2, 3, 4)\n", 4, 16, '').call_signatures()` 

gives `3` while

 `jedi.Script("def test(a=1, b=2, c=3, d=4):\n    return\n\ntest(1, b=2, c=3, d=4)\n", 4, 20, 'test.py').call_signatures()` 

gives `1`.

Reference: https://github.com/tkf/emacs-jedi/issues/277

**Comment by davidhalter** [comment]
Did you try master?

**Comment by Yevgnen** [comment]
@davidhalter Thanks for your reply. I found the issue in pip version 0.9.0. I tried the master version 0.10.0 and everything was just fine.
