### ISSUE TITLE
'Script' has no attribute 'source' error in sith.py

### ISSUE THREAD

**Issue by realh** [davidhalter/jedi#816]
I'm trying to get fakegir to work with vim-youcompleteme, but fakegir's build-jedi-cache.sh reports this error each time it tries to run jedi's sith.py:
`  File "/home/tony/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/sith.py", line 152, in show_location
    for i, line in enumerate(self.script.source.split('\n')[lower:lineno]):
AttributeError: 'Script' object has no attribute 'source'`
I see the Script class has a `_source` attribute though (with leading underscore). Is that what sith.py is meant to use here?

**Comment by davidhalter** [comment]
The problem is probably that YCM is using non-released versions.

> I see the Script class has a _source attribute though (with leading underscore). Is that what sith.py is meant to use here?

I think so.

**Comment by davidhalter** [comment]
It's working for me, so just use the latest dev branch.
