### ISSUE TITLE
Default keymap doesn't allow to use '('

### ISSUE THREAD

**Issue by rudolphalmeida** [davidhalter/jedi#819]
I am using jedi on Sublime Text 3 with Anaconda and it seems to disable the key bound to 'sublime_jedi_params_autocomplete'.

`{"command": "sublime_jedi_params_autocomplete", "keys": ["("],
        "context": [
           {"key": "selector", "operator": "equal", "operand":  "source.python - string - comment"},
           {"key": "selection_empty", "operator": "equal", "operand": true, "match_all": true},
           {"key": "following_text", "operator": "regex_match", "operand": "^($| )", "match_all": true}
        ]
    }`

For these settings I can't open parentheses unless I type in the closing parentheses first.

**Comment by davidhalter** [comment]
This repository has nothing to do with sublime, please report this to the Anaconda repository.

**Comment by rudolphalmeida** [comment]
The reason I posted it here is because it works properly if jedi is not installed.

**Comment by davidhalter** [comment]
Lol. Seriously. What should I do with that information. This is a tracker for things like I enter `import jedi` and then it blows up...
