### ISSUE TITLE
PEP 526 support

### ISSUE THREAD

**Issue by Hardtack** [davidhalter/jedi#821]
It seems that jedi does not support [PEP 526](https://www.python.org/dev/peps/pep-0526/) yet.
I can find any issues or code that mention it.
Is there any activities or plans to support this?

PEP 526 - Syntax for Variable Annotations
-----------------------------------------

```python
foo = {'bar': datetime.datetime.now()}
baz = foo['bar']  # type: datetime.datetime
# is equivalent to 
baz: datetime.datetime = foo['bar']

```

**Comment by davidhalter** [comment]
We should do that. Probably just need to add a Python 3.6 grammar and add like 5-10 lines to Jedi. We do something very similar for Jedi.

**Comment by davidhalter** [comment]
I've implemented it on the dev branch.
