### ISSUE TITLE
jedi for asyncio

### ISSUE THREAD

**Issue by bright-pan** [davidhalter/jedi#822]
hi, i use elpy for complete in python 3.5.2

```
import asyncio

loop = asyncio.get_event_loop()

loop.
```

```
>>> jedi.Script("import asyncio; loop = asyncio.get_event_loop(); loop.")
<Script: None>
```

**Comment by davidhalter** [comment]
What else would you want to be completable for asyncio stuff than get_event_loop()? Is this the only thing?

**Comment by bright-pan** [comment]
i  want to be completable for asyncio

**Comment by bright-pan** [comment]
i want to be completable for asyncio @davidhalter

**Comment by davidhalter** [comment]
I know you want `asyncio.get_event_loop()` to be completable, but is there something else you would want that has to do with asyncio?

**Comment by bright-pan** [comment]
i want to be completable for:

Tasks and coroutines
Event loops
Transports and protocols (callback based API)
Streams (coroutine based API)
etc...

**Comment by szastupov** [comment]
asyncio completion works fine for me as long as jedi uses proper python version.

**Comment by davidhalter** [comment]
@szastupov Which Python version are you using?

**Comment by szastupov** [comment]
I tried with 3.5 and 3.6 on Mac, but i had to explicitly set python path in sublime_jedi.sublime-settings:
```
{
    "python_interpreter": "/usr/local/bin/python3"
}
```

I usually have to do the similar thing for project settings in case projects use venv, not very convenient but works.

**Comment by szastupov** [comment]
Oh shi, I missed the fact that you guys are talking about completions of loop object itself, sorry, it doesn't work :/ But thb I don't think it's jedi's fault - get_event_loop() doesn't provide any type hints (neither annotations nor docstring) at all.

**Comment by davidhalter** [comment]
On current jedi master async/await completions are working. Just saying :)

**Comment by davidhalter** [comment]
I quickly looked into it and even fixed one part of the issue (about globals).

The other part is however not fixable. There's a lot of caching/side effects to classes happening that jedi just doesn't understand. It's documented that this is currently not what jedi understands, so I will close this one. Just follow #1056 if you want to stay informed.
