### ISSUE TITLE
Auto-completions working in terminal but not in vim

### ISSUE THREAD

**Issue by benhoff** [davidhalter/jedi#824]
Hey I'm having a weird issue where I can do autocompletions in the terminal, but they aren't working in vim for nested modules.

    import jedi
    jedi.Script('from PyQt5 import QtGui; QtGui.').completions() # this works

But whenever I try to autocomplete the submodule QtGui in vim, I get `Pattern not found`

Python 3, using the master branch from github. vim 8.0.

As far as I can tell the difference in the code is right here.
https://github.com/davidhalter/jedi/blob/master/jedi/evaluate/__init__.py#L263

When I run from the terminal, I get values on the above line.

Whereas when I'm running from vim, all I get back is an empty set().

The top level import parsing from the module works (so in this case `PyQt5`), but the submodules don't seem to.

Any ideas? I tried to debug it myself as much as possible, but once I got into the `memoize_cach` and fancy function decorators, I got lost in the code flow.

**Comment by davidhalter** [comment]
Debugging this stuff is always pretty hard, because it's extremely recursive. You should look to enable jedi's own debugger and look at stdout. That gives you access to at least some information.

**Comment by benhoff** [comment]
Looks like it's an issue with how arch linux is linking the python libs.
`:py3 from PyQt import QtGui` was throwing an ImportError about an undefined symbol.

Compiling vim with just python 3 support and not python 2 fixed the issue for me.

**Comment by davidhalter** [comment]
Great! Thanks for debugging it.
