### ISSUE TITLE
Autocomplete for magic methods

### ISSUE THREAD

**Issue by hieueastagile** [davidhalter/jedi#825]
Hi,

I'm developing a test assertion library and I want to enable the code completion for it. But, badly,  the architecture of the library relies on `setattr` to register the new kind of assertion (by adding the methods to the class). I guess that auto-completion for these defined-by-magic methods is kind of impossible thing, but I wonder is there kind of workaround or way we wrote the code the make it somehow autocomplete-able?

**Comment by davidhalter** [comment]
If it's not a too crazy setattr stuff, you can just add it to Jedi's `jedi.settings.auto_import_modules`. That might help. Other than that, I don't have much hope for you in the near future.
