### ISSUE TITLE
Public API to get info about sys_path being used

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#828]
For Jedi-vim I'd like to add information about the `sys_path` being used by Jedi.

That seems to be available through `jedi_vim.jedi.Script('')._evaluator.sys_path`, but there should be probably a better / public API for it?!

**Comment by davidhalter** [comment]
Hmm that's a good question. If you come up with a good name, I'd be happy to add it (or you could also PR it).

**Comment by davidhalter** [comment]
Environments have a way of showing the sys_path now. Please check #985. It's pretty cool and if you have some time, please review the API a bit. I'm happy about all input there.

**Comment by blueyed** [comment]
Thanks.
The reference to `#985` seems to be wrong though.

**Comment by davidhalter** [comment]
Fixed.

**Comment by davidhalter** [comment]
I meant of course #1053.
