### ISSUE TITLE
Decorators and autocomplete

### ISSUE THREAD

**Issue by gbritton1** [davidhalter/jedi#830]
![547017f6-d6a0-11e6-851c-2c0cb6edfcec](https://cloud.githubusercontent.com/assets/12263288/21986056/c8b21a1c-dbcb-11e6-9c62-0a11f371589b.gif)

Environment data

VS Code version:
Python Extension version:
Python Version:
OS and version:
Your launch.json (if dealing with debugger issues):

Your settings.json:

Logs

Output from Python output panel

Output from Console window (Help->Developer Tools menu)

Actual behavior

When using the Python decorator syntax, (at-sign) autocomplete doesn't show the decorators in a module

Expected behavior

I see the various available decorators

Steps to reproduce:
```
import abc
class Deco:
@abc. # I don't see abstractmethod, for example
```
[Python extension issue](https://github.com/DonJayamanne/pythonVSCode/issues/630)

**Comment by Mortal** [comment]
I've fixed this in PR #848 Complete dotted names properly in decorators.
