### ISSUE TITLE
Completing numbers gives keywords ?

### ISSUE THREAD

**Issue by Yevgnen** [davidhalter/jedi#835]
Hi, thanks for the great library. I have a question about why jedi try to completion number with keywords ? I use emacs-jedi and each time I input a number, jedi tries to give me the keyword completions.

![jedi](https://cloud.githubusercontent.com/assets/16749790/22173600/941441fe-e003-11e6-94d0-6381c2475923.gif)

The result is output by the master of jedi:

    In [1]: import jedi    
    In [2]: jedi.Script('123').completions()
    Out[2]:
    [<Completion: and>,
     <Completion: if>,
     <Completion: in>,
     <Completion: is>,
     <Completion: not>,
     <Completion: or>]

Thanks in advance.

**Comment by Carreau** [comment]
I'm going to guess that's because `and`, `or` ... are valid in between numbers:

```
$ python
Python 3.5.2 | packaged by conda-forge | (default, Jul 26 2016, 01:37:38)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 123and 456
456
>>> 123and 0
0
>>> 0 and 5
0
>>> 0 and 0
0
>>> 1 and 1
1
>>> 1 and 0
0
```

Which is generally useful because 0 is False-ish, the rest is likely due to "As you type" completions.. but I'm not familiar enough with Jedi internals.

**Comment by davidhalter** [comment]
Thanks @Carreau for explaining. It's valid Python.
