### ISSUE TITLE
No completion for `finally`/`except`

### ISSUE THREAD

**Issue by Carreau** [davidhalter/jedi#837]
Relatively minor, and probably a rare case. 

```
In [2]: s='''
   ...: try:
   ...:    pass
   ...: except Exception as e:
   ...:    pass
   ...: fin'''

In [3]: jedi.Script(s, 6,3).completions()
Out[3]: []
```

Same with `4,3` which returns only `Exception` and no `except`. On 1caa2ceafa7bc321a79dedc43d671bef8eec5d66

**Comment by lewisjb** [comment]
This seems to also be the case with `elif`s and `else`s.
e.g.
```
In [2]: s='''
   ...: If False:
   ...:     pass
   ...: elif False:
   ...:     pass
   ...: els'''

In [3]: jedi.Script(s, 6,3).completions()
Out[3]: []
```
(And with `4,3`)

**Comment by davidhalter** [comment]
It looks like this is working now. Also works for `for ... else`
