### ISSUE TITLE
Import-level completions somewhat illogical

### ISSUE THREAD

**Issue by gandhis1** [davidhalter/jedi#841]
Now, this may not be a bug, per se, because all of these completions are legal, but do they really make sense? Should it be jedi's or the consumer's (i.e. an IDE) responsibility to filter out the completions that don't really make sense? 

The completions below, to me, don't really make much sense in this context. Really I don't think there should be any completions. The reason I even bring this up is my IDE of choice (Visual Studio Code) brings up "pdb" as a completion when I type "pd", and pressing enter may accidentally trigger this completion. 

I'm guessing I'll probably get the response that it's the IDE's responsibility to address this, but I figured I'd start here first. 

`In [1]: ", ".join(map(lambda x: x.name_with_symbols, jedi.Script("import pandas as ").completions()))`

`Out [1]: 2to3-script, abc, activate-global-python-argcomplete-script, adodbapi, afxres, aifc, alabaster, anaconda-clean-script, anaconda-navigator-script, anaconda-script, anaconda_clean, anaconda_navigator, antigravity, anydbm, argcomplete, argparse, array, asadmin-script, ast, astroid, astropy, asynchat, asyncore, atexit, audiodev, audioop, autoreload, babel, backports, backports_abc, base64, BaseHTTPServer, Bastion, bdb, binascii, binhex, binstar-script, binstar_client, bisect, bitarray, blaze, blaze-server-script, bokeh, bokeh-script, bokeh-server-script, boto, bottleneck, bs4, bsddb, bundle_image-script, bz2, calendar, Canvas, cdecimal, cfadmin-script, cffi, cgi, CGIHTTPServer, cgitb, chest, chunk, cio_test, clear_comtypes_cache, click, cloudpickle, clr, clyent, cmath, cmd, code, codecs, codeop, collections, colorama, colorsys, commands, commctrl, compileall, compiler, comtypes, concurrent, conda, conda-build-script, conda-convert-script, conda-develop-script, conda-env-script, conda-index-script, conda-inspect-script, conda-metapackage-script, conda-render-script, conda-script, conda-server-script, conda-sign-script, conda-skeleton-script, conda_build, conda_env, configobj, ConfigParser, configparser, contextlib, contextlib2, Cookie, cookielib, copy, copy_reg, cPickle, cProfile, cq-script, createfontdatachunk, Crypto, cryptography, cStringIO, csv, ctypes, curl, curses, cwp, cwutil-script, cx_Oracle, cycler, cygdb-script, Cython, cython, cython-script, cythonize-script, cythonmagic, cytoolz, dask, datashape, datetime, dateutil, dbhash, dbi, dde, decimal, decorator, Dialog, difflib, dill, dircache, dis, distutils, doctest, docutils, DocXMLRPCServer, dumbdbm, dummy_thread, dummy_threading, dynamodb_dump-script, dynamodb_load-script, easy_install, easy_install-script, elbadmin-script, email, encodings, enhancer, entrypoints, enum, errno, et_xmlfile, exceptions, explode, f2py, fastcache, fetch_file-script, filecmp, FileDialog, fileinput, filelock, fits2bitmap-script, fitscheck-script, fitsdiff-script, fitsheader-script, fitsinfo-script, FixTk, flake8, flake8-script, flask, flask-script, flask_cors, fnmatch, formatter, fpformat, fractions, ftplib, funcsigs, functools, functools32, future_builtins, gc, genericpath, get_objgraph, getopt, getpass, gettext, gevent, gifmaker, glacier-script, glob, greenlet, grin, grin-script, grind-script, gzip, h5py, hashlib, heapdict, heapq, hmac, hotshot, htmlentitydefs, htmllib, HTMLParser, httplib, idle-script, idlelib, idna, ihooks, imageop, imagesize, imaplib, imghdr, imp, importlib, imputil, inspect, instance_events-script, io, ipaddress, ipykernel, IPython, ipython-script, ipython2-script, ipython_genutils, ipywidgets, isapi, isort, isympy-script, itertools, itsdangerous, jdcal, jedi, jinja2, json, jsonschema, jsonschema-script, jupyter, jupyter-console-script, jupyter-kernelspec-script, jupyter-migrate-script, jupyter-nbconvert-script, jupyter-nbextension-script, jupyter-notebook-script, jupyter-qtconsole-script, jupyter-script, jupyter-serverextension-script, jupyter-troubleshoot-script, jupyter-trust-script, jupyter_client, jupyter_console, jupyter_core, keyword, kill_instance-script, launch_instance-script, lazy_object_proxy, lib2to3, linecache, list_instances-script, llvmlite, locale, locket, logging, lss3-script, lxml, macpath, macurl2path, mailbox, mailcap, markupbase, markupsafe, marshal, math, matplotlib, mccabe, md5, menuinst, menuinst-script, mhlib, mimetools, mimetypes, MimeWriter, mimify, mistune, mkl, mmap, mmapfile, mmsystem, modulefinder, mpl_toolkits, mpmath, msilib, msvcrt, mturk-script, multifile, multipledispatch, multiprocessing, mutex, nb_anacondacloud, nb_conda, nb_conda_kernels, nbconvert, nbformat, nbpresent, nbpresent-script, netbios, netrc, networkx, new, nltk, nntplib, nose, nosetests-script, notebook, nt, ntpath, ntsecuritycon, nturl2path, numba, numba-script, numbers, numexpr, numpy, odbc, odo, odo-script, opcode, openpyxl, OpenSSL, operator, optparse, os, os2emxpath, painter, pandas, parser, partd, path, pathlib2, patsy, pdb, pep8, pep8-script, perfmon, pickle, pickleshare, pickletools, PIL, pilconvert, pildriver, pilfile, pilfont, pilprint, pip, pipes, pkg_resources, pkginfo, pkginfo-script, pkgutil, platform, player, plistlib, ply, popen2, poplib, posixfile, posixpath, pprint, profile, prompt_toolkit, pstats, psutil, pt2to3-script, ptdump-script, ptrepack-script, pttree-script, pty, py, py_compile, pyami_sendmail-script, pyasn1, pybabel-script, pycc-script, pyclbr, pycosat, pycparser, pycurl, pydoc, pydoc-script, pydoc_data, pyexpat, pyflakes, pyflakes-script, pygmentize-script, pygments, pylab, pylint, pylint-script, pyparsing, PyQt5, pytest, python-argcomplete-check-easy-install-script-script, pythoncom, pytz, pywin, pywin32_postinstall, pywin32_testall, pywin32_testutil, pywintypes, pyximport, qtawesome, qtconsole, qtpy, Queue, quopri, random, rasutil, re, regcheck, register-python-argcomplete-script, regutil, repr, requests, rexec, rfc822, rlcompleter, rmagic, robotparser, rope, route53-script, rst2html, rst2latex, rst2man, rst2odt, rst2odt_prepstyles, rst2pseudoxml, rst2s5, rst2xetex, rst2xml, rstpep2html, ruamel_yaml, run, runpy, runxlrd, s3put-script, samp_hub-script, sched, scipy, ScrolledText, sdbadmin-script, seaborn, select, servicemanager, sets, setuptools, sgmllib, sha, shelve, shlex, shutil, signal, SimpleDialog, simplegeneric, SimpleHTTPServer, SimpleXMLRPCServer, singledispatch, singledispatch_helpers, sip, sipconfig, sipdistutils, site, six, skimage, skivi-script, sklearn, smtpd, smtplib, sndhdr, snowballstemmer, socket, SocketServer, sockjs, sphinx, sphinx-apidoc-script, sphinx-autogen-script, sphinx-build-script, sphinx-quickstart-script, spyder, spyder-script, spyder_breakpoints, spyder_io_dcm, spyder_io_hdf5, spyder_profiler, spyder_pylint, sqlalchemy, sqlite3, sre, sre_compile, sre_constants, sre_parse, ssl, sspi, sspicon, stat, statsmodels, statvfs, storemagic, string, StringIO, stringold, stringprep, strop, struct, subprocess, sunau, sunaudio, symbol, sympy, sympyprinting, symtable, sys, sysconfig, tables, tabnanny, tarfile, taskadmin-script, telnetlib, tempfile, termcolor, test_path, test_pycosat, tests, textwrap, this, thread, threading, thresholder, time, timeit, timer, Tix, tkColorChooser, tkCommonDialog, Tkconstants, Tkdnd, tkFileDialog, tkFont, Tkinter, tkMessageBox, tkSimpleDialog, toaiff, token, tokenize, toolz, tornado, tqdm, trace, traceback, traitlets, ttk, tty, turtle, types, unicodecsv, unicodedata, unittest, unpickle, urllib, urllib2, urlparse, user, UserDict, UserList, UserString, uu, uuid, validate, vba_extract, viewer, volint-script, warnings, wave, wcslint-script, wcwidth, weakref, webbrowser, werkzeug, wheel, wheel-script, whichdb, widgetsnbextension, win2kras, win32api, win32clipboard, win32com, win32con, win32console, win32cred, win32crypt, win32cryptcon, win32event, win32evtlog, win32evtlogutil, win32file, win32gui, win32gui_struct, win32help, win32inet, win32inetcon, win32job, win32lz, win32net, win32netcon, win32pdh, win32pdhquery, win32pdhutil, win32pipe, win32print, win32process, win32profile, win32ras, win32rcparser, win32security, win32service, win32serviceutil, win32timezone, win32trace, win32traceutil, win32transaction, win32ts, win32ui, win32uiole, win32verstamp, win32wnet, win_unicode_console, winerror, winioctlcon, winnt, winperf, winsound, winxpgui, winxptheme, wrapt, wsgiref, xdrlib, xlrd, xlsxwriter, xlwings, xlwings-script, xlwt, xml, xmllib, xmlrpclib, xxsubtype, yaml, zipfile, zipimport, zlib, zmq, _abcoll, _ast, _bisect, _bsddb, _cffi_backend, _codecs, _codecs_cn, _codecs_hk, _codecs_iso2022, _codecs_jp, _codecs_kr, _codecs_tw, _collections, _csv, _ctypes, _ctypes_test, _elementtree, _functools, _hashlib, _heapq, _hotshot, _io, _json, _license, _locale, _lsprof, _LWPCookieJar, _md5, _MozillaCookieJar, _msi, _multibytecodec, _multiprocessing, _nsis, _osx_support, _pyio, _pytest, _random, _sha, _sha256, _sha512, _socket, _sqlite3, _sre, _ssl, _strptime, _struct, _subprocess, _symtable, _system_path, _testcapi, _threading_local, _tkinter, _version, _warnings, _weakref, _weakrefset, _win32sysloader, _winreg, _winxptheme, __builtin__, __future__, __main__`

**Comment by davidhalter** [comment]
Can you try on the dev branch? I think this has been fixed. (The dev branch is a bit buggy though when it comes to other stuff).

**Comment by gandhis1** [comment]
In the latest pip version, I get a shorter list, but most of the completions still seem out of place.

`>>> import jedi
>>> ", ".join(map(lambda x: x.name_with_symbols, jedi.Script("import pandas as ").completions()))
'algos, compat, computation, core, formats, hashtable, index, indexes, info, io, json, lib, msgpack, parser, rpy, sandbox, sparse, stats, tests, tools, tseries, tslib, types, util, _period, _sparse, _testing, _version'`

**Comment by davidhalter** [comment]
Ok. I can reproduce it. Even with the standard library:

```
>>> import jedi
>>> ", ".join(map(lambda x: x.name_with_symbols, jedi.Script("import json as ").completions()))
'decoder, encoder, scanner, tool'
```
