### ISSUE TITLE
Provide an official language-server implementation?

### ISSUE THREAD

**Issue by patrys** [davidhalter/jedi#845]
Microsoft maintains a specifiaction for [language-server-protocol](https://github.com/Microsoft/language-server-protocol) that allows a common API to be reused by multiple IDEs. Someone is already working on [an implementation based on Jedi](https://github.com/palantir/python-language-server) but I think maintaining an official one could help ensure that Jedi provides good enough APIs to implement the necessary endpoints.

I do realize that's quite a bit of work but am willing to help.

**Comment by davidhalter** [comment]
How complicated would it be with the current Jedi API?

**Comment by patrys** [comment]
I think one of the challenges where there is no immediate match between jedi's API and the language server spec is providing hover information for symbols. Currently we use "go to definition" but it would be nice to be able to provide values for literal constants along with their types. IIRC "go to definition" also returns the outer-most decorator for decorated functions but it does not respect `wraps` so the result is usually `inner(param self, param *args, param **kwargs)`.

**Comment by davidhalter** [comment]
Well I think those are both things that are known issues in Jedi itself. That doesn't have anything to do with the implementation.

**Comment by davidhalter** [comment]
I think that there is no need for an official implementation. IMO it doesn't really need to be official to server its purpose. The good thing is that it's very easy to fork a language server protocol implementation, because there's no need for a stable API (both ends are stable so you just have to write the adapter).
