### ISSUE TITLE
Installing jedi downloads 24MB

### ISSUE THREAD

**Issue by takluyver** [davidhalter/jedi#846]
There appears to be a random .wav file in the docs folder of the sdist tarball with nearly 2 hours of audio.

**Comment by davidhalter** [comment]
Thx. I will fix this.

**Comment by takluyver** [comment]
Thanks. Heads up: PyPI does not let you replace a file that was uploaded once, so fixing it will probably require a new version number.

**Comment by davidhalter** [comment]
I have just uploaded the wheel for Python 3. Let me know if somebody really needs the sources. I might need to release a new version in that case.

**Comment by takluyver** [comment]
Thanks, that works for me.

You may find downstream packagers asking for an sdist - I've put a number of wheel-only packages on PyPI (using flit), and there's generally some pushback. I'll let them make that request, though.
