### ISSUE TITLE
standard distribution for jedi 0.10.0 on pypi

### ISSUE THREAD

**Issue by papachoco** [davidhalter/jedi#849]
Hi,

Could you make a standard distribution (sdist / source) available on pypi? This is for legacy installations  (i.e. zc.buildout)

Thanks,

Carlos

**Comment by proofit404** [comment]
Any news?

**Comment by davidhalter** [comment]
As mentioned somewhere else, I have uploaded 0.10.0 and had to delete it again, because the build was broken. Since I cannot re-upload I need to upload `0.10.1` soon.

**Comment by proofit404** [comment]
Make sense. Thanks!

**Comment by ErwinJunge** [comment]
@davidhalter pypi is still showing 0.10.0, do you have an indication of when you will upload 0.10.1?

**Comment by davidhalter** [comment]
Soon. Some very serious bugs need fixing, first.

**Comment by davidhalter** [comment]
https://pypi.python.org/pypi/jedi

**Comment by proofit404** [comment]
Sorry I can't find any change log information for `0.10.1` release.
