### ISSUE TITLE
Fast, Non-lazy Completions.type

### ISSUE THREAD

**Issue by Carreau** [davidhalter/jedi#850]
Hey there !

For once not a bug, but a request for improvement. 
With current IPython integration, I need to greedily compute the `.type` of all completions.
For the terminal version I could it lazily, notebook I can't. In some case (`matplotlib.` ) this can be gargantuesqually slow (don't know if it's an english adverb, but anyway), and AFAICT, jedi is reparsing – or not reusing some available context.

I do understand it can be hard to "Guess" if the context have changed.

So is there a way to tell jedi (like using a context manager): Thinks are not going to change underneath you, can you compute all these things at once ?

Right now it seem like an LRU cache in `mixed.py` does the trick ( line 120ish)

```
@functools.lru_cache()
def parse(grammar, path):
    with open(path) as f:
        source = f.read()
    source = common.source_to_unicode(source)
    return FastParser(grammar, source, path)
```

Though I understand that FastParser is _also_ made to recompute only what's necessary using DiffParser. But FastParser is supposed to have CachedFastParser as a metaclass so should it be cached .. but is not... Anyway getting late let me know if things make sens

**Comment by davidhalter** [comment]
The parser structure/calling is really bad. I know that and I will be working on that. I think you're on to something that I have to look into first.

At least over the lifetime of an Evaluator there is no need to re-parse anything (or even open a file).

**Comment by davidhalter** [comment]
We have fixed this one afaik.
