### ISSUE TITLE
`Script.usages` can trigger out of bounds index in `ParamName.get_param` 

### ISSUE THREAD

**Issue by andylee-ncc** [davidhalter/jedi#856]
In the v0.10.0 tagged commit, sometimes calling `Script.usages` triggers an out of bounds index error in `jedi.evaluate.filters.ParamName.get_param`. For example, looking at usages for `isdir` in jedi's own code by running:

~~~
import jedi, os
filename = os.path.join(os.path.dirname(jedi.__file__), '__main__.py')
jedi.api.Script(source_path=filename, line=18, column=12).usages()
~~~

generates the error:

~~~
    107         params = self.parent_context.get_params()
    108         param_node = search_ancestor(self.tree_name, 'param')
--> 109         return params[param_node.position_nr]
    110
    111

IndexError: list index out of range
~~~

This also affects 8131f1975127e1675edfb8496cad13fcd8cd788b (where origin/dev is at at the moment).

**Comment by davidhalter** [comment]
Fixed. Thanks for the report!
