### ISSUE TITLE
Enhancement: Pick up on PEP-0484 Type hints when present

### ISSUE THREAD

**Issue by DonJayamanne** [davidhalter/jedi#858]
_From @dannystaple on February 9, 2017 17:14_

## Environment data
Python Extension version:  0.5.8
Python Version:   2.7 and 3.x

Independent of platform and VSCode version.

## Expected  behaviour

PEP-484 describes type hints/annotations, and how they can be used in two ways - for Python2.7 and Python 3.x. They are only intended for IDE's Linters and do not actually modify the runtime. IE- They are not enforced.

These type annotations can be used to suggest intellisense lookups for parameters where they should be of a particular object type. 

Example annotations using the comment style:

    def prepare_for_racks(slot, location, boot_env):
        # type: (data_helper.Slot, str, data_helper.BootEnvironment)
        .
        .
        .

Example annotations using Python 3 style (will not work in python 2 and will break some linters):

    def prepare_for_racks(slot: data_helper.Slot, location: str, boot_env: data_helper.BootEnvironment):
        .
        .
        .

It could also lead into a later enhancement to support using a python type linter.

_Copied from original issue: DonJayamanne/pythonVSCode#728_

**Comment by davidhalter** [comment]
Support for PEP 484 was added in the current version. See Changelog: https://github.com/davidhalter/jedi/blob/70200861661a921016563717487c1ced9993acdb/CHANGELOG.rst

See also https://github.com/davidhalter/jedi/pull/663

**Comment by m3nthal** [comment]
I am using Spacemacs with anaconda-mode with Jedi 0.10.0 and type hinting doesn't work for me.

```
from Selenium2Library import Selenium2Library
class S2LExtension:
    @property
    def s2l(self):
        # type: () -> Selenium2Library
        return BuiltIn().get_library_instance('Selenium2Library')
```

When I type `self.s2l.` I don't get any suggestions from Selenium2Library.

**Comment by davidhalter** [comment]
It's not like all of PEP 484 is supported, but a lot of it.

I'm closing, because the original issue was resolved. If you want support for those obscure usages, implement it :)
