### ISSUE TITLE
Ask jedi to not complete in strings ?

### ISSUE THREAD

**Issue by Carreau** [davidhalter/jedi#860]
Would it be possible to ask jedi to not complete to fucntions when inside a string ? That is to say the following to return an empty list ? 

Or is that considered a bug ? 

```
>>> jedi.Script('f("',1,3).completions()
<Completion: abs>
...
```

I can probably look at `_get_module().tree_node.children[-2] to be ErrorToken, but would prefer not to. Ideally I'd like to provide my own string completer from IPython at some point.

**Comment by gandhis1** [comment]
Yes! Especially in docstrings, this is very inconvenient when I use Jedi through VSCode.

**Comment by davidhalter** [comment]
Hmmm. I sometimes like it in docstrings. That's probably why it still exists. We could make a setting, though.

**Comment by Carreau** [comment]
> Hmmm. I sometimes like it in docstrings. That's probably why it still exists. We could make a setting, though.

Would it be possible to detect docstrings as a different type ? I agree that we could use jedi in docstring and that would be helpful.

**Comment by davidhalter** [comment]
That would probably be possible, but a bit more complicated. I'm not sure if it's also more helpful for people to complete just after `>>>`, which is usually what you want.

**Comment by davidhalter** [comment]
At some point there were no completions in docstrings anymore when I was improving some other things. Now I made completions available in three cases:
```
        - Having an indented block of code
        - Having some doctest code that starts with `>>>`
        - Having backticks that doesn't have whitespace inside it
```
