### ISSUE TITLE
Non-deterministic RecursionError in `Script.goto_definitions`

### ISSUE THREAD

**Issue by andylee-ncc** [davidhalter/jedi#861]
In v0.10.0, sometimes calling `Script.goto_definitions` triggers a
`RecursionError` when traversing the AST. For example, looking at definitions
for `str.endswith` in jedi's own code by running the script:

~~~
import jedi
filename = jedi.evaluate.imports.__file__
for ii in range(100):
    jedi.api.Script(source_path=filename, line=346, column=51).goto_definitions()
~~~

generates the error message `RecursionError: maximum recursion depth exceeded`,
with a very long stack trace involving finding things in the AST.

This error does not occur consistently. With a modified version of the test script, I caught 30 RecursionErrors in 100 trials.

The RecursionError does **not** occur for simpler code where jedi can figure out the type of
the object that owns the `endswith` method, like:

~~~
jedi.api.Script(source='def f(x: str):\n    x.endswith("a")', line=2, column=6).goto_definitions()
~~~

I'm on Python 3.5.2.

**Comment by davidhalter** [comment]
Thanks for looking into it. I might need some time to fix this one. Those errors are not so easy to find.

**Comment by davidhalter** [comment]
I did some changes to better avoid extreme amounts of recursions. However it was not enough and I also needed to increase the recursion limit of Python.

Probably we should just be switching away from this extreme amount of recursion and move to queueing which would also allow to use other algorithms such as breadth-first-search.
