### ISSUE TITLE
Please upload sdist for 0.10.0 to the PyPI.

### ISSUE THREAD

**Issue by proofit404** [davidhalter/jedi#869]
Hi David,

anaconda-mode uses easy-install implicitly to install jedi. I'm forced to use easy-install instead of pip. This was a bug in anaconda-mode with long history related to pip `-t` option broken for all mac users.

Can you please submit source distribution to the PyPI? Since easy-install doesn't support wheels.

Regards, Artem.

**Comment by davidhalter** [comment]
Duplicate: https://github.com/davidhalter/jedi/issues/849

**Comment by proofit404** [comment]
Sorry I don't notice existing issue.
