### ISSUE TITLE
Jedi breaks with Spyder 3.0

### ISSUE THREAD

**Issue by arita37** [davidhalter/jedi#870]
I have reported this breaks here :
https://github.com/spyder-ide/spyder/issues/4141

It seems more of Jedi dependencies issue, dont know where to look for de-bugging  :  

Jedi 0.8.1 works in this case:
       module is inside sites-packages (like numpy)

If I add my own custom directory in the PythonPath manager
and do 
    ` import myModule as mm`

it does not work....

Version and main components

```
Win10 64bits
Spyder Version: 3.0.0
Python Version: 2.7.12
Qt Versions: 5.6.0, PyQt5 5.6 on Windows
Dependencies
```

```
jedi >=0.8.1     :  0.8.1 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)
```

Kind regards

**Comment by davidhalter** [comment]
Sorry mate, Jedi is a dependency of Spyder. Not the other way around. If there's an actual bug in Jedi please use the Jedi API to prove it.
