### ISSUE TITLE
Autocompletion for chained function calls

### ISSUE THREAD

**Issue by tapan0007** [davidhalter/jedi#871]
Jedi is not able to provide auto-completion suggestion for the following code. 

_import isl
m = isl.map("{[i]->[j]}")
m.domain().<TAB> (no auto-completion)_

It is able to provide suggestions m.<TAB> but not for the above. Is it able to provide auto-completion for chained function calls?

**Comment by davidhalter** [comment]
Yes it is. `isl` probably is too complicated to understand. Jedi is pretty powerful, however stuff like setattr and metaclasses and some other things are not understood. If you think this is still a problem, please investigate a bit and post an url to that code.

**Comment by tapan0007** [comment]
Will it be possible to achieve auto-completion by following one of the docstring/annotation syntax style (PEP-0484 or sphinx)?

**Comment by davidhalter** [comment]
Yes, both are supported. I think it's also mentioned in the docs https://jedi.readthedocs.io.
