### ISSUE TITLE
No autocompletion on stored objects

### ISSUE THREAD

**Issue by tobig** [davidhalter/jedi#872]
```
class Set:                                                                       
        def intersect(self, other):                                              
                return self                                                      
                                                                                 
class Map:                                                                       
        def domain(self):                                                        
                return Set()                                                     
                                                                                 
# Map().domain().<tab>                                                           
# The above line suggests 'intersect'. This is correct.                          
                                                                                 
# m = Map()                                                                      
# m.domain().<tab>                                                               
# The above line does not suggest any completions.    
```

It seems jedi cannot complete types, when starting from an in-memory object. Am I doing something wrong, is this a bug, or an inherently difficult problem to solve.

I would expect jedi to get the type from m._ _ class _ _ and then perform type completion as normal.

**Comment by davidhalter** [comment]
Are you on working in a Python Shell or in the Editor?

**Comment by tobig** [comment]
In a C-python shell using https://jedi.readthedocs.io/en/latest/docs/usage.html#tab-completion-in-the-python-shell.

**Comment by tobig** [comment]
The precise commands I type are:

$ python
$> import complete.py
$> m = complete.Map()
$> m.domain()."tab"

**Comment by davidhalter** [comment]
Jedi version?

**Comment by tobig** [comment]
0.9.0-1 from the ubuntu packages.

**Comment by davidhalter** [comment]
Then that's the problem.

**Comment by tobig** [comment]
I just updated jedi

>>> print(jedi.__version__)
0.10.0
>>> import complete as c
>>> c.Map().domain().
...__class__         ...__eq__            ...__gt__            ...__lt__            ...__reduce_ex__     ...__str__
...__delattr__       ...__format__        ...__hash__          ...__ne__            ...__repr__          ...__subclasshook__
...__dir__           ...__ge__            ...__init__          ...__new__           ...__setattr__       ...intersect
...__doc__           ...__getattribute__  ...__le__            ...__reduce__        ...__sizeof__        
>>> c.Map().domain().
  File "<stdin>", line 1
    c.Map().domain().
                    ^
SyntaxError: invalid syntax
>>> m = c.Map()
>>> m.domain().
  File "<stdin>", line 1
    m.domain().
              ^
SyntaxError: invalid syntax
>>> # No completions given above

**Comment by tobig** [comment]
I also tried to add type annotations:

class Map:                                                                       
        def domain(self) -> Set:                                                 
                return Set()

**Comment by tobig** [comment]
But this did not help.

**Comment by tapan0007** [comment]
The contexts returned by the evaluate_call_of_leaf() function in the jedi.evaluate.helpers module is an empty list when trying to achieve auto-completion with a stored variable. (m.domain().<TAB>).  In contrast to a case like  isl.map("{ [i] -> [j] }").domain().<TAB> , the contexts returned is the copy of the original AST node. Is this has something to do with MixedObject and CompiledObject?

**Comment by davidhalter** [comment]
```
class Set:
        def intersect(self, other):
                return self

class Map:
        def domain(self):
                return Set()


m = Map().domain().intersect
```

is working for me. Can you please post an example with direct Jedi calls? It might be an issue in your editor.

**Comment by davidhalter** [comment]
I think it has to do with MixedObject, but I'm not sure.

**Comment by tapan0007** [comment]
The following shows the output for the returned contexts by evaluate_call_of_leaf().

` import isl; m = isl.map("{ [i] -> [j] }")
m.domain().<TAB>  #(No auto-completion)`

set([<CompiledObject: isl.map("{ [i] -> [j] }")>])
set([<CompiledObject: <bound method map.domain of isl.map("{ [i] -> [j] }")>>])
set([])  # The returned list is empty. No auto-completion

But in the below case,
`isl.map("{ [i] -> [j] }").domain().<TAB>`

set([<MixedObject: <module 'isl' from 'isl.pyc'>>])
set([<MixedObject: <class 'isl.map'>>])
set([<TreeInstance of <ClassContext: <Class: map@1792-2223>>(<TreeArguments: <String: u'"{ [i] -> [j] }"'>>)>])
set([<BoundMethod: <Function: domain@1169-1183>>])
set([<TreeInstance of <ClassContext: <Class: union_set@2607-2942>>(<TreeArguments: Node(arglist, [Node(argument, [<Name: ctx@1182,25>, <Operator: =>, <Name: ctx@1182,29>]), <Operator: ,>, Node(argument, [<Name: ptr@1182,34>, <Operator: =>, <Name: res@1182,38>])])>)>])

**Comment by davidhalter** [comment]
Can you retry with current Jedi master? I think it works now. (I cannot reproduce it anymore):

```
>>> import complete
>>> complete.Map().domain().<tab>
...__class__         ...__getattribute__  ...__reduce__        ...__sizeof__        
...__delattr__       ...__hash__          ...__reduce_ex__     ...__str__           
...__doc__           ...__init__          ...__repr__          ...__subclasshook__  
...__format__        ...__new__           ...__setattr__       ...intersect
```

**Comment by tobig** [comment]
Hi David,

your example works. However, the following does not show completions:

```
import complete
m = complete.Map()
m.<tab>  # This shows 'domain()' as completion option
m.domain().<tab> # This does not show any completion options.

**Comment by davidhalter** [comment]
Oh fuck, my bad..

**Comment by tobig** [comment]
I am still very interested to see this resolved. Any chance you could have a look!

**Comment by davidhalter** [comment]
Finally! Thanks for insisting that it was not fixed. This was quite a hard one. Took me a few hours and now it's finally in a good shape.

There have been a couple of issues surrounding instances, I hope they are all fixed now. Otherwise please tell me.

**Comment by davidhalter** [comment]
I'm actually not sure if it works with the shell completion that is described there. It's still kind of black magic to me how shell completion works. But I think at least the main issues in Jedi have been fixed. I cannot even complete `Map().domain().` in my REPL :confused: . I'm not really sure what I'm doing wrong and why it works for other people.

**Comment by tobig** [comment]
Perfect. Now all works as expected! Thank you a lot!
