### ISSUE TITLE
Print warnings make it hard to use

### ISSUE THREAD

**Issue by kernc** [davidhalter/jedi#874]
I'm not sure this is jedi bug as the whole stack is: Python < IPython < p**t**python < jedi, but it only manifests since upgrading to jedi 0.10.0.

Environment: jedi==0.10.0, ptpython==0.36, ipython==5.2.2, pandas==0.19.0+479 (git).

Typing the following in the prompt:
```py
>>> import pandas as pd
>>> s = pd.Series()
>>> s.
```
Now, as soon as the last period is pressed, the following FutureWarning is printed at cursor location:
```py
/home/user/venv/lib/python3.4/site-packages/jedi/evaluate/compiled/__init__.py:328: FutureWarning: is_time_series is deprecated. Please use Series.index.is_all_dates
  getattr(obj, name)
```
Which makes the whole prompt input buffer hard to read:
```py

>>> import pandas as pd
>>> s = pd.Series()
>>> s./home/user/venv/lib/python3.4/site-packages/jedi/evaluate/compiled/__init__.py:328: FutureWarning: is_time_series is deprecated. Please use Series.index.is_all_dates
  getattr(obj, name)
|  ← cursor position
```
This repeats _every_ time `s` is followed by a `.`.

Downgrading to jedi 0.9.0 works.

**Comment by davidhalter** [comment]
@Carreau Did you see this as well?

**Comment by Carreau** [comment]
Yes/No. I can trigger an error as well in pure IPython, but it does not mess up the layout. 

Digging in I can trigger an error:

```
is_instance = self._is_instance or fake.is_class_instance(obj)
        # ``dir`` doesn't include the type names.
        if not inspect.ismodule(obj) and obj != type and not is_instance:
            for filter in create(self._evaluator, type).get_filters():
                names += filter.values()
        return names

```

the `ob != type` trigger a custom `__eq__` of pandas crash some things. replacing by `is not` seem worse.

**Comment by davidhalter** [comment]
> replacing by is not seem worse.

How do you mean that?

**Comment by Carreau** [comment]
> How do you mean that?

I get more errors with IPython. Digging in. It's due to IPython trying to get the completions  `types` and many of them error.

**Comment by kernc** [comment]
Can no longer reproduce on Python 3.5, jedi 0.10.2.

**Comment by davidhalter** [comment]
Well the problem is probably that in general that warnings can be triggered by certain actions within Jedi. I'm thinking about wrapping certain parts of Jedi to avoid those warnings.

**Comment by kernc** [comment]
Indeed, I can now reproduce it with:
```py
>>> import pandas as pd
>>> ts = pd.Timestamp('2010')
>>> ts.   # Upon pressing <Tab> after period:
/home/user/venv/lib/python3.4/site-packages/jedi/evaluate/compiled/__init__.d
  getattr(obj, name)

**Comment by kernc** [comment]
Can't reproduce this case any longer in jedi 0.11.0.

**Comment by davidhalter** [comment]
I'll close in favor of #793. It's basically the same issue (plus you don't have the issue with pandas anymore. That doesn't mean it's fixed, though).
