### ISSUE TITLE
Minimal Crash 

### ISSUE THREAD

**Issue by Carreau** [davidhalter/jedi#875]
While debuggin #874 

```
import pandas as pd 
s = pd.Series() 
import jedi
jedi.Interpreter('s.',[ {'s':s}], line=1, column=2).completions()[0].type
```

Should trigger crash in 2 position that use != (replace by `is not`), then `==` (fake.py line 135). Not sure it's the right fix, but I takes notes before forgetting.

**Comment by Carreau** [comment]
Once these are fixed, with is/is not:

```
jedi.Interpreter('s.dat',[ {'s':s}], line=1, column=5).completions()[0].type
```

fails with a 3 stage error Attribute/Key/Value error https://gist.github.com/Carreau/4ed0987c3671d9cb92cf3b8a29542619

**Comment by davidhalter** [comment]
Is this fixed now?

**Comment by Carreau** [comment]
Sorry I have been away and offline for about 10 days, and need to catch up with things. I've seen you did a lot of refactor and need to reinvestigate all of that. It's on my todo list.

**Comment by davidhalter** [comment]
It's working again on the virtualenv branch.
