### ISSUE TITLE
CLI for generating completions

### ISSUE THREAD

**Issue by mkhl** [davidhalter/jedi#877]
I wrote a simple CLI for generating completions (because I wanted to call jedi from outside of python), so I thought I’d ask whether you’d accept a contribution of something like it to `jedi/__main__.py`.

<details>

* I used `plistlib` for the output format because it fit my use case, I expect having to change that to maintain portability.
* I’m aware that the `__main__` block needs error handling.

~~~python
#!/usr/bin/env python

"""Usage: jedi <column> <line> [<path>]

Read Python source on stdin, parse it with Jedi, return its completions.
"""


from __future__ import print_function

import plistlib
import sys

import jedi


def main(line, column, path=None):
    source = sys.stdin.read()
    script = jedi.Script(source, line, column, path)
    return [{'display': c.name, 'image': c.type}
            for c in script.completions()]


def write(completions):
    print(plistlib.writePlistToString(completions))


if __name__ == '__main__':
    line, column, path = sys.argv[1:]
    write(main(int(line), int(column), path))
~~~

**Comment by davidhalter** [comment]
My opinion is that this is not extremely useful for most people (it doesnt fit the 95% of Jedi users). Also `__main__` is already used. With `sith.py` you can actually do that in a pretty similar way (already).

I think I'd rather have a `python -m jedi "complete.here."`, if anything. But at the moment I'll just decline. I'll keep it in my head though. Thanks for your proposal!

**Comment by mkhl** [comment]
Got it. Thanks for your response!

> Also __main__ is already used. […] I think I'd rather have a python -m jedi "complete.here.", if anything.

Right, sorry I haven’t been clearer. I thought if anything this might become another subcommand inside __main__, i.e. `python -m jedi complete "source.code." …`
Of course I see your point though.
