### ISSUE TITLE
Endless loop in Diffparser._parse on 2nd invocation

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#878]
The following script will loop endlessly in `Diffparser._parse` (https://github.com/davidhalter/jedi/blob/fc27ca1b6ada9ac9f70fd38a4f7f803b40d1572e/jedi/parser/diff.py#L284):

```python
from jedi import api

print(api.Script('#dead', 1, 5, '', 'utf-8').call_signatures())
print(api.Script('#dead', 1, 5, '', 'utf-8').call_signatures())
```

`until_line` is 1 here, and `self._nodes_stack.parsed_until_line` is 0.

`_parse` does not seem to be called for the first call?!

Adding a newline to the end of the script (`'#dead\n'`) does not trigger the issue.

**Comment by davidhalter** [comment]
Thanks! I'm really looking for these. I know there's still one or two. Awesome!

**Comment by blueyed** [comment]
@davidhalter 
Do you have an idea how to fix it? Might be quite simple after all, but I stopped after finding it.
