### ISSUE TITLE
Infinite loop in DiffParser

### ISSUE THREAD

**Issue by Mortal** [davidhalter/jedi#882]
Suppose test.py contains the following:

```python
x = str(
    True)

a = 1

def foo():
    pass

b = 2
```

Vimrc:

```
execute pathogen#infect()
syntax on
filetype plugin indent on
let g:jedi#show_call_signatures = 2
set noshowmode
```

Steps to reproduce:
* Open test.py in Vim and press A to start inserting at end of line 1. Note that call signature of str is shown.
* Press `<Esc>`Js to move "True" up a line and start inserting right before True on line 1. Note that call signature of str is again shown.
* Press uuA to move "True" back down and start inserting at the end of line 1.

Expected result:
* Call signature of str shown.

Actual result:
* Vim hangs, CPU pegged at 100%.

Happens on both jedi master (fc27ca1b6ada9ac9f70fd38a4f7f803b40d1572e 'fix a couple of error locations') and dev (a859add6d7d86f3628cfe14f51dd1ae5addee65f Only resolve names for actual modules). I use Vim 8.0.329 in the terminal with both Python 2 and 3 support.

Git bisect suggests that b0f340748cad3555bfa9c2481f70fff02c370e5c "So much work for one simple diff fail." introduced the bug. The commit just before (b779677bf9f32a90f9a31203c91c08ca034f6859) does not exhibit the problem.

If I insert `assert from_ <= to, (self._copied_ranges, (from_, to))` right after [`self._copied_ranges.append((from_, to))`](https://github.com/davidhalter/jedi/blob/b0f340748cad3555bfa9c2481f70fff02c370e5c/jedi/parser/diff.py#L257-L262), then I get the following assertion failure traceback:

```
Traceback (most recent call last):
  File "/home/luser/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 87, in wrapper
    return dct[key]
KeyError: ((), frozenset())
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/luser/.vim/bundle/jedi-vim/jedi_vim.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/home/luser/.vim/bundle/jedi-vim/jedi_vim.py", line 360, in show_call_signatures
    signatures = get_script().call_signatures()
  File "/home/luser/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 300, in call_signatures
    helpers.get_call_signature_details(self._get_module_node(), self._pos)
  File "/home/luser/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 89, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/luser/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 137, in _get_module_node
    parser = FastParser(self._grammar, self._source, self.path)
  File "/home/luser/.vim/bundle/jedi-vim/jedi/jedi/parser/diff.py", line 33, in __call__
    parser.module = parser._parsed = d.update(new_lines)
  File "/home/luser/.vim/bundle/jedi-vim/jedi/jedi/parser/diff.py", line 192, in update
    self._copy_from_old_parser(line_offset, i2, j2)
  File "/home/luser/.vim/bundle/jedi-vim/jedi/jedi/parser/diff.py", line 263, in _copy_from_old_parser
    assert from_ <= to, self._copied_ranges
AssertionError: [(3, 7), (8, 7)]
```

I would try to fix the diff parser myself, but I don't understand it well enough.

**Comment by davidhalter** [comment]
I can reproduce. Thanks a lot. I'm really looking out for these. I have no clue what it exactly is, but it's probably something small.

**Comment by davidhalter** [comment]
The assert actually doesn't tell you much. It may be 8 and 7, because the range function that is used later will increase by one (yes it's all a bit weird) and therefore it works.

**Comment by davidhalter** [comment]
Only problem is that I have a hard time reproducing it in pure Python. And I'm pretty sure it's not a VIM issue.

**Comment by davidhalter** [comment]
WTF. It looks like it's even freezing on way simpler stuff:

Can you confirm?
```
vi foo.py
:set paste
i<enter><wait 2 seconds><enter>
```

cc @blueyed

**Comment by blueyed** [comment]
@davidhalter 
Yes, that looks like the issue I've bisected last week: https://github.com/davidhalter/jedi/issues/878 (with a easy-to-reproduce test case).

**Comment by Mortal** [comment]
@davidhalter Indeed I can reproduce the error in that simple case.

I've been running into this issue seemingly at random for the last week or so -- it's only this weekend that I had time to reproduce it on a small example. I hope you can resolve this. Every while-loop deserves a termination proof!

**Comment by davidhalter** [comment]
@blueyed Thanks. Sorry thought they were unrelated.

> Every while-loop deserves a termination proof!

Haha, if it was just that easy :-) The problem is usually that the preconditions that exist are wrong (due to bugs). In this case something is probably buggy in the tokenizer.

**Comment by blueyed** [comment]
@davidhalter 
You might still have some assertion in there to prevent this, and/or return in case the variables do not change anymore.

**Comment by davidhalter** [comment]
There's an assertion now and I think #878 is fixed. Please test.

**Comment by blueyed** [comment]
#878 seems to be fixed - according to my test case.  Thanks!
I think those fixes should go into master soon, and e.g. jedi-vim's submodule should get updated then.

**Comment by Mortal** [comment]
@davidhalter Your test case of `i<enter><wait 2 seconds><enter>` no longer causes the problem, but my test case in the issue description still goes in an infinite loop in `_copy_from_old_parser`:

```
(gdb) py-bt
Traceback (most recent call first):
  File "/home/rav/.vim/bundle/jedi-vim/jedi/jedi/parser/diff.py", line 220, in _copy_from_old_parser
    line_stmt = self._get_old_line_stmt(parsed_until_line_old + 1)
  File "/home/rav/.vim/bundle/jedi-vim/jedi/jedi/parser/diff.py", line 177, in update
    self._copy_from_old_parser(line_offset, i2, j2)
  File "/home/rav/.vim/bundle/jedi-vim/jedi/jedi/parser/diff.py", line 33, in __call__
    parser.module = parser._parsed = d.update(new_lines)
  File "/home/rav/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 137, in _get_module_node
    parser = FastParser(self._grammar, self._source, self.path)
  File "/home/rav/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 89, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/rav/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 300, in call_signatures
    helpers.get_call_signature_details(self._get_module_node(), self._pos)
  File "/home/rav/.vim/bundle/jedi-vim/jedi_vim.py", line 360, in show_call_signatures
    signatures = get_script().call_signatures()
  File "/home/rav/.vim/bundle/jedi-vim/jedi_vim.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/home/rav/.vim/bundle/jedi-vim/jedi_vim.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "<string>", line 1, in <module>
```

Furthermore, your assert in `_parse` is not triggered.

**Comment by davidhalter** [comment]
@blueyed I agree. I'd actually like to release soon as well again. Just want to fix a few bugs.

**Comment by davidhalter** [comment]
@Mortal Thanks, I have added another assert and I can reproduce it. This one is a bit harder, since it's probably a bug in the diff parser.

**Comment by davidhalter** [comment]
Found it. Thanks again for the detailed test and if you want to do me a favor, stay on the dev branch (at least for the next few weeks) and tell me if there's something wrong. :)

**Comment by Mortal** [comment]
Thanks for fixing it! I can confirm that my test case no longer causes an infinite loop as of af9b0ba8d697fd4d9953f84443b45ea7a744d778. I'll stay on the dev branch and let you know if I find more issues.
