### ISSUE TITLE
Is it possible to use Jedi's API to locate all local variables and function parameters in a script?

### ISSUE THREAD

**Issue by aivarannamaa** [davidhalter/jedi#885]
(I'm sorry to use bug-tracker for asking questions, but I didn't find other contact possibilities).

I'm writing an educational Python IDE and I want to format all local variables differently from global variables. I got the positions of local variables by messing with Jedi 0.9 private parts, but in 0.10 some of them are gone (eg. Script._parser).

I understand that it's not wise to touch others' private parts so I'm hoping to find a proper way to do this.

**Comment by davidhalter** [comment]
Have you tried using `jedi.names`? This gives you all variables. There's a `parent` attribute as well on the returned classes. Maybe that's what you want.

**Comment by aivarannamaa** [comment]
Thanks for the hint!

I tried this:

```python
for definition in jedi.names(source, all_scopes=True, definitions=True, references=True):
    if definition.parent().type == "function": # The name is located in a function ...
        ass = definition.goto_assignments()
        if len(ass) > 0 and ass[0].parent().type == "function": # ... and is assigned to in a function
            print("Found a local variable:", definition.name)
```

It almost worked, but failed, when global variables were assigned in a function (this code incorrectly treats these as locals). Please let me know if I've misunderstood or misused something! I understand that `goto_assignments` is not meant for finding all ocurrences, but I don't know other tools to use. (I got the impression that  `usages` is currently based on `goto_assignments` and also can't look upwards from the last assignment.)

For now I decided to keep my previous approach of messing with internals (just updated my code for version 0.10). In case you're interested, here's the code: https://bitbucket.org/plas/thonny/src/010f52976cb5e3b380dc4a22caa2429d672985e2/thonny/plugins/locals_marker.py?at=master&fileviewer=file-view-default#locals_marker.py-34

Anyway, Jedi is still a great tool -- thank you for your effort!

**Comment by davidhalter** [comment]
> It almost worked, but failed, when global variables were assigned in a function 

That's a case I never thought of in `names`.

> I understand that goto_assignments is not meant for finding all occurrences, but I don't know other tools to use

I'm not sure I understand. Wouldn't a call to `parent()` solve your issue?

**Comment by davidhalter** [comment]
Closing, because the question was never answered.

Happy to reopen if it's clearer what you want.
