### ISSUE TITLE
Unable to find definition when path specified to the script

### ISSUE THREAD

**Issue by sudarshang** [davidhalter/jedi#886]
`jedi.Script().goto_definitions` fails to find any definitions when the path of the file containing the code snippet is passed as an argument to `Script`.

goto_definitions returns the definition when the path kwarg is not provided to `Script`
`
jedi.Script(source='from jedi_import_error._jedi_import_counter import JediImportCounter')
s.goto_definitions() -> [<Definition class JediImportCounter>]
`

If the path to file is provided, then `goto_definitions` does not return any definitions even if the text of the file is identical to `source`

`
s = jedi.Script(source='from jedi_import_error._jedi_import_counter import JediImportCounter', path='/home/smg/Dropbox/projects/jedi_import_error/jedi_import_error/jedi_import_error.py')
s.goto_definitions() ->[]
`

I have created a sample repo [here ](https://github.com/sudarshang/jedi_import_error) to demonstrate this error. See also the ipython [gist](https://gist.github.com/sudarshang/99615235bd1c2b18cc4272319b60b4cb)

**Comment by davidhalter** [comment]
Thanks for the solid reproduction case. It should be fixed now, along with a few similar issues.
