### ISSUE TITLE
Freeze when using Script twice (if second source is without names)

### ISSUE THREAD

**Issue by aivarannamaa** [davidhalter/jedi#897]
Following code causes Jedi 0.10 to freeze on second `goto_definitions`:
```python

from jedi import Script

s = Script(source="a\n", line=1, column=0, path="test.py")
s.goto_definitions()
print("After first")

s = Script(source="\n", line=1, column=0, path="test.py")
s.goto_definitions()
print("After second")
```

Same happens when second source contains only a comment and a linebreak.

The freeze doesn't happen if I use different path for second script or if second source contains some (non-comment) Python tokens before the linebreak (a name or even a single quote would do).

Platform:  32-bit Python 3.6.1 rc1 on Windows 10.

**Comment by aivarannamaa** [comment]
Looks like the workaround is to always append eg, `"\n__dummy__variable__"` to source before sending it to `Script`

**Comment by davidhalter** [comment]
Can you retry on the dev branch? I think we have fixed this one. Happy to reopen if you still have this issue.

**Comment by aivarannamaa** [comment]
At least this exact case seems to run fine in dev branch.
