### ISSUE TITLE
Include decorator info with function definition

### ISSUE THREAD

**Issue by honorabel** [davidhalter/jedi#900]
Feature request
On the static analysis side, it would be great if function definitions included information about any/all decorators attached to that function.  Maybe I'm missing something in the api docs?

**Comment by honorabel** [comment]
Ah, though looks like its maybe possible to a degree using the AST node?
```
usages[0]._name.tree_name.parent.get_decorators()
```

**Comment by davidhalter** [comment]
Yes, it is possible. Would you want something added to the API? If so what would you propose?

**Comment by honorabel** [comment]
Eh, I mean, given that it's accessible via the ast, it doesn't seem as high priority
