### ISSUE TITLE
Support for understanding Python3.6 new string literals

### ISSUE THREAD

**Issue by karolyi** [davidhalter/jedi#901]
Hey guys,

I'm not sure this has been posted here, but Jedi aside from being great, doesn't support the [new string literals](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498) added in Python3.6.

Any chance of supporting it in the near future?

Cheers,
László

**Comment by davidhalter** [comment]
How would you say should Jedi support them? What are you thinking of?

**Comment by karolyi** [comment]
I'm using sublime with anaconda, with uses Jedi. I don't know what the problem is, but when I start to use the new string literals, the autocompletion stops working. Can this be because of Jedi?

When I restore the 3.5-style `''.format()`, the autocompletion works again. I assume Jedi has problem with understanding the code.

**Comment by davidhalter** [comment]
Jedi version?

**Comment by karolyi** [comment]
@DamnWidget [just rolled back](https://github.com/DamnWidget/anaconda/commit/223cc612b0318262535ac488d1f4b4121c2e8f0d) from `0.10.0`.

**Comment by DamnWidget** [comment]
Hi there, I did rollback from 0.10.0 (82d165a7) to 0.10.0 (f05c0714c7)

**Comment by davidhalter** [comment]
What? can you please talk?

**Comment by karolyi** [comment]
what is there not to be understood?

**Comment by davidhalter** [comment]
You're talking to a person that was not mentioned in this ticket before.

**Comment by DamnWidget** [comment]
I don't know if you are speaking to me @davidhalter but I just pointed to the commits that I did rollback and from which one I did it, I have o idea about whatever the issue is about.

**Comment by davidhalter** [comment]
ah lol. I did not really understand it. It's a bit confusing, but anyways. If there's an issue with Jedi, let me know. I just think that this is not an issue with Jedi but rather with the version OR python version.
