### ISSUE TITLE
jedi pip package 0.10.0 broken?

### ISSUE THREAD

**Issue by raghavkarol** [davidhalter/jedi#904]
I'm using jedi in Emacs and get the following error in `*Message*` buffer on completions; same error can also be invoked on calling `jedi:show-doc` 
```
deferred error : (error "\"RuntimeError('maximum recursion depth exceeded in cmp',)\"")
```

jedi is installed using `package-install` and the jedi server installed using `jedi:install-server`.

Information about jedi server and the virtual env
```
(default) Raghav-Mac-Mini:.python-environments rkarol$ pwd
/Users/rkarol/.emacs.d/.python-environments
(default) Raghav-Mac-Mini:.python-environments rkarol$ pip freeze
appdirs==1.4.3
epc==0.0.5
jedi==0.10.1
jediepcserver==0.2.7
packaging==16.8
pyparsing==2.2.0
sexpdata==0.0.3
six==1.10.0
virtualenv==15.1.0
```

It seems like an issue with `jedi==0.10.0`, dowgrading, downgrading to `jedi==0.9.0` works.

**Comment by davidhalter** [comment]
Please provide a reproduction case. It's well known that there might be such errors. We're trying to fix them.

**Comment by davidhalter** [comment]
In #905 he mentioned that this might be related to the old release. `0.10.1` was bugged and is fixed now. Let me know if it's working for you now (after upgrading to `0.10.2`).

**Comment by raghavkarol** [comment]
@davidhalter - confirming `0.10.2` is working for me.
