### ISSUE TITLE
jedi-0.10.1 release on pypi is missing grammar*.txt

### ISSUE THREAD

**Issue by RichardBarrell** [davidhalter/jedi#905]
Possibly related to #904? I found this while trying to track down the same issue on my laptop.

Both the wheel `jedi-0.10.1-py2.py3-none-any.whl` and sdist tarball `jedi-0.10.1.tar.gz` on [jedi 0.10.1's pypi page](https://pypi.python.org/pypi/jedi) are missing all the grammar files such as `grammar2.7.txt` and `grammar3.6.txt`.

This seems to have happened despite the fact that `MANIFEST.in` has the line `include jedi/parser/grammar*.txt`.

To find this, I attached strace to the anaconda-mode process which Spacemacs had spawned for syntax checking. The strace output from just after the anaconda-mode process received an RPC from Spacemacs contains very many repetitions of:

    open("/home/RichardB/.emacs.d/.cache/anaconda-mode/0.1.8/jedi-0.10.1-py2.7.egg/jedi/parser/python/grammar3.6.txt", O_RDONLY) = -1 ENOENT (No such file or directory)

**Comment by RichardBarrell** [comment]
Update: this appears to be the root cause of #904 for me. If I fix my installed jedi-0.10.1 install in-place by copying the `grammar*.txt` files from a git checkout of jedi into the `jedi/parser/python/` directory, #904 stops manifesting for me.

**Comment by davidhalter** [comment]
Yeah. Python packaging sucked. Solved by #902. It's released already.

**Comment by RichardBarrell** [comment]
Thank you! 👍
