### ISSUE TITLE
jedi shows wrong parameters 

### ISSUE THREAD

**Issue by monkoose** [davidhalter/jedi#909]
There is some functions that use additional commas like `numpy.arange()`. It looks like this `arange([start,] stop[, step,], dtype=None)`. Look at `]` between commas. And jedi(jedi-vim) transform it to `arange(param start, param stop, param step, param , param dtype)`. Look at blank param.

**Comment by davidhalter** [comment]
Not sure Jedi can help with this one. This is something that is not possible in Python and I'm not sure how we would even make this possible in the API.

**Comment by davidhalter** [comment]
This is not going to happen at least as long `range()` has the big issue. For range they just named the params x and y instead of start and stop, which is maybe less confusing. It's in typeshed. So maybe there will be a solution 5 years away, but I won't force that and close this issue for now.
