### ISSUE TITLE
Cantnot complete in docstrings,why not support it?

### ISSUE THREAD

**Issue by wzdnzd** [davidhalter/jedi#911]
![gif](https://cloud.githubusercontent.com/assets/8565764/25171388/3ccee838-2520-11e7-9a36-b45ac2894e72.gif)

**Comment by davidhalter** [comment]
It is actually possible to use Jedi completions in docstrings. Your IDE plugin is probably disabling that. So please use the issue tracker of your plugin.

There are however discussions to disable it in docstrings. Maybe with a setting. But that is not related to this issue.

```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
REPL completion using Jedi 0.10.3
>>> import jedi
>>> jedi.Script('""', column=1).completions()
[<Completion: abs>, <Completion: all>, ...]
```
