### ISSUE TITLE
Completion after number provides built-in keywords

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#913]
This seems as if it's not intentional:

```
>>> jedi.__version__
'0.10.2'
>>> s = jedi.Script("123", line=1, column=3)
>>> s.completions()
[<Completion: and>, <Completion: if>, <Completion: in>, <Completion: is>, <Completion: not>, <Completion: or>]
```

Originally reported as jorgenschaefer/elpy#1123

**Comment by davidhalter** [comment]
`1and""` is valid code :) There's way weirder stuff without spaces that works in Python: `br''or.0jif.1else-...`.

I gave a talk about it. It's not a perfect one, but some some parts are interesting and fun :) https://www.youtube.com/watch?v=6NVUbO7pFtA
