### ISSUE TITLE
_do_import/infer_import don't make use of cache (read) but do write.

### ISSUE THREAD

**Issue by Carreau** [davidhalter/jedi#915]
Adding pint statements to `_save_to_file_system` and running something like:

```
import matplotlib.pyplot as plt
from jedi import Interpreter, Script

interpreter = Script('''import matplotlib.pyplot as plt
plt.''')
completions = interpreter.completions()
for c in completions:
    c.type
```

Allow one to see that jedi will save a lot of parser information everytime the script is ran:

```
save to fs /Users/bussonniermatthias/anaconda/lib/python3.6/site-packages/matplotlib/pyplot.py <Module: @3-4144> False
save to fs /Users/bussonniermatthias/anaconda/lib/python3.6/__future__.py <Module: @1-141> False
save to fs /Users/bussonniermatthias/anaconda/lib/python3.6/site-packages/matplotlib/text.py <Module: @1-2382> False
save to fs /Users/bussonniermatthias/anaconda/lib/python3.6/site-packages/matplotlib/patches.py <Module: @3-4615> False
save to fs /Users/bussonniermatthias/anaconda/lib/python3.6/site-packages/matplotlib/artist.py <Module: @1-1520> False
save to fs /Users/bussonniermatthias/anaconda/lib/python3.6/site-packages/matplotlib/ticker.py <Module: @1-2462> False
save to fs /Users/bussonniermatthias/anaconda/lib/python3.6/site-packages/matplotlib/axes/_subplots.py <Module: @1-227> False
save to fs /Users/bussonniermatthias/anaconda/lib/python3.6/s...
```

Diving into this one can see that the cached files are never read. So something is missing the opportunity to use caching.

I'm going to __guess__ that might be because file content may change. My I suggest a caching base not only on file path, but file content hash ?

**Comment by davidhalter** [comment]
I'm not exactly sure what you mean with the files are never read. AFAIK the files are read on repeated usages of `Script`. However there's also in-memory caching. This means that loading from file will only happen when you restart Python.

**Comment by Carreau** [comment]
> I'm not exactly sure what you mean with the files are never read. AFAIK the files are read on repeated usages of Script. However there's also in-memory caching. 

> This means that loading from file will only happen when you restart Python.

That the part that does not work, they are not loaded from files (AFAICT). 
Also if they were read from disk, I expect these to no be re-written to disk every time. 


```diff
~/dev/jedi dev $ git diff
diff --git a/jedi/parser/cache.py b/jedi/parser/cache.py
index 182a8a47..e30b6695 100644
--- a/jedi/parser/cache.py
+++ b/jedi/parser/cache.py
@@ -89,6 +89,7 @@ def _load_from_file_system(grammar, path, p_time):
             else:
                 raise

+        print('reading from hash(grammar, ', path , ')')
         with open(cache_path, 'rb') as f:
             gc.disable()
             try:
@@ -117,6 +118,7 @@ def save_module(grammar, path, module, lines, pickling=True):


 def _save_to_file_system(grammar, path, item):
+    print('writing to hash(grammar, ', path , ')')
     with open(_get_hashed_path(grammar, path), 'wb') as f:
         pickle.dump(item, f, pickle.HIGHEST_PROTOCOL)
```

```python
 ~/dev/jedi dev $ cat jread.py
import matplotlib.pyplot as plt
from jedi import Interpreter, Script

interpreter = Script('''import matplotlib.pyplot as plt
plt.''')
completions = interpreter.completions()
```
```bash
 ~/dev/jedi dev $ python jread.py # should write some cache files, maybe read some
reading from hash(grammar, ~/anaconda/lib/python3.6/site-packages/matplotlib/__init__.py )
writing to hash(grammar,  ~/anaconda/lib/python3.6/site-packages/matplotlib/pyplot.py )

 ~/dev/jedi dev $ python jread.py # should read __init__.py and pyplot.py, write nothing
reading from hash(grammar,  ~/anaconda/lib/python3.6/site-packages/matplotlib/__init__.py )
writing to hash(grammar,  ~/anaconda/lib/python3.6/site-packages/matplotlib/pyplot.py )
```

I expect the second to be 
```
reading from hash(grammar,  ~/anaconda/lib/python3.6/site-packages/matplotlib/__init__.py )
reading from hash(grammar,  ~/anaconda/lib/python3.6/site-packages/matplotlib/pyplot.py )
```

It does not.

Does that make more sens ?

**Comment by davidhalter** [comment]
That is weird. Should not happen. I'm actually a bit surprised. I thought we had tested that one. But I might have changed something in the tests to make this even possible.

**Comment by Carreau** [comment]
Hum, things seem to be fixed now. At least on 9fb7fb66da2f8eef536f41ae2c122af89921e5ec. 
Closing. Not sure why.

**Comment by Carreau** [comment]
Well actually no, I miss-retested. reopening.

**Comment by Carreau** [comment]
Seem to come from 

```
/jedi/evaluate/imports.py(472)_load_module()
-> module_node = parse(code=code, path=path, cache=True, diff_cache=True)
```

As `code` is not `None` it will skip the loading from cache and will do a diff-parser, which try to get from in-memory, but its not there yet.

**Comment by Carreau** [comment]
I'm going to have a potentially dumb question. Is there any reason why you do not cache things on disk not based on the hash of their filename but base on the hash of their content ? I get that reading the file may be expensive, but not that much compared to pickling/unpickling.

I can see that `__init__.py`  may be empty, but there could be a likely simple cutoff: everything below `<NUMBER>` characters does not get cached. Anything beyond that is likely unique.

**Comment by davidhalter** [comment]
I didn't really measure it. If it doesn't increase pickling time by a lot, why not? I guess. My reasoning was always to 

BTW: If you want to make changes to the parser, please look at https://github.com/davidhalter/parso. It's the jedi parser with a few changes. Jedi will be switching to it, soonish.

**Comment by Carreau** [comment]
Ok, thanks. I'll give a try to your parser and measure hashing long strings.

**Comment by CodeMonk** [comment]
This is hitting me bad with a large django app.  I've subscribed so I can go back to jedi, but, for now, I'll have to stick to YouCompleteMe, and the taste of vomit in my mouth :(

**Comment by davidhalter** [comment]
@CodeMonk YouCompleteMe is actually using Jedi.

**Comment by CodeMonk** [comment]
Hmm - YCM was much faster, just a pain to keep updated/installed due to the compilation. I get a 5-10 second delay on the first django completion every time I restart vim with vim-jedi.

I've temporarily moved to neocomplete until the caching issue is fixed.

**Comment by davidhalter** [comment]
Both neocomplete and YCM use jedi. Contrary to jedi-vim they just have an async server implementation that allows them to not freeze your whole VIM.

**Comment by sirfz** [comment]
In my experience, neocomplete freezes only the first time when completion is being loaded for a large module (e.g. numpy or tensorflow) and later attempts all complete fast. YCM doesn't freeze, but you won't see any completion until loading is done (but you can still use vim in the meantime).

**Comment by davidhalter** [comment]
I have rewritten the caching layer in parso. Can you recheck if this is still an issue? (Current Jedi master)

**Comment by davidhalter** [comment]
I'll close, because I think it was fixed. Let me know if you disagree and I'll reopen.

**Comment by CodeMonk** [comment]
Sorry -- I'll  try to test soon. Moved to nvim, and I don't see the issue
there.
