### ISSUE TITLE
Interactively defined objects have empty params

### ISSUE THREAD

**Issue by Carreau** [davidhalter/jedi#917]
I'm still poking around the IPython completions and pondering improvement. 
There seem to be ways in jedi to get `call_signature`s, would there be a ways when using `Script(...).completions` to get a `call_signature`  on completions objects (that are callable of course).

Thoughts ?

**Comment by davidhalter** [comment]
Have you tried `Completion.params`? IIRC it uses the same logic that is used in `call_signature`.

**Comment by Carreau** [comment]
> Have you tried Completion.params? IIRC it uses the same logic that is used in call_signature.

Hum, it does indeed work for some things but not others, like interactively defined objects:

```
In [2]: import jedi
   ...: import numpy as np
   ...: def my_histogram(a, bins=10, range=None, normed=False, weights=None, density=None):pass

In [4]: jedi.Interpreter('np.histog', [{'np':np, 'my_histogram':my_histogram}], line=1, column=9).completions()[0].params
Out[4]:
[<_Param param a>,
 <_Param param bins=10>,
 <_Param param range=None>,
 <_Param param normed=False>,
 <_Param param weights=None>,
 <_Param param density=None>]

In [5]: jedi.Interpreter('my_histog', [{'np':np, 'my_histogram':my_histogram}], line=1, column=9).completions()[0].params
Out[5]: [<_Param param >]
```

I can reconstruct the signature from that though. Thanks.

Should I close or leave open as interactively defined objects have empty params ?

**Comment by davidhalter** [comment]
Just leave it here. I renamed the title.

**Comment by davidhalter** [comment]
d1c85191a0931bfa5dd0773d6d2f754199ee9699

We're using `inspect.signature` now. It's really awesome and I think that it solves a lot of issues around params. Annotations now also work much better when used in a REPL.
