### ISSUE TITLE
[Question] Best approach for Jedi + remote FS

### ISSUE THREAD

**Issue by keegancsmith** [davidhalter/jedi#918]
I have a use case of lazily loading a checkout of a repo and running jedi of it. Jedi in a few places does `open` calls assuming the file exists locally. Example is here https://github.com/davidhalter/jedi/blob/master/jedi/evaluate/imports.py#L502

Instead I would love if I could provide an opener or something similar so I could lazily load in remote files (without using a larger hammer like FUSE). Do you have any advice on the best approach for that? I'm happy to contribute code. Currently I have a hacked fork of Jedi which kinda works for my usecase, but would love to get something upstream.

This is very similiar to providing the source to `jedi.Script`, except I also want to provide source for other files that are lazily evaluated in.

**Comment by davidhalter** [comment]
We've had this feature request before. Previously there were some abstractions missing in the parser. Now that we have that abstraction it should be a lot easier to add a way to modify the default IO.

It's a bit more complicated than just replacing `open` calls, because there are also calls to `os.path.getmtime`, `makedirs` (for creating cache only), `os.path.exists`, `os.path.isdir`, `os.listdir` and there's even some strange stuff like using `chdir` in `jedi.evaluate.sys_path`.

So I'm not sure there's a fast solution here, I guess I'll definitely look at it once I release the parser as a separate project #895.

My goal would probably be to have an abstraction class that does all the IO (including listdirs etc.). If you want you could also do that. My idea is something like:

```
import os
from abc import abstractmethod, ABCMeta

class AbstractIO(object, metaclass=ABCMeta):
    @abstractmethod
    def open(self, path):
        raise NotImplementedError

    @abstractmethod
    def listdir(self, path):
        raise NotImplementedError


class FileSystem(AbstractIO):
    @contextmanager
    def open(self, path):
        with open(path) as f:
            yield f

    def listdir(self, path):
        return os.listdir(path)

```

Let me know what you think!

**Comment by keegancsmith** [comment]
@davidhalter thank you for the comment. The `AbstractIO` approach is what I was thinking of doing. Thanks for pointing out the other areas there is IO. At least from my perspective its alright for the cache to write to the local FS, my main objective is just being able to use Jedi without having all files checked out from a repo.

I assume I also need to do some tricks for `importlib`? I haven't solved this part of the problem yet (nor read much about it), but I assume I'd need to somehow hook into that as well.

I may have time this week to send out a PR which implements this and we can continue the discussion from there. No pressure to accept the PR, will do it mainly to achieve my own goals.

**Comment by davidhalter** [comment]
@keegancsmith I don't think you need to change anything about `importlib`. It's pretty well abstracted. What you need to do however is somehow make it possible to change the `sys.meta_path`. The `finder` objects contained in there are doing the actual IO. That's also how you could e.g. create a cloud storage import system without actually having the files locally.

**Comment by cryptomaniac512** [comment]
Is there any news about this feature? I think it would be very convenient to work with the code inside the containers.

**Comment by davidhalter** [comment]
What does this have to do with containers?

**Comment by cryptomaniac512** [comment]
If I understand correctly, with this feature I can connect into Docker container and work with code and libraries inside them.

Sorry for my bad English

**Comment by davidhalter** [comment]
Well if you write the stuff yourself that connects into a docker container, I think that's true.

**Comment by gatesn** [comment]
Looks like SourceGraph have made some progress here: https://github.com/sourcegraph/python-langserver/blob/master/langserver/jedi.py

**Comment by keegancsmith** [comment]
@gatesn We (Sourcegraph) use a fork of Jedi to accomplish it as well. We haven't gotten around to cleaning it up for upstream though.

**Comment by valentjedi** [comment]
I'm also hyped about opportunities it will give! One concern I have though is what to do with `goto`s? If source is some remote destination we can't just jump there. So either editors themselves will have to implement such jump (e.g. via TRAMP in case of emacs) or we can jump to some cached source (like PyCharm does in case of remote interpreter).

**Comment by gatesn** [comment]
Same behaviour as C modules, e.g. the string built in. There is no source that Jedi can jump to.

**Comment by valentjedi** [comment]
I think there might be a solutions similar to PyCharm. What they do is copying remote sources to some local directory like `.idea/remote_sources/site-packages/django/__init__.py` and when you jump to definition you find yourself there. But I don't know if jedi itself should do it or some `CustomIO` implementation. I think the latter.

So I think about `jedi` with abstracted io and some option to hook into io-process and some plugin like `jedi-remote` which will do this stuff and give jedi sources it can work with.

**Comment by davidhalter** [comment]
Ok. Now I feel like we have a good solution in Jedi. I think there are still a few things that might need patching, but that's really a minority and most things should work (things like buildout probably don't, but nobody uses that anyway). 

The basic idea is that Jedi loads FileIO objects now and passes them to parso. These know how to load source code - and know when a file was changed the last time. If anybody is actively testing this, feel free to file bug reports/pull requests. I probably won't fix them, but I'm glad to merge these.

In combination with sys.meta_path (not sure if it works well in Python 2), you can return whatever source code you want and Jedi can deal with it.

Currently this stuff is only available on the typeshed branch with the latest parso release.

It took me a while, but we're finally using abstract IO.
