### ISSUE TITLE
[Question] Using Jedi for AST parsing + type deduction

### ISSUE THREAD

**Issue by gosella** [davidhalter/jedi#920]
Hello!

I'm considering the Jedi's parser as a replacement for the python's `ast` module, to use it for inferring the types of the variables/parameters found in the parse tree.

Is that feasible?

Right now I managed to get a parse tree from the source but I'm lost about how to get the type(s) of a certain name from it. I can find the types from an Script but I don't know how to access the parse tree from it (or if that is the most convenient/efficient way to do it for my use case). 

I'm not really interested in getting the completions, only to trigger the deduction of the types for certain names (they don't even have to be all the names).

Any pointers/suggestions would be very appreciated!

**Comment by davidhalter** [comment]
Hmm why wouldn't you use the jedi API itself? There 's an api called `jedi.names`. It basically returns the names that you want and then you can infer them. If you just use the Jedi parser you have to write all of that stuff by yourself (which doesn't make a lot of sense, because if you want to do it well it's years of work).

**Comment by gosella** [comment]
We are developing a project that use the `ast` module to translate a subset of Python code to another language.

The problem I'm facing is that sometimes I have to generate different code from the same Python source. For example, if I get `y = x[1]`, it could result in code for accessing a list or for accessing a string depending if I can deduce that `x` can hold a reference to a `list` or a `str` object.

It seemed wasteful to parse the source code with the `ast` module and then reparse it with Jedi's own parser to get type inference. That's why I was asking if there was a simple way to get type inference from the parse tree (or the other way, to get the parse tree and use it to get type inference).

Given that I will also have to adapt my current codebase from using the AST to use the Jedi's own syntax tree, if I also will have to fight the Jedi API to get what I need, then I probably should follow your advice and use Jedi only for type deduction.

Currently, I'm creating a new `Script` object with the line/column of the variable I need the type inference every time I found a conflicting case and I use `goto_definitions()` method to get the inferred types. That seems right to you? Or there is a better/simpler/more efficient way to do it?

**Comment by davidhalter** [comment]
As I said. if you want to deduce just names, use the `jedi.names` API. I'm pretty sure it does most things that you might need.

I'm not sure what you need the parser for. You could of course abuse Jedi's non-public APIs. However that might get you into some problems later on. Otherwise you could just load the cached files from the jedi parser itself. Just reloading the cache with `parse(..., cache=True)` actually just gets the file from cache.

**Comment by gosella** [comment]
Couldn't find a way to get the deduced types from the definitions returned by `jedi.names` until I looked at the private methods and found `_goto_definitions()` (with the nice "# TODO make this function public." :smiley: ). I'm guessing that's what you are referring to? Can I count on that been there in the future?

About the parser, my idea was to do a single parse of a complete Python source file and from the resulting tree translate the nodes to a different language (like you do with refactoring except that you get the source code expressed in another programming language). Then, I would use the jedi `Evaluator` to ask for information about types. Right now, I'm using the AST from the standard `ast` module for the first part but was interested in using the jedi parser instead if that helped for the second part.

I guess I'll just stick with the `ast` module and use `jedi.names` when I need type deduction.

**Comment by davidhalter** [comment]
>  I'm guessing that's what you are referring to?

I thought it was already public. I probably didn't make it public because of insufficient testing.
