### ISSUE TITLE
Memory Leak and Loop 

### ISSUE THREAD

**Issue by DonJayamanne** [davidhalter/jedi#923]
_From @ppanhoto78 on May 8, 2017 12:58_

The bug is described at:
https://github.com/Microsoft/vscode/issues/25796

With versions and steps to reproduce

Hello.

I was starting to write a small script with a swig library. Quickly, VSCode started to consume all memory and all swap memory until I had to reboot. I'm using VSCode 1.11.2 and OpenSuSE leap 42.1

Steps to Reproduce:

Install quickfix-python
$ sudo pip install quickfix

start a project

type the script bellow.

```
#!/usr/bin/env python
import quickfix

class ClientApplication(quickfix.Application):
	def __init__(self, server):
		super(ClientApplication, self).__init__()
```

in my case, when I trigger autocompletion within the module quickfix, that is enough to cause the loop.

Extensions:
C/C++ 0.11.0
C# 1.9.0
C++ Intellisense 0.2.1
Mono Debug 0.15.5
Python 0.6.3

_Copied from original issue: DonJayamanne/pythonVSCode#947_

**Comment by davidhalter** [comment]
Can you write that a simple Python script? Like

```
import jedi
jedi.Script('....').completions()
```
?

**Comment by davidhalter** [comment]
Oh and your Jedi release is 6 months old:
https://github.com/DonJayamanne/pythonVSCode/tree/master/pythonFiles/release/jedi

Please mention the version that you're currently using in the future. Jedi is changing quite a bit.

**Comment by DonJayamanne** [comment]
Oops

**Comment by davidhalter** [comment]
I just checked. It takes me a few seconds the first time to complete this. The reason is that quickfix is 1.8 MB of Python code (which is huge). This is not what the parser can handle in a reasonable time, it takes a bit more than 200 MB of RAM on my machine. Let me know if it's still an issue.
