### ISSUE TITLE
Jedi cache directory on Windows (AppData\Roaming)

### ISSUE THREAD

**Issue by gandhis1** [davidhalter/jedi#926]
The default jedi cache directory is the roaming folder. In my company, we have restrictions on the file size of the Roaming folder (since I believe these settings are synced across computers). The jedi cache really isn't a fundamental user setting that needs to be synced across devices, so it really should be in the local app data folder. So I propose here that the default windows path use the environment variable `%LocalAppData%` instead.

**Comment by davidhalter** [comment]
I have no idea about typical windows folders whatsoever. Any other opinions?

**Comment by gandhis1** [comment]
Here's an excerpt from stackoverflow (https://superuser.com/questions/21458/why-are-there-directories-called-local-locallow-and-roaming-under-users-user):

> Roaming is the folder that would be synchronized with a server if you logged into a domain with a roaming profile (enabling you to log into any computer in a domain and access your favorites, documents, etc. Firefox stores its information here, so you could even have the same bookmarks between computers with a roaming profile.
> 
> Local is the folder that is specific to that computer - any information here would not be synchronized with a server. This folder is equivalent in Windows XP to C:\Documents and Settings\User\Local Settings\Application Data.
> 
> LocalLow is the same folder as local, but it has a lower integrity level. Internet Explorer 8, for example, can only write to the locallow folder (when protected mode is on).

Based on this, I would think Local is the way to go.

**Comment by davidhalter** [comment]
Can you fix it in parso and create a pull request (jedi's future parser)? https://github.com/davidhalter/parso

**Comment by davidhalter** [comment]
This was changed.
