### ISSUE TITLE
jedi strange problem on Windows/Spyder/Jedi-0.10.2+

### ISSUE THREAD

**Issue by stonebig** [davidhalter/jedi#927]
hi,

On Windows, the spyder editor is creating several processes:
- one of them is for ipython console (using jedi)
- one of them is for the spyder editor (using also jedi).

The spyder editor auto-completion fails to work reliabily. 
Is there a possibility that two jedi processes compete for the same cache and create this strange problem ?

**Comment by davidhalter** [comment]
Good point. Yes there is a very small chance that this happens (I think). But I'm pretty sure that that wouldn't make it feel like it's not working reliably. It would probably just fail for one completion. Please define `fails to work reliabily`.

**Comment by stonebig** [comment]
Retry of the day, in a calm environment:
- jedi-0.10.2, Ipython-0.6.1, WinPython-3.5.3 ,Windows 10 PC, 4Go, spinning disk, Spyder-3.2.0.dev0 of may 25th,
- Spyder integrates jedi for auto-completion in its "editor", "ipython" console, "classic" console.
- on a "first cold boot after winpython installation":
  - there is 1 than 4 python processes, and they calm down in cpu after 5'15, during that time also the windows anti-malware is checking frenzy and slowing down by half, I suspect,
  - after these 5'15, "import num"<tab> then works well on "Ipython" console, "Classis" console, "Editor" window,
  - if I had type "import num"<tab> on the ipython console as it shows up all, would be fine,
  - if I had typed it on the spyder editor, wich appears 2' before slow down on cpu,  the completion wouldn't have shown up, and would never after a fail try, but now (on another cold boot), it seems to be ok.

So, today, I can't reproduce the "continuous failing" problem. maybe ipython-0.6.1 did fix something, as previous fails were noticed with ipython-5.3 or Ipython-6.0.

**Comment by davidhalter** [comment]
Thanks for the research!
