### ISSUE TITLE
Jedi doesn't autocomplete return and print

### ISSUE THREAD

**Issue by shrx** [davidhalter/jedi#928]
I am using [jedi-autocomplete](https://github.com/notetau/geany-jedi-complete) plugin for Geany.
I noticed that it doesn't offer completion for `print` and `return`:

![screenshot_print](https://cloud.githubusercontent.com/assets/810337/26675861/bb989df0-46c5-11e7-8c6e-419bc90d42dc.png)

![screenshot_return](https://cloud.githubusercontent.com/assets/810337/26675870/c678f198-46c5-11e7-9ca9-3f5dbeae07bb.png)

Is this a bug?

**Comment by davidhalter** [comment]
I cannot reproduce it (0.10.2):

```
>>> jedi.Script('pri').completions()
[<Completion: print>]
>>> jedi.Script('def f():\n ret').completions()
[<Completion: return>]
```
