### ISSUE TITLE
Jedi f-string completions

### ISSUE THREAD

**Issue by gopar** [davidhalter/jedi#930]
Will jedi support [f-strings](https://www.python.org/dev/peps/pep-0498/)?
Pretty much code completion within strings?

Thanks, awesome package :)

**Comment by davidhalter** [comment]
Good idea! :)

**Comment by gopar** [comment]
Out of curiosity, how hard would this be to implement? Might try to make it work it the entry level is not that high. No promises though :P

**Comment by davidhalter** [comment]
I think it's actually really easy. The only hard part is splitting up the string. You have to parse the string. Once you have done that it's probably very easy (something like a five liner). I could help you with the second part.

**Comment by BlacKCaT27** [comment]
Curious what the status is here. Turns out this could be related to a downstream issue I've opened for VS Code [here](https://github.com/Microsoft/vscode-python/issues/344#issuecomment-356131274). You can use my example there as a test for your update :)

**Comment by z3dm4n** [comment]
As of today, it seems there is no final solution regarding f-strings here. Correct me, if I'm wrong. f-strings are great performance-wise. Any fix would be highly appreciated. Thanks and keep up the great work.

**Comment by davidhalter** [comment]
f-string support should be done now. Please test. You have to use both latest jedi and parso master branch to use it until the 0.12.0 release which is going to happen very soon.
