### ISSUE TITLE
PEP 526 support for instance fields

### ISSUE THREAD

**Issue by maxnordlund** [davidhalter/jedi#933]
I noticed that while there's support for PEP 526 for variables (#821), there's not for instance fields. Is this possible to add without to much hassle?

```python
class Spam:
    arr: list

    def __init__(self, arr):
        self.arr = arr

    def foo(self):
        self.arr.<tab> # Does not autocomplete .append etc
        other: list
        other.<tab> # Does autocomplete like you would expect
```

**Comment by davidhalter** [comment]
It's probably not too complicated.

**Comment by davidhalter** [comment]
I feel like this is working very well now. Also ensured it with a few additional tests. Please let me know if there are still issues.
