### ISSUE TITLE
different completions for import and import-as

### ISSUE THREAD

**Issue by mbannister** [davidhalter/jedi#940]
I noticed a string bug(?) in completion when using the [pyglet](http://pyglet.org) library. I am not sure if this is a known issue, as it look similar to some other reported issues.

The following code examples will not find all completions.

```python
import pyglet
w = pyglet.window.
```

```python
from pyglet import window
w = window.
```

However, when rewritten slightly it works, as the next example shows.

```python
import pyglet.window as window
w = window.
```

The following test script passes all asserts on my system (details below).

```python
import jedi

source = 'import pyglet; w = pyglet.window.'
script = jedi.Script(source, 1, len(source))
completions = script.completions()
names1 = set(c.name for c in completions)

source = 'from pyglet import window; w = window.'
script = jedi.Script(source, 1, len(source))
completions = script.completions()
names2 = set(c.name for c in completions)

source = 'import pyglet.window as window; w = window.'
script = jedi.Script(source, 1, len(source))
completions = script.completions()
names3 = set(c.name for c in completions)

assert 'Window' not in names1
assert 'Window' not in names2
assert 'Window' in names3
```

The above script was tested on macOS 10.12.5 with python 3.6.1 being installed via anaconda. The versions the packages are:

- jedi: 0.10.2
- pyglet: 1.2.4

Please let me know if I can do anything else to help track down the source of the problem.

**Comment by davidhalter** [comment]
If you want you can enable debugging and play around with `evaluate/imports.py`. It's a bug, thanks for reporting and reproducing!

BTW you can omit the positions in your `Script` calls. They are the defaults.

**Comment by mbannister** [comment]
Sounds good. I will play with and see if I can figure anything out.

**Comment by davidhalter** [comment]
ping

**Comment by mbannister** [comment]
Sorry about the radio silence. I have not been using completion much in my workflow, so I sort of forgot about this. I don't expect to be able to work on this in the near future.

**Comment by davidhalter** [comment]
Can you just retry the code above and see if it still asserts? Jedi 0.11.0 fixed some import related stuff.

**Comment by mbannister** [comment]
Same problem with Jedi 0.11.0 and all other version unchanged.

**Comment by davidhalter** [comment]
I kind of understand Python's import system now. It's one of the things that was done in a pretty bad way IMO. The side effects of the import system are often poorly understood and a big problem for many people. In your case Jedi is actually right. It does the thing the terminal does if you restart it between trying these things:
import from:
```
Python 3.6.3 (default, Oct  6 2017, 08:44:35) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
REPL completion using Jedi 0.12.0
>>> from pyglet import window
>>> window
<pyglet._ModuleProxy object at 0x7f02ad427ac8>
```

Just pyglet:
```
Python 3.6.3 (default, Oct  6 2017, 08:44:35) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
REPL completion using Jedi 0.12.0
>>> import pyglet
>>> pyglet.window
<pyglet._ModuleProxy object at 0x7f8bb444fb00>
```

With as:
```
Python 3.6.3 (default, Oct  6 2017, 08:44:35) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
REPL completion using Jedi 0.12.0
>>> import pyglet.window as x
>>> x
<module 'pyglet.window' from '/home/dave/source/python/jedi_issues/940/venv/lib/python3.6/site-packages/pyglet/window/__init__.py'>
```

As you can see, the last example differs. This doesn't need to be the case. If you call the last example first, you will be able to see that the ModuleProxy will have been overwritten:

```
<module 'pyglet.window' from '/home/dave/source/python/jedi_issues/940/venv/lib/python3.6/site-packages/pyglet/window/__init__.py'>
>>> pyglet.window
<module 'pyglet.window' from '/home/dave/source/python/jedi_issues/940/venv/lib/python3.6/site-packages/pyglet/window/__init__.py'>
>>> window
<module 'pyglet.window' from '/home/dave/source/python/jedi_issues/940/venv/lib/python3.6/site-packages/pyglet/window/__init__.py'>
```

You can see the effects very nicely here:

```
>>> import pyglet
>>> x = pyglet.window
>>> import pyglet.window as w
>>> x == pyglet.window
False
```

The import as modifies the pyglet module - which is stupid IMO. It's implicit and very magical. For whatever reason we were not able to get rid of that in the Python 2 to 3 conversion. Maybe Python 5.

Whatever. I think jedi does the right thing here. I know it can be confusing, but that's really Python's import system beneath that behaves like a fourteen year old kid :)

**Comment by valignatev** [comment]
Stumble across this myself. It happens because `import as` bounds name to the pyglet's `_ModuleProxy` which triggers `__getattr__` under the cover and evaluates the module. What bugs me is that Pycharm somehow resolves completions and goto-definitions even without `import as`. Maybe it's because Pycharm not just follows imports but analyzes package structure? I don't know what dark magic it uses, but it's really convenient.

**Comment by valignatev** [comment]
Interesting, thanks! Yeah, I agree that "perfect" completions are not for Python, same as jumping to the definitions in some cases probably. But I can only imagine all the nasty black magic needed for such kind of fuzzy heuristics.

**Comment by balta2ar** [comment]
> I also checked pycharm's code base. There's nothing that in there that would treat pyglet as a special case (except for some debugger related code).

Is it Open Source? Could you please give a link to that piece of code?

**Comment by valignatev** [comment]
@balta2ar Sure, here's Pycharm Community Edition: https://github.com/JetBrains/intellij-community/tree/master/python
