### ISSUE TITLE
Quite weak with the force 

### ISSUE THREAD

**Issue by TomSchalld** [davidhalter/jedi#943]
Does neither support force push nor force choke.

**Comment by lennartblom** [comment]
Agreed! Don't know why this is not implemented already...

**Comment by davidhalter** [comment]
Hmm, I'm not sure if these features are what we need. To quote Yoda: "If once you start down the dark path, forever will it dominate your destiny, consume you it will, as it did Obi-Wan’s apprentice.”

We had our struggles ourselves. The fear was big among us when the emperor's pull request was made: https://github.com/davidhalter/jedi/pull/128.

**Comment by davidhalter** [comment]
Don't abuse the force.
