### ISSUE TITLE
jedi bug discovered by elpy

### ISSUE THREAD

**Issue by vograno** [davidhalter/jedi#944]
The owner of the elpy project asked me to submit this bug report to jedi development. Here is a reference to the original report
https://github.com/jorgenschaefer/elpy/issues/1153#issuecomment-315404505

**Comment by davidhalter** [comment]
Can you please retry this one? It looks like I have fixed something like this. Checkout the current master branch.

**Comment by davidhalter** [comment]
Since you haven't retried, I'll close for now.

I have added a commit to make it easier to debug this in the future. I'll reopen.
