### ISSUE TITLE
goto_assignments with follow_imports=True seems to go into decorators

### ISSUE THREAD

**Issue by mpoindexter** [davidhalter/jedi#945]
Jedi 0.10.3

Using goto_assignments with follow_imports=True on `foo` in code like the following seems to navigate to `@decorator`

```
@decorator()
def foo():
    pass

foo()
```

I debugged it, and in this case in `filter_follow_imports` in `jedi/api/__init__.py` the name is an instance of TreeNameDefinition and calling name.infer() gives the wrapper function.

I changed the code to look like this, and it seems to improve things, but I haven't looked at the Jedi code enough to know if this is the right approach

```
        def filter_follow_imports(names):
            for name in names:
                if isinstance(name, imports.ImportName):
                    for context in name.infer():
                        yield context.name
                elif isinstance(name, TreeNameDefinition) and name.tree_name.get_definition().type in ('import_name', 'import_from'):
                    for context in name.infer():
                        yield context.name
                else:
                    yield name
```

**Comment by davidhalter** [comment]
That is strange, I cannot reproduce this. Can you write this with actual Jedi calls so we can run the same code?

**Comment by mpoindexter** [comment]
```
import jedi
from jedi.api import Script


SCRIPT='''import functools

def example_decorator():
    def wrapper_factory(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            return 'Hello World'
        return wrapper
    return wrapper_factory

@example_decorator()
def foo():
    return 'Decorated'

def bar():
    foo()
'''

script = Script(SCRIPT, line=16, column=5)
print jedi.__version__
print repr(script.goto_assignments(follow_imports=True))
print repr(script.goto_assignments(follow_imports=False))
```

When I run this with python 2.7 I get the following output:
```
0.10.3
[<Definition def wrapper>]
[<Definition def foo>]
```

**Comment by mpoindexter** [comment]
The code above reproduces the problem, but I found an additional case where it doesn't work.  If the decorated function is imported, it will still jump to the decorator. Changing `filter_follow_imports` to this seems to fix both cases:

```
        def filter_follow_imports(names):
            for name in names:
                if isinstance(name, imports.ImportName):
                    for context in name.infer():
                        yield context.name
                elif isinstance(name, TreeNameDefinition) and name.tree_name.get_definition().type in ('import_name', 'import_from'):
                    for context in imports.infer_import(name.parent_context, name.tree_name, is_goto=True):
                        yield context
                else:
                    yield name
```

It seems like the ultimate problem is that a bunch of the code in the evaluator package needs to go down a is_goto=True path for this to work, but name.infer() doesn't pass that flag down.

**Comment by davidhalter** [comment]
I think I just fixed it in 4a544c29ea57fde519971c9c3fc0f1c7fd1262bc. It looks really a lot like this issue. As you rightfully suggested it was wrong to just match TreeNameDefinition. I just found that by accident and just wanted to tackle your issue now. So I guess it's fixed either way. Your fix would have worked as well, but I think mine is a bit more elegant.

If you could please test it quickly I would really welcome that.

**Comment by mpoindexter** [comment]
I'll take a look tonight and report back, thanks!

**Comment by mpoindexter** [comment]
Looks like it's halfway fixed.  The first case is fixed.  The second case (where the decorated function is imported) still doesn't work.  See https://gist.github.com/mpoindexter/d1bd39ef8bdb53d5ac90e225c15c6ed1 for an example.

**Comment by davidhalter** [comment]
Oh fuck. That was on my todo list (in my head). I knew that that wasn't actually working properly. Anyway, I'll fix it ASAP. Thanks for noticing.

**Comment by davidhalter** [comment]
Please check again. I think now it's finally working.

**Comment by mpoindexter** [comment]
Looks good, thanks!
