### ISSUE TITLE
How to auto complete with only pyd file but without .py file?

### ISSUE THREAD

**Issue by moyotar** [davidhalter/jedi#949]
Original problem [here](https://github.com/Valloric/ycmd/issues/806).  Similarly, about `.dll`?

**Comment by davidhalter** [comment]
dll's are not supported. There's no support for `ctypes.cdll`.

I'm not sure about pyd files. I don't own a Windows machine and it's therefore hard for me to tell if it works. Generally if it's on the sys.path it should works if it works in Python.

Is your `example.pyd` file on a normal path where you can also import other things from and does `import example` in Python work?

**Comment by moyotar** [comment]
Yeah! It supports `.pyd` files to auto complete but not for `.dll` files.

**Comment by davidhalter** [comment]
Can you post some code? Sorry this answer really doesn't tell me anything.

**Comment by moyotar** [comment]
@davidhalter Sorry for replying so late. 

![image](https://user-images.githubusercontent.com/22092607/29241233-3b4d70dc-7fa8-11e7-9493-6c8d62bf8523.png)


1.  For `.pyd` file. `Jedi `can provide its members

![image](https://user-images.githubusercontent.com/22092607/29241213-eb014540-7fa7-11e7-8395-9c1396e458e3.png)

2. For `.dll` file. `Jedi` can provide nothing about it.
![image](https://user-images.githubusercontent.com/22092607/29241278-e83a4ff4-7fa8-11e7-89d2-2a39524bc0f1.png)

**Comment by davidhalter** [comment]
As I said, CDLL is not supported at the moment. If you want support for it you might write the code for it.

I won't (don't even have windows) and I'm therefore closing.
