### ISSUE TITLE
Feature request: dict auto completion

### ISSUE THREAD

**Issue by thernstig** [davidhalter/jedi#951]
I was asked to re-create this ticket in Jedi when originally raising the request in pythonVSCode, please refer to: https://github.com/DonJayamanne/pythonVSCode/issues/1145

## Environment data
VS Code version: 1.14.2
Python Extension version: 0.7.0 (3 August 2017)
Python Version: 3.6.1
OS and version: Windows 10 Home, Version 1703, OS-version 15063.483

## Actual behavior
When pressing ctrl+space on a defined dict, no suggestions are shown for the keys in the dict.

## Expected  behavior
If I use a defined dict in my file I want it to suggest the keys to select automatically.

Here is an example of what I mean:

![dict_auto_complete](https://user-images.githubusercontent.com/30827238/29113653-f1b88b4a-7cf1-11e7-8f21-17a039343360.png)

**Comment by davidhalter** [comment]
Makes sense. Dict support is still very marginal in general, but this makes sense.

**Comment by davidhalter** [comment]
Dict support is definitely not marginal anymore. Dict completions should now work on master branch.
