### ISSUE TITLE
PEP484 support for CompiledObjects (strings)

### ISSUE THREAD

**Issue by rp-** [davidhalter/jedi#952]
Compiled python objects don't get ```__annotations__``` evaluated and so have no completion support for e.g. return types.

I tried to hack it in, but I couldn't really figure out how to parse the ```__annotations__``` string to a jedi.tree.PythonNode and correctly feed it to the pep0484 infer functions.
But what I understood from the code is, it should be possible, but I'm not sure how well it fits in the current design.

**Comment by davidhalter** [comment]
> but I'm not sure how well it fits in the current design.

Then maybe we have to refactor the current design. :)

---

Anyway good thoughts! I agree that we should make that possible. There might need to be a kind of different API, but that's fine. I think if you're doing this, just try to do it as clean as possible and if you're not sure how to add new abstractions, we can always discuss here.

**Comment by rp-** [comment]
Ok, sadly I'm lacking some knowledge of jedi code.
I can't really figure out how to create the prober PythonNodes that should go into the pep0484._evaluate_for_annotion function.
Right now I try to parse the ```__annotation__``` string from the CompiledObject and pass the result nodes to the pep0484.infer_return_types function, which doesn't really work.

**Comment by davidhalter** [comment]
I just today added support for `__annotations__['return']`. However it only works for types and not strings. Just be aware of that. (Change not included in 0.14.0)

Keeping this issue open to eventually add support for strings as well.

**Comment by davidhalter** [comment]
Works now with Python3.6+ on master branch.
