### ISSUE TITLE
Does jedi support PowerShell?

### ISSUE THREAD

**Issue by alphardex** [davidhalter/jedi#955]
``` powershell
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
REPL completion using Jedi 0.10.2
Jedi: Module readline not available.
```
When I use PowerShell with jedi, it shows the above message, and jedi won't work, either. Does it support PowerShell?

**Comment by davidhalter** [comment]
I never tested this and quite frankly I would be very surprised if this worked.

Sorry, there will probably not be support for PowerShell. If you want you can improve documentation about that.
