### ISSUE TITLE
Jedi cache 1.5G

### ISSUE THREAD

**Issue by alper** [davidhalter/jedi#957]
I've been looking around where my hard drive space went and to my surprise I find jedi has taken 1.5G of it (in ~/Library/Caches/Jedi).

Is there some kind of limit or reuse to the cache or is it supposed to take as much as it does?

**Comment by davidhalter** [comment]
There is currently no limit and I don't have plans to add one. Currently I'm just recommending people to delete the folder from time to time. If someone wants to delete files that are e.g. older than a month I'm happy to receive pull requests.

**Comment by syllogismos** [comment]
My ~/Library/Caches/Jedi folder is 9.56 GB and was wondering if I can delete it. Thanks for this, will be deleting it.

I use vscode for python dev and `python-mode` in vim, used to have `jedi-vim` in vim. I'm guessing vscode is the culprit here.

**Comment by schroef** [comment]
Why is this cache needed actually? I wonder why this is not set for a time limit. I mean the prior post had almost 10Gb of lost space?!?!

**Comment by davidhalter** [comment]
> Why is this cache needed actually?

It's needed to load modules quickly, without always reloading 

And for most people the cache just never grows that big. For example for me it's 3 GB at the moment, which I think is fine considering that I have worked with different Python versions and environments.

As I'm said, I'm happy to discuss pull requests. The patch is needed in parso and not in Jedi though. I just don't think this is pressing enough. I have hardly had any complaints over the years.
