### ISSUE TITLE
Dynamic check for VIRTUAL_ENV python version

### ISSUE THREAD

**Issue by davidhalter** [davidhalter/jedi#962]
#556 was closed because I deleted a branch. It was a pull request but some of the ideas were good. Good virtualenv support is hopefully coming soon.

**Comment by cmcginty** [comment]
Any update on VIRTUAL_ENV support?

**Comment by davidhalter** [comment]
Virtualenv support should be in a pretty good shape on master branch. The API is not 100% stable and some fixes are still needed. I guess one/two months is realistic. :)

**Comment by cmcginty** [comment]
I run the master branch but it doesn't seem to work. Maybe because I use pyenv to generate my virtualenv? Do you support that? https://github.com/pyenv/pyenv-virtualenv

**Comment by davidhalter** [comment]
https://github.com/davidhalter/jedi/issues/1053

@cmcginty I'm not sure. Pretty sure it supports it, but there might be a security check that it fails. You could tray to play with the latest API if you want to give me more feedback.
