### ISSUE TITLE
Autocompletion doesn't work properly with custom library (dataset)

### ISSUE THREAD

**Issue by esauvisky** [davidhalter/jedi#964]
_I'm a new user to Python, so I don't know exactly what I'm doing. Keep that in mind please :)_ 

I'm using Anaconda with Sublime Text 3 as my Python IDE.
As I understand, Anaconda uses jedi to find autocompletions for imported packages.

However, when trying the sample script of dataset:
        
    db = dataset.connect('sqlite:///ebay.db')
    table = db['searches']
    table.insert [...]
         ^ problem happens there`

After the dot, I get no autocompletion of _insert_ (or any other functions).
When I try it in the python console it works fine. 

I tried to debug it and narrowed down the problem to either _jedi_ or _dataset_.
_At Python console:_

    >>> from jedi import Script
    >>> print(Script('import dataset;dataset.table.').completions())

_Returns:_

    [<Completion: and_>, <Completion: ClauseElement>, <Completion: Column>, <Completion: DatasetException>, <Completion: ensure_tuple>, <Completion: expression>, <Completion: false>, <Completion: func>, <Completion: Index>, <Completion: index_name>, <Completion: log>, <Completion: logging>, <Completion: normalize_column_name>, <Completion: normalize_table_name>, <Completion: NoSuchTableError>, <Completion: QUERY_STEP>, <Completion: ResultIter>, <Completion: select>, <Completion: SQLATable>, <Completion: Table>, <Completion: threading>, <Completion: Types>, <Completion: warnings>, <Completion: __doc__>, <Completion: __file__>, <Completion: __name__>, <Completion: __package__>]

Note there is no `Completion: insert` there.

If I try listing the completions of *dataset.* though, it looks like its working:

    >>> from jedi import Script
    >>> print(Script('import dataset;dataset.').completions())

Returns:

    [<Completion: connect>, <Completion: Database>, <Completion: database>, <Completion: os>, <Completion: row_type>, <Completion: Table>, <Completion: table>, <Completion: types>, <Completion: util>, <Completion: warnings>, <Completion: __all__>, <Completion: __doc__>, <Completion: __file__>, <Completion: __name__>, <Completion: __package__>]

As you can see, `Completion: connect` is there, for example.

Am I missing anything? Am I doing something stupidly wrong? Sorry if this is completely trivial.

**Comment by davidhalter** [comment]
Ok. I've looked at dataset now. It's interesting: The problem is actually that in the module database.Database.create_table,  the cache is filled with tables. Jedi doesn't really understand how to deal with that dictionary (jedi generally is not good in handling writing to dictionaries).

Therefore completions are not possible. I don't see at the moment that we're fixing this. Writing to dictionaries is on my long term list, but will definitely still take some time.
