### ISSUE TITLE
calling completions() for python-pptx package raises RecursionError

### ISSUE THREAD

**Issue by toxeus** [davidhalter/jedi#966]
I've encountered this bug using Python 3.6.2, python-pptx 0.6.6 and jedi 0.11.0 on Linux. It can be reproduced with the following script (python-pptx needs to be installed).

```python
import jedi

print(jedi.Script("""
from pptx import Presentation
Presentation().""",
    3,
    len("Presentation()."),
    "example.py"
    ).completions())
```

I've also tested this against the master branch of jedi with the same result. If additional information is needed I'll happily provide it.

**Comment by davidhalter** [comment]
Can you please provide the traceback? I'm too lazy to always check this by hand (might be a bug that is already fixed).

**Comment by toxeus** [comment]
@davidhalter I've deliberately didn't include the traceback because it's more than a thousand lines long.

**Comment by davidhalter** [comment]
I didn't read the title, sorry. It's already clear that it's a RecursionError. If it wasn't the traceback would have been useful.

**Comment by davidhalter** [comment]
I have just fixed a RecursionError that was probably similar. Tested it with latest master and it works now. 

Thanks for the report!

**Comment by toxeus** [comment]
You're welcome. Thank you for this great tool :+1:
