### ISSUE TITLE
Exception on AC a comment

### ISSUE THREAD

**Issue by TobiasRzepka** [davidhalter/jedi#968]
Hello David,
at first thanks for the good work. Actually I was improving the jedi plugin for the eric6 IDE. Sadly I found a bug and like to share it ;-)
When auto-completing following example, I got the attached exception. Tried with 0.10.2, 0.11.0 and latest sourcen from git hub (tested on Win 10, output from 0.10.2):
`
> s = jedi.Script("max_attr_value = int(2)  # Cast to int for spe", 1, 46, "cmd")
> s.completions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jedi\api\__init__.py", line 179, in completions
    completions = completion.completions()
  File "jedi\api\completion.py", line 96, in completions
    completion_names = self._get_context_completions()
  File "jedi\api\completion.py", line 124, in _get_context_completions
    grammar, self._code_lines, self._module_node, self._position
  File "jedi\api\helpers.py", line 140, in get_stack_at_position
    raise SystemError("This really shouldn't happen. There's a bug in Jedi.")
SystemError: This really shouldn't happen. There's a bug in Jedi.`

Tobias

**Comment by TobiasRzepka** [comment]
My again. Found out, that a different "code line" makes the same exception (nice, only one bug report ;-):
`jedi.Script("0x0", 1, 2, "cmd").completions()`
It's important, to complete after the "x". Same if you replace the "x" with "b" but not with "o" for octal representation ("o" gives "or"). Other letters seems to be accepted, e.g. "a" gives "and".
Tobias

**Comment by davidhalter** [comment]
Thanks for finding this! I can reproduce it.

**Comment by davidhalter** [comment]
Thank you again for the good report. It's really easy to solve these if I have a reproduction case :)

**Comment by TobiasRzepka** [comment]
Hi, I've checked on it because I always get the trace even with the latest jedi / parso combination from GIT (I've just to adjust the column position):
``` 
>>> s = jedi.Script("max_attr_value = int(2) # Cast to int for spe", 1, 45, "cmd")
>>> s.completions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jedi\api\__init__.py", line 162, in completions
    completions = completion.completions()
  File "jedi\api\completion.py", line 99, in completions
    completion_names = self._get_context_completions()
  File "jedi\api\completion.py", line 127, in _get_context_completions
    grammar, self._code_lines, self._module_node, self._position
  File "jedi\api\helpers.py", line 144, in get_stack_at_position
    raise SystemError("This really shouldn't happen. There's a bug in Jedi.")
SystemError: This really shouldn't happen. There's a bug in Jedi.
``` 
The second one with 0x0 seems to be fixed.

**Comment by davidhalter** [comment]
Thanks for re-checking and sorry for being sloppy and checking the first example as well. I'm on it.
