### ISSUE TITLE
PEP 526 - Ahead of time annotations

### ISSUE THREAD

**Issue by InfernoZeus** [davidhalter/jedi#974]
It seems that jedi doesn't properly support PEP 526 annotations when they're used ahead of time. This example should demonstrate the problem:

```python
    test_string: str = "Hello, world!"
    test_string.<tab> # Completes as you would expect: .capitalize, etc

    char: str
    for char in test_string:
        char.<tab> # Does not complete properly
```

I suspect it's closely related to #933.

Relevant section of PEP 526:

> Only single assignment targets and single right hand side values are allowed. In addition, one cannot annotate variables used in a for or with statement; they can be annotated ahead of time, in a similar manner to tuple unpacking:
>```python
>a: int
>for a in my_iter:
>    ...
>
>f: MyFile
>with myfunc() as f:
>    ...
>```

**Comment by davidhalter** [comment]
I'm pretty sure we don't support this use case, yet.

**Comment by johannesmik** [comment]
Your testcase worked for me, when I tested it with Jedi 0.11 and Python 3.5:

```
import jedi

source = """
teststring = "Hello, World!"
char : str
for char in teststring:
    char."""

jedi_script = jedi.Script(source=source)
print("Completions:", jedi_script.completions())
print("Jedi Version:", jedi.__version__)
```
 got the following output:

```
Completions: [<Completion: capitalize>, <Completion: casefold>, <Completion: center>, <Completion: count>, <Completion: encode>, ....... ]
Jedi Version: 0.11.0
```

I also got it working with Vim and YouCompleteMe (Ycm), after updating Ycm.

**Comment by johannesmik** [comment]
Yet, it looks like that Jedi is ignoring the "ahead of time annotation", and tries to infer the type in a different way.

For example:
```python
somelist = [1, 2, 3, "A", "A"]

element : int
for element in somelist[0:3]:
    element.<TAB> # Gives both int and string suggestions (bit_length, capitalize, ...)
```

**Comment by davidhalter** [comment]
We were discussing this issue at the pycon.de sprints and I guess @johannesmik and me figured out what the problem was. There's a pull request incoming.

**Comment by InfernoZeus** [comment]
@davidhalter @johannesmik Thanks to both of you! Really impressed by the quick fix 😃

**Comment by davidhalter** [comment]
Now you might be less impressed on how long it took to merge the request. I'm still trying to cleanup some things. Not really sure it works already.

**Comment by davidhalter** [comment]
Everything should be set. I refactored the tests a bit for a couple of reasons.

If you want you can already check it and tell me if some things are still broken. Classes are not supported yet, that's part of #933.
