### ISSUE TITLE
can not import NotFoundError

### ISSUE THREAD

**Issue by iromise** [davidhalter/jedi#979]
When I use it in spacemacs(with emacs 25), but it just give me 

    from jedi import Script, NotFoundError
ImportError: cannot import name NotFoundError

And when I choose to install version 0.10.2, it is ok.

**Comment by davidhalter** [comment]
I have no idea which jedi plugin you are using. Talk to them. NotFoundError was deprecated a few years ago and has been removed in 0.11.0.

**Comment by iromise** [comment]
Thanks a lot.

**Comment by ycz0926** [comment]
i use the jedi with emacs, also meet this problem, is there any method to fix it?

**Comment by davidhalter** [comment]
They need to not import NotFoundError in their emacs plugin.
