### ISSUE TITLE
Wrong completion for arbitrary argument lists

### ISSUE THREAD

**Issue by Victor-Savu** [davidhalter/jedi#980]
Accroding to [PEP-484](https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values), for the following function declaration:
```python
def foo(*args: str, **kwds: int):
```
> In the body of function foo, the type of variable args is deduced as Tuple[str, ...] and the type of variable kwds is Dict[str, int].

I am afraid jedi suggests completions for `args` as if its type were `str`:
![args](https://user-images.githubusercontent.com/2445711/32145388-f84eb90a-bcc7-11e7-8a4e-caa8c076c566.png)
 and for `kwds` as if its type were `int`:
![kwds](https://user-images.githubusercontent.com/2445711/32145390-f8766a40-bcc7-11e7-96e9-9f538136fc49.png)

The examples are from my `IPython 6.2.1` running `Python 3.6.3` and `jedi==0.11.0`. I observed this behavior when I was using the `deoplete-jedi` plugin in NeoVim, but I just wanted to provide a simpler reproduction.

**Comment by Victor-Savu** [comment]
I would like to contribute to fixing this issue and I'd be happy if I got some mentoring as I work towards a PR.

**Comment by davidhalter** [comment]
Well, it shouldn't be extremely hard, but it's probably also not extremely easy ;)

Basically most of that stuff is going to be part of the `pep0484.py` module and you can just inject it there. That's at least what I think, even though I'm not 100% sure. Try to print a few things there and ask me again what the issues are.

Sorry I had an answer prepared for this question, but then forgot about it again.

**Comment by Victor-Savu** [comment]
@davidhalter thanks for the advice! I'll try what you suggested and will probably come back with some questions or a PR.

**Comment by davidhalter** [comment]
Should be working now, thanks for the report!
