### ISSUE TITLE
Support all async constructs of python 3.6

### ISSUE THREAD

**Issue by robinro** [davidhalter/jedi#985]
So far not (fully) working:
* [ ] async generators:
```
async def foo():
    yield 1
    await asyncio.sleep(0)
    yield 2
```
  * `foo()` should be async-generator
  * `for x in foo()` should give NO generator
  * `async for x in foo()`: should make x an int
  * ensure support for `asend`, see [PEP 525](https://www.python.org/dev/peps/pep-0525/#asynchronous-generator-object)
* [ ] async comprehension (list, set, dict, generator) `[x async for x in foo()]`
* [ ] `async with` context managers

Maybe more, see [PEP 492](https://www.python.org/dev/peps/pep-0492/)

**Comment by robinro** [comment]
First step: #986.
I will probably look into getting more of this done, but I'm also happy if someone else implements it :)

**Comment by davidhalter** [comment]
Thanks for your work again. I think I've gotten all of the remaining constructs working. Please test and let me know if there's still issues. It's on master.
