### ISSUE TITLE
Use `types` instead of SPECIAL_OBJECTS

### ISSUE THREAD

**Issue by robinro** [davidhalter/jedi#988]
As @davidhalter pointed out offline, the stdlib provides a nice collection of types like async*, generators, ...
Use those instead of the current SPECIAL_OBJECTS variable.

**Comment by davidhalter** [comment]
It's actually a good idea to use them generally. We just have to check if the types are also available in 2.6.

**Comment by davidhalter** [comment]
I tried to follow your advice in the virtualenv branch. It's done, now :)
