### ISSUE TITLE
If inside a file the same name as a package importing, go to declaration may not work

### ISSUE THREAD

**Issue by tony** [davidhalter/jedi#991]
jedi-vim + jedi v0.11.0

# Example

## Environment

- python 3.6
- vim 8.0
- jedi-vim  https://github.com/davidhalter/jedi-vim/commit/77924398bd594e238766153cec97ace62650f082
- jedi https://github.com/davidhalter/jedi/tree/v0.11.0

## instructions to reproduce

- ``mkdir test``
- ``cd test``
- `virtualenv .venv`
- `. .venv/bin/activate`
- ``pip install pygments==2.2.0``

## Code

Filename: *test/pygments.py*

```python
from pygments import highlight
from pygments.formatters import HtmlFormatter
from pygments.lexers import TextLexer, get_lexer_by_name
```

Go to assignments on ``pygments`` itself will go to top of file

Can't find declaration for any of the packages/modules/imports

Rename to *test/foo.py*. Declarations work.

Except for *HtmlFormatter* and *TextLexer*, see #992.

**Comment by davidhalter** [comment]
This is probably actually a jedi-vim bug. I'm pretty sure I've seen this bug before and fixed it a few weeks ago. But it's probably in a branch (jedi-vim usages branch). You might need to wait a few days until that is upstream and then try again.

**Comment by davidhalter** [comment]
It works at the moment. However I'm not even sure this is good. This doesn't need to work, because it doesn't work for Python directly either, see:

```
$ python3 pygments.py 
Traceback (most recent call last):
  File "pygments.py", line 1, in <module>
    from pygments import highlight
  File "/home/dave/source/python/jedi_issues/991/pygments.py", line 1, in <module>
    from pygments import highlight
ImportError: cannot import name 'highlight'
```

Either use packages and then a file in there named `pygments` or don't use pygments at all. As soon as you're using that name you're essentially overwriting the name in the global namespace.
