### ISSUE TITLE
Accept column indexes greater than the length of lines

### ISSUE THREAD

**Issue by w0rp** [davidhalter/jedi#999]
See the related issue raised for python-language-server: https://github.com/palantir/python-language-server/issues/193

`jedi` prevents completion requests from being issued for column indexes greater than the length of a line.

```python
        if not (0 <= column <= line_len):
            raise ValueError('`column` parameter is not in a valid range.')
```

This validation makes it hard for python-language-server to implement the Language Server Protocol correctly, which states that column positions greater than the length of a line must be treated as if the line length was given instead. I recommend checking if the `column` value is `>= 0`, and using `column = min(column, line_len)` instead.

This kind of problem is common in Vim where the cursor rests on the end of word, like a column position of `4` for a cursor at the end of a line with `abc` like `abc|`. Other language servers for other languages might use that information to differentiate between `ab|c` and `abc|`.

**Comment by davidhalter** [comment]
This has nothing to do with VIM. It's simply a question of how strict you want to be with input.

I struggle to see why you would exactly want this behavior in jedi. In general it's actually good to have something that raises errors in certain error cases.

If you really just must comply with the language server protocol. I advice to create a function in front that does exactly that. It should check if the column is bigger and react in that case.

To me this looks like a very bad idea and at the moment I don't see myself at all changing the API for this.

**Comment by w0rp** [comment]
You make using your API harder by performing this validation, for no discernible benefit. You can do what you like.

**Comment by davidhalter** [comment]
It's not harder to use. It's just more correct to use. This is like using mysql when you could be using postgresql. Of course it's a bit harder to use. But you don't end up having weird shit in your database.

**Comment by bs** [comment]
I'm experiencing the same. Tricky to reproduce because it's sporadic, happening roughly 20% of the time when adding certain characters at the end of a line, specifically ```,<space>``` (note the space) ... just typing ```,``` repeatedly does not trigger. 

Throws:

```
[coc.nvim] Jedi error: Traceback (most recent call last):
  File "completion.py", line 670, in watch
    response = self._process_request(rq)
  File "completion.py", line 640, in _process_request
    return self._serialize_arguments(script, line, column, request["id"])
  File "completion.py", line 309, in _serialize_arguments
    "results": self._get_call_signatures_with_args(script, line, column),
  File "completion.py", line 148, in _get_call_signatures_with_args
    call_signatures = script.get_signatures(line, column)
  File "/Users/britt/opt/anaconda3/lib/python3.7/site-packages/jedi/api/helpers.py", line 464, in wrapper
    column, line_len, line, line_string))
ValueError: `column` parameter (103) is not in a valid range (0-102) for line 65
```

**Comment by mstuehn** [comment]
> This has nothing to do with VIM. It's simply a question of how strict you want to be with input.
> 
> I struggle to see why you would exactly want this behavior in jedi. In general it's actually good to have something that raises errors in certain error cases.
> 
> If you really just must comply with the language server protocol. I advice to create a function in front that does exactly that. It should check if the column is bigger and react in that case.
> 
> To me this looks like a very bad idea and at the moment I don't see myself at all changing the API for this.

Hi,
i'm using neovim with the setting
virtualedit=all
which enables the cursor to be at any column regardless of the last character of the line. This does trigger the problem of this issue very reliably. When i apply the fix mentioned in this thread, the problem goes away.

Is there a chance, that this patch gets imported into main?

**Comment by davidhalter** [comment]
Oh interesting, I did not know that!

I think this should be fixed within Jedi. Language servers hit this problem as well. Feel free to report it in the Jedi issue tracker (and potentially fix it as well, although it's not that easy).
